### ISSUE TITLE
Password validator requires a user?

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Identity#1002]
Why this methods requires a User to be passed by? 
https://github.com/aspnet/Identity/blob/5480aa182bad3fb3b729a0169d0462873331e306/src/Microsoft.AspNetCore.Identity/PasswordValidator.cs#L39-L75

I want to check if password "123" is valid for my option rules, but the method asking for a user (and not using it apparently) got me wondering. :)

**Comment by brockallen** [comment]
What if you need to check a password history list?

**Comment by Bartmax** [comment]
So it's there in case someone implementation needs to know the user then?

**Comment by brockallen** [comment]
Yes, that's why it's passed, right?

**Comment by Bartmax** [comment]
> What if you need to check a password history list?

i just hope *check a password history list* isn't still a thing in 2016 ;)

**Comment by brockallen** [comment]
Well, that's just one example. Perhaps per-user settings? Could be anything, I suppose.

**Comment by blowdart** [comment]
It's an extensibility point. You don't have to use it. Brock wanted it for password history.
