### ISSUE TITLE
ChangePasswordAsync invalidates authorization cookies?

### ISSUE THREAD

**Issue by breyed** [aspnet/Identity#1004]
The documentation for [ChangePasswordAsync](https://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/AspNetCore/Identity/UserManager-TUser/#meth-Microsoft.AspNetCore.Identity.UserManager<TUser>.ChangePasswordAsync) doesn't say whether it invalidates cookies held by other browsers, thus forcing those browsers would need to sign in again. It seems like this would be a good thing; otherwise, there wouldn't appear to be any way for a user to deauthorize other devices using the identity code shipped with the ASP.NET Core C# template.

A similar question exists for authorization cookies established via OAuth after the OAuth relationship has been revoked.

It would be good to ensure that the template code offers the user a means to deauthorize devices and that the portions of the identity API that it uses document this security feature.

**Comment by blowdart** [comment]
It does it automatically. It's not immediate, we check validity every 30 minutes by default.

**Comment by breyed** [comment]
Good to hear. The documentation for `ChangePasswordAsync` should describe or link to the invalidation design to make it more discoverable.
