### ISSUE TITLE
Race conditions in EntityFramework UserManager

### ISSUE THREAD

**Issue by eliassorensen** [aspnet/Identity#1008]
I think it is a huge problem that the `UserManager` uses a context it gets injected in the constructor. 
It leads to several race conditions if two requests that are using the UserManager happens at the same time. 

With more and more users/requests, I often see it failing because of the `InvalidOperationException` the context throws ("InvalidOperationException: An operation is already in progress.").

EF `DbContext` is not thread-safe, and it should never be shared.

Instead, every time it is used (within each method), we should create a new instance of the context for this thread (via using, since the context is disposable).

What are your thoughts about this? It's a serious issue that Identity is not thread-safe.

**Comment by Ketrex** [comment]
Each user's HttpContext has it's own thread and the default Identity DI implementation creates a UserManager and DbContext that are scoped to that thread. I have never run into a problem with thread safety under this scenario, so I'm curious how your application is configured. Do you have a sample repository that demonstrates your implementation?

**Comment by eliassorensen** [comment]
I will create a sample that recreates the issue and return back.

**Comment by HaoK** [comment]
By default user managers are not shared across requests, because as you discovered they are not thread safe.
