### ISSUE TITLE
Renaming Login action prevents antiforgery cookie from being created.

### ISSUE THREAD

**Issue by Ketrex** [aspnet/Identity#1014]
I modeled my project after the sample in the Identity repo. My application worked fine with version 1.0.0 but after upgrading to 1.1.0, I ran into this issue.

I renamed the "Account/Login" action to "Account/SignIn" simply because I prefer the term "SignIn" as opposed to "Login." I've been updating this project from RC1 to RC2 to 1.0 with no problems but when I upgraded to 1.1 preview recently, external authentication would no longer function via the "SignIn" action.

The server returned a 400 response and logged the following error in the console: `RequestId:0HL01QQLRKLAO RequestPath:/account/externallogin/ => IdentityTest.Ui.Controllers.AccountController.ExternalLogin (IdentityTest.Ui)
      Antiforgery token validation failed. The required antiforgery cookie ".AspNetCore.Antiforgery.zAXjNzH62J0" is not present.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery cookie ".AspNetCore.Antiforgery.zAXjNzH62J0" is not present.`

While examining in Fiddler, it was clear that the "SignIn" page was not sending the antiforgery cookie along with the POST to the ExternalLogin method. Oddly enough, the manual email address and password form on the "SignIn" page worked just fine and did pass the antiforgery cookie along.

After some investigating, I decided to rename the "SignIn" action back to "Login" and all of a sudden, external auth worked again and indeed the antiforgery cookie was being created and passed.

It seemed silly that simply renaming the action would fix the problem so I re-renamed my controller action to "SignIn." Initially it worked, but upon closing the brower window and re-opening, it was failing again.

Finally, I created both a "Login" AND a "SignIn" action with the same method body and signature.

When I launched a fresh browser window and navigated directly to the "SignIn" action and tried to authenticate externally, the error would occur. Oddly if I just simply visited  the "Login" page, but didn't even attempt to authenticate, and then manually went to the SignIn page, it worked correctly.

It appears the antiforgery cookie is only set for external logins by visiting an action specifically named "Login" before attempting to call the ExternalLogin method.

Perhaps this is by design, it just seems odd that the behavior has changed in this way.

I was able to replicate this issue in the Identity sample project by simply adding this action to the account Controller and visiting it without visiting the Login action first:

    // GET: /Account/Login
    [HttpGet]
    [AllowAnonymous]
    public IActionResult Signin(string returnUrl = null)
    {
        ViewData["ReturnUrl"] = returnUrl;
        return View("Login");
    }

**Comment by HaoK** [comment]
I don't have too much familiarity with what changed here, but this SO question might explain why you can't see how the antiforgery is being configured: http://stackoverflow.com/questions/30959972/html-antiforgerytoken-still-required

If you have more questions you should try in the https://github.com/aspnet/AntiForgery repo
