### ISSUE TITLE
When updating the security stamp, tokens for confirm email is invalid

### ISSUE THREAD

**Issue by gdoron** [aspnet/Identity#1017]
I'm not sure if this is by design or not, but I think it's broken.
We had a user which created a new account, got an email from the system to confirm his email address.

Then he logged out, asking to log out from all devices, so we needed to use `UpdateSecurityStampAsync` and then he tried to confirm his email address which failed because the security stamp has changed.

Something in the framework IMHO needs to be changed to support this (not bizarre) scenario.

**Comment by HaoK** [comment]
This behavior is currently by design, whenever the security stamp is invalidated, the default email token provider generates tokens with the security stamp embedded for verification.  Log out everywhere invalidates all security tokens associated with the account, including confirmation/forgot password/etc.

Any concerns with this @blowdart ?

**Comment by gdoron** [comment]
It obviously makes sense.
But I think there should be a way of not invalidating email tokens, probably should be an opt-in and not the default behavior.

**Comment by HaoK** [comment]
You can always implement your own email token provider that does not use the security stamp as part of its validation.

**Comment by blowdart** [comment]
The other approach is to set RequireConfirmedEmail to be true. Or they just request another password reset and the stamp will be regenerated and finally work.

It's weird, but it is secure :) As you can do it yourself and it's by design, I'm going to close this as wontfix.

**Comment by gdoron** [comment]
@blowdart I didn't understand what you meant by.

> The other approach is to set RequireConfirmedEmail to be true.

**Comment by HaoK** [comment]
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SignInOptions.cs#L15

**Comment by HaoK** [comment]
Basically, if you require users to have confirmed emails before allowing them to log in, that would mitigate the issue somewhat.

**Comment by gdoron** [comment]
@HaoK That's a no go for us (and most applications I know to be honest).
Anyway, any chance you will consider adding a flag for the EmailTokenProvider in the future into the framework in the future?
