### ISSUE TITLE
Simultaneous login control

### ISSUE THREAD

**Issue by pushist1y** [aspnet/Identity#1019]
Our system requires possibility to restrict user from logging in simultaneously from different browsers. Currently Identity does not support such restrictions. 

Currently I've implemented this by inheriting from SignInManager and adding another entity describing logged in users. 

Should I try to implement this inside Identity codes and PR it here or is this functionality not wanted in this repository?

**Comment by blowdart** [comment]
This isn't a common enough scenario for us to pull it into the main code, but thank you for the offer.
