### ISSUE TITLE
No foreign key constraint on custom AspNetUserTokens

### ISSUE THREAD

**Issue by perf2711** [aspnet/Identity#1023]
### Functional impact
No functionality from foreign key in database in table `AspNetUserTokens` and `AspNetUsers`.

### Minimal repro steps
1. Create new Code-First model with Identity
2. Create custom models with custom key, I used `System.Guid`
3. Create a migration, and deploy it to SQL Server

### Expected result
The table `AspNetUserTokens` should have a foreign key constraint to table `AspNetUsers`.

### Actual result
The table `AspnetUserTokens` is not related at all in database to table `AspNetUsers`.
### Further technical details
The database is implemented in class project file, which is referenced by the ASP.NET project. All migrations were made through the ASP.NET project.
![ssms_2016-11-09_12-41-21](https://cloud.githubusercontent.com/assets/9085864/20137504/25735e90-a67b-11e6-9dab-8a2b495b80c7.png)
_Screenshot from SQL Server database diagram_
The tables were renamed through `OnModelCreating` override. Derived classes has no additional code at all, apart from `User`, which has several fields and navigation properties added. This should not impact the issue at all, however.

I'm using Windows 10 x64 with SQL Server Express 2014. IDE is VS 2015 Enterprise Update 3.
Project.json file for database class project:
```
{
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNetCore.Identity": "1.1.0-preview2-22681",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0-preview2-22681",
    "Microsoft.EntityFrameworkCore": "1.1.0-preview2-22681",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0-preview2-22681",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-22681",
    "NETStandard.Library": "1.6.1"
  },

  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    }
  }
}
```
Project.json file for ASP.NET project:
```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.1.0-preview2-22681",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "CoreTests.Database": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0-preview2-22681",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-22681",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0-preview2-22681",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0-preview2-22675"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

**Comment by HaoK** [comment]
After discussing with @divega since this is how things were in 1.0.0, we'll make this change as part of 1.2 where we have more time and the ability to update the initial migration included in the templates at the same time.

I'll make this change as soon as the 1.2 branch is open as its an easy fix

**Comment by HaoK** [comment]
57a25d080d1d0337b3b2dd8a2906f74a6e94370c
