### ISSUE TITLE
GetUserAsync inconsistent result

### ISSUE THREAD

**Issue by mcgiany** [aspnet/Identity#1024]
I have class for User that extends IdentityUser.
It contains bool property IsEnabled.
In Database i have column IsEnabled with value 1. When i changed this value to 0 while i'm logged in and then i use UserManagers method FindByIdAsync in controller it returns me user from database as is, and IsEnabled property is False. This is correct.
But, when i call the same method with same parameters in the middleware, property IsEnabled is always true. Looks like the manager returns user from cache. Changes are affected when i re-run the solution.
Why this happens in middleware? How to change the behavior?

Invoke method from my middleware contains something like this:
user and dbUser - both have IsEnabled = true. In database is 0.
```
MyUser user = await _userManager.GetUserAsync(httpContext.User);
MyUser dbUser = null;
if (user != null)
{
dbUser = await _userManager.FindByIdAsync(user.Id.ToString());
}

**Comment by blowdart** [comment]
We need a more detailed repo I'm afraid. Any change you can strip everything down to demo this, and also include the middleware, then tag myself and @HaoK

**Comment by HaoK** [comment]
It looks like you are probably capturing the UserManager in your middleware which results in that capturing the first request's db context which is why you are seeing old data.  For this to work, you will need to service locate (`context.RequestServices.GetService<UserManager<TUser>>()`) try that to see if that helps

**Comment by mcgiany** [comment]
@HaoK was right, Using described solution helps. Thx again.
