### ISSUE TITLE
UserManager: adding and overriding password-related functions.

### ISSUE THREAD

**Issue by pushist1y** [aspnet/Identity#1029]
There are several password-related functions in the UserManager class: `ChangePasswordAsync`, `RemovePasswordAsync`, `AddPasswordAsync`.

They are marked as `virtual` so they are considered as a subject to override, but all of them rely on the private function `UpdatePasswordHash` which is not accessible in descendant classes. If you want to override one of that functions you will have to copy-paste (or implement yourself) codes accessing validators and hasher. 

Also there is no function for administrative change of the password for user. And if you want to implement it, you'll also have to copy-paste. I see that you can Remove and then Add password, but both of this operations trigger mandatory database update which makes it hard to make batch changes for single user (i.e. changing administratively several fields in with single update). 

I suggest to make `UpdatePasswordHash` function proctected and therefore accessible in the descendant classes which will enable all of this without excessive copy-pasting and redundant database operations.

**Comment by HaoK** [comment]
I'm not a huge fan of making UpdatePasswordHash protected, I'd rather just add a public SetPasswordAsync method which effectively does the same thing but in a cleaner way.  

Since AddPassword/RemovePassword exist already, its not like we are exposing anything new...

Thoughts @blowdart @divega

**Comment by divega** [comment]
@HaoK as long as the new method is invoked in all the places where currently we are using `UpdatePasswordHash` I think it should address @pushist1y's scenario. Agree?

**Comment by pushist1y** [comment]
@divega it's ok as long as it does not forcefully invoke database update - so you can make multiple changes to a user and batch them into single update.

**Comment by HaoK** [comment]
Fixed via https://github.com/aspnet/Identity/pull/1348/files#diff-e4eb25d41ae824584d1c4c8a9b91a7e4R2321

UpdatePasswordHash protected
