### ISSUE TITLE
New AspNetUserTokens Table Column Width Issues

### ISSUE THREAD

**Issue by eriksendc** [aspnet/Identity#1030]
Hi All,

My team is just wrapping up migrating from RC1 to RTM. There's now a table called AspNetUserTokens that is being created. Here's the DDL for the table as it was created auto-magically for us:

    CREATE TABLE [dbo].[AspNetUserTokens] (
        [UserId]        NVARCHAR (450) NOT NULL,
        [LoginProvider] NVARCHAR (450) NOT NULL,
        [Name]          NVARCHAR (450) NOT NULL,
        [Value]         NVARCHAR (MAX) NULL,
        CONSTRAINT [PK_AspNetUserTokens] PRIMARY KEY CLUSTERED ([UserId] ASC, [LoginProvider] ASC, [Name] ASC)
    );

When testing the delta script for going to production I got this warning in SQL Server Management Studio:

`Warning! The maximum key length is 900 bytes. The index 'PK_AspNetUserTokens' has maximum length of 2700 bytes. For some combination of large values, the insert/update operation will fail.`

Why are the lengths of the columns so large? It would seem that making `UserId`  be `NVARCHAR(36)` would be fine, given that it's 36 everywhere else. I see the length of `LoginProvider` matches the length of that column in `AspNetUserLogins`, but isn't 450 unnecessarily large? In practice the values are `Google` and `Facebook`, etc. Maybe the same is true of the `Name` column as well. Finally, using `NVARCHAR(MAX)` (using any column type with the length `MAX`) causes the database engine to have to determin if the length of the actual piece of data being stored for a particular row should be stored in the data page itself or outside of the data page. There is an unnecessary performance hit for using `NVARCHAR(MAX)` if the token's value will be something <= 4000 in practice. Why not put the value into `NVARCHAR(#)`, where # is the largest expected size of the token's value (again, if it is less than 4000 in practice).

For now we'll use the table as-is, but wanted to bubble up these thoughts for discussion.

Thanks!
-Brian Eriksen

**Comment by eriksendc** [comment]
By the way, we're not finding that data is ever insterted into AspNetUserTokens. What is it used for?

**Comment by HaoK** [comment]
Its only populated if you call SetAuthenticationToken, its used if you want to carry over any tokens like an OAuth access/refresh token https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserManager.cs#L2045
