### ISSUE TITLE
Project Mirosoft.AspNetCore.Identity does not contain an entry point and cannot be started directly.

### ISSUE THREAD

**Issue by yang929886709** [aspnet/Identity#1032]
Project Mirosoft.AspNetCore.Identity does not contain an entry point and cannot be started directly.

In order to debug this project,"emitEntryPoint":true needs to be added to the buildOptions in project.json and entry point added to your project.Alternatively,add an executable project to this solution which references this project and set that as the startup project.

How to make these code run directly?

**Comment by davidfowl** [comment]
Not sure what you are trying to do. Why are you trying to run the library?
