### ISSUE TITLE
Async methods and CancellationTokens

### ISSUE THREAD

**Issue by gravity00** [aspnet/Identity#1034]
At the present moment, most classes with async methods to not provide a way to pass `CancellationToken` instances (examples: `SignInManager.SignOutAsync()` or `UserManager.FindByIdAsync(id)`). Underline, some of this methods are implicitly using the `CancellationToken` from the current `HttpContext`, like the `UserManager` class.

With this in mind, here are some concerns that come to my mind:

1. I'm not passing a `CancellationToken`, yet, my async flow can be canceled even if I don't want it to be;
2. Classes like `UserManager` have no reason to be tied to ASP.NET Core and this implementation clearly makes it;
3. Using part of this library outside the scope of an ASP.NET Core application makes it impossible to use other `CancellationToken` besides the `HttpRequest.RequestAborted`. Example: imagine a CQRS application were you want to use the token provided by the bus;

Here are my suggestions:

- No breaking changes - add overloads that use the given `CancellationToken` instead of the internal one;
- Breaking change - remove the dependency on `HttpContext.RequestAborted` and only use provided `CancellationToken`;
- For consistency, all methods should have a token overload, even if the implementation does not require (example: `SignInManager.SignOutAsync()`)

**Comment by HaoK** [comment]
Would something like just making the CancellationToken property public and settable be sufficient for your @gravity00?  It would default to RequestAborted in general (if available), but it would use whatever the property was set to in general.

**Comment by gravity00** [comment]
This is far from the choice I would made but I understand that, with the current implementation, using a token parameter would be a major rework for you guys, so it is better than nothing.

Still, I must admit the usage is kinda quirky, specially when using DI:

```csharp
public class ExampleClass
{
    private readonly UserManager<IdentityUser> _userManager;

    public ExampleClass(UserManager<IdentityUser> userManager){
        _userManager = userManager;
    }

    public async Task DoSomethingAsync(CancellationToken ct){
        _userManager.CancellationToken = ct;

        //	do stuff
    }
}
```

**Comment by sirajmansour** [comment]
Are there any plans to support this ?
