### ISSUE TITLE
Adding new IdentityRole without NormalizedName fails subsequent lookups

### ISSUE THREAD

**Issue by leedjones** [aspnet/Identity#1037]
I recently [hit an issue](http://stackoverflow.com/questions/40765178/addtoroleasync-fails-to-find-role/40780886#40780886) whereby adding a new role to the system using the single parameter constructor:

`_context.Roles.Add(new IdentityRole(“SYSADMIN”));`

Would insert the record into the DB, but subsequent calls to look up this role, either by:

`_roleManager.FindByNameAsync(“SYSADMIN”)`

or indeed

`_userManager.AddToRoleAsync(adminUser, “SYSADMIN”);`

would both fail.
It appears that adding a role with a single string parameter populates the name field but leaves the NormalizedName field as null. However, it would seem NormalizedName is what is used to perform the lookup so the inserted record is never found thereafter.

I worked around it by using:

```
_context.Roles.Add(new IdentityRole("SYSADMIN")
{
  NormalizedName = "SYSADMIN"
});
```

Shouldn't

`_context.Roles.Add(new IdentityRole(“SYSADMIN”));`

Populate both `Name` and `NormalizedName`, or is there a use-case where you'd want Name to be populated but `NormalizedName` to be blank?

**Comment by HaoK** [comment]
You should use the identity APIs to create the role, `roleManager.CreateAsync()`
