### ISSUE TITLE
Store user emails in encrypted format instead of plain text.

### ISSUE THREAD

**Issue by nzhul** [aspnet/Identity#1038]
Hi guys,
I have simple question/request ?
Is it possible to store the emails in the database in encrypted format instead of plain text ?
I've tried to pass the email as encrypted string by bypassing the UserValidation with custom UserValidator, but when i try to get the user ( Login ) the authentication fails.

Best Regards,
Dobromir Ivanov

**Comment by blowdart** [comment]
Link to #836 and #1341, and close in favour of the more recent ones.
