### ISSUE TITLE
GetTokenAsync and RemoveTokenAsync is not virtual

### ISSUE THREAD

**Issue by msmolka** [aspnet/Identity#1041]
GetTokenAsync and RemoveTokenAsync should be virtual methods

**Comment by blowdart** [comment]
What's your justification/scenarios here?

**Comment by blowdart** [comment]
Part of #1040

**Comment by HaoK** [comment]
This will actually be fixed as part of https://github.com/aspnet/Identity/pull/1043 we did'nt have a public API validation test turned on for the EF core package which is why there were a few missing virtuals

**Comment by HaoK** [comment]
5e4e9ccdf164b622872c397c27b75d2bc8a329da
