### ISSUE TITLE
ASP.NET Core Identity + EF6 + IdentityServer4

### ISSUE THREAD

**Issue by mafshin** [aspnet/Identity#1042]
I'm currently developing a system with the following stack:

- ASP.NET Core
- [MembershipReboot](https://github.com/brockallen/BrockAllen.MembershipReboot)
- EF6
- [IdentityServer4](https://github.com/IdentityServer/IdentityServer4)

Now because of MembershipReboot support being expired, I decided to switch back to `ASP.NET Core Identity`. 

How can I have the following stack?

- ASP.NET Core
- ASP.NET Core Identity
- EF6
- [IdentityServer4](https://github.com/IdentityServer/IdentityServer4)

Is [this ](https://github.com/mrahhal/MR.AspNet.Identity.EntityFramework6) repo the way to go? Or any better alternative?

**Comment by blowdart** [comment]
The Identity Server folk have suitable templates for this in their samples; https://github.com/IdentityServer/IdentityServer4.Samples

**Comment by weitzhandler** [comment]
@blowdart 
Those examples use EFCore. The OP was referring to EF6, which is my question as well. And in short, how do I implement a `UserStore<User, TKey>` untied to EF7.
