### ISSUE TITLE
Randomly loggs out

### ISSUE THREAD

**Issue by dvdobrovolskiy** [aspnet/Identity#1044]
Here an Issue

I have 1.1.0 app (1.0.1 had same problem)

It randomly sends user to Login as if client was unauthorized. For now I found that an issue can be reproduced by sending request for controller to often. So normally app work perfectly. User logs in and stay logged while session is active (options.Cookies.ApplicationCookie.ExpireTimeSpan = TimeSpan.FromHours(2) in my case). But if user accidentally click link twice (mouse button jitter or just impatiently) it often send user to Login page withdrawing authentication.

Big remark: this happens only then I set minimum working process in apppool setting to number other that 1 (2 in my case - 2 cores 2 processes as I thought). This Produces 2 IIS processes to serve pool each start 2 instances of dotnet.exe. 

so, howto reproduce

Set minimum working process to "2"
Login in app
start accessing /Home/Index to often (I click on browser url input with mouse when press enter and repeat that. In this case I produce issue with 3-5 iterations)

It was quite an had challenge to find that courses it as I do not have it on local machine and do not click as maniac on production server but my clients have issue several times a day and have it randomly.

**Comment by blowdart** [comment]
What are you hosting this under? IIS? Has the app gone idle and restarted? If so, did you set up the data protection registry keys as discussed in https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#create-a-data-protection-registry-hive

**Comment by dvdobrovolskiy** [comment]
Looks like my problem. Tnks. Investigating that.

**Comment by blowdart** [comment]
Did you try running the powershell script?

**Comment by dvdobrovolskiy** [comment]
sorry man, not. so far. cannot play with my production server and have a very few time to recreate environment. Will try to reproduce error on test machine asap

**Comment by rtpHarry** [comment]
Its not just being idle that causes the app to be recycle. I had problems like this when a site was on a budget host. It was using too much ram and causing the app to be recycled.

**Comment by wc-matteo** [comment]
@blowdart is the powershell script required to persist the keys? Aren't the keys stored by default in `C:\Users\<user>\AppData\Local\ASP.NET\DataProtection-Keys`?

**Comment by blowdart** [comment]
Not under IIS without a profile loaded. It does that for IIS Express, or IIS where the profile is loaded. Without the profile there is no user. So yes, it's required in some configurations.

**Comment by wc-matteo** [comment]
Right, that's what I was thinking. Thanks for the confirmation.
