### ISSUE TITLE
Authentication not working on 1.1 using .NET 4.6.1

### ISSUE THREAD

**Issue by daver77** [aspnet/Identity#1046]
Hi,

I've posted this on [StackOverflow](http://stackoverflow.com/questions/40971505/issue-updating-from-aspnetcore-identity-1-0-to-1-1) .

I have an ASP.NET Core Identity and OpenIddict website which i'm trying to migrate from 1.0 to 1.1 but when I update project.json I am no longer redirected to the login page

**Comment by blowdart** [comment]
Is https://github.com/aspnet/Security/issues/930#issuecomment-261433813 applicable?

**Comment by daver77** [comment]
It sounds similar, I don't get the Windows Auth popup though

**Comment by blowdart** [comment]
This will get fixed in 1.1.1

**Comment by Eilon** [comment]
This appears to be a dup of https://github.com/aspnet/Security/issues/1044, which is already fixed in the patch branch, so I'm closing this issue.
