### ISSUE TITLE
Possibility to use Identity to register users only

### ISSUE THREAD

**Issue by dlacaille-baytech** [aspnet/Identity#1049]
Hi,
Would it be possible to use Identity to register local/external users only and rely on another mechanism/service to authenticate/authorize? Basically, we have an SSO service that takes care of authentication and would like to separate registration under another service (Members domain).

**Comment by dlacaille-baytech** [comment]
Hi. Any answer?

**Comment by blowdart** [comment]
How is this different to signing in with google in the templates, which then registers users?

**Comment by dlacaille-baytech** [comment]
Forget about it.
