### ISSUE TITLE
Identity HashedPassword

### ISSUE THREAD

**Issue by patsadow2** [aspnet/Identity#1050]
Hello,
Is there any way to say Identity to NOT hash password?

Or

Make 

> var hased =  hash.HashPassword(new ApplicationUser() { UserName = username, Email = username }, password);

to produce the same hash which is done by this in DATABASE?

>  var register = await userManager.CreateAsync(new ApplicationUser() { UserName = username, Email = username }, password));

Tried even sth like this and always FALSE

>                 var hasheduser = context.Users.First(d => d.UserName == username).PasswordHash;
>                 var user = context.Users.First(d => d.UserName == username);
> 
>                 PasswordHasher<ApplicationUser> hash = new PasswordHasher<ApplicationUser>();
>                 var hashed = hash.HashPassword(user, password);
>                 if(hasheduser == hashed)

**Comment by blowdart** [comment]
You could write your own password hasher, but this is a seriously bad idea, and we're not even going to show you how.
