### ISSUE TITLE
Make password validator options get public

### ISSUE THREAD

**Issue by Saticmotion** [aspnet/Identity#1061]
I want to show the current password rules on a webpage, without having to hardcode it in HTML. How do I get the current rules?

An example:

```HTML
<p>Minimum password length: @PasswordRules.RequiredLength</p>
```

**Comment by maliming** [comment]
```
//or as CustomPasswordValidator
var rules = (UserManager.PasswordValidator as PasswordValidator); 
rules.RequireDigit;
rules.RequiredLength;
```

**Comment by Saticmotion** [comment]
@maliming I'm using .NET Core, so I tried your second option. But it doesn't work, since Options is protected internal. I'm using the "Microsoft.AspNetCore.Identity.EntityFramewordCore" package, version 1.1.0.

**Comment by maliming** [comment]
@Saticmotion 
Derive a class from UserManager

![test](https://cloud.githubusercontent.com/assets/6908465/21385672/63c59f0a-c7aa-11e6-877a-0a2ef5c06764.png)

**Comment by maliming** [comment]
services.AddIdentity(.....).AddUserManager<MyUserManager>()

**Comment by Saticmotion** [comment]
This works, thank you! Though it's kind of annoying I have to solve it this way.

**Comment by divega** [comment]
@Saticmotion your controller can obtain the same `IOptions<IdentityOptions>` singleton from DI that the `UserManager` gets in its constructor:  https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserManager.cs#L75.

**Comment by divega** [comment]
BTW I am not against making the property getter public in 2.0. cc @HaoK

**Comment by maliming** [comment]
DI Is a best practice.😁

**Comment by Saticmotion** [comment]
@divega That's probably a better option. Thanks!!

**Comment by divega** [comment]
Reopening so that we can consider making the property getter public.

**Comment by HaoK** [comment]
b64a32f089f06c8c403f8bb9ee085a580c9555e2
