### ISSUE TITLE
CheckPasswordAsync is vulnerable to a timing attack

### ISSUE THREAD

**Issue by kezakez** [aspnet/Identity#1063]
When a consumer of the Identity API passes in a null user (ie. a username that doesn't exist) the CheckPasswordAsync function returns without doing any password hashing this gives tells an attacker if an account exists or not.

**Comment by blowdart** [comment]
As our own code null guards before calling that API, and there are much easier ways to discover if a username doesn't exist, for example by trying to register it, we don't see this as a concern.
