### ISSUE TITLE
How to use UserManager in Startup.cs class

### ISSUE THREAD

**Issue by Vaylandt** [aspnet/Identity#1065]
Help me please

In Startup.Auth.cs:
private void ConfigureAuth(IApplicationBuilder app)
{
username = "test"; 
_userManager = app.ApplicationServices.GetRequiredService<UserManager>();
_userManager = app.ApplicationServices.GetRequiredService<UserManager>();
var user = _userManager.FindByNameAsync(username).Result;
}

always responds with the **cached data ((**

related 
I need to use in Token Provider:
https://github.com/nbarbettini/SimpleTokenProvider/issues/11#issuecomment-269484942

**Comment by HaoK** [comment]
UserManagers need to be scoped as the stores depend on DbContext's which need to be scoped as well.  Capturing a user manager for reuse inside of startup is not a good idea.

**Comment by Vaylandt** [comment]
@HaoK ,It's clear :)
And what solution do you suggest?
I need a token provider and check through Identity simultaneously.

**Comment by VahidN** [comment]
@Vaylandt 
It's cached (or will be treated as a singleton) because there is only one scope at that point. You need to create and dispose a new scope this way:
```csharp
using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
{
    var signInManager = serviceScope.ServiceProvider.GetService<SignInManager<User>>();
    var userManager = serviceScope.ServiceProvider.GetService<UserManager<User>>();
}
```

**Comment by Vaylandt** [comment]
@VahidN , thank you very much!!! RESOLVED!

**Comment by Vaylandt** [comment]
@VahidN , one question, how fast this work?
Wouldn't it be reasonable to move JWT Provider in a regular controller?

**Comment by VahidN** [comment]
A regular controller does this scope creation and disposing behind the scene. It's part of a request life cycle. That's why you won't see that `cached` behavior at there.

**Comment by Vaylandt** [comment]
@VahidN , thank You for the answers!

**Comment by DavidMaltby** [comment]
Thanks!  Worked for me
