### ISSUE TITLE
UserManager do not support User primary key other than string?

### ISSUE THREAD

**Issue by chouex** [aspnet/Identity#1066]
My ApplicationUser using long type primary key

and i am able to implement ExampleUserStore 
```
public class ExampleUserStore : IUserRoleStore<long,ApplicationUser>
```

but UserManager only accept `IUserStore<TUser>` as a store, while i am using `IUserRoleStore<long, TUser>`

UserManager:
https://github.com/aspnet/Identity/blob/5aed9742a4f1a35558f5ca644e981398df7017c1/src/Microsoft.AspNetCore.Identity/UserManager.cs#L60

and SignInManager require `UserManager<TUser>` witch do not contain key type as well

**Comment by maliming** [comment]
I think you should customize User

[ApplicationUser](https://github.com/aspnet/Identity/blob/5480aa182bad3fb3b729a0169d0462873331e306/samples/IdentitySample.Mvc/Models/ApplicationUser.cs#L10)

[IdentityUser](https://github.com/aspnet/Identity/blob/5480aa182bad3fb3b729a0169d0462873331e306/src/Microsoft.AspNet.Identity.AspNetCoreCompat/IdentityUser.cs#L31)

**Comment by HaoK** [comment]
The key type is only a concern of the stores store, the Id's are always strings at the identity manager level. since all `IUserStores` implement `string GetUserIdAsync(TKey id)`

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/IUserStore.cs#L22
