### ISSUE TITLE
Can not login after changing password

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Identity#1068]
_From @anhlee24 on January 2, 2017 10:44_

After i update new password, i can not login with new password until i restart the application.

My code:
`var result = await _userManager.ChangePasswordAsync(user, userModel.CurrentPassword, userModel.Password);`

Do you have any suggest?

_Copied from original issue: aspnet/Home#1892_

**Comment by brockallen** [comment]
Sounds like they're caching a DbContext somewhere they shouldn't (perhaps singleton in DI?). That's my guess.

**Comment by anhlee24** [comment]
@brockallen  Have you met this issue before?
This is my startup.cs:

` services.AddDbContext<TCMSContext>(options => options.UseSqlServer(_config["ConnectionStrings:TCMSContextConnection"]));`

```
services.AddIdentity<User, Role>(config =>
            {
                config.User.AllowedUserNameCharacters = null;
                config.User.RequireUniqueEmail = true;
                config.Password.RequiredLength = 8;
                config.Cookies.ApplicationCookie.LoginPath = "/Auth/Login";
                config.Cookies.ApplicationCookie.Events = new CookieAuthenticationEvents()
                {
                    OnRedirectToLogin = async ctx =>
                    {
                        if (ctx.Request.Path.StartsWithSegments("/api") &&
                            ctx.Response.StatusCode == 200)
                        {
                            ctx.Response.StatusCode = 401;
                        }
                        else
                        {
                            ctx.Response.Redirect(ctx.RedirectUri);
                        }

                        await Task.Yield();
                    }
                };
            })
            .AddEntityFrameworkStores<TCMSContext, string>()
            .AddUserStore<UserStore<User, Role, TCMSContext, string>>()
            .AddRoleStore<RoleStore<Role, TCMSContext, string>>()
            .AddDefaultTokenProviders();
```

**Comment by brockallen** [comment]
> @brockallen Have you met this issue before?

In other contexts, yes. Your config does not seems to be setting up a singleton, so my hypothesis seems incorrect.

**Comment by anhlee24** [comment]
I will try to find a solution, thank you :)

**Comment by HaoK** [comment]
What does the initialization of _userManager look like in your controller?

**Comment by anhlee24** [comment]
@HaoK Here:  

        ```
private RoleManager<Role> _roleManager;
        private UserManager<User> _userManager;
        private SignInManager<User> _signInManager;

        public AuthRepository(
            UserManager<User> userManager, 
            RoleManager<Role> roleManager, 
            SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
        }
```

**Comment by HaoK** [comment]
Does your AuthRepository have a lifetime that spans multiple requests?  That's most likely the cause.

**Comment by VahidN** [comment]
Change your codes from:
```csharp
var result = await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
if (result.Succeeded)
{
   await _signInManager.SignInAsync(user, isPersistent: false);
}
```
to:
```csharp
var result = await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword).ConfigureAwait(false);
if (result.Succeeded)
{
    // reflect the changes in the Identity cookie
    await _userManager.UpdateSecurityStampAsync(user).ConfigureAwait(false);
    await _signInManager.RefreshSignInAsync(user).ConfigureAwait(false);
}
```

**Comment by HaoK** [comment]
That would only affect things if someone was insane enough to store the password within the cookie...

**Comment by anhlee24** [comment]
@HaoK  you right, its not working.

I have register my context interface like this, does it have something wrong? : 

```
public static class ServiceCollectionExtentions {

        private static void RegisterDataAccess<TEntityContext>(IServiceCollection services) where TEntityContext : EntityContextBase<TEntityContext>
        {
            services.TryAddTransient<IEntityContext, TEntityContext>();
        }
}
```

**Comment by HaoK** [comment]
The default EF user store caches entities, so you can't reuse them across requests.  Basically you cannot setup a repository to be reused across requests with that store.  Its almost certainly your AuthRepository having a singleton lifetime.

**Comment by anhlee24** [comment]
@HaoK  i have found the reason.
 In startup.cs, i need to get the instance of signInManager, so i create a instance like this:
```
private void ConfigureAuth(IApplicationBuilder app)
        {
            _userManager = app.ApplicationServices.GetRequiredService<UserManager<User>>();
            _signInManager = app.ApplicationServices.GetRequiredService<SignInManager<User>>();
}
```

and used like this:

```
private async Task<ClaimsIdentity> GetIdentity(string username, string password)
        {
            var result = await _signInManager.PasswordSignInAsync(username, password, false, lockoutOnFailure: false);
            if (result.Succeeded)
            {
                var user = await _userManager.FindByNameAsync(username);
                var claims = await _userManager.GetClaimsAsync(user);

                return (new ClaimsIdentity(new GenericIdentity(username, "Token"), new Claim[] { }));
            }
            return null;
}
```

But i do not know how to fix it. Do you have any suggest?

**Comment by brockallen** [comment]
> In startup.cs, i need to get the instance of signInManager, so i create a instance like this:

So you do have a cached reference. Elsewhere in the app, you should use DI to obtain references/instances of the UserManager.

**Comment by VahidN** [comment]
@anhlee24 
You need to create an scope manually (outside of the ASP.NET Core's life cycle). Otherwise it be treated as a singleton instance. Because there is only one scope here.
Try:
```csharp
using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
{
    using (var userManager = serviceScope.ServiceProvider.GetService<UserManager<User>>())
    {
          //
    }
}
```

**Comment by anhlee24** [comment]
@VahidN 
Thank you for your reply.

Can you suggest how to use SignInManager<User>?
Its show the error: "**SignInManager<User> type used in this statement must be implicitly convertible to System.IDisposable:**  "
```
using (var signInManager = serviceScope.ServiceProvider.GetService<SignInManager<User>>())
                {
                    _signInManager = signInManager;
                }
```

**Comment by VahidN** [comment]
Remove the second `using` statement here. It's unnecessary. Just use
```csharp
var signInManager = serviceScope.ServiceProvider.GetService<SignInManager<User>>();
```

**Comment by HaoK** [comment]
Ideally you inject the service in your controller, if you can't do that just get the service from HttpContext.RequestServices instead of caching it in an field,

`context.RequestServices.GetRequiredService<SignInManager<User>>();`

**Comment by anhlee24** [comment]
@HaoK its working! Thank you.

**Comment by jwhijazi** [comment]
@HaoK your solution worked,
Please correct me: doing this means get me new instance of the signInManager service, not the one in the scope of the application.
Right?

**Comment by anhlee24** [comment]
@jwhijazi yup
