### ISSUE TITLE
Make GetUserLockoutStore, etc. protected

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#1069]
I find myself in a situation where I need to have per-user lockout semantics. For example, user A must have 10 failed attempts and their lockout should be for 5m, but user B is 5 attempts for 10 mins. Whatever.

So I need to override `AccessFailedAsync`. It'd be nice to be able to access the user lockout store, but `GetUserLockoutStore` is internal. I know I can manually cast the `Store` now, but the existing APIs already exist.

**Comment by brockallen** [comment]
Also, the base `CancellationToken` is not available either :/

**Comment by brockallen** [comment]
So having opened this, I'm interested in discussing if it makes sense to open those base APIs as protected, or if you feel like that opens up the internals to too much access. I was able to successfully work around this, but many things from the base are not protected. So, more of a discussion point.

**Comment by brockallen** [comment]
The project I am on is still on 1.0. I'm looking at the 1.1 code -- looks like many of these were opened up, so perhaps this issue/discussion is moot.

**Comment by HaoK** [comment]
Yeah this was addressed in 1.1 hopefully, (not specifically the GetXyzStore methods as those are just helpers for casts/throwing, but some others were made protected virtual).  Feel free to reopen this if there's anything else that you need access to.
