### ISSUE TITLE
Several fields too long by 1 character for MySQL using InnoDB and UTF8

### ISSUE THREAD

**Issue by stephtr** [aspnet/Identity#1071]
InnoDB has a limit of 767 bytes for indexed fields, which is equal to 255 characters with UTF8.
Most string fields generated by IdentityDbContext have a length of 255, but some have 256:
aspnetroles.Name, .NormalizedName
aspnetusers.Email, .UserName, .NormalizedEmail, .NormalizedUserName
Therefore `dotnet ef database update` fails with `Specified key was too long; max key length is 767 bytes`.

**Comment by divega** [comment]
Related discussion: https://github.com/aspnet/Identity/issues/1040#issuecomment-267720205

**Comment by stephtr** [comment]
That would fix the issue.
I don't know about the present implementation, but maybe it would be useful to deliver a short term fix (decrease these field sizes by 1 char) until #1040 is ready.

**Comment by gravity00** [comment]
@stephtr reducing the sizes of columns would be a breaking change for people already using the framework. I had the same problems you faced using other databases and my solution was to change the columns lengths when overriding the `OnModelCreating`.

Example:

```csharp
public class ExampleIdentityDbContext : IdentityDbContext
{
    public ExampleIdentityDbContext(DbContextOptions options) : base(options)
    {

    }

    protected override void OnModelCreating(ModelBuilder builder){
        base.OnModelCreating(builder);
        
        //  this configuration should subsist over the default ones
        builder.Entity<IdentityUser>(cfg =>
        {
            b.Property(u => u.UserName).HasMaxLength(128);
            b.Property(u => u.NormalizedUserName).HasMaxLength(128);
            b.Property(u => u.Email).HasMaxLength(128);
            b.Property(u => u.NormalizedEmail).HasMaxLength(128);
        });
        
        //  apply to other entities as well
        //  ...
    }
}
```

**Comment by stephtr** [comment]
It wouldn't break that much because the length gets fixed while creating the migration.
I edited the migration, but modifying `OnModelCreating` that way is better.
Just for completeness, the configuration necessary for running on InnoDB with UTF8:
```
public class SiteDbContext : IdentityDbContext<User>
{

    // ...

    public SiteDbContext(DbContextOptions<SiteDbContext> options) : base(options) { }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        builder.Entity<User>(b =>
        {
            b.Property(u => u.UserName).HasMaxLength(255);
            b.Property(u => u.NormalizedUserName).HasMaxLength(255);
            b.Property(u => u.Email).HasMaxLength(255);
            b.Property(u => u.NormalizedEmail).HasMaxLength(255);
        });
        builder.Entity<IdentityRole>(b =>
        {
            b.Property(r => r.Name).HasMaxLength(255);
            b.Property(r => r.NormalizedName).HasMaxLength(255);
        });
    }
}
```
Thanks for the help!
