### ISSUE TITLE
Confusing PasswordSignInAsync in the Login method UserName instead of Email

### ISSUE THREAD

**Issue by Ponant** [aspnet/Identity#1075]
My goal is to set upon registration a UserName which is distinct from the Email. Eventually, I would prefer to have only unique Emails which I can configure in Startup. So I tested the code by changing the Register method to:
`var user = new ApplicationUser { UserName = "newuser", Email = model.Email };
`
where `"newuser"` has been substituted for `model.Email`.
However, while the user gets created and I logout, I cannot login and it seems that this is because the Login method requires a UserName and not an Email
`var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);
`
Besides the fact that this line of code in the ASP:NET Core Template is confusing, I am really wondering why the ASP.NET Identity Team has built PasswordSignInAsync with UserName instead of Email? What would be the best suited approach Login with Email while UserName is not equal to Email and without touching the ASP.NET Identity code?

**Comment by HaoK** [comment]
Use FindByEmail to get the user and use the username to login.
