### ISSUE TITLE
ExternalLoginConfirmation breaks if the username is already taken

### ISSUE THREAD

**Issue by rtpHarry** [aspnet/Identity#1080]
Repro:

  1. Login with a new Facebook account
  1. In the "ExternalLoginConfirmation" page enter an email that already exists on the system
  1. Press Register

The page reloads, the validation error is displayed saying "User name 'blah@example.com' is already taken." and all of the `ViewData` is now lost including the ReturnUrl of the form and the LoginProvider used in the h2 and intro paragraph.

**Comment by blowdart** [comment]
Moved to https://github.com/aspnet/Templates/issues/793
