### ISSUE TITLE
Build error with sample project(1.0.0-preview2-1-003180)

### ISSUE THREAD

**Issue by somsekhar** [aspnet/Identity#1081]
Getting following error while building project

Severity	Code	Description	Project	File	Line	Suppression State
Error		The project is configured to use .NET Core SDK version 1.0.0-preview2-1-003180 which is not installed or cannot be found under the path C:\Program Files (x86)\dotnet. These components are required to build and run this project. Download the version of .NET Core SDK specified in global.json or update the SDK version in global.json to the version that is installed.	IdentitySample.Mvc	E:\Sample Projects\Identity-dev\samples\IdentitySample.Mvc\GETSDKTOOLINGINFO	1

**Comment by blowdart** [comment]
Do you actually have  .NET Core SDK version 1.0.0-preview2-1-003180 installed? Which branch did you clone the repo from?

This looks like https://github.com/dotnet/cli/issues/5172

**Comment by pranavkm** [comment]
Running build.cmd should install the SDK for you under %LocalAppData%. As long as you use the same shell to launch VS, (i.e. launch Mvc.sln from the shell) it should pick it up. Alternatively you can install the MSI from
https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/1.0.0-preview2-1-003180/dotnet-dev-win-x64.1.0.0-preview2-1-003180.exe.

**Comment by manishsingh2061** [comment]
this link has a solution 
http://simplyaspnet.blogspot.in/2017/05/problem-if-you-open-orcreate.html
