### ISSUE TITLE
Improve email validation

### ISSUE THREAD

**Issue by VahidN** [aspnet/Identity#1086]
Currently email validation [is disabled in UserValidator class](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserValidator.cs#L94). `new MailAddress` part can be replaced with
```csharp
if(!new EmailAddressAttribute().IsValid(email)) { /*...*/ }
```
EmailAddressAttribute [is part of the new framework](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/EmailAddressAttribute.cs).

**Comment by Ponant** [comment]
Hi, I implemented a custom UserValidator to fix this issue, but I wonder at what date the miltestone 2.0.0 will be honored (approximately, 1 month, 2, 3 ?)

**Comment by HaoK** [comment]
I believe Q2 2017 is the current forecast, https://github.com/aspnet/Home/wiki/Roadmap

**Comment by HaoK** [comment]
12aa4a3f810648f94c7146e06e1a3c792a7eb1db
