### ISSUE TITLE
Reenable Interop4.5 sample

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Identity#1092]
As part of migrations to VS 2017, I temporarily disabled building the app which targets 4.5.1. Once we can build this sample again, we need to add it back to the solution and start building it again. https://github.com/aspnet/Identity/blob/a5ca720ff1bb361bdc4e4cb92652be26eae4b1ee/samples/Interop4.5/Interop4.5.csproj.aspnet45

**Comment by HaoK** [comment]
This was a point in time sample, the official interop sample will be done somewhere else (most likely docs)

**Comment by JunTaoLuo** [comment]
So should we remove the sample from this repo altogether?

**Comment by HaoK** [comment]
Its already gone :)
