### ISSUE TITLE
Suggest,If I want specify the name of each table in the database by using EF?

### ISSUE THREAD

**Issue by HeMinzhang** [aspnet/Identity#1094]
Identity can't Very good support,If you can provide their own class into the database to add or delete changes, may be better.
I'm sorry I'm poor in English.

**Comment by aioubamini** [comment]
Hi HeMinzhang,
Thank you for your message. in this sample project i want to customize the asp.net identity system and use in own project with custom tables and custom data types.
good luck.

**Comment by blowdart** [comment]
Could you try using your native language, which I assume is Chinese from your location, and we'll find a native speaker here to figure out what you're asking?

**Comment by JunTaoLuo** [comment]
@HeMinzhang  可以用中文描述或者解釋一下嗎？

**Comment by HeMinzhang** [comment]
So sorry.我想提一个建议，不知道是否可以添加，通过自己指定数据库里面每个表中字段的名字，来运行asp.net Identity.而不是asp.net Identity自己生成数据库中的数据结构。.asp.net Identity提供，登录cookie保护，验证这些功能。

**Comment by AnthonyOSX** [comment]
I assume you want to modify table names and/or column names? If so, you can accomplish this in your class that inherits from IdentityDbContext by overriding the following method like so:

```
protected override void OnModelCreating(ModelBuilder builder) {
	base.OnModelCreating(builder);
	builder.Entity<IdentityUser>().ToTable("UsersTable");
	builder.Entity<IdentityRole>().ToTable("IdentityRolesTable");
	builder.Entity<IdentityRoleClaim<string>>().ToTable("UserRoleClaimsTable");
	builder.Entity<IdentityUserClaim<string>>().ToTable("UserClaimsTable");
	builder.Entity<IdentityUserLogin<string>>().ToTable("UserLoginsTable");
	builder.Entity<IdentityUserRole<string>>().ToTable("UserRolesTable");
	builder.Entity<IdentityUserToken<string>>().ToTable("UserTokensTable");

	builder.Entity<IdentityUser>().Ignore((u) => u.PhoneNumber); // property example
}
```

**Comment by HeMinzhang** [comment]
@blowdart @JunTaoLuo @AnthonyOSX   Thanks a million.
