### ISSUE TITLE
Protected CreatePrincipal Method for UserClaimsPrincipalFactory

### ISSUE THREAD

**Issue by bchavez** [aspnet/Identity#1098]
Hello wonderful people,

I'd like to hook the creation of [`new ClaimsPrincipal(id)` in `UserClaimsPrincipalFactory:CreateAsync` at this location](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserClaimsPrincipalFactory.cs#L116) and return my own `MyAppClaimsPrincipal(id)` implementation.

The following is what I'd like to change in **UserClaimsPrincipalFactory.cs**:

[**UserClaimsPrincipalFactory.cs**](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserClaimsPrincipalFactory.cs#L116)
```
public class UserClaimsPrincipalFactory<TUser, TRole> : IUserClaimsPrincipalFactory<TUser>
    where TUser : class
    where TRole : class
{
        public virtual async Task<ClaimsPrincipal> CreateAsync(TUser user)
        {
            //... keep all microsoft's stuff
            return CreatePrincipal(id);
        }
        protected virtual ClaimsPrincipal CreatePrincipal(ClaimsIdentity id)
        {
            return new ClaimsPrincipal(id);
        }
}
```
-----
Currently, in order to wrap the `ClaimsIdentity` from `CreateAsync`, I have to call the `base.CreateAsync` like this:
```
public class MyAppClaimsPrincipalFactory : UserClaimsPrincipalFactory<User, Role>
  public override async Task<ClaimsPrincipal> CreateAsync(User user)
  {
      var basePrincipal = await base.CreateAsync(user);
      var myAppPrincipal = new MyAppClaimsPrincipal(basePrincipal.Identities.First(), this.Options);
      return myAppPrincipal;
  }
}
```
It would be great if I could simply handle the `ClaimsPrincipal` creation itself by overriding `CreatePrincipal(id)` as I've proposed above. I could simply do this instead:
```
  protected override ClaimsPrincipal CreatePrincipal(ClaimsIdentity id)
  {
      return new MyAppClaimsPrincipal(id);
  }
```
-----
Hm. Yea, it's a small nit-pick on the principal creation process but it does avoid a wasteful principal object allocation. I'd be happy to send a PR if you'd be okay with this small change. It's cool if not.

Thank you for your consideration, :v: 
Brian

:thought_balloon: :mag: ***["I want to know... what you're thinking..."](https://www.youtube.com/watch?v=ijAYN9zVnwg)***

**Comment by HaoK** [comment]
Seems fine, feel free to submit a PR and we'll take a look

**Comment by brockallen** [comment]
> return my own MyAppClaimsPrincipal(id) implementation.

IIRC, according to @blowdart that's not supported.
