### ISSUE TITLE
Bug in UserClaimsPrincipalFactory

### ISSUE THREAD

**Issue by armitagemderivitec** [aspnet/Identity#1104]
I  believe there is an issue with the following class:

[Identity/src/Microsoft.AspNetCore.Identity/UserClaimsPrincipalFactory.cs](https://github.com/aspnet/Identity/blob/master/src/Microsoft.AspNetCore.Identity/UserClaimsPrincipalFactory.cs)

Code:
`                var roles = await UserManager.GetRolesAsync(user);  
                foreach (var **roleName** in roles)  
                {  
                    id.AddClaim(new Claim(Options.ClaimsIdentity.RoleClaimType, roleName));  
                    if (RoleManager.SupportsRoleClaims)  
                    {  
                        var role = await RoleManager.FindByNameAsync(roleName);  
                        if (role != null)  
                        {  
                            id.AddClaims(await RoleManager.GetClaimsAsync(role));  
                        }  
                    }  
                }`   

`UserManager.GetRolesAsync(user)` returns a list of role names. 

`RoleManager.FindByNameAsync(roleName)` checks against NormalizedName and only returns if Name = NormalizedName which I assume is not intended.

**Comment by HaoK** [comment]
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/RoleManager.cs#L318

FindByName will normalize the name, so the casing of the role name can be different and it will be normaliezd.
