### ISSUE TITLE
Login and NormalizedUserName

### ISSUE THREAD

**Issue by sylvaincaillot** [aspnet/Identity#1106]
When registering a new user (test@here.com), I get the following saved into the [dbo].[AspNetUsers] table:

|       Email              |  NormalizedEmail    | NormalizedUserName   |     UserName       |
| ------------------ | --------------------- | ------------------------- | ------------------ |
|  test@here.com   |  TEST@HERE.COM   |    TEST@HERE.COM      |  test@here.com   | 

However, I thought that the username was not very user friendly in my layout and wanted to change it to something like:

|       Email             |  NormalizedEmail     | NormalizedUserName  |     UserName    |
| ------------------ | --------------------- | ------------------------- | ------------------ |
|     test@here.com    |  TEST@HERE.COM   |    TEST@HERE.COM      |    John Smith     | 

On the other hand, I found that by using the ResetPassword in the Account controller or the ChangePassword method in the Manage controller, the NormalizedUserName was overwritten by the UserName to get something like that:

|            Email        |   NormalizedEmail    | NormalizedUserName  |     UserName     |
| ------------------ | --------------------- | ------------------------- | ------------------ |
|  test@here.com  |  TEST@HERE.COM   |           JOHN SMITH        |    John Smith    |

Having something like that prevents me to login now as it is using the NormalizedUserName to get identified which is not an email anymore...

**Several questions:**

Why, when I reset or change my password, my NormalizedUserName gets overwritten?

Why do we use the NormalizedUserName to get logged? It doesn't make sense to me as we provide an email in the interface, it should be using the NormalizedEmail instead.

It would be great to make the distinction between user name for display purposes and user email for identification purpose.

Thank you for your help

Sylvain

ASP.Net Core 1.1

**Comment by blowdart** [comment]
The normalized pieces are for fast lookup, you're confusing email and username, they're different. User Name is the identification field for logging in. Email is there for password resets, password confirmations in our templates.

If you want a display name then you'll need to add it to your model for identity.
