### ISSUE TITLE
How can I use ASP.NET Identity in n-tier solution

### ISSUE THREAD

**Issue by icom99** [aspnet/Identity#1109]
I’m working on a solution which consists of layered mvc application using entity framework. I want to use AspNet Identity to manage user accounts and logins. Which has its own model and dbcontext classes embedded in it and all of these are inside  MVC project.
I want to be able to manage database interactions through data layer which is entity framework and DB context. And the ApplicationUser is referenced by other tables. 
How can I use ASP.NET Identity in the n-tier solution?
Thanks a lot.

**Comment by blowdart** [comment]
Like you would anything else, shove a facade in your service which wraps the methods you want to call.

The only fun part is creating the auth cookies, but that can be done in code once you have the facade return a ClaimsPrincipal;

```c#
    await HttpContext.Authentication.SignInAsync("Cookie", userPrincipal,
        new AuthenticationProperties
        {
            ExpiresUtc = DateTime.UtcNow.AddMinutes(20),
            IsPersistent = false,
            AllowRefresh = false
        });
```

Signout is much the same, except, well, you call SignOut, without needing to pass a principal.
