### ISSUE TITLE
Need a way to remove/override the default RoleValidator

### ISSUE THREAD

**Issue by gordon-matt** [aspnet/Identity#1112]
I am creating a multi-tenancy app and I need a way to override the default `RoleValidator` so that names are unique per tenant.. Example:

TenantId | Role
--- | ---
1 | Admin
1 | Tenant1CustomRole1
1 | Tenant1CustomRole2
2 | Tenant2CustomRole1
etc

I had this working very nicely in MVC5 and am in the middle of migrating to Core. I already created a custom `RoleValidator` which is essentially the same as the default, but checks for `TenantId`:

```
private async Task ValidateRoleName(
	RoleManager<TRole> manager, 
	TRole role,
	ICollection<IdentityError> errors)
{
	var roleName = await manager.GetRoleNameAsync(role);
	if (string.IsNullOrWhiteSpace(roleName))
	{
		errors.Add(Describer.InvalidRoleName(roleName));
	}
	else
	{
		var owner = await manager.Roles.FirstOrDefaultAsync(x => x.TenantId == role.TenantId && x.NormalizedName == roleName);

		if (owner != null &&
			!string.Equals(await manager.GetRoleIdAsync(owner), await manager.GetRoleIdAsync(role)))
		{
			errors.Add(Describer.DuplicateRoleName(roleName));
		}
	}
}
```

I then make sure to register my validator as follows:

```
services.AddIdentity<ApplicationUser, ApplicationRole>()
	.AddEntityFrameworkStores<ApplicationDbContext>()
	.AddUserStore<ApplicationUserStore>()
	.AddRoleStore<ApplicationRoleStore>()
	.AddRoleValidator<ApplicationRoleValidator>()
	//etc
```

The problem however, is that I have discovered that I cannot remove the default `RoleValidator`.. only supplement it with my own. Therefore, I always get the "Duplicate role name" error. Please make a way for us to clear the list of `RoleValidators` on the `RoleManager` or at least just the default one.

**Comment by HaoK** [comment]
Add your role validator before you call AddIdentity and that should prevent the default one from being registered.

**Comment by gordon-matt** [comment]
@HaoK Not very obvious, but that did the trick. Much appreciated, thanks!
