### ISSUE TITLE
Abide by the routing "LowercaseUrls" setting

### ISSUE THREAD

**Issue by AnthonyOSX** [aspnet/Identity#1115]
Setting the following in the ConfigureServices method does not effect the url generated by Identity framework (ex. redirecting to the login page due to failing basic route authentication will generate something like "/Account/Login" instead of the desired "/account/login"):

```
services.AddRouting((options) => {
	options.LowercaseUrls = true;
});
```

**Comment by singlewind** [comment]
Identity is using hard coded value "/Account/Login" as default if you are not specified. And it doesn't need to bring MVC features in and should be generic itself. It is always easier just give the value you want like

```
            services.Configure<IdentityOptions>(conf =>
            {
                conf.Cookies.ApplicationCookie.LoginPath = "/account/login";
                conf.Cookies.ApplicationCookie.LogoutPath = "/account/logout";
            });
```

**Comment by AnthonyOSX** [comment]
Didn't even know about these settings, thanks!
