### ISSUE TITLE
HasMaxLength does not affect generated migration code for classes that derive from Identity models

### ISSUE THREAD

**Issue by NickThissen** [aspnet/Identity#1118]
I am using Identity in combination with a MySQL database using either [SapientGuardian](https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql) or [Pomelo](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) MySQL providers.
I am trying to limit the length of string keys and indices so that they remain below 767 bytes as required for my database server.

I am not sure if this is an Identity issue, but I am seeing the same behavior for both of the mentioned MySQL providers. Therefore it might be an issue with Identity instead.
I had opened this issue in the repository of both providers as well:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/200
https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql/issues/49

### The issue

In the `OnModelCreating` method, the `HasMaxLength` call on the `ModelBuilder` seems to have no effect on the generated migrations if it is applied on a property that inherits an ASP.NET Identity Core class, such as IdentityUser or IdentityRole.

However, it seems to apply the length correctly when used directly on Identity classes that are not derived from, e.g. `IdentityUserLogin<int>` and `IdentityUserToken<int>`.

For example, I extended my IdentityUser class in a class `User` and IdentityRole in a class `IntRole`:

	public class User : IdentityUser<int>
	{
	    public string FullName { get; set; }
	}

    public class IntRole : IdentityRole<int>
    {
        public IntRole() : base() { }
        public IntRole(string name) : base(name) { }
    }

I use the model builder to set some max lengths to make sure the key size remains below 767 bytes.

    private const int MAX_KEY_LENGTH = 127;

    protected override void OnModelCreating(ModelBuilder builder)
    {
        // Make sure keys and indices are not too long
        builder.Entity<User>(e =>
        {
            e.Property(m => m.UserName).HasMaxLength(MAX_KEY_LENGTH);
            e.Property(m => m.NormalizedUserName).HasMaxLength(MAX_KEY_LENGTH);
            e.Property(m => m.Email).HasMaxLength(MAX_KEY_LENGTH);
            e.Property(m => m.NormalizedEmail).HasMaxLength(MAX_KEY_LENGTH);
        });

        builder.Entity<IntRole>(e =>
        {
            e.Property(m => m.Name).HasMaxLength(MAX_KEY_LENGTH);
            e.Property(m => m.NormalizedName).HasMaxLength(MAX_KEY_LENGTH);
        });

        builder.Entity<IdentityUserLogin<int>>(entity =>
        {
            entity.Property(m => m.LoginProvider).HasMaxLength(MAX_KEY_LENGTH);
            entity.Property(m => m.ProviderKey).HasMaxLength(MAX_KEY_LENGTH);
        });
        builder.Entity<IdentityUserToken<int>>(entity =>
        {
            entity.Property(m => m.LoginProvider).HasMaxLength(MAX_KEY_LENGTH);
            entity.Property(m => m.Name).HasMaxLength(MAX_KEY_LENGTH);

        });

        base.OnModelCreating(builder);
    }

After generating a migration, the length of the relevant columns is **incorrect** for the AspNetUser and AspNetRoles tables. However, it is **correctly modified** for the AspNetUserLogin and AspNetUserToken tables:

    dotnet ef migrations add Test

Generated migration code (pieces);

    // Roles: NOT CHANGED!
    migrationBuilder.CreateTable(
        name: "AspNetRoles",
        columns: table => new
        {
            Id = table.Column<int>(nullable: false)
                .Annotation("MySql:ValueGeneratedOnAdd", true),
            ConcurrencyStamp = table.Column<string>(nullable: true),
            Name = table.Column<string>(maxLength: 256, nullable: true),
            NormalizedName = table.Column<string>(maxLength: 256, nullable: true)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_AspNetRoles", x => x.Id);
        });
        
    // Users: NOT CHANGED!
    migrationBuilder.CreateTable(
        name: "AspNetUsers",
        columns: table => new
        {
            Id = table.Column<int>(nullable: false)
                .Annotation("MySql:ValueGeneratedOnAdd", true),
            AccessFailedCount = table.Column<int>(nullable: false),
            ConcurrencyStamp = table.Column<string>(nullable: true),
            CreatedTime = table.Column<DateTime>(nullable: false),
            Email = table.Column<string>(maxLength: 256, nullable: true),
            EmailConfirmed = table.Column<bool>(nullable: false),
            FullName = table.Column<string>(nullable: true),
            LockoutEnabled = table.Column<bool>(nullable: false),
            NormalizedEmail = table.Column<string>(maxLength: 256, nullable: true),
            NormalizedUserName = table.Column<string>(maxLength: 256, nullable: true),
            PasswordHash = table.Column<string>(nullable: true),
            PhoneNumber = table.Column<string>(nullable: true),
            PhoneNumberConfirmed = table.Column<bool>(nullable: false),
            SecurityStamp = table.Column<string>(nullable: true),
            TwoFactorEnabled = table.Column<bool>(nullable: false),
            UserName = table.Column<string>(maxLength: 256, nullable: true)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_AspNetUsers", x => x.Id);
        });
        
    // User Tokens: changed ok!
    migrationBuilder.CreateTable(
        name: "AspNetUserTokens",
        columns: table => new
        {
            UserId = table.Column<int>(nullable: false),
            LoginProvider = table.Column<string>(maxLength: 127, nullable: false),
            Name = table.Column<string>(maxLength: 127, nullable: false),
            Value = table.Column<string>(nullable: true)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_AspNetUserTokens", x => new { x.UserId, x.LoginProvider, x.Name });
    });

To be clear, the issue is the length of for example the `AspNetUser.Email` and `AspNetRole.Name` columns.

Is this an issue with the MySQL provider, with Identity, or just something wrong on my end?

### Further technical details

MySQL version: 5.7
Operating system: Windows 7
Microsoft.AspNetCore.Identity version: 1.1.0
SapientGuardian.EntityFrameworkCore.MySql version: 7.1.19
Pomelo.EntityFrameworkCore.MySql version: 1.1.0

**Comment by VahidN** [comment]
Put `base.OnModelCreating(builder);` at the top of the method. It will override all of your settings to default ones if you put it at the end.

**Comment by NickThissen** [comment]
Aha.... That works, thanks! I don't understand though why it was already working for IdentityUserToken and IdentityUserLogin?
