### ISSUE TITLE
Add Optional 'UpdateUser' Parameter to the AddToRoleAsync adn RemoveFromRoleAsync Methods

### ISSUE THREAD

**Issue by Singularity222** [aspnet/Identity#1122]
Hey there, I thought of a possible enhancement for the UserManager class, specifically the "AddToRoleAsync" and "RemoveFromRoleAsync" methods. I'm writing a custom UserStore  to be used with Identity using Dapper. When I began to implement these two methods, I took a look at the UserManager implementation and noticed both "AddToRoleAsync" and "RemoveFromRoleAsync" eventually call the "UpdateAsync" method at then end. In my implementation of the UserStore, there would be no reason to update the user at the end as adding or removing them from a role is done separately from the update of the user.

My thought was to add an optional parameter to the these methods with a default value of true and wrapping the call to UpdateUserAsync with a conditional checking the UpdateUser value. This would allow someone using the UserManager class to control whether the user is updated or not. This may be a pattern we can use elsewhere as well, but these were the first two places I noticed it. I'd be happy to work on these myself at some point as they are not very urgent, but I was hoping to see what people thought. I'm new to contributing to open source.

**Comment by HaoK** [comment]
The pattern for identity public APIs is basically to manipulate the entity via Store operations, do some validation, and then call UpdateUser.  We won't add a flag, but you can always keep track of whether the user data has been modified in the store yourself.
