### ISSUE TITLE
CookieAuthenticationProvider silently fails to Validate Identity if UserStore doesn't implement IUserSecurityStampStore

### ISSUE THREAD

**Issue by Phil-B** [aspnet/Identity#1123]
This can be filed as PEBCAK but caused several hours of agony which might be avoidable for others in future

### Minimal repro steps
1. Create an asp.net 4.5.2 MVC project using the 'individual user accounts' template
2. Create and implement a custom UserStore without implementing IUserSecurityStampStore
3. Compile and run
4. Sign in
5. Wait for validateInterval to lapse
6. Request any controller action

### Expected result
Either a compilation error at stage 3 or a runtime exception at stage 6

### Actual result
The identity is rejected, user must re-authenticate

**Comment by HaoK** [comment]
If you don't support security stamp you should remove the validator:

identityOptions.ApplicationCookie.Events.ValidatePrincipal = null
