### ISSUE TITLE
SignInManager.IsSignedIn does not handle exceptions from WindowsIdentity.get_AuthenticationType()

### ISSUE THREAD

**Issue by richmcd** [aspnet/Identity#1127]
The WindowsIdentity.AuthenticationType property getter throws exceptions derived from LsaGetLogonSessionData failures.  This is unusual for a property getter, but one I'm not sure how they are going to fix since there doesn't seem to be a good response for AuthenticationType when the current process simply doesn't have access to the Lsa Logon Session Data. Ultimately I believe the DotNet/CoreFx/System.Security.Principal.Windows contributors need to figure out a different way to determine, or default, the AuthenticationType when LsaGetLogonSessionData fails.

```
        //
        // Properties.
        //
        // this is defined 'override sealed' for back compat. Il generated is 'virtual final' and this needs to be the same.
        public override sealed string AuthenticationType
        {
            get
            {
                // If this is an anonymous identity, return an empty string
                if (_safeTokenHandle.IsInvalid)
                    return String.Empty;

                if (_authType == null)
                {
                    Interop.LUID authId = GetLogonAuthId(_safeTokenHandle);
                    if (authId.LowPart == Interop.LuidOptions.ANONYMOUS_LOGON_LUID)
                        return String.Empty; // no authentication, just return an empty string

                    SafeLsaReturnBufferHandle pLogonSessionData = SafeLsaReturnBufferHandle.InvalidHandle;
                    try
                    {
                        int status = Interop.SspiCli.LsaGetLogonSessionData(ref authId, ref pLogonSessionData);
                        if (status < 0) // non-negative numbers indicate success
----->                      throw GetExceptionFromNtStatus(status);

                        pLogonSessionData.Initialize((uint)Marshal.SizeOf<Interop.SECURITY_LOGON_SESSION_DATA>());

                        Interop.SECURITY_LOGON_SESSION_DATA logonSessionData = pLogonSessionData.Read<Interop.SECURITY_LOGON_SESSION_DATA>(0);
                        return Marshal.PtrToStringUni(logonSessionData.AuthenticationPackage.Buffer);
                    }
                    finally
                    {
                        if (!pLogonSessionData.IsInvalid)
                            pLogonSessionData.Dispose();
                    }
                }

                return _authType;
            }
        }

```

Until then, to work around this, I think SignInManager.IsSignedIn needs to check if a ClaimsIdentity is an instance of a WindowsIdentity and avoid the AuthenticationType property.  Either that or handle the exception gracefully, assuming that any ClaimsIdentity.AuthenticationType property getter could throw.

```

        public virtual bool IsSignedIn(ClaimsPrincipal principal)
        {
            if (principal == null)
            {
                throw new ArgumentNullException(nameof(principal));
            }
            return principal?.Identities != null &&
                principal.Identities.Any(i =>
                    // Avoid calling AuthenticationType on WindowsIdentity 
                    ((i as WindowsIdentity) != null &&
                        new string[]{ "Kerberos", "NTLM", "Negotiate", "Windows Authentication" }
                            .Contains(Options.Cookies.ApplicationCookieAuthenticationScheme)
                    ) ||
                    (i as WindowsIdentity) == null && 
                        i.AuthenticationType == Options.Cookies.ApplicationCookieAuthenticationScheme);

        }

```

The suggested change is a blunt instrument to deal with a problem that shouldn't have been there in the first place, but I attempt to honor the ApplicationCookieAuthenticationScheme comparison by supplying possible values for AuthenticationType when using Windows Authentication on IIS.  It's possible that the ApplicationCookieAuthenticationScheme should never be set to any of the values used by Windows Authentication in which case the left side of the OR expression can be dropped entirely in favor of the right side, unless you think its better to simply handle the exception and move on.

**Comment by blowdart** [comment]
Why are you using SignInManger with Windows auth?

This does seem to be a bug in the Windows Identity classes, not Identity.

**Comment by richmcd** [comment]
We're using Windows auth for authentication but are using Identity for role assignment within the app, we don't want to manage application roles in active directory.

Sent from my Android phone using TouchDown (www.symantec.com)

-----Original Message-----

**Comment by blowdart** [comment]
We've heard from the Windows folks they're looking at fixing it on their side, so we're closing this.
