### ISSUE TITLE
Debugging/Stepping through AspNetCore.Identity

### ISSUE THREAD

**Issue by dubeme** [aspnet/Identity#1128]
Hi guys,

I'm working on my custom **UserStore**, and will like to step though the default **UserManager** code. Is there a way to setup in VS to pull the source from GitHub, hence enabling me to step through the code.

**Setup**:
VS Enterprise
.NET - 1.0.0-preview2-1-003177

**Comment by HaoK** [comment]
You should be able to follow these steps: https://www.stevejgordon.co.uk/debugging-into-asp-net-core-source

**Comment by dubeme** [comment]
Thanks. I had tried that yesterday, but to no avail. Did it again, and it seems to be working now :)
