### ISSUE TITLE
How to limit c# model class parameter call to MS SQL server for non-existing table field

### ISSUE THREAD

**Issue by EdwardL75** [aspnet/Identity#1129]
Working with database-first approach creating a new ASPNETCORE MVC web app with user authentication, I would like to override the way the parameters from IdentityUser class are queried to the database. The reason is the current implementation of IdentityUser has two new parameters NormalizedEmail and NormalizedUserName (which in my opinion retracts from Normalization) and I do not wish to change the database table AspNetUsers.

So I am looking for information on the changes I need to make to model classes and controller classes that will use email.ToUpper() in the RegisterViewModel of the AccountController.Register Action upon submitting of a new user. As well any call to the AspNetUsers table will not query the NormalizedUserName and NormalizedEmail parameters to the database, so upon runtime there is no SQL exception from missing fields in the table.

I tried with writing the code below in the Model class so that those two parameters are not included in the query to the database to no success.

`public class IdentityUser : Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUser {

     public override string NormalizedUserName    { get { return UserName.ToUpper(); }  }
     public override string NormalizedEmail     { get { return Email.ToUpper(); }  } 
}`

If anything this will help teach me (and other novice who read this) how to transform/manipulate model class parameters being handled by DbConext and its interactions with a database. Thanks

**Comment by HaoK** [comment]
This may work functionally, but since we rely on these fields for our queries, they should be indexed which isn't possible if the column doesn't exist, so just update the database schema to include the columns.
