### ISSUE TITLE
Improve XML comments/intellisense contents

### ISSUE THREAD

**Issue by divega** [aspnet/Identity#113]
We need to wordsmith the comments and make sure they meet quality and consistency standards. It would be best to have specialized people, e.g. programing writers, help on this.

**Comment by HaoK** [comment]
Merged 715790c2134d5bd8904da65877c1fd4bce4b8035

Sorry @blowdart I only had one merge conflict...  It did take me an extra minute to resolve though!!

**Comment by HaoK** [comment]
But, thanks for doing this, these are probably 100x better than anything I could have done :)

**Comment by blowdart** [comment]
Damnit, I wanted this to be painful.

**Comment by HaoK** [comment]
Well you did mess up the logical ordering I had, which is painful, but since the code isn't changing much anymore, I can deal...
