### ISSUE TITLE
IQueryableUserStore<TUser> is too much Entity Framework like

### ISSUE THREAD

**Issue by RobinHerbots** [aspnet/Identity#1133]
When implementing a userstore or rolestore with another db, the IQueryableUserStore<TUser> isn't  that obvious to implement.  Maybe we could add another interface like 
```
 public interface IQueryStore<T> where T : class
    {
        Task<IEnumerable<T>> Query(QueryRequest<T> query, CancellationToken cancellationToken);
    }
```  
Where the QueryRequest class contains some filterexpression and paging related props.  This eases to implement and prevent querying for all instances.  Adding some extra checks to see which of the 2 are supported, can help to implement the generic UserManager, etc, ...

```
   public class QueryRequest<T>
    {
        /// <summary>
        /// Filter expression
        /// </summary>
        public FilterExpression<T> FilterExpression { get; set; } = new FilterExpression<T>();
        #region Paging
        public int Page { get; set; } = -1;
        public int Rows { get; set; }
        public int SkipValue => Page != -1 ? (Page - 1) * Rows : 0;
     }
```

The filterexpression should be usable like  users = users.Where(query.FilterExpression.FilterClause); or something alike.  I used the  LinqKit.Predicatebuilder to implement this.  I can share it as example if desired.

**Comment by HaoK** [comment]
We are not looking to abstract this for all possible providers of identity, since this is an optional interface, if its too hard to implement this, you don't have to, and you can use your own mechanism to execute queries against your data.

**Comment by RobinHerbots** [comment]
@HaoK , 

I know I can extend and add whatever I want.  The point was to keep the usermanager as generic as possible.  
Anyway, thx the answer.
