### ISSUE TITLE
An error occurred while calling method 'ConfigureServices' on startup class 'Startup'.

### ISSUE THREAD

**Issue by mdmoura** [aspnet/Identity#1134]
I have the following on an ASP.NET Core 1.1.1 project:

```C#
    public class DataContext : IdentityDbContext<User, Role, Int32, UserClaim, UserRole, UserLogin, RoleClaim, UserToken> { }

    public class User : IdentityUser<Int32, UserClaim, UserRole, UserLogin> { }
    public class UserClaim : IdentityUserClaim<Int32> { }
    public class UserLogin : IdentityUserLogin<Int32> { }
    public class UserRole : IdentityUserRole<Int32> { }
    public class UserToken : IdentityUserToken<Int32> { }

    public class Role : IdentityRole<Int32, UserRole, RoleClaim> { }
    public class RoleClaim : IdentityRoleClaim<Int32> { }
```

And Startup I have the following:

```C#
    services
      .AddIdentity<User, Role>()
      .AddEntityFrameworkStores<Context>()
```

But I get the error:

    An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. 
    Consider using IDbContextFactory to override the initialization of the DbContext at design-time. 
    Error: GenericArguments[0], 'WebProj.User', on 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`4[TUser,TRole,TContext,TKey]' violates the constraint of type 'TUser'.

Do I still need to create custom UserStore and RoleStore to make this work in ASP.NET Code 1.1.1?

Thank You,
Miguel

**Comment by HaoK** [comment]
Try `AddEntityFrameworkStores<Context, int>`

**Comment by mdmoura** [comment]
That compiles but when I run it I get the error:

    "GenericArguments[0], 'WebProj.User', on 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`4[TUser,TRole,TContext,TKey]' violates the constraint of type 'TUser'."

    "   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)\r\n   at System.RuntimeType.MakeGenericType(Type[] instantiation)\r\n   at Microsoft.Extensions.DependencyInjection.IdentityEntityFrameworkBuilderExtensions.GetDefaultServices(Type userType, Type roleType, Type contextType, Type keyType)\r\n   at Microsoft.Extensions.DependencyInjection.IdentityEntityFrameworkBuilderExtensions.AddEntityFrameworkStores[TContext,TKey](IdentityBuilder builder)\r\n   at WebProj.Startup.ConfigureServices(IServiceCollection services)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)\r\n   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()\r\n   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()\r\n   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()\r\n   at WebProj.Program.Main(String[] args)"

**Comment by HaoK** [comment]
Oh yeah, you still have to specify your own store:

See https://github.com/aspnet/Identity/issues/855

**Comment by HaoK** [comment]
We have improved this in 2.0 to fully use reflection to make `AddEntityFrameworkStores<Context>` 'do the right thing'

**Comment by HaoK** [comment]
See https://github.com/aspnet/Identity/issues/1001 for how things will work in 2.0

**Comment by mdmoura** [comment]
I saw that one and the milestone was [1.1.0-preview1](https://github.com/aspnet/Identity/milestone/21) so I though that was done. So the entire User Store needs to be created?

**Comment by HaoK** [comment]
That change is in 1.1.1, but you still need to put your own user store type into DI since the AddEntityFrameworkStores method is only using the 4 generic type constructor for UserStore, and you are specifying all of the child entities.
