### ISSUE TITLE
Not able to create User in Console Application and SignIn with it in Web Application

### ISSUE THREAD

**Issue by mdmoura** [aspnet/Identity#1135]
Using ASP.NET Core 1.1.1 I am creating a User as follows:

    DataContext context = new DataContext();

    User user = new User {
      Email = "john@company.com",
      Username = "john@company.com
    };

    var userStore = new UserStore<DataContext>(context);

    var userManager = new UserManager<User>(userStore, null, null, null, null, null, null, null, null);

    await userManager.CreateAsync(user, "johnpass");

The user is created but the login fails in my Web Application when doing it this way:

    var result = await _signInManager.PasswordSignInAsync("john@company.com", "johnpass", false, true); 

If I create the user on my Web Application Startup getting the UserManager from services then the login works.

Am I missing something?

What

**Comment by HaoK** [comment]
You should be getting the UserManager from RequestServices, not newing them up.

**Comment by HaoK** [comment]
Oh, Identity is not currently designed to support non Asp.NET scenarios

**Comment by mdmoura** [comment]
But is there a way to configure the services in a Console Application to replicate what is going on in the Web Application? I mean, I would like to seed the database through a Console Application and not having it in the Web Application.

**Comment by HaoK** [comment]
Sure you can new up a ServiceCollection() call AddIdentity and all the other things it needs (you'll need to replicate what hosting does as well to add things like Options/Logging)

See https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.Specification.Tests/IdentitySpecificationTestBase.cs#L61 as a starting point
