### ISSUE TITLE
Security (Sample) - don't use UserId in ConfirmEmail href

### ISSUE THREAD

**Issue by PartyArk** [aspnet/Identity#1138]
When we want to confirm our email, the Post to ConfirmEmail is { userid, token }. This is in contrast to resetting a password, where the model is { email, token }. 

The chain of events begins at successful registration, when the CallbackUrl is generated.

There doesn't seem anything to be gained by using the UserId directly. Since access is via a 'public' link sent to an email, it exposes a) whether the underlying store is int or guid based and b) provides a valid UserId which can be associated with the email it's been sent to.

I suggest operating the same way as the Post to ForgotPassword, and use the email as the account identifier.

**Comment by blowdart** [comment]
The reason we can't use the email in ConfirmEmail is because ... we don't have a confirmed email at that point :) So we have to use the userId.

**Comment by PartyArk** [comment]
I don't think that's right. Bear with me.

The process is:
- Successful registration. An a/c with a unique id and unique email is created, but is set to 'unconfirmed' so you can't login.
- Simultaneously, a url is sent to that email. It contains a userid/token pair to confirm the a/c is valid.
- On clicking the link, Identity fetches the registered a/c via userid and checks if the token is valid etc.

So, what would change if, instead, the url contained an email/token pair? Identity would look for the a/c via unique email address and check if the token is valid. Yes, the a/c is not yet confirmed, that's why we're trying to confirm it. 

You say we can't use the email as the a/c identifier because the a/c hasn't been confirmed. I don't follow that logic. The a/c has been created for the email, it's just waiting for valid token to confirm it. Both the userid and the email address are unique pointers to that a/c - but for the reasons I posted above I suggest email address would be the better choice to identity the a/c we want to try Confirming.

**Comment by HaoK** [comment]
Email is not guaranteed to be unique.  usernames are, so username and user id should be a 1:1

**Comment by PartyArk** [comment]
Fair point, although I suspect a large number of implementations will use email as username.

To be clear then: I suggest the confirmation should use the a/c username (which may also be the email) with token, rather than the userId with token, thus avoiding exposing db internals.

**Comment by Ponant** [comment]
If Email is not unique you can have 2 usernames for the same Email, but the `ForgotPassword `method defines the user by `FindByEmailAsync`, hence which user will be returned??

**Comment by HaoK** [comment]
Undefined, you probably shouldn't use FindByEmail if you don't have unique emails.  But the template uses email as the user name to simplify things, which effectively enforces that emails are unique as user names are always required to be unique.

**Comment by Ponant** [comment]
I have seen another issue where you correctly argued the use of `FindByUserName` until the template switched to `FindByEmail `. The unicity of UserName is fundamental, but now that `FindByEmail ` is in the template and furthermore UserName = Email in the template, this template becomes dangerous out of the box. I really think the template should start with UserName + Email as fields for login and register, thereby well distinguished, and propagate the code throughout reset, forgot pwd external logins, association. I am happy to help but there must be some discussion because there are many issues opened here and in the templates repo regarding such points and they are still open (sometimes back to 2015 :).
