### ISSUE TITLE
GetRolesAsync missing cancellation token pass in EntityFramework UserStore

### ISSUE THREAD

**Issue by audaciasoftware** [aspnet/Identity#1143]
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/UserStore.cs

The last line of the GetRolesAsync method is:

`return await query.ToListAsync();`

This should be passed the cancellation token and is inconsistent with the rest of the class, i.e.

`return await query.ToListAsync(cancellationToken);`

**Comment by HaoK** [comment]
a1b9857d94926b47e9d6acef779458e5658fa8fd
