### ISSUE TITLE
Not able to specify Id type in IUserStore.GetUserIdAsync

### ISSUE THREAD

**Issue by MaxZuber** [aspnet/Identity#1146]
When implementing IUserStore I am not able to specify type of Id key.
My IdentityUser look like this IdentityUser<int, ...>, so I cannot use it with current IUserStore
[https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/IUserStore.cs#L22](url)

**Comment by blowdart** [comment]
Identity treats the primary key as a string, always. It's up to the IUserStore to convert that to whatever you use in your custom IdentityUser.

**Comment by shoe788** [comment]
This is really inconvenient. In identity 2.0 we got `TKey : IEquatable<TKey>` added as a generic parameter on `Usermanager`, `IUserStore` and others. Why the step back?

**Comment by HaoK** [comment]
Generic support is still there, but its no longer needed on the core identity apis, its a concern only of your store, the EF UserStore implementations still have TKey.

**Comment by shoe788** [comment]
Sorry, I'm not following. I dont see it [here](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.Extensions.Identity.Core/IUserStore.cs), for example

**Comment by HaoK** [comment]
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/UserStore.cs

**Comment by shoe788** [comment]
Internally though you hit the same inconvenience. IUserStore expects a string for Id and that implementation has `ConvertIdFromString` to solve that issue. UserManager then still returns `string` which requires a convert back to `int`, `long` etc.
