### ISSUE TITLE
ChangeEmailAsync allow invalid character

### ISSUE THREAD

**Issue by rukai-kooboo** [aspnet/Identity#1150]
When I call ChangeEmailAsync to change a user email from e.g. username@domain.com to username#@domain.com,  it goes well, the email is changed. 

But after I want to change back from username#@domain.com to username@domain.com, it says: "InvalidUserName:User name 'username#@domain.com' is invalid, can only contain letters or digits.

I use default UserOptions.AllowedUserNameCharacters.

**Comment by blowdart** [comment]
This is probably because, in templates, the validator for email addresses and the validator for usernames are different, but the templates use email as both the username, and the email address.

You could fix this by changing the user name validator to include the characters you want.
