### ISSUE TITLE
Bring back Normalize when we're upgraded to NS.Library 2.0

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Identity#1153]
The commit to revert: https://github.com/aspnet/Identity/commit/1ddc6b111aa4fe3bd4e2f6ebbbe71d7fc6e9d9ae

**Comment by ajcvickers** [comment]
@HaoK Can you bring back Normalize in the next couple of days so we can see if the issue is fixed? If not, we need to follow up to get the fix in for 2.0.

**Comment by ajcvickers** [comment]
See also #1149

**Comment by HaoK** [comment]
e594854cd28dfe89bc87606d9c49a2a99a1700d0
