### ISSUE TITLE
RoleManager.CreateAsync throw exception when the role name is existed

### ISSUE THREAD

**Issue by thiennn** [aspnet/Identity#1154]
RoleManager.CreateAsync throw exception when the role name is existed. I think it should not throw the exception but wrap the error into IdentityResult returned by RoleManager.CreateAsync with a clear error message.

Object reference not set to an instance of an object. at Microsoft.AspNetCore.Identity.EntityFrameworkCore.RoleStore`5.ConvertIdToString(TKey id)\r\n   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.RoleStore`5.GetRoleIdAsync(TRole role, CancellationToken cancellationToken)\r\n   at Microsoft.AspNetCore.Identity.RoleManager`1.GetRoleIdAsync(TRole role)\r\n   at Microsoft.AspNetCore.Identity.RoleValidator`1.<ValidateRoleName>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Identity.RoleValidator`1.<ValidateAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Identity.RoleManager`1.<ValidateRoleInternal>d__46.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Identity.RoleManager`1.<CreateAsync>d__30.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n

**Comment by thiennn** [comment]
Just found the reason: The Id of the Role is null, because we have implemented the custom IdentityRole

```cs
    public class ApplicationRole : IdentityRole<string, ApplicationUserRole, IdentityRoleClaim<string>>
    {
        public ICollection<RolePermission> Permissions { get; } = new List<RolePermission>();
    }
```

init the role's Id in constructor will fixed this isssue

```cs
    public class ApplicationRole : IdentityRole<string, ApplicationUserRole, IdentityRoleClaim<string>>
    {
        public ApplicationRole()
        {
            Id = Guid.NewGuid().ToString();
        }

        public ICollection<RolePermission> Permissions { get; } = new List<RolePermission>();
    }
```

But any way, I think we should have a check on the role's Id

**Comment by blowdart** [comment]
Our assumption is all roles have an id. This won't be fixed.
