### ISSUE TITLE
Attribute model for mapping user properties to claims

### ISSUE THREAD

**Issue by danroth27** [aspnet/Identity#1155]
You should be able to attribute user properties and have them get preserved as claims in the principal that identity creates. This will become more important as we move to exposing identity as a service.

**Comment by danroth27** [comment]
@javiercn

**Comment by brockallen** [comment]
This is already possible via the `IUserClaimsPrincipalFactory`

**Comment by danroth27** [comment]
Right, I believe you can implement an `IUserClaimsPrincipalFactory` that provides an attribute based model, but the idea here is that it would be nice if we provided an attribute based model out of the box.

**Comment by blowdart** [comment]
@javiercn Apparently you are doing this now. Can you tag what preview it will appear in, if it appears at all?

**Comment by javiercn** [comment]
It'll be preview2

**Comment by mkArtakMSFT** [comment]
Closing this as we're not doing this any more.
