### ISSUE TITLE
Microsoft.IdentityModel.Protocols double dependency on System.Net.Http

### ISSUE THREAD

**Issue by mxdumas** [aspnet/Identity#1158]
### Title
The Microsoft.IdentityModel.Protocols package refers twice the package "System.Net.Http".

```
<dependencies>
      <group targetFramework=".NETFramework4.5.1">
        <dependency id="System.IdentityModel.Tokens.Jwt" version="5.1.2" />
      </group>
      <group targetFramework=".NETStandard1.4">
        <dependency id="System.Collections.Specialized" version="4.3.0" />
        <dependency id="System.Diagnostics.Contracts" version="4.3.0" />
        **<dependency id="System.Net.Http" version="4.3.0" />**
        <dependency id="System.IdentityModel.Tokens.Jwt" version="5.1.2" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      **<frameworkAssembly assemblyName="System.Net.Http" targetFramework=".NETFramework4.5.1" />**
</frameworkAssemblies>

```
Since it is defined as a frameworkAssembly, it forces the framework version 4.0.0 instead of using 4.3.0. 

### Functional impact
It is not possible to get a more recent version of System.Net.Http when this package is present.

### Minimal repro steps
I created a .Net Core Web Api project and switched framework to .NET 4.6.2. 

1. Add a dependency to "System.Net.Http": "4.3.0"
2. Add a dependency to "Microsoft.IdentityModel.Protocols": "2.1.3"
3. Restore packages. 

### Expected result
Should use System.Net.Http 4.3.0

### Actual result
System.Net.Http version is 4.0.0

### Further technical details
Can be fixed by removing these lines:
```
<frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Net.Http" targetFramework=".NETFramework4.5.1" />
</frameworkAssemblies>
```

**Comment by blowdart** [comment]
Identity Model isn't part of identity. This should be filed over at https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet
