### ISSUE TITLE
Missing tag for versions 1.1.1

### ISSUE THREAD

**Issue by giggio** [aspnet/Identity#1164]
I would like to look at the source for 1.1.1, but I can't find a tag or release. Would you please add the tag?

For example, what source is related to this nuget package?
http://www.nuget.org/packages/Microsoft.AspNetCore.Identity.EntityFrameworkCore

**Comment by blowdart** [comment]
@pranavkm It's rumoured you just created branches at some point, but no tags. Can you help?

**Comment by pranavkm** [comment]
Here's the branch that shipped - https://github.com/aspnet/Identity/tree/rel/1.1.1. We forgot to change them in to tags at the end. There's a work item to go back and do this for our past releases.
