### ISSUE TITLE
ChallengeResult("Auth0", returnUrl ?? Url.Action("Index", "Purchase")); Syntax Error.

### ISSUE THREAD

**Issue by dcbrewster** [aspnet/Identity#1165]
Current Readme.Text File

3. Challenge the Auth0 middleware when the user logs in or out:

public class AccountController : Controller
{
    public ActionResult Login(string returnUrl)
    {
        return new ChallengeResult("Auth0", returnUrl ?? Url.Action("Index", "Home"));
    }

    [Authorize]
    public void Logout()
    {
        HttpContext.GetOwinContext().Authentication.SignOut(CookieAuthenticationDefaults.AuthenticationType);
        HttpContext.GetOwinContext().Authentication.SignOut(new AuthenticationProperties
        {
            RedirectUri = Url.Action("Index", "Home")
        }, "Auth0");
    }
}

returnUrl ?? Url.Action("Index", "Home" creates an error as ChallengeResult is expecting a controller.
public ChallengeResult(string loginProvider, ApiController controller)

Which is correct? or Which should be changed?

**Comment by blowdart** [comment]
This would be a question better asked of Auth0 if this is in their readme. GetOwinContext isn't even a function in asp.net core, this is from older versions of asp.net
