### ISSUE TITLE
Please help:  No idea how to customize the role system to implement design

### ISSUE THREAD

**Issue by rykr** [aspnet/Identity#1167]
Working on a website that is meant as a service.   Users will be able to register with the service and create communities.   Each community can have it's on admin users just for that community.  Of course the site will have admin users as well.

So I'd like to write code in razor something like  @if (User.IsAuthenticated() && User.IsInRole(community_id, "Admin")) {  .. do something .. }

How can I extend the IsinRole concept to take a value that scopes it like that?

Thanks!

**Comment by blowdart** [comment]
This isn't a identity question really, you could do it via authorization policies thought - please see https://github.com/blowdart/AspNetAuthorizationWorkshop to get started.
