### ISSUE TITLE
Concurreny exception when using UserManager in two web requests

### ISSUE THREAD

**Issue by nicolasr75** [aspnet/Identity#1169]
I have a simple web application with two buttons AddUser and DeleteUser. The buttons call corresponding Web APIs. The controller for the APIs gets injected a UserManager instance. When I call the AddUser API the following code runs successfully:

	var user = new ApplicationUser { UserName = model.Username, Email = model.Email };

	var result = await userManager.CreateAsync(user, model.Password);

When I then press the button to call the DeleteUser API the following code is executed and thows a concurrency exception

	var user = new ApplicationUser { UserName = username };

	var result = await userManager.DeleteAsync(user);

Exception: optimistic concurrency failure, object has been modified.

I guess I am misunderstanding how this is supposed to work. How can I use UserManager from different web requests (two different threads)? Or is there another recommended way to do this?

**Comment by HaoK** [comment]
You shouldn't be new'ing up a user to delete, you should be calling FindByName and deleting the user you get back, that's probably why you are getting the exception.
