### ISSUE TITLE
Change claims on middleware

### ISSUE THREAD

**Issue by kodithuwa** [aspnet/Identity#1170]
Hi,
My requirement is to remove existing (System.Security.Claims.ClaimsPrincipal) User claims and add new claims for suspended users.
Is this possible ?
Thanks
Chaminda

**Comment by blowdart** [comment]
Could you explain what you're trying to do? Are you trying to let a user login successfully, but then, based on a condition, change their identity?

**Comment by kodithuwa** [comment]
Yes, what i have done,
Add identity RoleClaims for roles and that role assign to a user, when a user login to the system, we can check user claims in ControllerBase.User.Claims (System.Security.Claims.ClaimsPrincipal). but, claims can not be edited, it has only get method.
Is there any method to edit these claims ???

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
