### ISSUE TITLE
Query: How we can create object of UserManager without using in built dependency injection ?

### ISSUE THREAD

**Issue by siddharthashw** [aspnet/Identity#1173]
Right with ASP.NET Core 1.1 there is only one way initialize the user manager class is to use the dependency injection.

But in my application, I have 2 DbContext. In ConfigureService, I have added 

`services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();`

Now I want to use UserManager of my CustomDbContext. Please suggest me a way to create object of UserManager without using DI.

My ApplicationDbContext -

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ProBotDbContext(DbContextOptions<ProBotDbContext> options)
            : base(options)
        {
            
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }
    }

My CustomDbContext - 

    public class CustomDbContext : IdentityDbContext<ApplicationUser>
    {
        #region Constructor
        public ProBotTeamDbContext(DbContextOptions<CustomDbContext> options) : base(options)
        {

        }
        #endregion  

        #region Override Methods
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
        }
        #endregion
    }

**Comment by Singularity222** [comment]
You'd create it just like any other object. The UserManager class has quite a few dependencies though. In my application I've created a custom UserStore class that uses Dapper instead of Entity Framework to persist the user data to the database. So I have some integration tests to make sure things are working correctly. So I have something like this:

Note: I've excluded some code that deals with object creation specific to my application.
```
var userStore = new UserStore(userRepository, roleRepository, mediator, clock);
IPasswordHasher<ManticoreUser> hasher = new PasswordHasher<ManticoreUser>();
var validator = new UserValidator<ManticoreUser>();
var validators = new List<UserValidator<ManticoreUser>> { validator };
ILogger<UserManager<ManticoreUser>> logger = new MockLogger<UserManager<ManticoreUser>>();
var userManager = new UserManager<ManticoreUser>(userStore, null, hasher, validators, null, null, null, null, logger);

// Set-up token providers.
IUserTwoFactorTokenProvider<ManticoreUser> tokenProvider = new EmailTokenProvider<ManticoreUser>();
userManager.RegisterTokenProvider("Default", tokenProvider);
IUserTwoFactorTokenProvider<ManticoreUser> phoneTokenProvider = new PhoneNumberTokenProvider<ManticoreUser>();
userManager.RegisterTokenProvider("PhoneTokenProvider", phoneTokenProvider);
```

**Comment by HaoK** [comment]
Yep what @Singularity222 said, you can just new it up and pass in the dependencies.

**Comment by mawadallah** [comment]
is there any functionality for creating SignInManager?
