### ISSUE TITLE
Question: Custom Password Validator

### ISSUE THREAD

**Issue by jbrozek** [aspnet/Identity#1174]
Given this setup

```
services.AddIdentity<TUser, TRole>()
	.AddUserStore<SqlUserStore<TUser>>()
	.AddRoleStore<SqlRoleStore<TRole>>()
	.AddPasswordValidator<CustomPasswordValidator>();
```
				
It appears that during execution of 

`	services.AddIdentity<TUser, TRole>()`
	
the default password validator is included via

`	services.TryAddScoped<IPasswordValidator<TUser>, PasswordValidator<TUser>>();`
	
then when calling .AddPasswordValidator() to implement an my CustomPasswordValidator a second validator is added to the list.

This ultimately places 2 validators in the UserManager.PasswordValidators collection, which upon execution both validators are ran.

What is the recommended practice to only included my CustomPasswordValidator so the default PasswordValidator is not executed?

**Comment by HaoK** [comment]
If you add it before AddIdentity then the TryAdd won't add it
