### ISSUE TITLE
Disable auto challange for a method or controller

### ISSUE THREAD

**Issue by claudio4** [aspnet/Identity#1177]
Please add a  data anotation for disable autochallange for a method/controller, something like that:

[DisableAutoChallange]
public class NotAutoChallageController

**Comment by HaoK** [comment]
There is no more auto challenge with Auth 2.0, see https://github.com/aspnet/Announcements/issues/232

**Comment by HaoK** [comment]
Typically the authorize policy for the controller/action will control what schemes are challenged
