### ISSUE TITLE
Cannot Query Claims from RoleManager<ApplicationRole>

### ISSUE THREAD

**Issue by WilliamWsyHK** [aspnet/Identity#1178]
Hi, when I tried to query some default Roles and RoleClaims from the database (I am using MySQL, and connector from Pomelo.EntityFrameworkCore.MySql 1.1.1) using EF Core, the RoleManager<ApplicationRole> does not return any claims for that role.
(ApplicationRole is inherited from IdentityRole)

**Background:** One Role associate with only zero / one Claim.

**Some short description of the flow:**
First check if the default exists in the database, if no then create the role with corresponding claims; if exists, check if there is the claim for this role, if the claim is not in the database, add it back.

**Expected behavior:** If the default claim exists, no action need to be done.
**Actual behavior:** No matter how many claims in the database associated with the role, RoleManager<ApplicationRole> will always return Claims with Count 0.

Here are some code, implementing the flow mentioned,
```C#
// role has type KeyValuePair<string, string>
foreach (var role in Roles)
{
    if (!await roleManager.RoleExistsAsync(role.Key))
    {
        var identityRole = new ApplicationRole(role.Key);
        identityRole.Claims.Add(new IdentityRoleClaim<string>()
        {
            ClaimType = role.Key,
            ClaimValue = role.Value
        });
        var result = await roleManager.CreateAsync(identityRole);
        if (!result.Succeeded)
        {
            var exceptionStringBuilder = new StringBuilder()
                .AppendLine($"Default role \"{role.Key}\" cannot be created.");
            foreach (var error in result.Errors)
            {
                exceptionStringBuilder.AppendLine($"    {error.Code}: {error.Description}");
            }
            throw new Exception(exceptionStringBuilder.ToString());
        }
    }
    else
    {
        var identityRole = await roleManager.FindByNameAsync(role.Key);
        // ^^^^^^^^^^^^^^^^^^^^^^^^^^
        // The above row returned Claims.Count == 0,
        // which I expect at least 1.
        // ||||||||||||||||||||||||||||||||||||||
        if (identityRole.Claims?.Count == 0)
        {
            var claim = new IdentityRoleClaim<string>()
            {
                ClaimType = role.Key,
                ClaimValue = role.Value
            };
            var result = await roleManager.AddClaimAsync(identityRole, claim.ToClaim());
            if (!result.Succeeded)
            {
                var exceptionStringBuilder = new StringBuilder()
                    .AppendLine($"Default role \"{role.Key}\" cannot add claim with value \"{role.Value}\".");
                foreach (var error in result.Errors)
                {
                    exceptionStringBuilder.AppendLine($"    {error.Code}: {error.Description}");
                }
                throw new Exception(exceptionStringBuilder.ToString());
            }
        }
    }
}
```

Thank you,
WilliamW

**Comment by blowdart** [comment]
This is because EF doesn't lazy load. The easiest way to fix this is to use RoleManager.GetClaims(role) before you access identityRole.Claims

**Comment by WilliamWsyHK** [comment]
Hmm... This is quite out of my expectation. In my point of view, should't it automatically load the claim for me when querying the IdentityRole? Or at least white down some docs for this behavior for now.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
