### ISSUE TITLE
Update RoleManager and UserManager to use Protected Internal rather than Private

### ISSUE THREAD

**Issue by jamiewest** [aspnet/Identity#1180]
**Problem**
When extending RoleManager or UserManager, we are unable to call the following methods in a derived class:

RoleManager
- ValidateRoleInternal
- UpdateRoleAsync

UserManager
- ValidateUserInternal
- UpdateUserAsync
- UpdateSecurityStampInternal

These are useful and have repeated in the base class to continue the same pattern of functionality.

**Solution**
Change these methods to use protected internal rather than private so they will be accessible in a derived class.

**Comment by HaoK** [comment]
@ajcvickers seems safe to move this to 2.1, no breaking changes here
