### ISSUE TITLE
IdentityServer 4 , ASP.NET Core- Custom User Manager?

### ISSUE THREAD

**Issue by alexandranb** [aspnet/Identity#1184]
Hello,

I have a problem with my app workflow process. I need to build an ASP.NET Core with IdS4 where all my clients and users are managed through an external API. I need to validate users and sing them into the app only using the API. My question is : do I need to have a custom user manager and retrieve in it all the users for password validation or can I just use the api to validate the pass and sign them in?

Thank you

**Comment by blowdart** [comment]
You could just call your external API when you get asked to validate the details.

**Comment by vgponline** [comment]
Hi, 

If you have any sample implementation for this customer api call with identityserver4, please share it.

Thanks
