### ISSUE TITLE
TaskCache inaccessible due to its protection level

### ISSUE THREAD

**Issue by jnegron357** [aspnet/Identity#1185]
I downloaded version 1.1.1 and attempted to run the sample application but got several errors concerning the TaskCache. The errors were two kinds "TaskCache inaccessible due to its protection level" and "TaskCache does exist in the current context". Am I missing something? NOTE: I got the same result when I tried running the 1.1.2 version.

Platform Details: 
VS 2017 Pro
Windows 7 Pro with Service Pack 1 64bit

**Comment by HaoK** [comment]
Will no longer be an issue going forward, was needed before the move to netstandard 2
