### ISSUE TITLE
Allow null UserName values

### ISSUE THREAD

**Issue by alataffective** [aspnet/Identity#1186]
To avoid potential enumeration of usernames, I want to set them only after the user has registered with, and confirmed their email address. Until the username is set, I would like it to be null.

As far as I can tell, to allow null usernames I have to provide my own implementation of `IUserValidator<TUser>`.

One way to do this, is to override `UserValidator<TUser>` (see https://stackoverflow.com/questions/43807787/how-to-allow-a-null-username-in-asp-net-core-identity). However, doing this means I lose email validation as it is not possible to override validation of username and email separately.

It's possible there's an elegant solution staring me in the face, but the best I can come up with so far is to provide a full implementation of `ValidateAsync`, not calling into `UserValidator<TUser>.ValidateAsync`.

All this seems a bit heavy going, just to support a null username.

I guess having something on `UserOptions`, e.g. `UserOptions.AllowNullUserName` would do it (though adding such options could start to get out of hand, unless representing a common requirement).

Alternatively or additionally, allow `UserValidator.ValidateUserName` and `UserValidator.ValidateEmail` to be overridden (they're currently private). This would give the needed flexibility but allow maximum reuse of existing code.

Any thoughts?

**Comment by alataffective** [comment]
I see that SignInManager needs a username to sign in. Hence the username cannot be null after all? I guess one way to support the scenario I'm looking at is to have both email and username set to the same value (as is the case in the Visual Studio solution template) and have a separate name property entirely (e.g. DisplayName), adding separate validation for this.

**Comment by HaoK** [comment]
Yeah user name is assumed to be non null , adding a display name is better
