### ISSUE TITLE
Allowing duplicate emails results in email not being validated

### ISSUE THREAD

**Issue by CMircea** [aspnet/Identity#1189]
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserValidator.cs#L51'

ValidateEmail should be called regardless of RequireUniqueEmail. There should be a separate method that checks if the email is unique and only call that if necessary, but always validate the email address.

However, the better design is to make unique email validation a requirement for the UserStore to fulfill (the same for usernames), because in this situation there is a race condition. The UserStore must be able to ensure the uniqueness of emails/usernames if requested (in SQL it's an unique index, in some document DB's you store a special document with the email as the document key).

**Comment by HaoK** [comment]
Actually, we can't do this, since this would effectively require an email, when today email is only required when this flag is on.

**Comment by HaoK** [comment]
Null/empty emails are allowed when this flag is off, which is intended right now

**Comment by CMircea** [comment]
Well... the ValidateEmail method can check if the email is required and not throw an error if the email is missing and it's optional.

**Comment by HaoK** [comment]
Oh I see, its only the valid email check that you want as opposed to that its non empty and valid

**Comment by CMircea** [comment]
Yep. That is skipped, but it shouldn't be.

**Comment by CMircea** [comment]
Might want to add the bug tag back, it is a bug if the email isn't validated in this case.

**Comment by HaoK** [comment]
Note to triage: @blowdart @ajcvickers this is probably a breaking change since with this bug fix, existing users with invalid emails that used to be able to function, would start failing to update/save until their emails were made valid.

**Comment by HaoK** [comment]
Might need a new flag to control this, an `alwaysValidateEmail` instead, so existing apps wouldn't be broken on upgrade.

**Comment by HaoK** [comment]
Discussed in triage, we decided it wasn't worth doing this, there is always the workaround of plugging in your own custom UserValidator to control the validation entirely
