### ISSUE TITLE
How to combine the aspnetusers table and my current user table?

### ISSUE THREAD

**Issue by hubaozhang** [aspnet/Identity#1191]
My understanding is there are two functions for PasswordSignInAsync in SignInManager (sign in the user in using the user name and password): (1) verify the user name and password against the ones saved in the Aspnetusers table; (2) create sign in cookie. 

I have my own user table, users. How to do combine the two tables? What are common practices?

**Comment by blowdart** [comment]
Do you really need identity? (Roles, claims etc.) or do you just want a login process? If it's the later then [using cookie authentication on its own](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?tabs=aspnetcore2x) might work well for you.
