### ISSUE TITLE
Add navigation properties to IdentityUserRole

### ISSUE THREAD

**Issue by thiennn** [aspnet/Identity#1203]
Is it possible to add 2 navigation properties

```cs
public virtual IdentityUser User { get; set; }

public virtual IdentityRole Role { get; set; }
```

So that we can join them easier.  For example I want to write a EF query to get a list of user together with their roles.

**Comment by HaoK** [comment]
We no longer have any navigation properties as of 2.0, you are free to add these yourself in your pocos.
