### ISSUE TITLE
Remove restriction to user UserManager<TUser> and RoleManager<TRole> directly

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/Identity#1204]
Hi,

Currently, there is an exception [thrown](https://github.com/aspnet/Identity/blob/master/src/Microsoft.AspNetCore.Identity/IdentityBuilder.cs#L179) if the UserManager isn't assignable from the custom type, this means that you can't specify `  app.AddUserStore<UserStore<User>>()` but you rather need to subclass it, and call `app.AddUserStore<AppUserStore>` when `AppUserStore` inherits from `UserStore<User>`.

Please change [the code](https://github.com/aspnet/Identity/blob/master/src/Microsoft.AspNetCore.Identity/IdentityBuilder.cs#L177) to check the exception from 

      !userManagerType.GetTypeInfo().IsAssignableFrom(customType.GetTypeInfo()))

to

      !customType.GetTypeInfo().IsAssignableFrom(userManagerType.GetTypeInfo()))

Same with [RoleManager](https://github.com/aspnet/Identity/blob/master/src/Microsoft.AspNetCore.Identity/IdentityBuilder.cs#L195).

Is there any reason why the `IsAssignable` was checked in this reversed way at first place? Am I getting anything wrong?

[Here](https://github.com/weitzhandler/Identity/commit/8247e7fff3263920e808ee24d3c631da4c24f18e) is a commit for it.

**Comment by HaoK** [comment]
This is meant only to be used with derived classes, AddIdentity already registers the base manager types.  See https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/IdentityBuilder.cs#L193 which would be a infinite loop if this was the same type.
