### ISSUE TITLE
App management UI

### ISSUE THREAD

**Issue by danroth27** [aspnet/Identity#1207]
To be able to use ASP.NET Core Identity for multiple apps you need to be able to manage the registered apps with some sort of UI:
- List, edit, remove, add registered application
- List, edit, remove, add redirect URIs
- List, edit, remove, add scopes
- Generate client secrets

This UI will ship as part of the templates.

**Comment by badre429** [comment]
Create REST endpoints for  management over webapi its more sample to integrate with SPA application

**Comment by weedkiller** [comment]
Hello, Can you also add manage roles and users per app scope or at least in general.

**Comment by tsirkin** [comment]
+1 for @weedkiller idea

**Comment by weedkiller** [comment]
Hello, when will this ship - for managing tenants & roles
