### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by rustd** [aspnet/Identity#122]
All Identity events (UserManager methods) should be logged. For eg.
- User Logged In
- Account Lockout Out
- Failed password attempts
- Email Sent
- 2FA code generated
- 2FA code verified
- 2FA code sent
- Can SMS service listen to these events
and more

**Comment by tugberkugurlu** [comment]
I am interested in this. How do we listen to these events and act on them?

**Comment by tugberkugurlu** [comment]
ow, how did I do that?

![image](https://cloud.githubusercontent.com/assets/328122/10978897/54c520b4-83f1-11e5-9e97-86f3a003d423.png)

**Comment by MohammadYounes** [comment]
@HaoK  How do we listen to these events ?
