### ISSUE TITLE
Support concept of ClientApplication in identity core

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#1244]
Should try to roll that into the 2.0 schema and eliminate the Microsoft.AspNetCore.Identity.Service.EntityFrameworkCore

This would likely look something like:
`Microsoft.Extensions.Identity`:
+ `ClientApplicationManager`, `IClientApplicationStore`

`Microsoft.Extensions.Identity.Stores`:
+ `IdentityClientApplication`, `IdentityClientApplicationClaim`, `IdentityClientApplicationScope`, `IdentityClientApplicationRedirectUri`

**Comment by brockallen** [comment]
What about scenarios where customers don't want their own token service and just want an identity database? Shouldn't all this config for the onprem B2C be in a separate DB and corresponding config system? // @danroth27

**Comment by HaoK** [comment]
Its no different than roles, today you can mark them as ignored in the model and just don't use the new manager, similar to what I'm sure you are doing with roles :)

**Comment by HaoK** [comment]
you can also just stick to IdentityStoreVersion1 which won't have any of the new stuff

**Comment by PinpointTownes** [comment]
@HaoK what's the problem with having these entities - specific to the B2C emulator - in a separate package?

**Comment by HaoK** [comment]
I'd like to address the underlying issue more directly which we've struggled with for a while anyways (how do we start adding features + schema in an optional way and let people opt out of specific schema/functionality).  If we solve that, there shouldn't be as much of an issue right?  You won't get any of the conflated stuff unless you ask for it via something like `AddEntityFrameworkStoresLatest/AddIdentity<TUser, TRole, TApplication>`.

**Comment by PinpointTownes** [comment]
> If we solve that, there shouldn't be as much of an issue right?

The problem is not adding new features nor modifying the DB schema (1), it's adding the "identity service" entities directly in the Identity core components, adding totally unnecessary tables for people that don't plan to use the B2C emulator.

I know the Azure folks are pushing hard to add their "Trojan horses" everywhere in ASP.NET Core to promote their stuff (e.g ApplicationInsights, that you can't avoid 'cause it's automagically added at runtime by VS in 2.0...), but at some point, you guys will have to be honest about this aggressive marketing strategy, instead of pretending you're just adding new features to make everyone's life easier (@danroth27... if you read me...) :smile: 

(1): if you do that, I'd love to see a `ClaimValueType` property for `UserClaim` :smile:

**Comment by HaoK** [comment]
Yeah so this is a bit similar to IdentityRoles, there's a bunch of people that will never use the RoleManager similarly. So it's still going to be 'additive' in that it doesn't affect UserManager.  There will be a new manager/store which will shield any 'taint' into existing identity APIs.  The only bleed will be in the default EF implementation/schema, which has versioning now, so if you don't want any of the taint, the old APIs won't give you any of it...

`AddIdentity<TUser, TRole>.AddEntityFrameworkStores()`

File a bug for (1), definitely something we can just do for the Version 2.0 schema

**Comment by brockallen** [comment]
These are two different features: Identity database and token service database. It's like saying let's put Program.cs and Startup.cs all into a single file. Oh wait...

Anyway, it does affect people even if they don't use the APIs -- it's non-trivial to not use the EF stuff out of the box and thus my DB gets polluted with all these "additive" features that are unused.

**Comment by PinpointTownes** [comment]
> Yeah so this is a bit similar to IdentityRoles, there's a bunch of people that will never use the RoleManager similarly.

Except roles have a real use in the core components: you can register them using the role manager, associate them to profiles via the user manager ; they are automatically added in the app authentication cookie and they can be retrieved from user code to define authorization policies.

If you add the "identity service entities" in the core components, they'll have absolutely no use.

> The only bleed will be in the default EF implementation/schema, which has versioning now, so if you don't want any of the taint, the old APIs won't give you any of it...

So the solution is to explicitly opt for an obsolete scheme, just to avoid having the identity service entities? :trollface: 

(BTW, this versioning story is insane... it will be a total PITA for community folks who maintain non-EF Identity stores as they'll have to develop a user/role store per version :open_mouth:)

**Comment by HaoK** [comment]
> (BTW, this versioning story is insane... it will be a total PITA for community folks who maintain non-EF Identity stores as they'll have to develop a user/role store per version 😮)

There's no concept of store versioning in core identity, this is an implementation detail for the EF store.  The base IdentityStoreOption lives in Microsoft.Extensions.Identity.Stores which you can think of as the opinionated helpers (that the default EF UserStore derives from and uses).  non-EF identity stores can continue having a single version no?  This madness is only needed if you want to enable the most definitely a big PITA scenario of optional/schemas features...

The UserManager continues to behave the same as it does today, it looks for whether the store implements interfaces, so custom stores just need to decide whether they want to implement IUserActivityStore or not, and IClientApplicationStore or not, they can totally just ignore them if they want.  They definitely do not have to do the crazyness I had to do to enable optional schema updates...

That said, if they are reusing the Identity.Store.UserStoreBase, they will need to pick a version (or always use latest)

**Comment by PinpointTownes** [comment]
> non-EF identity stores can continue having a single version no?

Only if there are no "breaking changes" between versions (e.g a table or a property name change, or a property type change). Is this something you can guarantee?

One thing I don't understand is why you have to support the 1.0 schema in 2.0 (for the EF provider). Why not providing a migration script/class to make the necessary changes in the DB?

**Comment by brockallen** [comment]
> One thing I don't understand is why you have to support the 1.0 schema in 2.0 (for the EF provider). Why not providing a migration script/class to make the necessary changes in the DB?

Unfortunately, EF migrations have never been and aren't currently designed for library authors, as they are provider specific.

**Comment by HaoK** [comment]
> Only if there are no "breaking changes" between versions (e.g a table or a property name change, or a property type change). Is this something you can guarantee?

Tables are an implementation detail for the stores themselves no?  Traditionally we only add things via IUserXyzStore interfaces in core.  But long story short for stores that aren't trying to reuse the default EF implementations, nothing has changed.

Things will be a bit more interesting going forward as I'm going to have to version things in the new Microsoft.Extensions.Identity.Store package

**Comment by PinpointTownes** [comment]
> Unfortunately, EF migrations have never been and aren't currently designed for library authors, as they are provider specific.

Doh, really? I thought the migrations stack was supposed to be decoupled from the actual relational provider and that things like `IMigrationsSqlGenerator` - implemented by the providers - were there to deal with the actual migration queries?

> Tables are an implementation detail for the stores themselves no?

Yeah, "table" was not the appropriate word, I meant "type"/"entity". Stores that depend on the CLR generic entities from `Microsoft.Extensions.Identity.Stores` to dynamically generate their queries will stop working correctly if types or properties are renamed or deleted (just like EF).

**Comment by HaoK** [comment]
Yeah so depending on anything in Microsoft.Extensions.Identity.Stores will be subject to the many of the versioning issues that the EF default implementation has.  The current existing path still is valid though, which is derive from UserStore which matches staying on the latest train.  Most of this complexity is there so people can stick to a specific version and not be broken...

The new pattern most likely will be the following for a new feature
- In Extensions.Core: New IXyzStore added with new Manager code using the store if its supported.
- In Extensions.Stores: Updates to the POCOs, almost always additive only, with a new major/minor version in IdentityStoreOptions
- New AspNet.EF: OnModelCreating/AddEntityFrameworkStoresVX matching new version in IdentityDbContext/UserStore to implement new functionality and add the new versioned stores

**Comment by PinpointTownes** [comment]
> almost always additive only, with a new major/minor version in IdentityStoreOptions

I suppose even that would break ORMs like EF6, that don't like when new properties are added :cry: 

> Most of this complexity is there so people can stick to a specific version and not be broken...

I still don't get why it's preferable to the "database migration" path. A schema change is no different from a API/contract change. Folks who migrate to 2.0 should also migrate their DB to be compatible with 2.0 (using migration scripts or by manually applying the needed changes if they use a provider that doesn't support migrations).

**Comment by HaoK** [comment]
Historically the 'database migration' path has been rocky, the intent is so folks can control when they want to migrate, as opposed to requiring migrations which tends to really make the bar for schema changes really high

**Comment by brockallen** [comment]
> Historically the 'database migration' path has been rocky

This is the only way a 1.x project can move to use these new 2.0 features, right?

**Comment by danroth27** [comment]
@HaoK Let's hold off on this until we've had a chance to more fully discuss it. I'd like to avoid baking in any identity service concepts to ASP.NET Core Identity that might impede the development of 3rd party identity service implementations.

@PinpointTownes If you're seeing issues with the local app insights integration in VS or you have general feedback on the feature, then please file an issue in the https://github.com/aspnet/azureintegration repo so we can discuss. The VS integration is intended to aid with local debugging, but if it's causing harm or irritation then we should talk about whether it's the right default behavior.

**Comment by HaoK** [comment]
@danroth27 Sure that's why I created an issue instead of a PR.   I'd also like to continue discussions on what the final name of the "identity service" should be, because I don't think there are currently many fans of the current naming...

In terms of constraints from previous discussions, it sounds like OIDC, Azure, Tokens, and Server were ruled out from names for various reasons, which is why we ended up with something pretty generic and confusing.  

Identity is already a "service" today, but I'm guessing the intent was to imply Identity providing authentication as a  service.  So how about `Identity.Authentication` as the namespace/term we use to describe this.

**Comment by PinpointTownes** [comment]
> The VS integration is intended to aid with local debugging, but if it's causing harm or irritation then we should talk about whether it's the right default behavior.

Oh it's not, but it certainly gives Azure's services an unfair advantage their competitors can't have (and will likely never have). But I suppose telemetry is one of these... strategic things? :trollface: 

> @danroth27 Sure that's why I created an issue instead of a PR. I'd also like to continue discussions on what the final name of the "identity service" should be, because I don't think there are currently many fans of the current naming...

The naming is just the visible part of the iceberg, IMHO.

@danroth27 pretends that IdentityService should be regarded as a development server meant to offer a smooth migration to B2C or OSS projects but that's not really the impression I have when seeing all these tickets: https://github.com/aspnet/Identity/labels/identity-service.

If your intention is to make this thing a "real" OIDC server (that can be "officially" used in production), then you should be clear and sincere about that. Having another competitor in the field is not a bad thing - people like and need having multiple options - but the way you Microsofties communicate about this project is not really satisfying.

**Comment by HaoK** [comment]
Yeah, but as of now, there aren't a lot of new 2.0 features in core they'd get (asking for creation date/last sign in/password change).  We'll likely be adding some behavior around enforcing password expiration policy, but basically we would be forcing everyone to migrate for basically no features

**Comment by HaoK** [comment]
@PinpointTownes I'm not sure how much tracking you are going to get on moving the whole 'iceberg'.  But I believe we can at least give it a sensible name :)

**Comment by blowdart** [comment]
OK we've talked about this, and @HaoK has promised that he can make the tables optional, so they won't appear unless you ask for them in code in your constructors. Which hopefully alleviates @brockallen's concern.

Naming on the other hand is a whole other discussion :D

**Comment by HaoK** [comment]
Moving to preview 2 for visibility

**Comment by HaoK** [comment]
As part of this work, we would also make IdentityRoles optional

**Comment by brockallen** [comment]
> As part of this work, we would also make IdentityRoles optional

Sounds interesting.
