### ISSUE TITLE
SignIn not working with ASP.NET Identity 2.0 and 1.1 Core side by side

### ISSUE THREAD

**Issue by Ponant** [aspnet/Identity#1250]
1) 1.1 Identity , register user a@gmail.com + pwd
2) 2.0 Identity , register user b@gmail.com + pwd

All done on the same browser

**Result**: Step 2 will persist the user to the DB but login will not occur. Now logout from 1.1 and refresh 2.0, the user b@gmail.com appears as logged in.

**Comment by blowdart** [comment]
It's not clear what you're trying to do here.

Are these separate applications? Are they on separate URLs?

**Comment by Ponant** [comment]
@blowdart , seprate applications, seprate urls

**Comment by blowdart** [comment]
And both are identity core?

**Comment by Ponant** [comment]
Yes as the title says, sorry for having been short!

**Comment by blowdart** [comment]
So separate applications are separate by default, they don't share login cookies (although you can kinda force the database). So logging out in 1.1 identity is not going to affect 2.0.

**Comment by Ponant** [comment]
But it does...

**Comment by blowdart** [comment]
It shouldn't, unless you have a fixed app identifier.

Do you have a simple repo anywhere @HaoK can look at?

**Comment by Ponant** [comment]
I created each template as it comes from VS 2017 (and preview for 2.0)

**Comment by blowdart** [comment]
Strange. Ok, @HaoK can you take a look at this? (Please note it's a public holiday today in the US, so it'll be a couple of days)

**Comment by Ponant** [comment]
BTW, I do not know think this is related but IIS express shows 2 localhost ports for the 2.0 Core app.

**Comment by HaoK** [comment]
Is the 2.0 app using the identity service stuff?  That uses a different cookie and really is quite different than 1.1 as it's not using the identity cookie for login.

**Comment by danieloprado** [comment]
Is both hosted at localhost? Same domain, same cookie storage...

**Comment by Ponant** [comment]
@HaoK , yes, for the 2.0 I am using the identity service stuff. New project--> asp.net core 2.0 with individual in-app store. @danieloprado , I am on localhost for both on my W10 dev machine. I did not touch the code of neither projects.

**Comment by Ponant** [comment]
I just made 2 created two other projects, same issue.

**Comment by danieloprado** [comment]
See: https://stackoverflow.com/questions/1612177/are-http-cookies-port-specific

> Similarly, cookies for a given host are shared across all the ports on that host, even though the usual "same-origin policy" used by web browsers isolates content retrieved via different ports.

**Comment by Ponant** [comment]
@danieloprado , I do not think this is the same discussion here. The issue is not present if you use 2 .Net Core 1.1.

**Comment by Ponant** [comment]
@HaoK , it seems to be due to the AspNetCore.AntiForgery cookie.

**Comment by blowdart** [comment]
Do you have data protection configured to share a keyring? https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview

**Comment by Ponant** [comment]
I am running on the template provided by VS 2017 for .Net Core 1.1 and VS 2017 Preview 1 for .Net Core 2.0; these were untouched and do not seem to have data protection configured. Where you able to reproduce the bug?

**Comment by HaoK** [comment]
Closing as this was a preview 1 issue and we didn't ship identity service in 2.0
