### ISSUE TITLE
The foreign key {'UserId'} on entity type 'IdentityServiceApplication' cannot be marked as optional

### ISSUE THREAD

**Issue by gbfromhb** [aspnet/Identity#1251]
Have been using the Identity.EntityFrameworkCore and it is working with an existing User table with the Primary key Id column being an integer. Now trying to get the new Identity.Service.EntityFrameworkCore ver: 1.0.0 preview 1 working, and having the following problem. "The foreign key {'UserId'} on entity type 'IdentityServiceApplication' cannot be marked as optional". Here is one attempt at resolving this using the Fluent API. 

```
builder.Entity<IdentityServiceApplication>()
         .Property(a => a.UserId)
         .IsRequired(false);
```

I have tried some inheritance:

```
public class MyIdentityServiceApplication : IdentityServiceApplication<Guid, int> {
      public new int? UserId {
         get { return base.UserId == 0 ? (int?)null : base.UserId; }
         set { base.UserId = value.HasValue ? value.Value : 0; }
      }
   }
```
Here is how the DbContext is set up.

```
public class HubActionDbContext : IdentityServiceDbContext<HubUser, Role, int, IdentityServiceApplication<Guid, int>, Guid> {
...
}
```
Looking for some advice, or confirmation that there might be a bug.

**Comment by blowdart** [comment]
@javiercn

**Comment by javiercn** [comment]
That foreign key is going to go away before RTM, but I see the issue, when the relationship is optional the key needs to be Nullable<T>

**Comment by gbfromhb** [comment]
OK, let me get this straight. I think you and I saw the same issue the foreign key was causing the problem, and your are saying  this key is going away on a future release, right? So it sounds like problem solved.

**Comment by javiercn** [comment]
Yep

**Comment by gbfromhb** [comment]
Thanks
