### ISSUE TITLE
Question: Why many of async methods return IdentityResult with errors data instead of normally throwing exceptions 

### ISSUE THREAD

**Issue by ivankarpey** [aspnet/Identity#1252]
Why many of async methods return `IdentityResult` with errors data instead of normally throwing exceptions. This behavior seems pretty strange for me. Since if before I just should be able to handle problematic cases with `try/catch` now it's required to actually dig in results filed and write quite a unpleasant code.

so instead clean and traditional
```
try{
     await userManager.CreateUserAsync(new User());
}catch(Exception e){
     .... //somehow handling bad case
}
```

it's required to write something like

```
var result = await userManager.CreateUserAsync(new User());'
if(results.Errors != null){
      ...//trying to do something there, or maybe even parsing ienumerable to get error type and go to appropriate branch to handling specific case. 
      // Also, what's about finally block in that case??? 
}
```

So this is looks completely unclear for me. Is it possible to change those behavior to classical, error throwing model?

**Comment by blowdart** [comment]
Exceptions are, well, exceptional. Like database is on fire. Duplicate usernames, or validation failures are typical errors, they're not exceptional, so we don't use exceptions.

**Comment by Ibro** [comment]
duplicate username doesn't really resonate like typical error
