### ISSUE TITLE
Cleanup: Move more classes from Microsoft.AspNetCore.Identity into Extensions

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#1253]
IdentityBuilder, and a few other classes like validators can be moved into Extensions as well

**Comment by HaoK** [comment]
@ajcvickers is this still considered cleanup?  Basically moving classes between assemblies, would not have any real customer impact as currently they always get the AspNetCore assembly, we'd just be enabling more stuff working when using the new Microsoft.Extensions.Identity...

But using a strict interpretation of 'features', this would be enabling some scenarios around that (using Microsoft.Extensions.Identity directly)...

**Comment by ajcvickers** [comment]
@HaoK If it doesn't impact any customer experience and won't break apps, then it's fine to do post preview2.

**Comment by HaoK** [comment]
Tracking this via https://github.com/aspnet/Identity/issues/1269
