### ISSUE TITLE
Setting Cookies.ApplicationCookie.Events from services.Configure<IdentityOptions> prevents security stamp validation from working

### ISSUE THREAD

**Issue by AbdelrahmanGIT** [aspnet/Identity#1258]
### Setting Cookies.ApplicationCookie.Events from services.Configure<IdentityOptions> prevents security stamp validation from working
*setting events inside configure service disables security stamp validation check which is hard to spot*  

### Functional impact
Disables security stamp validation completely without any errors and it's hard to spot

### Minimal repro steps
1. Create project with identity in asp.net core 1.1.
2.configure identity options.
3. Add this segment:
         `options.Cookies.ApplicationCookie.Events = new CookieAuthenticationEvents()
                {
                    OnRedirectToLogin = (context) =>
                    {
                          //Some code
                          Task.FromTesult(0);
                     }
                   }`
And to fix this problem you need to move events from configure identity options to app.UseCookieAuthentication
### Expected result
Custom event to excute without effecting security stamp validation

### Actual result
Events code works but Security stamp validation stops working.

### More details
(https://stackoverflow.com/q/44284627/5895031)

**Comment by HaoK** [comment]
Can't you just modify the existing ApplicationCookie.Events instead of new'ing it up?  Doesn't that solve things?
