### ISSUE TITLE
Move IdentityOptions from Microsoft.AspNetCore.Builder to identity namespace

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#1261]
I guess it has been in Microsoft.AspNetCore.Builder all this time, this used to be the pattern so intellesense would work before we switched consistently to lambdas everywhere...  Seems like we should welcome the options class home.  This realistically shouldn't break many apps, as its rare for the options type to be used by itself without any other identity classes...  Maybe something we can do post preview 2...  @ajcvickers

**Comment by HaoK** [comment]
The benefit isn't that big, so I don't think its worth adding any build stability issues to try and slam it in right now

**Comment by PinpointTownes** [comment]
If you do that, please also consider moving all the scheme handlers options (in aspnet/Security) to their respective repos :smile:

**Comment by HaoK** [comment]
You mean moving the options for the security/auth handlers to the right namespace?  I think they are in the right repo today :)

**Comment by PinpointTownes** [comment]
lol yeah, I meant namespace, not repo, sorry for the confusion :sweat_smile:

**Comment by HaoK** [comment]
@ajcvickers ok for me to move the options type to the proper namespace now?  We already moved it to a different assembly in (Extensions), might as well move it to the proper home namespace

**Comment by ajcvickers** [comment]
Yes

**Comment by HaoK** [comment]
eb3ff7fc32dbfff65a1ba6dfdca16487e0f6fc41
