### ISSUE TITLE
Fix and unskip broken tests

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Identity#1266]
ValidateLogoutUri_FailsIfTheUriIsRelative and ValidateRedirectUri_FailsIfTheUriIsRelative were failing, they're skipped for preview2 so we can get a passing build of identity as a whole.

**Comment by Eilon** [comment]
@javiercn do you have an update on this?

**Comment by javiercn** [comment]
These are related to identity as a service, they only fail on Linux because of System.Uri having a different behavior. Given that we are not shipping it on 2.1 I'm moving it out the milestone.

**Comment by javiercn** [comment]
We removed the code
