### ISSUE TITLE
PasswordSignInAsync(TUser user, string password, bool isPersistent, bool lockoutOnFailure) could return SignInResutl.Failed instead of throw

### ISSUE THREAD

**Issue by Ponant** [aspnet/Identity#1270]
In a way similar to 
`PasswordSignInAsync(string userName, string password,  bool isPersistent, bool lockoutOnFailure)` , 
`PasswordSignInAsync(TUser user, string password,  bool isPersistent, bool lockoutOnFailure)` could return `SignInResult.Failed` instead of throwing when `user = null`.

**Comment by HaoK** [comment]
Where does it throw?

**Comment by Ponant** [comment]
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L258

**Comment by HaoK** [comment]
The two scenarios are different, one is clearly a developer error, passing in a null user, the API that takes a username, returns failed if you pass in a user name that doesn't exist.

**Comment by Ponant** [comment]
@HaoK , I see what you mean, and thought about it before raising up this thread. However, in my opinion, I think it is a pity not to take advantage of the return type `SignInResult.Failed`. this will avoid a dev to add the check `if(user !=null)`. Cheers

**Comment by HaoK** [comment]
So its intentional in general you should never pass a null user into any identity APIs.
