### ISSUE TITLE
Consider making SignInOrTwoFactorAsync public

### ISSUE THREAD

**Issue by Ponant** [aspnet/Identity#1274]
Here https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L680

This will help in overriding the `PasswordSiginInAsync` method 
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L252
. The method `SignInOrTwoFactorAsync  `is used only in `PasswordSiginInAsync `and `ExternalLoginSignInAsync `.
See discussion here https://github.com/aspnet/Identity/issues/1265 . I am happy to PR for this if this sounds reasonable.
Thanks

**Comment by HaoK** [comment]
Feel free to submit a PR, I think protected virtual is more appropriate as this still isn't something Controllers should call directly for example.

**Comment by Ponant** [comment]
@HaoK ok, done.

**Comment by HaoK** [comment]
98263cca298fb234344c436dd2ee866ab9567a22
