### ISSUE TITLE
Consider backing out schema changes store versioning until 2.1

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#1278]
We should consider backing out https://github.com/aspnet/Identity/commit/be8232d3f9c7a312314ab42dfe37047ec3b16665 since identity service didn't make it into 2.0, this would give us more time to react/update things without having backcompat issues.

The main motivation from my perspective is not introducing a 2.0 schema change that only adds 2 properties, that seems like a waste.

There doesn't appear to be anything preventing us from bringing all of this back as a new feature in 2.1 as it doesn't affect anything outside of the EntityFrameworkCore.

We'd also back out the new activity/sign in/ password feature as well since that's what drove the schema changes.

cc @ajcvickers @divega @blowdart

**Comment by HaoK** [comment]
Basically we should only add this complexity when we have a large schema update/optional features that are compelling enough to justify all of this stuff...

**Comment by HaoK** [comment]
After talking to @ajcvickers plan is to back these out for now, we can add this back along with our next schema update, most likely in 2.1

We'll be focusing on making Roles optional at the new lower Microsoft.Extensions.Identity layer instead

**Comment by HaoK** [comment]
a9192d99dc79e64c6ebc8bc434917af8bea02573

**Comment by kinosang** [comment]
Will this feature be add back for 2.1?
