### ISSUE TITLE
ToTable does not change the Table name

### ISSUE THREAD

**Issue by JStepien90** [aspnet/Identity#1280]
Hello,

I use Identity with the configuration with EntityFramework and SqlServer. I'm trying to change the default names of identity tables. Below it's my code to create database context. 

 public class XXXContext : IdentityDbContext<User, IdentityRole<int>, int>
    {
        public XXXContext(DbContextOptions options) : base(options)
        {

        }
        public DbSet<User> User { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //Identity
            modelBuilder.Entity<User>().UserMap();

            modelBuilder.Entity<IdentityRole<int>>(entity =>
            {
                entity.ToTable(name: "AspNetRole", schema: "Security");
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).HasColumnName("AspNetRoleId");

            });
          
            base.OnModelCreating(modelBuilder);
        }
    }

    public class User : IdentityUser<int>
    {
    }

    public static class UserMappings
    {
        public static void UserMap(this EntityTypeBuilder<User> entityTypeBuilder)
        {
            entityTypeBuilder.ToTable(name:"AspNetUser", schema:"Security");
            entityTypeBuilder.Property(x => x.Id).HasColumnName("BaseUserId").ValueGeneratedOnAdd();
        }
    }

Why ToTable ignore the tables names? Schemes names are modified correctly. Is it a bug or I do something wrong?

**Comment by VahidN** [comment]
`base.OnModelCreating(modelBuilder);` will override your custom settings. so put it at the beginning of the `OnModelCreating` method.

**Comment by ajcvickers** [comment]
Closing as @VahidN has answered the question.
