### ISSUE TITLE
Shadow properties are introduced while configuring Identity schema manually

### ISSUE THREAD

**Issue by aneequrrehman** [aspnet/Identity#1290]
I am trying to change the schema of `AspNetUserRoles` table because I have two other fields `FieldA` and `FieldB` and I want both of these fields to be primary keys.

When I do something like this:

```C#
 builder.Entity<ApplicationUserRole>(b =>
            {
                b.HasKey(r => new { r.UserId, r.RoleId, r.FieldA, r.FieldB });
            });
```

It configures the primary keys but doesn't remove the default Unique Constraint that is on `UserId` and `RoleId`. What I want is all four fields to be primary key, and remove the default unique constraint.

I have tried various configurations, but all in vain. So I ended up trying to create the identity schema myself by removing the call `base.OnModelCreating()` and instead copying all the OnModelCreating code from the github repository. When I add the migration, it introduces new shadow properties. E.g. in the generated migration, `AspNetUserLogins` table has these fields: 

LoginProvider, 
ProviderKey, 
ApplicationUserId, 
ProviderDisplayName, 
UserId

Where `ApplicationUserId` is introduced automatically. Why is this shadow property introduced? And this happens with all other identity tables as well.

**Comment by blowdart** [comment]
@HaoK

**Comment by HaoK** [comment]
@ajcvickers @divega any ideas?

**Comment by rmja** [comment]
I am having the same problem. A fix is to explicitly set the foreign key when creating the model, e.g.:

```
protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<ApplicationUser>()
                .HasMany(x => x.Claims)
                .WithOne()
                .HasForeignKey(x => x.UserId);

            builder.Entity<ApplicationUser>()
                .HasMany(x => x.Logins)
                .WithOne()
                .HasForeignKey(x => x.UserId);
        }
```

I think the problem is related to the removal of the navigation properties in https://github.com/aspnet/Announcements/issues/263.

**Comment by ajcvickers** [comment]
@rmja's answer is essentially the correct way to do this. In general, if the Identity model is going to be modified to add/remove relationships or keys that participate in relationships, then other parts of the model will need to be changed to make it consistent again. 

Issue #1447 is about improving the documentation for this.
