### ISSUE TITLE
Trying to build rel/1.1.0 locally: 'TaskCache' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by tlycken** [aspnet/Identity#1301]
I've cloned this repository, opened Identity.sln in Visual Studio 2017 (Version 15.2 (26430.14) Release, pro edition, to be precise) and tried to compile, but it fails [here](https://github.com/aspnet/Identity/blob/rel/1.1.0/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L695) with the error `'TaskCache' is inaccessible due to its protection level.`.

My ultimate goal is to obtain debugging symbols so I can step into [ExternalLoginSignInAsync](https://github.com/aspnet/Identity/blob/rel/1.1.0/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L458) and figure out why my login attempt fails, but just activating Microsoft Symbol Servers and adding https://nuget.smbsrc.net to symbol sources didn't help, so I'm trying to add a source reference instead.

How can I get past these errors, so I can step through the method and see what's going on?

**Comment by blowdart** [comment]
What else are you building? You're going, at a minimum, also compile in https://github.com/aspnet/Common/tree/rel/1.1.0/src/Microsoft.Extensions.TaskCache.Sources

**Comment by tlycken** [comment]
Hm, I didn't build anything but the sources from this repo. I'll try again after also building that.

Do they have to reside in some special relation to each-other on the file system? Is it documented somewhere that there's a dependency on building that locally, too?

**Comment by kangze** [comment]
i hava some question, did you get it? why Microsoft Dever did not care it?

**Comment by tlycken** [comment]
@kangze I actually never managed to build this locally, mostly because I figured out what my real problem was anyway (I only needed a local build to step through with the debugger).
