### ISSUE TITLE
SignInManager, IUserManager and IRoleManager - Interfaces needed

### ISSUE THREAD

**Issue by generik0** [aspnet/Identity#1308]
Hi

Why is there no interfaces for all the identity managers e.g.
SignInManager, IUserManager and IRoleManager. it is impossible to:

.AddUserManager<UserManager>()
.AddRoleManager<RoleManager>()
.AddSignInManager<SignInManager>() 

Use case:
Is a standard (web) application we want to deploy to different sites with different user, role manages to be handled by the IoC
So that each enterprises special conditions identity reimplementation can be meet.

Please add the interfaces like with the stores, etc.

**Comment by blowdart** [comment]
Dupe of https://github.com/aspnet/Identity/issues/215

**Comment by generik0** [comment]
Thanks. Didn't see that...
