### ISSUE TITLE
Should Identity set DefaultForbidScheme and DefaultSignOutScheme?

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Identity#1311]
/cc @HaoK

**Comment by HaoK** [comment]
Those still fallback to Challenge/SignIn which are set

**Comment by PinpointTownes** [comment]
Sure. But wouldn't that be clearer if they were set by Identity? (+ it would avoid the fallback logic).
I discovered this oddity when creating my own "post initializer" for `AuthenticationOptions`, so I presume other people might be confused by that too.

**Comment by PinpointTownes** [comment]
BTW, is there any particular reason you need the double-fallback (`DefaultForbidScheme` -> `DefaultChallengeScheme` -> `DefaultScheme`), now that we have a universal fallback scheme (`DefaultScheme`)?

**Comment by HaoK** [comment]
Nothing has really changed conceptually, before we used DefaultAuthenticateScheme as the universal fallback scheme, now we have an explicit one.  Without the double fallback you'd have really weird behavior where challenge/forbid and sign in/out would be out of sync, its still possible if they set forbid/sign out without setting sign in/challenge, but that's almost certainly going to be something they notice in their app.

**Comment by PinpointTownes** [comment]
That still seems too magical for me (a single fallback should be enough), but okay. Thanks for the explanation :sweat_smile:
