### ISSUE TITLE
'User' does not contain a definition for 'Roles' and no extension method 'Roles' acceptiong a first argument of type 'User' could be found(are you missing a using directive or an assembly reference ?)

### ISSUE THREAD

**Issue by marcosph** [aspnet/Identity#1316]
I'm using net core Version="2.0.0-preview2-final"
Note: Image of the error
![one](https://user-images.githubusercontent.com/5003847/28216995-fab7a66c-6889-11e7-9bf6-64b775fbf796.png)

**Comment by HaoK** [comment]
The navigation properties were removed from IdentityUser since we weren't populating them anyways, you will need to add them back in your application specific user class.

**Comment by HaoK** [comment]
I filed an announcement for this breaking change here: https://github.com/aspnet/Announcements/issues/263
