### ISSUE TITLE
Missing the UserManager.VerifyPasswordResetTokenAsync method

### ISSUE THREAD

**Issue by MovGP0** [aspnet/Identity#1320]
I want to implement a password change flow. Naturally I would expect it to work like this: 

```csharp
var token = await UserManager.GeneratePasswordResetTokenAsync(user);
var result = await UserManager.VerifyPasswordResetTokenAsync(user, token);
```
Unfortunately, I only find this method: 
```csharp
var result = await UserManager.VerifyUserTokenAsync(user, "tokenProvider", "ResetPassword", token);
```
This makes it confusing what to use as token provider and purpose strings. Allowing to use custom token providers and purposes seems like a good idea, but when just starting out, there should be a default implementation.

**Comment by MovGP0** [comment]
Implementation is pretty straight-forward: 
```csharp
public async Task<bool> VerifyUserTokenAsync(TUser user, string token)
{
     var tokenProvider = Options.Tokens.PasswordResetTokenProvider;
     return await VerifyUserTokenAsync(user, tokenProvider, "ResetPassword", token);
}
```

**Comment by HaoK** [comment]
You are looking for the ResetPassword method I believe:

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.Extensions.Identity.Core/UserManager.cs#L862

**Comment by MovGP0** [comment]
No I don't. I want to implement the token verification.

**Comment by blowdart** [comment]
This was a deliberate design choice, to avoid the weird intermediate state of verifying a token, but not using it for an action. Your work around is correct, but its unlikely the flow/api will change, unless we get more people asking for this.

**Comment by sanmscse** [comment]
Hi,

What value we have to set for _userManager.Options.Tokens.AuthenticatorTokenProvider.

I'm using 2FA without Entity Framework in core2.0. i've to write custom methods for token generation and verification. the below method reuires string for AuthenticatorTokenProvider. Does anyone know what provider i'veto give?

var is2faTokenValid = await _userManager.VerifyTwoFactorTokenAsync(
                user, _userManager.Options.Tokens.AuthenticatorTokenProvider, verificationCode);


Thanks,
Saravanan
