### ISSUE TITLE
Doesn't support hierarchyid type

### ISSUE THREAD

**Issue by seven1986** [aspnet/Identity#1323]
I need add a property in ApplicationUser Class which datatype is hierarchyid.
How can I do that?

**Comment by craigahanson** [comment]
Can you not simply inherit from ApplicationUser and add the properties you want to your new class?

**Comment by blowdart** [comment]
This is more of an entity framework question, they would need to support it. @divega any idea on a timescale here?

**Comment by blowdart** [comment]
This is by design in EF. You should ask in the EF repo about this. https://github.com/aspnet/EntityFrameworkCore
