### ISSUE TITLE
User manager constants should be publicly accessible

### ISSUE THREAD

**Issue by usarskyy** [aspnet/Identity#1325]
Whenever somebody implements `IUserTwoFactorTokenProvider` interface, he usually wants to be able to verify token based on its purpose. 
"purpose" argument comes from `UserManager` and all its values are currently hardcoded directly in `UserManager` as three constants:

```
        protected const string ResetPasswordTokenPurpose = "ResetPassword";
        protected const string ChangePhoneNumberTokenPurpose = "ChangePhoneNumber";
        protected const string ConfirmEmailTokenPurpose = "EmailConfirmation";
```

The problem is that developer cannot reference those constants and would need to introduce "magic strings" in his code.

Task summary:
As a developer, I'd like to be able to write code like this:
```
switch(purpose) {
    case UserManager.ResetPasswordTokenPurpose:
    // do some password reset specific verification here
    break;
}
```
instead of hardcoding purpose string like now:
```
switch(purpose) {
    case "ResetPassword":
    // do some password reset specific verification here
    break;
}
```

**Comment by MovGP0** [comment]
to be precise, those constants should be in a dedicated static class, rather than in the `SignInManager` (because of the Single-Responsibility-Principle).

**Comment by usarskyy** [comment]
Single Responsibility Principle is about something else, but if those constants are extracted into a separate class, like is suggested by @MovGP0, that is easy to find (like FacebookDefaults for FacebookOptions, for example) then, as a developer, I would be also satisfied.

**Comment by blowdart** [comment]
We'll look at this for 2.1

**Comment by HaoK** [comment]
We'll just make them public for now, we can consider extracting the constants into a shared class in the future, there is an IdentityConstants but its in the wrong layer for these purposes to go.
