### ISSUE TITLE
SignInManager<T>.SignInAsync(user) persists more changes than expected.

### ISSUE THREAD

**Issue by ctolkien** [aspnet/Identity#1326]
(Using 2.0.0-preview2)

`await _signInManager.SignInAsync(user, isPersistent: true);` this will fire off a call to the database to persist information like the `LastLoginDate`. However, the update statement it issues will update _all_ properties on the `user` being passed in. This means that any other changes which have been made against `user` will be persisted against the database.

This is, at the very least... surprising or potentially a bug. It is not obvious that the action of signing someone in would update potentially unrelated database fields.

**Comment by blowdart** [comment]
This is how POCOs/EF works unfortunately. Because LastLoginDate is a property of the user the entire user gets saved. We can't change it.
