### ISSUE TITLE
ASP.NET Core Web App doesn't support in-app identity provider

### ISSUE THREAD

**Issue by sidshetye** [aspnet/Identity#1329]
Using Visual Studio 2017 Preview (15.3.0 Preview 5.0) + .NET Core 2.0 we currently don't see an option to create an in-app / native / on-premise identity provider when selecting "Individual User Accounts". Nor do we see support for people coming from `Microsoft.AspNet.Identity.Core` 2.x. See image below which only shows Azure AD B2C. Having Azure hosting options is fine as opt-in but they shouldn't displace native choices. 

![image](https://user-images.githubusercontent.com/2595088/28540993-30c5d9e2-706c-11e7-8ad1-450303e9a862.png)

**Comment by blowdart** [comment]
This could be a bug in your preview version. 

![snip_20170802112038](https://user-images.githubusercontent.com/796298/28888226-b058be90-7774-11e7-97a5-ba06e33713d5.png)

**Comment by vdevappa** [comment]
When is this coming to VS 2017 RTM version?

**Comment by sidshetye** [comment]
It's not a bug - see the background window of my submitted screenshot (`WebAPI`)

**Comment by sidshetye** [comment]
I mean it's not a bug on my installation instance, it's a bug in the product / template itself as reported.

**Comment by vdevappa** [comment]
Then maybe someone should assign this bug to the VS 2017 team?

**Comment by blowdart** [comment]
Oh, WebAPI

Yea, that's never been there in Core, in any shape or form. 

It will come in v2.1, when we have a token service in box.
