### ISSUE TITLE
Allow customizing lifetime of 2FA codes for built in providers

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#133]
Changing the time for which the 2FA codes are valid is not possibly right now. Need to look into that

**Comment by suhasj** [comment]
Removing milestone for it to be triaged. Need to review this request from a security perspective.

**Comment by HaoK** [comment]
Probably can just add a Timespan expiries to the options per provider, one knob per TokenProvider class seems reasonable, @blowdart  thoughts?

**Comment by blowdart** [comment]
Timespan works for me

**Comment by HaoK** [comment]
Dupe of https://github.com/aspnet/Identity/issues/465
