### ISSUE TITLE
Very difficult to unit test with SignInManager

### ISSUE THREAD

**Issue by craigahanson** [aspnet/Identity#1333]
I am really struggling to add unit tests over a service I have developed which has a dependency on the SignInManager<TUser>. Is there a reason there is no interface for the sign in manager?

**Comment by MovGP0** [comment]
I have similar concerns about the dependencies on classes rather than interfaces. they should get removed. Ie. the constructor of `SignInManager` has a hard dependency on `UserManager<TUser>`, rather than on `IUserManager<TUser>` (which doesn't exist either). 

My workaround so far was to subclass everything and put proper interfaces on them.

**Comment by HaoK** [comment]
The main reason was we wanted the ability to add new API to the managers without causing breaking changes.  You can still mock the managers, see: https://github.com/aspnet/Identity/blob/dev/test/Microsoft.AspNetCore.Identity.Test/SignInManagerTest.cs#L197

What is it you are trying to do that an interface would let you do that you can't do today in your tests?  Effectively the manager types are the interface, you can register your own manager type with DI which will take over the implementation.

**Comment by HaoK** [comment]
We still unit test them and fake them in the tests whether or not they are interfaces or classes, you can still use something like Moq to fake and inject them, see:

https://github.com/aspnet/Identity/blob/dev/test/Shared/MockHelpers.cs#L19

**Comment by ppi-rloving** [comment]
all of these links are broken ...grrrrr!

**Comment by tiagodenoronha** [comment]
For anyone searching, here is the current link: https://github.com/aspnet/Identity/blob/master/test/Shared/MockHelpers.cs
