### ISSUE TITLE
Identity 2.0 issues - MVC 5

### ISSUE THREAD

**Issue by avechuche** [aspnet/Identity#1334]
Hi. I'm starting to use Identity in ASP .NET MVC 5 and I already have some questions

1) What is the function of the "Identity_UserId" column. In all tables that appear (UserRoles, UserLogins, and UserClaims), it is always "NULL".
It has an FK relationship with the Users table.

![1](https://user-images.githubusercontent.com/11781418/28696307-2c65235c-730b-11e7-8593-530f87c03ba2.JPG)

2) Why **await UserManager.GetLoginsAsync (User.Identity.GetUserId())**; Always returns 0? I have a registered user and I have it linked to two external accounts (Facebook and Google)

        public async Task<ActionResult> ManageLogins(ManageMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ManageMessageId.RemoveLoginSuccess ? "The external login was removed."
                : message == ManageMessageId.Error ? "An error has occurred."
                : "";
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user == null)
            {
                return View("Error");
            }
            var userLogins = await UserManager.GetLoginsAsync(User.Identity.GetUserId());
            var otherLogins = AuthenticationManager.GetExternalAuthenticationTypes().Where(auth => userLogins.All(ul => auth.AuthenticationType != ul.LoginProvider)).ToList();
            ViewBag.ShowRemoveButton = user.PasswordHash != null || userLogins.Count > 1;
            return View(new ManageLoginsViewModel
            {
                CurrentLogins = userLogins,
                OtherLogins = otherLogins
            });
        }

![2](https://user-images.githubusercontent.com/11781418/28696311-3163ccbe-730b-11e7-86bc-f611b6998fbd.JPG)

**Comment by blowdart** [comment]
This repo is for ASP.NET Identity for ASP.NET Core, not for older versions I'm afraid. It looks like your linking is failing.
