### ISSUE TITLE
Preventing Redirect based on rules

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Identity#1337]
I used to do this with the CookieAuthenticationOptions, but it doesn't seem to be working in ASP.NET Core Identity Preview2. Any ideas?

```
 services.Configure<CookieAuthenticationOptions>(opt =>
      {
        opt.Events = new CookieAuthenticationEvents()
        {
          OnRedirectToLogin = async ctx =>
          {
            if (..) // stop redirection if something is true.

          }
        };
      });
```

**Comment by blowdart** [comment]
Linked to https://github.com/aspnet/Security/issues/1347

Cookie Auth is in the security repo, so closing this.

**Comment by HaoK** [comment]
What's not working here exactly?  Are you using identity or only a single cookies?
