### ISSUE TITLE
IIS Restarts Invalidate Identity Cookies?

### ISSUE THREAD

**Issue by PuttItOut** [aspnet/Identity#1338]
I am hosting a core 2 preview 2 app in IIS on windows 2012 R2 using AspNetCoreModule and whenever I restart IIS or Stop/Start, the identity cookies sent are not recognized after the restart.

I can not reproduce this any other way but by hosting in IIS and cycling the server process. Kestrel restarts work as expected when directly hitting the dotnet process.

I figure this is a configuration issue and am using all defaults in IIS for this test site.

Any ideas? Apologies if this isn't the correct location for such a question. 

Source code is located here: https://github.com/voat/voat/tree/Core

**Comment by DamianEdwards** [comment]
Please see the instructions for configuring "Data Protection" when hosting under IIS at https://docs.microsoft.com/en-au/aspnet/core/publishing/iis

**Comment by PuttItOut** [comment]
Perfect! Thank you so much.
