### ISSUE TITLE
Email with two factory email verification

### ISSUE THREAD

**Issue by stuart-lawrence** [aspnet/Identity#1347]
The IdentityConfig RegisterTwoFactorProvider does not accept html email template

this code fails as input string not in correct format:

  var m = new IdentityMessage()
            {
                Subject = "Email verification token",
                Body = "Your token code is {0}"
            };

            string body = helper.GetPartialViewString("~/views/Shared/emailTemplates/_UserVerifyCodeEmailTemplate.cshtml", m).ToString();

            manager.RegisterTwoFactorProvider("Email Code", new EmailTokenProvider<ApplicationUser>
            {
                Subject = m.Subject,
                BodyFormat = body
            });
            manager.EmailService = new EmailService();

**Comment by blowdart** [comment]
This isn't a Identity Core issue, this looks like previous, non-Core versions of identity and MVC. You could log a bug on codeplex but to be honest we're not doing any active work there. Stackoverflow might be a good option.
