### ISSUE TITLE
IdentityUserToken - how works this "table"

### ISSUE THREAD

**Issue by Jenan** [aspnet/Identity#1350]
Hello,

how works this table - IdentityUserToken, what is the purpose of this table?

I can't find the relationship with other objects becuase I've use the external providers but this table is still empty. :)

Thank you for your clarification.

**Comment by blowdart** [comment]
It's where we store "tpkens". We don't user it by default, unless you are using authenticator apps. You could use it to add things like refresh tokens for external logins, but we don't do that by default, you have to use APIs to store them.
