### ISSUE TITLE
When using `CheckPasswordSignInAsync`, how should you protect against timing attacks?

### ISSUE THREAD

**Issue by liamdawson** [aspnet/Identity#1352]
Within a multi-tenanted environment (without public registration), we use `CheckPasswordSignInAsync` as one of the login steps (as we also need to check permissions before logging in, too). When the user does not exist in the system, how can I effectively still run a hash before returning, so that the existence/absence of the user isn't given away via a timing attack?

I haven't measured yet, but will the following line of code run a comparable hash, therefore meaning the responses take the same time for an invalid password vs a missing user?

```
if (user == null)
{
    // fake a password hash operation:
    await _signInManager.CheckPasswordSignInAsync(new ServiceUser(), "wrong password", false);
    return;
}

var result = await _signInManager.CheckPasswordSignInAsync(user, password, true);
if (!result.Succeeded) return;
```

**Comment by benaadams** [comment]
Not strictly serious, but you could do:
```csharp
var failedDelayMs = rnd.Next(100, 300);
var sw = Stopwatch.StartNew();

SignInResult result = null;
if (user != null)
{
    result = await _signInManager.CheckPasswordSignInAsync(user, password, true);
}
sw.Stop();

if (!(result?.Succeeded ?? true))
{
    // Failed, wait random time less time already taken
    await Task.Delay(Math.Max(failedDelayMs - sw.ElapsedMilliseconds, 50));
    return;
}
```

@blowdart might have a more sensible suggestion...

**Comment by blowdart** [comment]
We've never worried about this, because, well, we assuming a user being registered or not is public information (i.e. you can test it via register). So what you could do is in each tenant is create a fake user in your database when onboarding a tenant and then then check against that when the user doesn't exist. We really aren't designing for private registration scenarios.
