### ISSUE TITLE
Set IdentityOptions values when project runs

### ISSUE THREAD

**Issue by kodithuwa** [aspnet/Identity#1354]
Hello,
I have try to dynamically set DefaultLockoutTimeSpan value because it is needed to change from frontend.
what i did, IdentityOptions gets into my service with injecting constructor and change its value. but, seems it is not effected to configured Identity service. how can i change identity options values when project runs?
Thanks 
CK

**Comment by HaoK** [comment]
Resolve `IOptions<IdentityOptions>` and configure DefaultLockoutTimeSpan however you like dynamically
