### ISSUE TITLE
Multiple Identities with different token providers

### ISSUE THREAD

**Issue by Elfocrash** [aspnet/Identity#1360]
_From @Elfocrash on August 15, 2017 10:15_

## Intro

On my application I need to have two different Identities with different options for each Identity.
What I initially did is to simply add the identities with `services.AddIdentity<AdminUser, IdentityRole>`, `services.AddIdentity<User, IdentityRole>`
and do a `.AddDefaultTokenProviders()` at the end of the call, as the project does anyway.

## The problem
The problem is that when i have two identities and i call `.AddDefaultTokenProviders()` only the second call's tokens stay in the dictionary. That is because the system is checking if token providers with those names exist and if they do it replaces them with the latter.
The problem is that the IdentityOptions is a Singeton.
The error i was getting was `"No IUserTokenProvider named 'PasswordResetTokenProvider' is registered."`

My next idea after diving into the code was to remove the `.AddDefaultTokenProviders()` and manually add 3 calls for my providers ex. `.AddTokenProvider("UserDefault",                    typeof(DataProtectorTokenProvider<>).MakeGenericType(typeof(User)))` (and the respective ones for email and phone).

Then i manually set the token provider to be used in the User managers created for each identity like this: `optionsAccessor.Value.Tokens.PasswordResetTokenProvider = "UserDefault";`

However every time i needed to call a user manager the code was stepping in both managers (or there are cases where i need both). Because the `optionsAccessor.Value.Tokens.PasswordResetTokenProvider`, `optionsAccessor.Value.Tokens.ChangeEmailTokenProvider` and `optionsAccessor.Value.Tokens.EmailConfirmationTokenProvider` are system wide value, only the one set last will be used.
This makes the system unable to user the correct token.

## The workaround
The way I worked around it is by adding the `IHttpContextAccessor` in my usermanager and checking Route values to see if the request is coming by a specific area, controller and action.

Obviously this is very hacky and I am not happy with it.
I know that the correct way would be to use claims and roles to give different permissions to separate admin users and normal users, but the app I'm buying had this separation as a requirement on a higher level (Potentially the need to store them in a centralized database away from the other records, different cookie persistence values etc).

## Suggestion
To me it looks like the problem is that we use a Dictionary that limits the keys to one value.
The second `.AddDefaultTokenProviders()` call should probably throw an exception saying that i have something with that name already registered.
Another thing would be that instead of using a Dictionary, we use a data structure that allows key-value combination checks. That way we can have "Default"-"AUserManager" and "Default" - "BUserManager" but the code retrieves the one appropriate for this specific usermanager requesting it.

What are your thoughts on this?
Was Identity never build around the idea of having multiple ones?

_Copied from original issue: aspnet/Mvc#6656_

**Comment by Elfocrash** [comment]
_From @davidfowl on August 15, 2017 10:20_

This should be moved to http://github.com/aspnet/Identity/.

**Comment by Elfocrash** [comment]
@davidfowl I actually just saw that Identity is it's own project. Should i close it and recreate it in Identity or is that something you can do?

**Comment by Elfocrash** [comment]
_From @davidfowl on August 15, 2017 10:27_

https://github-issue-mover.appspot.com/ 😄

**Comment by HaoK** [comment]
Yeah today there's only really support for a single identity options and related managers that consume them (you could have multiple managers with different entities, but they would all have to share the same options today).  We could address this by switching to named options if this is something frequently asked for.

With the token providers, you can always drop down and configure them on the manager directly via: 
`userManager.RegisterTokenProvider("whatever", yourTokenProviderInstance);`

**Comment by Elfocrash** [comment]
I didn't have any luck configuring them on the manager as they have to be set to used by the manager somehow and the options are again system wide.

It would be helpful separating them moving forward especially for saas products.

**Comment by blowdart** [comment]
Do you have multiple managers or something? We don't really support multiple instances of identity within a single app.

**Comment by blowdart** [comment]
Closing due to lack of response.

**Comment by Costo** [comment]
We do use multiple user types and multiple managers in our app so we have this problem too.  
> We don't really support multiple instances of identity within a single app.

What is the guidance then? Create one application per user type?
