### ISSUE TITLE
IdentityBuilder is missing in Identity-rel-2.0.0 compare with Identity-rel-2.0.0-preview2

### ISSUE THREAD

**Issue by brijesh-1111** [aspnet/Identity#1363]
Hi Team,

Compare to `Identity-rel-2.0.0-preview2,` `Identity-rel-2.0.0` is not having the extension methods like `AddCookieAuthentication`?

When I was comparing the file `IdentityServiceCollectionExtensions.cs` under `Microsoft.Extensions.DependencyInjection` (between both the version) I found that  #using `Microsoft.AspNetCore.Builder`  namespace is not there in release version.

Can I ask, what are the alternative suggested? according to the preview2 notes, we should register all the services like `AddFacebookService` and `AddCookieService under ConfigureServices(IServiceCollection services)` method whereas under `Configure(IApplicationBuilder app, IHostingEnvironment env)` method we should have only `app.UseAuthentication()`
But it seems that assumption is no more working under final release.

Can I ask some inputs in this understanding?

**Comment by HaoK** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x

**Comment by HaoK** [comment]
If you have any further questions after reading the doc, please use this issue: https://github.com/aspnet/Identity/issues/1364
