### ISSUE TITLE
Document Branches

### ISSUE THREAD

**Issue by AZDeveloper777** [aspnet/Identity#1367]
Hi !
Please consider a cleanup and document effort for this repository.
I'm an experienced developer (20+ years). I'm still fairly new to Git and GitHub, but I feel like I should have been able to come to the main page for this repository and be able to answer these questions:

1.  If I create a new VS2017 Project of the type "ASP.NET Web Application (.Net Framework)", choose the MVC template, click the "Change Authentication" button and select "Individual User Accounts", VS2017 puts in the basic structure of some version of ASP.Net Identity.   
What branch in this repository does that correspond to ?

2. Same question as above but for the VS 2017 Project type of "ASP.NET Core Web Application (.NET Framework) ?

3. What branch in this repository represents the code that was hosted on the abandoned CodePlex ASP.Net identity site ?

It would be very helpful for those 3 questions to be answered.

From a general project management standpoint, there are 35 branches in this repository !   
How is a developer who is new to this repository supposed to understand which ones he should care about ?

Thanks !

**Comment by blowdart** [comment]
1. This depends on the version of the .net framework. If it's not core, it's probably on codeplex somewhere.
2. Don't look at branches, look at tags, which map to releases, which you can then map into your csproj package versions.
3. None. The codeplex stuff is just on codeplex.

Branches don't matter. We branch for feature work, it's just how git functions. Dev is latest, whatever we're currently working on. Everything else is tags, that's how you get code for individual versions.
