### ISSUE TITLE
`UnauthorizedAccessException`  thrown when checking if a user is SignedIn while using IIS Windows Authentication and 

### ISSUE THREAD

**Issue by mxa0079** [aspnet/Identity#1370]
When using EF Identity along with IIS Windows Authentication, the [SignInManager](https://github.com/aspnet/Identity/blob/eb3ff7fc32dbfff65a1ba6dfdca16487e0f6fc41/src/Microsoft.AspNetCore.Identity/SignInManager.cs) throws a `UnauthorizedAccessException` when checking if the user is signed in (line 120).

The root cause of the issue [is described here](https://github.com/aspnet/IISIntegration/issues/231) (in the comment by ph1ll) -- the call to [`i.AuthenticationType`](https://github.com/aspnet/Identity/blob/eb3ff7fc32dbfff65a1ba6dfdca16487e0f6fc41/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L127) makes a win32 call to LsaGetLogonSessionData, which requires the caller to be the session owner or the local admin; something quite unlikely in a web application inside an enterprise environment.

**Comment by HaoK** [comment]
If you are using windows auth, you can probably just replace the call to SignInManager with something like User.Identity.IsAuthenticated

**Comment by blowdart** [comment]
@brentschmaltz do you still own WindowsIdentity? This seems to be a problem with WindowsIdentity.

**Comment by brentschmaltz** [comment]
@blowdart We don't 'own' it, but we have done some work in WindowsIdentity.  From time to time we help out with issues.  It looks like a fix is needed.

**Comment by blowdart** [comment]
@brentschmaltz Who should be tagged to do the work?

**Comment by brentschmaltz** [comment]
@blowdart you can tag me. Ill investigate.

**Comment by blowdart** [comment]
Consider yourself tagged then :)

**Comment by blowdart** [comment]
Closing as external
