### ISSUE TITLE
How DefaultTokenProviders Work?

### ISSUE THREAD

**Issue by joalcava** [aspnet/Identity#1372]
Hello everyone. I'm new to Identity, I have created a new application and now I'm testing with some users.
I have found that my confirmation emails does not last more than 24 hours.
My question is: Is this the expected behavior or it is because i have a bug in my code?.
And if that is the expected behavior how can i change the token expire time.
Thank you!

**Comment by HaoK** [comment]
Take a look at https://github.com/aspnet/Identity/issues/859, that's basically the same issue
