### ISSUE TITLE
AddEntityFrameworkStores blocks using the generic IdentityRole<TKey> directly

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#1373]
The check should allow using the generic type directly, instead of requiring a derived type.

`AddIdentity<ApplicationUser, IdentityRole<int>>` won't work
while
`AddIdentity<ApplicationUser, ApplicationRole> where ApplicationRole : IdentityRole<int>` works

@ajcvickers @blowdart this is hitting a lot of people, something we can consider fixing in the next patch as it should be a low risk fix.

**Comment by ajcvickers** [comment]
@HaoK Yes, we should try to patch this. if you get fix done as a priority and I'll see if there is still time to get it approved for 2.0.1.

**Comment by ajcvickers** [comment]
@HaoK Please add risk assessment either here on directly in the OneNote.

**Comment by HaoK** [comment]
The fix should be low risk as it will just involve and additional check to allow the base generic type to be  used instead of only derived types.

**Comment by ajcvickers** [comment]
Thanks @HaoK. I updated the OneNote.
