### ISSUE TITLE
Updated 2.0 but now IDesignTimeDbContextFactory vs IDbContextFactory

### ISSUE THREAD

**Issue by jvelezc** [aspnet/Identity#1375]
The compiler states
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0619	'IDbContextFactory<ApplicationDbContext>' is obsolete: 'Use IDesignTimeDbContextFactory instead.'

However, I do not see any way of doing what I used to do using IDbCOntextFactory. In my case I was using IDbContextFactory to apply migrations from 1 project without having to pass connection string and settings. In other words, I was storing the connection strings and other settings in an appsetting.json file located in the class library. (I wanted to completly separate the web project from the database project in which I had already achieved with IDbContextFactory. I now need some guidance as to how to achieve the same now that IDbContextFactory is obsolete.

Here the code that worked before 2.0.
```
{
    public class ApplicationDbContextFactory : IDbContextFactory<ApplicationDbContext>
    {
        public ApplicationDbContext Create(DbContextFactoryOptions options)
        {
            var builder = new DbContextOptionsBuilder<ApplicationDbContext>();
            var variables = new EnviromentInformation();
            var connectionString =
                new ConnectionStringBuilder()
                .CreateConnectiongString(
                                         basePath: variables.GetBasePath(),
                                         environmentName: variables.GetEnviromentName()
                                        );

            builder.UseSqlServer(connectionString);

            return new ApplicationDbContext(builder.Options);
        }

```

**Comment by plaisted** [comment]
Think this is EntityFramework question not identity. See https://github.com/aspnet/Announcements/issues/258 for more information about the changes.

If you look at the error it tells you to use `IDesignTimeDbContextFactory`. From the link above they simply renamed `IDbContextFactory` to `IDesignTimeDbContextFactory` and removed the `DbContextFactoryOptions` parameter (that you weren't using anyway).  I didn't have any issues switching to `IDesignTimeDbContextFactory` in my projects.

**Comment by jvelezc** [comment]
thanks for helping even thought it wasnt the right github project!
