### ISSUE TITLE
User Id null error ambiguous 

### ISSUE THREAD

**Issue by hahn-kev** [aspnet/Identity#1378]
I've been working with aspnet Identity recently, I've run into an issue a couple times where my user didn't have an Id and was therefore null. In the [following method](https://github.com/aspnet/Identity/blob/e2ef51b57c916345a09e1ba1f58f54b58efb723f/src/Microsoft.Extensions.Identity.Core/UserClaimsPrincipalFactory.cs#L82) if the `UserId` is null the `Claim` constructor throws an argument null exception. 

Digging into the source of entity framework it seems that it doesn't check if `UserId` is null before returning it from the `UserStore` (which is what `UserManager` is calling in the method above) so that doesn't seem to be where the fix should go.

I think putting in a couple null checks for UserId and Username would save some headache when trying to put the user Id into a claim. However, it might be worth looking at the `Claim` Constructor to adjust the null error that gets thrown from that to include more detail about the claim type that is being created.

**Comment by blowdart** [comment]
So under what circumstances did your user end up without an ID? This shouldn't happen if you're going through identity, but if you're manipulating the database all on your own, or creating a user directly then you're on your own.  Claim values in general can be null, it's perfectly valid, so we aren't even going to change that.

**Comment by hahn-kev** [comment]
I had a null ID using the Identity provider from LinqToDB, I've reported the issue [Here](https://github.com/linq2db/LinqToDB.Identity/issues/10).

If a Claim value can be null then why does [this constructor](https://referencesource.microsoft.com/#mscorlib/system/security/claims/Claim.cs,205) throw an exception if you pass null in? I'm not sure if the source is on Github for Claims, but after decompiling the source on my machine I'm seeing the same thing. Maybe that constructor needs to change?

**Comment by blowdart** [comment]
This is just an identity assumption, you must have an id for a user. This isn't going to change.
