### ISSUE TITLE
IdentityBuilder methods not compatible with 3rd party service providers

### ISSUE THREAD

**Issue by nphmuller** [aspnet/Identity#1379]
I've been scratching my head on this for a couple of hours during my migration from 1.x to 2.0.

The IdentityBuilder class uses a couple of calls that add services to the service provider of which I don't really understand how they work, but they work with the default service provider and don't with 3rd party service providers (at least Autofac).

For example: https://github.com/aspnet/Identity/blob/8cbda5a23dd594116fcd2f60c486d15fa50051af/src/Microsoft.Extensions.Identity.Core/IdentityBuilder.cs#L109 and https://github.com/aspnet/Identity/blob/8cbda5a23dd594116fcd2f60c486d15fa50051af/src/Microsoft.Extensions.Identity.Core/IdentityBuilder.cs#L200

They add a user/role store and use the user/role as the concrete type? How does the service provider know which store to actually use? TUserStore or TRoleStore seemed way more logical and convenient.

Anyway, when I try to build the service provider after calling `.AddRoles<MyRoleType>()` I get this exception (again, with Autofac):
```
System.ArgumentException: The type 'MyRoleType' is not assignable to service 'Microsoft.AspNetCore.Identity.IRoleStore`1[[MyRoleType, MyApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'.
   at Autofac.Builder.RegistrationBuilder.CreateRegistration(Guid id, RegistrationData data, IInstanceActivator activator, IEnumerable`1 services, IComponentRegistration target)
   at Autofac.Builder.RegistrationBuilder.CreateRegistration[TLimit,TActivatorData,TSingleRegistrationStyle](IRegistrationBuilder`3 builder)
   at Autofac.Builder.RegistrationBuilder.RegisterSingleComponent[TLimit,TActivatorData,TSingleRegistrationStyle](IComponentRegistry cr, IRegistrationBuilder`3 builder)
   at Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at MyApi.Startup.ConfigureServices(IServiceCollection services)
```

**Comment by nphmuller** [comment]
The workaround:

Instead of this:
``` c#
services.AddIdentityCore<User>(options => { ... })
    .AddRoles<Role>()
    .AddRoleStore<RoleStore>()
```
do this:
``` c#
services.AddIdentityCore<User>(options => { ... });
new IdentityBuilder(typeof(User), typeof(Role), services)
    .AddRoleStore<RoleStore>()
    .AddRoleValidator<RoleValidator>()
    .AddRoleManager<RoleManager>();
```

**Comment by HaoK** [comment]
Yeah there's a bug in AddRoles, it shouldn't be calling AddRoleStore at all...

**Comment by nphmuller** [comment]
Ah, that explains it. Never thought it could be a bug since it seemed too big to be in the final release. But I guess these things happen. :)

It's at least a better explanation than the magic that I had in mind.

**Comment by HaoK** [comment]
Yeah the tests typically always call AddRoleStore after anyways, since you can't use identity without a store registered, so it was masked until your issue

**Comment by HaoK** [comment]
Fixed via https://github.com/aspnet/Identity/pull/1406
