### ISSUE TITLE
2FA changes from 1.0 to 2.0

### ISSUE THREAD

**Issue by dcarl1** [aspnet/Identity#1383]
We previously had a simple, email based, 2FA setup with ASP.Net Identity core 1.0 - but on moving to 2.0 we get:

Store does not implement IUserAuthenticatorKeyStore<User>.

I do not see any references to this (or 2fa at all) in the migration guide or breaking change lists.

Am I missing something or is this gone?

**Comment by blowdart** [comment]
Can we see your call stack please? Is this a custom store?

**Comment by dcarl1** [comment]
Yes, I will grab a callstack as soon as I can. 

I am using this for the store:

https://github.com/mrahhal/MR.AspNet.Identity.EntityFramework6

On second thought... the issue could be in that lib.

**Comment by dcarl1** [comment]
Yep, looks like its in that package. Thanks.
