### ISSUE TITLE
How to modify login url when using asp.net identity

### ISSUE THREAD

**Issue by rpundlik** [aspnet/Identity#1384]
Can we modify the default `/account/login` url to some custom url while redirecting the user to login page in case of unauthorized access ?

Let's say client name need to be appended to url which will look like `/ClientABC/account/login` which will redirect to login page and after login will redirect to respective url which is present in return url parameter.

I am trying this in below way. Setting the login Url, here I want to append the client name

```
services.Configure<IdentityOptions>(opt =>
            {
                opt.Cookies.ApplicationCookie.LoginPath = new PathString("/account/login");
            });
```
and then making sure all urls requires authentication

```
  services.AddMvc(o =>
                {
                   o.Filters.Add(new AuthorizeFilter(new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build()));

                })
```

I am trying this from many days, not able to figure out the solution !

Thanks !
Rohit

**Comment by blowdart** [comment]
Have you trying hooking the OnRedirectToLogin event? You can then modify the context.RedirectUri inside there.

**Comment by rooonikz** [comment]
@rpundlik For ASP.NET Core Identity 2.0 I did this: 
`services
                .ConfigureApplicationCookie(options =>
                {
                    options.Events.OnRedirectToLogin = (context) =>
                    {
                        context.Response.StatusCode = StatusCodes.Status401Unauthorized;
                        return Task.CompletedTask;
                    };
                });`

**Comment by blowdart** [comment]
Closing due to lack of response.
