### ISSUE TITLE
ConfirmEmail doesn't work

### ISSUE THREAD

**Issue by blowdart** [aspnet/Identity#1390]
Moved from https://github.com/aspnet/Home/issues/2152 by @kironet

Hey,

I was following this tutorial: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?tabs=aspnetcore2x%2Csql-server

And email is sent, I'm getting url like this: 
_https://localhost:44343/Account/ConfirmEmail?userId=e714dc1d-1b6b-4dfd-8288-78f8b429d506&amp;code=CfDJ8GPqscMYofFCs%2FRH3ucxQlVR4O2ONj8uPQyVUpllt5vd9QrjduDA46u%2FAI9jDaBK28e5U0uzFfx1zxwKQ2O0c41qpXlkVzya%2FU5D1aeLIiMUsiDTxUqil04U%2FRFs%2B%2FZ3UBXmr62zHd%2FxJdsWyo3R4gU1TMwo82OAc0qWrIzG%2BmkxE4SS%2BR0%2BvVVzDyZxLQm4Fc6B9%2Byep6o7ZzVyvhbVKlraFkE6irltJLhKcNFlT6pgmyObNk8uPANP9MXiOdNRvg%3D%3D_

But if I click on it, it does nothing, just redirect to Home/Index and I still can't login, because email is not confirmed.

**Comment by blowdart** [comment]
@Rick-Anderson are the docs correct? The problem here sees to be there's URL encoding on the query string, you can see the &amp in there and that's screwing it all up.

**Comment by Rick-Anderson** [comment]
security/authentication/accconfirm #4075
