### ISSUE TITLE
Multi name claim issue

### ISSUE THREAD

**Issue by farshid3003** [aspnet/Identity#1394]
I have a User with UserName field and name claim.
I use IUserClaimsPrincipalFactory 

 ```
           ApplicationUser user = await _userManager.FindByIdAsync(sub);
            ClaimsPrincipal principal = await _claimsFactory.CreateAsync(user);

```
there is problem bu createAsync method that convert UserName to name claim and in the result I will have more than one name claims

by the way I use entity framework with sql for the Identity
when I use this result for Open Id authentication it throw and error in core 2.0 version.

**Comment by blowdart** [comment]
What error is thrown? Are you saying a username field gets mapped to a name field in OpenID? What OpenID provider are you using? Do you have code you can show us for your user?

**Comment by farshid3003** [comment]
would you pleae look at this
https://github.com/aspnet/Security/issues/1383#issuecomment-325432124

**Comment by blowdart** [comment]
OK then that's not identity, and the security repo issue is where it should be. Closing.

**Comment by farshid3003** [comment]
why you close this. there is a big bug here. you convert Username to name claim and this is wrong.

**Comment by brockallen** [comment]
> why you close this. there is a big bug here. you convert Username to name claim and this is wrong.

This is a valid complaint, but probably different than the one you originally raised. I agree that ASP.NET Identity should not be putting the user's username as the display name claim. But it's done that for a while now (unfortunately).
