### ISSUE TITLE
Port ChangePhoneNumber fix to 2.0.1

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#1395]
Port https://github.com/aspnet/Identity/issues/1388

Change: b7d5a461d4234f0522a01e5de3c14b7a05dc019a

**Comment by kinosang** [comment]
I wanna to know when will this patch released?

or should I use the nightly build before you publish it?

**Comment by Eilon** [comment]
This patch bug is **approved** for the 2.0.x patch. Please send a PR to the `feature/2.0.1` branch and get it reviewed and merged. When we have the `rel/2.0.1` branches ready please port the commit to that branch.

**Comment by Eilon** [comment]
@kinosang we're working on setting up a feed for the upcoming 2.0.x patch that will have this fix.

**Comment by HaoK** [comment]
Pushed https://github.com/aspnet/Identity/commit/b7d5a461d4234f0522a01e5de3c14b7a05dc019a to `feature/2.0.1`

**Comment by Eilon** [comment]
Hi, we have a public test feed that you can use to try out the ASP.NET/EF Core 2.0.3 patch!

To try out the pre-release patch, please refer to the following guide:
* https://github.com/aspnet/Announcements/issues/274 (info)
* https://github.com/aspnet/Home/issues/2254 (discussions and questions)

We are looking for feedback on this patch. We'd like to know if you have any issues with this patch by updating your apps and libraries to the latest packages and seeing if it fixes the issues you've had, or if it introduces any new issues. If you have any issues or questions, please reply on this issue to let us know as soon as possible.

Thanks,
Eilon

**Comment by PinpointTownes** [comment]
Erf, this "patch" introduces a terribad regression: it's no longer possible to create a custom provider for the "phone number tokens" as `GenerateChangePhoneNumberTokenAsync()` now directly calls the internal `Rfc6238AuthenticationService` class instead of the usual providers thingy.

Why was it fixed this way?

**Comment by blowdart** [comment]
@HaoK was this deliberate?
