### ISSUE TITLE
Consider ASP.NET Sync Context functionality in K

### ISSUE THREAD

**Issue by rustd** [aspnet/Identity#14]
Culture and other states in the execution context does not flow in async operations or continuation

**Comment by HaoK** [comment]
Looks like this is already in, from PRs lke this https://github.com/aspnet/XRE/pull/1210/files

**Comment by divega** [comment]
Still more work is needed to fix it on desktop .NET 4.5.1 (see aspnet/XRE#1211) but should be ok to stop tracking it on Identity /cc @DamianEdwards
