### ISSUE TITLE
AddIdentity should set DefaultScheme and DefaultChallengeScheme only

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#1401]
There's a bug because we added DefaultScheme but didn't update identity to set the default, instead it sets the individual schemes which ends up making setting the default less useful than it could be:

We should update AddIdentity to set the DefaultScheme + DefaultChallengeScheme instead

**Comment by HaoK** [comment]
Is this something we can do in 2.1, as its kinda a breaking change...

cc @blowdart @ajcvickers @davidfowl @Tratcher

**Comment by blowdart** [comment]
Is it a good breaking change? :)

**Comment by HaoK** [comment]
Well it makes Identity play nicer with the new defaults we added, of course the tradeoff is that people don't really know the side effects of calling AddIdentity, so changing them in 2.1 might result in different effective defaults for apps which will cause another wave of migration issues.

For example:

Today:
```
   services.AddAuthentication(o => o.DefaultAuthenticateScheme = "Bearer");
   services.AddIdentity() // DefaultAuthenticateScheme = "Identity", so context.User = identity cookie
```

After this change:

```
   services.AddAuthentication(o => o.DefaultAuthenticateScheme = "Bearer");
   services.AddIdentity() // DefaultScheme = "Identity", but explicit "Bearer" wins so context.User = Bearer
```

So it might have been the correct thing to do...but...2.1 migration pain if we change it now

**Comment by blowdart** [comment]
This feels more like fixing a bug than a breaking change to me, but @Eilon should weigh in.

**Comment by HaoK** [comment]
I think we might be stuck with AddIdentity for 2.x, and we should maybe switch to the `AddIdentityCore<TUser>` method which decouples authentication from identity

**Comment by HaoK** [comment]
Basically once we do https://github.com/aspnet/Identity/issues/1409 we switch templates over to using that in 2.1, and just deprecate AddIdentity in 3.0 but leave it alone in 2.x

**Comment by HaoK** [comment]
Closing in favor of https://github.com/aspnet/Identity/issues/1409 we'll add a new way to add identity without any authentication settings, leaving the existing settings alone to avoid any breaking changes
