### ISSUE TITLE
Refactor AddIdentity splitting out Authentication from core identity

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#1409]
ASP.NET Identity is a library, and should not have such an opinion and side-effect on a hosting application. By setting the default signin scheme to external, you're making assumptions about the hosting application. If the hosting app wants to use external cookies, then it should do that configuration itself. 

I understand why it was added in here -- it makes the templates easier. But it's a bad library design choice (especially since the behavior is not relied upon anywhere in the ASP.NET Identity library itself). You might have an app that uses some NuGet library with a transitive dependency on ASP.NET Identity and it'd be incredibly confusing to have this behavioral change in the hosting app as a result of just adding a library.

**Comment by HaoK** [comment]
Yup, the new refactored surface area won't set things up this way, but we had to preserve existing behavior for `AddIdentity<TUser, TRole>`

**Comment by HaoK** [comment]
In 2.1, you should be able to switch to something like:

```
services.AddIdentityCore<TUser>()
   .AddRoles<TRole>()
   .AddEntityFrameworkStores<TContext>()
   .AddCookieAuthentication() // Brings in sign in manger cookies, and you'd be able to control the default schemes here somehow
```

**Comment by davidfowl** [comment]
I agree m, Hao an I spoke about this earlier and threw around some ideas. I don't think identity should set the default scheme at all and should have extensions methods on both IServiceCollection and Authentication builder.

**Comment by HaoK** [comment]
Yup, we'll use this bug to track that work

**Comment by brockallen** [comment]
The name `DefaultSignInScheme` is really the wrong one given what I think the intent of this feature is. I think your intent is that this is meant for the external authentication middleware, right? This property should be renamed to be `DefaultExternalSignInScheme`. Perhaps the optional `scheme` param on all the `HttpContext` APIs should be removed and make it explicit. Given these global defaults and the implicit behavior, it seems brittle.

**Comment by davidfowl** [comment]
>  I think your intent is that this is meant for the external authentication middleware, right?

No, it maps to any call to SignInAsync without parameters.

> Perhaps the optional scheme param on all the HttpContext APIs should be removed and make it explicit. Given these global defaults and the implicit behavior, it seems brittle.

In what version? 3.0?

**Comment by HaoK** [comment]
It's already possible to specify schemes explicitly everywhere the only thing the defaults are mandatory for is the UseAuthentication() middleware to determine what context.User gets set to. 

We started with almost no defaults and very quickly we ended up with defaults for everything again. So I don't think it's realistic to expect people to set schemes everywhere, especially when they only have one. 

I'll have a PR prototype shortly introducing something we've been discussing internally with authentication policies that map to a set of schemes which may help with this (or it will just add yet another set of more complex overloads :)

**Comment by brockallen** [comment]
> > I think your intent is that this is meant for the external authentication middleware, right?
> No, it maps to any call to SignInAsync without parameters.

You are promoting two different semantics and it's unclear which is the intended use case. One scenario is you have someone building a login page that wants to issue a cookie, so they use `SignInAsync` without the `scheme` (thus getting the `DefaultSigninSceme`, or `DefaultScheme`). Then there's the other scenario where you set the `DefaultSigninSceme` to be an external cookie so the external authentication middlewares don't have to be explicitly configured with a `SigninSceme`. Those two models are not consistent. I just want to know which one is the intended scenario for `DefaultSigninSceme`.

If it's the first scenario, then I'd say it makes no sense to have a separate `DefaultSigninSceme`, because really what this really would mean is you want to issue a cookie with the `DefaultAuthennticationScheme`. This means there's no point in having a `DefaultSigninSceme`. 

If it's the latter, then I'd say the name `DefaultSigninSceme` is misleading and and should be called `DefaultRemoteSigninSceme` instead.

**Comment by brockallen** [comment]
> We started with almost no defaults and very quickly we ended up with defaults for everything again.

Right, and we've always recommended that people *do* explicitly set them so there's no magic and/or misunderstanding. That's why I suggested removing the ability to not pass a scheme to the various authentication service API. And as you said, perhaps the only default scheme that makes sense anywhere is the `DefaultAuthenticationScheme` to be used by the authentication middleware.

**Comment by HaoK** [comment]
There is indeed two slightly different scenarios that you described but the default sign in behavior is still consistent. 

The default sign in is used when a scheme is not specified. That applies to both remote authentication when they choose not to specify the sign in scheme in the RemoteAuthOptions and also when you explicitly call sign in and don't specify the scheme. 

In the past pre core and in 1.x this was surfaced via shared options and only used for the remote sign in scheme. So the new default is a super set of what the old did but you can continue to use it as only the external default if you always specify the scheme everywhere else.

**Comment by brockallen** [comment]
> There is indeed two slightly different scenarios that you described but the default sign in behavior is still consistent.

Sure the behavior is consistent but if affects how your write all that other code. And if all that other code has been written based on one of the semantics and the config value is changed it changes semantics. So it's the semantics that are not consistent.

How would code in a library know the intended semantics and do the right thing? I know the answer -- it's to always pass a scheme explicitly to any of those APIs. But all the external middlewares pass null by default and don't require you to have explicitly configure them. You hinted at above is not something that you want people to have to do.

**Comment by brockallen** [comment]
> In what version? 3.0?

@davidfowl  Also, I'm really sorry that it's only now that I have had time to provide this feedback (I wasn't being paid to work on the OSS, whereas you guys were and I had my own bills to pay). I know that this feedback and suggestions would be breaking changes. But that's part of the price for pushing releases so fast without giving time to foster more feedback. Perhaps you guys should hire folks to give feedback, rather than relying on the open source model of expecting free labor from the community. Hasty releases to meet arbitrary dates means you will need to get used to major version changes every 6-12 months to correct mistakes. All in all, this ends up being more costly (mainly to your customers).

**Comment by HaoK** [comment]
> But all the external middlewares pass null by default and don't require you to have explicitly configure them. 
> 

Correct the remote auth schemes job is to just call sign in with the sign in scheme.  It's up to the app/library to configure things in a sensible way. 

Historically our identity based templates rely on AddIdentity wiring things up, with the external cookie being the default sign in scheme (only to prevent having to set sign in scheme on every remote auth explicitly). SignInManager uses explicit schemes with the correct identity cookie everywhere so the default behavior doesn't really affect identity. 

The defaults are mainly there to make things simple when there's only one cookie/jwtbearer. Once you have multiple cookies and more complex auth setups the app should be explicit and specify the schemes. 

We started with something fairly close to what you want with explicit schemes everywhere. But we got several sources of feedback to make it easier to configure, especially for apps where a specifying one or two  defaults is actually enough.

**Comment by brockallen** [comment]
> We started with something fairly close to what you want with explicit schemes everywhere. But we got several sources of feedback to make it easier to configure, especially for apps where a specifying one or two defaults is actually enough.

So it sounds like this motivated the `DefaultSigninScheme`, which sounds more like my 2nd description of the intended use case. Would that be accurate?

**Comment by davidfowl** [comment]
Since we're not making any braking changes, are you suggesting we add another setting?

**Comment by HaoK** [comment]
> So it sounds like this motivated the DefaultSigninScheme, which sounds more like my 2nd description of the intended use case. Would that be accurate?
> 
> —
> 
> 
Not really identity is typically the only one who uses this. The two common ones that were being set are DefaultAuthenticateScheme and DefaultChallengeScheme. We don't have any templates that register external auth by default. 

The sign in and sign out behavior was added to make everything consistent in the authentication service.

**Comment by brockallen** [comment]
Ok, I'll rephrase what I think the problem is. Maybe it'll help the discussion.

There are 3 main scenarios for the SignInAsync method:

* Login code within in the app needs to issue the authentication cookie (high trust)
* External authentication needs to issue the main authentication cookie because the external provider is first-party (high trust, AAD/OIDC)
* External authentication needs to issue an external authentication cookie because the external provider is third-party (low trust, google/facebook and sometimes OIDC)

This, to me, is the confusion over the semantics of calling SigninAsync with a null scheme. It's unclear which of these two semantics are to be used. For the two high-trust scenarios SignIn should be using the default authentication scheme to issue a cookie (not the default signin scheme since you've shown those can be different). For low-trust scenarios SignIn should be issuing the external cookie (which is where a default signin does make sense, but could be better named IMO to indicate it's low-trust or external).

Hopefully this helps. I don't know the solution (other than the suggestions I made earlier), but it only took a day of building a real app for me to run into this. This is why my frustration took over above with the comments about features needing more time. For my short comments, I apologize.

Given that it's complicated, providing settings to facilitate one scenario (at the expense of others) doesn't help, IMO. If you get feedback that something requires too many settings, then push back and explain that sometimes it's complicated and thus a simplification is the wrong thing.

**Comment by leastprivilege** [comment]
You should attend our workshop @davidfowl @HaoK @blowdart

**Comment by davidfowl** [comment]
:trollface:

**Comment by leastprivilege** [comment]
I was actually serious.

**Comment by HaoK** [comment]
> This leads me to think you should always be passing a scheme (and thus deprecate the ability to not pass a scheme).

Not every application supports external authentication, and for many apps that have only a single application cookie/bearer sign in scheme, there's no confusion with the defaults.

In general, libraries/frameworks should always specify the scheme when its available, the only time the defaults should be used is in application code, i.e. [Authorize].  

Some of the confusion here is simply due to the fact that `AddIdentity` hides the fact that its adding 3 cookies, and setting the defaults in a slightly surprising way (AuthenticateScheme = Application, SignInScheme = External) , but that's somewhat intentional as SignInManager was meant to handle the authentication side of things, and hide all of this complexity.  If a developer wants to do auth themselves when Identity is involved, they will need to specify the appropriate scheme, or at least understand what defaults identity sets.

**Comment by brockallen** [comment]
This thread has also made me realize that the same can be said for DefaultSignOutScheme, as that falls back to the DefaultSignInScheme rather than just jumping to the DefaultScheme.

**Comment by HaoK** [comment]
Discussed with @ajcvickers today and the tentative plan for now is to end up with something like this:

```
   services.AddIdentityCore<TUser>(identityOptions => { }} // Exists already

         // Will live in a new Identity.SignIn package, also opt in/out to TFA/External features
         .AddSignIn(newSignInOptions => newSignInOptions.EnableExternal = false)

         // Will live in a new Identity.SignIn.Cookies, adds cookies using the new sign in options to control which cookies are enabled
         .AddSignInCookies() 
```

Also as part of this work, we'll refactor the logic that SignInManager uses today for TFA/External/Lockout into new pieces that can be reused, and then switch SignInManager over to use the new implementation.

@davidfowl feedback/thoughts?  I know you mentioned possibly deprecating SignInManager, what would the replacement be if we did that?  This design should allow you to add whatever back in auth instead of cookies, i.e. Identity.SignIn.Jwt so long as it supports the auth handlers support Authenticate/SignIn things should just work

**Comment by thepinkmile** [comment]
Am I right in thinking these changes will eventually allow me to configure Identity to use my Jwt Token Authentication?
I am using this in an API to enable authentication for the API, however it breaks my Jwt authentication because it is setting the Default Schemes and forcing the addition of cookies which are completely useless for an API.

**Comment by HaoK** [comment]
Yes it will make that easier, but you already can use `AddIdentityCore` and add whatever pieces of identity you need in 2.0, this will just make it a lot smoother

**Comment by blowdart** [comment]
Blocked awaiting Virtual Scheme review

**Comment by HaoK** [comment]
Running out of time in 2.1, will look at this again in 2.2 as we will want to rationalize this across all of the other auth handlers as well.

**Comment by HaoK** [comment]
Trying to fit this into 2.1-preview 2 again

**Comment by HaoK** [comment]
Done via https://github.com/aspnet/Identity/pull/1442
