### ISSUE TITLE
why use "hash != null"???

### ISSUE THREAD

**Issue by zuosc** [aspnet/Identity#1411]
https://github.com/aspnet/Identity/blob/e36e681d5477e8fc4de7cc46717bb73f5fe92a0b/src/Microsoft.Extensions.Identity.Core/UserManager.cs#L710

I think use ```if (!string.IsNullOrWhiteSpace(hash))``` is better.

so,why use ```if (hash != null)```???

@HaoK

**Comment by Palmer11** [comment]
Because we are assuming something or nothing. An Empty string wont/shouldnt be returned. So checking for WhiteSpace would be redundant.

**Comment by blowdart** [comment]
Pretty much :)
