### ISSUE TITLE
How to get current user for web API request ?

### ISSUE THREAD

**Issue by Awd60** [aspnet/Identity#1416]
How to get current user for web API request ?
 this example does not work
var claims = ((ClaimsIdentity)User.Identity).Claims;

**Comment by blowdart** [comment]
How are you authenticating to the webapi?

**Comment by Awd60** [comment]
We are using AAD to register App for WebAPI.  (Active Directory Authentication)

**Comment by blowdart** [comment]
And how are you getting the AAD token? What are you doing with it after? How are you sending it with each request to the api endpoint?

**Comment by Awd60** [comment]
We are using standard Azure authentication.
![authentication](https://user-images.githubusercontent.com/30531953/30369536-28a18852-9875-11e7-9d4a-ecf732bab8c6.PNG)
![authentication1](https://user-images.githubusercontent.com/30531953/30369535-2890f2d0-9875-11e7-895f-88bd496a2c2e.PNG)
Application itself does not handle authentication and rely for Azure .

**Comment by Awd60** [comment]
Issue was closed by my mistake

**Comment by blowdart** [comment]
This issue was moved to aspnet/Security#1427
