### ISSUE TITLE
asp.net core 2.0 + angular 4  + jwt authorization 

### ISSUE THREAD

**Issue by AlexOliinyk1** [aspnet/Identity#1422]
Hi All

I can't find way how configure my application using bearer token authorization, I used this article as example https://wildermuth.com/2017/08/19/Two-AuthorizationSchemes-in-ASP-NET-Core-2

I'm implemented it successful   on the empty application. But after moving logic to my already created asp.net core 2 and anngular  4 using angular cli. 

I'm got error like this '404 not found ' for more details  https://github.com/nbarbettini/SimpleTokenProvider/issues/7 
![image](https://user-images.githubusercontent.com/10448723/30217173-0639af84-94be-11e7-9e0c-27ec6463e54b.png)

But when I removed authorize attribute this route working. 

Problem is I can't configure the server as I think, because I saw as token was passed to the server in the header. 

my startup looks like this 

![image](https://user-images.githubusercontent.com/10448723/30217331-7be106b0-94be-11e7-9e37-98e77d68a89c.png)
![image](https://user-images.githubusercontent.com/10448723/30217347-87e40c46-94be-11e7-813e-00a2ee1afee0.png) 
![image](https://user-images.githubusercontent.com/10448723/30264088-0b47be3e-96e0-11e7-8a39-d2faaff43f91.png)

**Comment by blowdart** [comment]
You can't put authorize on the login endpoint, that's kind of defeating the purpose - it needs to allow anonymous access so you can actually login. You don't really say what the problem is though.

**Comment by AlexOliinyk1** [comment]
This example from article is worked for me, it seems I something was missed from article above, before crearted this issue.

**Comment by marcobarbero** [comment]
I have post a simplified example for user Jwt authentication on Asp Net Core 2.0 and Angular with a custom repository here:
https://expertcodeblog.wordpress.com/2018/01/11/implement-jwt-authentication-on-asp-net-core-2-0-and-angular/.
This is a simplified example of what I used on my project that work correctly.
I hope it can help you.
