### ISSUE TITLE
Move Options Defaults to Summary instead of Remarks

### ISSUE THREAD

**Issue by scottsauber** [aspnet/Identity#1426]
Just wanted to open a issue about the Defaults for things like `PasswordOptions` defaults being in the [Remarks tag of the xml doc comments instead of the Summary tag](https://github.com/scottsauber/Identity/blob/bc75b1a0e73d782fbe221fb6f12855d1a337a5b1/src/Microsoft.Extensions.Identity.Core/PasswordOptions.cs#L14).

I think for discoverability from a Developer point of view, it would be better if the defaults were in the Summary.  That way we see the default directly in the intellisense of VS while we type without having to hit F12 to dive into the remarks.

I was going to submit a PR to add the defaults to `UserOptions` which currently doesn't have any defaults in the Remarks or Summary, but then this just hit me.

Happy to submit a PR to switch this if there's interest.  Thoughts?

**Comment by HaoK** [comment]
Sure a PR would be great!

**Comment by scottsauber** [comment]
Awesome!  I'm headed to bed now, but I will send one tomorrow.
