### ISSUE TITLE
Remove .vscode files

### ISSUE THREAD

**Issue by blowdart** [aspnet/Identity#1428]
Those are yours @javiercn - they're not supposed to be in source control :p

**Comment by nonintanon** [comment]
interesting.. isn't it supposed to be part of gitignore in the first place?

**Comment by blowdart** [comment]
The gitignore files were created long before VS Code was available

**Comment by javiercn** [comment]
I will just add it to the .gitignore when I get to this

**Comment by nonintanon** [comment]
ah.. undertood. thanks.

**Comment by natemcmaster** [comment]
FYI - VSCode files are designed to be okay to commit to source. Even the VSCode repo itself commits their files. https://github.com/Microsoft/vscode/tree/master/.vscode. It's a nice way to share the debugger setup, common tasks, common editor settings, etc. 

But in this repo, it looks like the VSCode settings were added by accident. So yeah, probably good to remove.

**Comment by javiercn** [comment]
7ccc463f6d6240684e1af37cb5e5d2cd51e5f095
