### ISSUE TITLE
How can I replace base64 in GenerateEmailConfirmationTokenAsync?

### ISSUE THREAD

**Issue by NorDroN** [aspnet/Identity#1429]
Hi!
I'm developing a dotnet core template based on JavaScriptServices (angular 4) and OpenIddict - https://github.com/NorDroN/AngularTemplate 

I've tried to add an email confirmation, but it turned up not so simple:
Microsoft.AspNetCore.Identity use base64 when generates token (GenerateEmailConfirmationTokenAsync), but base64 can contain slash (/) and also base64 is case sensitive
I've tried to solve this problems:
1) I've tried to add Encode in my code for token ( / -> %2F), but angular can understand this ( %2F -> / ) and parse it as part of url :(
2) angular also replaces my url with base64 code to url in lowercase (I don't know why, but it's so) and of course when I try to check it I get an error

How can I replace base64 to base32 or may be something else?

**Comment by blowdart** [comment]
@HaoK

**Comment by blowdart** [comment]
Implement your own IUserTwoFactorTokenProvider, add it options.ProviderMap.Add with a name and set options.EmailConfirmationTokenProvider to the name.

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.Extensions.Identity.Core/IUserTwoFactorTokenProvider.cs
