### ISSUE TITLE
No User available until cookie created?

### ISSUE THREAD

**Issue by chassq** [aspnet/Identity#1430]
When we run this call 

`var signInResult = await _signInManager.PasswordSignInAsync(login.LoginName, login.Password, login.RememberMe, true);`

we cannot seem to get to the HttpContext.User until after the Action Method completes and has returned. Is that correct?

**Comment by blowdart** [comment]
That's expected. Nothing can get populated in the user field until the cookie gets read, and that takes a new request. HttpContext is populated at the start of the request, so there's no user at the start.

**Comment by chassq** [comment]
Ok got it. Thanks!
