### ISSUE TITLE
_userManager.ResetPasswordAsync(...) is returning Invalid Token validation message

### ISSUE THREAD

**Issue by saf-itpro** [aspnet/Identity#1433]
App: **ASP.NET MVC Core 1.1.1 with Individual User Accounts
Identity Core
Entity Framework Core
Visual Studio 2017 ver 15.3.3**

When clicking on `Forgot Password` link, the following code successfully sends an email with a generated link. Clicking on the link inside the email body correctly displays the `Reset Password` form.  But after entering login name, new password etc and clicking on Reset button, the validation error` Invalid Token` shows up.

**Body of my Email that App sent**:

    Please reset your password by clicking here: <a href='http://localhost/HPF/Account/ResetPassword?userId=1db73091-8098-4427-9a1a-1897dcabea90&code=CfDJ8IgLyyEqB6dPkvwFmW%2BJlPrg%2Fpz%2FiNTD442K1KoBG7MSx3zp6TFSY5w0Xj49cG87P%2BkGSWalD6YbbRlrLP4qAEORuoaHZM%2BMe0G08Y9EeUycbhNxx%2FpEv2z3sJ%2BMr4ZccLBO08iwlbIxBnXkJ5gu%2Bsnoo5FHAKysp85%2FrLdbS47smj%2Bt9kaaFA5DDBkzmR%2Bb0HTV2FL8CyjH2M1wCjLgcSC2Jg6BIcDAVUd7jEwxB8V9upAVh%2FR3FJCk2OAJU4w4Fg%3D%3D'>link</a>

**Note**: The `PasswordReset `functionality works fine if I am logged in and want to reset my password to something else.

The only difference between following code and the default code that `VS2017 `generates in `AccountController `is that we're not using Email attribute as a user name, we have changed
```
[Required]
[EmailAddress]
public string Email { get; set; }
```
to

```
[Required]
public string UserName { get; set; }
```
etc. etc., and have extended the user properties as follows:

**ApplicationUser.cs**:

```
// Add profile data for application users by adding properties to the ApplicationUser class
public class ApplicationUser : IdentityUser
{
    public string UserFullName { get; set; }
    [Column(TypeName = "varchar(50)")]
    public string UserEmaill { get; set; } 
    [Column(TypeName = "varchar(15)")]
    public string UserCity{ get; set; }
}
```

**Controller**:

    [HttpPost]
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ForgotPassword(ForgotPasswordViewModel model)
    {
        if (ModelState.IsValid)
        {
            var user = await _userManager.FindByNameAsync(model.UserName);
            string sUserEmail = user.UserEmail; //I Added this. Note the email is not the user name in my app
            if (user == null)
            {
                // Don't reveal that the user does not exist or is not confirmed
                return View("ForgotPasswordConfirmation");
            }
    
            // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=532713
            // Send an email with this link
            var code = await _userManager.GeneratePasswordResetTokenAsync(user);
            var callbackUrl = Url.Action("ResetPassword", "Account", new { userId = user.Id, code = code }, protocol: HttpContext.Request.Scheme);
            await _emailSender.SendEmailAsync(sUserEmail, "Reset Password", $"Please reset your password by clicking here: <a href='{callbackUrl}'>link</a>");
            return View("ForgotPasswordConfirmation");
        }
    
        // If we got this far, something failed, redisplay form
        return View(model);
    }
    
    [HttpPost]
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ResetPassword(ResetPasswordViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        var user = await _userManager.FindByNameAsync(model.UserName);
        if (user == null)
        {
            // Don't reveal that the user does not exist
            return RedirectToAction(nameof(AccountController.ResetPasswordConfirmation), "Account");
        }
        var result = await _userManager.ResetPasswordAsync(user, model.Code, model.Password);
        if (result.Succeeded)
        {
            return RedirectToAction(nameof(AccountController.ResetPasswordConfirmation), "Account");
        }
        AddErrors(result);
        return View();
    }

**UPDATE**:
I read [this famous article ](http://tech.trailmax.info/2015/05/asp-net-identity-invalid-token-for-password-reset-or-email-confirmation/) on the above issue. But the article is more than 2 years old and none of the following scenarios apply to my case:

1. _Password Reset Token vs Email Confirmation Token_: I've verified that I'm using Password Reset Token; moreover, the input parameter `purpose` in the signature `public virtual async Task<string> GenerateUserTokenAsync(string purpose, TKey userId)` is not used in `GeneratePasswordResetTokenAsync(...)` of ASP.NET Core 1.1.1.

2.  _Token is changed in transit_: Author is talking about using Url-Encoding  such as: `code = System.Web.HttpUtility.UrlEncode(code);` but ASP.NET Core does not have `System.Web` available.

3.  _Security Stamp is Null_: I've verified that each user in my ASPNETUsers table has SecurityStamp value not null.

4.  _Machine Keys are not matching_: Token was generated on the same desktop machine (windows 10) where it's being validated (just minutes after it was generated).

**UPDATE 2**
After reading a response from `@claudioct`, I installed [NuGet package ](https://www.nuget.org/packages/Microsoft.AspNet.WebUtilities/) for using UrlEncode. I then tried the following but to no avail
1. I tried `code = System.Net.WebUtility.UrlEncode(code);` after the line `var code = await _userManager.GeneratePasswordResetTokenAsync(user);` inside `ForgotPassword(...)` POST method; but still the same error. I then also tried `var code = System.Net.WebUtility.UrlDecode(model.Code);` before the line `var result = await _userManager.ResetPasswordAsync(user, code, model.Password);` inside `ResetPassword(...)` POST method; same error again.

**Comment by claudioct** [comment]
Can use System.Net.WebUtility.UrlEncode("string") and System.Net.WebUtility.UrlDecode("string") to resolve #2;
--

**Comment by saf-itpro** [comment]
@claudioct I tried your suggestion but still the same error. I've added **UPDATE 2** in my post above.

**Comment by claudioct** [comment]
If you're using ModelBinder, try to not use _System.Net.WebUtility.UrlDecode("string")_ . 
I guess Net Core do the dirty work for us.

**Comment by saf-itpro** [comment]
@claudioct  Yes, I've read that at different places online to not to use Decode since, according to some, it may even bring back the issue you are trying to resolve. That's why, I mentioned in my UPDATE 2, that first I tried using Encoding part only. But after getting the same error, I tried Decoding part, as well, but still the same error.

**Comment by claudioct** [comment]
Did you debugged to make sure you're trying to change password with correct token?

**Comment by saf-itpro** [comment]
@claudioct In my Note in the post above I mentioned that the PasswordReset functionality works fine if I am logged in and want to reset my password to something else. Now the same functionality does not work when a generated link is clicked on the email body. I don't know how I would debug outside the visual Studio (please note that we are now not inside the Visual Studio anymore; it's PasswordReset form when I click on the link in the email). Browser F12 mode does not give any info not even any error.

**Comment by blowdart** [comment]
@HaoK

**Comment by blowdart** [comment]
This is really up to your code. We give you a code which must match. How you render the tag in your email is up to you. UrlEncode is wrong for example, because you're passing it as a query string, and UrlEncode is for path parts.
