### ISSUE TITLE
Dev branch not resolving EntityFrameworkCore packages?

### ISSUE THREAD

**Issue by jhermsen** [aspnet/Identity#1434]
I'm trying to do a clean build of the dev branch, but it won't get all packages.
I was hoping to test the Identity.Service packages.

All I did was:
-Clone: git clone https://github.com/aspnet/Identity.git
-Build: build.cmd

Resulting in these kind of errors with EntityFrameworkCore packages:
`C:\Source\Repos\Identity\src\Microsoft.AspNetCore.Identity.EntityFrameworkCore\Microsoft.AspNetCore.Identity.EntityFrameworkCore.csproj : error NU1603: Microsoft.AspNetCore.Identity.EntityFrameworkCore depends on Microsoft.EntityFrameworkCore.Relational (>= 2.1.0-preview1) but Microsoft.EntityFrameworkCore.Relational 2.1.0-preview1 was not found. An approximate best match of Microsoft.EntityFrameworkCore.Relational 2.1.0-preview1-26623 was resolved. [C:\Source\Repos\Identity\Identity.sln]`

What am I missing?

**Comment by natemcmaster** [comment]
EF is producing bad packages. Should be fixed with https://github.com/aspnet/EntityFrameworkCore/pull/9845

**Comment by jhermsen** [comment]
Oké thanks
