### ISSUE TITLE
Why are all the Get...Store functions private or don't check Supports...Store

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Identity#1439]
Flabbergasted by this, as to disable a piece of functionality on a manager now requires much more overrides compared to overriding just the one method and throwing unconditionally.

I see more of these flaws in places where we'd like to take away or slightly remold functionality. Take for instance the idea of the feature interfaces for stores. The stores are great as we don't want to fully create the stores functionality ourselves and we like the idea of using interfaces to detect which features are supported. Problem with it though is the combination of those two are very hard on library users as we can't take away an interface once implemented. Which as they're all already implemented on all the supplied stores (base and inherits) is a problem... Now we have to choose, do we want reusability or a nice fit for our project's supported set.

Example below to disable user claims as we ignore that entity in the dbcontext modelbuilder (we have our own solution for it):
![screen shot 2017-09-20 at 22 15 05](https://user-images.githubusercontent.com/4218809/30665458-5a751448-9e51-11e7-88bc-1d7f3121b31f.png)

**Comment by HaoK** [comment]
The scenario you describe where you want to selectively disabled functionality while reusing our base store implementations is not something we have focused on.  

The store interfaces are meant to be pretty simple to implement.

But have you tried overriding `UserManager.SupportsUserClaim` and making it false?  GetClaims(user) might still call through to the store, if your store actually implements this interface, but your app wouldn't be calling this API ever right?

**Comment by NinoFloris** [comment]
Nobody does those checks before executing a method, and as witnessed in the manager code you don't expect them to either as you recheck support in those Get...Store methods.

I don't know what you mean with "GetClaims(user) might still call through to the store" as all the functions using that have been overridden to throw.

Easiest fix is to make Get...Store respect any overridden result of the Supports... methods instead of trying with the (by default) same code in a private method where nobody can reach it.

**Comment by HaoK** [comment]
The original idea is that callers do not call methods on the manager that their store doesn't support.  Those private get methods are just a pattern used to consistently throw NotSupportException if the store doesn't implement the interface.

What are you actually trying to do? 

If you disable UserClaims because you don't use them, nothing should be calling the Claims methods (other than the default claims principal factory which does check SupportsUserClaim)

**Comment by NinoFloris** [comment]
Yes that's why I'd like to see a more constructive solution where there is a store we can actually use as a base that doesn't already implement everything

**Comment by blowdart** [comment]
If we end up writing a base that implements something, what would you choose to implement? Everyone would want something different. You're not meant to hit the not implemented exception, or use our classes to derive from and then attempt to pick and choose, instead you start from your own simplest implementation then layers features on as you need them.
