### ISSUE TITLE
Why isn't the normalized name used when adding roles to the claimsidentity?

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Identity#1440]
https://github.com/aspnet/Identity/blob/eb3ff7fc32dbfff65a1ba6dfdca16487e0f6fc41/src/Microsoft.Extensions.Identity.Core/UserClaimsPrincipalFactory.cs#L143

As `ClaimsPrincipal.IsInRole()` calls down to `ClaimsIdentity.HasClaim()` which uses an Ordinal comparison on the value it seems logical to save the normalized name for the role. Or if it's important to be able to display the original name to return a version of ClaimsIdentity that has an overridden `HasClaim` method with an OrdinalIgnoreCase comparison, perhaps just for the default role type.

Otherwise why normalize the role name at all?

**Comment by blowdart** [comment]
Normalization is there for index comparisons/lookups/uniqueness. When it goes into a claim we use the real value, because fidelity is important. What ClaimsIdentity does isn't something under our control.
