### ISSUE TITLE
Issue with IdentityUserToken Id data type

### ISSUE THREAD

**Issue by natelaff** [aspnet/Identity#1443]
Branching this into a new issue from https://github.com/aspnet/Identity/issues/1364 because I believe it's a bug and can reproduce it.

I override my datatypes in Identity with Guid. Nothing fancy. But getting this as of upgrade to 2.0.

ArgumentException: The key value at position 0 of the call to 'DbSet<IdentityUserToken>.Find' was of type 'Guid', which does not match the property type of 'string'.

Basically, start a new project with individual auth.

```C#
    public class User : IdentityUser<Guid>
    {
        public string MyProperty { get; set; }
    }

    public class Role : IdentityRole<Guid>
    {
        public string MyProperty { get; set; }
    }


    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        builder.Entity<User>().ToTable("User").HasKey(u => u.Id);
        builder.Entity<Role>().ToTable("Role").HasKey(u => u.Id);
        builder.Entity<IdentityUserClaim<Guid>>().ToTable("UserClaim").HasKey(uc => uc.Id);
        builder.Entity<IdentityUserLogin<Guid>>().ToTable("UserLogin").HasKey(ul => new { ul.LoginProvider, ul.ProviderKey });
        builder.Entity<IdentityUserRole<Guid>>().ToTable("UserRole").HasKey(ur => new { ur.UserId, ur.RoleId }); ;
        builder.Entity<IdentityRoleClaim<Guid>>().ToTable("RoleClaim").HasKey(rc => rc.Id);
        builder.Entity<IdentityUserToken<Guid>>().ToTable("UserToken").HasKey(ut => new { ut.LoginProvider, ut.UserId, ut.Name });
    }
```
Nothing crazy happening here. Just making the key a Guid and renaming the tables.
Replace appropriate methods to use that User/Role/Key type.
Run, create a user, then go to Two Factor Auth page and you'll hit it on the call to _userManager.GetAuthenticatorKeyAsync(user)

**Comment by natelaff** [comment]
[WebApplication6.zip](https://github.com/aspnet/Identity/files/1345480/WebApplication6.zip)

Here's a repro project.

1) Create database
2) Register as a new user
3) Go to Manage page
4) Click Two Factor Auth

**Comment by HaoK** [comment]
@natelaff can you convert your zip to a repo on github instead?  And then I'll take a look thanks

**Comment by natelaff** [comment]
https://github.com/natelaff/aspnetcore20-identity-bug

**Comment by HaoK** [comment]
So I was able to get a simplified version what you were trying to accomplish to work I think:

1. Create a new MVC app with individual auth.
2. Customize the user + role with an additional property:
```
    public class ApplicationUser : IdentityUser<Guid>
    {
        public string MyProperty { get; set; }
    }

    public class Role : IdentityRole<Guid>
    {
        public string MyProperty { get; set; }
    }

```
3. Update Startup: `AddIdentity<ApplicationUser, Role>`
4. Update `ApplicationDbContext : IdentityDbContext<ApplicationUser, Role, Guid>`
5. Delete all initial migrations/classes that the template generated in Data, Migrations
6. run `Add-Migration initial` to create a new migration and apply it
7. Run the app, Register a user, clicking on TFA works

@ajcvickers does this sound like a reasonable set of steps to customize the model to switch the primary key?  At a minimum we should include this with the docs for 2.0 cc @scottaddie

**Comment by HaoK** [comment]
Note: the two big changes from your repro that I avoided was the OnModelCreating configuration, and leaving the ApplicationUser class name alone.

**Comment by natelaff** [comment]
I already have an existing database where I have those table names set so I'm kind of locked in there :)

**Comment by blowdart** [comment]
Assigning to @ajcvickers because EF :)

**Comment by natelaff** [comment]
Came back to now that 2.1 is out and still ran into this. What can I do here to proceed? I have an existing db that's live that has this structure. What do I need to do to get my app upgraded? Thanks!

**Comment by natelaff** [comment]
Ok, I basically did what was suggested and blew away the identity stuff from my snapshot and regenerated. also killed my model customizations on identity other than the essential stuff like the user table and just migrated data over. everything worked good here. must have been a result of just early snapshots from 1.0 beta stuff. you can close, or keep open if you want to attempt to fix for later. but I've moved past it :)
