### ISSUE TITLE
Email confirmation token becomes invalid after redeployment

### ISSUE THREAD

**Issue by mkArtak** [aspnet/Identity#1444]
Hi.

I have an asp.net core 2 web application which is hosted in Azure AppService.
When a new user signs up the application sends an email confirmation request to the user (as an email), with a link in it for the user to click.
The link uses a token generated using the following method:
`UserManager<TUser>.GenerateEmailConfirmationTokenAsync(TUser user)`

When user clicks the link, the AccountController handles that request and tries to find the user given the email address and the token:
`IdentityResult result = await this.userManager.ConfirmEmailAsync(user, code);`

However, if after generating the code a new deployment had happened, the ConfirmEmailAsync method would not be able to find the user with that code, so the confirmation request results in an error.

Here is the list of relevant packages my project references:
```
<PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.3.0.21" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Twitter" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.0" />
```

**Comment by VahidN** [comment]
This may help: ["... by default the keys will be held in memory ..."](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x#data-protection)

**Comment by mkArtak** [comment]
Thanks @VahidN .

I will try to persist those and see whether that will fix it or not. Hopefully, it will !

**Comment by blowdart** [comment]
It should :) @mkArtak did this work for you?

**Comment by mkArtak** [comment]
@VahidN , persisting the key indeed helped. For now I'm storing it in Azure Storage Blob. In the future will be switching to Azure KeyVault.

Thanks for your help !
