### ISSUE TITLE
PasswordValidator.IsLower and .IsUpper only reconizing the english alphabet

### ISSUE THREAD

**Issue by svethors** [aspnet/Identity#1445]
When validating passwords and requiring either upper or lower case characters, non-english characters are not properly recognized as being upper or lower case. For example the Norwegian character 'Æ' is the upper case of 'æ', but will not be regarded as either, and so setting PasswordOptions.RequireLowercase = true will result in an error even if the lower case 'æ' is present in a password.

The code leading to the problem is found in Microsoft.AspNetCore.Identity.PasswordValidator:
Line 96:
```
public virtual bool IsLower(char c)
{
    return c >= 'a' && c <= 'z';
}
```
And line 106:
```
public virtual bool IsUpper(char c)
{
    return c >= 'A' && c <= 'Z';
}
```

**Comment by blowdart** [comment]
This is a limitation of the .NET framework. Instead you'd have to implement your own IPasswordValidator and inject it into DI to override the default one.
