### ISSUE TITLE
Document how to customize the EF model

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/Identity#1447]
People often seem to run into issues when attempting to customize the entities in the Entity Framework model. It would be good to have documentation showing the general approach (i.e. talk about OnModelCreating, that the model needs to remain in a consistent state, etc) as well as common scenarios (adding a property, adding an FK, changing to use a composite key, etc.)

**Comment by HaoK** [comment]
cc @Rick-Anderson @scottaddie

**Comment by HaoK** [comment]
Maybe we can expand the existing Customizing Foreign Keys doc into this?

**Comment by scottaddie** [comment]
@HaoK Are you referring to the following doc? https://docs.microsoft.com/aspnet/core/security/authentication/identity-primary-key-configuration

**Comment by Rick-Anderson** [comment]
@ajcvickers  can you provide a first draft for this and we'll take it from there? Should it go under https://docs.microsoft.com/en-us/ef/core/modeling/ ?

**Comment by HaoK** [comment]
Yeah @scottaddie basically that is one specific common customization, this new topic should include that, but also cover the other common scenarios that currently aren't documented

**Comment by andreyshade** [comment]
In my case I need guide how to run asp.net core + mvc + identity + sqlite

**Comment by ajcvickers** [comment]
@Rick-Anderson Yes, I will write a draft of this.

@andreyshade If you're looking for general docs on how to use ASP.NET Core (including the things you mention) then the best place to start is here: https://docs.microsoft.com/en-us/aspnet/index

**Comment by natemcmaster** [comment]
This is still in the 2.1.0 milestone. Is this complete?

**Comment by ajcvickers** [comment]
@natemcmaster Yes, pretty much. I have one outstanding update to make, but I'm tracking that somewhere else.
