### ISSUE TITLE
The proper way to extend UserManager

### ISSUE THREAD

**Issue by yodasad** [aspnet/Identity#1448]
Assume I want to write a library that extends identity model with a new object called Organization.  It can look like this
````
public class Organization
{
    public string Id { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }

    // Some other properties
}
````
A user can be a member of many organization.
The next step is to extend `UserManager` with some methods
````
AddUserToOrganizationAsync
RemoveUserFromOrganizationAsync
GetUserOrganizationsAsync
````

My question is: what is the proper way to implement these methods?
1. Should I invent a new class `UserOgranizationInfo` (analogue of `UserLoginInfo`)?

So the methods will look like
````
public class UserOgranizationInfo
{
    public string Id { get; set; }
    public string Name { get; set; }
}

public class MyUserManager<TUser> : UserManager<TUser> where TUser : class
{
    public Task AddUserToOrganizationAsync(TUser user, UserOrganizationInfo org);
    public Task RemoveUserFromOrganizationAsync(TUser user, UserOrganizationInfo org);
    public Task<IEnumerable<UserOrganazationInfo>>GetUserOrganizationsAsync(TUser user);
}
````

2. Or is it normal to use my entity type here?

So my UserManager will look like
````
public MyUserManager<TUser, TOrganization> : UserManager<TUser>
    where TUser : class, TOrganization : class
{
     // Other code

    public Task AddUserToOrganizationAsync(TUser user, TOrganization org);
    public Task RemoveUserFromOrganizationAsync(TUser user, TOrganization org);
    public Task<IEnumerable<TOrganazation>>GetUserOrganizationsAsync(TUser user);

    // Other code
}
````

Or even more simpler
````
public MyUserManager: UserManager<IdentityUser>
{
     // Other code

    public Task AddUserToOrganizationAsync(IdentityUseruser, Organization org);
    public Task RemoveUserFromOrganizationAsync(IdentityUseruser, Organization org);
    public Task<IEnumerable<Organazation>>GetUserOrganizationsAsync(IdentityUser user);

    // Other code
}
````

I think that the only purpose for the first case (with `UserOrganizationInfo`) is to support store that doesn't support Organizations at all. In this case it will be quite inconvenient to add dependency on Organization.
But if I know that my stores and my UserManager will always support Organizations the second way is ok, is it? Because the second way is much more convenient: we can get full organization info directly from the UserManager rather than from additional `OrganizationManager` class.

Am I right?

**Comment by HaoK** [comment]
So the main guiding factor is whether you are building something more like a library for reuse in different situations, or if this is specific to your app.  If you don't envision reusing this for other organization types in the future, you don't need the extra generic complexity...

There's no clear right or wrong choice between your options, the tradeoffs are between extra work/complexity for some extensibility...

**Comment by yodasad** [comment]
Thank you! I got it.
