### ISSUE TITLE
KeyVault extension should provide an overload that takes KeyVaultClient and doesn't require IIdentityBuilder

### ISSUE THREAD

**Issue by pakrym** [aspnet/Identity#1456]
Required for:
https://github.com/aspnet/specs/issues/90

1. We don't have `TUser, TRole` in light-up so there is no way to call `AddIdentity`.
2. When using MSI (https://docs.microsoft.com/en-us/azure/active-directory/msi-overview) we get auth callback for  `KeyVaultClient` instead of ClientSecret/ClientID

/cc @javiercn

**Comment by javiercn** [comment]
We removed the code
