### ISSUE TITLE
Default DataProtectionProvider

### ISSUE THREAD

**Issue by ActionJ4ckson** [aspnet/Identity#1457]
I am working on an application built on MVC 5, .Net 4.5, Identity 2.2.1 using Visual Studio 2017. 

Assume that I have started with a fresh application and not altered the default Startup.Auth neither have changed any configuration for ApplicationUserManager.DataproctectionProvider. When I debug the application, in ApplicationUserManager.Create the default value of `options.DataProtectionProvider` is Microsoft.Owin.Host.SystemWeb.DataProtection.MachineKeyDataProtectionProvider. 

But the articles I have been following since beginning says that by default it will pick DpapiDataProtectionProvider. What I am missing here?

Since my app will be going on Azure I am really concerned if should I explicitly implement my own MachineKeyDataProtectionProvider? 

P.S - I hate to raise it as an issue, please direct me to the right forum for asking queries

**Comment by blowdart** [comment]
This is not an identity issue or a .NET Core issue.  The articles you're reading are for Data Protection in ASP.NET Core, which does try autodetection. As you're not using ASP.NET Core you don't get this feature and what you see in debug is correct, it uses a machine key from web.config. Azure Web Apps set this to a consistent value so you don't have to, so it'll just work.
