### ISSUE TITLE
Create simple constructor for UserManager for console applications

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#146]
The current UserManager takes in dependencies of type: IUserStore&lt;TUser&gt; , IOptionsAccessor&lt;IdentityOptions&gt; , IPasswordHasher , IUserValidator&lt;TUser&gt; , IPasswordValidator&lt;TUser&gt; , IClaimsIdentityFactory&lt;TUser&gt; 

It is easy to get an instance in web application through DI but in cases where users wants to instantiate the UserManager locally, they have to provide all these dependencies. It would be good to have one with default constructor or a static method that returns a UserManager with defaults set

var usermanager = UserManager.Create(IUserStore);

**Comment by ahmad-moussawi** [comment]
This can be helpful on some situations where I need to seed the database on startup and add users through the `UserManager`.

I've tried this:
```
UserManager<ApplicationUser> userManager = (UserManager<ApplicationUser>)httpContextAccessor
                    .HttpContext.ApplicationServices.GetService(typeof(UserManager<ApplicationUser>));
```

but at this stage (database seeding on startup) there is no HttpContext

**Comment by dejx** [comment]
One way of achieving this could be if you create your own instance of `IServiceCollection `.

Below is the example code

```cs
  public class AspNetIdentityCredentialProvider
    {
        private readonly IServiceCollection _serviceCollection;

        public AspNetIdentityCredentialProvider()
        {
            _serviceCollection = new ServiceCollection();
            _serviceCollection.AddIdentity<IdentityUser, IdentityRole>()
                .AddEntityFrameworkStores<IdentityDbContext<IdentityUser>>()
                .AddDefaultTokenProviders();
            _serviceCollection.AddDbContext<IdentityDbContext<IdentityUser>>(options =>
            {
                options.UseSqlServer(connString);
            });
        }
```

Then you're able to do whatever you desire
```cs
            var um = _serviceCollection.BuildServiceProvider().GetService<UserManager<IdentityUser>>();
            try
            {
               var u= await um.FindByNameAsync("..");
```
