### ISSUE TITLE
What is Microsoft.AspNetCore.Identity.Service.* packages?

### ISSUE THREAD

**Issue by hikalkan** [aspnet/Identity#1460]
Is it a replacement for IdentityServer4? Is there any documentation for that? How and why we use that?

Thanks.

**Comment by Eilon** [comment]
@danroth27 do we have a pointer to the current state of this?

**Comment by brockallen** [comment]
> Is it a replacement for IdentityServer4

I can only speak for the IdentityServer side of things, but IdentityServer is not going anywhere. We will continue to provide a flexible, customizable, and spec-compliant OIDC and OAuth2 token server.

**Comment by RainingNight** [comment]
+1

**Comment by danroth27** [comment]
@hikalkan It was an effort to build an identity service component that can operate as an OpenID Connect provider, but it has never shipped and we are looking at switching to use IdentityServer instead.

**Comment by hikalkan** [comment]
Thanks @danroth27 for the clarification. I also think this is a right decision.
