### ISSUE TITLE
TwoFactor/MultiFactor Authentication without asp.net core Identity

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Identity#1461]
The current TwoFactor authentication is strongly link to the asp.net core identity, please consider allowing TwoFactor/MultiFactor authentication wihout using asp.net core Identity.

example: sites configured to use external oauth/authentication providers such as Facebook, Twitter, Google and Microsoft accounts where a authenticator application is needed to allow the uses to gain access or elevat permission for some action.

**Comment by HaoK** [comment]
How would you imagine this to work without identity as the abstraction used to store user information in the app?

**Comment by grahamehorner** [comment]
The repository that store the TwoFactor/MultiFactor security keys would dependency injected and provide methods to store/retrieve security keys a string (the oauth provide name & user identit)  (no need to store anything else) when a user signs in for the first time (using the provide they have chosen) the application would generate and store the key under the oauth provider user identity  email/display a QR code, with information with regards where to download the authenticator app; subsequent sign in would then require a TOTP TwoFactor code.

**Comment by HaoK** [comment]
This sounds like implementing a very bare bones identity store that only supports TFA and external logins.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
