### ISSUE TITLE
How to change Type from String to Int and Auto-generated UserName and NormalizedUserName Properties?

### ISSUE THREAD

**Issue by naveddeshmukh** [aspnet/Identity#1464]
I intended to use UserName property as Employee Codes (integers and auto-incrementing). 

As per policy, My application requires the employee to be able to log in using their employee code (which are integer values of 5 digits, if that's relevant ). 

I was using UserName property to store the employee codes, but now the requirement is to automatically generate an Employee Code (similar behavior of auto increment in SQL Server.) 

Is their anyway to override UserName and used it as integer and auto-generate it whenever a new record is inserted in the table.

**Comment by blowdart** [comment]
We don't design for this flow, because what you'd need is the ability to create a user with no username in order to get the auto increment working. So no, we don't believe this is possible, we'd approach it as a separate table, and link through.
