### ISSUE TITLE
Best practice to integrate Identity into a multiple-layers project?

### ISSUE THREAD

**Issue by heku** [aspnet/Identity#1465]
Hi,

I have google/bing this but no good solution/suggestion found, as all examples just demonstrate the usage in one project, I'm wondering what's the best practice for integrate Identity with a real solution like below.

- UI Layer (MVC)
- Domain/Models Layer (i.e. `AppUser`, and we may want to keep this layer POCOs)
- Infrastructures Layers (i.e. `AppDbContext`)

In this case, we cannot define an `AppDbContext : IdentityDbContext<AppUser>` because` AppUser` is expected an `IdentityUser`, to make this work, we have to add reference to Identity stuffs to Domain layer.

I understand that if I re-implement all Identity Stores inside the Infrastructures layer, this would work, but this sounds not so good.

Is there a best practice that we can reuse majority of Identity and keep each layer clean?

It's very appreciated to hear your suggestion?

**Comment by heku** [comment]
Current, I use a separated `DbContext` for identity stuffs, and keep all identity models into an infra project, so that these don't break my domain models.

Still hope to hear your suggestions/practices on this.

**Comment by blowdart** [comment]
This is probably best asked on StackOverflow, this is not something we have support for natively, and we don't have best practice for this.
