### ISSUE TITLE
Suggestion: Support migrating to new Password Hashers over time

### ISSUE THREAD

**Issue by paulhickman-a365** [aspnet/Identity#1466]
Over time, password hashes that were once considered secure are no longer considered so. Therefore, it would be desirable to be able to support multiple hashes in a single identity database, and transparently re-encrypt users' passwords as they login if a more secure hash function is available.

A newer hash function may mean a new algorithm (e.g. Argon2), or simply more iterations / different configuration parameters for the algorithm already in use.

A possible implementation would be:

1.  ASPNet the identity `UserManager` has a `PasswordHashers` property added, which is a list of `IPasswordHasher` objects in order of ascending secure-ness called `PasswordHashers`. The existing `PasswordHasher` property is changed to retrieve the last item in the list, and is made read-only, so that newly stored passwords use the latest hash function.

2. The  list index of the `PasswordHasher` that was used for a particular user is stored in a property of the `TUser` object called `PasswordHashVersion` 

3. During the authentication process, if the password check is successful, but the `PasswordHashVersion` value indicates it was not hashed using the current hasher, re-hash the password using the current `UserManager.PasswordHasher` and update the hash and version stored in the `TUser` object.

This would mean, over time, users still using the application would have their password encryption level upgraded and it would not be stuck at the quality of hashing algorithm available in the year they signed up. Users who no longer user the application would be stuck with the older password hashes. However, administrators could query the database to report on the number of users with legacy hashes, and contact them to request they sign-in to retain their account.

**Comment by blowdart** [comment]
We have this in Core, if we rev the password hashers, we have a requires upgrade and in Identity Core it automatically will update the hash.

You can replace the hashers entirely yourself, and implement this, but we're not about to make this generic, because now you're going to have databases created in one project not readable by another.
