### ISSUE TITLE
Add alternative ASP.NET Identity RavenDB Provider to the README file

### ISSUE THREAD

**Issue by maqduni** [aspnet/Identity#1467]
What's the process for adding an alternative provider? There already is a RavenDB Provider listed in the repository description, I'd like to list my package [https://github.com/maqduni/AspNetCore.Identity.RavenDb](https://github.com/maqduni/AspNetCore.Identity.RavenDb) there as well, it's also the most downloaded and complete RavenDB provider.

Should I list it in parenthesis by the existing link? like,

- ASP.NET Identity RavenDB Provider ([alternative provider by Maqduni](https://github.com/maqduni/AspNetCore.Identity.RavenDb))

**Comment by blowdart** [comment]
Sure, send a PR

**Comment by HaoK** [comment]
Merged thanks

**Comment by maqduni** [comment]
Thank you!
