### ISSUE TITLE
IUserStore<TUser, TKey> seems to be missing

### ISSUE THREAD

**Issue by clausjensen** [aspnet/Identity#1482]
Reading the documentation regarding changing the primary key of the users using `ApplicationUser : IdentityUser<int>` at https://docs.microsoft.com/en-us/aspnet/identity/overview/extensibility/overview-of-custom-storage-providers-for-aspnet-identity when using a custom UserStore.

This seems applicable to Identity Core, until you get to the part with having the custom `UserStore` implement `IUserStore<TUser, TKey>`. It seems this interface with `TKey` does not exist: https://github.com/aspnet/Identity/blob/dev/src/Microsoft.Extensions.Identity.Core/IUserStore.cs#L14

Not being able to specify this `TKey` causes my UserStore to require me to implement `FindByIdAsync` with a `string` parameter that I would then have to parse to an `int` before doing the lookup - which is a bit annoying.

Has the way to achieve this been changed? - I was not able to find out a way to get all the way using the classes and interfaces available .. but I might have missed something.

**Comment by blowdart** [comment]
Identity in Core always uses a string as a key, removing TKey was a specific design decision. 

So yes, you must convert to an int before doing a lookup.
