### ISSUE TITLE
Revert the fix introduced in https://github.com/aspnet/Identity/issues/1395

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Identity#1483]
When @HaoK fixed https://github.com/aspnet/Identity/issues/1388, he decided to update the `GenerateChangePhoneNumberTokenAsync()`/`ValidateChangePhoneNumberTokenAsync()` methods to directly use the internal Rfc6238AuthenticationService class instead of using the provider configured in the options.

Unfortunately this fix is bad and will break apps using a custom token provider (e.g not based on TOTP) for the "change phone number tokens".

Consider reverting this change and fixing the bug at the root by changing this line to point to the phone provider (by default): https://github.com/aspnet/Identity/blob/f147951d92ff5b4413d7ffdd55dcc91dfcfdfdca/src/Microsoft.Extensions.Identity.Core/TokenOptions.cs#L63-L69

**Comment by HaoK** [comment]
Hrm this code was just reverted to what it looked like in 1.1.2

https://github.com/aspnet/Identity/blob/rel/1.1.2/src/Microsoft.AspNetCore.Identity/UserManager.cs#L1550

I guess I must have introduced ChangePhoneNumberTokenProvider in 2.0 to make things consistent at some point, as it doesn't appear to exist in 1.1.2's TokenOptions.  https://github.com/aspnet/Identity/blob/rel/1.1.2/src/Microsoft.AspNetCore.Identity/TokenOptions.cs

I'll take a look

**Comment by blowdart** [comment]
@Eilon has decided we'll patch this but quirk it.

**Comment by PinpointTownes** [comment]
A quirk to use the logic added in the "previous" iteration of 2.0.3 or the logic used in 2.0.0?

In both cases, I'm not sure it makes much sense.

**Comment by HaoK** [comment]
Its going to be a quirk that lets you get the old 2.0.0 default value, basically if for whatever reason they want the 2.0 DefaultProvider instead of the DefaultPhoneProvider from token options.  Instead of using the quirk they could just set the option too, but this is the pattern that is used for breaking changes generally (add a quirk mode)

**Comment by PinpointTownes** [comment]
> basically if for whatever reason they want the 2.0 DefaultProvider instead of the DefaultPhoneProvider from token options

lol, are there people that are crazy enough to force their users to enter a token protected by Data Protection in a web form?

Adding a quirk doesn't harm anyone, so... :trollface:

**Comment by HaoK** [comment]
I argued against the quirk mode as well, but what can you do :)

**Comment by HaoK** [comment]
Merged into 2.0.3. via https://github.com/aspnet/Universe/commit/60d604580c4e6ca944390ad6fc760e1e2624c283

**Comment by PinpointTownes** [comment]
Thanks for fixing that :+1:

**Comment by Eilon** [comment]
@PinpointTownes thanks for reporting it! 😄
