### ISSUE TITLE
Changing required password length

### ISSUE THREAD

**Issue by derth** [aspnet/Identity#1487]
I’m using the following code:

`
services.AddIdentity<ApplicationUser, IdentityRole>(options =>
{
	// Password settings
	options.Password.RequiredLength = 8;
	options.Password.RequireNonAlphanumeric = false;
	options.Password.RequireUppercase = false;
})
.AddEntityFrameworkStores<ApplicationDbContext>()
.AddDefaultTokenProviders();
`

When i go to register, and click a single letter for password, the validation scripts still warn me about the default required length, which is 6 characters, instead of the new one i set (8 characters).
If i submit the form, i get the correct warning from the server, for the 8 characters.

**Comment by HaoK** [comment]
The code you have included changes the server side validation, you will also need to update the equivalent client side validation to reflect the new length, its usually a data annotation on the model

**Comment by derth** [comment]
But i don't have access to the user model, it's built in asp.net. How am i supposed to change it?
