### ISSUE TITLE
Authentication Cookie not deleted when using HttpContext.SignOutAsync();

### ISSUE THREAD

**Issue by gustyn** [aspnet/Identity#1488]
Whenever I call the said function, the cookies are never deleted.  I have to delete the cookies manually by calling the following:

`await HttpContext.SignOutAsync();
HttpContext.Response.Cookies.Delete(IdentityServerConstants.DefaultCookieAuthenticationScheme);
HttpContext.Response.Cookies.Delete(IdentityServerConstants.DefaultCheckSessionCookieName);
HttpContext.Response.Cookies.Delete(IdentityServerConstants.ExternalCookieAuthenticationScheme);
`
From everything I have read and based on the name, I should not have to do this.  Am I missing something?

**Comment by HaoK** [comment]
SignOutAsync only signs out the DefaultScheme, it won't sign out multiple schemes for sure.

**Comment by blowdart** [comment]
Closing due to lack of response.

**Comment by gustyn** [comment]
OK thanks.  Sorry missed the response.
