### ISSUE TITLE
IdentityConstants

### ISSUE THREAD

**Issue by pushist1y** [aspnet/Identity#1490]
Consider redeclaring `IdentityConstants` class properties as actual constants instead of static readonly fields. 

These fields are used as authentication schema names. If the application uses more than one auth scheme it can specify the scheme to be used (or multiple) in `Authorize` attribute but the attribute only accepts compile-time constants as parameters. 

I've run into this issue when creating mixed MVC-WebAPI application with double authentication (cookies for MVC pages and JWT for API calls) and i had to declare a constant with value of `"Identity.Application"` to be used with `Authorize` attribute.

**Comment by blowdart** [comment]
This is an interesting design discussion. Constants are generally things that will never change, like the speed of light. We're kind of inconsistent here, and lots of things are constants that shouldn't be, so if anything we ought to move to static readonly unfortunately. So I'm afraid this is not something we're going to do.
