### ISSUE TITLE
[Question] HttpContext?.User?.Identity?.Name casing differs when run on Mac OS vs Windows

### ISSUE THREAD

**Issue by mkArtak** [aspnet/Identity#1496]
Hi.

I have a controller action, which uses current user's name internally. While running on Windows, I got used to getting the result of HttpContext?.User?.Identity?.Name in uppercase. However, just discovered, that the same API returns the value in lowercase on Mac.

The project runs on the latest ASPNET Core framework.

Is this by design ?

Thanks,
Artak

**Comment by blowdart** [comment]
What authentication is in use, is it actually ASP.NET identity, or is it something else?

**Comment by mkArtak** [comment]
It is ASP.Net core identity

**Comment by blowdart** [comment]
Do you have a repro? What template was your app generated from? What databases are being used? Can you upload a sample to github?

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
