### ISSUE TITLE
Password backward compatibility

### ISSUE THREAD

**Issue by rvandulek** [aspnet/Identity#1501]
I'm in the process of creating a new MVC application that has to plug in to our existing SQL Server based user store.  The problem is old user accounts can't be used in the new website, trying to log in with one results in "failure". New accounts can be created, but can't be used by the existing MVC web sites, try to login in with one results in "failure".  I'm guessing this is a compatibility issue for the hashed passwords.  How can I configure the new site, to use the existing (circa 2014 MVC) password hash?  I've compared the NuGet packages in both websites and they match (both are using 2.2.1)

**Comment by HaoK** [comment]
Are you trying to create a new MVC Core application and have it plug into an older Identity 2.2 database?

**Comment by rvandulek** [comment]
No, just a new MVC 5 application (using whatever the current template is in the latest VS 2017).  Our existing apps are also MVC 5, but were created 2-3 years ago (but have been updated, for the most part, via Nuget to the latest component versions).  Existing apps are using .Net 4.5.1.

**Comment by blowdart** [comment]
Moving as this isn't an identity core issue.

**Comment by blowdart** [comment]
This issue was moved to aspnet/AspNetIdentity#2
