### ISSUE TITLE
IdentityServiceCollectionExtensions ambiguous reference

### ISSUE THREAD

**Issue by daniel-tikhonov** [aspnet/Identity#1503]
The type 'IdentityServiceCollectionExtensions' exists in both 'Microsoft.AspNetCore.Identity, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.Extensions.Identity.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

Just trying to access IdentityServiceCollectionExtensions class in my project and it throws error. How can I get this class?

**Comment by HaoK** [comment]
What are you trying to do actually, those are just static extension classes, you can just call the method you want off of IServiceCollection with a using typically.

**Comment by brockallen** [comment]
I bet VS auto added the nuget reference, thus the conflict...?

**Comment by daniel-tikhonov** [comment]
@HaoK I know about extensions, but I really need to call this class directly.

**Comment by daniel-tikhonov** [comment]
@brockallen Microsoft.Extensions.Identity.Core is dependency of Microsoft.AspNetCore.Identity so it need to be added
