### ISSUE TITLE
Using both identity and cookie authentication on the same time is not working

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Identity#1504]
Startup.cs
```
 services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<MultipleDbContext>()
                .AddDefaultTokenProviders();

services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie();
```

Index.cshtml
```
 if (!HttpContext.User.HasClaim(c => c.Type == ClaimTypes.Name))
{
//This will be always called
}
```

If I use both identity and cookie authentication, the cookie authentication won't work

If change the Startup.cs like this, then it will work
Startup.cs
```
services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie();
```

Is this by design?

**Comment by blowdart** [comment]
Identity already adds cookie auth. Why are you trying to do here?

**Comment by andrew-vandenbrink** [comment]
Within 1 domain, imagine content management system,

I have 2 logins, one for anonymous users and one for administrator
Administrator will use identity
Anonymous users will use claims

valid use case?

**Comment by blowdart** [comment]
That's "odd" but possible. You would cookie a second time, just use a unique scheme name and *not* the default as you are doing; you'd also have to configure it so it's not automatic in any way, and then specify the scheme in the authorize attributes when you want to use it.

**Comment by andrew-vandenbrink** [comment]
I think I did try with changing the scheme name but it doesn't work...
