### ISSUE TITLE
Describe default hashing logik in docs

### ISSUE THREAD

**Issue by twenzel** [aspnet/Identity#1505]
Please describe the currently used (v3) logic how a password is hashed (which algorythm and what salt) is used. 
There is no official documentation about those information. Only some blog entries from users/non-officials. You have to dig into the code trying to find those information.

Please extend the offical docs  (https://docs.microsoft.com/de-de/aspnet/core/security/authentication/identity)

**Comment by blowdart** [comment]
As we may, in future, change the algorithms used the source is the prime, err, source for this. If you want the docs updated then please file an issue in the docs repo - https://github.com/aspnet/Docs/issues
