### ISSUE TITLE
Login Providers Question

### ISSUE THREAD

**Issue by Singularity222** [aspnet/Identity#1507]
For the different social logins, a provider key is saved in the AspNetUserLogins table. What does the provider key refer to when using a Google account to sign in? Is it the user ID or something like that?

**Comment by blowdart** [comment]
It's whatever google, or an external provider sends us as their ID for a user. It might be a login, an email, or something entirely unique per user per applications. For Oauth/OIDC it's the subject claim.

In [their docs](https://developers.google.com/identity/protocols/OpenIDConnect) google says

>An identifier for the user, unique among all Google accounts and never reused. A Google account can have multiple emails at different points in time, but the sub value is never changed. Use sub within your application as the unique-identifier key for the user.
