### ISSUE TITLE
Lock user for using invalid credentials in ChangePasswordAsync

### ISSUE THREAD

**Issue by FaizulHussain** [aspnet/Identity#1508]
Is it possible to add the lockout feature during password change if the currentPassword is not valid? Similar to the lockout during signin (if enabled).

Thx

**Comment by blackadder1000** [comment]
I have exactly the same issue, has anyone got an answer?

**Comment by blowdart** [comment]
You would simply call the lockout apis you see in the login code. https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L313
