### ISSUE TITLE
Loading relations from usermanager

### ISSUE THREAD

**Issue by patsadow2** [aspnet/Identity#1509]
Hello, is there any way to load relations ?

    public class ApplicationUser : IdentityUser<Guid>
    {
        public virtual Customer Customer { get; set; }
    }

after

```
var user = await _userManager.FindByEmailAsync(identity.Name);
user.Customer is null 
```

when set value by new and next query the same

user.Customer still null

Any advices ? BR

The same problem here : https://stackoverflow.com/questions/39837355/eager-loading-using-usermanager-with-ef-core

I used : 
```
          var user = await _userManager.FindByEmailAsync(identity.Name);
            _context.Entry(user)
            .Reference(b => b.Vendor)
            .Load();

```
But not sure if it's correct ?

**Comment by HaoK** [comment]
Yeah that seems fine, basically any of the approaches shown here should be fine:  Identity won't load related data, its up to you to do that:

https://docs.microsoft.com/en-us/ef/core/querying/related-data

**Comment by benrhere** [comment]
But what if you want to access related data when you're adding your own custom claims in GenerateClaimsAsync (which gets passed the user object and has no access to db context)?

**Comment by HaoK** [comment]
DbContext's are scoped services so your custom objects should be able to just get them in its ctor

**Comment by benrhere** [comment]
That makes good sense. Thank you!
