### ISSUE TITLE
谁能解释一下为什么用户管理可以批量添加Claim而角色管理却不能呢？

### ISSUE THREAD

**Issue by china-live** [aspnet/Identity#1510]
谁能解释一下为什么用户管理可以批量添加Claim而角色管理不能呢？
这个是bug还是有什么特别的考虑？

![1111](https://user-images.githubusercontent.com/12002799/33108460-2f962ae4-cf77-11e7-939b-72bb9a9e69cf.png)
![2222](https://user-images.githubusercontent.com/12002799/33108461-2fc9c070-cf77-11e7-8018-65fdf457fe19.png)

**Comment by JunTaoLuo** [comment]
@blowdart The user is wondering why you can add an `IEnumberable` of `Claims` in the `IUserStore` but only individual claims in `IRoleStore`

**Comment by blowdart** [comment]
Thank you :) @HaoK do you remember why?

**Comment by HaoK** [comment]
Its just an additional sugar method that we added to the user store.  Its a breaking change to add it to the interface now.
