### ISSUE TITLE
@ missing  in AccessDenied page 

### ISSUE THREAD

**Issue by prashantham** [aspnet/Identity#1511]
> dotnet new mvc --auth Individual -o Test
> Views/Account/AccessDenied.cshtml 

    @{
     ViewData["Title"] = "Access denied";
    }
    <header>
    <h2 class="text-danger">ViewData["Title"]</h2>
    <p class="text-danger">You do not have access to this resource.</p>
    </header>

    Should have been
    <h2 class="text-danger">@ViewData["Title"]</h2>

**Comment by blowdart** [comment]
@pranavkm As you're updating templates right now, could you validate this, and move the issue to templates and fix if it's a problem?

**Comment by pranavkm** [comment]
Moved to https://github.com/aspnet/templating/issues/183
