### ISSUE TITLE
saas application as used Identity？

### ISSUE THREAD

**Issue by qibucloud** [aspnet/Identity#1515]
我做的工作是一个saas应用,有一个Site表，通过SiteId区分，我如何使用Identity，达到每一个站点管理对应的用户列表
The job I'm doing is a saas application with a Site table that distinguishes it by SiteId and how I use Identity to reach the list of users for each site management

**Comment by blowdart** [comment]
Identity isn't aimed as SAAS - you could prefix the usernames in the identity database and then hide/add it from the users using your own convention.
