### ISSUE TITLE
Change the UserManager context connection string

### ISSUE THREAD

**Issue by tgourley** [aspnet/Identity#1516]
I am looking for a way to change the DbContext object that is used by the UserManager/SignInManager that is injected into the AccountController.  As far as I can tell, the underlying context is inaccessible from the AccountController.  I am setting up a multitenant website, and as such, I need to switch the identity context per the request.

Any thoughts?

I have also asked this question on StackOverflow.  https://stackoverflow.com/questions/47516358/changing-asp-net-core-2-0-identity-connection-string-in-controller/47521556

**Comment by blowdart** [comment]
We don't support this, Identity was not designed for multi-tenancy.
