### ISSUE TITLE
Core CLR crashes when using Authorize attribute and OpenIdConnect

### ISSUE THREAD

**Issue by Liero** [aspnet/Identity#1519]
I've described my problem here: https://stackoverflow.com/questions/47674101/asp-net-core-2-0-app-crashes-when-role-based-authorization-faild

Basically, when I use `[Authorize(Roles = "Administrator")]` AND I use OpenIdConnect to authenticate agains AAD:

    services.AddAuthentication(sharedOptions =>
    {
        sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
    })
      .AddCookie(option => option.Cookie.SameSite = SameSiteMode.None)
      .AddOpenIdConnect(option =>
      {
          option.ClientId = config.ClientId;
          option.Authority = String.Format(config.AadInstance, config.Tenant);
          option.SignedOutRedirectUri = config.PostLogoutRedirectUri;    
      });

my application crashes. I've tried to host it in both IIS Express and console app.

Here is error from Windows' Event Log:

> Faulting application name: dotnet.exe, version: 2.0.25816.2, time stamp: 0x59e535ea
> Faulting module name: coreclr.dll, version: 4.6.25815.2, time stamp: 0x59e2b767
> Exception code: 0xc00000fd
> Fault offset: 0x000000000005b2b8
> Faulting process id: 0x1ae4
> Faulting application start time: 0x01d36ea24dd61ded
> Faulting application path: C:\Program Files\dotnet\dotnet.exe
> Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\coreclr.dll
> Report Id: b8649be7-a4a8-464b-8dc0-613bc642dc3a
> Faulting package full name: 
> Faulting package-relative application ID:

**Comment by blowdart** [comment]
This issue was moved to aspnet/Security#1566
