### ISSUE TITLE
Merge all changes from release/2.0.0 back to dev

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Identity#1522]
I'm not sure https://github.com/aspnet/Identity/pull/1485 made it back into dev. I tried merge the branches and there were a bunch of conflicts. We should look into this closer.

**Comment by HaoK** [comment]
I'll double check that everything we wanted from #1485 made it back, but most of that change shouldn't come back to dev as it was a quirks mode fix

**Comment by natemcmaster** [comment]
Ok good to know. Also, this change shouldn't come back to dev either. It was a 2.0.x infrastructure-only change. https://github.com/aspnet/Identity/commit/becf1df9c5a3b908e28ec3c1272b072d8801e3dc

**Comment by HaoK** [comment]
I think we are good, I looked at the changes in rel/2.0.1 and the two fixes we took are already in dev:

87bbff65867710b5a49265fdf09de4a6d539ac8d
b865d5878623077eeb715e600d75fa9c24dbb5a1

Was there any other commits in particular that you wanted me to review/ensure we have in dev from the release branches?

**Comment by natemcmaster** [comment]
Here are the only important changes I'm still seeing when comparing the two branches. Everything else is build infrastructure improvements

https://github.com/aspnet/Identity/compare/release/2.0.0#diff-57b020cd354da4b1e16f9d9e056d92f6
https://github.com/aspnet/Identity/compare/release/2.0.0#diff-aed72f60743ee817f0aef869518022fb

**Comment by HaoK** [comment]
Strange since this looks like it should have been ported in https://github.com/aspnet/Identity/commit/73afa0af5e27b09aeaea684731bbe7a338e21903

never the less, dev has the right code since the fix went in there first anyways, so I don't think that diff is an issue.  The second diff is a release only test for the release only quirks mode so that one we definitely don't want in dev.

**Comment by HaoK** [comment]
Oh maybe the first fix went into 2.0.1 not 2.0?

https://github.com/aspnet/Identity/compare/dev...patch/2.0.1

**Comment by natemcmaster** [comment]
Release/2.0.0 is poorly named. It should release be named "release/2.0". It is used to build any 2.0.x patch. (We'll fix this in 2.1 by naming the branch release/2.1). Also, I need to clean all of our stale branches. patch/2.0.1 might be one of those.

Then to close this out, let's make one of those no-change merges from release/2.0.0 to dev. That should help us move patches from 2.0 to dev if there are any

**Comment by natemcmaster** [comment]
BTW, the latest public release of 2.0.x used this. https://github.com/aspnet/Identity/tree/8c47b90677c0f544844151418ba94f24d9f2a094

**Comment by HaoK** [comment]
I assume we want to do the no-change merge before I do the rename push?

**Comment by natemcmaster** [comment]
yes please

**Comment by HaoK** [comment]
Ok cherry picked your empty merge and pushed: 79de498dcb740f9930adb2218f75df3babec2ba6
