### ISSUE TITLE
How to customize GenerateUserTokenAsync token lifespan? What about brute-force protection? 

### ISSUE THREAD

**Issue by Biarity** [aspnet/Identity#1524]
I'm using `GenerateUserTokenAsync` and `VerifyUserTokenAsync` with `provider="Email"`. How can I customize token expiry so tokens last longer/shorter before they aren't valid?

Additionally, how would you implement token lockout to prevent someone from brute-forcing the token? With `provider="Email"`, the tokens are just 6 digits which should be easy to brute-force (<1 million possibilities, ~11 minutes on a core i3 laptop).

**Comment by blowdart** [comment]
You can plug-in your own token provider for "Email" or any other purpose, and implement shorter lifetimes, or indeed increase the token length.

However I'm a bit confused, we have a specific email token provider which is NOT 6 digits. it is horribly long and would be really hard to brute force. This sounds like you're using the TOTP / Phone one for email? Could we see some configuration and use code?

**Comment by Biarity** [comment]
Yeah, that's what I'll try doing next. I am currently using `provider="Email"`.  This generates a 6 digit code, which is equivalent to using `provider="Phone"`. This might be a bug since using `provider="Default"` generates a long GUID-esque token, which I think is the one you're referring to?

Do you mind pointing me to the source code for the `"Email"` or `"Phone"` (ie. 6-digit) providers? I'd like to see how I can build similar ones, and how you were able to sign such a short token with the purpose/userId/security stamp.

**Comment by blowdart** [comment]
@HaoK is email really not giving the right token here?

**Comment by HaoK** [comment]
Ok sorry I got the defaults mixed up:

"default" is using DataProtection (really long token)
https://github.com/aspnet/Identity/blob/e6f3ebf5810c793edc6f3b4ca3438194786b86a2/src/Microsoft.AspNetCore.Identity/DataProtectionTokenProvider.cs

"email", "phone" are using TOTP (6 digits) https://github.com/aspnet/Identity/blob/dev/src/Microsoft.Extensions.Identity.Core/TotpSecurityStampBasedTokenProvider.cs.



https://github.com/aspnet/Identity/blob/f555a26b4a554f73eea70b4b34fca823fab9a643/src/Microsoft.AspNetCore.Identity/IdentityBuilderExtensions.cs#L28
