### ISSUE TITLE
UserManager does not follow DI rules / Can't decorate IUserStore

### ISSUE THREAD

**Issue by twenzel** [aspnet/Identity#1528]
The [UserManager](https://github.com/aspnet/Identity/blob/87bbff65867710b5a49265fdf09de4a6d539ac8d/src/Microsoft.Extensions.Identity.Core/UserManager.cs#L66) requires an `IUserStore<TUser>` as constructor paramter. But somewhere in [code](https://github.com/aspnet/Identity/blob/87bbff65867710b5a49265fdf09de4a6d539ac8d/src/Microsoft.Extensions.Identity.Core/UserManager.cs#L2277) the store will be casted as `IUserEmailStore<TUser>`. 

The problem is I can't simply replace/decorate the IUserStore<TUser> interface because my implemenation should also implement

* IUserPasswordStore<TUser>
* IUserLoginStore<TUser>
* IUserClaimStore<TUser>
* IUserSecurityStampStore<TUser>
* IUserEmailStore<TUser>
* IUserLockoutStore<TUser>
* IUserPhoneNumberStore<TUser>
* and some more..

So this is not a good DI pattern.

I want to decorate the IUserStore in order to implement a little caching mechanism for the user access.

**Comment by blowdart** [comment]
Afraid so, this was designed before DI was put into ASP.NET, so it's "quirky". Unfortunately there's nothing you can, you can inherit, but not decorate, and it'd be a huge breaking change for us to move it now.
