### ISSUE TITLE
Detect if an external authentication provider was used at sign in or not

### ISSUE THREAD

**Issue by gabosistvanpwc** [aspnet/Identity#1530]
Hi,

Is there any way to tell after login if the current user was signing in by using the regular authentication flow or an external authentication provider?

Thank you

**Comment by grahamehorner** [comment]
the claims for the user identity should have the login provider information?

**Comment by gabosistvanpwc** [comment]
Unfortunately it doesn't. 

I'm using the basic ASP.NET Core Web Application project template with the Individual User Accounts authentication option. As the external provider I have configured the WsFederation middleware as follows:

services.AddAuthentication()
.AddWsFederation(options =>
{
options.Wtrealm = "xxxx";
options.MetadataAddress = "xxxx";
})
.AddCookie();

After the request is going through the usual steps 

1. AccountController.ExternalLogin
2. Identity provider login page
3. AccountController.ExternalLoginCallback (and here _signInManager.ExternalLoginSignInAsync method)

and the user is authenticated the claims from the User.Identity have the same "default" entries as if the user was authenticating directly through the application.

I would like to tell at any point when accessing an action /controller which requires authentication if the user was logging in the system through the regular sign in flow or through an external authentication provider.

Probably I'm missing here something....

**Comment by blowdart** [comment]
This issue was moved to aspnet/Security#1574
