### ISSUE TITLE
Under Membership, please support Groups/tenants for SAAS apps memberships

### ISSUE THREAD

**Issue by papyr** [aspnet/Identity#1532]
This feature is _incorrectly_ named, its supposed to be `Membership `- 

With so many SaaS apps, adoption of ASP is so far behind, primarily **leaving out membership components for groups/tenants** (with the turn of a switch/configurable).

![image](https://user-images.githubusercontent.com/12733414/33976237-76f7e198-e061-11e7-9f3b-dc21bcb3ee8c.png)

Many will argue its not membership, however - a group/company similar to users, i.e. it also has access/features/roles/components enabled at the group level for e.g. free/pro/premium or non-profits/commercial etc. 

IMHO it is a subset of membership. This has not been properly addressed and been punted for a very long time. Further - this is an aspect/AOA of the systems authorization and security, that's commons to many SaaS apps/developers, impeding the rolls out of SaaS apps. Many are reinventing the wheel.

I really like johns sample on [ASP MVC group management](http://bit.ly/2Bn0c7h)

**Comment by blowdart** [comment]
As we've said, ASP.NET identity is not aimed at multi-tenancy. It's identity, because that's what it is, it provides a database schema and support for logging in with either a local or federated identity. There's nothing to stop you adding your own groups support, it is, after all, just a bunch of EF models.

**Comment by whizkidwwe1217** [comment]
@blowdart Yes you're right, those are all just bunch of EF models but there's actually something that stops us from adding our own groups/tenants support and it's the 'UsernameIndex'/'RoleNameIndex' in the IdentityDbContext. You could've just provide us a way to override it in the OnModelCreating. We're not gonna use a bloated ASP.NET Boilerplate 3rd party library or reinvent the Identity library from scratch. I'm sorry but it seems like this library is only for blog sites. It's not ready for enterprise apps. We love ASP.NET Core and we hope we can have this feature in the next versions of it.
