### ISSUE TITLE
[DOC] Please fix doc sample

### ISSUE THREAD

**Issue by postb99** [aspnet/Identity#1533]
Please fix the "Add IdentityUser POCO Navigation Properties" example code on [this page](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x) register entities: in my case I have derivated types for IdentityUser, IdentityRole, IdentityUserRole, IdentityUserToken, IdentityUserLogin (they have int primary/foreign  key), with "long" naming of navigation properties (User has a navigation property named "UserRoles" instead of "Roles"...)

Then my user has UserRoles, UserTokens, UserLogins navigation properties, my Role has UserRoles navigation property.

I end up with correct initial migration with these mapping declarations: in addition to the example code, I declare the one to many relationship from Role to UserRole, so that "RoleId1" column isn't created.

```
modelBuilder_.Entity<User>().HasMany(e => e.UserRoles).WithOne().HasForeignKey(e => e.UserId).IsRequired().OnDelete(DeleteBehavior.Cascade);
modelBuilder_.Entity<User>().HasMany(e => e.UserRoles).WithOne().HasForeignKey(e => e.RoleId).IsRequired().OnDelete(DeleteBehavior.Cascade);
modelBuilder_.Entity<Role>().HasMany(e => e.UserRoles).WithOne().HasForeignKey(e => e.RoleId).IsRequired().OnDelete(DeleteBehavior.Cascade);
modelBuilder_.Entity<User>().HasMany(e => e.UserLogins).WithOne().HasForeignKey(e => e.UserId).IsRequired().OnDelete(DeleteBehavior.Cascade);
modelBuilder_.Entity<User>().HasMany(e => e.UserTokens).WithOne().HasForeignKey(e => e.UserId).IsRequired().OnDelete(DeleteBehavior.Cascade);
```

**Comment by blowdart** [comment]
This issue was moved to aspnet/Docs#5028
