### ISSUE TITLE
Multiple sets of Identity tables from one MVC app.

### ISSUE THREAD

**Issue by dpedrelli** [aspnet/Identity#1535]
Hi,

I have three MVC apps, which all share a single database.  I remapped the names of the Identity tables.  Each MVC app has its own set of Identity tables, in the single database.  I want to be able to create users, in any of the three AspNetUser tables, from a single MVC app.  Can I specify the AspNetUser table name, when I instantiate a UserManager?  What is the best way to do this?

Thanks,

David

**Comment by HaoK** [comment]
Not easily since identity assumes there's only one single `UserManager<TUser>` you can have multiple DbContext's that point to the tables with different user table names mapped.  But you might be able to get this to work with different TUser types, basically:

```
   public class AppUser // All your real stuff
   public class AppAUser : AppUser // just there for distinguishing
   public class AppBUser : AppUser // just there for distinguishing
   public class AppCUser : AppUser // just there for distinguishing

   public class DbContextA // OnModelCreating maps user table to A's table
   public class DbContextB // OnModelCreating maps user table to B's table
   public class DbContextC // OnModelCreating maps user table to C's table

   services.AddIdentity<AppAUser, IdentityRole().AddEntityFrameworkStores<DbContextA>()
   services.AddIdentity<AppBUser, IdentityRole().AddEntityFrameworkStores<DbContextB>()
   services.AddIdentity<AppCUser, IdentityRole().AddEntityFrameworkStores<DbContextC>()

   // Access the appropriate identity manager via the appropriate user generic type.
```

@ajcvickers does that sound reasonable?

**Comment by dpedrelli** [comment]
@HaoK that could work.  I want to extended two of the AspNetUser tables, but differently.  So, I really do need three different ApplicationUser classes.  The ApplicationDbContext.OnModelCreating() is where I remap the tables.  I will try that.  Thanks.

**Comment by dpedrelli** [comment]
@HaoK I implemented this, but I get an error with multiple calls to services.AddIdentity(), as referenced it [https://github.com/aspnet/Identity/issues/1540](https://github.com/aspnet/Identity/issues/1540)

**Comment by HaoK** [comment]
looks like you got it working in the other issue
