### ISSUE TITLE
How can I make the Identity working correctly thought a reverse proxy server?

### ISSUE THREAD

**Issue by zmjack** [aspnet/Identity#1539]
I run a demo MVC project which using ASP.NET Identity under a private network (192.168.200.1). And I setup a reverse proxy server (192.168.200.201) to visit it.

I use IIS 6.1 with Application Request Routing (ARR) 2.5 as the reverse proxy server.

In the Identity library, the default LoginPath is **"/Account/Login"**. I don't change it, but when I visit some Actions which need Authorized in **192.168.200.201**, it always redirect to **"192.168.200.1/Account/Login"**. It's going wrong! The correct redirect address is **"192.168.200.201/Account/Login"**.

What's wrong with it? I look forward to your reply. Thank you!

**Comment by blowdart** [comment]
You need to config the proxy server to pass on X-Forwarded-For and then wire that in using the [.UseForwardedHeaders](https://github.com/aspnet/BasicMiddleware/blob/dev/samples/HttpOverridesSample/Startup.cs) middleware.

**Comment by zmjack** [comment]
I tried, but it doesn't work in IIS with ARR 2.5.

So, I have to find another solution.

I use ngnix as reverse proxy server to visit the http server. I can't belive that it's working correctly!

I don't know what happened, but it's a right way to make Identity work correctly on ngnix.

Thank you!

**Comment by blowdart** [comment]
You reopened this.

So what isn't working? It certainly does work with IIS with ARR, that's how Azure Web Apps work. For nginx you need to configure nginx to forward the headers, for example https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/
