### ISSUE TITLE
User name and email confusing

### ISSUE THREAD

**Issue by fe-c** [aspnet/Identity#1541]
Hello!
I was created ASP.Net Core project with individual accounts.
After user registration User Name and Email are same.
I was edit Profile page to change User Name, becouse I want to display user name, not email in top navbar.
At now I cant login, cause signInManager.PasswordSignIn need user_email in user name field.
When I change user email, I still need to signin with user_name=old_user_email.
It's very confusing users and developers.

**Comment by blowdart** [comment]
Can you post a small repro of the changes you made?

**Comment by fe-c** [comment]
I just make user name editable. signInManager.PasswordSignIn don't have ability to login with email, so i revert this chanhes.

**Comment by HaoK** [comment]
Yes so in the templates, it conflates UserName and Email, registering a user using the email as the initial user name.  So if you add the ability to change the email, that does not affect the user name for the user.  You could try updating both UserName and Email at the same time in your app.

**Comment by fe-c** [comment]
Yes, I can change them at the same time. I can also add one more field for the real user name, and so on.

Perhaps a better solution would be to create a "Login" field, into which you can write a login, email or phone? and use it to sign in methods.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
