### ISSUE TITLE
sample project needs more 

### ISSUE THREAD

**Issue by samarmir** [aspnet/Identity#1542]
I find it dissapointing that the sample code does not show how to extend the applicationuser with extra properties.

**Comment by blowdart** [comment]
@ajcvickers This would fall into your documentation updates.

**Comment by HaoK** [comment]
We should wait to see how the new UI stuff in 2.1 ends up before updating the documentation since otherwise the documentation updates might be obsolete immediately :)

**Comment by ajcvickers** [comment]
New documentation is here: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1
