### ISSUE TITLE
Optimistic concurrency failure upon using RoleManager DeleteAsync!

### ISSUE THREAD

**Issue by embryologist** [aspnet/Identity#1546]
My implementation,

**`ApplicationRole Class`**

      public class ApplicationRole: IdentityRole
        {
            public string Description { get; set; }
        }
**`ApplicationRoleViewModel class`**

    public class ApplicationRoleViewModel
    {
        public string RoleId { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Role Name")]
        public string RoleName { get; set; }
        public string Description { get; set; }
    }

**Registering `Identity` Service**

     services.AddIdentity<ApplicationUser, ApplicationRole>

**`Registering RoleManager Service`**

    services.AddScoped<IRoleManager, RoleManager>();

**`RoleManager` Service**

    public interface IRoleManager
        {
            Task<IdentityResult> CreateAsync(ApplicationRoleViewModel model);
            Task<IdentityResult> DeleteAsync(ApplicationRoleViewModel model);
        }
        public class RoleManager : IRoleManager
        {
            private readonly RoleManager<ApplicationRole> roleManager;
            public RoleManager(RoleManager<ApplicationRole> roleManager)
            {
                
                this.roleManager = roleManager;
    
            }
            public Task<IdentityResult> CreateAsync(ApplicationRoleViewModel model)
            {
                ApplicationRole role = new ApplicationRole();
                role.Name = model.RoleName;
                return this.roleManager.CreateAsync((role));
            }
            public Task<IdentityResult> DeleteAsync(ApplicationRoleViewModel model)
            {
                ApplicationRole role = new ApplicationRole();
                role.Name = model.RoleName;
                return this.roleManager.DeleteAsync((role));
            }

        }

**`UserManagementController`** 

    [HttpDelete]
     public async Task<IActionResult> DeleteIdentityRole([FromBody] ApplicationRoleViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            IdentityResult result = await this.roleManager.DeleteAsync(model);
            if (result.Succeeded)
                return Ok(model.RoleName + " role has been created successfully");

        return BadRequest(result.Errors);

    }
I keep receiving this error by calling `DeleteAsync`
> Optimistic concurrency failure, object has been modified.

**Comment by embryologist** [comment]
It was a wrong implementation in the service,
buggy code of mine,
I am closing this issue

**Comment by douglampe** [comment]
For anyone else who stumbled on this before solving the problem, here is the solution:
````
            ApplicationRole role = await roleManager.FindByNameAsync(model.RoleName);
            return this.roleManager.DeleteAsync(role);
````
Creating a new instance of the role creates a new entity object that is in a new state which then is added to the manager context when delete is called. This is why the "object has been modified" error occurs.
