### ISSUE TITLE
How to get all Roles using asp.net core 2 Identity?

### ISSUE THREAD

**Issue by embryologist** [aspnet/Identity#1547]
**This is a question, Not an Issue**
I have a custom `IdentityRole` called `ApplicationRole`. I created a RoleManager Service and I was successful in creating new roles using `CreateAsync` method but I am facing  I can't get all roles using this implementation (`GetAllRolesAsync`). I keep getting this error,

> Cannot implicitly convert type
> 'System.Collections.Generic.List<ApplicationRole>' to
> 'System.Threading.Tasks.Task<ArtNgCore.Controllers.ViewModels.IdentityViewModels.ApplicationRoleViewModel>'

I am posting the relevant code for this implementation.

  **`ApplicationRole Class`**

      public class ApplicationRole: IdentityRole
        {
            public string Description { get; set; }
        }
**`ApplicationRoleViewModel class`**

    public class ApplicationRoleViewModel
    {
        public string RoleId { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Role Name")]
        public string RoleName { get; set; }
        public string Description { get; set; }
    }

**Registering `Identity` Service**

     services.AddIdentity<ApplicationUser, ApplicationRole>

**`Registering RoleManager Service`**

    services.AddScoped<IRoleManager, RoleManager>();

**`RoleManager` Service**

    public interface IRoleManager
        {
            Task<List<ApplicationRoleViewModel>> GetAllRolesAsync();
            Task<IdentityResult> CreateAsync(ApplicationRoleViewModel model);
            Task<IdentityResult> DeleteAsync(ApplicationRoleViewModel model);
        }
        public class RoleManager : IRoleManager
        {
            private readonly RoleManager<ApplicationRole> roleManager;
            public RoleManager(RoleManager<ApplicationRole> roleManager)
            {
                
                this.roleManager = roleManager;
    
            }
            public Task<IdentityResult> CreateAsync(ApplicationRoleViewModel model)
            {
                ApplicationRole role = new ApplicationRole();
                role.Name = model.RoleName;
                return this.roleManager.CreateAsync((role));
            }
            public Task<IdentityResult> DeleteAsync(ApplicationRoleViewModel model)
            {
                ApplicationRole role = new ApplicationRole();
                role.Name = model.RoleName;
                return this.roleManager.DeleteAsync((role));
            }
    
            public Task<List<ApplicationRoleViewModel>> GetAllRolesAsync()
            {
                var roles = this.roleManager.Roles.ToList();
                return roles;
            }

        }

**`UserManagementController`** 

    [HttpGet]
    public async Task<IActionResult> GetAllRoles() {
        var roles = this.roleManager.GetAllRolesAsync();
        return Ok(roles);
    } 

    [HttpDelete]
     public async Task<IActionResult> DeleteIdentityRole([FromBody] ApplicationRoleViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            IdentityResult result = await this.roleManager.DeleteAsync(model);
            if (result.Succeeded)
                return Ok(model.RoleName + " role has been created successfully");

        return BadRequest(result.Errors);

    }

**Comment by HaoK** [comment]
this.roleManager.Roles.ToList() would be an `List<ApplicationRole>` which is not a  `List<ApplicationRoleViewModel>`
