### ISSUE TITLE
update wiki page. it's showing code for asp.net core RC1

### ISSUE THREAD

**Issue by SychevIgor** [aspnet/Identity#1563]
Please, update or delete this page 
![image](https://user-images.githubusercontent.com/578954/34813158-e419ad06-f6b9-11e7-850a-34a765a390d4.png)

https://github.com/aspnet/Identity/wiki/Using-Identity-in-ASP.NET-applications

you are using namespaces no longer available starting from RC2... it's not a good sign for wiki.

**Comment by blowdart** [comment]
@Eilon Can you just delete the wiki?

**Comment by Eilon** [comment]
As in, completely hide the wiki? I can do that. It'll mean any existing links to it will be broken. Are you ok with that?

**Comment by blowdart** [comment]
There's nothing in it but a single page, so yes, kill it please :)

**Comment by Eilon** [comment]
Wiki is gone.
