### ISSUE TITLE
Expose ASP.NET Identity via LDAP interface (.NET Core 2.0)

### ISSUE THREAD

**Issue by sebastianbk** [aspnet/Identity#1568]
I have an ASP.NET Core 2.0 application where I am using the stock implementation of ASP.NET Identity to manage and authenticate my users.

I would like to use my application as an identity provider for 3rd party service that I am planning on using. The only issue is that this service can only communicate with identity providers over LDAP.

Is there a way to stand up an LDAP server as part of my ASP.NET Core application?

I know there is an option to do so in Java by using UnboundID LDAP SDK. However, I cannot find a .NET alternative to this.

How should I go about exposing my ASP.NET Identity users via LDAP?

**Comment by blowdart** [comment]
That's not something we'd consider supporting I'm afraid. LDAP isn't an HTTP based protocol, so it wouldn't be an ASP.NET concern at all. I'm unaware of any .net core based library for this.
