### ISSUE TITLE
ASP.NET Core 2.0 Identity Expiration

### ISSUE THREAD

**Issue by Ruslan-Ba** [aspnet/Identity#1575]
Please, see: 
https://github.com/aspnet/Identity/issues/1478

```
services.ConfigureApplicationCookie(options =>
            {            
                options.CookieName = "Test1";
                options.AccessDeniedPath = new Microsoft.AspNetCore.Http.PathString("/account/login");
                options.LoginPath = new Microsoft.AspNetCore.Http.PathString("/account/login");
                options.ExpireTimeSpan = TimeSpan.FromMinutes(1);
                options.SlidingExpiration = true;
            });
```

AccessDeniedPath  is ignored when cookie expires.
401 returns but is it expected to be redirected to AccessDeniedPath ?

**Comment by blowdart** [comment]
That issue is about expiring cookies. Please give us more information to go on, and post your app configuration

**Comment by Ruslan-Ba** [comment]
I updated the issue

**Comment by blowdart** [comment]
And this is a browser based request? 

In any case when the cookie expires I would expect it to redirect to login - at that point the user is now unauthenticated, so they are treated as anonymous.

Whats does auth configuration look like? i.e. everything before you are calling .ConfigureApplicationCookie?

**Comment by Ruslan-Ba** [comment]
"And this is a browser based request?" - Yes
"I would expect it to redirect to login" - We do it with JS

The question is: Why do we need AccessDeniedPath if it does not do anything?
I expected to be redirected to AccessDeniedPath.
Please, correct me if I am wrong.

**Comment by blowdart** [comment]
Sorry, you do what with JS? This isn't an HTTP Post form submit? It's an ajax request?

**Comment by Ruslan-Ba** [comment]
Yes, it is an ajax request.

**Comment by blowdart** [comment]
Then it's doing what it's supposed to. AJAX doesn't follow redirects, so you're going to get a status code back, and it's a 401 because the cookie no longer exists, therefore the user is unauthenticated, therefore you get a 401.

**Comment by Ruslan-Ba** [comment]
Thank you. 
You may close the issue.
