### ISSUE TITLE
Using EntityFramework Core to store Identity Database in Azure sql

### ISSUE THREAD

**Issue by simont789** [aspnet/Identity#1576]
Hi Community,

As mentioned, I'm trying to store all my Identity information in Azure Sql using Ef Core. Thought it would have been smooth but I've been facing a lot of difficulties. Research online has shown me ways to edit the migration file, since there are some wrong data type when it is mapped. However I'm still stuck with the "System.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated." message. 

Before I show my problem to the community, just wondering if there is a proper tutorial to teach us how to map your Identity core to a database with Entity Framework Core? Or if there is an easier way to do things? All I wanna do is just saving my Identity info on the cloud for my asp.net core app. Really just using the default settings at the moment. 

If these information does not solve the problem I will post my code up and try to solve the bug with you guys. 

Cheers for the help!

**Comment by simont789** [comment]
Found the problem. I was using the default migration that was created for SqLite. Was fine when I created another migration file. Cheers!

**Comment by blowdart** [comment]
That's somewhat strange, any chance you could post your startup.cs - it should use the provider you wired up, or did you bring the default migration from another project?
