### ISSUE TITLE
Travis not enabled in Identity?

### ISSUE THREAD

**Issue by javiercn** [aspnet/Identity#1584]
For some reason it doesn't seem to be triggered @HaoK @Eilon 

![image](https://user-images.githubusercontent.com/6995051/35198212-64051ad0-fea0-11e7-86df-6249a08ce705.png)

**Comment by HaoK** [comment]
This must be specific to some of PRs, travis is showing up in typically in mine: https://github.com/aspnet/Identity/pull/1577

**Comment by Eilon** [comment]
I think this is the reason: https://github.com/aspnet/Identity/blob/dev/.travis.yml#L17-L23

**Comment by javiercn** [comment]
Should we remove that?

**Comment by Eilon** [comment]
Yes we ought to tweak the list of branches there (and remove old bogus ones). But please in `dev` only because we don't want to cause spurious builds in the patch branch.

**Comment by javiercn** [comment]
Is @ryanbrandenburg the right person to do this? (I have absolutely no idea how this works). I checked MVC and we probably have to also do it there, so I'm inclined to think this is a change across all our repos

**Comment by HaoK** [comment]
What's the issue exactly, your private branches don't get verified?  Can't you just create a PR with a merge against dev to trigger the CI build?

**Comment by javiercn** [comment]
Closing this. It's likely due to the base branch the branch was getting merged into.
