### ISSUE TITLE
IUserStore/IUserRoleStore

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Identity#1585]
IMHO IUserRoleStore<T> shouldn't inherit for IUserStore<T> as this could case issues where user roles have a different storage provider to that of the UserStore; ie. a centralised user store for multiple applications; with each application having an implementation of the role store.

**Comment by HaoK** [comment]
IUserStore has the only methods that should be updating/committing the user (Create/Update/Delete), the IUserRoleStore methods should only be updating the entity, but the changes shouldn't be 'persisted' until Update is called.
