### ISSUE TITLE
Consider changing the 'purpose' to device identifier

### ISSUE THREAD

**Issue by wiktor-golonka** [aspnet/Identity#1602]
Hi,
Currently the method `ValidateAsync `from the `IUserTwoFactorTokenProvider<TUser>` contains a parameter called 'purpose' which is always equals to 'TwoFactory' if the default method in `UserManager `is not overridden. 

This is because the default implementation inside the `Microsoft.AspNetCore.Identity.UserManager<TUser>`
of the method `VerifyTwoFactorTokenAsync(TUser user,string tokenProvider, token)`
looks that: 
`var result = await _tokenProviders[tokenProvider].ValidateAsync("TwoFactor", token, this, user);`
 
So this 'purpose' parameter seems to be pretty useless right now. However it could be replaced by some kind of device identifier so it would be easier to store multiple devices for the same TokenProvider (so the single user could have 2 devices for the same token provider).

Please let me know what you think.

**Comment by blowdart** [comment]
We have no plans to add support for multiple devices which have different tokens.
