### ISSUE TITLE
[UI] 2fa: Forget this browser button is broken

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#1611]
@javiercn this was probably introduced with your extensibility changes due to the base model not having OnPost defined so clicking the button doesn't run the server side handler to clear the remember me cookie.

https://github.com/aspnet/Identity/blob/dev/src/UI/Areas/Identity/Pages/Account/Manage/TwoFactorAuthentication.cshtml.cs#L27

I thought it was a bug in the new totp/security stamp code i was working on...but it turned out the button was a placebo...click on it all you want, it never clears your remember browser since it doesn't hit the method :)

This probably is in the preview 1 templates as well.

**Comment by javiercn** [comment]
@HaoK Good catch. I'm going to start the process to get this into preview1

**Comment by javiercn** [comment]
Actually, this is only on dev, isn't it? I think it was a bad merge on my part.

**Comment by HaoK** [comment]
I didn't look at other branches, I'm only in dev, I already fixed it in my branch so I'm not blocked on this...

**Comment by HaoK** [comment]
Fixed as part of c6a82ad19a0bdb80b7358dc843b66664bbf33f96
