### ISSUE TITLE
Cookie expiration always set to Session

### ISSUE THREAD

**Issue by robfarmergt** [aspnet/Identity#1612]
Seems like the Identity application cookie is always set to `Session` even when the expiration TimeSpan is set. I'm using .NET Core 2.0.

```
services.ConfigureApplicationCookie(options =>
    {
        // Cookie settings
        options.Cookie.HttpOnly = true;
        options.Cookie.SecurePolicy = MyAppConfig.Secure ? CookieSecurePolicy.Always : CookieSecurePolicy.None;
        options.Cookie.Name = "IbIdentity";
        options.Cookie.Expiration = TimeSpan.FromMinutes(30);
        options.ExpireTimeSpan = TimeSpan.FromMinutes(30);
        options.SlidingExpiration = true;
    });
```

**Comment by blowdart** [comment]
ExpireTimeSpan and SlidingExpiration are mutually exclusive.

Making it permanent is a function of the call to SignIn

```c#
await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);
```

The third parameter, RememberMe is what you want

**Comment by robfarmergt** [comment]
Thank you @blowdart. What I'm trying to achieve is for Identity to authorize the user for sliding time period of 30 minutes.

With the settings above and setting `rememberMe: true` during `SignIn` is that achieved? I can see the cookie being set with an expiration date and that it "slides" with additional requests but I want to make sure Identity is also set to have the authorization work the same way.

**Comment by blowdart** [comment]
I believe you don't need to set options.Cookie.Expiration, just the ExpireTimeSpan and set Sliding. Is that right @HaoK ?

**Comment by robfarmergt** [comment]
As far as the cookie on the client that seems to be the case. I can remove it and behavior stays the same.

What I want to confirm too is that even though the cookie is set to expire, if someone were to try to use that cookie after the expiration will the server invalidate the request?

**Comment by HaoK** [comment]
Yeah options.SlidingExpiration  = true and options.ExpireTimeSpan

**Comment by HaoK** [comment]
Yes, see https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs#L140

**Comment by robfarmergt** [comment]
Thanks so much @blowdart and @HaoK ! Really impressed with the work being done! Thanks again!

**Comment by blowdart** [comment]
Just to be clear for others who end up here the expiry of a ticket is a property of the ticket itself, not the cookie. So even if the cookie lives on the expiry date is baked into the data it contains, so after it expires, it's dead regardless.

**Comment by robfarmergt** [comment]
@blowdart meaning the expiration of the cookie is tied to the expiration of the ticket. So even if someone tried to fudge the cookie expiration the server will reject it?

**Comment by blowdart** [comment]
Correct :)

**Comment by HaoK** [comment]
Yeah this is why the options.Cookie.Expiries property is ignored for cookie authentication, its that embedded expiry date in the data that matters.
