### ISSUE TITLE
Replace SignIn with RefreshSignIn in UI 

### ISSUE THREAD

**Issue by jbagga** [aspnet/Identity#1616]
> Manage actions lose cookie info (persistent/external login claim) when they call SignInAsync instead of RefreshSignIn

See https://github.com/aspnet/Identity/pull/1615#issuecomment-363236876

cc @HaoK

**Comment by HaoK** [comment]
Cool, are you planning on fixing this @jbagga ?

**Comment by jbagga** [comment]
I'll let it be triaged first. @Eilon

**Comment by Eilon** [comment]
Yeah seems like a good idea.

**Comment by jbagga** [comment]
Assigning cost: S as I expect to wrap this up within a day or two.
