### ISSUE TITLE
[IdentityUI]: Consider showing a landing page that says account was successfully deleted before redirecting to the home page

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Identity#1619]
When deleting personal data succeeds, the page immediately redirects to the site root allowing no opportunity to show a success message. We should consider showing a success page (*Sorry to see you go 😦*) that redirects to the site root.

**Comment by blowdart** [comment]
Why? During customization you could add this anyway. Why give people an extra screen, they're deleted, they "don't matter"
