### ISSUE TITLE
[IdentityUI]: Experience for using a custom ApplicationUser : IdentityUser has room for improvement

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Identity#1620]
Writing the release verification plan for Identity that involves using a custom ApplicationUser type with additional properties. To do this, it seems like I have to override the following files in my application:

* https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.DefaultUI/Areas/Identity/Pages/_ViewImports.cshtml
* https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.DefaultUI/Areas/Identity/Pages/Account/Register.cshtml
* https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.DefaultUI/Areas/Identity/Pages/Account/Register.cshtml.cs
* https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.DefaultUI/Areas/Identity/Pages/Account/Manage/Index.cshtml
* https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.DefaultUI/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs

There's a fair bit of knowing the details of how things Identity UI work once you get to these many files. In addition, we'd need to provide guidance for users that customized these pages if we do update these files in our package. If this is a fairly commonly scenario, perhaps the experience in using a custom user this should be first class.

**Comment by javiercn** [comment]
@pranavkm I do believe this is covered by the scaffolder. It will allow you to choose individual views to scaffold in the future. If that sounds good to you, feel free to close this.

**Comment by pranavkm** [comment]
Cool, I didn't know about the Scaffolding experience whilst I created the issue. There were a couple of ideas thrown around as part of https://github.com/aspnet/Release/issues/235 to customize `ApplicationUser`. Do we want to use this issue to track those? I don't think there was a follow up to the conversation.

Tagging @HaoK  since he was also on that thread.

**Comment by javiercn** [comment]
@pranavkm I would suggest filing independent bugs for those things. I have scanned the thread but I wasn't sure what you meant.

**Comment by javiercn** [comment]
@pranavkm I'm closing this issue. Can you file individual issues for your specific suggestions is they still apply?

**Comment by javiercn** [comment]
@pranavkm Or please confirm they don't apply anymore.
