### ISSUE TITLE
How to perform additional checks on cookie login?

### ISSUE THREAD

**Issue by Amethi** [aspnet/Identity#1622]
Hello. I’ve got a UserStatus claim that says if the user is Activ/Suspended/Banned. I use this to check if a user can sign-in or not. This works fine for controller-based logins, i.e. external or username & password as I can add my custom check code there, but how can I add this check when a user is signing in using a cookie?

**Comment by blowdart** [comment]
You could add a validator, or an event. A validator would probably be better because it'll allow you to sign out users when you change their status.

Start with https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?tabs=aspnetcore2x#reacting-to-back-end-changes - and then if you are using ASP.NET Core Identity let us know and we'll help you wire it up.

**Comment by Amethi** [comment]
Thanks. I'm using ASP.NET Core Identity with Identity Server 4 to service OIDC clients.

I did try the CustomCookieAuthenticationEvents approach from that article but it didn't fire for me. For now I'd be happy with a sign-in event I could hook into.

**Comment by Amethi** [comment]
I've solved this. I needed to do it this way:

Startup.cs:
`services.AddSingleton<IConfigureOptions<CookieAuthenticationOptions>, ConfigureCookieOptions>();`

NEW: ConfigureCookieOptions.cs:
```
internal class ConfigureCookieOptions : IConfigureNamedOptions<CookieAuthenticationOptions>
    {
        private readonly IConfiguration _configuration;

        public ConfigureCookieOptions(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public void Configure(CookieAuthenticationOptions options) { }

        public void Configure(string name, CookieAuthenticationOptions options)
        {
            options.Events = new DatabaseCookieAuthenticationEvents(_configuration);
        }
    }
```

New: DatabaseCookieAuthenticationEvents.cs:
```
 public class DatabaseCookieAuthenticationEvents : CookieAuthenticationEvents
    {
        private readonly IConfiguration _configuration;

        public DatabaseCookieAuthenticationEvents(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public override Task ValidatePrincipal(CookieValidatePrincipalContext context)
        {
            if (!context.Principal.IsAuthenticated())
                return base.ValidatePrincipal(context);

            using (var connection = new SqlConnection(_configuration["DefaultConnection"]))
            using (var command = new SqlCommand())
            {
                connection.Open();
                command.Connection = connection;
                command.CommandText = $"SELECT [Status] FROM AspNetUsers WHERE [Id] = '{context.Principal.GetSubjectId()}'";

                var status = (UserStatus) command.ExecuteScalar();
                if (status != UserStatus.Active)
                {
                    context.RejectPrincipal();
                    context.HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme).Wait();
                }
            }

            return base.ValidatePrincipal(context);
        }
    }
```

Not very elegant, but I couldn't work out how to get UserManager into the ConfigureCookieOptions singleton.
