### ISSUE TITLE
Asp .Netcore 2.0 Auth Cookie doesn't expire in Chrome

### ISSUE THREAD

**Issue by PacmanLazy** [aspnet/Identity#1624]
I used that code below to manage cookies behaviour.
But if I don't use "RememberMe" cookie which expires on session end doesn't expire in Google.
I can't find any solution.
For example, in django I could use request.session.set_expiry(expiration_time)
`services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(options =>
    {
        // Cookie settings
        options.Cookie.HttpOnly = true;
        options.Cookie.SameSite = SameSiteMode.Strict;
        options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
        options.LoginPath = "/Account/Login";
        options.LogoutPath = "/Account/Logout";
        options.AccessDeniedPath = "/Account/AccessDenied";
    }
);

services.ConfigureApplicationCookie(options =>
{
    // Cookie settings
    options.Cookie.HttpOnly = true;
    options.Cookie.SameSite = SameSiteMode.Strict;
    options.SlidingExpiration = true;
    options.Cookie.Expiration = TimeSpan.FromDays(150);
    options.ExpireTimeSpan = TimeSpan.FromDays(150);
});`

**Comment by blowdart** [comment]
Why can't you use remember me when you're signing in, which as you say, works?

**Comment by PacmanLazy** [comment]
But what if I want different time cookies/sessions? I tried to modify
headers, but it doesn't work. I can't find the way to control or modify
that not only with startup file.

2018-02-15 22:20 GMT+02:00 Barry Dorrans <notifications@github.com>:

**Comment by blowdart** [comment]
You can configure an absolute expiry via the options, or use remember me to make it persistent. Those are the only options I'm afraid.
