### ISSUE TITLE
Setting `RazorPagesOptions.AllowAreas` to `false` does not disable area pages

### ISSUE THREAD

**Issue by dougbu** [aspnet/Identity#1626]
_From @dougbu on February 10, 2018 21:26_

Change `Startup.ConfigureServices` to include
``` c#
            services
                .AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_0)
                .AddRazorPagesOptions(options =>
                {
                    options.AllowAreas = false;
                });
```

Expected: All area-related pages result in 404s.
Actual: See the usual content of pages such as https://localhost:44312/Identity/Account/Manage or https://localhost:44312/MyArea

Note either `CompatibilityVersion.Version_2_0` or `AllowAreas == false` should have been sufficient to disable areas.

_Copied from original issue: aspnet/Mvc#7348_

**Comment by dougbu** [comment]
_From @pranavkm on February 14, 2018 15:55_

Is this specifically with pages from a precompiled class library? I can't reproduce this with files on disk.

**Comment by dougbu** [comment]
No, problem wasn't specific to area pages in a library. I also cleaned and rebuilt my solution a few times to ensure I wasn't testing older code. Then again, my test app does use area pages from a library -- the Identity.UI pages in particular.

Which SDK build are you testing with? I'm using 2.1.300-preview1-008117.

I'll test this again with 2.1.300-preview1-008123 later today.

**Comment by dougbu** [comment]
Turns out the problem was my `Startup` calls `IdentityBuilder.AddDefaultUI()`. This has the unexpected behaviour of enabling a `IPostConfigureOptions<RazorPagesOptions>` implementation (`IdentityDefaultUIConfigureOptions<{IdentityUserType}>`) which **overrides** this user's `RazorPagesOptions.AllowAreas` setting.

Side note: That configuration setup also overrides user `StaticFileOptions.FileProvider` settings. Fortunately, other options properties set in `IdentityDefaultUIConfigureOptions<{IdentityUserType}>` seem to be additive.

Will move this issue to the Identity repo.

**Comment by dougbu** [comment]
_From @mkArtakMSFT on February 14, 2018 18:1_

@dougbu, can you please confirm this is not the case for usual (local) views? /cc @javiercn

**Comment by dougbu** [comment]
> @dougbu, can you please confirm this is not the case for usual (local) views?

Not sure of your exact question @mkArtakMSFT. But, the effect of setting `RazorPagesOptions.AllowAreas` to `true` unconditionally is global -- affecting area pages on disk as well as those in the Identity.UI library. And, it overrides the user's chosen compatibility version as well as any implicit or explicit change they've made to `AllowAreas`.

**Comment by HaoK** [comment]
This is sort of expected, AddDefaultUI is really forcing some opinionated settings on MVC as well.

cc @davidfowl I think this is another point in favor of making one uber `AddDefaultIdentityEntityFrameworkUI<TUser, TRole, ApplicationDbContext>()` method since now its just not auth settings that identity will clobber, its also clobbering razor and static files

**Comment by dougbu** [comment]
@HaoK how would that uber method help here? The issue is the unexpected clobbering, not the number of extension methods needed to thoroughly clobber anything.

My suggestion is for `dentityDefaultUIConfigureOptions<{IdentityUserType}>` to also implement `IConfigureOptions<RazorPagesOptions>` and `IConfigureOptions<StaticFileOptions>`. Those new methods would handle `RazorPagesOptions.AllowAreas` and `StaticFileOptions.FileProvider` while allowing later user overrides.

One alternative would be for the existing methods to `throw` if reached when the options aren't set as expected. That would give the user the knowledge to choose between setting `AllowAreas==true` or using the default Identity UI.

Finally, overriding `StaticFileOptions.FileProvider` unconditionally may just be a bug. Could add a `null` check there.

**Comment by HaoK** [comment]
I think the default UI requires areas so I don't think its unreasonable for that to set allow areas = true. 

If you want to override it, you can still turn it off again after you call AddDefaultUI right?

Basically my point is mostly just that identity sets up a bunch of opinionated defaults to make things 'work' by default.

**Comment by HaoK** [comment]
Oh I see, so you are just complaining about the fact that the UI is doing the stomping in post configure?  So users would have to override by adding a `PostConfigure(o = > o.AllowAreas = false)`...  but its kind of nonsensical to use both DefaultUI and try to turn areas off....

**Comment by dougbu** [comment]
> it's kind of nonsensical to both use DefaultUI and try to turn areas off

Not sure I buy that. It's an internal implementation detail of the Identity UI that it uses areas. Why would a user think the two features are related?

Separately, we could also go at this by removing the *global* option's impact on area pages in libraries. Users could then set the option however they like. See also aspnet/Mvc#7346. (Note `IdentityDefaultUIConfigureOptions<{IdentityUserType}>` does not change the options mentioned in that issue. But, they still have the potential to break the Identity UI.)

**Comment by HaoK** [comment]
So AllowAreas = false with AddDefaultUI would result in blocking areas except for ones added by libraries?  

I fully agree that its a mystery what AddDefaultUI does...  I pushed strongly for naming it something explicit like AddRazor/MVCUI, but Dan/Damian liked a more generic name rather than mention any implementation details in the name...

**Comment by dougbu** [comment]
> So AllowAreas = false with AddDefaultUI would result in blocking areas except for ones added by libraries?

Yup, that's what I'm suggesting.

**Comment by javiercn** [comment]
> It's an internal implementation detail of the Identity UI that it uses areas

Areas are not an implementation detail of how the Identity UI works, it is part the contract that we choose to have at the MVC level with other parts of your application.

We don't consider the scenario of turning off areas to be a common case and we favor an experience in which AddDefaultUI always gives you a result that works. In other words, we prefer doing anything we need to do to make it work other than throw an exception if things are not setup correctly.

Regarding the changes on the file system part, it's a small bug in there. I've sent out a PR to fix it. I'll let Hao review it.
https://github.com/aspnet/Identity/pull/1629/files

**Comment by dougbu** [comment]
> it is part the contract that we choose to have at the MVC level with other parts of your application.

That contract (between Identity and MVC) doesn't equate to user understanding.

**Comment by Eilon** [comment]
Is the issue here that the DefaultUI is modifying MVC settings to make sure that it will work? That seems reasonable to me.

Is there any other issue being discussed here?

**Comment by dougbu** [comment]
@Eilon my concern is more about user expectations and their ability to configure the application as they wish. `AddDefaultUI(...)` isn't just changing MVC settings so it will work, it's also resetting changes users may make.

The more I think about this, the more I like the idea of splitting user decisions about their application from provider decisions about libraries they provide. That's more general than `AllowAreas` having only two possible values and affecting all area pages everywhere. But, if gave library authors control over their libraries (as we did in localization), they wouldn't have to clobber user settings.

**Comment by Eilon** [comment]
> ability to configure the application as they wish

They absolutely are. Last person to change an option wins. The user's customizations of options should come last.

**Comment by dougbu** [comment]
> The user's customizations of options should come last.

Not true in this case.

Because Identity uses `IPostConfigureOptions<RazorPagesOptions>`, the only way users can change things would be to also implement `IPostConfigureOptions<RazorPagesOptions>` and add their instance after calling `AddDefaultUI(...)`. That's not particularly discoverable or friendly and is why I earlier suggested having `IdentityDefaultUIConfigureOptions<{IdentityUserType}>` set `AllowAreas` in a new `IConfigureOptions<RazorPagesOptions>` method (i.e. non-post).

**Comment by Eilon** [comment]
Ah, fair point, I did not realize that.

However, if this option isn't set, the UI won't work, right? So why would you want to disable it *and* use the UI?

**Comment by HaoK** [comment]
So its a little odd that its post configure instead of normal configure, but its not that hard for them to override, they just do `servives.PostConfigure(o => o.AllowAreas = false)`

**Comment by javiercn** [comment]
We are not planning to change how this works. I chatted at the time with @danroth27 and @DamianEdwards about this and we want an experience in which AddDefaultUI makes everything it can to make ensure that the UI is plugged-in and functional.
