### ISSUE TITLE
TOTP without cookies (using tokens)

### ISSUE THREAD

**Issue by Werner-Swart-83** [aspnet/Identity#1632]
Is it possible to implement TOTP authentication without using cookies?

I am currently using the _signInManager.GetTwoFactorAuthenticationUserAsync() method to get the user from the cookie being sent back from the SPA which is fine. There are however business scenarios where clients do not allow the use of cookies (legal reason or what not).

Would it be possible to generate a PasswordSignIn token instead of a cookie to be used by the TwoFactorAuthenticatorSignIn?

**Comment by blowdart** [comment]
At the minute you can't, we have a long term goal to separate everything. The flow right now is we drop a cookie that says "Hey you've authenticated, but you still need to give me an MFA code". This necessitates cookies, you'd have to implement your own custom flow for this which has a persistence mechanism for this saving of state. If your clients want to disallow cookies, well then you're going to have to roll your own. Even GPDR allows cookies, this isn't a request we've heard of at all before.
