### ISSUE TITLE
The old token is not expire in GenerateChangePhoneNumberTokenAsync method?

### ISSUE THREAD

**Issue by Sathiyamm** [aspnet/Identity#1633]
I'm facing this issue,
GenerateChangePhoneNumberTokenAsync(user, PhoneNumber)-This method is for generate the Confirmation Code
ChangePhoneNumberAsync(user, PhoneNumber, code);-This method is for Confirmation Code

Scenario:
1.Sending Verification Code(First Verification is Code sent to mobile)
2.Again Clicking Resend the Verification Code(Second Code is sent to Mobile)
3.If I give the first verification code its gets accepted...

How to Expire the old code?

**Comment by blowdart** [comment]
TOTP codes are based on time, not on usage. It'll roll over on its own without invalidating. You could write your own provider that implements one shot tokens by implementing [IUserTwoFactorTokenProvider.cs](https://github.com/aspnet/Identity/blob/dev/src/Core/IUserTwoFactorTokenProvider.cs)

**Comment by dnxit** [comment]
It'll be nice if option is there to give the time span as parameter 
just like we have in Email Confirmation Tokens but for PhoneNumberToken its by default 3 minutes I guess ?

so would it be possible to make it a parameter ?

_userManager.UserTokenProvider = _userManager.GetDataProtectionProvider("EmailConfirmationToken", TimeSpan.FromDays(7));
