### ISSUE TITLE
Add third party notice to identity UI package

### ISSUE THREAD

**Issue by javiercn** [aspnet/Identity#1643]

**Comment by Eilon** [comment]
Given that the Identity UI package pretty much just has stuff from our templates, you can use https://github.com/aspnet/templating/blob/dev/src/THIRD-PARTY-NOTICES as a starting point. Please trim out any references to 3rd party libs that aren't there (note: some of these libs are just part of other libs, such as HTML5 Boilerplate being included in Bootstrap). Also, make sure the versions are *exactly* the same, or else we gotta problem.

**Comment by mkArtakMSFT** [comment]
@kichalla can you please look into this, thanks!
