### ISSUE TITLE
Default provided claims in System.IdentityModel is missing new claims from JWT

### ISSUE THREAD

**Issue by brgrz** [aspnet/Identity#1645]
The claims provided in System.IdentityModel.JwtRegisteredClaimNames are only a few of those currently provided by IANA

Here is the current full list for JWT claims:
https://www.iana.org/assignments/jwt/jwt.xhtml

My question is if, when and how are you going to introduce new claims to ASP.NET Core or IdentityModel in general?

**Comment by blowdart** [comment]
This is not ASP.NET, this is System.Identity. You should ask your question at https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet
