### ISSUE TITLE
Difference between Microsoft.Extensions.Identity.Stores and Microsoft.AspNetCore.Identity

### ISSUE THREAD

**Issue by enemyofthedawn** [aspnet/Identity#1646]
On Nuget there are 2 packages that seem identical. What is the difference between them?

https://www.nuget.org/packages/Microsoft.AspNetCore.Identity/
https://www.nuget.org/packages/Microsoft.Extensions.Identity.Stores/

**Comment by HaoK** [comment]
The stores only contain base classes and helper base class implementations of stores that use those pocos.  AspNetCore.Identity is the main package that you would use that brings in SignInManager and the asp.net core specific implementations of identity (without any stores, those come in the EntityFrameworkCore package)
