### ISSUE TITLE
Issue When Configuring Alternate Key for User Role

### ISSUE THREAD

**Issue by scottsauber** [aspnet/Identity#1647]
**Scenario:**
- I have an Admin Role (among others)
- That Admin Role can be assigned to a specific company.  So someone can be an Admin at Company 1,2 and 4, but not 3.

**Problem:**
When I try to add a User with the Roles above, I get this error:

"The instance of entity type 'UserRole' cannot be tracked because another instance with the same key value for {'UserId', 'RoleId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached."

It seems to be complaining that the PK is UserId and RoleId.  But I've already overridden that in my `IEntityTypeConfiguration` below:

```csharp
    public class UserRoleConfig : IEntityTypeConfiguration<UserRole>
    {
        public void Configure(EntityTypeBuilder<UserRole> builder)
        {
            builder.HasKey(r => r.Id);
        }
    }
```

ID is a long I've defined below:
```csharp
    public class UserRole : IdentityUserRole<string>
    {
        public long Id { get; set; }
        public int CompanyId { get; set; }
        public Company Company { get; set; }
    }
```

My `OnModelCreating` looks like below.
```csharp
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.ApplyConfiguration(new UserRoleConfig());
        }
```

What am I doing wrong?  Why isn't EF respecting my ID override?

**Comment by HaoK** [comment]
How is your store/db context configured, what's your AddIdentity full call look like?

**Comment by scottsauber** [comment]
Thanks for the quick response @HaoK.  Here it is.

```csharp
            services.AddIdentity<User, Role>(options =>
            {
                options.Password.RequireDigit = true;
                options.Password.RequiredLength = 8;
                options.Password.RequireNonAlphanumeric = true;
                options.Password.RequireUppercase = true;
                options.Password.RequireLowercase = true;

                options.SignIn.RequireConfirmedEmail = true;

                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(15);
                options.Lockout.MaxFailedAccessAttempts = 5;
                options.Lockout.AllowedForNewUsers = true;

                options.User.RequireUniqueEmail = true;
            })
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();
```

**Comment by HaoK** [comment]
Can you include your ApplicationDbContext?

**Comment by scottsauber** [comment]
```csharp
       public class ApplicationDbContext : IdentityDbContext<User, Role, string, UserClaim, UserRole, UserLogin, RoleClaim, UserToken>
    {
        // Other non-Identity DbSets ommitted

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
            
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);

            optionsBuilder.ConfigureWarnings(warnings => warnings.Throw(RelationalEventId.QueryClientEvaluationWarning));
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.ApplyConfiguration(new RoleConfig());
            builder.ApplyConfiguration(new UserConfig());
            builder.ApplyConfiguration(new UserRoleConfig());
            builder.ApplyConfiguration(new RoleClaimConfig());
            builder.ApplyConfiguration(new UserClaimConfig());
            builder.ApplyConfiguration(new UserLoginConfig());
            builder.ApplyConfiguration(new UserTokenConfig());
            // Other config of other entities here
        }
    }
```

**Comment by HaoK** [comment]
Strange, everything looks reasonable, can you try getting rid of the base configure and just configuring everything explicitly yourself to see if that at least works?

**Comment by scottsauber** [comment]
:( I was hoping it was something dumb I did.

I'm on Central Time so I'm about to head home.  Will try it late tonight or tomorrow morning and will report back.  Thanks for being so responsive!

If the OnConfiguring doesn't work, I can make you a minimal repro if it would help.

**Comment by HaoK** [comment]
Sure a repro never hurts :)

**Comment by scottsauber** [comment]
removing `base.OnConfiguring(optionsBuilder);` did not help.  Will work on a repro.

If I don't inherit from IdentityDbContext and add the config it's adding myself, am I in for a world of hurt in some spot?

**Comment by HaoK** [comment]
There's not too much going on other than defining the db sets in the model, and the on configuring:

https://github.com/aspnet/Identity/blob/dev/src/EF/IdentityUserContext.cs

**Comment by scottsauber** [comment]
Perfect.  I had a once over the code, but just making sure I wasn't missing anything that was looking specifically for something inheriting from IdentityDbContext.  Glad to hear there's not much there.

Repro here: https://github.com/scottsauber/AspNetCoreIdentityUserRoleRepro

Repro steps:
1. Run the app
2. Register a user
3. Go to the root Index page (should redirect on Register) where it will add 2 user roles with diff company Id's, and then it will fail with 
"The instance of entity type 'ApplicationUserRole' cannot be tracked because another instance with the same key value for {'UserId', 'RoleId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values."

**Comment by HaoK** [comment]
So I debugged this, and it looks like the issue is that calling HasKey again doesn't remove the keys added by IdentityDbContext.  So the ApplicationUserRole has 2 keys defined:
the composite userId + roleId, in addition to the new long id property that you added.

@ajcvickers is there a way to remove/replace a primary key in the builder?

// Specifically
```
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
           // results in: .HasKey(r => new { r.UserId, r.RoleId });

            builder.ApplyConfiguration(new ApplicationUserRoleConfiguration());
           // results in: .HasKey(r => r.Id);

           // Resulting in two keys, is there a way to only have the r.Id key.
        }


```

**Comment by scottsauber** [comment]
@HaoK - circling back to this... so when I just stop inheriting from IdentityDbContext and add the EF configuration myself... when PasswordSignInAsync is called I get this:

```
Cannot create a DbSet for 'IdentityUserRole<string>' because this type is not included in the model for the context.
```

It appears that my custom UserRole class is not being respected.... any ideas?

**Comment by scottsauber** [comment]
@HaoK - never mind, I got around this by still inheriting from `IdentityDbContext` but just not calling `base.OnModelCreating`

**Comment by ajcvickers** [comment]
@scottsauber Sorry for being late to the conversation. I suspect this was happening because the original key was still being referenced by an FK. In general, when changing the primary key of an entity type any FKs that reference that primary must also be changed, otherwise the original key is still needed as well.

There is now some better documentation on customizing the Identity model: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1
