### ISSUE TITLE
aspnet/identity issue

### ISSUE THREAD

**Issue by H4Himanshu** [aspnet/Identity#1651]
Hello I am following a tutorial on udemy and instructor was explaining the identity. He added the same in the tutorial and i am getting some error when i am trying to add this. Can someone help me out ? I am attaching all the relevant information i can about my project and error.

Screenshot of error which i am getting in browser.
![image](https://user-images.githubusercontent.com/6859459/36627616-32dc497a-196b-11e8-8262-ab0d6aba4201.png)

Screenshot of my startup.cs file
![image](https://user-images.githubusercontent.com/6859459/36627622-5fd374da-196b-11e8-99c4-bdece26f4443.png)

Screenshot of my Application User File:
![image](https://user-images.githubusercontent.com/6859459/36627628-7c346170-196b-11e8-85f2-77618d8d3751.png)

can anyone help me out if i am missing any file or missing lines of code  ?

**Comment by blowdart** [comment]
Well the error is quite clear. You're attempting to add a role class, but you're not inheriting from IdentityRole, you're inheriting from IdentityUser.
