### ISSUE TITLE
Don't work reference for Microsoft.AspNet.Identity.AspNetCoreCompat

### ISSUE THREAD

**Issue by TDDinAction** [aspnet/Identity#1652]
Don't work reference for open source code of package Microsoft.AspNet.Identity.AspNetCoreCompat: https://github.com/aspnet/Identity/tree/dev/src/Microsoft.AspNet.Identity.AspNetCoreCompat

Please repair it or specefy new path.

**Comment by HaoK** [comment]
https://github.com/aspnet/Identity/tree/dev/src/AspNetCoreCompat

**Comment by TDDinAction** [comment]
Ok, thanks)
