### ISSUE TITLE
Core Identity and the User.Identity.Name problem

### ISSUE THREAD

**Issue by brgrz** [aspnet/Identity#1654]
After spending a couple of hours debugging the issue when the User.Identity.Name property was null (even when all the required claims were present on the ClaimsPrincipal) I discovered the following blog post which I was able to follow and solve the issue.

https://cerkit.com/2017/07/25/asp-net-core-jwt-tokens-and-user-identity-name-property/

Is there a specific reason why this isn't included by default in ASP.NET Core project templates?

Seems really counter intuitive because when working with Identity and Claims you are bound to run into this issue.

**Comment by brockallen** [comment]
A more in-depth look at the issue: https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/

**Comment by blowdart** [comment]
That would be a question for the JWT parser owners ... https://github.com/IdentityModel

**Comment by brgrz** [comment]
@brockallen @blowdart two answers neither of which detailing why this is implemented as it is (wrong, imo) and an immediate closure of this issue. 

Seriously, what part of the issue, which is described in enough detail and probably bugs lots of ppl, don’t the two of you understand?

**Comment by brgrz** [comment]
@blowdart what does identityserver have to do with asp.net core Identity internal code and VS templates?

**Comment by blowdart** [comment]
hah, oops, wrong repo link. My bad :)

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet

I closed it because we, that is, asp.net don't implement this, the AD team does.

**Comment by brgrz** [comment]
Not really, greenfield asp.net core projects, created from templates, could easily and safely include it, you would not break anything. Only save probably hundreds of developer hours monthly worldwide.

**Comment by brgrz** [comment]
Who actually maintains the templates? What repo are they in?

**Comment by blowdart** [comment]
We've been through this before with templates, and it also depends on the JWT token actually containing that claim, but sure, have at it https://github.com/aspnet/templating
