### ISSUE TITLE
Identity UI Scaffolding Code Bug: duplicate "_LoginPartial.cshtml" cause some Anti-forgery token error.

### ISSUE THREAD

**Issue by kapr1k0rn** [aspnet/Identity#1659]
I searched and did not see this bug was mentioned.
Following the instruction in the [2.1 Identity UI](https://blogs.msdn.microsoft.com/webdev/2018/03/02/aspnetcore-2-1-identity-ui/), I added the identity code back to my project, then found this: if I logout from any of the "Manage your account" pages, an anti-forgery token error would happen and caused a 400 status page. It turned out that there were 2 _LoginPartial.cshtml in the project, /Pages/Shared/_LoginPartial.cshtml and /Views/Shared/_LoginPartial.cshtml. Removing /Pages/Shared/_LoginPartial.cshtml fixed the error for me.

**Comment by Eilon** [comment]
@javiercn ?

**Comment by javiercn** [comment]
@prafullbhosale Can you take a look at this? If there's a login partial in ` /Views/Shared/` we should not generate one in `/Pages/Shared/`.
/cc: @danroth27

**Comment by javiercn** [comment]
Closing as this is a scaffolding issue. 

See
https://github.com/aspnet/Scaffolding/issues/714
for details.
