### ISSUE TITLE
Show external providers on the Register page

### ISSUE THREAD

**Issue by Eilon** [aspnet/Identity#1661]
_From @Eilon on October 24, 2017 21:53_

_From @Tratcher on April 8, 2016 22:13_

The individual auth template has a login page and a register page. Login shows a password login and external providers. Register only shows a password login. Register should also show external providers, as this is where new users will go to sign-up.

_Copied from original issue: aspnet/Templates#490_

_Copied from original issue: aspnet/templating#118_

**Comment by HaoK** [comment]
Alternatively you could just add some text that says you can directly login with an existing social provider

**Comment by HaoK** [comment]
This is likely a dupe of https://github.com/aspnet/Identity/issues/1636

**Comment by Eilon** [comment]
Yeah closing as a dup of https://github.com/aspnet/Identity/issues/1636, it looks the same.
