### ISSUE TITLE
AccountController ForgotPassword should check the UserId before ResetPassword

### ISSUE THREAD

**Issue by Eilon** [aspnet/Identity#1663]
_From @Eilon on October 24, 2017 21:36_

_From @HaoK on January 25, 2017 19:32_

Moved from: https://github.com/aspnet/Home/issues/1911#issuecomment-275184195

Today we are passing in the userId from ForgotPassword:  https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Controllers/AccountController.cs#L282

But not using it when we reset: https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Controllers/AccountController.cs#L321

We should check that the User with userId matches the user that is retrieved via FindByEmail as well.

cc @blowdart 

_Copied from original issue: aspnet/Templates#804_

_Copied from original issue: aspnet/templating#96_

**Comment by javiercn** [comment]
Relevant pieces of code
https://github.com/aspnet/Identity/blob/dev/src/UI/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs#L48
https://github.com/aspnet/Identity/blob/dev/src/Core/UserManager.cs#L1708

I do believe this is done. @HaoK @blowdart Can you confirm?

**Comment by blowdart** [comment]
@HaoK  did this get done?

**Comment by javiercn** [comment]
@HaoK PING

**Comment by HaoK** [comment]
Doesn't look like we are checking the user id here, but I think there was another bug that removed passing the user id that we weren't using :)

See it passed in here: https://github.com/dotnet/templating/blob/VS2017.4-Preview1/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Controllers/AccountController.cs#L425

And not here: https://github.com/aspnet/Identity/blob/dev/src/UI/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs#L57

So at this point we should just close this I guess as won't fix?

**Comment by javiercn** [comment]
Yeah. Sounds good to me.
