### ISSUE TITLE
Web App with Individual Auth uses Web Helper instead of TagHelper

### ISSUE THREAD

**Issue by Eilon** [aspnet/Identity#1665]
_From @mlorbetske on September 22, 2017 18:18_

_From @phenning on July 6, 2017 17:26_

In the Individual Auth template for Core Web Application, there is exactly one Web Helper, at line 38 in Views/Accout/Login.cshtml.

This should be changed to a TagHelper.

```
                        <div class="checkbox">
                            <label asp-for="RememberMe">
                                <input asp-for="RememberMe" />
                                @Html.DisplayNameFor(m => m.RememberMe)
                            </label>
                        </div>
```

_Copied from original issue: dotnet/templating#1024_

_Copied from original issue: aspnet/templating#25_

**Comment by Eilon** [comment]
No tag helper currently exists for this. If we add one, we can consider it. Here's the related issue: https://github.com/aspnet/Mvc/issues/6782

**Comment by Eilon** [comment]
The new feature still doesn't exist yet, so this can probably sit in some future milestone.

**Comment by danroth27** [comment]
This is an appropriate use of an HTML helper, so closing.
