### ISSUE TITLE
Support a synchronous API

### ISSUE THREAD

**Issue by marcwittke** [aspnet/Identity#1668]
I know about the benefits of having async methods. But, however, there are always situations, that do not allow using the async/await pattern, often outside your control. My case is an encapsulated business domain that raises an event, that should be handled synchronously by `UserManager`.

I also know there are various techniques to make this happen, however, I spent various days to find a possibility to do so, that does not deadlock in a single cpu environment (cheap azure build agent, cheap azure hosting), not only because it is really hard to reproduce that issue locally. Btw: I ended up with [this answer on SO](https://stackoverflow.com/a/5097066/164162), but to be honest: I am not able to explain, why this is better than `TaskFactory.StartNew(func).Unwrap().GetAwaiter().GetResult()` . It is proven to work by trial and error, what makes me feel not so comfortable.

Is there a specific reason to force the consumer of ASP.Net Identity Core to the async pattern, except "that's how it should be done today. basta."?

**Comment by blowdart** [comment]
It's this way because at it's core (pun intended) ASP.NET Core is async. "That's how it should be done today. Marc" :)

So we have no plans to write sync wrappers.
