### ISSUE TITLE
Support password migration

### ISSUE THREAD

**Issue by slaneyrw** [aspnet/Identity#1670]
I'm investigating a solution to migrating legacy passwords ( SHA256 cyptro provider, not Dbkdf2), MS ID v2, and MS ID v3 passwords to a new algorithm ( specifically Argon2 ) with the requirement to not store the old hash details post migration.

My thoughts are that during migration we...

1. Take existing hash from the old algorithm and rehash the hash using the new algorithm
2. Store the new passwordHash ( with it's metadata ) and the old algorithm's metadata

During password verification we recursively run through the algorithms, taking the hashed output as the input into the next in the chain.  If the password matches then we rehash the password provided using the newest algorithm, akin to increasing the iterations in the MS ID password hasher.

My problem is that I cannot get the resultant hash from the IPasswordHasher instance evaluated during VerifyHashedPassword for use into the next algorithm into the chain, and if I call HashPassword it will give me a different hash for the same password because of the random 16 bytes into Pbkdf2.

I already have a coordinator IPasswordHasher instance that inspects the algorithm byte and forwards the call to the relevant hasher.  It was my intent to have this coordinator loop/recurse through the chain.

Short of completely rebuilding all the Password hashers ( including ASP.NET Identity ) to separate recalculating and compare functions the existing hashers, can you think of another way I could do this?

**Comment by blowdart** [comment]
We have migration in our hashers, where we upgrade from an old hash and rehash the password with the new algorithm. We don't support chaining of hashes like you wish to do.

**Comment by slaneyrw** [comment]
I know... but this leaves the old hash in the system - a requirement we cannot live with.

Like the Async password hashing I have already prototyped this and works without any change to the UserManager or SignInManager.
