### ISSUE TITLE
AggregateException occurs after converting User Id to int in ApplicationUser/ApplicationRole

### ISSUE THREAD

**Issue by MonaLarsen** [aspnet/Identity#1674]
By following this tutorial [Here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-primary-key-configuration?tabs=aspnetcore2x) I got to succesfully convert the User Id to int so i can use Linq with operations done on users in my application.

Everything worked fine here, but after creating default users in startup.cs like this:

```c#
    public async Task CreateUsersAndRoles(IServiceScope serviceScope)
        {
            var userManager = serviceScope.ServiceProvider.GetService<UserManager<ApplicationUser>>();
            var roleManager = serviceScope.ServiceProvider.GetService<RoleManager<IdentityRole>>();

            await roleManager.CreateAsync(new IdentityRole("TopUser"));
            var TopUsers = new ApplicationUser { UserName = "xxxxx@xx.com", 
                                                  Email = "xxx@xxxx.com",  
                                                  };


            await userManager.CreateAsync(adminUser, "xxxxxx");
            await userManager.AddToRoleAsync(TopUsers, "TopUser");

}`
```

i am getting an error in ` CreateUsersAndRoles(serviceScope).Wait();` that is not clear and i don't know why the compiling is failing as eveything seems to be logically working.

Here is the error: `An exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'One or more errors occurred.' Inner exceptions found, see $exception in variables window for more details. Innermost exception System.NullReferenceException : Object reference not set to an instance of an object.`

What am i doing wrong? And how do i find the error that is causing the code to fail?

**Comment by blowdart** [comment]
We more information please, your startup, your configuration and your classes for the user and role.

**Comment by HaoK** [comment]
Feel free to reopen this with more details to repro this
