### ISSUE TITLE
Consider allowing using entities that don't derive from IdentityUser with the default UI

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Identity#1679]
> The decision was made for 2.0 templates to start using the properties on IdentityUser directly instead going thru the user manager for things like user.Id for some of the exception messages. That binds the views to IdentityUser. I did bring this up at the time the change was made so it was intentional, You can ask @DamianEdwards / @danroth27 to consider revisit that decision

So... @DamianEdwards @danroth27 please reconsider this decision :sweat_smile:

**Comment by kichalla** [comment]
Done as part of fixing https://github.com/aspnet/Identity/issues/1690

**Comment by PinpointTownes** [comment]
Great news, thanks!
