### ISSUE TITLE
Allow specifying the default authorization scheme on a controller action without the authorize attribute

### ISSUE THREAD

**Issue by Gengadook** [aspnet/Identity#1682]
This would be useful in the situation where I have some api controllers hosted within an MVC app that already uses a default cookies authorization scheme. In this scenario, the api controllers would use a JWT Bearer token for auth rather than the default cookie scheme used by the rest of the web app.

Normally the way to do this would be to decorate the controller or action with [Authorize(AuthenticationSchemes="Bearer")]. 
However, say I wish to allow anonymous requests to the api action method and return a specific result based on User.Identity.IsAuthenticated as in the example below. 

```
[HttpGet("")]
public IActionResult GetApiAction(){
    if(User.Identity.IsAuthenticated){
        // result for authenticated users
        return Ok(...);
    }else{
        // result for unauthenticated users
        return Ok(...);
    }
} 
```

In this scenario, the authentication scheme cannot be applied to the controller action anymore and it defaults back to cookie auth rather than populating the UserPrincipal when a valid JWT token is supplied in the request.

I feel it would be more flexible to allow the scheme to be added via its own attribute similar to [AuthenticationSchemes(Schemes="...")] rather than being coupled to the [Authorize] attribute directly.

**Comment by javiercn** [comment]
This is more of a question for security than for here, but I would say that you can do two things. Add [AllowAnonymous] and call `HttpContext.AuthenticateAsync(scheme)` within the action method. Then decide what to do.

The second things is that you can use the upcoming authentication policy to achieve this. @HaoK can provide more details

**Comment by blowdart** [comment]
This issue was moved to aspnet/Security#1710
