### ISSUE TITLE
System.Data.SqlClient.SqlException: 'Invalid column name 'ApplicationRoleId'.'

### ISSUE THREAD

**Issue by farhadibehnam** [aspnet/Identity#1683]
I'm working on my project it's based on ASP.net Core 2.0. I've created ApplicationRole and ApplicationUser class. I've wrote a snippet code for making roles when I run my project I've got this error:

    

> System.Data.SqlClient.SqlException: 'Invalid column name 'ApplicationRoleId'.

But the same code that I use in ASP.net Core 1.1 didn't have any problem.

I think it has a problem with this line of code:

    

> lineNumberOfUsers =  r.Users.Count

Because when I comment this code project works fine, but I need count of users for every role.

Controller:

```
public class ApplicationRoleController : Controller
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly RoleManager<ApplicationRole> _roleManager;

    public ApplicationRoleController(UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager)
    {
        _userManager = userManager;
        _roleManager = roleManager;
    }

    public IActionResult Index()
    {    
        List<ApplicationRoleViewModel> models = new List<ApplicationRoleViewModel>();
        models = _roleManager.Roles.Select(r => new ApplicationRoleViewModel
        {

            Id = r.Id,
            Name = r.Name,
            Description = r.Description,
            NumberOfUsers =  r.Users.Count 
        }).ToList();
        return View(models);
    }
}
```

Model

```
public class ApplicationRole : IdentityRole
{
    public string Description { get; set; }
    public virtual ICollection<ApplicationUser> Users { get; } = new List<ApplicationUser>(); 
}
```

I've checked sql query in sql server profiler. when i ran sql query in sql server I got the same error.

   

>  Invalid column name 'ApplicationRoleId'.

```
SELECT [r].[Id], [r].[Name], [r].[Description], (
    SELECT COUNT(*)
    FROM [AspNetUsers] AS [a]
    WHERE [r].[Id] = [a].[ApplicationRoleId]
) AS [NumberOfUsers]
FROM [AspNetRoles] AS [r]
```

**Comment by farhadibehnam** [comment]
My problem is fixed.the navigation property Users in your ApplicationRole class isn't needed.

The relationship between AspNetUsers and AspNetRoles tables is present in a separate table AspNetUserRoles as foreign keys. So, when you want to query the number of users in a given role, you need to interrogate that table AspNetUserRoles. In order to achieve that you can call

`_userManager.GetUsersInRoleAsync("roleName").Result.Count;`

To do that, implement your Index action method like this:

```
public IActionResult Index()
{    
  List<ApplicationRoleViewModel> models = new List<ApplicationRoleViewModel>();
  models = _roleManager.Roles.Select(r => new ApplicationRoleViewModel
        {
            Id = r.Id,
            Name = r.Name,
            Description = r.Description
            // notice I am not assigning NumberOfUsers here.See further down...
        }).ToList();

        foreach(var m in models)
        {
          m.NumberOfUsers = _userManager.GetUsersInRoleAsync(m.Name).Result.Count;
        }
        return View(models);
}
```

Hope this helps.

**Comment by blowdart** [comment]
@ajcvickers Navigation properties again :) Docs?

**Comment by ajcvickers** [comment]
This is now documented here: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1

**Comment by vmass20** [comment]
That link is dead already.

**Comment by vmass20** [comment]
> This is now documented here: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1

Link seems to be dead already.

**Comment by ajcvickers** [comment]
@vmass20 https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.1
