### ISSUE TITLE
Asp identity not working without https

### ISSUE THREAD

**Issue by binhghi5** [aspnet/Identity#1691]
- Open Visual Studio 2017
- Create new ASP Web App (net core 2.0) with Individual User Account (Authentication)
- Run the app with default url (https://localhost:44330)
- Create new user (UserName: user1@gmail.com | Password: Abc@1234) and login ==> success!!
- Stop the app
- Open Properties tab -> Debug -> uncheck "Enable SSL" -> copy text from "App URL" textbox to "Launch browser" textbox
- Run the app again (http://localhost:12421/)
- Login using user1@gmail.com ===> FAIL!! (This page isn’t working HTTP ERROR 400)

Without https, some Asp identity cookies and antiforgerytoken cookies couldn't be created.
And............................ HOW TO FIX IT?????????????????????????????????

**Comment by blowdart** [comment]
What is happening here is cookies are aware of the protocol they are written on. If a cookie is written during an HTTPS request then by default it will limit itself to HTTPS. This is deliberate, once you go HTTPS you really should switch back.

However in dev environments that can be common. You can fix it by clearing the cookies for localhost.

**Comment by blowdart** [comment]
Have you captured a fiddler trace to see if the cookies are actually being set in the response?

**Comment by binhghi5** [comment]
I created new project and disabled SSL in the beginning. Now i'm fine.
