### ISSUE TITLE
Investigate EF warning from tests about 20+ service providers

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#1699]
You'll see these during many of the Identity functional tests

```
More than twenty 'IServiceProvider' instances have been created for internal use by Entity Framework. This is commonly caused by injection of a new singleton servic
e instance into every DbContext instance. For example, calling UseLoggerFactory passing in a new instance each time--see https://go.microsoft.com/fwlink/?linkid=869049 fo
r more details. Consider reviewing calls on 'DbContextOptionsBuilder' that may require new service providers to be built. 
```

cc @ajcvickers

**Comment by HaoK** [comment]
Moving to mq, since this doesn't seem critical for RC1/RTM

**Comment by kieronlanning** [comment]
Yet to find a definitive resolution for this.

**Comment by ajcvickers** [comment]
@kieronlanning This issue is just about the Identity tests. If you are getting the exception in your application then the most common reason is [setting a new LoggerFactory on every context instance](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging).

**Comment by javiercn** [comment]
@ajcvickers This I believe is because of the way we setup the functional tests. I spoke to @bricelam about it and he explained to me how to fix it (although I don't remember the details). I believe it has a relatively easy solution, we'll get to it on MQ as its not critical.

**Comment by ajcvickers** [comment]
@javiercn Yeah, it's a test issue, and not even a really significant one. I'll take care of it in MQ.

**Comment by javiercn** [comment]
Haven't seen this in a long time, so closing.
