### ISSUE TITLE
Need to rehash password if custom PasswordHasher returns PasswordVerificationResult.SuccessRehashNeeded

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#17]
If the user implements a custom PasswordHasher and returns the PasswordVerificationResult.SuccessRehashNeeded in the 'VerifyHashedPassword' method, we need to rehash the password and store it back into the database. 

 This is not implemented currently, for example. in the Find method for usermanager we verify if the verification code is not 'Failed'. If not we return true. We can check if the code is PasswordVerificationResult.SuccessRehashNeeded and rehash the password

**Comment by henninga** [comment]
Will this only be part of the vNext?
