### ISSUE TITLE
TFA Recovery codes discussion

### ISSUE THREAD

**Issue by xrkolovos** [aspnet/Identity#1700]
Hello,

my Version
`<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />`

I created the latest startup project of asp.net core with Identity (local stored account in my sql). I created a new user and went to enable TFA. I got the recovery code and tryied the TFA. Login wokrs fine, but LoginWithRecoveryCode always fail with message "Invalid recovery code entered". 

My recovery code is as i copied it from the webpage.

```
ef3899d4 97bf06ad
b8927df8 6ad00f89
ec5e6e30 17872076
1ac5ca54 c8ec38a6
2fed51c8 c7a063e9
```

I try to past it in 4 ways

```
//1 as i copied it
//2 ef3899d4 97bf06ad b8927df8 6ad00f89 ec5e6e30 17872076 1ac5ca54 c8ec38a6 2fed51c8 c7a063e9
//3 ef3899d497bf06adb8927df86ad00f89ec5e6e30178720761ac5ca54c8ec38a62fed51c8c7a063e9
//4 ef3899d4;97bf06ad;b8927df8;6ad00f89;ec5e6e30;17872076;1ac5ca54;c8ec38a6;2fed51c8;c7a063e9
```
The 4th way is as copied from the database. 

none of this wokrs. 

thank you.

**Comment by xrkolovos** [comment]
I think that 1,2,3 ways should all work

**Comment by brockallen** [comment]
Did you try to just enter one of the codes, instead all of them?

**Comment by brockallen** [comment]
> Encrypt the codes

yes, i opened an issue for that a while ago

**Comment by xrkolovos** [comment]
#836 #1341

**Comment by blowdart** [comment]
What do you think encrypting the codes would give you here? You still need a valid password, they're for use when you don't have your 2fa app.

**Comment by brockallen** [comment]
> What do you think encrypting the codes would give you here? You still need a valid password, they're for use when you don't have your 2fa app.

I always try to protect the identity system with the assumption an attacker has read-only access to the DB. Thus, protecting access tokens, 2FA codes, 2FA reset codes, email confirmation codes, etc. In ASP.NET Identity some of these values are protected by virtue of data protection and not storing them in the DB. But many other values are in the DB... in plain text.

**Comment by xrkolovos** [comment]
Reading the data from the db would give you access to any account with TFA enabled. If the codes are one-way encrypted that adds an extra layer of security.

**Comment by blowdart** [comment]
No it wouldn't allow any access with just the codes. Those recovery codes still need a correct username and password, they're for occasions when you don't have access to your 2fa generator.
