### ISSUE TITLE
Maximum limit of Role Claims

### ISSUE THREAD

**Issue by kodithuwa** [aspnet/Identity#1702]
I have used Role Claims for authorize our system, but, problem is role claim table growing rapidly and sometimes there are more than 200 claims for some roles. and it has given error (HTTP Error 400. The size of the request headers is too long.) when a user going to login the site. HOW CAN I FIX THIS ????

**Comment by blowdart** [comment]
That's a really really big number of roles. So aside from reducing those you could not store them in the cookie, and have your policies go off to your role store instead when authorization happens., Would that work for you?

**Comment by brockallen** [comment]
> HOW CAN I FIX THIS

Perhaps with a separation of concerns: http://policyserver.io/. Consider the identity system separate from the authorization system. The video in the link above elaborates on this design.

**Comment by blowdart** [comment]
Closing as the only answers that work are given. Please reopen if you need further help.
