### ISSUE TITLE
Add an option in Identity System, so we can define the length of TFA Recovery codes

### ISSUE THREAD

**Issue by xrkolovos** [aspnet/Identity#1708]
As, i see in method [TwoFactorRecoveryCodeSignInAsync](https://github.com/aspnet/Identity/blob/c6a82ad19a0bdb80b7358dc843b66664bbf33f96/src/Identity/SignInManager.cs), they don't protect against brute force attacks.
8 char long strings are venerable to brute force attacks.

Add an option in Identity System, so we can define the length of TFA Recovery codes, and i thing you should raise the number. Normally the recovery codes are larger strings.

That's issue comes from discussion #1700

**Comment by HaoK** [comment]
You should just add a derived UserManager that generates the TFA codes how you like by overriding this method:

https://github.com/aspnet/Identity/blob/c6a82ad19a0bdb80b7358dc843b66664bbf33f96/src/Core/UserManager.cs#L2199

**Comment by xrkolovos** [comment]
You don't think this should be configurable?

**Comment by HaoK** [comment]
@blowdart ?  In general we haven't make these things configurable historically, only via extensibility,

**Comment by blowdart** [comment]
Looking at my recovery codes, Dropbox, Facebook, Instagram, Gmail, Slack and Wordpress are all 8 characters, so I'd dispute the "larger strings" assertions, excluding Github which is 10. So yea, I think this would be a really low priority.
