### ISSUE TITLE
Online Source Code for Identity V2

### ISSUE THREAD

**Issue by trailmax** [aspnet/Identity#1709]
Hello Team!

I have noticed that CodePlex is in archive mode now and source code is  no longer available to browse online (though you can download the whole archive).

What would be good is to have source code of v2 available online, so it can be referenced online. I'm mostly interested in ability to point people to a specific file or line of code in answers on StackOverflow.

Do you think it would be possible to set up a read-only version of source code for Identity V2 on GitHub? In a rush of a moment I've created my own repo with your source code, but after a bit of thinking deleted it later - you guys might not like some random dude setting up a repo with your code (older version or not).
I think it would be more appropriate if older version code is living in AspNet organisation. However if you don't want to maintain yet another repository, I'm willing to take care of that repository (I'd imagine people would create issues).

What do you think?

**Comment by HaoK** [comment]
Yup, its here: https://github.com/aspnet/AspNetIdentity

**Comment by trailmax** [comment]
So it is. How did I miss it?? total "duh!" on my part!

**Comment by HaoK** [comment]
The name isn't exactly super obvious :)

**Comment by trailmax** [comment]
Maybe that link should be on Codeplex page (can you still update the landing page?) and on readme in this repo, clearly stating that it is for MVC5 only?

**Comment by blowdart** [comment]
Done
