### ISSUE TITLE
Authorization Points (i.e. authorization on at-the-point-of-authorization basis) as an improvement on current methodologies

### ISSUE THREAD

**Issue by olugt** [aspnet/Identity#1710]
I have a proposal for the Identity team to include a feature, especially as an optional feature and upgrade, that would enable authorizing based on at-the-point-of-authorization basis, for example...

`[Authorize(AuthorizationPointId = "UniqueIdOfThisAuthorizationPoint")]//The value of the unique authorization point ID could be a GUID string or something familiar and human-readable, as chosen by the developer.`
`public ActionResult EditBlogPost()`
`{`
`    ...`
`}`

...instead of just based on hard-coding the names of roles, etc., as it's being currently done, for example...

`[Authorize(Roles = "Admin")]`
`public ActionResult EditBlogPost()`
`{`
`    ...`
`}`

The currently used method, i.e. based on hard-coding names of roles, etc., is not scalable and quite a bad practice, because when role names happen to get changed in the lifetime of the solution, it can become hard to reflect the changes in code.

Now, with this request or solution I am proposing, authorization point IDs should be used as an optional feature. Every identity entity (i.e. roles, claims, users, etc.) that should be able to access code or resource being guarded must be enrolled in the said authorization point. This enrollment can be eased if the Identity team can provide a Visual Studio integration or solution for that (similar to how web pages are already prepared to register users, etc.), because, for example, if a developer decides to use GUID strings as their authorization IDs, it can be hard to bear in mind the roles and users that can have access through said authorization IDs. But if there can be a Visual Studio integration such that, for example, on mouse hovering over the Authorize attribute, enlisted roles and users can pop up in some way similar to how IntelliSense does it.

I have used this methodology in my own private coding and it works very fine. I didn't implement mine using the Authorize attribute though. Anybody who have been faced with the inflexibility of Identity in the area of renaming roles and some other tasks that could make things flexible, can testify to how Identity can quickly become unhelpful beyond mere authorization.

I plead with the Identity team to REALLY consider this and make it a feature in Identity.

**Comment by olugt** [comment]
@pranavkm @HaoK Please, this is worth your attention, unless I'm not knowledgeable enough about if Identity already has a scalable and viable solution to this.

**Comment by olugt** [comment]
The great part of this proposal is that authentication point IDs scale with the solution since they don't have to be changed, only the roles and users associated with it have to be re-enlisted.

**Comment by PinpointTownes** [comment]
It's already supported and known as policy-based authorization: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies.

**Comment by olugt** [comment]
@PinpointTownes Thank you.

Policy-based authentication does not entirely tackle all of what I'm asking for. How about having to hard-code role names? And besides, what I am asking for qualifies as an entirely new feature if critically looked at.@PinpointTownes Thank you.

Policy-based authentication does not entirely tackle all of what I'm asking for. How about having to hard-code role names? And besides, what I am asking for qualifies as an entirely new feature if critically looked at.

**Comment by olugt** [comment]
@PinpointTownes Thank you.

Policy-based authentication does not entirely tackle all of what I'm asking for. How about having to hard-code role names? And besides, what I am asking for qualifies as an entirely new feature if critically looked at.@PinpointTownes Thank you.

Policy-based authentication does not entirely tackle all of what I'm asking for. How about having to hard-code role names? And besides, what I am asking for qualifies as an entirely new feature if critically looked at.

**Comment by olugt** [comment]
@PinpointTownes Thank you.

Policy-based authentication does not entirely tackle all of what I'm asking for. How about having to hard-code role names? And besides, what I am asking for qualifies as an entirely new feature if critically looked at.

**Comment by blowdart** [comment]
I'm with @PinpointTownes on this, you can do this with policies as of now, you're just replacing a policy name with another type of ID. Policies mean you don't hard code role names.

Roles based authorization via attributes is there for backwards compatibility.

**Comment by olugt** [comment]
@blowdart Thanks.

But when you create policies, somewhere along the way you hard-code role names. And that's still a problem.

For now, what I personally do is, in a database, I assign a GUID as ID to every role name, so that when I change role names their reference will still be maintained. Then, I enlist the IDs of roles under IDs of Authentication Points, which I then use instead of policies. I don't get to use the full capacity of Identity in for real, mainly because of having to hard-code role names, even though hard-coding policy names isn't a problem. This seems like a crude approach (or not) but it works and is extremely powerful.

So, because this approach can actually be tiresome, it will be great if other people and/or the Identity can just take a closer look at it and implement it or something more refined. Having to hard-code role names is enough reason for a change, even though Identity seemingly provides a way to rename roles, but which does not still prevent hard-coding of role names.

**Comment by blowdart** [comment]
No you don't. You can quite happily get the current roles from a database. 

You're hung up on roles. You don't have to use roles at all, we'd rather you didn't, we'd rather you look at claims, something the user is, and then turn those into permissions within the policy handler, which is basically what you want for your hard coded guid, you can do that *now* if you want to write the code.

**Comment by olugt** [comment]
@blowdart Thanks, again.

Actually, I now get it more clearly that claims and policies solve the problem if used cleverly. They make the problem of hard-coding gone too. In the documentation, there should have been more on claims and policies, but there's very little. Roles can essentially be done away with because claims can actually replace the use of roles, as you rightly said. This should also be emphasized in the documentation.

**Comment by olugt** [comment]
@blowdart 

Although most claim values are essentially permanent and don't need to change, e.g. setting an age limit, etc. But I am still concerned about having to hard-code something that should be changeable as claim values.

I'm not yet satisfied but I can/would improvise on top of what claims and policies now provide.

**Comment by blowdart** [comment]
You don't have to hard code anything at all. What comparisons you do inside a policy could come from XML, SQL, MongoDB, JSON, whatever, you just need to provide the parsing code. In fact we have people building products on that flexibility, https://policyserver.io/ is one such product.

**Comment by blowdart** [comment]
Closing as this isn’t something we’d want to persue

**Comment by olugt** [comment]
OK. Great. That's pretty much what's to be done, getting data from other sources.
