### ISSUE TITLE
Improve cookie invalidation scenario (UpdateSecurityStamp/claims/role updates)

### ISSUE THREAD

**Issue by rustd** [aspnet/Identity#172]
When you change claims or roles for the user, we should update the security stamp of the user so the current cookie will be invalid.

Here is the user scenario ported from https://aspnetidentity.codeplex.com/workitem/2275
Usage scenario: upon collecting several pieces of information from a logged-in user within that user's session, our application assigns a role ("VIP") to the user (the role exists in the AspNetRoles table). Immediately after that we redirect the user to a controller action that is guarded by the [Authorize(Roles = "VIP")] attribute, which doesn't succeed and, instead, the user is sent to Account/Login. If the user logs out and logs back in the assigned role works as expected.

Expected result: if a role is assigned to a given user within the user's session it should become available for authorization after the UserManager.AddToRoleAsync() call (or at least upon a single redirect to another action).

**Comment by HaoK** [comment]
@blowdart This is basically the same issue as the runtime role assignment issue we resolved as won't fix I think isn't it?  I think the behavior today is fine, you can update an user's roles in one request, but its not going to be valid until the next request with the updated cookie/identity

**Comment by blowdart** [comment]
Yea, this is how it's always been. I see no burning need to change it.
