### ISSUE TITLE
Cookie is broken when there are too many permission for a user. 

### ISSUE THREAD

**Issue by maxwang** [aspnet/Identity#1739]
Dear Sir/Madam,

We use Asp.Net Identity framework as our ACL and wrote some custom code to fit our requirement.  The framework works fine. We use Claims-based authorisation. 

We found a very strange issue today. There is a user who belongs many roles which have lots of permission claims. And this use keep getting:

 "HTTP Error 400. The size of the request headers is too long." error. 

And I checked and found there are some ASP.Net core identity cookies as attached image:

![img_04042018_090514_0](https://user-images.githubusercontent.com/716782/38407080-6edc3942-39bb-11e8-819f-f43c2bb9272a.png)

I manually removed cookie and that user could work for a while. And I also found this only happens after second AJAX call (not cross domain AJAX call).

After I remove this user from some roles and only keep one or two roles for him, everything works perfectly.

My development environment is .Net Core 1.1. 

Does anyone have some idea on this issue?

Thanks.

Regards,
Max

**Comment by Niels-V** [comment]
There are limits to the size of your request headers. Both IIS as Kestrel have options to configure these limits. So you have the option to increase this limit.

**Comment by maxwang** [comment]
Hi Niels,

Thanks for your information. I have changed IIS request limit size but does not work. I will check Kestrel options.

Thanks again.

**Comment by Niels-V** [comment]
There might also be restriction by http.sys. Check these SO posts:
https://stackoverflow.com/questions/35749180/do-web-config-header-size-limits-override-http-sys-limits-in-the-registry
 
https://stackoverflow.com/questions/37112367/size-of-the-request-headers-is-too-long
 
 
But for another, more robust, solution you can also look into implementing a SessionStore. It is a settable property on the CookieAuthenticationOptions, designed for these kind of issues. The complete set of claims for the user are stored in the specified session store, and only a session identifier is stored in the cookie, greatly decreasing the site of the cookie.

**Comment by maxwang** [comment]
Hi Niels,

Thanks for help. It seemed that this is IIS issue. It works after I modified registry entry for MaxFieldLength,MaxRequestBytes. 

It is very strange that modified httpRuntime maxRequestLength with IIS Configuration Editor does not work. But this is not Asp.net Identity problem.

Thanks again.

Regards,
Max

**Comment by blowdart** [comment]
How many claims do you have? If you're seeing a cookie of that size your user claims must be *huge* Do you really need that many? Are you treating claims as permissions perhaps?

The server and even the browser itself will set limits on header sizes and lengths. As @Niels-V suggests you could move to using a session store; there's a sample in https://github.com/aspnet/Security/tree/dev/samples/CookieSessionSample

**Comment by blowdart** [comment]
As you're unblocked I'm closing the issue.
