### ISSUE TITLE
RoleManager.CreateAsync throw an Exception when role with the same name already exists.

### ISSUE THREAD

**Issue by ivanstamenic** [aspnet/Identity#1740]
When role with the same name already exists _RoleManager.CreateAsync_ throw an Exception "Object reference not set to an instance of an object.".

**Comment by HaoK** [comment]
I don't see this behavior, we also have a unit test covering this, so this is most likely something specific to your app/code, if you provider a repro I can take a look

https://github.com/aspnet/Identity/blob/dev/src/Specification.Tests/IdentitySpecificationTestBase.cs#L385
