### ISSUE TITLE
IUserStore.GetNormalizedUserNameAsync / IUserEmailStore.GetNormalizedEmailAsync not used anywhere

### ISSUE THREAD

**Issue by zhulien-ivanov** [aspnet/Identity#1741]
So, basically the required to implement methods:  **IUserStore.GetNormalizedUserNameAsync** and **IUserEmailStore.GetNormalizedEmailAsync** aren't used anywhere in the source code(UserManager, SignInManager, etc...). What's the purpose of having them required by the interface? Am I missing something?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
