### ISSUE TITLE
loop to change user

### ISSUE THREAD

**Issue by nm-1216** [aspnet/Identity#1746]
foreach (var item in list)
            {
                var model = new {headimgurl = "", nickname = ""};
                item.WxAvatar = model.headimgurl;
                item.WxName = model.nickname;
                await userManager.UpdateAsync(item);
            }

System.InvalidOperationException: Invalid operation. The connection is closed.

**Comment by blowdart** [comment]
OK, guessing here, but you're trying to update a user in asp.net identity?

This will only work when you retrieve an instance of the user from the user manager, update the fields on the user class you got back, then pass that to update. Without doing that there's no way to even lookup your user, this type of anonymous type simply will not work.

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
