### ISSUE TITLE
ASP.NET Identity Core 2.0: Custom usermanager causing problems with security stamp?

### ISSUE THREAD

**Issue by benrhere** [aspnet/Identity#1757]
Hi,

I'm generating custom claims with the following method:

        protected override async Task<ClaimsIdentity> GenerateClaimsAsync(TUser user)
        {
            var id = await base.GenerateClaimsAsync(user);
            var myOrgs = user.OrganizationMemberships;
            var myAdminOrgs = myOrgs?.Where(om => om.Role == Data.Enums.OrganizationMembershipRole.Admin || om.Role == Data.Enums.OrganizationMembershipRole.SecondaryAdmin).Select(org=>org.Id).ToList();
            var myPlayerOrgs = myOrgs?.Where(om => om.Role == Data.Enums.OrganizationMembershipRole.Athlete || om.Role == Data.Enums.OrganizationMembershipRole.Admin || om.Role == Data.Enums.OrganizationMembershipRole.SecondaryAdmin).Select(org=>org.Id).ToList();
            if (myAdminOrgs!= null && myAdminOrgs.Count > 0)
            {
                var adminOrgStrings = String.Join(",", myAdminOrgs);
                id.AddClaim(new Claim(MyDotNetCoreAppClaimTypes.MyDotNetCoreAppOrgAdmin, adminOrgStrings));
            }
            if (myPlayerOrgs != null && myPlayerOrgs.Count > 0)
            {
                var playerOrgStrings = String.Join(",", myPlayerOrgs);
                id.AddClaim(new Claim(MyDotNetCoreAppClaimTypes.MyDotNetCoreAppOrgMember, playerOrgStrings));
            }
            return id;
        }

The important thing to note is that I'm referencing a table related to the users table, so I need to explicitly load it. To achieve that, I've created a custom UserManager which pulls the additional needed data:

public class MyDotNetCoreAppUserManager : UserManager<MyDotNetCoreAppUser>
    {

        public MyDotNetCoreAppUserManager(IUserStore<MyDotNetCoreAppUser> store, IOptions<IdentityOptions> optionsAccessor,
        IPasswordHasher<MyDotNetCoreAppUser> passwordHasher, IEnumerable<IUserValidator<MyDotNetCoreAppUser>> userValidators,
        IEnumerable<IPasswordValidator<MyDotNetCoreAppUser>> passwordValidators, ILookupNormalizer keyNormalizer,
        IdentityErrorDescriber errors, IServiceProvider services, ILogger<UserManager<MyDotNetCoreAppUser>> logger)
        : base(store,optionsAccessor,passwordHasher,userValidators,passwordValidators,keyNormalizer,errors,services,logger)
        {
        }

        /// <summary>
        /// Gets all users
        /// </summary>
        /// <param name="includes">Optional parameter for eager loading related entities</param>
        /// <returns>An list of users</returns>
        public async Task<MyDotNetCoreAppUser> GetAll(string userName, params string[] includes)
        {

            // Get our User DbSet
            var users = base.Users.Where(u=>u.UserName == userName);

            // For each include, include in the query
            foreach (var include in includes)
                users = users.Include(include);

            // Return our result
            return await users.FirstOrDefaultAsync();
        }

        //This is called on initial login and is necessary to pull additional related user data
        //used in claim generation. But overriding this causes sescurity stamp validation to fail!
        public override Task<MyDotNetCoreAppUser> FindByNameAsync(string userName)
        {
            var fetchTask = GetAll(userName, "OrganizationMemberships");
            return fetchTask;
        }

        //When it's time to validate the security stamp, a call is made into here for some reason.
        //If I comment this override out, it successfully regenerates claims, and
        //regenerates a login cookie (and I stay logged in)
        //but the claims generation misses the needed related data.
        //But if I enable this override, it just logs the user out after calling into here. (Doesn't
        //fire GenerateClaimsAsync)
        public override Task<MyDotNetCoreAppUser> FindByIdAsync(string userId)
        {
            return GetAll(userId, "OrganizationMemberships");
        }
    }

But please see above comments in this code. The problem is that after 30 minutes, when it's time to revalidate the security stamp and the user refreshes, one of two things happens:

-If I do NOT override FindByIdAsync, it somewhat works, meaning the user stays logged in and claims are generated - however, the user object passed ot GenerateClaimsAsync does NOT contain the required OrganizationMemberships property populated.
-If I DO override FindByIdAsync, I hit that breakpoint when I refresh the page after the security stamp timeout expires. However, after I continue, I don't hit the ClaimsGeneration method. Instead, I'm logged out and redirected to the login page.

Also maybe relevant:

           services.AddIdentity<MyDotNetCoreAppUser, MyDotNetCoreAppRole>(opt =>
            {
                opt.Password.RequireNonAlphanumeric = false;
                opt.Password.RequireUppercase = false;
            })
                .AddEntityFrameworkStores<MyDotNetCoreAppDbContext>()
                .AddUserManager<MyDotNetCoreAppUserManager>()
                .AddSignInManager<MyDotNetCoreAppSignInManager>()
                .AddDefaultTokenProviders();

            services.AddAuthorization(opt =>
            {
                opt.AddPolicy("OrgAdmin", policy => policy.RequireClaim(MyDotNetCoreAppClaimTypes.MyDotNetCoreAppOrgAdmin));
                opt.AddPolicy("OrgMember", policy => policy.RequireClaim(MyDotNetCoreAppClaimTypes.MyDotNetCoreAppOrgMember));
            });
            services.Configure<SecurityStampValidatorOptions>(options =>
            {
                // enables immediate logout, after updating the user's stat.
                options.ValidationInterval = TimeSpan.FromSeconds(6);
            });

(I set the validation interval to 6 seconds to be able to debug the security stamp validation more easily.)

Appreciative of any thoughts on this. Thanks...

**Comment by blowdart** [comment]
@HaoK

**Comment by benrhere** [comment]
Working as expected; I found the problem on my end. Sorry for the trouble.
