### ISSUE TITLE
Enable users to extend result returned by SigninManager for SigninStatus

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#176]
For sign in, the SigninManager returns SigninStatus which is an enum. It is not convenient when extending the SigninManager and returning custom status since enum is not inheritable.

Can we rethink on how we can make this more extensible ?

Ref: https://aspnetidentity.codeplex.com/workitem/2262

**Comment by wbreza** [comment]
Is this still happening?  I don't see this pull request merged into the v2.2.1 identity assemblies.
