### ISSUE TITLE
External login provider and confirm email page are not accessible when using global authorize filter

### ISSUE THREAD

**Issue by jbagga** [aspnet/Identity#1762]
When an external login provider is configured, and a global authorize filter is applied, clicking the button to navigate to the provider (say Twitter sign in) redirects back to the current Login page.

To allow anonymous users to log in to an external provider while using a global authorize filter, the user can scaffold the `ExternalLogin.cshtml.cs` page and add the `AllowAnonymous` attribute to the `ExternalLoginModel`.

Please note, if this is something we want to allow by default, a corresponding change must also be made in aspnet/Scaffolding repo.

**Comment by blowdart** [comment]
This should be allowed by default, otherwise you can't login. Can you create the corresponding bug please?

**Comment by blowdart** [comment]
Never mind, I'm told I can move it :D

**Comment by blowdart** [comment]
This issue was moved to aspnet/Scaffolding#769

**Comment by blowdart** [comment]
@mkArtakMSFT it'd be good to get this fixed, it's an unexpected side effect, most people who want to add global authentication would still expect logins to work, otherwise what's the point?

**Comment by mkArtakMSFT** [comment]
@jbagga, can you please prepare a PR for this? Thanks!

**Comment by jbagga** [comment]
While using the global authorization filter, `ConfirmEmail` is not accessible when clicking the verification email link (when logged out). So adding the attribute to it as well.

**Comment by jbagga** [comment]
@mkArtakMSFT PR #1769 addresses the issue
