### ISSUE TITLE
Wrong file name _Layout.chstml after scafolding Identity

### ISSUE THREAD

**Issue by HSchwichtenberg** [aspnet/Identity#1767]
Visual Studio 2017 15.7 Preview 4, .NET Core SDK 2.1.300-preview2-008533

New Project
ASP.NET Core Web Application
WebApplication with indvidual Accounts
New Scaffolded Item
Identity
Check only "Account/Login"
There is a typo now in Areas/Identity/Pages/_ViewStart.cshtml

@{
    Layout = "/Pages/Shared/_Layout.**chstml**";
}

**Should be:**

@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}

**Comment by javiercn** [comment]
This belongs to the scaffolding repo. Adding @seancpeters to confirm as he's the owner. I believe this is fixed post preview2. Thanks for bringing it up.
