### ISSUE TITLE
2fa recovery code is not working (invalid)

### ISSUE THREAD

**Issue by melvillo** [aspnet/Identity#1770]
Hi,
Seems there is an issue with 2fa recovery code as it's not working.
1. Create a new ASP.NET Core Web project with built-in authentication, and deploy the db as default schema
2. Create a new user, and enable it's 2fa by using Microsoft Authentication app or Google's, copy the 2fa recovery code
3. Log out, and re-Log in, but use the 2fa recovery code to reset the 2fa settings, then you can get the error message

netcoreapp2.0
Microsoft.AspNetCore.All            Version="2.0.6" 
Microsoft.EntityFrameworkCore.Tools          Version="2.0.2"

**Comment by unruledboy** [comment]
Same problem, I reckon it is a logic problem with RedeemCodeAsync.

**Comment by blowdart** [comment]
Here's what I tried to do to reproduce this. 

1. Created a new ASP.NET Core 2.0 web application (so using Razor) with individual accounts in-app. '
2. Ran the app
3. Created the database via the apply migrations web page that pops up
4. Created a new user
5. Turned on 2fa
6. Saved recovery codes
7. Logged out
8. Logged in again
9. Redeemed code

Now ... is this a UI problem? In each line there are TWO recovery codes;

For example, here's what my app generated

```
e1eb3889 a8a62fce
7735bfe3 2643f20e
e22c9ae7 1a042ddc
b98f90f8 c8b6ab47
99380395 47684d0d
```

The first recovery code is e1eb3889. Are you perhaps entering both codes from the first line?

**Comment by melvillo** [comment]
OK. Then, that's interesting. Actually looks like I don't need to copy and store all of these recovery codes, but just any one of them. And when recovery I just need to use any one, not all.
Hmm, if the UI can tell it more clear, that would be better.
Thanks.
