### ISSUE TITLE
I feel tied up there is a class with wrong entity column names by intentional pattern

### ISSUE THREAD

**Issue by renatoprogramer** [aspnet/Identity#1775]
I would like you to be able to customize my user ID class

Can not do this

    public class User
    {
        [Key]
        public long id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        [EmailAddress]
        public string email { get; set; }
        public string password { get; set; }
        public string tel { get; set; }
        public string cel { get; set; }
        public DateTime created { get; set; }

    }

            services.AddIdentity<User, IdentityRole>()
                .AddEntityFrameworkStores<EntityContext>()
                .AddDefaultTokenProviders();

Could an interface of identityUser to complement and use names as we do not like the names of the columns identityUser

**Comment by blowdart** [comment]
Not really, no. To be honest the database is just an object store for us, its somewhere data gets serialized. You could implement your own store and your own mappings, but this isn't something we feel is needed.
