### ISSUE TITLE
Identity core in ASP.NET MVC 6

### ISSUE THREAD

**Issue by Ruud-cb** [aspnet/Identity#1784]
I am trying to port a class library to .NET Standard, this library includes all repositories, entities and my DbContext. This will be used by both .NET Core applications and .NET Framework applications. 
The library itself is done and EF code-first migrations can be created successfully. Now I am trying to use the AspNetCore.Identity.EntityFrameworkCore inside my ASP.NET MVC Framework application.

Any guidance or documentation on using the .net core Identity within an existing .net framework asp.net project? Without converting the asp.net mvc project to a .net core project?  I don't want to convert it because too many other libraries are now not able to and simply this takes to much time.

Full issue described here with more details:
https://stackoverflow.com/q/50236246/2901207

**Comment by HaoK** [comment]
I don't think you will be able to easily (if at all) use IdentityCore without asp.net core, have you tried using the old precore Identity 2.2.x instead?  That likely would be a better fit, you probably would still be able to use EFCore with old identity by plugging in a custom identity store that was implemented using EFCore.

**Comment by Ruud-cb** [comment]
Hi Haok,
you refer to these?:
https://www.nuget.org/packages/Microsoft.AspNet.Identity.Owin/
and https://www.nuget.org/packages/Microsoft.AspNet.Identity.EntityFramework/
I must admit I didn't update them to the latest version but what do you suggest exactly?

Everything within the .NET Standard library is now using the AspNetCore.Identity.xx things, how would a custom identity store look like that uses the new Identity objects (IdentityUser, UserManager, UserStore, IdentityDbContext)?

**Comment by HaoK** [comment]
My point mostly is that old MVC needs to work against old Identity/OWIN/Auth, Identity Core is designed to work against new auth/Asp.NET Core.

**Comment by HaoK** [comment]
EF is the only framework out of these 3 that you can mix into either MVC/Identity combination

**Comment by Ruud-cb** [comment]
Ok thanks for clarifying this, saves some time trying to use the new Identity stuff in .NET Framework. I would need to, like you said, write some custom 'conversion' so that for example the old UserManager is using the new UserManager. Do you perhaps have some guidance on doing this? Since in .NET Core I think it is not really recommended to create your own UserManager due  the high amount of additional objects that need to be created.

**Comment by HaoK** [comment]
Not quite, so what I'm saying is you don't mix.  If you are using old precore MVC, you need to use the old precore Identity 2.x, you can't use the new core identity objects at all unless you use ASP.Net core

**Comment by Ruud-cb** [comment]
Yea I eventually managed to solve it by having 1 DB context specifically for the authentication and the rest all in EFCore, then creating interfaces for IApplicationUser to facilitate the UserManager's, I will some day update my stackoverflow with an answer for new readers. Thanks for the help anyway.
