### ISSUE TITLE
Microsoft.AspNetCore.Identity.UI.csproj failed to load

### ISSUE THREAD

**Issue by Yeeler** [aspnet/Identity#1786]
git clone code, then load it in VS 2017 ver 15.7.1 
Microsoft.AspNetCore.Identity.UI.csproj load failed.

![image](https://user-images.githubusercontent.com/5031611/39835715-a0f6e776-5403-11e8-857d-17086584219f.png)

**Comment by blowdart** [comment]
@javiercn ?

**Comment by blowdart** [comment]
Did you try running the build.cmd file first, rather than using VS?

**Comment by javiercn** [comment]
Yes. Also %userprofile%/.dotnet/x64 needs to be on the path when you launch Visual Studio for it to pick up the right dotnet to use.

**Comment by Yeeler** [comment]
Thanks guys. I missed that path. After I add it and run build.cmd, I can compile the code without errors.
Is there a document can walk me through how to use it? Which project should I use to generate database? I am new to .Net core. Thanks for the help.

**Comment by Yeeler** [comment]
I have set default project to 'sample\IdentitySample.DefualtUI in Package Manager Console, and run 'update-database'. 
I got an error 'The EntityFramework package is not installed on project 'Identity.DefaultUI.WebSite'.'
I checked its dependency which has 'Microsoft.EntityFrameworkCore.Tools;.
Why I cannot run 'Update-Database'?

**Comment by javiercn** [comment]
Can you run add migration and then update database? Also try from the command-line “dotnet ef database update” on the project folder.

**Comment by Yeeler** [comment]
D:\_GIT\Identity\samples\IdentitySample.DefaultUI>dotnet ef database update
No executable found matching command "dotnet-ef"

PM> Add-Migration ddd
The EntityFramework package is not installed on project 'IdentitySample.DefaultUI'.

I am really confused. Normally, I do update-database in EF6.

**Comment by Yeeler** [comment]
This is my dotnet, not sure if I have the right version
![image](https://user-images.githubusercontent.com/5031611/39932624-3c8b194e-5573-11e8-8a30-b059c4f4c681.png)

**Comment by javiercn** [comment]
is that after running build.cmd?
You should do dotnet --info which will give you the exact information.

**Comment by Yeeler** [comment]
![image](https://user-images.githubusercontent.com/5031611/39951698-e2301dea-55be-11e8-8abe-1c6504b5340e.png)
 
why can't I use ' dotnet ef database update'?

**Comment by javiercn** [comment]
You are on an older version of dotnet. You need to run build.cmd and use the version on %userprofile%/.dotnet/x64

**Comment by Yeeler** [comment]
thanks for the help @javiercn 
I found the following url. It helped, just like you said I should replace the default .net core with whatever in %userprofile%/.dotnet/x64.  I can start the sample now.

https://github.com/aspnet/Home/wiki/Building-from-source#path

**Comment by javiercn** [comment]
Closing this as there's no further action required.
