### ISSUE TITLE
Guidance on new 2.1 stuff

### ISSUE THREAD

**Issue by natelaff** [aspnet/Identity#1789]
Can we get guidance on adding user properties, renaming Identity tables and changing key types with all of these changes for 2.1 (i.e. #1690, #1679)

It seems like this was made easier, right? Can we see how it all comes together now?

Thanks!

**Comment by blowdart** [comment]
@ajcvickers This is your bailiwick

**Comment by ajcvickers** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1
