### ISSUE TITLE
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware An unhandled exception has occurred: Failed to retrieve Facebook user information (BadRequest) Please check if the authentication information is correct and the corresponding Facebook Graph API is enabled.

### ISSUE THREAD

**Issue by eriksendc** [aspnet/Identity#1790]
Hi All,

Starting May 1st at approximately 1:33pm Eastern US time we started seeing the following error reported in  our logs:

`Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware An unhandled exception has occurred: Failed to retrieve Facebook user information (BadRequest) Please check if the authentication information is correct and the corresponding Facebook Graph API is enabled.`

We made no code changes at that time. This just started happening out of the blue. We know this is affecting users because we've had at least 10 requests for help per day from our users since the 1st. It's becoming a real user experience issue. Any clues?

We're on 2.0.1 in general, and specifically for Microsoft.AspNetCore.Authentication.Facebook.

Thanks in advance!

-Brian Eriksen

**Comment by Tratcher** [comment]
Stack trace?

**Comment by Tratcher** [comment]
No repro, 2.0.1 works fine locally. 

Note 2.0.1 uses v2.6 of Facebook's API which will expire on July 13th. This shouldn't be a problem as it will gracefully roll forward to 2.7.
https://developers.facebook.com/docs/graph-api/changelog

**Comment by eriksendc** [comment]
Hi @Tratcher . The latest round of these errors stopped occurring early in the morning of 15 May. We can't reproduce. Definitely works fine for us locally, too. I was assuming that it wasn't a problem with the code per se but thought someone might recognize the error and know how to contact Facebook to have them fix whatever's going on. Anyways, I'm happy to close this given that there's nothing to be done code-wise. -Brian
