### ISSUE TITLE
Primary Key in RoleClaim & UserClaim provider dependent

### ISSUE THREAD

**Issue by tidyui** [aspnet/Identity#1793]
This probably belongs in the EntityFrameworkCore repo, but I haven't bumped into it before using Identity. The migration generated for `RoleClaim` and `UserClaim` is provider dependent on the provider that was used when generating the migration.

For example the primary keys are generated with `Annotation(Sqlite:Autoincrement, true)` when using SQLite, and `Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)` when creating the migration with SqlServer.

While this probably works when generating a migration for a single application it totally breaks when using it in a reusable library that is not supposed to be database dependent because the migration only works on the same type of database as it was created for.

It also seems a bit odd as one of the main features of EntityFramework is to abstract the database provider from the application making it easy to change the underlying infrastructure.

Best regards

Håkan

**Comment by blowdart** [comment]
I'm afraid you're right, this is an EF problem, and as there's an issue there already I'd suggest taking it there. We're not going to roll a new identifier class, when that's really a function of the database.
