### ISSUE TITLE
Unusual behavior when implementing IUserSecurityStampStore

### ISSUE THREAD

**Issue by kamilwattoo** [aspnet/Identity#1799]
I am implementing Custom Stores without Entity Framework. But there seems to be a problem because `UserManager` always changes `SecurityStamp` prior to calling `IUserStore.Update`. Which results in failing of `IUserStore.Update` because persisted `SecurityStamp` and Current Security Stamp do not match. This behavior forces implementation of Custom Stores to use Entity Framework or some other equivalent ORM. Setting new `SecurityStamp` should be responsibility of `IUserStore.Update` and `IUserStore.Create`. Is this behavior by design?

**Comment by HaoK** [comment]
The behavior is by design, its probably your implementation of Update that is causing issues.  Update should be what's persisting the user.  updating the security stamp should just be setting the property or equivalent on the user entity.

**Comment by kamilwattoo** [comment]
When updating an entity it requires to check `SecurityStamp` is same or not. But `UserManager` change `SecurityStamp` before calling `Update` so my method fails everytime.

```
public async Task<IdentityResult> UpdateAsync(User user, CancellationToken token)
{
    // this is going to fail every time because SecurityStamp was changed
    const string sql = "UPDATE Users SET EmailConfirmed=@EmailConfimed, SecurityStamp=@NewSecurityStamp WHERE  Id=@Id AND SecurityStamp=@SecurityStamp";
   // Executing and return result
}
```

How can I avoid this issue?

**Comment by HaoK** [comment]
As you have noticed, that constraint where security stamp = security stamp is invalid.  It will never work, so remove it?

**Comment by HaoK** [comment]
The security stamp isn't something that stores can use in a way differently from how its used by identity, its something that the user manger/identity use for invalidating cookies

**Comment by kamilwattoo** [comment]
Then how can I assure that nobody else have modified the record?

**Comment by kamilwattoo** [comment]
I thought `SecurtyStamp` is for optimistic concurrency. My bad
