### ISSUE TITLE
Role being cached for too long

### ISSUE THREAD

**Issue by MetalBreaker** [aspnet/Identity#1804]
### Roles are cached for too long
So, I wanted to create an admin-only panel. That's all fine and dandy, and the mechanism ended up working. However, ASP.NET Core caches the role for too long (at first I thought it was my code), and if I add or remove the role, I have to either log out and then log back in or wait around ~10 minutes (don't quote me on that) for the admin-only panel to appear/disappear. It's very annoying.

### Functional impact
If an admin gets demoted for abusing their powers, they will still have admin powers on the website until the cached role resets.

### Minimal repro steps
1. I'm using the current code:
```
@page
@model App.Pages.Account.Manage.AdminPanelModel
@{
    ViewData["Title"] = "AdminPanel";
    var isAdmin = User.IsInRole("Admin");
}

@if (isAdmin)
{
    <h2>Hello, fellow administrator.</h2>
     //WIP
}
else
{
    Response.StatusCode = (int)Microsoft.AspNetCore.Http.StatusCodes.Status401Unauthorized;
    <h2>You are not authorized.</h2>
}
``` 
and creating the Admin role in Startup using RoleManager.
2. Try adding/removing the role to/from the user.
If it's added to the user, the admin panel should pop up immediately.
If it's removed from the user, the admin panel should disappear.

### Expected result
Changes should be effective almost immediately.

### Actual result
Changes take a lot of time to go into effect.

**Comment by blowdart** [comment]
`options.SecurityStampValidationInterval` is what you need. 

In `ConfigureServices` add 

```c#
            services.Configure<SecurityStampValidatorOptions>(options =>
            {
                options.ValidationInterval = new TimeSpan(0, 5, 0);
            });
```

Each validation does involve a database lookup, so you may want to tune the interval you choose based on load.

**Comment by MetalBreaker** [comment]
I already figured it out by myself.
Thank you anyway!

I used the `SignInManager.RefreshSignInAsync()` method.
