### ISSUE TITLE
Scaffolding 2.1 RTM in existing MVC application 404 for non overridden pages

### ISSUE THREAD

**Issue by dotnetshadow** [aspnet/Identity#1809]
I recently upgraded my ASP.NET Core application 2.1. I used the identity scaffolder to override Login and Register pages. Upon doing this I noticed that routes to logout and manage were incorrect

`?page=Account/Manage` rather than `/Identity/Account/Manage`

I then rescaffolded and this time and chose to override all files. This seemed to work. 
In my particular case there seems to be an issue with scaffolding just a handful of pages and not being able to find the remaining pages that aren't scaffolded

Just wondering if I'm missing something?

**update**
I think the issue i have is that i was using AddIdentity instead of AddDefaultIdentity. Unfortunately i am unable to try this yet

**Comment by blowdart** [comment]
@javiercn Does this happen for you?

**Comment by javiercn** [comment]
This issue was moved to aspnet/Scaffolding#811
