### ISSUE TITLE
Identity UI's embedded static files will return 404s if app.UseStaticFiles() is passed a StaticFileOptions object.

### ISSUE THREAD

**Issue by BrendanRidenour** [aspnet/Identity#1812]
**Is this a Bug or Feature request?**

Bug

**Steps to reproduce:**

1. Create a new ASP.NET Core Web Application (2.1).
2. Be sure Authentication is set to "Individual User Accounts".
3. Run the app and navigate to the Register and Login pages. Everything works as expected so far.
4. Stop the app.
5. Delete the file at "Areas/Identity/Pages/_ViewStart.cshtml". This will force Identity to use its default layout page (with links to embedded static files).
6. Now open Startup.cs and change `app.UseStaticFiles();` to `app.UseStaticFiles(new StaticFileOptions());`.
7. Run the app again (**with browser cache disabled**) and navigate back to the Register and Login pages. All the embedded static files from Identity’s Default UI now return 404s.

**Description of the problem:**

After digging through the source code, I found the problem. Calling `app.UseStaticFiles()` in Startup.cs with no options parameter works as expected because the registered `IPostConfigureOptions<StaticFileOptions>` instances get called correctly.

However, if you call `app.UseStaticFiles(staticFileOptions);` with an options argument, that instance gets passed into the `StaticFileMiddleware` directly (which is obviously by design). Unfortunately, that also means that any registered `IPostConfigureOptions<StaticFileOptions>` will NOT be called, including Identity UI’s `IdentityDefaultUIConfigureOptions` class.

`IdentityDefaultUIConfigureOptions` is the class that adds the `ManifestEmbeddedFileProvider` and `CompositeFileProvider` to the StaticFileOptions object. But if its `PostConfigure(name, staticFileOptions)` method is never called, those embedded files are not found and everything 404s at runtime.

**Comment by blowdart** [comment]
@javiercn

**Comment by javiercn** [comment]
This is by design. If you are taking control over the options used in static files, you need to include the static files used by identity manually.

To do so, you just need to create your file provider as in the snippet on the link:
https://github.com/aspnet/Identity/blob/dev/src/UI/IdentityDefaultUIConfigureOptions.cs#L65-L66
