### ISSUE TITLE
Cannot retarget "package" to dotnet core 2.1

### ISSUE THREAD

**Issue by mprevot** [aspnet/Identity#1814]
I couldn't find out how to make Identity projects work with dotnet  core 2.1 instead of 2.2-preview.
I don't have 2.2 preview, build succeeds but tests do not.
How do we do this ?

[SO](https://stackoverflow.com/questions/50680422/how-to-setup-dotnetcore-target-for-build-and-tests)

Thanks.

**Comment by blowdart** [comment]
Are you checking out the dev branch? dev is always what we're working on right now, and that's going to be targetted against 2.2, because that's what will be next.

https://github.com/aspnet/Identity/tree/release/2.1 is the 2.1 released code, so if you want 2.1 I'd start there.

**Comment by mprevot** [comment]
Thanks for the details and the pointer. I wanted to check out the GPDR components being implemented so far, and make this work targeting 2.1 (for production).

[https://github.com/aspnet/Identity/tree/release/2.1](https://github.com/aspnet/Identity/tree/release/2.1) is also targeting dotnet core 2.2.0-preview1-26531-03

Can't I retarget the dev branch to 2.1 (and asp.net identity 2.1 release too) ? If yes, what are the recommended steps ?

In any case, how should I add dotnetcore 2.2 (for development / follow) ?

**Comment by blowdart** [comment]
@HaoK can you help?

**Comment by mprevot** [comment]
Just to mention: using the nuget package manager doesn't work since the dotnet core version (2.2-preview) were "locked" by the project.

**Comment by HaoK** [comment]
You should just work off of the https://github.com/aspnet/Identity/tree/2.1.0 2.1 tree if you want to work against 2.1 and not 2.2
