### ISSUE TITLE
Can Identity be used in a WinForm App?

### ISSUE THREAD

**Issue by sbersey** [aspnet/Identity#1819]
I am using Identity in a APS.NET WebForm app and would like to log in users using the same identity database for my Desktop app (WinForms) that is currently using membership? Can this be done? Are their examples? 

(sorry if this is not the correct format for a Q: if it is not, please inform how to post a identity Q properly)

**Comment by blowdart** [comment]
Membership is really rather old, and identity hasn't been decoupled from ASP.NET, You could implement your own store to talk to the old membership tables, but at lot of the things you need simply aren't going to be there in the mapping exercise.

**Comment by HaoK** [comment]
We did most of the decoupling work already in 2.0, you would use only the `Microsoft.Extensions.Identity.Core` and `Microsoft.AspNetCore.Identity.EntityFrameworkCore` packages, there might not be very much sugar to register the appropriate services but these should contain everything you need to use identity for win forms for basic username/password.  It doesn't have some of the more complex login apis like password lockout which are today coupled with ASP.NET authentication.

**Comment by sbersey** [comment]
Indeed. Only looking to do user/password check and grab roles that the user is in all out of Identity.

Know of any example for these basic features in forms?

Thanks for the info below; much appreciated.

steve

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by HaoK** [comment]
No examples to date, but it should be fairly straight forward, mostly just need to call
`AddIdentityCore` on your service collection, and then create a scope before getting the managers.


It would look something like:
```
using (var scope = host.Services.CreateScope())
    {
        var serviceProvider = scope.ServiceProvider;
        try
        {
            var userManager = serviceProvider.
GetRequiredService<UserManager<MyIdentityUser>>();

            var roleManager = serviceProvider.
GetRequiredService<RoleManager<MyIdentityRole>>();

```
