### ISSUE TITLE
Flaky tests: CanChainRoleValidators et all

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Identity#1823]
We see this message popping up a lot in failing identity builds on [VSTS](https://dotnet.visualstudio.com/public/public%20Team/_build/results?buildId=1053&view=logs) and [appveyor](https://ci.appveyor.com/project/aspnetci/identity/build/1.0.1587):
```
System.Data.SqlClient.SqlException : Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=45447; handshake=27; 
---- System.ComponentModel.Win32Exception : The wait operation timed out.
```

**Comment by HaoK** [comment]
@ajcvickers has EF started using VSTS at all?  It looks like all the identity SqlServer tests are timing out/failing in these kinds of builds now.  This hasn't been an issue in the past so I wonder if there's something different about the configuration (timeout too low?)

**Comment by ryanbrandenburg** [comment]
EF does build against VSTS, but they might also be using different timeout settings.

**Comment by HaoK** [comment]
Dupe of https://github.com/aspnet/Identity/issues/1895
