### ISSUE TITLE
Configuirability of QR code site name in UI library

### ISSUE THREAD

**Issue by ATylerYarnott** [aspnet/Identity#1826]
In playing with the new Identity UI as a Razor Class Library, I came across the issue of how to configure the site's QR code. Previously, it was suggested to change the value in the EnableAuthenticator.chtml.cs file (the default value would be taken from the solution name). It looks like this value is hard-coded to "Microsoft.AspNetCore.Identity.UI". Thus, every website would need to scaffold and override that file in order to customize this.

Should there perhaps be an AuthenticationTokenProviderOptions class available in ConfigureServices that would allow this to be specified, perhaps defaulting to the solution name? Perhaps something like:
```c#
services.Configure<AuthenticationTokenProviderOptions>(options =>
{
    options.AuthenticatorSiteName = "MyWebsiteName";
});
```
This would follow current conventions, allow changing this value without scaffolding/overriding the UI RCL, and would provide a simpler method to configure that behavior even if that file is overridden.

Thoughts or alternate proposals?

**Comment by blowdart** [comment]
I didn't realise scaffolding did this :( Yes, this sounds like a good idea. @HaoK can you estimate how long this would take for you to add the setting and wire it through to the view?

**Comment by ATylerYarnott** [comment]
In looking more into this, perhaps a better config property name would be AuthenticatorIssuer as opposed to AuthenticatorSiteName, since it doesn't strictly have to match the site name and more closely matches the URI format.

**Comment by HaoK** [comment]
We are just talking about making this line configurable right?

https://github.com/aspnet/Identity/blob/dev/src/UI/Areas/Identity/Pages/Account/Manage/EnableAuthenticator.cshtml.cs#L159

**Comment by HaoK** [comment]
We could just add something to https://github.com/aspnet/Identity/blob/dev/src/Core/TokenOptions.cs

so you'd be able to do:

```
  AddDefaultIdentity(o => o.Tokens.AuthenticatorIssuer = "Microsoft.AspNetCore.Identity.UI")
```

**Comment by HaoK** [comment]
https://github.com/aspnet/Identity/pull/1925
