### ISSUE TITLE
connect to .NET Core 2.1 "Identity as UI" from a .NET Core 2.1 console app client

### ISSUE THREAD

**Issue by kofifus** [aspnet/Identity#1828]
I create a simple .NET Core 2.1 server using "Identity as UI" with the default template, and then add some methods 

I now need to create  .NET Core 2.1 console app client but I can't find anything on how to authenticate that client with the server (with an email & password). In particular I want to authenticate and then get the authentication cookie so that I can later feed it to ie SignalR.

As far as I understand this should be possible without an external framework like IdentityServer.

How do I do that ? is there any sample code anywhere ?

Thanks!

**Comment by blowdart** [comment]
What's your reason for avoiding identity server? It would be the best approach

**Comment by kofifus** [comment]
I'm trying to avoid bringing in (and learning) a whole new framework when I get identity out of the box. All I need is a way to get the cookie and feed it to signalr HubConnectionBuilderHttpExtensions.WithCookie .. is that not possible ?

**Comment by kofifus** [comment]
I did ended up getting this to work like this:

On the server I scaffolded Login and then in Login.cshtml.cs added

```
[AllowAnonymous]
[IgnoreAntiforgeryToken(Order = 1001)]
public class LoginModel : PageModel
```
That is I do not require the anti forgery token on login (which doesn't make sense anyway)

The client code is then like this:

```
HttpClientHandler handler = new HttpClientHandler();
CookieContainer cookies = new CookieContainer();
handler.CookieContainer = cookies;
HttpClient client = new HttpClient(handler);

var uri = new Uri("http://localhost:5000/Identity/Account/Login");
string jsonInString = "Input.Email=myemail&Input.Password=mypassword&Input.RememberMe=false";
HttpResponseMessage response = await client.PostAsync(uri, new StringContent(jsonInString, System.Text.Encoding.UTF8, "application/x-www-form-urlencoded"));
var responseCookies = cookies.GetCookies(uri);
var authCookie = responseCookies[".AspNetCore.Identity.Application"];

var hubConnection = new HubConnectionBuilder()
        .WithUrl("http://localhost:5000/hubs/myhub", options =>
        {
            options.Cookies.Add(authCookie);
        })
        .Build();

await hubConnection.StartAsync();
await hubConnection.SendAsync("Send", "hello!");
```
(of course password will be elsewhere in deployment)

**Comment by kofifus** [comment]
solved see https://stackoverflow.com/questions/50752724/authenticate-a-net-core-2-1-signalr-console-client-to-a-web-app-that-uses-iden
