### ISSUE TITLE
Add Bootstrap 4 compatible Identity UI views

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Identity#1835]

**Comment by danroth27** [comment]
@ryanbrandenburg How is this different from #1834?

**Comment by ryanbrandenburg** [comment]
I don't think it is, I probably got interupted in the middle of filing my list of issues and double-filed.

**Comment by damienbod** [comment]
I updated Identity to Bootstrap 4. Maybe you could use this:

https://damienbod.com/2018/06/26/updating-asp-net-core-identity-to-use-bootstrap-4/

**Comment by ryanbrandenburg** [comment]
Awesome @damienbod, that will be at minimum a great reference point.

**Comment by mkArtakMSFT** [comment]
@javiercn, we will need your help in delivering this in Preview1. Please work with @ryanbrandenburg to get details about the updated dependencies.
