### ISSUE TITLE
IdentityServiceCollectionExtensions.AddIdentity<TUser,TRole>() doesn't have a type constraint for IdentityUser and IdentityRole

### ISSUE THREAD

**Issue by Kiiyya** [aspnet/Identity#1836]
Basically this becomes a run-time exception while it could easily be a compile time error:

![image](https://user-images.githubusercontent.com/17028679/41507646-c36223ec-7236-11e8-9278-b35dd701a87e.png)

(Hint: I'm still new to Asp.Net authentication so I might be wrong)

**Comment by HaoK** [comment]
This is intentional, AddIdentity allows arbitrary TUser/TRole types, its AddEntityFrameworkStores that requires TUser/TRole to be derived from IdentityUser/Role
