### ISSUE TITLE
Lack of documentation on adding roles and assigning roles to users

### ISSUE THREAD

**Issue by tstivers1990** [aspnet/Identity#1837]
As the title says, there is a complete lack of documentation when it comes to role management. There's plenty of documentation on how to limit access to content based on roles. But none when it comes to creating roles, deleting roles, giving roles to users, and taking roles from users.

**Comment by blowdart** [comment]
@Rick-Anderson One for you?

**Comment by Rick-Anderson** [comment]
I though you preferred [authorization handlers](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.1#create-owner-manager-and-administrator-authorization-handlers) to roles.

**Comment by HaoK** [comment]
Being tracked in docs
