### ISSUE TITLE
Razor Pages _ViewImports documentation could be more clear

### ISSUE THREAD

**Issue by tstivers1990** [aspnet/Identity#1839]
https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio#using-layouts-partials-templates-and-tag-helpers-with-razor-pages

The part of this documentation that details the `@namespace` declaration could be made more clear. It has led some people to believe `@namespace` should be used as though it is a `using` statement. See the linked StackOverflow answer below for an example of this. I believe part of the reason it isn't clear, is because it doesn't explain `@using` directives in the context of a `_ViewImports` file.

In short, the wording could be made more clear, and a section should be added detailing `@using` directives in the context of a `_ViewImports` file.

https://stackoverflow.com/a/50322359

**Comment by blowdart** [comment]
This doesn't appear to be an identity issue, so moving.

**Comment by blowdart** [comment]
This issue was moved to aspnet/Mvc#7932

**Comment by tstivers1990** [comment]
Thanks. I derped and put it in the wrong place.
