### ISSUE TITLE
Add 'Group Based' Permissions Management

### ISSUE THREAD

**Issue by autosys** [aspnet/Identity#184]
Implementing  a more advanced, "permissions management" model, very necessary in LOB apps with large numbers of users.

**Comment by mojtabakaviani** [comment]
so can I authorize by groups?
```
[Authorize(Groups= "Administrators")]
```

**Comment by blowdart** [comment]
Questions about authorization would be better asked in the Security repo https://github.com/aspnet/security as a separate issue, rather than tagging onto an issue which isn't about authorization.

**Comment by blowdart** [comment]
Closing again, off topic now.
