### ISSUE TITLE
Scaffolding Identity code?

### ISSUE THREAD

**Issue by martinpetrovaj** [aspnet/Identity#1840]
Hey guys, quick question. One of the older blogs ([this one](https://blogs.msdn.microsoft.com/webdev/2018/03/02/aspnetcore-2-1-identity-ui/)) mentions that we should be able to also scaffold the "old" Identity (like normal controllers and views to which are all sensible and sane MVC people used to) - quoting the linked post:

> If you want the flexibility of having the identity code in your app, you can use the new identity scaffolder to add it back.

So at least that is how I understood it. Is this already implemented, has it been dropped or what? If it is a thing already, how can I access it when creating a new project? Or is there at least any real explanation of the changes, how does this new Identity UI work and how to use it? You don't possibly expect all users to read through your repo and API just to understand how to create and extend a damn login or basic application user functionality, do you?

_As a little friendly side note, reworking a thing like Identity so much from 2.0 to 2.1 without an obvious reason or any gains from user perspective and releasing it with piss-poor documentation is probably one of the main causes why so many people are still reluctant to transition to Core. This instability, fluctuation and immaturity of Core is just killing._

**Comment by tstivers1990** [comment]
That quote is intended to mean that you can scaffold the `cshtml` files into your application. It's not intended to mean that you can scaffold the old controllers into your application.
