### ISSUE TITLE
Storing huge amount of data in claims creates too large cookie ticket

### ISSUE THREAD

**Issue by ms92ita** [aspnet/Identity#1841]
Hi guys,

I have encoutered that if I have some data in user claims (from Azure SQL as storage and we use them such as dynamic properties without creating database columns), the cookie manager creates a ticket that in some cases reaches the limit of bytes per domain and I think that depends from the amount of data from the user claims.
I am using .NET 4.6.1.

Since that some of this data is vital for us, is there a possibility to exclude some claims from the ticket so we can reduce it enough and avoid these types of issue?

Kind regards

**Comment by HaoK** [comment]
You can plug in your own claimsprincipalfactory to strip out claims from the identity before it gets sent to the cookie.

**Comment by ms92ita** [comment]
Thank you for the answer.
It seems that it is possibile to implement a ClaimsPrincipalFactory only in .net core and before I've specified that I am using .NET 4.6.1
At the moment I can not update the application to Asp.Net Core.
Modifying/deleting not useful claims when I have created the identity with UserManager.CreateIdentity can be a solution?

**Comment by HaoK** [comment]
Yeah CreateIdentity is the equivalent, if you have any more issues, you should use the https://github.com/aspnet/AspNetIdentity repo for pre core identity issues
