### ISSUE TITLE
IdentityOptions.User.IdentityOptions.User.AllowedUserNameCharacters set to support a language not English, like Chinese?

### ISSUE THREAD

**Issue by Caizhenyu** [aspnet/Identity#1848]
How can i set `AllowedUserNameCharacters` to support Chinese?
I need it to be UserName not Email.

**Comment by blowdart** [comment]
You'd specify all the allowed characters in the option you mention. But given the large amount of Chinese characters that's probably not going to work for you. Instead try your own UserValidator, using https://github.com/aspnet/Identity/blob/dev/src/Core/UserValidator.cs as a staring point

**Comment by Caizhenyu** [comment]
@blowdart ，thank you. But i will add a property Name in my User : IdentityUser.
