### ISSUE TITLE
Can Web Api generate a _ValidationScriptsPartial

### ISSUE THREAD

**Issue by Caizhenyu** [aspnet/Identity#1849]
I want to create a Web Api project and i want to use Identity.
I know in MVC' script, there is `@await Html.PartialAsync("_ValidationScriptsPartial")`,
but in api project, can i get a  _ValidationScriptsPartial or other property the same use?

**Comment by blowdart** [comment]
I don't understand your question. What are you trying to achieve?

**Comment by Caizhenyu** [comment]
@blowdart , thank you and sorry , it's not clear . I want to implement a identity  system by using net core identity, and the system isn't a mvc project, it just a api project. so i need generate a  Antiforgery token. I found my answer here [https://docs.microsoft.com/zh-cn/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.1#javascript-ajax-and-spas]

**Comment by blowdart** [comment]
Ah thanks! One other option I'd look at is IdentityServer, so you'd use OIDC to get a token to authenticate against the API project through the authorization header. Which is nice and standard.
