### ISSUE TITLE
Documentation for two factor (2FA) TOTP support

### ISSUE THREAD

**Issue by skyflyer** [aspnet/Identity#1850]
ASP.NET Identity 2.x includes support for two factor TOTP authentication using an authenticator on the smartphone. I couldn't find it documented anywhere. All I could find is configuring two factor auth with SMS Code, even though the docs specifically refer to TOTP as more appropriate:

From [docs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-2.1):
>  Two factor authentication (2FA) authenticator apps, using a Time-based One-time Password Algorithm (TOTP), are the industry recommended approach for 2FA. 2FA using TOTP is preferred to SMS 2FA.

Since TOTP does not need to be configured separately and is included by default in identity razor class library, it is not a big issue, but I suppose it would make sense to document that:

* it is enabled by default
* how to disable it

**Comment by blowdart** [comment]
This issue was moved to aspnet/Docs#7326
