### ISSUE TITLE
ConfirmEmailAsync in UserManager does a ton of unrelated actions and validations

### ISSUE THREAD

**Issue by zhulien-ivanov** [aspnet/Identity#1856]
**`ConfirmEmailAsync`** in **`UserManager`** should validate a token and set the **`EmailConfirmed`** flag to true. However, in the current implementation, we save the context changes through invoking the **`UpdateUserAsync`** method. It re-sets the Normalized username and email and then calls the **`ValidateUserAsync`** method, which in turn runs the user validators. It is not that great of an overhead, but is this really necessary or is it just an architectural trade-off?

**Comment by HaoK** [comment]
Yeah this is the general pattern of UserManager methods that persist the user.  Update is the only operation that saves the user, and it always runs the valdiation/actions you see.
