### ISSUE TITLE
ConfirmEmailAsync in UserManager is not doing a check if the email is already confirmed

### ISSUE THREAD

**Issue by zhulien-ivanov** [aspnet/Identity#1861]
Hey. Shouldn't the **`ConfirmEmailAsync`** method in **`UserManager`** do a check if the email is already confirmed? Is it an adequate behaviour to successfully confirm an already confirmed email? It basically don't change the outcome in any way(and the operation can be considered as successful), because the email confirmation state stays the same, but shouldn't it be considered an exceptional behaviour and be accompanied with an error?

**Comment by blowdart** [comment]
No. You have the `IsEmailConfirmedAsync` method to check with. If you're calling `ConfirmEmailAsync` we're going to do what the method indicates, send a confirmation notice.
