### ISSUE TITLE
Two factor authentication by Email

### ISSUE THREAD

**Issue by flatproject** [aspnet/Identity#1867]
Is it possible to configure 2FA via email in a .net core 2.0 or 2.1 application? 

I can't find any information anywhere about it apart from SMS or QR code examples which are not usable in a PCI compliant environment.

Are there any email 2FA examples anywhere?

Thank you

**Comment by brockallen** [comment]
Yes, it's still in there (and presumably supported). My suggest is to create an ASP.NET Core 1.x project and see how the starter code does it.

**Comment by flatproject** [comment]
That's great, thank you! I can confirm I followed the process from core 1.x and it worked without any issues.
