### ISSUE TITLE
using same ASP.net core identity for multiple web applicaitons

### ISSUE THREAD

**Issue by bigpodgurc** [aspnet/Identity#1874]
Hello

I want to have 3 different web applications but want to use same identity back end application so i have SSO. im using Individual user accounts

thanks

**Comment by AdrienTorris** [comment]
You can check the eShopOnContainers template, there is an centalized Identity service : https://github.com/dotnet-architecture/eShopOnContainers

**Comment by bigpodgurc** [comment]
I was hoping its something that could be used with already made identity individual user authenticaton

**Comment by blowdart** [comment]
You could use Identity Server as the login point, and then connect your web sites to that via OIDC

**Comment by bigpodgurc** [comment]
thats one thing i was looking at but for now i was still looking at something that could work with what i already have(i have on onee web app accounts already and i dont want migrating accounts if it isnt neccecery)

**Comment by brockallen** [comment]
You don't need to migrate your user data to use IdentityServer.

**Comment by bigpodgurc** [comment]
didnt know that

**Comment by bigpodgurc** [comment]
@brockallen just a quick question for information if it is needed in future is there a way to use identityserver for logins in lets say console app, (basicly login in console app and for backend it uses identity server)

**Comment by brockallen** [comment]
Check the docs page: http://docs.identityserver.io/
