### ISSUE TITLE
Why isn't there a FindByNormalizedName method?

### ISSUE THREAD

**Issue by postb99** [aspnet/Identity#1879]
Hello,

I'm reading UserManager and RoleManager API documentation. I've understood the usefulness of normalized name/email, to have consistent comparison, maybe also a uniqueness value check.

Why aren't there FindByNormalizedNameAsync (UserManager and RoleManager) and FindByNormalizedEmail (UserManager) methods?

Thanks for information.

**Comment by HaoK** [comment]
Because the managers already treat them as case insensitive, what are you trying to do?

**Comment by Xarkam** [comment]
@HaoK if the managers treat them as case insensitive, where is the interest to have a normalized field in database ?

**Comment by postb99** [comment]
Thanks @HaoK so this isn't clearly stated in documentation, am I wrong? So I would need to open a PR regarding documentation.

For example:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.rolemanager-1.findbynameasync?view=aspnetcore-2.1#Microsoft_AspNetCore_Identity_RoleManager_1_FindByNameAsync_System_String_

**Comment by HaoK** [comment]
that's how they do case insensitive searches... username = Hao, NormalizedUserName = HAO.  One is for display purposes, other is for searching

**Comment by postb99** [comment]
Thanks @HaoK for the definition, but this is off-topic. My feeling was that documentation should be improved, since I know databases that are case-sensitive or case-insensitive, so legitimately wondered about the identity managers, since there is no information in documentation about search being case-insensitive. Do you agree that there is a need to be explicit in documentation?

**Comment by HaoK** [comment]
Feel free to file an issue in https://github.com/aspnet/Docs if you feel the documentation is not sufficiently clear, I believe they are fairly open to PRs as well if you have any particular ideas about how you would like the documentation to be clearer...
