### ISSUE TITLE
How can i use AspNetCore.Identity  in .net4.7 mvc5

### ISSUE THREAD

**Issue by huxiaozhong** [aspnet/Identity#1885]
i want use AspNetCore.Identity in  .net4.7 mvc5 ,can you  help me  or  give me some example;

i want to know  how to resoleve  SignInManager<User> in Controller

**Comment by blowdart** [comment]
You can't. It's part of ASP.NET Core. MVC5 is not ASP.NET Core. So you move your app to ASP.NET, or you use the older versions of ASP.NET identity. General usage questions are better shared in StackOverflow as they're not bugs or issue.
