### ISSUE TITLE
Scaffold Identity omits custom ApplicationUser

### ISSUE THREAD

**Issue by Ponant** [aspnet/Identity#1886]
**Works**
1) New project 2.1 MVC with no auth
2) Scaffold identity and choose the plus button for the user class

![scaffoldidentity21](https://user-images.githubusercontent.com/19961806/42952012-cef98632-8b77-11e8-9c61-219423f81672.PNG)

The resulting code is expected because it refers to `ApplicationUser`

`    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
`
`                services.AddDefaultIdentity<ApplicationUser>()
`

**Does not work**
1) New project 2.1 MVC with no auth
2) Create a class ApplicationUser that derives from IdentityUser
`    public class ApplicationUser : IdentityUser
`
3) Scaffold identity and choose the **dropdown** button for the user class

![scaffoldidentity21bug](https://user-images.githubusercontent.com/19961806/42952344-8aa84c10-8b78-11e8-96d4-c37ede8b262c.PNG)

The resulting code is unexpected because it refers to `IdentityUser`. `ApplicationUser `is totally ignored

`    public class ApplicationDbContext : IdentityDbContext<IdentityUser>
`
`                services.AddDefaultIdentity<IdentityUser>()
`

Bug?

**Comment by blowdart** [comment]
This issue was moved to aspnet/Scaffolding#839
