### ISSUE TITLE
ExternalLoginInfo.ProviderDisplayName doesn't use the authentication scheme display name

### ISSUE THREAD

**Issue by thomaslevesque** [aspnet/Identity#1892]
I use ASP.NET Identity with Azure AD as an external identity provider. I configured Azure AD with a display name:

```csharp
services.AddAuthentication()
    .AddOpenIdConnect("AzureAD", "Azure Active Directory", options =>
            {
                ...
            });
```

When I call `SignInManager.GetExternalAuthenticationSchemesAsync()`, I would expect `ProviderDisplayName` in the result to be "Azure Active Directory", but it's "AzureAD" instead.

**Comment by thomaslevesque** [comment]
Apparently this is a known issue:

https://github.com/aspnet/Identity/blob/ff0e9257421a296012d03e8729ad79e9471f72e8/src/Identity/SignInManager.cs#L616-L620

**Comment by thomaslevesque** [comment]
Current workaround:

```csharp
    public class SignInManagerWithCorrectProviderDisplayName<TUser> : SignInManager<TUser>
        where TUser : class
    {
        public SignInManagerWithCorrectProviderDisplayName(UserManager<ApplicationUser> userManager, IHttpContextAccessor contextAccessor, IUserClaimsPrincipalFactory<ApplicationUser> claimsFactory, IOptions<IdentityOptions> optionsAccessor, ILogger<SignInManager<ApplicationUser>> logger, IAuthenticationSchemeProvider schemes)
            : base(userManager, contextAccessor, claimsFactory, optionsAccessor, logger, schemes)
        {
        }

        public override async Task<ExternalLoginInfo> GetExternalLoginInfoAsync(string expectedXsrf = null)
        {
            var info = await base.GetExternalLoginInfoAsync(expectedXsrf);
            if (info != null)
            {
                var schemes = await GetExternalAuthenticationSchemesAsync();
                var scheme = schemes.FirstOrDefault(s => s.Name == info.LoginProvider);
                if (!string.IsNullOrEmpty(scheme?.DisplayName))
                    info.ProviderDisplayName = scheme.DisplayName;
            }

            return info;
        }
    }
```

**Comment by blowdart** [comment]
You are, as you've discovered, conflating the display name with the scheme. So your workaround isn't a work around, it's the right way to do it, it's what it done in templates. There's no bug here, it's by design.

**Comment by thomaslevesque** [comment]
@blowdart I'm confused... Are you saying that `ExternalLoginInfo.ProviderDisplayName` is _supposed_ to return the same thing as `ExternalLoginInfo.LoginProvider` and isn't supposed to actually return a display name? In this case the property is useless...

> it's what it done in templates

Which templates are you referring to? I don't think the Identity template does this; I wouldn't have needed the workaround if it did.

**Comment by thomaslevesque** [comment]
If you're talking about [this](https://github.com/aspnet/Identity/blob/master/src/UI/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs), it doesn't even attempt to use a display name, it just uses `LoginProvider`, which is a "technical" name not intended to be seen by users.

**Comment by HaoK** [comment]
Ah I misread the issue, yep its a bug, we can fix this in 2.2

**Comment by thomaslevesque** [comment]
> The default UI does use the DisplayName here https://github.com/aspnet/Identity/blob/master/src/UI/Areas/Identity/Pages/Account/Login.cshtml#L69
> so the templates should be affected by this bug too

Some places use the display name, others use the provider name, e.g.:

https://github.com/aspnet/Identity/blob/ff0e9257421a296012d03e8729ad79e9471f72e8/src/UI/Areas/Identity/Pages/Account/ExternalLogin.cshtml#L12

https://github.com/aspnet/Identity/blob/ff0e9257421a296012d03e8729ad79e9471f72e8/src/UI/Areas/Identity/Pages/Account/Manage/ExternalLogins.cshtml#L17

https://github.com/aspnet/Identity/blob/ff0e9257421a296012d03e8729ad79e9471f72e8/src/UI/Areas/Identity/Pages/Account/Manage/ExternalLogins.cshtml#L25

**Comment by blowdart** [comment]
@hoak We should fix them all to be consistent.

**Comment by thomaslevesque** [comment]
Would you be willing to accept a PR for this?

**Comment by HaoK** [comment]
Sure that would be great

**Comment by HaoK** [comment]
Thanks @thomaslevesque !
