### ISSUE TITLE
typo "deleteing" in DeletePersonalData.cshtml.cs

### ISSUE THREAD

**Issue by Gordon-Beeming** [aspnet/Identity#1907]
Small typo near line 83 in **DeletePersonalData.cshtml.cs**

`throw new InvalidOperationException($"Unexpected error occurred deleteing user with ID '{userId}'.");`

should be

`throw new InvalidOperationException($"Unexpected error occurred deleting user with ID '{userId}'.");`

**Comment by HaoK** [comment]
Thanks merged
