### ISSUE TITLE
Scaffold CRUD for Identity Roles and other Identity classes

### ISSUE THREAD

**Issue by josejmoran** [aspnet/Identity#1910]
It will be awesome if I can scaffold the CRUD operations for Identitiy Roles. The functionality is just not there or I am looking in the wrong places.

**Comment by blowdart** [comment]
We support roles, but prefer claims, thus it's not in the scaffolded code. There were also a bunch of user issues where people asked why there were roles tables when we never used them, so now you have to manually add the roles pieces.

**Comment by blowdart** [comment]
We're closing this issue as the behaviour discussed seems to be by design.
