### ISSUE TITLE
Identity documentation a la Bootstrap

### ISSUE THREAD

**Issue by josejmoran** [aspnet/Identity#1911]
One of the possible factors of the massive adoption of Bootstrap is the fact that you can go to their website and learn how to use the framework. You are able to copy and paste working code and tailor it to your needs. .NET Core will benefit greatly by providing great documentation and code sample that allows developer to learn how to use the different classes and the proper places and recommended way to use them.

**Comment by blowdart** [comment]
This issue was moved to aspnet/Docs#8129
