### ISSUE TITLE
MVC1000 warning due to the use of IHtmlHelper.Partial

### ISSUE THREAD

**Issue by thomaslevesque** [aspnet/Identity#1938]
Warning MVC1000 is triggered in the following scaffolded pages:
- Identity/Account/ExternalLogins.cshtml
- Identity/Account/Index.cshtml

> Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.

(there might be other instances of this, but I didn't scaffold all pages)

**Comment by thomaslevesque** [comment]
Oops, looks like it has already been fixed

**Comment by wysisoft** [comment]
Can you explain how this problem was solved? I get this error on every page I get from scaffolding

**Comment by thomaslevesque** [comment]
> Can you explain how this problem was solved? I get this error on every page I get from scaffolding

It was fix in the code but the fix has not released yet.

You can just use `<partial name="_StatusMessage" for="StatusMessage" />` instead of `@Html.Partial("_StatusMessage", Model.StatusMessage)`.
