### ISSUE TITLE
Does asp net core identity supports the hierarchy based resource access?

### ISSUE THREAD

**Issue by saurabhlogward** [aspnet/Identity#1943]
I am planning To use the asp net identity as a web api for my use case where I have to create  a company based hierarchy and based on which I need to provide the resource access.
I can have many such hierarchy for each company accounts. All I need to achieve  through asp net core identity is, identifying the logged in user, to which company it belongs to and what can he/she have access to with in the hierarchy.

Is this achievable using asp net core identity?

**Comment by brockallen** [comment]
Identity != Permissions

**Comment by saurabhlogward** [comment]
@brockallen I think the asp net core identity also provides the Authorization mechanism so I believe it should do that. Isn’t it ?

**Comment by blowdart** [comment]
Identity doesn't provide authorization, Identity is basically a user database. How you make use of the identities it populates is a separate concern.

(But yes, it would be possible, depending on how you extend the identity model and then plug it into [resource authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-2.1&tabs=aspnetcore2x))
