### ISSUE TITLE
Manage/_Layout.cshtml doesn't load without "AddDefaultUI"

### ISSUE THREAD

**Issue by IlyaSolovyov** [aspnet/Identity#1954]
### Title
Replacing ".AddDefaultIdentity" with ".AddIdentity" without using ".AddDefaultUI" command means that even after scaffolding all pages Manage section doesn't load its layout file.

### Minimal repro steps
1. Create new application with Identity
2. Disable default UI.
3. Scaffold all the pages.
4. Sign in and navigate to /Identity/Manage.

### Expected result
![image](https://user-images.githubusercontent.com/23297756/44991006-8458bd80-af9b-11e8-9c1e-e383f8892a85.png)

### Actual result
![image](https://user-images.githubusercontent.com/23297756/44991056-a0f4f580-af9b-11e8-969e-d9b1f73baa19.png)

### Further technical details
Scaffolded file "Identity/Pages/Account/Manage/_Layout.csthml" has a "Layout = "/Areas/Identity/Pages/_Layout.cshtml";" line that points to a non-existing file. There are no _Layout pages in Identity area other than the one in Manage section. Pointing it to global one doesn't change anything. Removing _Layout file doesn't help either

**Comment by perkops** [comment]
I can confirm, that i have the same issue.

I however found out, that when using the AddDefaultUI, it would also catch up a "faulty" layout with a wrong header/footer. (Looks pre-compiled)

When changing the Layout reference in Areas/Identity/Pages/Account/Manage/_Layout.cshtml
From:     Layout = "/Areas/Identity/Pages/_Layout.cshtml";
To:          Layout = "/Pages/Shared/_Layout.cshtml.";

The correct layout (header/footer) is shown.

**Comment by blowdart** [comment]
This issue was moved to aspnet/Scaffolding#885
