### ISSUE TITLE
Identities aren’t stored when using an in-memory database

### ISSUE THREAD

**Issue by pekspro** [aspnet/Identity#1961]
* Create a new ASP.NET Core Web Application.
* Select ASP.NET Core 2.1, Web Application and change authentication to Individual User Accounts.
* In startup.cs replace:

      services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
        Configuration.GetConnectionString("DefaultConnection")));

with

    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseInMemoryDatabase(Guid.NewGuid().ToString()));

Run the application and register an account. Logout and try to login with the created account. This will fail.

It looks like nothing is written in the Users-table when an account is registered.

I know there are [some limitations](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory) when using an in-memory database, but shouldn’t this work? If it’s not supported I would prefer an exception than the current behavior.

**Comment by blowdart** [comment]
@HaoK

**Comment by ajcvickers** [comment]
@HaoK Yep. The same database name needs to be used for saving and querying.

**Comment by pekspro** [comment]
😳  That so obvious! I don’t get how I could miss that. Thanks for the answer.
