### ISSUE TITLE
Can't use GUID identifier on IdentityRoleClaim and IdentityUserClaim

### ISSUE THREAD

**Issue by dragankae** [aspnet/Identity#1973]
I'm not able to use GUID identifier on IdentityRoleClaim and IdentityUserClaim classes. TKey is not set on the Id.

![capture](https://user-images.githubusercontent.com/10271448/45870178-918eee00-bd8a-11e8-9af7-34d06918e2e8.JPG)

**Comment by jamiewest** [comment]
Looks like you would need to override Id with `TKey` or whatever data type you want to use and potentially create a constructor to initialize the variable. Deriving this would also require that you create derived instances of the stores and manager as well. Is there a specific reason why you need this PK to be a different data type? Also, are there instances where the data type would be different that of `TKey`.

**Comment by dragankae** [comment]
I wanted to use Guid types for my identifiers and I noticed that TKey is not set on the Id in IdentityRoleClaim and IdentityUserClaim while is set on IdentityRole and IdentityUser. That kind a confused me, but anyway i will try with your suggestion with overriding.
