### ISSUE TITLE
Question: Can the cookies be customised to exclude dashes?

### ISSUE THREAD

**Issue by flatproject** [aspnet/Identity#1989]
I have two apps on Azure which work great. I recently added an Application Gateway with firewall and IPS/IDS and since then any identity cookies or cookies in general that contain a double dash "--" are getting blocked because they match the OWASP rule "SQL Comment Sequence Detected cookies". I know according to [RFC6265](https://tools.ietf.org/html/rfc6265#section-4.1.1) that a hyphen is an allowed token but is there any way to customise the cookies not to include any hyphens?

I have disabled the rule but i would feel more confident if i could actually fix the cookies and re-enable the rule.

**Comment by flatproject** [comment]
@vcsjones Apologies, I didn't make it clear in my question. I'm looking for ways to exclude double hyphen "--" from the cookie content, not the name.

**Comment by blowdart** [comment]
No. Cookies are encrypted and signed via data protection, it's opaque and can't be changed. Your IDS rule is rather wrong IMO.

**Comment by flatproject** [comment]
@blowdart ok thanks, I thought as much. Unfortunately it's the default rule (942440) from OWASP 3.0 rule set that Azure applies. Don't think it can be customised apart from on/off so I have turned it off for now.

> Detail:SQL Comment Sequence Detected. Matched Data: --2cLgVPGYiAi2uM6AoGSb- found within REQUEST_COOKIES:DevDomain: CfDJ8OtsiqIjD1VBj_Z8Dpbp3tJlPM3k1appZ0kHeyLFWlyD0PjFsd0GEEjchGFvqSl45FIMFqE6pLwxnsavLd3gLyJ2KycHOLjVSBj-Q-qjxYocgtInGbSX_CngIEFkMS1a_YbUoY2mljwLGaJrXOsypu6rqm-OY9LsqfcqGgmRScXdhYqqWBKu3PkIRKGNziIDNe9ymS8gGeiO7gyUQF5SRiwBhyKN22GRVQmO50Y7hX8OGQwrwkdnsOp3EZLx6xLcmWiXnQ8kt5nb6QzC4JJAu3OLDBvp0VLcvynDHTkyGhtIcWm3J-ZHM-dIawj0PtacTjS2tGmcUI6TAi4PjCMtmzF3fNs4KOUFnLCUMZDtywYm...
