### ISSUE TITLE
Example of an IUserClaimStore

### ISSUE THREAD

**Issue by yetanotherchris** [aspnet/Identity#1993]
Hello,

I'm looking through the source (EF mainly) and can't find an IUserClaimStore example. Does it implement it? Or is there source repo somewhere else I could find a working example?

**Comment by blowdart** [comment]
IClaimStore isn't one of ours, do you mean [IUserClaimStore](https://github.com/aspnet/Identity/blob/master/src/Core/IUserClaimStore.cs)?

**Comment by yetanotherchris** [comment]
I guess the answer is no, so I'm closing
