### ISSUE TITLE
UI package has path error

### ISSUE THREAD

**Issue by StuffOfInterest** [aspnet/Identity#2002]
I was trying to import the Microsoft.AspNetCore.Identity.UI NuGet package into a local package server (using NuGet.Server).  This one package refused to import.  After opening an issue with the NuGet team (https://github.com/NuGet/NuGetGallery/issues/6543) the problem was traced to a bad path in the embedded nuspec file.

```
<Override ContentType="application/octet" PartName="//THIRD-PARTY-NOTICES"/>
```

The server did not like the double slash in front of the name.

It appears this path is coming from the csproj file (https://github.com/aspnet/Identity/blob/master/src/UI/Microsoft.AspNetCore.Identity.UI.csproj).

```
<None Include="THIRD-PARTY-NOTICES.txt" Pack="true" PackagePath="/" />
```

My guess is the "PackagePath" shouldn't start with "/" or it cannot be just a single "/".

**Comment by blowdart** [comment]
@javiercn

**Comment by blowdart** [comment]
@javiercn

**Comment by javiercn** [comment]
@pranavkm Do you have any idea?

**Comment by pranavkm** [comment]
Specify a full path e.g. `<None Include="THIRD-PARTY-NOTICES.txt" Pack="true" PackagePath="/THIRD-PARTY-NOTICES.txt" />` seems to fix the issue. @StuffOfInterest would you like to send a PR to fix this?

**Comment by StuffOfInterest** [comment]
@pranavkm, I guess @javiercn took care of it already.  Saved me from doing a clone for a one line fix.  Thanks for getting it taken care of.
