### ISSUE TITLE
Same Package On Nuget With Different Names

### ISSUE THREAD

**Issue by brainoverflow98** [aspnet/Identity#2012]
Are there any difference between Microsoft.AspNetCore.Identity.dll and Microsoft.Extensions.Identity.Core.dll ? If not why there are two of them ?

**Comment by Eilon** [comment]
Microsoft.AspNetCore.Identity depends on Microsoft.Extensions.Identity.Core, so they are not the same thing, but both are used in ASP.NET Core Identity.
