### ISSUE TITLE
HTTP API for Identity

### ISSUE THREAD

**Issue by Sigvaard** [aspnet/Identity#2014]
Is there any HTTP API on top of ASP.NET Core identity available? I was looking at  https://github.com/aspnet/Identity/issues/1187 but it's too bloated to understand anything. I'm trying to avoid creating my own HTTP API for user management but I guess there's no other choice.

I would like to build my own interface for user management but through web API.

**Comment by brockallen** [comment]
There are commercial products that offer the API and UI: https://www.identityserver.com/documentation/admin-ui/

**Comment by blowdart** [comment]
This isn't something we're look at doing given there are other projects out there. It's outside of the scope for identity, which is a simple starting point.
