### ISSUE TITLE
UserOlnyStore bug not fix in release branch 2.0

### ISSUE THREAD

**Issue by soargon** [aspnet/Identity#2017]
there is not matched number of generic arguments 
this bug fixed on commit 85f8a49aef68bf9763cd9854ce1dd4a26a7c5d3c
![3](https://user-images.githubusercontent.com/775878/47058023-cc533d00-d1f5-11e8-829a-61fd0b9e4ff5.png)

**Comment by blowdart** [comment]
2.0 is not supported any more. If the issue is still present in 2.1 please reopen this issue.
