### ISSUE TITLE
Random token invalid issue.

### ISSUE THREAD

**Issue by LindaLawton** [aspnet/Identity#2020]
**Issue**

I have been getting a random issue with users trying to reset their passwords in our production and test environments.  

The main problem is that we recently moved about 10k users from a legacy login system over to the identity server.   When we did this their login page changed so everyone who had their password saved in their browser and now cant remember it has had to reset their password.   A small percentage of those users has not been able to reset their password.   They always get an invalid token error.     (Support says some of the email verification tokens for new users is also invalid but i have not seen this personally I need to have them send me these as well for debugging.)

I have not been able to recreate this on my local machine.    I tried copying their concurrencyStamp and secrutystamp to my own account hoping that would force it to generate an invalid token.   That did not work either.    I have about 700 test users on my local machine i went though about 50 of them before i started to loose my mind and gave up trying to recreate it that way.   

The error in question is 

> VerifyUserTokenAsync() failed with purpose: ResetPassword for user 289512042.

This didnt give me much information so i added my own debuging and added this issue request which i will be posting a pull request for later this morning [Show errors in the log from VerifyUserTokenAsync](https://github.com/aspnet/Identity/issues/2000)

> User reset password failed [user.Id: 289512042] Invalid code

So i know that the error is that the code is not valid.    

-  I can verify that the code is not to old.   I have seen the the logs the user requesting it and then getting the email and clicking on the link within minutes.   It does not work.
-  I also have a supporter who swears she watched the user do it over team viewer they event tried using an incognito window.

**About the application**

-  .net core 2.0 
-  Identity server 4.   
-  Entity framework with Asp .net users.
-  one Redis server running in test and production.  
-  Production and test running in a docker swarm.  
-  Identity server # of instances Test running two instances  production running one.   We are still trying to fix bug with this user move so didnt want to make matters worse by running multiple instances in production yet.   I had it running two instances last week for a day or so just to test it.

**Start up**

```
_logger.LogInformation(LoggingEvents.StartupRedis,
$"Data protection enabled with with redis: {Configuration["Redis:ApplicationName"]}", Configuration["Redis:ApplicationName"]);

                
services.ConfigureApplicationCookie(opts =>
                    opts.SessionStore = new RedisCacheTicketStore(new RedisCacheOptions()
                    {
                        Configuration = Configuration["Redis:HostPort"]
                    }, _logger, Configuration)
                );
 var redis = ConnectionMultiplexer.Connect(Configuration["Redis:HostPort"]);
services.AddDataProtection(config => config.ApplicationDiscriminator = Configuration["Redis:ApplicationName"])
                    .SetApplicationName(Configuration["Redis:ApplicationName"])
                    .PersistKeysToRedis(redis, "DataProtection-Keys");

```

Application name is based upon environment "ApplicationName": "XXXXIdentityserver-v2-Production-Key"

We currently only have one redis server which is serving both production and test.

**Background Info**

This identity server has been running for around two years.   I recently added asp.net users and imported about 10k users into it from a legacy system, so that it now manages the users.   When i did the import of the users I neglected to create them a concurrencyStamp and securitystamp.    This lead to an issue where legacy users were creating a reset password token that would never validate.  (_It may be an idea to test that the stamps are not null before creating the token in the library itself._ )  I have added a check in my code before creating the token to ensure that a user has the tokens before creating the reset password token.

`if (user.SecurityStamp == null) await _userManager.UpdateSecurityStampAsync(user);`

This random invalid token is happening on new users as well as legacy users who have already reset their password once.     So it is IMO unrelated to the fact that these are legacy users as opposed to newly created users.

Reset password

 ```
[HttpPost]
[AllowAnonymous]
[ValidateAntiForgeryToken]
public async Task<IActionResult> ForgotPassword([FromForm] ForgotPasswordViewModel model)
{

     {removed}

      var passwordResetCode = await _userManager.GeneratePasswordResetTokenAsync(user);
      var passwordResetCallbackUrl = Url.ResetPasswordCallbackLink(user, model.ReturnUrl, passwordResetCode, Request.Scheme);

       {removed}
       return RedirectToAction(nameof(ForgotPasswordConfirmation));
}
 ```

Helper method

 ```
public static string ResetPasswordCallbackLink(this IUrlHelper urlHelper, ApplicationUser user , string returnUrl, string code, string scheme)
        {
            return urlHelper.Action(
                action: nameof(AccountController.ResetPassword),
                controller: "Account",
                values: new { userid = user.Id, code = Uri.EscapeDataString(code), returnUrl },
                protocol: scheme);
        }
```

**EscapeDataString**

I have recently started using EscapeDataString i read this very old question on stack[Asp.NET Identity 2 giving “Invalid Token” error](https://stackoverflow.com/questions/25405307/asp-net-identity-2-giving-invalid-token-error) and figured it was worth a try.       I cant verify that it works yet.   Its fall vacation this year the number of users trying to reset their password this week isnt enough to verify that its working.

**An Example**

If it helps this was an invalid code that had been requested last week.   At the time of its use it was only just created.

https://logintest.XXXXX.biz/Account/ResetPassword?userid=25296662&code=CfDJ8PJUKz96qKpBrYBBC57a4f3D%2Bgt7xJOmrQN9kMSVuLUXecxJMDVFsG%2BFd5T7BJZai84psokeVyTD5JUJRzzNlFmd%2F%2BISYRh%2Bm%2FxbLrqS4oY0FBfYNy1GcZx%2BlRawi1bXAzlyksAiITrLOUYEaz%2F5J53CLmjGUhG3JlTxK9J6PiXH

**Note**

I hate to bother you with an issue that I cant prove, cant recreate,  and cant debug.   But i am running out of ideas.  I sent out a call on Twitter and Barry Dorrans responded and suggested i post this here.    Any help would be greatly appreciated. 

Our UserId is a long not the standard GUID.  This was due to the legacy system.  Changing that to support GUID would have been to big of a job.

**My current idea**

Ok after digging around in the library.  I think I have an idea.   What if i create a custom IUserTwoFactorTokenProvider basically copy DataProtectorTokenProvider.   My idea is to create a validation method then call that from ValidateAsync.   I want to use the exact same one thats used in DataProtectorTokenProvider.   By having one that i can call that will return the error rather than just a true and false i can call that if the validate fails and then log why it failed.

**Comment by blowdart** [comment]
@LindaLawton do these users have valid security stamps?

**Comment by HaoK** [comment]
You should be able to test users by just calling Generate and Validate right away, see if any of the users fail when doing that...

```
   var token = await _userManager.GeneratePasswordResetTokenAsync(user);
   var result = await VerifyUserTokenAsync(user, _userManger.Options.Tokens.PasswordResetTokenProvider, _userManager.ResetPasswordTokenPurpose, token))
```

Otherwise if i were to guess what's going on, maybe the security stamp for those users has changed after the token was generated, that would cause the tokens to be invalid.

**Comment by blowdart** [comment]
It looks like when a key is created it's not getting stored in the Redis cache. Can you try dumping the cache and see what's in it?

**Comment by LindaLawton** [comment]
@blowdart  I am in the process of getting access to the cluster so i can see this information.   How soon after i see the error do you need me to dump the cache?

Just got another intersting error from my logging
```

System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Xena.IdentityServer.Services.CustomDataProtectorTokenProvider`1.<ValidateAsync>d__13.MoveNext() in /var/lib/jenkins/_xena-identityserver_master-GOXBVJ5FZB6XR4BFBDEOFNCAVTISFMJUP3YCSGLXO77AA655HWSQ/src/Xena.IdentityServer/Services/CustomDataProtectorTokenProvider.cs:line 113
```

**Comment by blowdart** [comment]
As that's identity server I have no insight as it's not us

**Comment by brockallen** [comment]
> Xena.IdentityServer.Services.CustomDataProtectorTokenProvider

That looks more like custom code in IdentityServer.

**Comment by LindaLawton** [comment]
@brockallen if you are following the thread.  I have created a CustomDataProtectorTokenProvider which is a pure copy of [DataProtectionTokenProvider.cs](https://github.com/aspnet/Identity/blob/c7276ce2f76312ddd7fccad6e399da96b9f6fae1/src/Identity/DataProtectionTokenProvider.cs) simply adding some logging since the default version does not contain any logging.  

There is no custom code in this.  Its just logging so that we can try and track down what the issue is.
