### ISSUE TITLE
Support for ApiAuth using Identity Server

### ISSUE THREAD

**Issue by javiercn** [aspnet/Identity#2033]
Our goal is to leverage Identity Server to provide a simplified story for providing authentication and authorization for APIs. Our focus is on:

* Simplified setup of Identity Server with an API on the same app.
* Simplified setup of Identity Server with a SPA on the same app.
* Simplified setup through configuration and smart defaults.
* Simplified setup using Identity as the account store.
* Simplified setup using Identity default UI for login.

**Comment by RainingNight** [comment]
any new?

**Comment by blowdart** [comment]
Merged in https://github.com/aspnet/Identity/pull/2047

Discussion in https://github.com/aspnet/Identity/issues/2048
