### ISSUE TITLE
Question: can return an IIdentityBuilder interface instead of IdentityBuilder class?

### ISSUE THREAD

**Issue by qqliweng** [aspnet/Identity#2042]
i want to use my ApplicationIdentityBuilder class than inherit from  IdentityBuilder class
when use   services.AddIdentity<TUser,TRole>() it will never return ApplicationIdentityBuilder 
because in server.AddIdentity<TUser,TRole>() will return this
![source_code](https://user-images.githubusercontent.com/3477336/47772626-3f929e00-dd22-11e8-942e-42d3d67d28c7.png)
in order to use my ApplicationIdentityBuilder  so i write an extension method like this
![aaa](https://user-images.githubusercontent.com/3477336/47772770-b5970500-dd22-11e8-8490-7d9dd34046ad.png)
of course it works fine but looks like little strange
in my customer  SignInManager like this
![bbb](https://user-images.githubusercontent.com/3477336/47774683-aadf6e80-dd28-11e8-9d64-86c61e8e3d77.png)
i think server.AddIdentity<TUser,TRole>() return an IIdentityBuilder Interface will be better
so if we want use customer IdentityBuilder can like this
![ccc](https://user-images.githubusercontent.com/3477336/47775091-b1221a80-dd29-11e8-985e-d50586d5c407.png)
and ApplicationIdentityBuilder  define can like this
![ddd](https://user-images.githubusercontent.com/3477336/47775342-589f4d00-dd2a-11e8-98f2-1dbf73f89873.png)

**Comment by qqliweng** [comment]
can return a IIdentityBuilder from services.AddIdentity<TUser,TRole>()  not IdentityBuilder directly?

**Comment by blowdart** [comment]
As you can see from the method definitions the answer is no.
