### ISSUE TITLE
[Question] Passwords should not be of type String ?

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Identity#2051]
My security team escalated to me that the `PasswordHasher` is vulnerable to heap inspection, as the password is of type `String`. 
It should be instead a byte array / span of bytes cleared at the end of the process, as it is done by any cryptographic operation in corefx. CC @bartonjs.
Same problem with any password related types (`IPasswordValidator`, and maybe also the `IUserPasswordStore`)

**Comment by blowdart** [comment]
So .. yes but ...

When the passwords are delivered over an HTTP request they're strings. You can pretend to add safety by turning them into a byte array, but it doesn't add anything, they've been strings already, now you have them represented in two places. It's the same problem SecureString has, byte arrays are only useful if you control the input mechanism. 

So sure, in theory yes, in practice it adds nothing.

**Comment by ycrumeyrolle** [comment]
But what if I am controlling the input mechanism?
In my case, password is a PIN typed on a randomized virtual keyboard. The http request just has the position on the keyboard, not the value. After decoding the position, I am able to provide a byte array without passing by a string.

**Comment by blowdart** [comment]
Then you're way outside what we expect identity to be used for.
