### ISSUE TITLE
Spelling error DeletePersonalData.cshtml.cs 

### ISSUE THREAD

**Issue by blankenbush** [aspnet/Identity#2065]
The word "deleteing" is wrong.  It should be "deleting" on line: 111; DeletePersonalData.cshtml.cs.

Also found in comment on line 183; SqlStoreTestBase.cs

![capture](https://user-images.githubusercontent.com/187785/48412982-33401500-e714-11e8-903b-6e2fcc8e0a6a.PNG)

**Comment by blowdart** [comment]
Would you like to go for a pull request here? :)

**Comment by blankenbush** [comment]
https://github.com/aspnet/Identity/pull/2066
