### ISSUE TITLE
BypassTowFactor in SignInManager:ExternalLoginSignInAsync should default to False

### ISSUE THREAD

**Issue by wijnsema** [aspnet/Identity#2067]
As requested by @brockallen in #850 it is now possible to bypass 2FA in case of an external login. 

I'm sure there are good reasons to bypass 2FA, however the current implementation is far to general: 

- All providers all treated equal (some providers might not even support 2FA at all)
- All users all treated equal (users can have 2FA enabled or not)

This bypass of 2FA really needs more refinement.

**What makes this really a problem is the fact that it is enabled in the UI templates!** 
As a developer using the template and enabling 2FA you expect 2FA to work for both local and external login!

Furthermore, the redirect to the 2FA page is missing, so changing to call to `bypassTwoFactor = false` results in a confusing error that the user already exists.

In my opinion the following fragment from ExternalLogin.cshtml.cs
```C#
var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, 
      info.ProviderKey, isPersistent: false, bypassTwoFactor: true);
if (result.Succeeded)
{
   _logger.LogInformation("{Name} logged in with {LoginProvider} provider.", 
      info.Principal.Identity.Name, info.LoginProvider);
   return LocalRedirect(returnUrl);
}
```
should be replaced with
```C#
var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, 
   info.ProviderKey, isPersistent: false, bypassTwoFactor: false);
if (result.Succeeded)
{
   _logger.LogInformation("{Name} logged in with {LoginProvider} provider.", 
      info.Principal.Identity.Name, info.LoginProvider);
   return LocalRedirect(returnUrl);
}
if (result.RequiresTwoFactor)
{
   return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl });
}
```
If you enabled bypassTwoFactor it will still work.

**Comment by vankampenp** [comment]
Exactly, that is how I implemented it in my UI customization

**Comment by blowdart** [comment]
If you are using external providers we expect the 2fa enforcement to be their concern, not that of your app.

**Comment by vankampenp** [comment]
There are two issues with this.
First, my app contains sensitive data, and it makes sense to use 2fa with that. Someone might have a different view on the sensitivity of their Facebook account, and not use 2fa with that. Now when you would leave the concern for 2fa enforcement to the external provider, the very fact that I have a Facebook login possibility on the site, a hacker can use the Facebook login to bypass the 2fa. In other words, if any site has social media logins, then the user needs to put 2fa on all those social media accounts to get the same protection level. 

The second issue is that the code currently does not work that way. 

```
var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, 
      info.ProviderKey, isPersistent: false, bypassTwoFactor: true);
if (result.Succeeded)
{
   _logger.LogInformation("{Name} logged in with {LoginProvider} provider.", 
      info.Principal.Identity.Name, info.LoginProvider);
   return LocalRedirect(returnUrl);
}
```
In the above code, result.Succeeded returns false if my app wants 2fa to be checked (cookie expired). So I think @wijnsema  is correct to suggest that the code needs to check on result.RequiresTwoFactor.

**Comment by wijnsema** [comment]
> If you are using external providers we expect the 2fa enforcement to be their concern, not that of your app.

From a theoretical point of view, I agree with you. In practice, with social providers like Facebook and Twitter the 2fa from the app can be a welcome extra security layer. 

Like mentioned before: As a developer using Identity I was surprised to see 2fa not working with external login. But I understand your explanation.

**Comment by blowdart** [comment]
Well what if someone added 2fa to facebook already? Do people really expect two 2fa prompts? I think 4fa might be an unwelcome shock :)

**Comment by vankampenp** [comment]
That would be a rare case where both 2fa cookies are expired at the same time, but yes, I would expect that.

In any case, the current code does not work, as it does not log the user in at all, when the 2fa cookie is expired.

**Comment by wijnsema** [comment]
Maybe not a big problem.

1. They were probably logged in to Facebook earlier, and trusted their computer for a week or so.
2. 2fa might not be the same for all platforms

**Comment by blowdart** [comment]
The code bug is a bug, @HaoK can you look at that?

I'd respectfully disagree on the idea that "you expect 2FA to work for both local and external login", as that's not how it's designed, and to be honest it's not something I've seen in the wild, so this would be something the templates wouldn't support without you changing the flow as you have,

**Comment by vankampenp** [comment]
We then agree to disagree. I remain that if someone put’s social media logins on their site, social media logins should not enable someone to bypass the 2fa that you have set on that site. If someone hacks your PC and steals both your sensitive app’s credentials and your social media credentials, you still should be able to trust the 2fa that you have set on the sensitive app.

Put it the other way, for GDPR, 2fa helps me to prove that the user logged in, rather than some hacker, in case of a data leak. With your preferred implementation, it proves nothing, as I cannot check if someone has also protected their social media accounts. In that case, I need to take that possibility of my app altogether.

In my view, the code is not a bug, the UI has a bug.

**Comment by blowdart** [comment]
Yes, I accept its a scenario that would work for you, but templates are starter points which cover the common cases, hence saying it's not suitable for the templates themselves.

**Comment by vankampenp** [comment]
That is fine with me, but if you change the output of ExternalLoginSignInAsync to return true where it now returns false for 2fa, it would break my code, and disable my scenario.

**Comment by vankampenp** [comment]
I suggest you change the template to:

```
var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, 
      info.ProviderKey, isPersistent: false, bypassTwoFactor: true);
if (result.Succeeded || result.RequiresTwoFactor)
{
   _logger.LogInformation("{Name} logged in with {LoginProvider} provider.", 
      info.Principal.Identity.Name, info.LoginProvider);
   return LocalRedirect(returnUrl);
}
```
Than nothing breaks

**Comment by wijnsema** [comment]
@vankampenp be careful not overrate 2fa as 'prove' of a users identity. 2fa is just an extra layer. 2fa is as secure as the generated key used to set it up. If this key is leaked somehow (it is not stored encrypted in the default implementations) anybody with this key can bypass 2fa easily.

**Comment by blowdart** [comment]
True, if you really wanted proof you'd go for certificates, but even those aren't foolproof.

**Comment by vankampenp** [comment]
@wijnsema thanks for the tip!. If someone gets the contents of my database, I have a whole other problem. In the end nothing is secure. 

But it helps me to think that this extra layer prevents someone to guess a password, or reuse a password written on paper or something like that. At least the hacker will need access to the mobile phone as well (or my database, but than they are no longer interested in bypassing the 2fa).

**Comment by HaoK** [comment]
@blowdart what code bug are you specifically referring to in here, there's a lot of comments and its not clear to me what behavior is the bug

**Comment by wijnsema** [comment]
@HaoK  I'm not sure this is actually a bug. Maybe @vankampenp can clarify.

From my perspective: 
I wanted to change the behavior of the app to require 2fa for external login providers. I changed the ExternalLoginSignInAsync call to bypassTwoFactor: false. But then result.Succeeded is false while result.RequiresTwoFactor is true. 

The code then tries to register a new user, which fails because the user already exists!

If you add
```
if (result.RequiresTwoFactor)
{
   return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl });
}
```
just like in Login.cshtml.cs you are redirected to the 2fa page as expected.

If you have bypassTwoFactor = true these lines have no influence. 

So yes, you could call this dead code, but it is very convenient for those who change the bypassTwoFactor while not harming those who leave it as is.

**Comment by wijnsema** [comment]
Taking one step back, it wouldn't be dead code if the default would be to have 2fa for external logins...

**Comment by ajcvickers** [comment]
@HaoK Even though the code is not in the template, given that we tell people to scaffold the code into their applications, it effectively becomes the same as code in the template. Therefore I think we should fix this. 3.0 is fine.

**Comment by blowdart** [comment]
Leaning towards this not being a bug, we don't want two two factor challenges. Scaffolding out and changing the code is the way to go.
