### ISSUE TITLE
Replace a Role Validator

### ISSUE THREAD

**Issue by mmillican** [aspnet/Identity#2080]
I am trying to create a custom role validator to support pseudo-multi-tenancy (which I know is not _officially_ supported in Identity) and am running into some issues.

I've verified that my validator does work and is being called. However, the default validator appears to be called also. 

Here's my Identity service registration
```
services.AddIdentity<User, Role>(setup =>
    {
        // Redacted settings
    })
    .AddRoleValidator<CustomRoleValidator<Role>>()
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders();
```

How can I _remove_ the default RoleValidator?

**Comment by HaoK** [comment]
If you add a `IRoleValidator<Role>` before calling AddIdentity, it should skip adding the default one.  Alternatively i believe you can remove service registrations directly as well, but try adding yours first

**Comment by mmillican** [comment]
Thanks @HaoK! That did the trick.

I also had to change the unique index on the Roles table as well.
