### ISSUE TITLE
Microsoft.AspNet.Identity.MongoDB

### ISSUE THREAD

**Issue by adam-szabo** [aspnet/Identity#225]
I have created a MongoDB provider which builds against Identity 3.0.0-alpha4.
Is this something you planned, or would be interested in having incorporated in the project?
If so, I can tidy it up and create a new pull request.

**Comment by kowsheek** [comment]
I'd love to see MongoDb support for Identity, both standalone and through EntityFramework. While I'm not using Identity & MongoDb right now, I'd imagine it being used with Mongoose.

**Comment by rustd** [comment]
We are looking for community contribution for this one.

**Comment by dstockhammer** [comment]
At the moment the MongoDb C# driver does not support dnxcore, and I'm not aware of any plans to add support in the near future. I suppose that's a problem for "official" MongoDb support in an Microsoft.AspNet.* package?

If however this is acceptable, I'd be happy to generalize my (working) implementation and submit a PR for review.

**Comment by SharePointRadi** [comment]
So far I have a Microsoft.AspNet.Identity.MongoDb library with all unit tests passing: https://github.com/OneBitSoftware/Identity/tree/MongoDBImplementation

From a perspective of running unit tests and attempting all the plumbing - all good and a leap forward.

But, the challenges at the moment:
- dnxcore50 and getting the dependencies to always work for the ASP.NET sample application
- the MongoDB C# driver not working for dnxcore - I have started discussions and a fork already exists:
https://jira.mongodb.org/browse/CSHARP-1177?filter=-4&jql=text%20~%20%22coreclr%22%20ORDER%20BY%20createdDate%20DESC 
- breaking changes in asp.net slow things down quite a bit: https://github.com/aspnet/Announcements/issues/51

Effort should go there now so we can actually build an asp.net web application running in dnxcore, depending on Identity and the MongoDB implementation.

**Comment by SharePointRadi** [comment]
Just to add, this is where the dnxcore discussion is happening for Mongo: https://github.com/mongodb/mongo-csharp-driver/pull/210

I'll be spending some free time there to see how I can help move it forward.

**Comment by tugberkugurlu** [comment]
Here is an implementation for this http://www.tugberkugurlu.com/archive/asp-net-5-identity-mongodb-implementation which supports dnx452 for beta8 runtime. It's available on NuGet: https://www.nuget.org/packages/Dnx.Identity.MongoDB.

**Comment by HaoK** [comment]
We are not planning on releasing our own, but this is good for the community to own.
