### ISSUE TITLE
Overriding the Identity Error Messages

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#23]
AFAIK, currently the error messages in identity library are not override-able. For example, we cannot override 'Name {0} is already taken.'. This will cause a big headache for multi-lingual application and also in some other cases,  http://forums.asp.net/t/1957899.aspx?How+to+override+validation+for+UserName

**Comment by djs1** [comment]
1) This is getting a second look. See https://aspnetidentity.codeplex.com/workitem/1947 and http://aspnetidentity.codeplex.com/discussions/638351. 

2) I think that the word "Override" means "change the resources.resx file's value" not point to another neutral culture.
