### ISSUE TITLE
Expose UserValidator logic in virtual methods for extensibility

### ISSUE THREAD

**Issue by danielwertheim** [aspnet/Identity#241]
Use-case. When implementing the identity provider model against a store/DB that only has one unique constraint possibility, e.g the Id; you then also want that field to be able to hold e.g. username and/or email. That is `Id --> UserName --> Email`

If you do this the validator will not report on duplicate username and/or email, due to e.g.

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/UserValidator.cs#L64

If there was an owner, it is not considered to be a duplicate if the Id's of the owner and new user are the same. In the case where the Id is represented by e.g. email, this will be the case, when it actually should be a duplicate violation.

**Comment by rustd** [comment]
Will be done as part of #278
