### ISSUE TITLE
There should be a way of providing claim uniqueness 

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Identity#246]
I feel there should be a way of providing claim uniqueness inside the identity library but I'm not 100% sure how and where this should be done. [`ClaimsIdentity.Claims`](http://msdn.microsoft.com/en-us/library/system.security.claims.claimsidentity.claims(v=vs.110).aspx) doesn't enforce uniqueness of a claim and that raises a few questions for me like which information inside the claim should participate in uniqueness check. In some cases, the type information will be enough but in some cases, maybe all the information inside the claim will participate inside the check process. This sort of makes it clear for me that this all really depends on the application's business logic.

This issue is also somehow related to #245 but I feel that this thing deserves its own place of discussion :smile:

**Comment by rustd** [comment]
User can implement this in their app.
