### ISSUE TITLE
ReplaceClaimAsync EF Implementation: update the POCO or remove the old one and create new one

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Identity#251]
Today, on [ReplaceClaimAsync](https://github.com/aspnet/Identity/blob/8672bd7797c819b94970628e70fd073b4dfdb043/src/Microsoft.AspNet.Identity/IUserClaimStore.cs#L43), it's replacing the claim by updating the POCO as opposed to removing the existing one and creating a new one [inside the EF implementation](https://github.com/aspnet/Identity/blob/8672bd7797c819b94970628e70fd073b4dfdb043/src/Microsoft.AspNet.Identity.EntityFramework/UserStore.cs#L444-L468). It should be decided whether this is the right approach or not.

This issue raised [during the PR](https://github.com/aspnet/Identity/pull/239#discussion_r19754562).

**Comment by HaoK** [comment]
We decided to go with update the existing poco which is the current behavior
