### ISSUE TITLE
Support Multi Tenancy out of the box

### ISSUE THREAD

**Issue by mbeckenbach** [aspnet/Identity#266]
Lots of guys out there build multi tenant apps. This is a feature, that should be part of a modern identity framework.

Maybe the mechanism could be similar to roles. A user can be a member of one or more tenants. 

This would allow to easily set permissions, change the frontend theme or control data access by tenant.

I'm thinking on a quite easy way to access this info like 

if(User.IsInTenant('microsoft')) {
 // do some thing tenant specific
}

or

User.GetTenants();

Also this could be coupled with azure ad multi tenant apps in a nice way.

**Comment by papyr** [comment]
This should be revisited!

**Comment by mach37** [comment]
Absolutely needed - shame on ASP TEAM for leaving this out. From the ASP home page, the goals are to support large enterprises and saas apps, but if you leave this out... you're inherently leaving this implementation open to flaws and more vulnerabilities, thus ignoring security 

+1 for @mbeckenbach @papyr for calling this out.

**Comment by brockallen** [comment]
I just implemented this recently, and it was not that difficult. It did require a good understanding of the inner working of the framework. I agree it should be better integrated/supported by the ASP.NET Identity framework itself, though.

**Comment by luisgizirian** [comment]
Any chance you can share your efforts Brock?

**Comment by brockallen** [comment]
iirc, here's the short list of what i did: delete the 2 username and email indexes the built-in stuff creates. add a tenant column to the user table. add new indexes for username/tenant and email/tenant. add a tenant to the store and change the IQueryable users property to filter on tenant.

**Comment by brockallen** [comment]
also, in the store overload create and set the tenant on the user.

**Comment by brockallen** [comment]
the most painful part of all of this is the base DbContext creating the 2 indexes on username and email and EF not providing an easy way for a derived DbContext to undo base class OnModelCreating stuff. better support would be in EF to delete an index on the ModelBuilder, or in ASP.NET Identity to have virtuals for pieces of this so you can override some of them rather than having to replace all of OnModelCreating and copy 95% of their default code. // @HaoK @rowanmiller

**Comment by luisgizirian** [comment]
Thanks! We have an Identity v2 customized for Multitenancy based on a
GitHub Jskimmer library. As we couldn't understand how to make it work on
v3 we have a bigger migration on hold. We'll investigate on your guidance.

**Comment by brockallen** [comment]
feel free to fund me working on an OSS version of it for AspId3 :)

**Comment by luisgizirian** [comment]
Sure thing!

**Comment by mach37** [comment]
While it seems fun and just, the fact is for the average developer or small businesses/devs this is an absolute pain. 3rd party options/flavors as OSS are great; however, **a basic default implementation MUST BE part of the templating option during the creating of the initial project.**

This is not trivial for the average developer and the version that @luisgizirian is referring to - is over 2 yrs old, missing _(user lock outs, SMS verification, host tenants, super admin, user impersonation, skinning, redirects, handlers, etc.. the list is long)_ - clearly not for the faint of heart, a serious detour from the core business logic and work I do as a developer.

More importantly, until the core team tries the implementation on their own - they will not realize to flush out how under the current framework simply not geared to support tenants easily.

Case in point - _a peek into orchard, music store, umbarco, skimming and others biggies implementation reveals **how very complicated, extensive** and different they all are just to implement the core multi tenants._ 

@blowdart @rustd - ASP TEAM devs please get your act together if you're serious about helping the developer community!!

**Comment by tugberkugurlu** [comment]
Putting each tenant's identity data into a different database would accomplish that unless I am missing something. That way you can pretty much use all of the identity implementations out there within your multi tenant app.

To my experience, it's mostly a good idea to keep the database(s) single tenant whereas you keep the application level multi-tenant. This increases the operational costs (e.g. monitor more databases, backups of all, updating more database (if your database has schema), etc.). This approach would also allow you to allocate different level of resources for your each tenant. In identity case here, each tenant can have customized database resources (e.g. Tenant A's identity database is on a SQL Azure Premium database since it has 10 million users, Tenant B's identity database is on a SQL Azure Basic database since it has 1000 users, etc.).

**Comment by luisgizirian** [comment]
We're using AspNet Identity v.2 with Mutitenancy support using @jskimming library (https://github.com/JSkimming/AspNet.Identity.EntityFramework.Multitenant).

Following on @tugberkugurlu comments, on the DB side of our evolution plan, we'd like to use an Azure Elastic Pool for SQL. Here, the sharding key would be the TenantId.

Without Identity's v3 supporting multitenancy the way we do with v2, we can't find a way to move to v3, so it forces us to keep doing v2 on MVC5.

To clarify what I said earlier on this thread, this is also stopping us from a bigger move on porting all our platform to AspNet Core and being able to run our workloads into Azure Service Fabric.

**Comment by tugberkugurlu** [comment]
> we'd like to use an Azure Elastic Pool for SQL. Here, the sharding key would be the TenantId.

AFAIK, [you can put multiple databases into the pool with Azure Elastic Pool](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-elastic-pool), no?

**Comment by luisgizirian** [comment]
Sorry @tugberkugurlu, can't see your point (feel free to write me directly). Lets please not deviate the discussion from the main issue here. :)

**Comment by JSkimming** [comment]
@luisgizirian I've been somewhat negating that [library I created](https://github.com/JSkimming/AspNet.Identity.EntityFramework.Multitenant), I don't have the time and I don't use it myself (the project for which it was written never took off).

I'd happily review any pull requests should someone submit one, also happy to consider freelance work 😃

**Comment by weedkiller** [comment]
#https://github.com/aspnet/Identity/issues/569

So many others here have this need!

**Comment by tugberkugurlu** [comment]
@luisgizirian I don't mean to deviate from the issue. I talking about something related which you originally brought up.

The point I am trying to make is that storing the identity data in one database for all of your tenants is a not a good idea at all. There are so many things that can go wrong if you architecture your system in this way. See https://ayende.com/blog/3497/multi-tenancy-the-physical-data-model for a few of those scenarios. 

Even if you are OK with this architecture, a generic library like ASP.NET Identity should not encourage you to adopt this pattern. In fact, clearly, it's not hard to do this w/o having an explicit support from this library if you really want to shoot yourself in the foot.

**Comment by mach37** [comment]
I also can see @tugberkugurlu point of view, and how the tenant is configured for storage can be a simple option during install during setup. A check box of whether sotred in same tables, different tables or different db's all together

How can we get this issue re-opened.
