### ISSUE TITLE
AzureAD should be a first class citizen

### ISSUE THREAD

**Issue by mbeckenbach** [aspnet/Identity#267]
An azure ad middleware (that supports also multi tenant or mixed mode with local users) should be as important as the facebook login. 

.Net is still mostly used in enterprise. Enterprises need something made for enterprises. not facebook. 

Please extend your development, documentation and support for your own authorization technologies.
On MyGet there are already vnext packages for google, facebook and co. but nothing for windows auth or azure ad. Even on "vLast" azure ad via oauth / open id is not really good documented or implemented until today.

**Comment by GuardRex** [comment]
@blowdart I'm just arriving to the issue. https://github.com/AzureADSamples/WebApp-WebAPI-OpenIdConnect-AspNet5/tree/master/TodoListWebApp is broken for `dnxcore50` ... it's so old it actually names `aspnetcore50`, so it's not surprising it doesn't work. https://github.com/r2musings/AzureADTest/tree/master/src/AzureADTest2 works, but only for `dnx451` ... I couldn't get a `dnxcore50` version working. Do you know of any `dnxcore50` sample that will handle a vanilla AAD Identity authentication? ... or is the middleware just plain broken right now for Core CLR?

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
