### ISSUE TITLE
Pluggable telephone number validator

### ISSUE THREAD

**Issue by Avalaxy** [aspnet/Identity#270]
Hi,

I'd like to add a IIdentityValidator to the UserManager class that allows the application developer to inject a pluggable telephone number validator that can be used to validate telephone numbers against the E164 standard before being persisted to the database.

I would then add a check in SetPhoneNumberAsync to see if a validator has been configured. If so, it will be used to validate the number, otherwise all input (if not empty) is accepted.

Can I go ahead a build this and offer it as a pull request or would that be a waste of my effort?

**Comment by rustd** [comment]
The valitdators are pluggable so you can write your own.
