### ISSUE TITLE
apiKey login

### ISSUE THREAD

**Issue by NicoJuicy** [aspnet/Identity#274]
I have added a property : Guid apiKey{get;set;}

If the user use this, they can test the api quickly with it (eg. the-url.com/Test/Weights?apiKey={Guid} and they should be authenticated.

I currently have this as AuthorizationHandler, but it doesn't work:

    using (Models.ApplicationDbContext db = new Models.ApplicationDbContext())
            {
                // ... your authentication logic here ...
                Guid key = Guid.Parse(apiKey);
                var user = db.Users.Where(el => el.apiKey == key ).FirstOrDefault();
                if (user != null)
                {
           
                    // await SignIn(user, isPersistent: false);
                    var usernameClaim = new Claim(ClaimTypes.Name, user.UserName);
                    var identity = new ClaimsIdentity(new[] { usernameClaim }, "apiKey");
                    var principal = new ClaimsPrincipal(identity);

                    Thread.CurrentPrincipal = principal;

                }
            }

How come? I suppose the above isn't used for Owin? (i'm using default individual login in an Asp.Net Web Api project)

**Comment by rustd** [comment]
This is not related to identity.
