### ISSUE TITLE
Consider splitting validators into multiple validators

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#278]
now that we support multiple validators, consider splitting the current validators into more than one validator as appropriate, for example could pull the UniqueEmail validation out of UserValidator and into a seperate stand alone validator, which would let us remove the Option flag for it as well

**Comment by rustd** [comment]
Split the user validator into multiple ones.

**Comment by rustd** [comment]
@HaoK will this happen for Beta8?

**Comment by HaoK** [comment]
This is a nice to have and not really sure this is the right thing to do.  Moving to 1.0.0 backlog is probably best
