### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by thdotnet** [aspnet/Identity#292]
I'm trying to confirm an email account, but I'm getting the error "Invalid Token".

I'm gerenating the confirmation token using the following code:

var code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                        var callbackUrl = Url.Action("ConfirmacaoEmail", "Usuario", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);

```
                    await UserManager.SendEmailAsync(user.Id, "Ativação de Conta", user.GetEmailAtivacao(model.Nome, callbackUrl));

                    ViewBag.Link = callbackUrl;
                    return View("ExibicaoEmail");
```

As I'm testing, I've copied the callbackUrl and pasted in another tab. To confirm the token, I'm using the following code:

var resultConfirmacaoEmail = await UserManager.ConfirmEmailAsync(identityUser.Id, model.Code);

It seems to be a encode/decode problem, but I've already tested with and without encode the confirmation code and it still not working and I don't know what to do.

Here the link:

<a href="http://localhost:58053/Usuario/ConfirmacaoEmail?userId=0bc06d5c-dad2-4017-ac7c-e24011398a1f&amp;code=HSLVy54VW3%2FZOEBGeme3%2FF4IyTS1gbixTVejbxdKrsMZ3E3QFVomMS7rOkLsgqfRo%2BSTf8fbBib9h9CK4tTsXNoq5ffD3hn%2BULIWvmUWORcVrZLFIT0OQ6AWuQ8bIWIlXC%2BqyrHJE3atF15T8Rmtnymjqa2lHUXxmT122E6Q564axhN0SR3XCFG2uYXZkM8%2F">link</a>

I've tried confirmation code as:

HSLVy54VW3/ZOEBGeme3/F4IyTS1gbixTVejbxdKrsMZ3E3QFVomMS7rOkLsgqfRo+STf8fbBib9h9CK4tTsXNoq5ffD3hn+ULIWvmUWORcVrZLFIT0OQ6AWuQ8bIWIlXC+qyrHJE3atF15T8Rmtnymjqa2lHUXxmT122E6Q564axhN0SR3XCFG2uYXZkM8/

and 

HSLVy54VW3%2FZOEBGeme3%2FF4IyTS1gbixTVejbxdKrsMZ3E3QFVomMS7rOkLsgqfRo%2BSTf8fbBib9h9CK4tTsXNoq5ffD3hn%2BULIWvmUWORcVrZLFIT0OQ6AWuQ8bIWIlXC%2BqyrHJE3atF15T8Rmtnymjqa2lHUXxmT122E6Q564axhN0SR3XCFG2uYXZkM8%2F

both return the same error: "Invalid Token". Any clues?

**Comment by PTRPlay** [comment]
I've got the same problem, has anyone figured our  something?
