### ISSUE TITLE
Changing Tables name

### ISSUE THREAD

**Issue by Shahrooze** [aspnet/Identity#300]
I want to change Identity table name with this code:
      

         builder.Entity<ApplicationUser>(b =>
            {
                b.Key(u => u.Id);
                b.ForRelational().Table("Users");
            });
            builder.Entity<IdentityRole>(b =>
            {
                b.Key(r => r.Id);
                b.ForRelational().Table("Roles");
            });

            builder.Entity<IdentityUserClaim>(b =>
            {
                b.Key(uc => uc.Id);
                b.ManyToOne<ApplicationUser>().ForeignKey(uc => uc.UserId);
                b.ForRelational().Table("UserClaims");
            });

            builder.Entity<IdentityRoleClaim>(b =>
            {
                b.Key(rc => rc.Id);
                b.ManyToOne<IdentityUserRole>().ForeignKey(rc => rc.RoleId);
                b.ForRelational().Table("RoleClaims");
            });

            builder.Entity<IdentityUserRole>(b =>
            {
                b.Key(r => new { r.UserId, r.RoleId });
                b.ForRelational().Table("UserRoles");
            });

            builder.Entity<IdentityUserLogin>(b =>
            {
                b.Key(l => new { l.LoginProvider, l.ProviderKey });
                b.ManyToOne<ApplicationUser>().ForeignKey(uc => uc.UserId);
                b.ForRelational().Table("UserLogins");
            });
But this code not work for me when generate migration:
   
                builder.Entity("Microsoft.AspNet.Identity.IdentityRole", b =>
                    {
                        b.Property<string>("Id");
                        b.Property<string>("Name");
                        b.Key("Id");
                        b.ForRelational().Table("Roles");
                    });
                
                builder.Entity("Microsoft.AspNet.Identity.IdentityRoleClaim", b =>
                    {
                        b.Property<string>("ClaimType");
                        b.Property<string>("ClaimValue");
                        b.Property<int>("Id")
                            .GenerateValuesOnAdd();
                        b.Property<string>("RoleId");
                        b.Key("Id");
                        b.ForRelational().Table("RoleClaims");
                    });
                
                builder.Entity("Microsoft.AspNet.Identity.IdentityRoleClaim`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]", b =>
                    {
                        b.Property<string>("ClaimType");
                        b.Property<string>("ClaimValue");
                        b.Property<int>("Id")
                            .GenerateValuesOnAdd();
                        b.Property<int>("RoleId");
                        b.Key("Id");
                        b.ForRelational().Table("AspNetRoleClaims");
                    });
                
                builder.Entity("Microsoft.AspNet.Identity.IdentityUserClaim", b =>
                    {
                        b.Property<string>("ClaimType");
                        b.Property<string>("ClaimValue");
                        b.Property<int>("Id")
                            .GenerateValuesOnAdd();
                        b.Property<string>("UserId");
                        b.Key("Id");
                        b.ForRelational().Table("UserClaims");
                    });
                
                builder.Entity("Microsoft.AspNet.Identity.IdentityUserClaim`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]", b =>
                    {
                        b.Property<string>("ClaimType");
                        b.Property<string>("ClaimValue");
                        b.Property<int>("Id")
                            .GenerateValuesOnAdd();
                        b.Property<int>("UserId");
                        b.Key("Id");
                        b.ForRelational().Table("AspNetUserClaims");
                    });
                
                builder.Entity("Microsoft.AspNet.Identity.IdentityUserLogin", b =>
                    {
                        b.Property<string>("LoginProvider");
                        b.Property<string>("ProviderDisplayName");
                        b.Property<string>("ProviderKey");
                        b.Property<string>("UserId");
                        b.Key("LoginProvider", "ProviderKey");
                        b.ForRelational().Table("UserLogins");
                    });
                
                builder.Entity("Microsoft.AspNet.Identity.IdentityUserLogin`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]", b =>
                    {
                        b.Property<string>("LoginProvider");
                        b.Property<string>("ProviderDisplayName");
                        b.Property<string>("ProviderKey");
                        b.Property<int>("UserId");
                        b.Key("LoginProvider", "ProviderKey");
                        b.ForRelational().Table("AspNetUserLogins");
                    });
                
                builder.Entity("Microsoft.AspNet.Identity.IdentityUserRole", b =>
                    {
                        b.Property<string>("RoleId");
                        b.Property<string>("RoleIdKey");
                        b.Property<string>("UserId");
                        b.Key("UserId", "RoleId");
                        b.ForRelational().Table("UserRoles");
                    });
                
                builder.Entity("Microsoft.AspNet.Identity.IdentityUserRole`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]", b =>
                    {
                        b.Property<int>("RoleId");
                        b.Property<int>("UserId");
                        b.Key("UserId", "RoleId");
                        b.ForRelational().Table("AspNetUserRoles");
                    });
What is my problem?

**Comment by rustd** [comment]
Please reopen if this is still an issue.

**Comment by Bartmax** [comment]
While removing AspNet prefix as @Kukkimonsuta suggested does work, I'm wondering why doing for every entity in a single line create 2 tables.

For example:
```
builder.Entity<IdentityRoleClaim>().ForRelational().Table("NewRoleClaim");
```


creates 2 tables: NewRoleClaim and AspnetRoleClaims.

why?
