### ISSUE TITLE
Consider removing dependency on Microsoft.AspNet.Http and related dependencies

### ISSUE THREAD

**Issue by Kukkimonsuta** [aspnet/Identity#302]
For larger projects I'm often forced to create single purpose command line tools to which one might have to sign in with user/administrator account. This is currently awkward since all the security checks like `CanSignInAsync ` are within `SignInManager` and the whole thing is dependent on the http stack. I'd like to see the library split into two, one specific to http and one that contains just the core logic behind authenticating and locking out users.

**Comment by rustd** [comment]
ASP.NET Identity is targeted at ASP.NET web scenarios only.
