### ISSUE TITLE
avoid simultaneous login from same account

### ISSUE THREAD

**Issue by thdotnet** [aspnet/Identity#308]
I was searching but I could not find one answer to this question: does aspnet identity provide one way to avoid simultaneous login from the same account?

**Comment by suhasj** [comment]
Not out of the box but it can be implemented by the user. Refer to the sample [here](https://aspnet.codeplex.com/SourceControl/latest#Samples/Identity/SingleSignOutSample/). This sample maintains all the clients that are logged in and the single sign out feature lets users sign out from all clients with a single click. You can tweak to not allow users to log in when they are already logged in from one client

**Comment by suhasj** [comment]
Let me know if caters to your requirement and I can close out this bug

**Comment by thdotnet** [comment]
I'll take a look, but you can close this issue. Thank you!
