### ISSUE TITLE
TwoFactorSignInAsync Ignoring CookieAuthenticationOptions

### ISSUE THREAD

**Issue by BennyM** [aspnet/Identity#309]
I have run into some inconsistencies with TwoFactor support. Using the 'remember me' function leads to different behaviour depending on where you hook into the API. I'm able to reproduce this issue in the provided sample.

1. Setup the ASP.NET Identity Sample.
2. In Startup.Auth replace the line 
`app.UseTwoFactorRememberBrowserCookie(DefaultAuthenticationTypes.TwoFactorRememberBrowserCookie)` 
with

 ```c#
CookieAuthenticationOptions cookieAuthenticationOptions = new CookieAuthenticationOptions();
    cookieAuthenticationOptions.AuthenticationType = DefaultAuthenticationTypes.TwoFactorRememberBrowserCookie;
    cookieAuthenticationOptions.AuthenticationMode = Microsoft.Owin.Security.AuthenticationMode.Passive;
    cookieAuthenticationOptions.CookieName = ".AspNet." + DefaultAuthenticationTypes.TwoFactorRememberBrowserCookie;
    cookieAuthenticationOptions.ExpireTimeSpan = TimeSpan.FromDays(30);
    cookieAuthenticationOptions.SlidingExpiration = false;
    CookieAuthenticationExtensions.UseCookieAuthentication(app, cookieAuthenticationOptions);
```
3. Using this configuration I would assume that when I choose the 'Remember me' option, the two factor cookie would be stored for 30 days. Yet this does not occur when I use the normal login procedure.

In the following screenshots you can see the behaviour. 

First I log into the system.

![1](https://cloud.githubusercontent.com/assets/584287/5614124/f4451ebc-94ed-11e4-9341-8462603dda83.PNG)

Then I'm prompted for my 2nd factor.

![2](https://cloud.githubusercontent.com/assets/584287/5614131/06f6c394-94ee-11e4-848c-960573fecf07.PNG)

I enter my 2nd factor and clearly indicate I want it to be remembered.

![3](https://cloud.githubusercontent.com/assets/584287/5614514/41d3ad5c-94f2-11e4-8715-0ac0af1d91b3.PNG)

After the token is validated, I'm logged into the system. Yet the TwoFactorRememberBrowser cookie is a session cookie. Not one with an expiration date as I've configued in Startup.Auth.

Only when I navigate to manage and click on 'Forget Browser' and then on 'Remember Browser' I get a cookie configured the way I want.

![4](https://cloud.githubusercontent.com/assets/584287/5614523/5affbe38-94f2-11e4-9773-1698e97873bd.PNG)

I've traced it down to the SignInManager where the implementation of 'SignInAsync' causes the different behaviour. Is there a valid reason for the code to behave like this?
 
The last bulletpoint in the sample also states that it should behave the way I expect:
>If the machine you are browsing this website is your own machine, you can choose to check the "Remember Me" option after you enter the code. This option will remember you forever on this machine and will not ask you for the two-factor authentication, the next time when you login to the website. You can change your "Remember Me" settings for two-factor authentication in the Manage page.

**Comment by HaoK** [comment]
So the behavior you are looking for should be part of:

```
        public virtual async Task<SignInResult> TwoFactorSignInAsync(string provider, string code, bool isPersistent, bool rememberClient, CancellationToken cancellationToken = default(CancellationToken))

```

This should store the two factor remember me cookie when true.  SignInAsync should only ever affect the application cookie (remember me for login cookie).  Can you clarify where you think the issue is?  Its certainly possible there's a bug here

**Comment by BennyM** [comment]
I tried some more different scenarios and now realize the issue I reported is not entirely the problem I'm facing. When configuring the two factor remember me cookie as posted above and modifying the sample like so:

` var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, false, shouldLockout: false);`

So passwordsignin is never remembered. And:

`var result = await SignInManager.TwoFactorSignInAsync(model.Provider, model.Code, isPersistent: true, rememberBrowser: true);`

So two factor remember me cookie should be stored. 

Both cookies get an expire date:

![capture](https://cloud.githubusercontent.com/assets/584287/5635126/62d886e0-95e6-11e4-82b8-6d2d1894d728.JPG)

I would think the expected behavior would be an application cookie configured as a session cookie and a two factor remember cookie with an expire time. 

I'm using the sample on NuGet so not entirely sure if I should post here or on Codeplex.

**Comment by HaoK** [comment]
Can you reopen this on codeplex if this is a 2.0 issue?

**Comment by kerrpeter** [comment]
Was this ever fixed  - I get the same issue on Asp.net identity 2.2.1

**Comment by BennyM** [comment]
I did not report it on codeplex, but someone else did: https://aspnetidentity.codeplex.com/workitem/2532

**Comment by DeluxZ** [comment]
@HaoK I'm also running into this issue as reported [here](https://aspnetidentity.codeplex.com/workitem/2532)
