### ISSUE TITLE
Port samples from codeplex that were written for 2.0

### ISSUE THREAD

**Issue by rustd** [aspnet/Identity#311]

**Comment by HaoK** [comment]
Moving to RC

**Comment by HaoK** [comment]
:trollface:

**Comment by blowdart** [comment]
Damnit

**Comment by HaoK** [comment]
The docs for the custom providers is referencing these too unfortunately, so as part of https://github.com/aspnet/Docs/issues/1162#issuecomment-261172896 we probably need to do this as well...  :/
