### ISSUE TITLE
EmailTokenProviderOptions.Name is from a resource

### ISSUE THREAD

**Issue by blowdart** [aspnet/Identity#318]
Its used for the data protector name  It shouldn't be regionalized :) Switch to string?

**Comment by HaoK** [comment]
Actually not, this is actually the two factor token provider name, so it shows up in the dropdown as "Email" or "PhoneNumber" in the app itself today.

**Comment by HaoK** [comment]
Only the DataProtectionTokenProvider is used for the DPAPI name, all of these guys are IUserTokenProviders but they are used differently.  TwoFactor show up in a drop down.  The DPTP is used as the UserTokenProvider which is used with a specific purpose for the ResetPassword/EmailConfirmation methods (but that name isn't localized cuz we don't expose it in the app)

Confused yet? :)

**Comment by blowdart** [comment]
Oh! OK. Change of issue then - rename to DisplayName...

**Comment by HaoK** [comment]
It's both. Name is used as a unique id for the framework. It's only the template that uses it as a display name. From the framework perspective it's more of an id.

On Jan 10, 2015, at 12:23 PM, "Barry Dorrans" <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh! OK. Change of issue then - rename to DisplayName...

-

**Comment by blowdart** [comment]
Single responsibility darn it!

Separate them out?

**Comment by HaoK** [comment]
That's mostly a template change then as opposed to framework

On Jan 10, 2015, at 1:11 PM, "Barry Dorrans" <notifications@github.com<mailto:notifications@github.com>> wrote:


Single responsibility darn it!

Separate them out?

-

**Comment by blowdart** [comment]
We should look at that when you get back then :)

**Comment by HaoK** [comment]
Hardcoded to "Email", feel free to open another bug if you want to track the templates issue
