### ISSUE TITLE
PasswordHasherOptions isn't registered properly via DI

### ISSUE THREAD

**Issue by egorpavlikhin** [aspnet/Identity#319]
services.AddOptions(identityConfig) cannot find PasswordHasherOptions as they are not part of IdentityOptions or anything discoverable.

    'Microsoft.Framework.OptionsModel.OptionsManager`1' is waiting for the following dependencies:
    - Service 'System.Collections.Generic.IEnumerable`1[[Microsoft.Framework.OptionsModel.IConfigureOptions`1[[Microsoft.AspNet.Identity.PasswordHasherOptions, Microsoft.AspNet.Identity, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Framework.OptionsModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' which was not registered.

**Comment by HaoK** [comment]
Can you include more of the repro which triggered this error?  Can you show entire method that's configuring your service collection?

**Comment by egorpavlikhin** [comment]
Maybe it works with default DI container, I am using a custom Castle.Windsor container. All in all the problem is fixed simply by adding  

    services.Configure<PasswordHasherOptions>(options =>
                {
                });

Services registration method:

    app.UseServices(services => {
                // Add EF services to the services container.
                services
                    .AddEntityFramework(Configuration)
                    .AddSqlServer()
                    .AddDbContext<ApplicationDbContext>();

                // !! This fixes the problem described !!
                services.Configure<PasswordHasherOptions>(options =>
                {
                });

                // Add Identity services to the services container.
                services
                    .AddIdentity<ApplicationUser, IdentityRole>(Configuration)
                    .AddEntityFrameworkStores<ApplicationDbContext>()
                    .AddDefaultTokenProviders();

                // Add MVC services to the services container.
                services
                    .AddMvc();

                container.Populate(services);

                container.BeginScope();

                return container.Resolve<IServiceProvider>();
            });

**Comment by HaoK** [comment]
Closing unless we can get a repro, options don't need to be registered in DI, only the IOptions itself which is done via services.AddOptions() or using any framework which does this for you (AddIdentity/AddMvc)

**Comment by egorpavlikhin** [comment]
It is hard to get a repro, since it requires a different DI container to be shown, but services.AddOptions(); isn't enough, PasswordHasherOptions do not get registered. If I have time I will create a repro project.

**Comment by egorpavlikhin** [comment]
Ok, here is a repro https://github.com/egorpavlikhin/IdentityIssue319

**Comment by egorpavlikhin** [comment]
@HaoK please have a look at the repro project, when you get a chance.

**Comment by HaoK** [comment]
So it looks like you are doing your own DI here, could it be an issue with your implementation behaving differently from the rest in how it tries to resolve IEnumerable of a generic type?  Basically Options is just querying DI `IEnumerable<ConfigureOptions<TOptions>>`.  Nothing is registered by default for this, it should just return an empty enumerable by default.

**Comment by egorpavlikhin** [comment]
This container passes all DI unit tests though. Do you think this should be added as a test case or each option should be registered explicitly with the container?

**Comment by HaoK** [comment]
I'm not sure, but perhaps these lines might be the issue? 

What does the HasComponent check do?   https://github.com/egorpavlikhin/IdentityIssue319/blob/master/WindsorRegistration.cs#L108

**Comment by divega** [comment]
> Do you think this should be added as a test case ...?

Sounds like a good idea (although other things maybe missing this shouldn't hurt). @HaoK can you take care of it?

**Comment by egorpavlikhin** [comment]
@HaoK if a type is not registered within the container Windsor will not resolve IEnumerable, that's just how it works. Autofac works differently, but I don't think it is right to assume that every DI implementation returns empty Enumerable for unregistered types.

**Comment by HaoK** [comment]
@davidfowl @lodejard I'm pretty sure K assumes that all DI implementations will return an empty IEnumerable<T> when requested.  Can you guys confirm?  Certainly options is built on this assumption, and if the DI implementations throws an exception saying T is not registered, that is the DI implementation not living up to the implicit contract.  I can certainly add a unit test in DI verifying that asking for an IEnumerable of another generic type doesn't blow up once we have consensus.

**Comment by rustd** [comment]
The DI implementation has to return empty IEnumerable
