### ISSUE TITLE
Will IUser, IRole & co. interfaces be supported in vnext?

### ISSUE THREAD

**Issue by ilmax** [aspnet/Identity#324]
In current stable version of asp.net identity [2.1.0 at time of writing](http://www.nuget.org/packages/Microsoft.AspNet.Identity.Core/2.1.0) there are IUser, IUser<TKey>, IRole and IRole<TKey> interfaces, I found those interfaces useful in past projects so I would like to know if those interfaces will be supported by asp.net identity vnext

**Comment by HaoK** [comment]
No, IUser and IRole are gone, and the methods are now part of the IUser/RoleStores

**Comment by divega** [comment]
@ilmax It would be good for us to learn if the new model works for you or if there is something that you think was more useful about the interfaces we had before.

**Comment by ilmax** [comment]
@divega those interfaces can be useful when you want to change the shape of user or role in your db for example. I can obviously live without, but they can be a nice addition to aspnet Identity
