### ISSUE TITLE
Login.cshtml should check ViewBag.LoginProviders for null first

### ISSUE THREAD

**Issue by egorpavlikhin** [aspnet/Identity#336]
https://github.com/aspnet/Identity/blob/c9d27e27e6dd6c15b4228de6e5de3c1a22c15a6d/samples/IdentitySample.Mvc/Views/Account/Login.cshtml#L63

There should be a check for null first.

**Comment by lpaluszk** [comment]
It's not needed. 

I believe that even without elements the result would be: System.Linq.Enumerable.WhereListIterator<AuthenticationDescription>

This doesn't really matter though as ToList() method will definitely turn it into an empty list:
https://github.com/aspnet/Identity/blob/c9d27e27e6dd6c15b4228de6e5de3c1a22c15a6d/samples/IdentitySample.Mvc/Controllers/AccountController.cs#L31

Also, see this:
http://stackoverflow.com/questions/1191919/what-does-linq-return-when-the-results-are-empty

**Comment by egorpavlikhin** [comment]
Strange, because right now it does end up being null.

**Comment by rustd** [comment]
@egorpavlikhin can you please send us repro steps on how are you getting a null value?

**Comment by rustd** [comment]
Closing this one as there was no response.
