### ISSUE TITLE
Please stop exposing IQueryable

### ISSUE THREAD

**Issue by ilmax** [aspnet/Identity#338]
I consider a bad practice to expose IQueryable from Repository/Store, this is often source of bugs.

For example one common bug exposing IQueryable and using the EF's QueryableProvider is getting an ObjectDisposedException if you didn't enumerate your query before of the context disposal.

Proven that IMHO this is a bad practice (but there are tons of great [articles](http://blog.ploeh.dk/2012/03/26/IQueryableTisTightCoupling/) around), this also makes replace the default User/Role-Store with a custom one more fragile (since we may rely on the QueryableProvider capabilities of the chosen storage mechanism).

At this point I suggest to remove ```IQueryableRoleStore<TRole>``` and ```IQueryableUserStore<TUser>``` interfaces and ```IQueryable<TUser> Users``` and ```IQueryable<TRole> Roles``` properties.

**Comment by HaoK** [comment]
Custom stores are not required to implement this interface, if they don't implement the Queryable interface, the managers will throw not supported exceptions if you try and use the properties.  We were aware that there was disagreement over IQueryable early on, and this was the compromise we eventually chose since our default EF provider already supports this natively, and custom stores can opt out easily.

**Comment by rustd** [comment]
@divega @tugberkugurlu The proposal is to remove IQueryable. What do you think?

**Comment by jusbuc2k** [comment]
What benefit does having the interfaces support IQueryable if different implementations can choose to not implement them by throwing? Wouldn't it better that if a specific implementation wants to provide IQueryable's that said implementation provides those via a singleton or something? e.g. SpecificUserStore.Current.GetQueryableUsersOrWhatNot()

**Comment by divega** [comment]
My take is that we should remove the IQueryable escape hatch interface in Identity 3.0. I will stay away from the debate on whether exposing IQueryables on repository-like abstractions is a bad practice and focus on a different aspect: 

If an application takes a dependency on the ability to issue arbitrary queries against the data store underlying Identity, it will most likely better off doing so by accessing directly the data stack in question and without any false claim of abstraction. E.g. in the typical ASP.NET 5 application it should be super easy to  get to the IdentityDbContext for the request using DI. Using the context directly will result in much cleaner code and more flexibility. 

If on the other hand there were specific gaps on the query capabilities required to implement common  scenarios we want to support in Identity, those would be better addressed by adding specific methods on the Identity classes in such way that all possible store providers can easily support. IQueryable is not a great solution for that.

**Comment by ilmax** [comment]
@divega agree, aside from IQueryable debate, exposing access to underlying provider makes the abstraction weak.

**Comment by tugberkugurlu** [comment]
I am also not a fan of exposing `IQueryable` but I can understand the desire and @divega is right about issuing some search queries for that reason even if that's not an elegant solution. The other question would be whether you would use the same data storage system for the search as well. It depends on the volume of data but removing `IQueryable` would also make that distinction which I would like.

**Comment by rustd** [comment]
We are not doing this. Admin scenarios need this.

**Comment by divega** [comment]
Just to add some detail: we looked at the possibility of adding a separate "repository" interface that could be used to implement similar admin scenarios without bringing all objects into memory but sacrificing some of the query flexibility that IQueryable can express. All in all we couldn't come up with something that looked compelling enough, so at least for now, stores that want to enable rich admin scenarios (e.g. from third party tools) will have to expose IQueryable in some way.
