### ISSUE TITLE
Problems resolving references in VS2015 CTP5 IdentitySample but still builds...

### ISSUE THREAD

**Issue by WillBaldwin** [aspnet/Identity#342]
Does anyone know how to fix my situation?
  
I can build the IdentitySample.Mvc with 0 Warnings and 0 Errors but Intellesense and VS editor in general can't seem to resolve any of the Nuget packages or even "using System".  EntityFramework7 samples have the same behavior in fact all nightly builds seem to have this behavior.  I am certain there is a switch or something that I need to flip to get VS2015 to behave....

![screenshot](https://cloud.githubusercontent.com/assets/5522137/5958730/68b121c2-a78d-11e4-8377-2fb8d930c93a.png)

**Comment by suhasj** [comment]
Can you show me the feeds configured for the project ?

**Comment by rustd** [comment]
Closing as this is not an Identity issue. You can open issues for Visual Studio on the Connect site.
