### ISSUE TITLE
Make SignInManager and UserManager more unit-testable

### ISSUE THREAD

**Issue by ianhong** [aspnet/Identity#344]
I tried to write unit tests for MusicStore. Many of controllers in MusicStore use SignInManager and UserManager, but it wasn't easy to mock them. I think we could make  SignInManager and UserManager more unit-testable. For example, providing the default constructor, or making them use interfaces. 

Thanks,

**Comment by HaoK** [comment]
The idea is that you mock the store and use the managers directly in your tests.  You shouldn't need to swap out the managers.

**Comment by ianhong** [comment]
@Haok I'm creating unit tests for MusicStore controllers, and do you have any samples to mock the store??

**Comment by HaoK** [comment]
Depending on your tests, you can just do something like use a in memory store for identity, you can lift this https://github.com/aspnet/Identity/tree/dev/test/Microsoft.AspNet.Identity.InMemory.Test, or you can mock line by line which is a bit painful: https://github.com/aspnet/Identity/blob/dev/test/Microsoft.AspNet.Identity.Test/SignInManagerTest.cs

**Comment by rustd** [comment]
Please reopen this issue if you think there is a bug that we should fix.

**Comment by hannmtz85** [comment]
```c#
public class FakeUserManager : UserManager<User>
    {
        public FakeUserManager() 
            : base(new Mock<IUserStore<User>>().Object,
                  new Mock<IOptions<IdentityOptions>>().Object,
                  new Mock<IPasswordHasher<User>>().Object,
                  new IUserValidator<User>[0],
                  new IPasswordValidator<User>[0],
                  new Mock<ILookupNormalizer>().Object, 
                  new Mock<IdentityErrorDescriber>().Object,
                  new Mock<IServiceProvider>().Object,
                  new Mock<ILogger<UserManager<User>>>().Object, 
                  new Mock<IHttpContextAccessor>().Object)
        { }

        public override Task<User> FindByEmailAsync(string email)
        {
            return Task.FromResult(new User{Email = email});
        }

        public override Task<bool> IsEmailConfirmedAsync(User user)
        {
            return Task.FromResult(user.Email == "test@test.com");
        }

        public override Task<string> GeneratePasswordResetTokenAsync(User user)
        {
            return Task.FromResult("---------------");
        }
    }
```

**Comment by jholovacs** [comment]
Isn't that a bit ridiculous to mock what should be a simple interface?  There should be an `IUserManager<TUser>` that `UserManager<TUser>` implements, instead of going umpteen levels deep into mocking hell.  Nobody is trying to test the functionality of the `UserManager`, we should definitely not be instantiating this class to run unit tests.
