### ISSUE TITLE
Provide an overload of SignInManager.SignOut taking an authType

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Identity#361]
Currently when I say SignOut it specifically signs out the cookie middlewares that Identity wired up. 

https://github.com/aspnet/Identity/blob/597e2b3153936313c769ac6c22f7059bc684481b/src/Microsoft.AspNet.Identity/SignInManager.cs#L87

When I use OpenIdConnect with identity, to sign out from OpenIdConnect I ended up doing a 

````
Response.SignOut("OpenIdConnect");
```

as in https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/Controllers/AccountController.cs#L442

**Comment by HaoK** [comment]
This is sort of by design honestly, Identity is primarily concerned with only the main application cookie.  To sign out other auth types, Response.SignOut("authType)" is correct.  That said, we can add an overload that just routes it through as well.

**Comment by Praburaj** [comment]
Having an overload will help using a familiar API for all signin/signout needs - as templates will use this. I  remember we had this in Identity 2.0 so I thought it will be useful.

**Comment by HaoK** [comment]
Can revisit if we get more requests, don't really want to expose duplicate Security Authentication APIs
