### ISSUE TITLE
Remove roles. 

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Identity#365]
Right now we have roles table and claims table where can contains roles. That's nonsense. 

I suggest to get away with the role concept on the core and stores and still make it available on the Api, so when I do user.isinrole("test") we check the claim of type role. (We are doing this already) and when we do user.addtorole("test") we create a claim of type role (this ain't happening right now). 

With this we can remove the roles tables and use only claims. This role specific methods/idea being implemented as an extension of the claims system we can then add other extensions like example: isUserFromFacebook or any claim type, the same we do isUserInRole and have any specific implementation for developer needs. The introduction of claims to developers as roles is also great for learning and entry point because developers would be already managing claims without the need to understand what's a claim. 

We also create a lot of simplicity by only handling claims by removing the roles and rolestore. 

I guess this has been suggested many time but couldn't find it, so maybe I'm guessing wrong.

**Comment by brockallen** [comment]
This has been suggested before. Perhaps ASP.NET Identity v3 would be the right version to re-consider this?

**Comment by Bartmax** [comment]
@brockallen agree. This is definitely right for v3.

**Comment by rustd** [comment]
We are not doing this for v3
