### ISSUE TITLE
IdentityUser.Claims and IdentityUser.Roles does not support set accessor methods

### ISSUE THREAD

**Issue by WillBaldwin** [aspnet/Identity#366]
I have been curious why IdentityUser objects returned by UserManager.FindByIdAsync() don't have roles or claims populated.  Looking in to the IdentityUser class it appears as if there is no possible way to populate claims or roles because set accessor methods do not exist, and the values for roles and claims can not be set by the constructor or seemingly any other function thus, UserManager.FindByIdAsync() can't possibly populate the roles and claims.
```javascript
IdentityUser identityUser
     = await UserManager.FindByIdAsync(id, cancellationToken: Context.RequestAborted);
```

**Comment by rustd** [comment]
You can use the Identity APIs to get roles, claims for the user. You can also use the Add/ Update APIs on the User/Role Manager to set the claims and roles

**Comment by WillBaldwin** [comment]
Agreed I can use the Identity APIs APIs on the User/Role Manager to set the claims and roles but I can not seem to use Identity APIs to enumerate claims or roles (roles may become depreciated).  Furthermore there appears to be no HasClaim() method that would allow efficient authorizations. 

My current workaround is to bypass Identity Framework and get at claims through Entity Framework, i.e. non-ideal.

**Comment by HaoK** [comment]
UserManager.GetUserClaims/Roles?  For AuthZ you should be looking the HttpContext.User ClaimsPrincipal to do claims checks vs that, not hitting the database/user on every request.

**Comment by WillBaldwin** [comment]
I knew there was a better way!  I'll look into that and report back.

**Comment by WillBaldwin** [comment]
@HaoK Suppose I have a DynamicMenuViewComponant that is included in the _Layout.cshtml so it is rendered for every HTTP response.  Suppose the DynamicMenuViewComponant.InvokeAsync() looks like the following.  I need the get the claims of the current user for building a dynamic menu that only renders menu items the user has claims for.  This seems very inefficient because it will call FindByIdAsync() and GetClaimsAsync() for each and every render unless you tell me that IdentityFramework has magic caching implemented to make this efficient.  NOTE:  User.Identity.GetUserName() is used because the application uses windows Kerberos authentication.
 
What do you think?  Is there a better way?

```javascript
public async Task<IViewComponentResult> InvokeAsync()
        {
            ApplicationUser applicationUser
                = await _userManager.FindByIdAsync(User.Identity.GetUserName(), cancellationToken: Context.RequestAborted);
            IList<Claim> claims 
                = await _userManager.GetClaimsAsync(applicationUser, cancellationToken: Context.RequestAborted);
            return View(claims);
        }
```
