### ISSUE TITLE
Add concurrency token to UserLogin and UseClaims class 

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#369]
Should we be adding concurrency token for them as well ?

**Comment by HaoK** [comment]
No, only makes sense on the top level entities

**Comment by divega** [comment]
@HaoK do we increment the version if changes happen on the non-top level entities?

**Comment by HaoK** [comment]
Yep, there's no way to save the lower level entities via identity, you can only update/create users/roles

**Comment by divega** [comment]
Makes sense. Thanks.
