### ISSUE TITLE
Add normalized fields as indexes 

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#370]
The normalized fields in IdentityUser and IdentityRole should be set as indices in IdentityDbContext to get the expected perf results.

**Comment by suhasj** [comment]
String indexes need to have fixed length. Waiting for https://github.com/aspnet/EntityFramework/issues/882 to set MaxLength on properties

**Comment by rustd** [comment]
@bricelam is Index support happening for Beta5?

**Comment by bricelam** [comment]
@ajcvickers has been working on the type mapping.

**Comment by ajcvickers** [comment]
@suhasj @rustd @divega Setting MaxLength won't make them fixed length. To do that with the current design you would need to set the datatype explicitly. Otherwise on SQL Server you will get nvarchar(x) where x is the max length.

**Comment by bricelam** [comment]
I think he just means it needs to not have `max`. You can definitely put an index on `nvarchar(450)` columns.

**Comment by divega** [comment]
Exactly. Is that coming soon or should we move this one out?

**Comment by ajcvickers** [comment]
It is coming soon.

**Comment by HaoK** [comment]
Is the required EF feature done for this now?

**Comment by bricelam** [comment]
Should be in dev via aspnet/EntityFramework#2300

**Comment by HaoK** [comment]
Cool...  so now the question is should we limit user names and the normalized versions of them to something reasonable like 128 characters so we can add indexes?

@divega @blowdart @rustd

**Comment by blowdart** [comment]
Yes. Even for emails as usernames that's reasonable IMO

**Comment by HaoK** [comment]
Ok look slike we had 256 as the default in Identity 2.0, I'll make the same changes for 3.0

**Comment by HaoK** [comment]
d8b3cf238e3a106ebb3e08b1eb9f5661f997cdc0
