### ISSUE TITLE
UserManager.FindByNameAsync() appears to be bugged in Beta3

### ISSUE THREAD

**Issue by WillBaldwin** [aspnet/Identity#372]
UserManager.FindByNameAsync() appears to be bugged in Beta3 it worked in Beta2 just fine; in Beta3 it always returns null.

**Comment by HaoK** [comment]
Is this with a clean database or did you migrate from Beta2?

**Comment by HaoK** [comment]
We made some schema changes like adding a normlized user name column which is what FindByName uses now, so if your database has a null column for that...yeah it won't work...

**Comment by WillBaldwin** [comment]
I am using a brand spanking new DB built under beta3 with code first.  I have the data there in the column.  I can see it the data in the object when I do a code break.  It just simply fails the comparison.
I am working around the problem at the moment with entity framework so I know the data is good and the strings to compare correctly with entity framework.  It just failed with identity framework.
  
I have also tried using lower and upper Invariants for both the string in the database and the search string without success.

**Comment by WillBaldwin** [comment]
Works
```javascript
List<ApplicationUser> applicationUsers
     = await _db.Users.Where(b => b.UserName == User.Identity.GetUserName()).ToListAsync();
```
Fails
```javascript
ApplicationUser applicationUser
  = await _userManager.FindByNameAsync(User.Identity.GetUserName().ToUpperInvariant(), cancellationToken: Context.RequestAborted);
```
Fails
```javascript
ApplicationUser applicationUser
  = await _userManager.FindByNameAsync(User.Identity.GetUserName(), cancellationToken: Context.RequestAborted);
```

**Comment by WillBaldwin** [comment]
@HaoK   I found the problem and of course it is on my end.  FindByNameAsync is using the new NormalizedUserName field and my (b => b.UserName == User.Identity.GetUserName()) is using the original non-normalized field.  My NormalizedUserName field contained incorrect data and was throwing FindByNameAsync() off.  Closing this issue.
