### ISSUE TITLE
Add mechanism easy disabled/enabled user identity

### ISSUE THREAD

**Issue by mojtabakaviani** [aspnet/Identity#373]
many times need disabled/enabled user to access your profile. but now must customize asp.net identity that support this. please add mechanism easy disabled/enabled user identity to asp.net identity that support this capability as native.

**Comment by rustd** [comment]
@HaoK We will ad a flag in the schema to check for this and block login if the user account is disabled

**Comment by rustd** [comment]
@mojtabakaviani can you please explain on your scenario? Do you only want to block login for disabled users or all actions (reset password etc.)

**Comment by mojtabakaviani** [comment]
thanks! I think just block login will be enough but if admin reset password or other actions automatic enabled.

**Comment by rustd** [comment]
We discussed this more this is app specific scenario which can be enabled by extending the Identity schema and adding a flag to check if the user is disabled or not.

**Comment by mojtabakaviani** [comment]
By the way this is important support specific scenario and not mothods
