### ISSUE TITLE
UserManager.ReplaceClaimAsync() parameters..

### ISSUE THREAD

**Issue by WillBaldwin** [aspnet/Identity#374]
Is there a reason that ReplaceClaimAsync() expects as parameters, System.Security.Claim.Claims rather than IdentityUserClaim?  Converting IdentityUserClaims to  System.Security.Claim.Claims seems messy (not just a simple cast) and somehow I'd expect an Identity Framework function to use Identity Framework centric parameters.

**Comment by HaoK** [comment]
The IdentityUserClaim is a store specific POCO, it doesn't exist at the Identity core layer which knows nothing about what's inside a TUser, the contract is adding/removing Claims for the user.  How the store choses to persist the user's claims is up to the store.  Our EF implementation happens to use the IdentityUserClaim class, but that actually will be moving to the EF assembly soon, to make it clear that its not something generally applicable.

**Comment by HaoK** [comment]
Some more context for you here: https://github.com/aspnet/Identity/issues/332
