### ISSUE TITLE
Please consider two additional methods for UserManager for claims

### ISSUE THREAD

**Issue by WillBaldwin** [aspnet/Identity#375]
I can easily get a enumerated list of claims for a user from the UserManager but when writing a user interface for claims CRUD, I find that the following two methods would be very useful.

Consider adding Bool UserManager.HasClaimAsync()
Consider adding IdentityUserClaim UserManager.GetClaimAsync()  //see below extension

```javascript
public static async Task<IdentityUserClaim> GetClaimAsync(this UserManager<ApplicationUser> usermanager, int claimId, ApplicationDbContext applicationDbContext)
   {
       IdentityUserClaim<string> IdentityUserClaimString
           = await applicationDbContext.UserClaims.SingleAsync(c => c.Id == claimId) ;

       IdentityUserClaim identityUserClaim = new IdentityUserClaim();

       identityUserClaim.Id = IdentityUserClaimString.Id;
       identityUserClaim.ClaimType = IdentityUserClaimString.ClaimType;
       identityUserClaim.ClaimValue = IdentityUserClaimString.ClaimValue;
       identityUserClaim.UserId = IdentityUserClaimString.UserId;

       return (identityUserClaim);
   }

**Comment by HaoK** [comment]
Why are you trying to get the store specific POCO out?  The data inside of it is basically the same as a standard Claim (Type/Value).  

wrt to HasClaim, if you are looking for claims on the logged in user, you can simply do something like:
`Context.User.HasClaim(c => c.Type == "whatever" && c.Vaue == "value");`

If you want it against an arbitrary user, you can still use LINQ .Where against the IEnumerable of claims from GetUserClaims()

**Comment by WillBaldwin** [comment]
Dropping the request for UserManager.HasClaimAsync()
  
On GetClaimAsync()  POCO or not, for my purposes, i.e. in this instance I am managing claims for users other than the logged on user; building a UI to manage the claims another user has within the application.  The properties identityUserClaim.Id and identityUserClaim.UserId are both important.  System.Security.Claims.Claim does not have Id or UserId properties if that is what you refer to.

**Comment by HaoK** [comment]
wrt GetClaimAsync, you can still just display a view listing all of a user's claims (`GetUserClaims(TUser)`).  Once the user has decided which claims to add/remove, you can call Add/RemoveUserClaim() with the claim, and the store will remove/add the appropriate instances.  You still don't need to know about the child entity, that's an implementation detail for the store.  You don't need to drop down to that level, and you probably shouldn't unless you really need to

**Comment by WillBaldwin** [comment]
@HaoK ,
 
I am unsure why I don't need identityUserClaim.Id and identityUserClaim.UserId of a claim.  identityUserClaim.Id is after all, the primary key, identityUserClaim.UserId is the foreign key.  When building MVC for managing a specific claim such as delete, I use the primary key to know which claim to delete.  That follows the pattern for other identity objects, 'users' for example.  

In my App, security is important, and will have a relatively small users base.  The security manager needs to be able to quickly review all assigned claims for all users without having to select each user to see what claims are assigned.  That way the security manager can quickly determine no one has claims they should not.  So I plan to give the security manager user a view enumerating all the claims in the app, again identityUserClaim.Id and identityUserClaim.UserId of each claim will be very important for the edit and delete actions or if the user wants to navigate to the details for the related user.

My app uses windows Kerberos authentication, context.User is the IPrincipal (Windows Identity) for the current logged in user. In my case Context.User doesn't have any (Identity Framework) claims. 

Context.User has the IPrincipal assigned from the windows Kerberos authentication consequently Context.User object does not contain the claims assigned to the matching Microsoft.AspNet.Identity.IdentityUser that are stored using Entity Framework.

Thus:
•Context.User.HasClaim() can not determine authorizations 
•[Authorize("Administrator", "Allow")] attribute on a controller action method to determine authorization at the controller cannot function.

What can I do to get Context.User.HasClaim() and [Authorize("Administrator", "Allow")] to function correctly when using windows Kerberos authentication?

**Comment by rustd** [comment]
@blowdart

**Comment by blowdart** [comment]
@WillBaldwin 

It looks like you're attempting to use AD for auth and then pull in additional claims from an identity database? Is that correct?

This isn't a scenario we've supported for quite a while now. It was fraught with problems and very few, if any implementations got it correct. IdentityUser is meant for forms based authentication, or a smattering of social auth and nothing more.
