### ISSUE TITLE
Allow localizing front-end messages.

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [aspnet/Identity#379]
Hi.

The project uses a resource file for messages. This makes it very easy to add localized versions to the source code. A quick search reveals that some people really like to have the localization option.

I'm not an expert in .net localization, but I guess we have 3 options:
1: Add localized resource files in the same project as the main
2:Create localization assemblies.
3:Allow loose localized resource files.

Which one is the preferred approach?

**Comment by rustd** [comment]
@HaoK can you follow up for the Identity ask. For the Web app, we don't have a localization story yet.

**Comment by AlirezaHaghshenas** [comment]
@rustd @HaoK I guess I can contribute this. But I need to be briefed on your preferred method.

**Comment by HaoK** [comment]
@AlirezaHaghshenas Have you taken a look at the IdentityErrorDescriber service?  That is what you might be able to plug in to localize identity specific application facing errors.

**Comment by AlirezaHaghshenas** [comment]
@HaoK  Ok, I'll give it a try. I'll ask you in case I'm unsure about the approach.

**Comment by AlirezaHaghshenas** [comment]
Which source should I make changes to? The V2.x in CodePlex or V3.x in Github?

**Comment by HaoK** [comment]
Feature only exists in v3 (Github)
