### ISSUE TITLE
Support to logicaly delete users

### ISSUE THREAD

**Issue by lnaie** [aspnet/Identity#380]
Meaning users have to stay to preserve data integrity cross DB, but sign-in will fail in a way the user is not there.

Usecase: user record has been used in various tables and cannot be deleted, but the account should be hidden to outside and user name should be available for registration.

I have checked the code and as it is now shouldn't be too hard to achieve it, although in nuget v2 it's not possible because SignInManager.CanSignInAsync is not public. Possibly evolve the api with that in mind as well.

Thanks

**Comment by rustd** [comment]
@blowdart

**Comment by blowdart** [comment]
We're not going to add this because too many people depend in a user name being unique in their code. It would break too many people's assumptions in a way that leads to security failure.

#373 may be worth following, as it might be asking for a simpler sort of disabling mechanism.
