### ISSUE TITLE
UserManager RemoveClaimsAsync causes "Collection was modified; enumeration operation may not execute."

### ISSUE THREAD

**Issue by fmgppt** [aspnet/Identity#382]
Hello,

The usage scenario I'm going for this error is simple: I want to have custom user claims updated on the database upon login on an external service using the google/facebook/microsoft/etc... providers.

I'm using:
Net Framework v4.5.2
ASP.NET MVC 5 (v5.2.3)
ASP.NET Identity v2.2.0
Owin Security v3.0.1

Using the example and updating both ExternalLoginCallback and ExternalLoginConfirmation methods on the AccountController, I can easily add claims.
The issue I present occurs when trying remove an existing claim in order to add another in its place in an attempt to perform an "update" during the ExternalLoginCallback method for the AccountController.

From what I inspected on the code I figured it's the foreach loop syntax on the UserStore for this method that triggers this error (and noticed this error is also likely to happen on the RoleStore).

Haven't tried any other Remove*Async on this method at this time, however as I peaked into your code I noticed they're likely to suffer from the same issue.

Best regards,

Filipe

**Comment by rustd** [comment]
This is tracked on CodePlex site for Identity

**Comment by gouravd** [comment]
Could you please share the link? I was not able to find it here - https://aspnetidentity.codeplex.com/workitem/list/basic?field=CreationDate&direction=Descending&issuesToDisplay=Open&keywords=&emailSubscribedItemsOnly=false

**Comment by suhasj** [comment]
https://aspnetidentity.codeplex.com/workitem/2509
