### ISSUE TITLE
StartedWeb template picks up windows login (no auth enabled)

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/Identity#383]
Using latest WTE build...
* Create a new project using the starter web template
* Run the app
* You'll see "Welcome [windows username]" in the top bar

This only happen running under IIS (the default), if you swap to using the `web` command then everything works as expected.

Prevents using any other auth (i.e. social) since Identity just always thinks you are logged in.

**Comment by rowanmiller** [comment]
@rustd this is the issue you looked at on my machine yesterday

**Comment by HaoK** [comment]
I probably broke something with my Auth changes :/

**Comment by rustd** [comment]
This is not a runtime issue. Please open a tooling bug

**Comment by rowanmiller** [comment]
Guys this is a lame response :smile:... the default experience with identity is broken (and this is the identity repo), if it's an issue with how VS is launching the app then work with them to fix it :smile_cat:

**Comment by blowdart** [comment]
<pedant>Windows Identity is not ASP.NET identity, and this repo has *nothing* to do with it, as it's a hosting concern.</pedant>

**Comment by rowanmiller** [comment]
But isn't `User.Identity.GetUserName()

**Comment by blowdart** [comment]
That's not this repo, that's actually CoreCLR :D

**Comment by rowanmiller** [comment]
Fundamentally, the issue is I create a project template that should have local accounts enabled... but I can't login/register etc. because it just picks up my windows user

**Comment by blowdart** [comment]
Yes, sounds like a tooling bug :) We can go pick on @madskristensen or @barrytang if you like.

**Comment by rowanmiller** [comment]
BTW just to be clear... I'm not arguing about where the technical fix lies... I'm just saying the default ASP.NET Identity experience is busted. If you need to work with other folks because someone else busted you... then great. Just don't close the issue with a 'not technically our area' response... go open the relevant issues to get it fixed :smile: 

To be clear... I'm not trying to be an ass... I just don't want us to drop things because we're focusing on where technical boundaries lie and not what the experience of using our features is like.

**Comment by blowdart** [comment]
Yea, but you have the repo of the bug, if we go file the issue and mads asks for a repo, I can't give him one :) This is where github lets us down, in that we can't shuffle issues to other repos where they belong.

**Comment by barrytang** [comment]
Can one of you open a issue under Tooling-Internal?

**Comment by divega** [comment]
@barrytang I did a few days back, and it was fixed. Thanks!

**Comment by barrytang** [comment]
Great to hear! Thanks @divega!
