### ISSUE TITLE
Where is the code for UserManagerExtensions?

### ISSUE THREAD

**Issue by japurcell** [aspnet/Identity#389]
Can't seem to find the file containing the extensions for the UserManager as referenced here: https://msdn.microsoft.com/en-us/library/microsoft.aspnet.identity.usermanagerextensions(v=vs.108).aspx.

**Comment by HaoK** [comment]
https://aspnetidentity.codeplex.com/SourceControl/latest#src/Microsoft.AspNet.Identity.Core/Extensions/UserManagerExtensions.cs

**Comment by japurcell** [comment]
Out of curiosity, why isn't it on github?

**Comment by HaoK** [comment]
Because we were using codeplex back in those days

**Comment by HaoK** [comment]
Github is for current Identity 3.0+, Codeplex hosts the older ldentity 2.x code base

**Comment by japurcell** [comment]
Makes sense now; 3.0+ isn't on Nuget yet.
