### ISSUE TITLE
Duplicate queries - Identity and EF Code First

### ISSUE THREAD

**Issue by greerde** [aspnet/Identity#392]
I was using Glimpse to check up on the performance of a few pages in my app (MVC5, EF6 Code First, newest Identity).  

This is a glimpse snapshot from one of my normal pages right now: 

![screen shot 2015-03-08 at 11 52 50 am](https://cloud.githubusercontent.com/assets/1305375/6546826/9479bfec-c599-11e4-9270-ff91f02c7241.png)

An hour or so later, I was back and checking on things again.  However, this time I noticed Glimpse was reporting this: 

![screen shot 2015-03-08 at 1 31 16 pm](https://cloud.githubusercontent.com/assets/1305375/6546831/af52f0f4-c599-11e4-91e2-3d23b787b988.png)

Nothing had changed on the server - no data or code.  Notice the number of queries jumped from 20 to 43.  

A quick look into those queries revealed that there are a bunch of Identity tables being queried multiple times (all duplicates of each other). 

For example, instead of this query getting excited once, it now gets excited about 4 or 5 times: 

![screen_shot_2015-03-08_at_1_31_39_pm](https://cloud.githubusercontent.com/assets/1305375/6546841/1472cc2a-c59a-11e4-9b34-3ec86acced85.png)

Same with this: 

![screen_shot_2015-03-08_at_1_32_11_pm](https://cloud.githubusercontent.com/assets/1305375/6546844/2ee1ed52-c59a-11e4-8a2b-2e5d721af7c6.png)

The AspNetUsers and AspNetUserLogins also gets queried multiple times.  

Browsing ANY page on the site has all of these extra queries, even a completely empty controller and view (with no authentication required).  Once the extra queries are there, they don't seem to go away until a logout. 

If I log out and log back in, I am back to the normal operation.  I was able to repeat this on my production server and development computer - both seem to be triggered by a period of inactivity (session related?).  

Thoughts?

**Comment by divega** [comment]
It seems to me that you are describing this issue: [CodePlex #2508](http://aspnetidentity.codeplex.com/workitem/2508) GetClaimsAsync() invoked on every request after identity was regenerated.

It is an unintended regression we introduced in cookie validation in Identity 2.2. We should be releasing a patch with the fix soon.

**Comment by greerde** [comment]
Is there any update on this?  @suhasj @rustd 

I just updated to the latest and greatest Identity Nuget packages.  I am setting getting very high query counts with most being repeats.

**Comment by greerde** [comment]
@divega

**Comment by HaoK** [comment]
Gitthub is for identity 3+, please dicuss Identity 2.x issues on codeplex

**Comment by rustd** [comment]
This was fixed in ASP.NET Identity 2.2.1 Please make sure you are using the latest version and open an issue on http://aspnetidentity.codeplex.com/ if it still reproes for you
