### ISSUE TITLE
Add string overload of RoleManager<T>.CreateAsync

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/Identity#408]
Small thing... but I would find it useful to have this overload for the app I'm working on. For the most part I can just use the `Name` of the `Role` when working with Identity APIs (`UserManager.IsInRoleAsync`, `RoleManager.RoleExistsAsync`, etc.) but to create a role I need to create an `IdentityRole` instance. It's not 100% clear that you can just create the object and set the `Name` property and ignore the other 3 properties (that get filled in by the stack).

[Code where I would like to use this overload](https://github.com/rowanmiller/UnicornStore/blob/master/UnicornStore.AspNet/src/UnicornStore.AspNet/Models/Identity/IdentityExtensions.cs#L19)

**Comment by HaoK** [comment]
We could only provide this extension method specfically for RoleManager<IdentityRole> as we don't have any constraint in general other than for our default EF role poco

**Comment by rowanmiller** [comment]
BTW I'm totally fine if you decide not to do this... I just wanted it while I was app building, so thought I'd log the request and let you decide what to do with it :)

**Comment by rustd** [comment]
Sorry Rowan this is not critical.

**Comment by rowanmiller** [comment]
No worries, totally up to you guys... just wanted to let you know I would have found it useful :smile:
