### ISSUE TITLE
Make all properties of IdentityRole, User, etc... virtual

### ISSUE THREAD

**Issue by Riva81** [aspnet/Identity#413]
This is simply so that we can extend them further with annotations for example. IdentityUser seems to be implemented like that, IdentityRole also seems to be in github but not in nuget

**Comment by rustd** [comment]
@suhasj can you please check if this is fixed in 2.x and 3.x

**Comment by suhasj** [comment]
I checked that all the properties for IdentityUser and IdentityRole are virtual in 3.0 The name and Id property for IdentityRole is not virtual for 2.0. Porting this bug to codeplex for triage

Please refer https://aspnetidentity.codeplex.com/workitem/2522 for updates

**Comment by Riva81** [comment]
Thanks it looks like v2.0 is dead as there have been no updates ever since.
