### ISSUE TITLE
Avoid repetition of method names in log messages and scopes

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#414]
The method names are repeated in scopes as well as log messages. Revisit them to have a better experience

**Comment by suhasj** [comment]
Piggy backing on this bug for logging changes for beta5

- Intelligent logging
- Using BeginScope with string and parameters if necessary
- Log Information for methods that can be called from Controller class

**Comment by HaoK** [comment]
e80853a4cf665d73e7e5cdcb652d3d51cd456068
