### ISSUE TITLE
Revisit constructor of manager class

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#415]
Tracking bug based on the discussion that we might want to see if the dependencies are to be null or not and whether they are instantiated by default in the constructor

**Comment by HaoK** [comment]
@divega So, thinking about the ctor a bit, I think maybe taking only IServiceProvider might actually be better than the current 8+ arguments, IFF we can supply defaults like we did before for everything other than the IUserStore.

So basically if IUserStore isn't found, we throw saying something like "Its required, maybe you forgot to call AddIdentity().AddEntityFrameworkStores()"

For all other services, we can just supply working defaults like we used to do...

Thoughts?

**Comment by rustd** [comment]
Keep the constructor as it is and throw in app.UseIdentity() that AddIdentity() needs to be defined.

**Comment by HaoK** [comment]
Creating a new bug tracking AddIdentity
