### ISSUE TITLE
Unnecessary call in UserManager

### ISSUE THREAD

**Issue by mw2nukeboy** [aspnet/Identity#417]
At line 716 in the UserManager class on the dev branch, there is an seemingly unnecessary call to the GetSecurityStore method.  It isn't assigned to a variable, so it isn't serving much of a purpose.

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/UserManager.cs#L716

**Comment by HaoK** [comment]
GetSecurityStore throws if the store doesn't support the operation

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/UserManager.cs#L682
