### ISSUE TITLE
Pass in DbContextOptions to /Microsoft.AspNet.Identity.EntityFramework.IdentityDbContext

### ISSUE THREAD

**Issue by diffused** [aspnet/Identity#418]
Would like to externally override DbContextOptions when instantiating a context that uses IdentityDbContext like so:
```
public class AppDbContext : IdentityDbContext<ApplicationUser>
{
	public AppDbContext() { }

	public AppDbContext(DbContextOptions options)
		: base(options)
	{
	}
}
```

Perhaps adding something like this to IdentityDbContext.cs?

```
public class IdentityDbContext<TUser> : IdentityDbContext<TUser, IdentityRole, string> where TUser : IdentityUser
{
	public IdentityDbContext() { }
	public IdentityDbContext(DbContextOptions options)
		: base(options)
	{
	}
}
```

**Comment by rustd** [comment]
@divega can you please comment on this?

**Comment by divega** [comment]
@diffused could you elaborate a bit on why you would want this? To be clear currently if you use the `AddDbContext<T>(options => { ... })` on `ConfigureServices()` you will get an instance of DbContextOptions accessible to the DbContext without having to have a parameter constructor. On the other hand, the case can be made for copying all the non-default constructors from DbContext into the IdentityDbContext, we are just not sure about the priority of doing so.

**Comment by diffused** [comment]
I'd like to be able to do something like this:

public class Startup
{
    // ...

    public void ConfigureServices(IServiceCollection services)
    { 
        var connectionString = Configuration.Get("Data:DefaultConnection:ConnectionString");

        // Add EF services to the services container.
        services.AddEntityFramework(Configuration)
            .AddSqlServer()
            .AddDbContext<AppDbContext>(option => {
    			option.UseSqlServer(connectionString);
    		}); 
    }

    // ...
}



I've been using "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta3"
(it's what comes up in in intellisense when adding to the project.json)

**Comment by rustd** [comment]
This should work. Can you tell us what does not work?

**Comment by rustd** [comment]
Closing as we think this should work with Beta4. Please reopen if it does not.

**Comment by NeoAnomaly** [comment]
For an unit tests purposes I need something like this:

```
var builder = new DbContextOptionsBuilder<UnifiedContextInMyApp>();
builder.UseInMemoryDatabase(persist: true);
var options = builder.Options;

using (var context = new UnifiedContextInMyApp(options))
{
...test code...
}
```

Any workaround for this?
