### ISSUE TITLE
IPasswordValidator ValidateAsync pass PasswordOptions instead of UserManager

### ISSUE THREAD

**Issue by oferns** [aspnet/Identity#421]
Hi,
 Would it be feasible to remove the UserManger parameter from the ValidateAsync method and replace it with PasswordOptions? in your implementation you only use the options, and I can't think of a scenario where you would need the UserManager here. Perhaps even remove the parameter completely and pass it in the constructor of the implementation? So instead of

     Task<IdentityResult> ValidateAsync(UserManager<TUser> manager, TUser user, string password, 
            CancellationToken cancellationToken = default(CancellationToken));

perhaps...

     Task<IdentityResult> ValidateAsync(PasswordOptions options, TUser user, string password, 
            CancellationToken cancellationToken = default(CancellationToken)); 

or

     Task<IdentityResult> ValidateAsync(TUser user, string password, 
            CancellationToken cancellationToken = default(CancellationToken));

Thanks,
Oli

**Comment by HaoK** [comment]
Any validator that needs to access the user id or user name for example, needs the manager.

**Comment by HaoK** [comment]
Accessing properties directly off of the TUser is relying on store specific implementation which prevents validator from being used across stores potentially
