### ISSUE TITLE
Test Identity on cross platform

### ISSUE THREAD

**Issue by divega** [aspnet/Identity#423]
Our default stores use EF7 with SQL Server and should be easy to switch them to use a different store with EF7 support. This combination which happens to be very good default choice for VS development on Windows doesn't work in cross platform scenarios where there is currently no up to date and complete enough implementation of SqlClient and where very frequently open source database are commonly targeted. 

We expect this to be addressed with the addition of new store providers for EF7 but I think it is worth having an item to track this on the Identity side.

Here is a summary of some combinations that would be good to try:

- Identity + EF provider on .NET Core
- Identity + Non EF providers

**Comment by calwi** [comment]
Not sure where to direct this, but I came up with the same error raised by jchadwick #403. In short I'm working through 'My First ASP.NET 5' on OS X. Yeoman, scaffold, all working fine. I clicked Register link on the running app, and get connection string error. I've changed this to point to a running version of SQL 2014 I have access to. I've created a blank DB for the purpose. It looks like it partially works, creating 7 Tables, then blows with this error. I can put the full stack trace somewhere if it's of interest, but point being, is it too early yet for this to be expected to work, or can you help point me in the right direction to help track down a fix? My setup is running EF7-beta4-13307, with DNX Mono-beta4 Runtime.

**Comment by divega** [comment]
We have learned that the SqlClient implementation in Mono has no support for DateTimeOffset. We haven't tested Identity in this this scenario enough to know whether you could hit any other issues. 

Unfortunately I cannot think of a workaround short of creating your own set of IdentityUser class and your own stores that don't use DateTimeOffset. 

I suggest you ask for this to be fixed on Mono (http://www.mono-project.com/community/).

Besides, there are also plans to create an implementation of SqlClient that will work cross platform and be more functional. See https://github.com/aspnet/EntityFramework/issues/2161 for more details.

cc @HaoK.

**Comment by calwi** [comment]
OK. Thanks Diego, Will what they say over at mono then, otherwise wait for the SqlClient long term as this seems the direction of travel.

**Comment by divega** [comment]
@calwi thanks for asking!

Removing myself and the milestone to re-discuss if there is anything we can do in triage.

**Comment by calwi** [comment]
Seems like they are already looking with this (https://github.com/mono/mono/pull/1773) and should be included in the next release, 4.2. I'm downloading a nightly build now to see if it turns up anything.

**Comment by divega** [comment]
I read in another bug report that Mono's version of the SqlDbType enumeration is missing DateTimeOffset (and also DateTime2). Not sure if that is still the case but I suspect they will need it fixed before things can work end-to-end.

**Comment by rustd** [comment]
* Identity + EF Provider on Mono
* Identity + EF Provider on .NET Core
* Identity + Non EF Provider

**Comment by HaoK** [comment]
Move this to RC?

**Comment by rustd** [comment]
@divega can you please check if there is EF issue tracking the EF + SQLLite testing.

**Comment by HaoK** [comment]
Nothing to do for this right now so unassigning
