### ISSUE TITLE
Override defaults to use Identity instead of Sequence for SQL Server in IdentityDbContext

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#426]
Porting from templates repo https://github.com/aspnet/Templates/issues/41 

For beta4, this fix needs to be in IdentityDbContext

**Comment by divega** [comment]
Updating the title.

**Comment by divega** [comment]
This is necessary so that the database created by default can work on Azure SQL Database. Note that this can be reverted as soon as we fix aspnet/EntityFramework#1960.

**Comment by suhasj** [comment]
checked in for beta4 and merged with dev branch as well
