### ISSUE TITLE
Runtime Role-based Access Control In ASP.NET MVC

### ISSUE THREAD

**Issue by SirwanAfifi** [aspnet/Identity#440]
ASP.NET MVC allows users the ability to assign permissions to functionality (i.e. Actions) at Design Time like so:  

    [Authorize(Roles = "Administrator,ContentEditor")]
    public ActionResult Foo()
    {
       return View();
    }
How Can I set the role at the runtime? And I wanna check Role is my view something like this:  

    @if (User.IsInRole(Model.User.Role))
    {
        <div>This will be visible only to users in the ContentEditor role.</div>
    }
Any Idea?

**Comment by stephenstroud** [comment]
Could you not achieve this using partial views at design time, depending on their role.

**Comment by rustd** [comment]
As of the current design Roles are not settable at runtime.

**Comment by SirwanAfifi** [comment]
@rustd So what's another solution for doing that? Any idea?
