### ISSUE TITLE
Different user types in ASP.Net Identity

### ISSUE THREAD

**Issue by SirwanAfifi** [aspnet/Identity#441]
In my application I have different types of user( Teacher, Student, ...) that have their own properties, For for Teacher I have `Experience, Languages Spoken, Certifications, Awards, Affiliations, ...` and for Student I different information. So in this way I can't use roles because of different information per user. So all of them actually are users I mean they can login on my site. Also They have common information for signing up: `First Name, Last Name, Email, Password` Now what do you think and what's the best option for doing this? Should I create class for each user that inherits from `IdentityUser<int, CustomUserLogin, CustomUserRole, CustomUserClaim>` ? 
Any idea?

**Comment by Bartmax** [comment]
I would really like to hear about this too. I'm not sure what's a good option.

What I'm doing is having an ApplicationUser, which inherits from IdentityUser.
```
Student.cs
{
    public string StudentId { get; private set; }
}

Teacher.cs
{
    public string TeacherId { get; private set; }
}

and OnModelCreating

builder.Entity<Teacher>(b =>
{
    b.HasOne<ApplicationUser>().WithOne().ForeignKey<Teacher>(x => x.TeacherId);
});

builder.Entity<Student>(b =>
{
    b.HasOne<ApplicationUser>().WithOne().ForeignKey<Student>(x => x.StudentId);
});
```
this is beta3, on other version the api has changed, not sure if this still applies.
does it make sense ?

hope it helps.

**Comment by rustd** [comment]
@divega can you please comment on User model?

**Comment by divega** [comment]
@SirwanAfifi @Bartmax From the pure modeling perspective, it should be ok to add derived classes for user and get those instances persisted to the database, that is, __as soon as we are done adding inheritance support to EF7__. 

However, ASP.NET Identity was not designed to map specific user types to a role or a claim. Identity models roles and claims as associations instead. Those associations can change over the lifespan of a user, while on the other hand the type of an entity is immutable. 

Given all that, separating the different persona types in your domain model from the application user entity seems reasonable.
