### ISSUE TITLE
Identity Groups

### ISSUE THREAD

**Issue by stephenstroud** [aspnet/Identity#443]
Why isn't there a concept of groups in identity -  I've had to create a Group Manager for roles, would be nice if this came out of the box unless there was a reason for not including it?

**Comment by blowdart** [comment]
What do you mean by groups?

**Comment by stephenstroud** [comment]
Assign a Role group to a user which consists of many roles.

Nice example here:
http://typecastexception.com/post/2014/08/10/ASPNET-Identity-20-Implementing-Group-Based-Permissions-Management.aspx

**Comment by HaoK** [comment]
One of these should be duped: https://github.com/aspnet/Identity/issues/184

**Comment by weedkiller** [comment]
Blowdart is an idiot ...
so many people are requesting groups and tenants
 https://github.com/aspnet/Identity/issues?utf8=%E2%9C%93&q=is%3Aissue+group , https://github.com/aspnet/Identity/issues/1532 , 
https://github.com/aspnet/Identity/issues/545 , 
https://github.com/aspnet/Identity/issues/184 , 
https://github.com/aspnet/Identity/issues/586 ,
https://github.com/aspnet/Identity/issues/184 ,
https://github.com/aspnet/Identity/issues/83 ,
https://github.com/aspnet/Identity/issues/62 ,
https://github.com/aspnet/Identity/issues/1187 ,
https://github.com/aspnet/Identity/issues/1518
