### ISSUE TITLE
IUser UserName Property

### ISSUE THREAD

**Issue by vishal123** [aspnet/Identity#446]
I might be nitpicking here, but just wondering why the IUser interface has both Id and UserName properties.
Wouldn't the Id property alone be enough?

**Comment by stephenstroud** [comment]
For uniqueness yes, however, Usernames are easier for the user to remember rather than ID as they can associate this to something they know such as an email address. Nothing stopping you giving your users a GUID/ID to login though.

**Comment by HaoK** [comment]
UserName is potentially mutable, while ID is expected to be stable forever

**Comment by vishal123** [comment]
@stephenstroud i think you've misunderstood me. I'm not suggesting users login using a GUID/ID. While it is certainly a valid use case, it is very niche. A user's name can be stored in the Id property, and surely its the concern of the store to ensure uniqueness. 
In such a situation the need for a username doesn't exist, and you have to work around the interface by setting the Id getter to return username.

@HaoK I'd agree for the current EntityFramework, and most typical website authentication style implementations. However what if a UserName doesn't exist? It doesn't feel right to have to throw NotSupportedExceptions.

Anyway just something I came across when writing a UserStore, so i though i'd bring it up.
