### ISSUE TITLE
Bug when using generic IdentityRole<TKey> ?

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Identity#449]
Bug when using generic `IdentityRole<TKey>`  ?

```
public class ApplicationUser : IdentityUser<Guid>
    {
        public ApplicationUser()
        {
            Id = Guid.NewGuid();
        }
    }

services.AddIdentity<ApplicationUser, IdentityRole<Guid>>()
                .AddEntityFrameworkStores<ApplicationDbContext, Guid>();
```

this creates 3 properties on table UserRoles and 3 Foreign Keys, something like this:

```
UserId = c.Guid(nullable: false),
RoleId = c.Guid(nullable: false),
IdentityRoleId = c.Guid(nullable: false) // can't remember the exact name.
```

If I add an ApplicationRole inheriting from `IdentityRole<TKey>`, and using that instead in the AddIdentity method works as expected:

```
    public class ApplicationRole : IdentityRole<Guid>
    {
        public ApplicationRole()
        {
            Id = Guid.NewGuid();
        }
    }

services.AddIdentity<ApplicationUser, ApplicationRole>()
                .AddEntityFrameworkStores<ApplicationDbContext, Guid>(); 
```

I think this is a bug.

**Comment by suhasj** [comment]
@Bartmax I tried this on a sample web application using packages from `https://www.myget.org/F/aspnetrelease/` and things seem to work as expected

Some questions
- What version of packages do you have ?
- Hope you ApplicationDbContext declaration was updated to include the IdentityRole<Guid> ?
- Are you using migrations to create the database ?
- Are you using IdentityDbContext or a new implementation of it ?

**Comment by Bartmax** [comment]
> What version of packages do you have ?

```
		"Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta3",
		"EntityFramework.Commands": "7.0.0-beta3"
```

> Hope you ApplicationDbContext declaration was updated to include the IdentityRole ?

yes.

> Are you using migrations to create the database ?

yes. ef migration add initial

> Are you using IdentityDbContext or a new implementation of it ?

IdentityDbContext.


I just created the minimal repo that shows the problem, maybe something is missing

https://github.com/Bartmax/AspnetExpriments/tree/master/AspnetExperiments/src/EFGuidPrimaryKey.Sample

**Comment by suhasj** [comment]
thank you for the repro. I'll take a look and get back

**Comment by HaoK** [comment]
I don't see this on beta5 or beta 6 bits, if this repos still once you update to later beta builds, please reopen this issue.
