### ISSUE TITLE
Problem with cookies when using Guid as Primary key.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Identity#450]
I'm really not sure if this is or not a cookies problem since I cannot reproduce it easily.

When using Guid as the TKey for Identity, I can register, login, etc as expected. Everything works fine.
If I kill IISExpress and browse to the application also works ok. Until some moment (not sure why / when because I'm developing so close, start, code changes quite often, maybe when after leaving the app idle for some time I get an error
`InvalidCastException: Invalid cast from 'System.String' to 'System.Guid'.`

the stack is: 
```
InvalidCastException: Invalid cast from 'System.String' to 'System.Guid'.
System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
System.Convert.ChangeType(Object value, Type conversionType)
Microsoft.AspNet.Identity.EntityFramework.UserStore`4.ConvertIdFromString(String id)
Microsoft.AspNet.Identity.EntityFramework.UserStore`4.FindByIdAsync(String userId, CancellationToken cancellationToken)
Microsoft.AspNet.Identity.UserManager`1.FindByIdAsync(String userId, CancellationToken cancellationToken)
Microsoft.AspNet.Identity.SignInManager`1.<ValidateSecurityStampAsync>d__28.MoveNext()
```

The only way to get the application back to normal behavior is deleting the asp.net cookie and login again.  

here is how I have configured identity:
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddEntityFramework(Configuration)
        .AddSqlServer()
        .AddDbContext<ApplicationDbContext>();

    services.AddIdentity<ApplicationUser, ApplicationRole>()
        .AddEntityFrameworkStores<ApplicationDbContext, Guid>();
}

public void Configure(IApplicationBuilder app)
{
    asp.UseIdentity();
    // ...
}

public class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, Guid>{
    // ...
}

```

**Comment by divega** [comment]
Dupe of #420?

**Comment by Bartmax** [comment]
I think it is, maybe @cherrydev can confirm.

**Comment by cherrydev** [comment]
I'm a bit confused by the inconsistent appearance of the error, but the stack trace definitely matches.

**Comment by Bartmax** [comment]
yes dupe!. closing.
