### ISSUE TITLE
ServiceCollection AddIdentity Extension Requires TRole and RoleStore

### ISSUE THREAD

**Issue by kspearrin** [aspnet/Identity#453]
I am implementing Identity with a custom UserStore and without a RoleStore, yet the ServiceCollection AddIdentity extension requires me to specify a TUser and TRole as well as specify `AddRoleStore<T>()` on the IdentityBuilder or I get an exception:

> InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNet.Identity.IRoleStore`1[System.Object]' while attempting to activate 'Microsoft.AspNet.Identity.RoleManager`1[System.Object]'.

I do not need roles. Could we add an overload for the AddIdentity extension in IdentityServiceCollectionExtensions.cs that does not require role manager?

**Comment by atrauzzi** [comment]
:+1:

**Comment by rustd** [comment]
You can write your own extension for registering the services. Here is an example https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/IdentityServiceCollectionExtensions.cs#L39

**Comment by moliveto** [comment]
Hello,
I have the same problem. I have an UserStore without RoleStore.
You have been able to solve your problem?
