### ISSUE TITLE
Create a compatibility package to help migrate existing apps from v4.5  to v5.0 

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#457]
We need to come up with a compatibility package between ASP.NET 5.0 and ASP.NET v4.5 apps so that they can share existing database and user persisted cookies which would be the first step in migrating apps from v4.5 to v5.0. The package should
- Help user bridge model changes between 4.5 and 5.0
- Help migrate database without loss of data
- Use the update PasswordHasher and DataProtection
- Help applications understand cookies among them

- [ ] Create a Sample
- [x] Create a package

**Comment by rustd** [comment]
This is fork which has these changes https://aspnetidentity.codeplex.com/SourceControl/network/forks/suhasj/aspnetidentity

**Comment by rustd** [comment]
https://github.com/aspnet/DataProtection/issues/85

**Comment by blowdart** [comment]
Also https://github.com/aspnet/Security/issues/280

**Comment by rustd** [comment]
@HaoK Can you please link the Security related bugs for this migration case.

**Comment by HaoK** [comment]
Tracking the samples work here https://github.com/aspnet/Identity/issues/682 for Rc2, remaining package/documentation can be done post RC2

**Comment by HaoK** [comment]
e0676292fcc8537fb6a7d3709b36b5963881a981 AspNet.Identity.CoreCompat package added
