### ISSUE TITLE
How to alter the username validation rules

### ISSUE THREAD

**Issue by RyanDansie** [aspnet/Identity#458]
Apologies for asking this here but I cant find anything about it in the documentation. How would you alter the username validation rules to allow an email address to be used as a username.

I can see what needs to be done to the validator from looking at the last unit test on this page:
https://github.com/aspnet/Identity/blob/dev/test/Microsoft.AspNet.Identity.Test/UserValidatorTest.cs

But I cant see how to apply the validator to my project (default template for mvc6 with single user authentication) or access the default validator to modify it. I know in previous versions there was a UserValidator property within UserManager but this property doesnt exist any more.

The documentation I have read is from the below URL so please let me know if there is anything else I should be reading.
http://docs.asp.net/en/latest/security/data-protection/index.html

**Comment by HaoK** [comment]
You probably want to call in your ConfigureServices something like: services.ConfigureIdentity(options => { options.User.Xyz = "whatever" }), to adjust the options which are picked up by the default validators

**Comment by RyanDansie** [comment]
That's exactly what I needed. Thanks very much!
