### ISSUE TITLE
Add sugar method to add instance of UserClaimsFactory on IdentityBuilder

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#463]
Right now if we want to add a custom implementation of `IUserClaimsPrincipalFactory<TUser>` we need to added it on the ServiceCollection object directly passing the TUser and TRole which makes it ugly. This should be on the IdentityBuilder so that it can added fluently like
`builder.AddUserClaimsFactory<T>()`

**Comment by HaoK** [comment]
This is no longer needed by compat app, so not sure this is still needed

**Comment by rustd** [comment]
Closing as not needed.
