### ISSUE TITLE
Consider creating Microsoft.AspNet.Identity.Abstractions

### ISSUE THREAD

**Issue by divega** [aspnet/Identity#469]
This would make Identity more consistent with other projects across the stack and help organize the code, plus also possibly help third party libraries that want to interact with Identity without taking a dependency on the full thing.

**Comment by rustd** [comment]
Beta6 should not break tooling/ templates that ship with beta5

**Comment by HaoK** [comment]
Clearing milestone so we can triage/discuss

**Comment by blowdart** [comment]
There are already enough comments about the massive dependency tree you get importing framework libraries because of Abstractions, Core and Common. I'm not sure we should, if you implement your own identity store you'd use that in an app that already adds an identity dependency.

**Comment by davidfowl** [comment]
> If you implement your own identity store you'd use that in an app that already adds an identity dependency.

This is about library authors not apps. Applications always pull in everything so it shouldn't be used as an argument about not layering.

**Comment by blowdart** [comment]
And what would libraries would be written against abstractions for identity? Aside from implementations on data stores EF doesn't provider, or token providers for strange SMS providers?

**Comment by davidfowl** [comment]
Whatever extensibility points existed in identity.

**Comment by HaoK** [comment]
Yeah the idea would be, custom identity implementations wouldn't have to suck in all the default stuff they may or may not want, if we had an abstractions layer.  (That said, I'm not sure this is something we can do easily at this time, but we should at least consider it)

**Comment by blowdart** [comment]
All of which are there to provide things for identity to use and for nothing else, and aren't usable outside of identity. So what do we gain by moving them into another package? There's nothing generic here.

**Comment by HaoK** [comment]
Identity.Core is already sort of our Abstractions++, it just has a bit of extra stuff.  Could be as simple as a rename

**Comment by divega** [comment]
Having an abstractions package would actually reduce the bloat of the dependencies for some customers, e.g. if someone wants to write an alternate implementation of one of the Identity service interfaces or a store provider he would only need to pull Microsoft.AspNet.Identity.Abstractions and whatever dependencies they need in their implementation instead of the 20+ dependencies of the Microsoft.AspNet.Identity package. 

The problem is that this would only add value only for a relatively small set of customers: library writers extending Identity. For the rest of our customers it would effectively add 1 item to the list.
