### ISSUE TITLE
HttpContext is null in RoleManager.Update

### ISSUE THREAD

**Issue by pmiddleton** [aspnet/Identity#473]
In our codebase we override SaveChanges on our DBContext in order to update the modified Date and modified By fields on our Identity classes (SecurityUser, SecurityRole, etc).  We are getgin the currently logged in user from the HttpContext.

Inside of the RoleManager and UserManager the various add/update methods internally perform their work by starting a new task using TaskFactory.StartNew.  Unlike async/await, which uses an AspNetSynchronizationContext to flow the HttpContext to the async callback. the aspTaskFactory.StartNew method will not preserve the HttpContext in the callback which leads to a null reference exception.  

We need some way to flow the HttpContext to the internal callback created by the AsyncHelper.RunSync method internal to ASP.Net Identity.

**Comment by HaoK** [comment]
This is an Identity 2.2 issue, can you file this over here instead?  Thanks https://aspnetidentity.codeplex.com/
