### ISSUE TITLE
Miscellaneous feedback

### ISSUE THREAD

**Issue by glen-84** [aspnet/Identity#474]
1. I find it a bit strange that e-mail is used by default instead of username. I think it would be best to ask for an actual username in addition to e-mail (after an external login as well), and allow signing in with either. It looks wrong to use an e-mail for display purposes (at the top right, for example).
2. If you sign in using an external provider that returns an e-mail address which is already in the database, you should be asked if you want to link to the existing account (which would require authentication and thus ask for a password), or create a new account (which would ask for a username, as it does now). ([Example](http://ctrlv.in/583628))
3. If you register using an external provider, the forgot password form will not work, even if you've set a local password (because e-mail is not confirmed). `ExternalLoginConfirmation` should send an account activation (e-mail confirmation) e-mail to the user.
4. For what reason do you use a GUID (I think?) instead of an int for user IDs? Is it related to distributed scenarios? The user ID needs to be in URLs sometimes (account activation, profile page, etc.) and a big ugly string isn't pleasant to look at (f.e. /users/e226cb09-20e7-4646-bbf5-4a12fe662a3c/glen vs /users/12345/glen)

**Comment by HaoK** [comment]
For 3. you should be able to login via external and add password via the manage page

**Comment by glen-84** [comment]
True, but you may think that you registered locally, and there's no indication of failure (see also https://github.com/aspnet/Mvc/issues/2637 no. 12).

You might consider instructing the user to sign in via one of his/her connected services when a matching account is found with no password.

**Comment by Pictuel** [comment]
About you first inquiry, it's very easy to switch to username as default instead or in addition of email.
