### ISSUE TITLE
I can not havet this solution build on visual studio 2015 RC

### ISSUE THREAD

**Issue by Piusn** [aspnet/Identity#476]
![capture](https://cloud.githubusercontent.com/assets/925985/8020992/f64e0076-0c97-11e5-8384-d183d08122e2.PNG)

I need help on this issue. I open the solution with VS 2015 RC, but it does not build. Anyone with such an issue or a solution on how to solve it I would be glad

**Comment by rustd** [comment]
Please see the getting started instructions on Home repo. We are publishing nightly builds on MyGet so it could be that things might have been broken for a particular build.
This is not Identity related so I am closing this issue.
