### ISSUE TITLE
Ca we now use the beta4 release in Production

### ISSUE THREAD

**Issue by ikourfaln** [aspnet/Identity#484]
Hi,

We are working on a big project, and we need to build it with ASP.NET 5. But we can't wait anymore for the RTM, so is it safe to start the project with Visual Studio 2015 RC (Identity beta4) ?

Thanx for all your hard work

**Comment by blowdart** [comment]
This depends on your expectations

You'd be running beta identity code, on top of a beta framework. We don't security patch betas, we simply tell you to move to the latest beta. We don't have support expectations either. Nor do we have concrete release dates for any of these (when support will become available).

If you're comfortable with those risks then you could considering using it.

**Comment by ikourfaln** [comment]
thanx for reply :+1:
