### ISSUE TITLE
Using multiple ASP Identity within MVC5

### ISSUE THREAD

**Issue by warheat1990** [aspnet/Identity#488]
I've added admin area to an existing MVC5 project for managing content.

The site is currently secured by custom ASP Identity Framework. Now I need to authenticate some user to access the admin area, the user data is in different database with different structure.

It is easy to do this with Membership providers, for example : http://stackoverflow.com/questions/5342158/using-multiple-membership-providers-within-asp-net-mvc-3-application

But is this possible in ASP Identity? I've tried looking everywhere but still nothing.

**Comment by HaoK** [comment]
You can probably do this if you construct two different user managers with their own DbContext's pointing at different databases.  And then just use the appropriate instance for each part of your app.
