### ISSUE TITLE
SignInManager<TUser>.SignInAsync doesn't work in IActionFilter.OnActionExecuting method.

### ISSUE THREAD

**Issue by evorine** [aspnet/Identity#494]
In development environment I wanted to make sure that every request is already logged-in with a default user to skip the login screen and save time.
So I decided to add an action filter and try to sign-in at `OnActionExecuting` method.

But after the second request I get this error while calling `SignInManager<TUser>.SignInAsync` in the `OnActionExecuting` method:
> InvalidOperationException: The following authentication scheme was not accepted: Microsoft.AspNet.Identity.Application.

Same codes work on actions but not in action filters.

I have a minimal project uploaded on github to reproduce the problem: https://github.com/evorine/IdentityTests

PS: I'm trying to implement custom identities. I'm not using EF.

**Comment by rustd** [comment]
Try doing this https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Abstractions/IAsyncActionFilter.cs
instead of .Wait()
Also does this work without AutoFac?

**Comment by evorine** [comment]
I found the problem. It was my bad. I was adding the instance of the filter directly as a filter. I fixed it by changing adding the filter's type instead of instance while registering it as a service.

Changed from:
```csharp
services.Configure<MvcOptions>(options =>
{
    options.Filters.Add(Container.Resolve<Filters.GlobalActionFilter>());
});
```
To:
```csharp
services.Configure<MvcOptions>(options => 
{
    options.Filters.Add(typeof(Filters.GlobalActionFilter));
});
```
