### ISSUE TITLE
Identity for for WEB API only

### ISSUE THREAD

**Issue by stephenstroud** [aspnet/Identity#495]
http://www.asp.net/web-api/overview/security/individual-accounts-in-web-api

How can I achieve the above for web API security in VNext. I'm planning on passing around the cookie - ".AspNet.Microsoft.AspNet.Identity.Application=gfdgdgdfgg"

WEB API 2.2 used token in the header.

Will this work for the Authorise attribute and roles etc? thanks

Looking around I want to achieve this for authentication and I don't want a website over the top for my project.

http://docs.asp.net/projects/mvc/en/latest/tutorials/native-mobile-backend.html

**Comment by stephenstroud** [comment]
In case anyone needs bearer tokens earlier. Basic example of Identity with Bearer tokens.

https://github.com/bigfont/AspNet.Security.OpenIdConnect.Server/tree/bigfont/samples/ResourceOwnerPasswordFlow

**Comment by leak** [comment]
Thanks for your example.

When I clone your repo and switch the startup project to yours i get 157 build errors and 2 warnings. Seems to be mostly related to the forked project. Any chance you could have a look at that?

**Comment by stephenstroud** [comment]
@leak, have you upgraded to the latest dnvm? Doing the open connect conversation on gitter very active. https://gitter.im/aspnet-contrib/AspNet.Security.OpenIdConnect.Server not my repo sorry.

**Comment by leak** [comment]
I am running dnx-clr-win-x86.1.0.0-beta6

**Comment by stephenstroud** [comment]
Yeah I'm running successfully with dnx-clr-win-x86.1.0.0-beta7-12364. You will probably need to add all the nightly build feeds to your Nuget Package manager if you haven't already. That should sort you out.

**Comment by rustd** [comment]
Closing since #503 is tracking this
