### ISSUE TITLE
Shouldn't AddEntityFrameworkStores use services.TryAdd instead of just services.Add ?

### ISSUE THREAD

**Issue by eduaglz** [aspnet/Identity#496]
I created my own implementation of the IUserStore and added it to the services, but calling AddEntityFrameworkStores registers a new implementation for the interface (the default one) and makes UserManager to use that one instead of mine.

I believe the problem can be easily solved by changing the implementation of the extension method from:
```csharp
public static IdentityBuilder AddEntityFrameworkStores<TContext>(this IdentityBuilder builder) where TContext : DbContext
{
    builder.Services.Add(IdentityEntityFrameworkServices.GetDefaultServices(builder.UserType, builder.RoleType, typeof(TContext)));
    return builder;
}
```

to:
``` csharp
public static IdentityBuilder AddEntityFrameworkStores<TContext>(this IdentityBuilder builder) where TContext : DbContext
{
    builder.Services.TryAdd(IdentityEntityFrameworkServices.GetDefaultServices(builder.UserType, builder.RoleType, typeof(TContext)));
    return builder;
}
```

So that it only adds the services if I haven´t added my own implementation before.

**Comment by HaoK** [comment]
Yep, good catch, these should be TryAdds... I'll fix this

**Comment by eduaglz** [comment]
There you go =), I had some free time
