### ISSUE TITLE
Token Authentication in Header/Body instead of Cookie

### ISSUE THREAD

**Issue by YZahringer** [aspnet/Identity#500]
Hello,

Are there plans to support authentication token in Header/Body instead of Cookie?

(eg JSON Web Token)

Thank you,
Best regards,
Yann

**Comment by prasannapattam** [comment]
I vote for this feature.

**Comment by PinpointTownes** [comment]
@YZahringer @prasannapattam you might be interesting in this SO post: http://stackoverflow.com/questions/31007470/does-asp-net-mvc6-support-oauth-2-bearer-tokens/31093557#31093557

___________

**TL;DR: the official packages developed by Microsoft for ASP.NET 5 only support OAuth2 bearer token validation.**

This means that...

1. ... you'll be able to authenticate your users using bearer tokens issued by an external identity provider (like Azure Active Directory) with the `Microsoft.AspNet.Authentication.OAuthBearer` package:

        app.UseOAuthBearerAuthentication(options => {
            options.AutomaticAuthentication = true;
            options.Audience = "http://localhost:50000/";

            // Authority is only useful if your JWT tokens
            // are issued by an OpenID Connect server.
            options.Authority = "[OpenID Connect provider address]";


            // If you don't use an OpenID Connect server, you have to manually update the
            // token validation parameters with the issuer's signing key.
            options.TokenValidationParameters.IssuerSigningKey = new X509SecurityKey(certificate);
        });

That said, only JWT tokens are now supported OTB: the OAuth2 bearer middleware shipped with Katana 3 used to natively support opaque tokens produced by the OAuth2 authorization server, but this support has been removed.

2. ... you won't be able produce your own tokens anymore. The OAuth2 authorization server has been removed and won't be ported to ASP.NET 5: http://stackoverflow.com/questions/29055477/oauth-authorization-service-in-asp-net-mvc-6/.

Luckily, alternatives exist. I'm personally developing an OpenID Connect server middleware based on the OAuth2 server shipped with Katana, that offers the same low-level experience: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server

For more information, you can take a look at this SO answer: http://stackoverflow.com/questions/30768015/configure-the-authorization-server-endpoint/30788109#30788109

**Comment by HaoK** [comment]
https://github.com/aspnet/Identity/issues/503

**Comment by HaoK** [comment]
Dupe
