### ISSUE TITLE
Investigate possible spurious concurrency exceptions caused by Identity calls

### ISSUE THREAD

**Issue by divega** [aspnet/Identity#502]
Moved from https://github.com/aspnet/Mvc/issues/2713 for more details. @HaoK can you please dig deeper into this?

**Comment by HaoK** [comment]
@toddtsic can you include the full controller code that is causing this so we can investigate more?  Also how are you getting your db context, are you using the same one that identity is using (getting it from the ctor/DI)?

**Comment by toddtsic** [comment]
Hao,

I'm using a base controller class, so from controller in question

    public FamilyController(
	            UserManager<ApplicationUser> userManager,
	            SignInManager<ApplicationUser> signInManager,
	            ITSICSessionManager session,
	            ApplicationDbContext dbcontext,
	            IOptions<AppSettings> appSettings,
	            IBusinessRulesManager brules
	        ) : base(userManager, signInManager, dbcontext, session, appSettings, brules)
	        {
	        }

and from base controller:

    public class BaseController : Controller
    {
        public ApplicationDbContext db { get; private set; }
        public ITSICSessionManager s { get; private set; }
        public IBusinessRulesManager br { get; private set; }
        public SignInManager<ApplicationUser> SignInManager { get; private set; }
        public UserManager<ApplicationUser> UserManager { get; private set; }
        public IOptions<AppSettings> AppSettings { get; private set; }

        public BaseController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ApplicationDbContext context, ITSICSessionManager session, IOptions<AppSettings> appSettings, IBusinessRulesManager brules)
        {
            db = context;
            s = session;
            SignInManager = signInManager;
            UserManager = userManager;
            AppSettings = appSettings;
            br = brules;
        }

Does this get at what you are looking for, or do you need more detail?

Thanks for looking at this, 
Todd

**Comment by HaoK** [comment]
Can you also include one of the controller action methods that repos this behavior so I can try some form of it out?

**Comment by toddtsic** [comment]
Here's the action method now (notice my workaround using PasswordHasher.VerifyHashedPassword, if you replace that with CheckPasswordAsync, you will be able to reproduce.

T

    [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTSICPlayerToFamilyAccount(FamilyViewModel model)
        {
            if (!String.IsNullOrEmpty(model.New_Player_Detail.TSIC_Username) && !String.IsNullOrEmpty(model.New_Player_Detail.TSIC_Password))
            {
                ApplicationUser user = await UserManager.FindByNameAsync(model.New_Player_Detail.TSIC_Username);
                if (user != null)
                {
                    string thisUserId = user.Id;

                    int countPrevious = await (from fm in db.Family_Members where fm.Family_UserId == model.Family_Details.Family_UserId && fm.Family_Member_UserId == user.Id select fm).CountAsync();
                    if (countPrevious == 0)
                    {
                        Family_Members record = new Family_Members()
                        {
                            Family_UserId = model.Family_Details.Family_UserId,
                            Family_Member_UserId = thisUserId,
                            modified = DateTime.Now,
                            lebUserID = model.Family_Details.Family_UserId
                        };

                        PasswordHasher<ApplicationUser> pHasher = new PasswordHasher<ApplicationUser>();
                        try
                        {
                            PasswordVerificationResult pvResult = pHasher.VerifyHashedPassword(user, user.PasswordHash, model.New_Player_Detail.TSIC_Password);

                            switch (pvResult)
                            {
                                case PasswordVerificationResult.Success:
                                case PasswordVerificationResult.SuccessRehashNeeded:
                                    db.Family_Members.Add(record);
                                    await db.SaveChangesAsync();
                                    return RedirectToAction("EditFamilyAccount", new { StatusMessage = String.Format("Player: {0} has been added to your family account.", model.New_Player_Detail.TSIC_Username) });
                                case PasswordVerificationResult.Failed:
                                    return RedirectToAction("EditFamilyAccount", new { StatusMessage = "Credentials for new player were not valid." });
                            }
                        }
                        catch 
                        {
                            //if (ex is FormatException)
                            //{
                            //    user.PasswordHash = pHasher.HashPassword(user, model.New_Player_Detail.TSIC_Password);
                            //    user.SecurityStamp = Guid.NewGuid().ToString();
                            //    await UserManager.UpdateAsync(user).ConfigureAwait(false);
                            //}
                            return RedirectToAction("EditFamilyAccount", new { StatusMessage = "There was a server error validating the new player, please try again..." });
                        }
                    }
                    else
                    {
                        return RedirectToAction("EditFamilyAccount", new { StatusMessage = String.Format("Player: {0} is already included in your family account.", model.New_Player_Detail.TSIC_Username) });
                    }
                }
                else
                {
                    return RedirectToAction("EditFamilyAccount", new { StatusMessage = String.Format("Username: {0} is not a valid.", model.New_Player_Detail.TSIC_Username) });
                }
            }

            return RedirectToAction("EditFamilyAccount", new { StatusMessage = "There was an error updating your family account." });
        }

If it helps to see the Family_Members model 

btw I us database first,  specifically:

dnx . ef reveng "Data Source=HP-HT\SQLEXPRESS2014;Initial Catalog=TSIC2015V6;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"


using System;
	using System.Collections.Generic;
	using Microsoft.Data.Entity;
	using Microsoft.Data.Entity.Metadata;

	namespace TSICV5.ModelsDB
	{
	    public partial class Family_Members
	    {
	        public Family_Members()
	        {
	        }
	        
	        // Properties
	        public int Id { get; set; }
	        public string Family_Member_UserId { get; set; }
	        public string Family_UserId { get; set; }
	        public string lebUserID { get; set; }
	        public DateTime modified { get; set; }
	        
	        // Navigation Properties
	        public virtual AspNetUsers Family_Member_User { get; set; }
	        public virtual Families Family_User { get; set; }
	    }
	}

**Comment by HaoK** [comment]
@divega is the navigation property perhaps the issue?

        public virtual AspNetUsers Family_Member_User { get; set; }

**Comment by HaoK** [comment]
@toddtsic does this still repro for you?  I tried the following repro which mimics your code and I don't see the Concurrent update exception (granted I'm not using MVC, but the flow should be similar)

```
            var family = new Family { Id = Guid.NewGuid().ToString() };
            using (var db = CreateContext())
            {
                var manager = CreateManager(db);
                IdentityResultAssert.IsSuccess(await manager.CreateAsync(user, "password"));
                db.Families.Add(family);
                await db.SaveChangesAsync();

            }
            using (var db = CreateContext())
            {
                var manager1 = CreateManager(db);
                var user1 = await manager1.FindByIdAsync(user.Id);
                Assert.NotNull(user1);
                Assert.True(await manager1.CheckPasswordAsync(user, "password"));
                var record = new FamilyMember()
                {
                    UserId = user.Id,
                    FamilyId = family.Id
                };
                db.Members.Add(record);
                await db.SaveChangesAsync();
                Assert.NotNull(db.Members.SingleOrDefault(m => m.UserId == user.Id && m.FamilyId == family.Id));
            }
```

**Comment by HaoK** [comment]
Feel free to reopen this if you are still seeing this
