### ISSUE TITLE
No Salt in User Password Hash

### ISSUE THREAD

**Issue by jwdavidson** [aspnet/Identity#507]
The password hash value for 2 different users with the same password have the same hash values. This indicates that there is no per user salt employed. This is confirmed by the lack of a Salt filed in the table AspNetUsers.

The source code for the hash is designed to use unique salts, but this is not being used.

**Comment by HaoK** [comment]
Salts are directly combined in the hash, added a test just to be sure 3321adbe640d846913be19f82b5a51cba8c0642e
