### ISSUE TITLE
DependencyResolutionException on SignInManager

### ISSUE THREAD

**Issue by vncastanheira** [aspnet/Identity#509]
I did not know if this should be issued on Identity or Mvc repository, but I chose here because it occurs only with `SignInManager`.

In short terms:
* Create an `IAccountServices` interface.
* Implement that interface in another assembly
* In the implementation class, use `SignInManager<ApplicationUser>` as a parameter on the constructor
* Inject the assembly via Autofac

And then, this is the error:
````
An exception of type 'Autofac.Core.DependencyResolutionException' occurred in Autofac.dll but was not handled in user code

Additional information: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.AspNet.Identity.UserManager`1[SignInManagerProblem.Models.ApplicationUser], Microsoft.AspNet.Hosting.IHttpContextAccessor, Microsoft.AspNet.Identity.IUserClaimsPrincipalFactory`1[SignInManagerProblem.Models.ApplicationUser], Microsoft.Framework.OptionsModel.IOptions`1[Microsoft.AspNet.Identity.IdentityOptions], Microsoft.Framework.Logging.ILoggerFactory)' on type 'SignInManager`1'.
````

And the **InnerException** says:
`{"Value cannot be null\r\nParameter name: contextAccessor"}`

I made a minimum viable example. Build the **Module** project and then reference it's DLL on the **Startup.cs** class. [Download it here](https://mega.nz/#!5Y8mia5b!0EcAj7lUdhRVgFZWZX8V-7i3cEDyJILm990QuT-T9zw)

**Comment by HaoK** [comment]
Does your container actually have a IHttpContextAccessor service registered at the point where SignInManager is being created?

**Comment by vncastanheira** [comment]
@HaoK I used those Autofac registrations on the end of the `public void ConfigureServices(IServiceCollection services)`, after all service registrations, although I don't know where `IHttpContextAccessor` is registered exactly  (maybe with the other Identity services?). 

Instancing `SignInManager` throws this error only in this specific case. Controller, for example, are able to use it without any problem.

**Comment by HaoK** [comment]
Exactly, the service only exists as part of the request (its scoped), so the controller ctor is run during the request.  You can't create an instance of SignInManager outside of the request scope today because it of the IHttpContextAccessor service

**Comment by vncastanheira** [comment]
@HaoK Oh, it makes sense now. Better use it directly on Controllers for now.
