### ISSUE TITLE
UserManager CreateAsync Does Not Add User Profile Info to Separate Model Table During Register

### ISSUE THREAD

**Issue by Reafidy** [aspnet/Identity#512]
I created  a separate table to store user profile information however the create async method adds the user to the AspNetUsers table but not the additional profile information to the UserInfo table when registering a new user.  Something which worked in earlier versions.

IdentityModel:

    public class ApplicationUser : IdentityUser
     {
         public virtual UserProfile UserProfile { get; set; }
     }  

     public class UserProfile
     {
         public int Id { get; set; }
         public string FirstName { get; set; }
         public string LastName { get; set; }     
     }

UserProfile table is defined in the DbContext:

     public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
        {
            private static bool _created;

            public DbSet<UserProfile> UserProfile { get; set; }

            public ApplicationDbContext()
            {      
                if (!_created)
                {
                    Database.AsRelational().ApplyMigrations();
                    _created = true;
                }
            }

            protected override void OnModelCreating(ModelBuilder builder)
            {
                base.OnModelCreating(builder); 
            }
        }

Account Controller: Register:

    var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                user.UserProfile = new UserProfile
                {
                    FirstName = "MyFirstName",
                    LastName = "MyLastName"
                };
     var result = await UserManager.CreateAsync(user, model.Password);

Demo project to illustrate problem:
https://github.com/Reafidy/DemoBugS

**Comment by Reafidy** [comment]
Trying to create a separate table to store profile information however the create async method adds the user but not the additional profile information. 


    public class ApplicationUser : IdentityUser
     {

         public virtual UserProfile UserProfile { get; set; }
     }  


     public class UserProfile
     {

     
         public int Id { get; set; }

         public string FirstName { get; set; }

         public string LastName { get; set; }     
     }

     public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
     {
         private static bool _created;

         public DbSet<UserProfile> UserProfile { get; set; }

         public ApplicationDbContext()
         {
             // Create the database and schema if it doesn't exist
             if (!_created)
             {
                 Database.AsRelational().ApplyMigrations();
                 _created = true;
             }
         }

         protected override void OnModelCreating(ModelBuilder builder)
         {
             base.OnModelCreating(builder);
             // Customize the ASP.NET Identity model and override the defaults if needed.
             // For example, you can rename the ASP.NET Identity table names and more.
             // Add your customizations after calling base.OnModelCreating(builder);
         }
     }

**Comment by Pictuel** [comment]
Why don't you directly add those fields into the aspnetusers table?

something like

<pre><code>
public class ApplicationUser : IdentityUser
{
    public virtual string FirstName { get; set; }
    public virtual string LastName { get; set; }
} 
</code></pre>

**Comment by Reafidy** [comment]
That doesnt work with our buisness rules.  The userprofile table is actually more like a people table it has many other fields,  i have simplified the example.  There are many people but only a small amount of people have logins.   
This feature use to work in older versions of asp.net identity.

**Comment by Pictuel** [comment]
I understand what you're writing. Another way to do it, as you should already do it is to create the table after the result.Succeed condition and add an user id property to the userprofile table.

In the account controller file and register post method:
<pre>
if (result.Succeeded)
{
// ...

var db = new ApplicationDbContext();

var userProfile = new UserProfile
{
    UserId = user.Id,
    FirstName = "MyFirstName",
    LastName = "MyLastName"
};

db.UserProfile.Add(userProfile);
await db.SaveChangesAsync();

// ...
}
</pre>

then you can retrieve the table with selected user's id, a bit annoying to do it like this but it's working.
Still some improvements to make it fancy but as an example you should understand easily.
I wish to help you here. :)

**Comment by Reafidy** [comment]
Thanks for your help, that is definitely a solution to the problem.   

I was just curious as to what has changed in the new framework and whether or not it was a bug.

**Comment by rustd** [comment]
This is blocked on https://github.com/aspnet/EntityFramework/issues/2726

**Comment by rustd** [comment]
Closing since there is no bug in Identity. We are using the EF issue to track this.
