### ISSUE TITLE
We should be able to encrypt values stored in default identity tables

### ISSUE THREAD

**Issue by Pictuel** [aspnet/Identity#516]
It would be nice to encrypt values stored with different hashes options in case your database tables are leaked. Just to make it harder to get the real values like email and username.

I'm actually trying to do that on an application but can't find a way to do it with the identity framework, maybe I'm missing something?

**Comment by Pictuel** [comment]
Can this be a possibility, regarding the roadmap?
Do I need to pull a request for it?

**Comment by rustd** [comment]
I think the question here is more generic on how to encrypt app specific data. You can use DataProtection to protect data in your app. more details are http://aspnet.readthedocs.org/en/latest/security/data-protection/index.html

**Comment by Pictuel** [comment]
Thanks, for your answer, I'll learn how data protection works.
I already found a way to do it with a custom method, but I'm wondering if it can be an option in Identity.

**Comment by rustd** [comment]
We will consider it for a future release.

**Comment by HaoK** [comment]
Tracking via https://github.com/aspnet/Identity/issues/836
