### ISSUE TITLE
StackOverflowException in SecurityStampValidator.ValidatePrincipalAsync

### ISSUE THREAD

**Issue by csunali** [aspnet/Identity#517]
Hey,

I have started having strange "never loading" issues under both IIS and IIS Express recently. It started happening after I started using Identity.

I have downloaded the Cookie Authentication and Identity source files onto my computer and tried to track down the issue. It seems that there is a problem with the way Identity utilizes the `CookieAuthenticationHandler`.

Please note that the issue does not always show up. On my instance, it shows up if I have not worked on the project for a few days and if the previous cookies have expired (I have seen cases where they were not expired too.)

It seems that the `CookieAuthenticationHandler.AuthenticateAsync` method gets called over and over again and I was able to break that circle by commenting out the `return validator.ValidateAsync(context);` code line within the `SecurityStampValidator.ValidatePrincipalAsync` method.

If that line does not get executed, the `StackOverflowException` does not get thrown. 

Based on my limited debugging adventure, the following line seems to call the `SecurityStampValidator.ValidatePrincipalAsync` method:

```
await Options.Notifications.ValidatePrincipal(context);
```

And that method is located within `CookieAuthenticationHandler.AuthenticateAsync` method.

That sounds like `CookieAuthenticationHandler.AuthenticateAsync` and `SecurityStampValidator.ValidatePrincipalAsync` methods keep calling each other again and again in an endless loop under some circumstances which also avoids the whole application starting up.

I have seen my poor application consuming more than 8GB of memory in less than 5 minutes as a result of the loop.

What could be the reason? Can you please check the issue and fix it as it is really a show stopper? 

P.S.: I am using the dev repositories, meaning Beta 6.

**Comment by csunali** [comment]
Okay, I believe I figured out the exact reason.

- The `CookieAuthenticationHandler.AuthenticateAsync` method wants to validate the principle.
- The `await Options.Notifications.ValidatePrincipal(context);` code line calls the `SecurityStampValidator.ValidatePrincipalAsync` method.
- The `validate = timeElapsed > accessor.Options.SecurityStampValidationInterval` code line sets the `validate` variable to `true` because the timeElapsed is over the validation interval.
- The `validate` variable being `true` gets the following two lines of code executed:

```
if (validate)
{
    var validator = context.HttpContext.RequestServices.GetRequiredService<ISecurityStampValidator>();
    return validator.ValidateAsync(context);
}
```

- The resolved service is of type: `SecurityStampValidator<TUser>` and its "ValidateAsync" method is below:

```
/// <summary>
/// Validates a security stamp of an identity as an asynchronous operation, and rebuilds the identity if the validation succeeds, otherwise rejects
/// the identity.
/// </summary>
/// <param name="context">The context containing the <see cref="ClaimsPrincipal"/>and <see cref="AuthenticationProperties"/> to validate.</param>
/// <returns>The <see cref="Task"/> that represents the asynchronous validation operation.</returns>
public virtual async Task ValidateAsync(CookieValidatePrincipalContext context)
{
    var manager = context.HttpContext.RequestServices.GetRequiredService<SignInManager<TUser>>();
    var userId = context.Principal.GetUserId();
    var user = await manager.ValidateSecurityStampAsync(context.Principal, userId);
    if (user != null)
    {
        // REVIEW: note we lost login authenticaiton method
        context.ReplacePrincipal(await manager.CreateUserPrincipalAsync(user));
        context.ShouldRenew = true;
    }
    else
    {
        context.RejectPrincipal();
        await manager.SignOutAsync();
    }
}
```

- The code line `var user = await manager.ValidateSecurityStampAsync(context.Principal, userId);` returns null because the security stamp has expired.
- The context should Reject the principle so the following code from the above method gets executed:

```
        context.RejectPrincipal();
        await manager.SignOutAsync();
```

- The `SignOutAsync` method also gets executed and it has the following code inside:

```
/// <summary>
/// Signs the current user out of the application.
/// </summary>
public virtual async Task SignOutAsync()
{
    await Context.Authentication.SignOutAsync(IdentityOptions.ApplicationCookieAuthenticationScheme);
    await Context.Authentication.SignOutAsync(IdentityOptions.ExternalCookieAuthenticationScheme);
    await Context.Authentication.SignOutAsync(IdentityOptions.TwoFactorUserIdCookieAuthenticationScheme);
}
```

- The `Context.Authentication` property is of type `Microsoft.AspNet.Http.Authentication.Internal.DefaultAuthenticationManager`

- The moment SignOutAsync method gets called, the story begins all over again from the first step - meaning the `CookieAuthenticationHandler.AuthenticateAsync` getting called again - and continues forever.

**Comment by csunali** [comment]
One more feedback regarding the issue, since I said that the issue would occur when the security stamp validation timespan has expired, I tried if the issue gets fixed by deleting the existing browser cookies.

Indeed, it does. The issue went away when I cleared the browser cookies. Whole application loaded successfully.

That definitely looks like a bug to me. I hope the steps I provided will make you able to fix it.

**Comment by PinpointTownes** [comment]
FYI, a similar bug has been reported on `aspnet/Security` and should be fixed soon: https://github.com/aspnet/Security/issues/355

/cc @HaoK

**Comment by csunali** [comment]
@PinpointTownes, that seems to be exactly the same issue. Thank you for informing.

**Comment by HaoK** [comment]
This should be fixed now with ab4ba794e546074a573fbf76d9150ffcf9752c89 issue should be fixed once packages are pushed

**Comment by csunali** [comment]
Thanks. Will try it as soon as it is published and report back if the problem persists.

**Comment by csunali** [comment]
I guess the changes were pushed. I don't seem to have the same problem since I have updated to the latest dev bits.

Thanks for your efforts.
