### ISSUE TITLE
Facebook identity misses email claim

### ISSUE THREAD

**Issue by GregorBiswanger** [aspnet/Identity#518]
I set the E-Mail scope and accept the Facebook App:
app.UseIdentity().UseFacebookAuthentication(options => 
{ 
	options.Scope.Add("email"); 
});

Unfortunately, I get no email claim back. The email here is null:
var email = info.ExternalPrincipal.FindFirstValue(ClaimTypes.Email);

I got only the name of user. Does anyone have an idea or is it a bug?

**Comment by Phasiq** [comment]
I just tested it and I was able to retrieve the email claim without any problem. Perhaps in the user's facebook account, they have chosen not to provide their email address?

You may want to debug and set a breakpoint when you get the claims back from facebook and evaluate them manually to see if the email claim is in the collection. If it is not, it's likely the user account is not providing it (they have the option to opt out on the confirmation screen).

**Comment by HaoK** [comment]
Yes, even though you ask for the email you might not get it (if the user doesn't want to share it for example).

**Comment by Morcatko** [comment]
It does not work for me. Based on some googling it seems to be related to change in facebook api.

**Comment by AlissonRS** [comment]
Yep, they changed things since api 2.4 as far as I know. I found a solution [here](http://stackoverflow.com/questions/31714500/access-email-address-in-the-oauth-externallogincallback-from-facebook-v2-4-api-i).

**Comment by RocketPop** [comment]
Why is this bug closed when the bug still exists? See the SO "workaround" linked by AlissonRS for more info

**Comment by AlissonRS** [comment]
@HaoK and @Ketrex assumed the user didn't want to share email, but this wasn't the case. I even tried with my own facebook account. I think @HaoK closed due to a lack of feedback from the OP. If you think this should be fixed in order to work without that workaround in SO, I think you should open a new thread/bug explaining with more details.
