### ISSUE TITLE
Multiple authentication context

### ISSUE THREAD

**Issue by alexsandro-xpt** [aspnet/Identity#522]
There a possible way do use multiple authentication context(Identity) at same web application in area scope like `/admin` and `/manufacturer`?

It's is useful, and I don't know how Identity manage cookie path works.

**Comment by rustd** [comment]
This is not supported. Can you please elaborate more on what your requirements are?

**Comment by alexsandro-xpt** [comment]
I wish to separate business users of system users.

**Comment by joeaudette** [comment]
why can't you just use different roles or claims for the different permissions/authorirization and add the different user types to different roles or claims?

**Comment by alexsandro-xpt** [comment]
Yes, I could use different roles or claims for the different permissions/authorization but for a better security design, a second cookie authentication to another path(new context) sounds good.
