### ISSUE TITLE
Claim issuer information is not not saved in the database.

### ISSUE THREAD

**Issue by sherif-elmetainy** [aspnet/Identity#525]
I wonder if it is possible to add an extra field to the AspNetUserClaims and AspNetRoleClaims tables to store the claim issuer?
Different external login providers my issue different claims with same claim type but different claim value and it's useful to know which claim is issued by which external login provider.

**Comment by rustd** [comment]
Claims stored in the database should be normalized to unique names as when an Identity is populated from the database the issuer is the application. By design.
