### ISSUE TITLE
Review all XML docs

### ISSUE THREAD

**Issue by jods4** [aspnet/Identity#532]
It says that you should pass the normalized name, when in fact it performs the normalization for you.

**Comment by HaoK** [comment]
@blowdart

**Comment by jods4** [comment]
Sorry I edited the issue. It's not UserStore but UserManager! 
In fact the whole description seems copy-pasted from `UserStore`, the parameters are not even right!
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/UserManager.cs#L390

**Comment by HaoK** [comment]
Nah, I'm sure someone hand typed all of those doc comments :wink:

**Comment by jods4** [comment]
Let's do a blame to find out who's being lazy! ;)

**Comment by divega** [comment]
FWIW, it seems that we need to revisit the comments but just removing a bunch of cancellationToken parameters from them should go a long way.

Should this one be assigned to @HaoK or @blowdart?

**Comment by HaoK** [comment]
379f1928a4d676d2ad14ba026f50b204ed33d518
