### ISSUE TITLE
User login attempt is revealing the locked out status

### ISSUE THREAD

**Issue by bmrpatel** [aspnet/Identity#537]
Once the user is locked out, any attempt to login with bad password results in locked out status. Hence it reveals that user with that username exists. I am trying to change that to just show invalid attempt message. It is part of SignInManager.PasswordSignInAsync and it always return IsLockedOut status even if it is invalid password. I think it would be better to return Failed.

**Comment by HaoK** [comment]
The app is free to treat IsLockedOut as other password failures.  We left that decision to the callee to interpret and use how they will, otherwise they would have no way to detect the difference.

**Comment by HaoK** [comment]
See here: https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.Mvc/Controllers/AccountController.cs#L58

You can simply not check for IsLocked out and fall into the general error case

**Comment by bmrpatel** [comment]
It does not resolve my issue. :( I will try to fix it and submit a pull request. Thanks
