### ISSUE TITLE
There is no way to change Login Url when using UseIdentity()?

### ISSUE THREAD

**Issue by XiaoweiJia** [aspnet/Identity#539]
Is there no way to change login url when using UseIdentity()? It always redirect to "Account/Login". This is very inconvenient. Please advise. Thanks

**Comment by sergeyzwezdin** [comment]
In `ConfigureServices()` something like this:

```csharp
services.Configure<CookieAuthenticationOptions>(options =>
{
    options.LoginPath = new PathString("/login");
});
```

**Comment by HaoK** [comment]
This will likely be addressed in a PR that's coming soon as we are exposing the individual cookie options.  It will look something like

` options.Cookies.AppliationCookie.LoginPath = new PathString("/login");`

**Comment by HaoK** [comment]
2113ef5abcb64bf1c49d8485bcfae45b703f4b78

**Comment by runxc1** [comment]
Note to others looking at this as it is not evident but
this worked in beta7 and is no longer how you set the login path.   
```   
services.Configure<Microsoft.AspNet.Authentication.Cookies.CookieAuthenticationOptions>(options =>
            {
                options.LoginPath = new Microsoft.AspNet.Http.PathString(loginSafe);
            });
```
This seems to work for setting the login path
```
            services.Configure<IdentityOptions>(options=>
            {
                options.Cookies.ApplicationCookie.LoginPath = new Microsoft.AspNet.Http.PathString(loginSafe);
            });
```

**Comment by kennyrulez** [comment]
@runxc1 Thanks for the tip.
Now I see that Identity team removed the Notifications, and then I cannot access to OnApplyRedirect. Do you have any idea how to get this back?

Thanks!

**Comment by runxc1** [comment]
@kennyrulez can you get to that property from the IdentityOptions?
```
 services.Configure<IdentityOptions>(options=>
            {
                    options....
```

**Comment by kennyrulez** [comment]
@runxc1 nope. Does not exist anymore...
