### ISSUE TITLE
Too long tokens

### ISSUE THREAD

**Issue by sergeyzwezdin** [aspnet/Identity#542]
The be honest I like idea of tokens which implemented for the moment. But I have some confusion about it. I build email confirmation token with `UserManager` this way:

```csharp
string emailToken = await _userManager.GenerateEmailConfirmationTokenAsync(user);
```

It gives me token with 200 characters length. Also, it contains characters which can not be used in URL, so I encode it in this way:

```csharp
string code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(emailToken));
```
And it gives me string 267 characters length. Next, I want to compose email confirmation URL for my application and email it to user. Please note, I should include something like user id in URL as well. Including the host name full URL going to be 300+ characters, which throws runtime error with "Bad Request" reason, as URL is too long.

In previous versions of ASP.NET it was possible to increase URL length, but it looks as some kind of hack for me.

So if application can't embedd it into URL it's going to be a bit useless. What the proposed way of using this tokens? How current archtecture expects to use the tokens (like email confirmation, password reset, change phone and so on)?

**Comment by yetanotherchris** [comment]
The fix would be fairly easy, `EmailTokenProvider` should override the  `GenerateAsync` method it gets from `TotpSecurityStampBasedTokenProvider` instead of using `Rfc6238AuthenticationService` which is presumably for two way auth.

**Comment by sergeyzwezdin** [comment]
Thanks! Also, if move token to GET-parameter it resolves the issue.

**Comment by ahmad-moussawi** [comment]
@yetanotherchris Could you please give us an example on how to extend the `EmailTokenProvider` ?

I need to generate a smaller token, since I have a case where the user should enter it manually, so with a long token this could be impossible.

**Comment by brockallen** [comment]
> The fix would be fairly easy, EmailTokenProvider should override the GenerateAsync method it gets from TotpSecurityStampBasedTokenProvider

Beware using this with a very long window of time -- it might open up a brute force attack on validating the email confirmation token (more of a concern for password reset scenarios).
