### ISSUE TITLE
Are there any plans for groups?

### ISSUE THREAD

**Issue by yetanotherchris** [aspnet/Identity#545]
One of the biggest problems for me with the last two attempts at creating user authentication APIs in ASP.NET was the lack of groups of users - users in a group, with a role (and also restricted to a certain database schema and tie in with that). 

Without the group feature, you end up with a big mess of a UI to manage roles, as you can't apply them to groups of users. Are there any plans to add groups to the Identity library?

**Comment by rustd** [comment]
There are no plans for groups or management UI..
