### ISSUE TITLE
Fix travis build

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Identity#546]
https://travis-ci.org/aspnet/Identity

**Comment by divega** [comment]
Has it ever passed? I woud expect the same kind of issues ee had in EF tests that use databases.

**Comment by davidfowl** [comment]
Not that I'm aware of. It's one of the few repositories that don't pass on travis. We should skip the localdb tests on mono.

**Comment by HaoK** [comment]
@davidfowl I skipped the tests, but looks like the travis build is failing on setup first... any ideas what's busto?

19.06s$ ./build.sh --quiet verify
Installing 'KoreBuild 0.2.1-beta7-15004'.
Successfully installed 'KoreBuild 0.2.1-beta7-15004'.
Unable to find version '0.2' of package 'Sake'.
Determining latest version
Latest version is 1.0.0-beta8-15118 
Downloading dnx-mono.1.0.0-beta8-15118 from https://www.myget.org/F/aspnetvnext/api/v2
Download: https://www.myget.org/F/aspnetvnext/api/v2/package/dnx-mono/1.0.0-beta8-15118
######################################################################## 100.0%
Installing to /home/travis/.dnx/runtimes/dnx-mono.1.0.0-beta8-15118
Adding /home/travis/.dnx/runtimes/dnx-mono.1.0.0-beta8-15118/bin to process PATH
Setting alias 'default' to 'dnx-mono.1.0.0-beta8-15118'
Cannot open assembly 'packages/Sake/tools/Sake.exe': No such file or directory.

**Comment by HaoK** [comment]
2161f42086ca0f5b9c0c04460a0dc45e72b678bd
