### ISSUE TITLE
IUserRoleStore<TUser> uses the string roleName instead of IdentityRole object

### ISSUE THREAD

**Issue by saan800** [aspnet/Identity#552]
The interface for IUserRoleStore<TUser> is inconsistent with the rest of the IUserXxxxStore interfaces.

In the other user store interfaces (eg IUserLoginStore, IUserClaimStore) the object is passed to the data layer, but IUserRoleStore<TUser> only passes the roleName.

When implementing a document store implementation of the UserStore, this is an issue as the whole IdentityRole details (ie role + claims) should be save in the user document.

A much wider usage option for IUserRoleStore<TUser> would pass through the IdentityRole objects. Then the data layer implementation can pick and choose which details to use from the IdentityRole.

Implementation in progress at: https://github.com/saan800/AspNet.Identity3.MongoDB

**Comment by SharePointRadi** [comment]
Hey saab800, you should check out https://github.com/aspnet/Identity/issues/225, maybe we should be aligning

**Comment by saan800** [comment]
@SharePointRadi - possibly yes.
I definitely like the way you did the DB connection stuff, so can have both user and role collections available to the store's, think I will use that instead of what I have going on.

Out of curiosity - why do you have UserCliams, UserLogins, UserRoles, RoleClaims in separate collections?
I would have thought that the main benefit of using MongoDB is all associated user/role details are stored in one document. So thought only should have collections for Users and Roles?

My implementation is currently using:
- dnx451
- MongoDB.Driver: 2.0.0
- Microsoft.AspNet.Identity: 3.0.0-beta6-*

Keeping tabs on the Identity, and c# MongoDB driver repositories for updates.

**Comment by HaoK** [comment]
The current interface expects only the role name to be stores, which is enough to find the role.  The main reason for this difference is because we didn't want to flow the Role type into the UserStore interfaces as it would bring in an additional generic
