### ISSUE TITLE
Use constants in UserManager for token purposes

### ISSUE THREAD

**Issue by hvanbakel** [aspnet/Identity#557]
Currently, methods like `GenerateEmailConfirmationTokenAsync` and `ConfirmEmailAsync` in https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/UserManager.cs use strings as purpose for generating a token. Say I want to override one of these methods, it would be helpful if I could just reuse the purpose. 
If this would be exposed as a const the code would be cleaner anyway since there are no 2 magic values. Obviously this also goes for the other tokens.

**Comment by HaoK** [comment]
We will expose them as protected const string ResetPasswordPurpose/ConfirmEmailPurpose etc.
