### ISSUE TITLE
UserOptions.AllowedUserNameCharacters?

### ISSUE THREAD

**Issue by mlynam** [aspnet/Identity#558]
I am wondering what value was added here.  Previously we set a regex for this option.  It appears now we need to assign an entire character map via string.  I much preferred the regex method as our validation method was standardized, it allowed us to force a particular username format and in most cases required far fewer characters to define.

**Comment by blowdart** [comment]
We have been moving away from regular expressions throughout asp.net as part of our security effort. Some folks tend to write complicated regular expression based validators that leave themselves open to DoS, and that's very hard to mitigate against.

You could, if you wished to continue with regular expressions, implement your own IUserValidator implementation and register that with the IdentityBuilder.AddUserValidator<T> method.

**Comment by mlynam** [comment]
Fair enough.

**Comment by Ponant** [comment]
@blowdart , sorry for this question on a old topic but it will be great if you could guide me a bit. If you use `AllowedUserNameCharacters` which is presumably safer, how would you, for instance, go about allowing a user to enter a `UserName ` in ASP.NET Identity in the form `myuser.name` but disallow for dots at the edge of the string (myusername. or .myusername)? I am concerned on both client-side and server-side validation and recalling that UserName is part of the Asp.Net Identity EF.
Thanks

**Comment by HaoK** [comment]
You can always write your own derived UserValidator that adds additional validation like excluding dots from the ends of the user name.

**Comment by Ponant** [comment]
Hi @HaoK , if understand well `UserValidator `is server side and you would do it with regex or linq, right? If so, on the client side you would use `RegularExpression`? cheers

**Comment by HaoK** [comment]
Up to you, but if you are just trying to block starting with ".", you can simply check for starts/EndsWith

**Comment by Ponant** [comment]
Yep, I was however unclear on whether UserValidator remains server side only, I think it does.

**Comment by HaoK** [comment]
Ah yes its server side only

**Comment by HaoK** [comment]
The client side validation you would need to do in your view (i.e with annotations on your model)

**Comment by Ponant** [comment]
OK thanks a lot
