### ISSUE TITLE
Token Expiration

### ISSUE THREAD

**Issue by satyajit-behera** [aspnet/Identity#562]
There are no ways where a generated Token for asp.net web api can be forced to expire other than the default time allocated to the token.

It may be good to have a mechanism where the token can be expired when the user logout or some other scenarios where the token needs to be deactivated.

Thanks

**Comment by rustd** [comment]
How and where are you generating token?

**Comment by stephenstroud** [comment]
@satyajit-behera I achieved this with JwtBearerAuthentication(VNext), the tokens are self contained, so you can't force it, however, you can persistently store the token and validate it exists when making requests or delete it on logout so subsequent requests will be denied. You could also achieve sliding token lifetimes in the same way. You could do the same with the older version OAuthBearerTokens.

**Comment by satyajit-behera** [comment]
Thanks @stephenstroud Can you give some more details or reference examples to elaborate this.

**Comment by satyajit-behera** [comment]
thanks @rustd . I am using the default asp.net identity provider while using the web api template in visual studio.

**Comment by stephenstroud** [comment]
@satyajit-behera  which template version are you using? Are you using VS 2013?

**Comment by satyajit-behera** [comment]
@stephenstroud  VS 2013
