### ISSUE TITLE
login attempt with bad password is revealing the locked out status

### ISSUE THREAD

**Issue by bmrpatel** [aspnet/Identity#563]
refer to #537 for more info. Please let me know and I will provide more details.

**Comment by HaoK** [comment]
We don't think this is an issue because your app doesn't need to show different error messages for lock out/wrong password.  Can you explain why you feel this is an issue?

**Comment by bmrpatel** [comment]
When someone tries wrong password, Identity framework returns that user is locked out. I only want to show that user is locked out if the password is correct. How would I do this? 

*Please don't close the issue before you understand my issue first.*

**Comment by PinpointTownes** [comment]
Congrats, you made @blowdart rant :trollface: 

![image](https://cloud.githubusercontent.com/assets/6998306/10208664/30a35698-67d5-11e5-9d8e-7ed4f2146b3f.png)

**Comment by HaoK** [comment]
Check the password manually first as you pointed out in the other issue.

**Comment by HaoK** [comment]
We don't check the password if you are locked out in the other method.  So if you really care that much, you need to check yourself

**Comment by blowdart** [comment]
We do close issues because the issue opener hasn't responded within what we consider a reasonable amount of time.

**Comment by HaoK** [comment]
Well in this case, it wasn't that.  This is by design :)

**Comment by bmrpatel** [comment]
@HaoK I understand that it is by design. I am sure there is a reason behind this. Possibly to make it faster in case of user locked out (so no need to check for password). :smile: 

@blowdart  Sorry, but I wasn't passive aggressive. This is the second issue(question) I created for this and closing comments weren't very clear to me. I think have responded to comments in detail.
