### ISSUE TITLE
Cookie persistence

### ISSUE THREAD

**Issue by dvdcrr77** [aspnet/Identity#564]
I am not sure if this is the desired behaviour but when expiration is set via ConfigureIdentityApplicationCookie and then making a call to PasswordSignInAsync with persist the token is not being set even though the signin status result is returning success status.

**Comment by rustd** [comment]
Can you please post your Startup code where you configure.

**Comment by dvdcrr77** [comment]
Its been a while I can't seem to replicate the issue as of this moment.
