### ISSUE TITLE
IdentityBuilder does not contain AddSignInManager however it do contain AddUserManager 

### ISSUE THREAD

**Issue by israelito3000** [aspnet/Identity#565]
If you want to implement your own SignInManager and UserManager you have to activate them like:
```
services.AddScoped(typeof(MyUserManager<IUser>));
services.AddScoped(typeof(MySignInManager<IUser>));

services.AddIdentity<ApplicationUser, ApplicationRole>()
```

so what is the purpose of: AddUserManager
```
services.AddIdentity<ApplicationUser, ApplicationRole>()
.AddUserManager<MyUserManager<IUser>>() 
```
it does not work.

would be better if we can declare them like:
```
services.AddIdentity<ApplicationUser, ApplicationRole>()
.AddSignInManager<MySignInManager<IUser>>() 
.AddUserManager<MyUserManager<IUser>>()
```
or simply remove the AddUserManager method.

**Comment by rustd** [comment]
We are not going to have this for RTM but will consider it for the future.

**Comment by HaoK** [comment]
27f021ab933a153eb977318e844a74f8497e3b47
