### ISSUE TITLE
Hard to extend SignInManager, property UserManager need more visibility (protected)

### ISSUE THREAD

**Issue by israelito3000** [aspnet/Identity#566]
I was trying to add PasswordExpiration to the current framework and I found a very hard mechanism to extend SignInManager. Currently UserManager is private as well as other important methods like: PreSignInCheck, IsLockedOut, ResetLockout, In my case I needed to create another: PasswordSignInAsync method and ask for password expiration after PasswordCheck but many methods are private, seems like this class is not ready to be extended or customized.

**Comment by HaoK** [comment]
acfee9e7e05bfb8ef25c8a7628c200c4cc715ff0
