### ISSUE TITLE
Clarification from the AccountControllers view - lockout is set in 2 different places

### ISSUE THREAD

**Issue by winecraft** [aspnet/Identity#568]
Hello, I am using the Microsoft guidance from your blog and your sample code. Is the AccountController there still valid? 

For e.g. there are references to the `SigninManager` and `Helper` helping to configure lockout... can you please help on how to proceed forward?

1. Inside this class... you've 

           public class ApplicationUserManager : UserManager<ApplicationUser, string>
           ...
           // Configure user lockout defaults
            manager.UserLockoutEnabledByDefault = true;
            manager.DefaultAccountLockoutTimeSpan = TimeSpan.FromMinutes(5);
            manager.MaxFailedAccessAttemptsBeforeLockout = 5; \\ why is it set here too?

2.  but in another section it set to `false` below...

        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {            
            // This doen't count login failures towards lockout only two factor authentication
            // To enable password failures to trigger lockout, change to shouldLockout: true
            var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, 
           model.RememberMe, shouldLockout: false); \\its set to false here?
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(returnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");

            }
        }

I am a little lost as I try to implement the identity and security, can you please shed some light on and provide guidance how to what the old account controller was doing, and what to discard from that sample... 

As we upgrade to this version, do you now have  _new_ helper classes that handle the old AccountHelpers functionality?

**Comment by rustd** [comment]
This issue is for ASP.NET Identity v2. This repo is for ASP.NET Identity v3. Can you please ask this question on aspnetidentity.codeplex.com

Is your question around migrating to v3?
