### ISSUE TITLE
Multitenancy and Groups, for e.g. mapping users and common roles to unique companies

### ISSUE THREAD

**Issue by winecraft** [aspnet/Identity#569]
Hello, please help with a feature or some guidance - how is a public SaaS web app, beyond an intranet to handle multi-tenancy with just roles and users, when the same roles can exist across various groups such as companies registering?

In a web app, there are many common `Roles` for e.g. employees, managers etc. across companies...

While you let us extend the users and roles, there is no-convenient way or **no-mapping** of these common roles(mgrs) to unique companies(groups) and their users. For e.g. `Walmarts-Managers` vs `HomeDepot-Managers`, how do the developers map this for a Saas web app, outside a company/intranet scenario?

For instance, starting at one level above, how can I say 
`Group("Targett").GetRole("Managers").ToList();` or 
`Group("CNNN").GetRole("Editors").ToList();`

**Comment by rustd** [comment]
Identity is not meant for multi-tenant scenarios.
