### ISSUE TITLE
Request: Improve MSDN documentation on ASP.NET Identity 3

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Identity#576]
Currently, the information available on the different types and approaches of ASP.NET Identity 2 is a mess. There is not a single comprehensive documentation available on the web. A documentation on the `IAppBuilder` interface is not even available anywhere.

I wonder how people are supposed to take educated decisions if there is no comprehensive documentation available? Are we supposed to wade through tons of confined tutorials and samples, each written by another author, to eventually and hopefully grasp the big picture some time in the future?

As a paying MSDN Premium subscriber I strongly propose that Microsoft resources are acquired to create a comprehensive documentation von ASP.NET Identity 3 - before its final release.

**Comment by rustd** [comment]
Thank you for your feedback. Documentation for ASP.NET 5/ Identity 3 is open sourced https://github.com/aspnet/Docs/blob/master/aspnet/index.rst and can be found here docs.asp.net/
