### ISSUE TITLE
The CancellationTokenSource has been disposed

### ISSUE THREAD

**Issue by GVX111** [aspnet/Identity#578]
When I authorizing showing this error:
The CancellationTokenSource has been disposed
Can someone help me?

**Comment by rustd** [comment]
Is there a repro available? There is not enough detail in this bug.

**Comment by BenjiZombie** [comment]
I'm also experiencing this issue with beta7. 

I've implemented a custom `AspNetIdentityUserService` for signing in into my app. This service is registered as Scoped in my DI. `UserManager<ApplicationUser>` is also registered as Scoped by the `services.AddIdentity<ApplicationUser, IdentityRole>()()` registration in `Startup.cs`.

	public AspNetIdentityUserService(UserManager<ApplicationUser> userManager)
	{
		Check.NotNull(userManager, nameof(userManager));

		_userManager = userManager;
	}

Here, ApplicationUser is `IdentityUser<string>`.

Upon POSTing my credentials, this function gets called:

	public override async Task AuthenticateLocalAsync(LocalAuthenticationContext context)
	{
		if (_userManager.SupportsUserPassword)
		{
			// Crashes here
			var user = await _userManager.FindByNameAsync(context.UserName);
			...
		}
	}

Here's the relevant output:

	Microsoft.Data.Entity.Storage.Database: Information: Compiling query model: 'from ApplicationUser u in value(Microsoft.Data.Entity.Query.EntityQueryable`1[My.IdentityProvider.AspNetIdentity.Models.ApplicationUser]) where ([u].NormalizedUserName == __normalizedUserName_0) select [u] => FirstOrDefault()'
	Microsoft.Data.Entity.Storage.Database: Information: Optimized query model: 'from ApplicationUser u in value(Microsoft.Data.Entity.Query.EntityQueryable`1[My.IdentityProvider.AspNetIdentity.Models.ApplicationUser]) where ([u].NormalizedUserName == __normalizedUserName_0) select [u] => FirstOrDefault()'
	Microsoft.Data.Entity.Storage.Database: Information: Tracking query sources: [u]
	Microsoft.Data.Entity.Storage.Database: Information: TRACKED: True
	(QueryContext prm0, QueryResultScope prm1) => () => IAsyncEnumerable<ApplicationUser> TaskToSequence(
		task: Task<ApplicationUser> FirstOrDefault(
			source: IAsyncEnumerable<ApplicationUser> _Select(
				source: IAsyncEnumerable<QueryResultScope> _SelectMany(
					source: IAsyncEnumerable<QueryResultScope> _ToSequence(
						element: prm1
					)
					, 
					selector: (QueryResultScope prm1) => IAsyncEnumerable<QueryResultScope<ApplicationUser>> _ShapedQuery(
						queryContext: prm0, 
						commandBuilder: SelectExpression: 
							SELECT TOP(1) "u"."Id", "u"."AccessFailedCount", "u"."ConcurrencyStamp", "u"."Email", "u"."EmailConfirmed", "u"."LockoutEnabled", "u"."LockoutEnd", "u"."NormalizedEmail", "u"."NormalizedUserName", "u"."PasswordHash", "u"."PhoneNumber", "u"."PhoneNumberConfirmed", "u"."SecurityStamp", "u"."TwoFactorEnabled", "u"."UserName"
							FROM "AspNetUsers" AS "u"
							WHERE "u"."NormalizedUserName" = @__normalizedUserName_0
						, 
						shaper: (ValueBuffer prm2) => QueryResultScope<ApplicationUser> CreateEntity(
							querySource: from ApplicationUser u in value(EntityQueryable`1[My.IdentityProvider.AspNetIdentity.Models.ApplicationUser]), 
							queryContext: prm0, 
							parentQueryResultScope: prm1, 
							valueBuffer: prm2, 
							valueBufferOffset: 0, 
							entityType: My.IdentityProvider.AspNetIdentity.Models.ApplicationUser, 
							queryStateManager: True, 
							entityKeyFactory: SimpleNullSentinelEntityKeyFactory`1, 
							keyProperties: List<Property> { ApplicationUser.Id, }, 
							materializer: (ValueBuffer prm3) => 
							{
								var var4
								var4 = new ApplicationUser()
								var4.Id = (string) object prm3.get_Item(0)
								var4.AccessFailedCount = (int) object prm3.get_Item(1)
								var4.ConcurrencyStamp = (string) object prm3.get_Item(2)
								var4.Email = (string) object prm3.get_Item(3)
								var4.EmailConfirmed = (bool) object prm3.get_Item(4)
								var4.LockoutEnabled = (bool) object prm3.get_Item(5)
								var4.LockoutEnd = (Nullable<DateTimeOffset>) object prm3.get_Item(6)
								var4.NormalizedEmail = (string) object prm3.get_Item(7)
								var4.NormalizedUserName = (string) object prm3.get_Item(8)
								var4.PasswordHash = (string) object prm3.get_Item(9)
								var4.PhoneNumber = (string) object prm3.get_Item(10)
								var4.PhoneNumberConfirmed = (bool) object prm3.get_Item(11)
								var4.SecurityStamp = (string) object prm3.get_Item(12)
								var4.TwoFactorEnabled = (bool) object prm3.get_Item(13)
								var4.UserName = (string) object prm3.get_Item(14)
								var4
							}
						)
					)
				)
				, 
				selector: (QueryResultScope prm1) => ApplicationUser prm1._GetResult(
					querySource: from ApplicationUser u in value(EntityQueryable`1[My.IdentityProvider.AspNetIdentity.Models.ApplicationUser])
				)
			)
			, 
			cancellationToken: prm0.CancellationToken
		)
	)

	Microsoft.Data.Entity.Query.QueryContextFactory: Error: An exception occurred in the database while iterating the results of a query.
	System.ObjectDisposedException: The CancellationTokenSource has been disposed.
	   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
	   at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
	   at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSynchronizationContext, Boolean useExecutionContext)
	   at System.Threading.CancellationToken.Register(Action callback)
	   at System.Linq.AsyncEnumerable.<>c__DisplayClass29`1.<Create>b__27(CancellationToken ct)
	   at System.Linq.AsyncEnumerable.AnonymousAsyncEnumerator`1.MoveNext(CancellationToken cancellationToken)
	   at System.Linq.AsyncEnumerable.FirstOrDefault[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
	   at lambda_method(Closure )
	   at Microsoft.Data.Entity.Query.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
	Exception thrown: 'System.AggregateException' in mscorlib.dll
	The program '[37844] iisexpress.exe' has exited with code 0 (0x0).

**Comment by rustd** [comment]
Can you make sure that your code is not running after the request is done?

**Comment by rustd** [comment]
Try changing the lifetime to be Singleton of  AspNetIdentityUserService

**Comment by divega** [comment]
> Try changing the lifetime of AspNetIdentityUserService to be Singleton to see if this fixes this issue.

Just to clarify, this is a way to test the hypothesis that what is happening is that your service is getting disposed before the query executes, not necessarily a good workaround.

**Comment by BenjiZombie** [comment]
@rustd It previously was registered as Singleton and I had the same issue. The UserManager<> passed in my service's ctor was then invalid since it had been disposed (since UserManager<> is Scoped).

**Comment by gvx111** [comment]
@rustd can you post example how to change?

**Comment by HaoK** [comment]
@BenjiZombie Can you give us your startup.cs to start?

**Comment by gvx111** [comment]
<pre>   public static class UserStore
    {
        public static IApplicationBuilder UseUserStore(this IApplicationBuilder app)
        {
            app.UseStaticFiles()
               .UseIdentity()
               .UseDeveloperExceptionPage();

            return app;
        }

        public static IServiceCollection UserStoreServices(this IServiceCollection services)
        {
            services.AddEntityFramework()
                   .AddSqlServer()
                   .AddDbContext<EfContext>(options => options.UseSqlServer("Server=****"));

            services.AddEntityFramework()
                 .AddSqlServer()
                 .AddDbContext<AccountContext>(options => options.UseSqlServer("****"));

            services.AddIdentity<Account, IdentityRole>(e =>
            {
                e.Password.RequireLowercase = false;
                e.Password.RequireUppercase = false;
                e.Password.RequireNonLetterOrDigit = false;
                e.Password.RequiredLength = 6;
            })
                    .AddEntityFrameworkStores<AccountContext>()
                    .AddDefaultTokenProviders();

            return services;
        }
    }</pre>
it isextenssion.

**Comment by HaoK** [comment]
Where's the code that actually calls this in startup

**Comment by gvx111** [comment]
<pre>   public IServiceProvider ConfigureServices(IServiceCollection services) {

            services
                .UserStoreServices()
                .WebHost();

            services.Modules("~/Modules");
            services.AddSignalR(options =>
            {
                options.Hubs.EnableDetailedErrors = true;
            });
            return services.BuildServiceProvider();
        }

        public void Configure(IApplicationBuilder builder, IHost host, ILoggerFactory loggerFactory) {
            builder.UseUserStore();

            builder.UseFileServer();

            builder.UseSignalR();
            builder.ConfigureHost(loggerFactory);
            host.Start();
        }</pre>

**Comment by HaoK** [comment]
What does host.Start() do?  That certainly looks like it could cause lifetime issues.

**Comment by rustd** [comment]
Can you please try reproing this without SignalR?

**Comment by divega** [comment]
@halter73 I hope you may have enough context to be able to comment on this. In summary:

- @gvx111 is using SingalR with Identity (see the [startup.cs](https://github.com/aspnet/Identity/issues/578#issuecomment-149386966) above) 
- If this was a regular MVC app the exception he is observing would be a symptom of trying to do work with services obtained from a DI scope that has been disposed (Identity's UserManager will flow the HTTP context accesor's `RequestAborted` as the `CancellationToken` to all database calls).

Would you expect this to work? Would you expect it to fail under certain conditions, e.g. if the connection is dropped?

**Comment by gvx111** [comment]
I have already removed Signalr from my project and same problem.

**Comment by divega** [comment]
Ok @gvx111. Would it be possible for you to provide the full repro with SignalR removed?

**Comment by gvx111** [comment]
I can't because it is Framework and 10 Projects are referenced. :| I can show you debug mode.

**Comment by halter73** [comment]
@divega Sorry I missed your @ mention yesterday. Even if a connection is dropped, SignalR should wait until it is finished invoking user code before completing the app func and allowing scoped services to be disposed.

There might be an issue with the WebSocket transport and async Hub methods, but since @gvx111 said this repros without SignalR it looks like I'm off the hook for now :)

**Comment by gvx111** [comment]
I think problem is another.
When i enter wrong password SignInResult return Failed.
I trying to debug singin ExceptionMessage: InnerException = {"The connection was not closed. The connection's current state is open."}
<pre>
  public async void TestLogin(HttpContext httpContext)
        {
            try
            {
                var user = new Account() { UserName = "GVX111" };
                var manager = (UserManager<Account>)httpContext.RequestServices.GetService(typeof(UserManager<Account>));

                var contextAccessor = (IHttpContextAccessor)httpContext.RequestServices.GetService(typeof(IHttpContextAccessor));
                var roleManager = (RoleManager<IdentityRole>)httpContext.RequestServices.GetService(typeof(RoleManager<IdentityRole>));
                var identityOptions = new IdentityOptions();
                var options = (IOptions<IdentityOptions>)httpContext.RequestServices.GetService(typeof(IOptions<IdentityOptions>));
                var claimsFactory = new UserClaimsPrincipalFactory<Account, IdentityRole>(manager, roleManager, options);
                var logStore = new StringBuilder();
                var logger = (ILogger<SignInManager<Account>>)httpContext.RequestServices.GetService(typeof(ILogger<SignInManager<Account>>));
                var helper = new SignInManager<Account>(manager, contextAccessor, claimsFactory, options, logger);

                // Act
                var result = await helper.PasswordSignInAsync(user.UserName, "123321", false, false);
            }
            catch (Exception e)
            {
                throw;
            }  
        }
</pre>

**Comment by gvx111** [comment]
@halter73 @divega I found problem. Error on GetSecurityStampAsync()

**Comment by HaoK** [comment]
Please reopen this if the issue is still happening for you
