### ISSUE TITLE
Beta 8?

### ISSUE THREAD

**Issue by angelsix** [aspnet/Identity#580]
Any idea when beta 8 is out? I have to use beta 8 of Entity Framework and with ASP.Net Identity only in beta 7 there are a lot of conflicts.

**Comment by GuardRex** [comment]
The milestones for dnx, dnvm, identity, abstractions, configuration, diagnostics, hosting, security, razor, and mvc are 100%. Entity Framework is showing 94% with 3 open issues. DI and Common are 75% each with 1 open issue each. Must be close!

**Comment by angelsix** [comment]
Cool. If Identity is 100% is there anyway to get it? Does it mean the github identity dev repo is the "beta8" as it currently stands?

To be more specific of my issue I'm getting a MethodMissingException in Mvc when adding an Identity provider (an Entity Framework one)

services.AddIdentity<IdentityUserDataModel, IdentityRoleDataModel>()

Which I am guessing is due to the fact the extesion AddIdentity is beta7, and my identity provider and almost all other parts of the app are beta 8.

**Comment by angelsix** [comment]
Also, I could use Beta 7 if I could define a one to many relationship as thats the only thing I cannot find in beta 7 (the .HasMany calll):

I would need to do the following equivalent in beta 7:
b.Many(u => u.Claims).WithOne().ForeignKey(uc => uc.UserId);

Where u is a user that has multiple claims, and the claim has a UserId referencing the Id of the user

**Comment by rustd** [comment]
Please see https://github.com/aspnet/Home/wiki/Roadmap for the updated dates for beta8

**Comment by hieupious** [comment]
How about beta 8? I don't see any updates from it.
