### ISSUE TITLE
Where did IUser go?

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/Identity#584]
I'm using Elastic DB and don't want to use your baked in implementation for EntityFramework. In the past I used IUser<> and all of the rest of the interfaces. They all appear to be there in AspNet 6 except IUser which makes them largely useless.

What am I missing?

**Comment by rustd** [comment]
IUserStore is the one that has this functionality now. You need to implement IUserStore

**Comment by JohnGalt1717** [comment]
Ok, in the past IUserStore also required an implementation of IUser?
