### ISSUE TITLE
Indentity To INT

### ISSUE THREAD

**Issue by gvx111** [aspnet/Identity#587]
Application startup exception: System.Reflection.TargetInvocationException: Exce
ption has been thrown by the target of an invocation. ---> System.ArgumentExcept
ion: GenericArguments[0], 'ITN.TS.UserStore.Models.Account', on 'Microsoft.AspNe
t.Identity.EntityFramework.UserStore`3[TUser,TRole,TContext]' violates the const
raint of type 'TUser'. ---> System.TypeLoadException: GenericArguments[0], 'ITN.
TS.UserStore.Models.Account', on 'Microsoft.AspNet.Identity.EntityFramework.User
Store`4[TUser,TRole,TContext,TKey]' violates the constraint of type parameter 'T
User'.
<pre> 
services.AddIdentity< Account, IdentityRole >()
               .AddEntityFrameworkStores< AccountContext, int >()
               .AddDefaultTokenProviders();
</pre>
<pre>
public class ApplicationUserLogin : IdentityUserLogin<int> { }
    public class ApplicationUserRole : IdentityUserRole<int> { }
    public class ApplicationUserClaim : IdentityUserClaim<int> { }

    public sealed class ApplicationRole : IdentityRole<int>
    {
        public ApplicationRole() { }
        public ApplicationRole(string name) { Name = name; }
    }

    public class ApplicationUserStore : UserStore<ApplicationUser, ApplicationRole, AccountContext, int>
    {
        public ApplicationUserStore(AccountContext context) : base(context) { }
    }

    public class ApplicationRoleStore : RoleStore<ApplicationRole, AccountContext, int>
    {
        public ApplicationRoleStore(AccountContext context) : base(context) { }
    }

    public class ApplicationUser : IdentityUser<int>
    {

    }

    public sealed class AccountContext : IdentityDbContext<ApplicationUser, ApplicationRole, int>
    {
        private static bool _created = false;
        public DbSet<Account> Accounts { get; set; }
        public DbSet<AccountMeta> AccountMeta { get; set; }

        public AccountContext()
        {
            // Create the database and schema if it doesn't exist
            // This is a temporary workaround to create database until Entity Framework database migrations 
            // are supported in ASP.NET 5 
            if (!_created)
            {
                Database.Migrate();
                // this.Configuration.ProxyCreationEnabled = false;
                _created = true;
            }
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=sql.alltours.ge;Database=TSS; User Id=sa; Password=Gitara123; MultipleActiveResultSets=true");
        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            builder.Entity<Account>(e => {
                                             e.HasKey("Id");
                                             e.HasMany(a => a.AccountMeta).WithOne(a => a.Account); e.ToTable("Accounts");
            });
            builder.Entity<Role>(e => { e.HasKey("Id"); e.ToTable("Roles"); });

        }
    }
</pre>

**Comment by DAllanCarr** [comment]
I think the Account class is being incorrectly mapped in the call to AddIdentity.

**Comment by gvx111** [comment]
Its my account class
<pre> public class Account : IdentityUser
    {
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public DateTime Birthdate { get; set; }
        public bool Gender { get; set; }
        public virtual ICollection<AccountMeta> AccountMeta { get; set; }
        public string GetGender()
        {
            return Gender ? "Male" : "Female";
        }
    }</pre>
Whats wrong?

**Comment by DAllanCarr** [comment]
Looks good I just saw this code and was not sure.

```
 public class ApplicationUser : IdentityUser
    {

    }
```

**Comment by DAllanCarr** [comment]
Diving into the codebase all of the identity classes use string keys by you ar requesting an int key type

https://github.com/aspnet/Identity/blob/5da757642dd7c7a25315250ae3738b87f622cb4c/src/Microsoft.AspNet.Identity.EntityFramework/IdentityEntityFrameworkServices.cs#L22-L23

**Comment by GuardRex** [comment]
May I suggest ...
```
public bool Gender { get; set; }
```
to
```
public bool HasPenis { get; set; }
```
... jk, but it's not very nice referring to women as a "false" gender. :smile:

**Comment by rustd** [comment]
Please refer this test and derive from `IdentityUser<int>`
https://github.com/aspnet/Identity/blob/dev/test/Microsoft.AspNet.Identity.EntityFramework.Test/UserStoreIntKeyTest.cs#L9
