### ISSUE TITLE
EntityFramework.MicrosoftSqlServer depency in Microsoft.AspNet.Identity.EntityFramework

### ISSUE THREAD

**Issue by rbarbe** [aspnet/Identity#588]
It seems that EntityFramework.MicrosoftSqlServer is not needed for Microsoft.AspNet.Identity.EntityFramework project.
It should be replaced by EntityFramework.Relational

**Comment by HaoK** [comment]
a754b9cb6186aa5ad39d67a5f184244295049fa7
