### ISSUE TITLE
Optional IRoleStore

### ISSUE THREAD

**Issue by fabiomaulo** [aspnet/Identity#589]
Previously the IRoleStore was an optional implementation but now is "something mandatory" due IdentityServiceCollectionExtensions.AddIdentity extension. 
As you know we can use just the ClaimType Role to store user's role (user claims are enough in many cases)
Nice to have :
IdentityServiceCollectionExtensions.AddIdentity without the IRoleStore impl.
Thanks

**Comment by rustd** [comment]
Does #581 capture your requirements?

**Comment by rustd** [comment]
Closing as #581 is capturing this. Please add any more details to #581
