### ISSUE TITLE
Decouple Identity.EntityFramework from Web Project?

### ISSUE THREAD

**Issue by lazarofrancoe** [aspnet/Identity#592]
HI !
    I updated to beta-8, now I can reference Library Class Projects from my Web Project in order to decouple the solution. 
    But I'd like to know if it's possible install Microsoft.AspNet.Identity.EntityFramework in a Library Class Projects, so the Web Project doesn't have any references to persistence elements. I was able to install EntityFramework.SqlServer, but when trying to install Microsoft.AspNet.Identity.EntityFramework, the next output:

"Cannot install the package 'Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta8'. You are trying to install this package for a project that has Version=v4.5.1 as target..."

Thank you!

**Comment by rustd** [comment]
ASP.NET Identity 3 can only be used in ASP.NET 5 projects. You can install this package in DNX based Class Library projects
