### ISSUE TITLE
Test coverage for cascade deletes of UserClaims and UserLogins and RoleClaims

### ISSUE THREAD

**Issue by divega** [aspnet/Identity#593]
We should have a case with nullable `TKey` types to avoid regressing that scenario, since EF will not cascade if the FK doesn't appear to be required.

**Comment by HaoK** [comment]
Won't get to this in RC2

**Comment by HaoK** [comment]
This looks like its already covered by the UserStoreStringKeyTest which tests cascading deletes from SqlStoreBaseTest's DeleteUserRemovesFromRoleTest using string for TKey
