### ISSUE TITLE
ASP.NET Identity generates tokens (e.g. email confirmation, password reset) even when User.SecurityStamp is null

### ISSUE THREAD

**Issue by christophermllr** [aspnet/Identity#598]
I noticed that ASP.NET Identity will still generate tokens even if the user's SecurityStamp is null.  My understanding is that these tokens would never be valid.  Shouldn't UserManager throw an Exception in this case?

Possibly out of scope because if the user is created using UserManager, SecurityStamp won't be null.  However, as was the case for me, if an external process is creating users by manually forcing them into the AspNetUsers table, SecurityStamp could be null.

**Comment by rustd** [comment]
Default should always have a value.

**Comment by divega** [comment]
To clarify: we discussed this and came to the conclusion that we should create a SecurityStamp early on when the user is added.

**Comment by HaoK** [comment]
I looked and the security stamp is always set to something if the user was created via identity APIs.  So If the user was created in some other fashion, a valid (non null) security stamp should be created as well as part of that process.  Or simply update the user in some other fashion before trying to use the two factor APIs that require a stamp.

**Comment by HaoK** [comment]
The current behavior is by design
