### ISSUE TITLE
Migration Identity 2.0 to 3.0 namespaces

### ISSUE THREAD

**Issue by joshmouch** [aspnet/Identity#600]
When migrating from Identity 2.0 to 3.0, am I correct in assuming that the namespaces Microsoft.Owin.* have been replaced replaced by Microsoft.AspNet.*?
Are the classes within functionally similar (enough to start the migration off with, at least)?

**Comment by rustd** [comment]
There are more changes other than namespaces. We will be documenting the migration process https://docs.asp.net/en/latest/migration/index.html
For now you can create a new ASP.NET 5 Web Application with Individual Account and compare the Startup class and Account/ Manage Controller to look at the code changes.
Closing this as this is not a bug.
