### ISSUE TITLE
Add support for UserManager CreateAsync to add external login as an atomic operation

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Identity#601]
Right now, if you look at the templates of Individual Account you will see code like this:

```csharp
// ...
var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
var result = await _userManager.CreateAsync(user);
if (result.Succeeded)
{
    result = await _userManager.AddLoginAsync(user, info);
    if (result.Succeeded)
    {
        await _signInManager.SignInAsync(user, isPersistent: false);
        return RedirectToLocal(returnUrl);
    }
}
AddErrors(result);
```

Interesting enough, if `AddLoginAsync` fails, the result is a new user with no way to log in nor register again.

> *This happens if, for example, email confirmation is required.* https://github.com/aspnet/Templates/issues/242 for details.

But that may not be the only reason, it could be because server error, or whatever.
I think it will be great if we can add a new overload to `CreateAsync` that accepts `UserLoginInfo` so instead of the above code, we can have

```csharp
// ...
var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
var result = await _userManager.CreateAsync(user, info);
if (result.Succeeded)
{
    await _signInManager.SignInAsync(user, isPersistent: false);
    return RedirectToLocal(returnUrl);
}
AddErrors(result);
```

The current workaround is to set `UserStore.AutoSaveChanges = false;` and manage all the `SaveChanges` operations manually.
or delete the user in case of fails (which introduces another point of failure on the delete operation itself).

Thoughts?

**Comment by HaoK** [comment]
@rustd we can consider deleting the user if AddLogin fails in this flow (or they might be able to still reset their password today)

**Comment by Bartmax** [comment]
Meh...
