### ISSUE TITLE
ASP.NET Identity 3: What is the standard procedure for using local authentication plus OpenID Connect?

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Identity#603]
I want my users to choose between either creating a local account (similar to the early Forms Authentication) and logging in using OpenID Connect using one of their existing social provider accounts.

What's the standard procedure for providing for this using ASP.NET Identity 3?

What steps are neccessary to be added to the DB to provide for storing user preferences no matter which kind of log in the user chooses?

**Comment by rustd** [comment]
You can add OpenIdConnect middleware as another provider. If you create ASP.NET 5 Web App with Individual Account, it comes with Facebook and other providers. You can login and store user information in the database. You can add OpenIdConnect in a similar manner.
I am closing this issue as this is not a product bug.
