### ISSUE TITLE
Controller in API meaning , should not redirect to Login View on unauthorized access

### ISSUE THREAD

**Issue by Gentlehag** [aspnet/Identity#604]
A very common usecase is that controllers used in an api style way are supposed to have other behavior on unauithorized access then view style controllers.

In detail this means: When having an unauthorized acces  the expected behavior for controller used in a view orientied way is to redirect to a login page with status code 200 ; a api style controller should return a status code indicating NotAuthoried and not redirecting to the login view.

As there are no technical differences anymore between these two kinds of controller they behave the same way .

There are workarounds like described here:

http://stackoverflow.com/questions/33375322/asp5-unauthorized-acces-should-return-401-and-200-not-login-page?noredirect=1#comment54562421_33375322

But they smell. It would be better to have a more expressive way. Like Annotating the Controler or at least have a ExtensionMethod simplifying things.

**Comment by Gentlehag** [comment]
any thoughts about this?

**Comment by HaoK** [comment]
@blowdart can you comment on this?

**Comment by blowdart** [comment]
I am confused. Are you accessing the controllers with cookie auth? Only interactive auth schemes would issue a redirect. You ought to be using a bearer scheme for WebAPI controllers.

@HaoK didn't we discuss changing this in security so the redirect didn't happen on Ajax requests if you did do the wrong thing and used cookies?

This isn't an identity issue, it's a security middleware issue.

**Comment by HaoK** [comment]
Yeah in rc1 we added some logic where cookies doesn't redirect for XmlHttpRrequests, it just sets the location header

**Comment by blowdart** [comment]
So that would fix this issue, probably. Can you link this issue to that commit?

**Comment by HaoK** [comment]
Sure fixed by 1d2c6ba1223748df02a879622e8deb6ac23db5b7

**Comment by MaximRouiller** [comment]
Is there an actual link? Finding the commit hash for this can be hard. Which repo at least?

**Comment by joshmouch** [comment]
What is the link and what is the fix?

**Comment by divega** [comment]
https://github.com/aspnet/Security/commit/1d2c6ba1223748df02a879622e8deb6ac23db5b7
