### ISSUE TITLE
Should NTLM/Negotiate show up as External Auth Types in Templates

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#607]
[Also they don't currently work when clicked on, so if the answer is yes, we need to make them work :)]

We have some logic in SignInManager that returns all auth types that have a DisplayName.  This will include windows auth which doesn't actually work

**Comment by rustd** [comment]
rc1?

**Comment by HaoK** [comment]
Isn't that more or less done?  Just hide them for rc1 and we can figure out what the right thing to do is with this bug.

**Comment by rustd** [comment]
Yeah. Templates have a workaround for rc1

**Comment by HaoK** [comment]
Replaced by https://github.com/aspnet/Identity/issues/614
