### ISSUE TITLE
Forcing recreation of User Principal

### ISSUE THREAD

**Issue by jerriep** [aspnet/Identity#608]
I have a CustomSignInManager class which inherits from `SignInManager<ApplicationUser>`. In the `CreateUserPrincipalAsync` method I set a couple of claims which I read from the `ApplicationUser` class, so they can be retrieved easily elsewhere in the application without having to re-query the database.

This al works great, but because these are value which are stored on the ApplicationUser class, when the user actually updates these values I want the User Principal to be recreated.

I thought I could just make a call to `_signInManager.CreateUserPrincipalAsync(user)` but this does not work as it does not update the cookie I believe.

The only way I could get it to work is to actually sign in the user again by calling `await _signInManager.SignInAsync(user, true);` but I am not sure whether this is preferable.

Is there another way to force the User Principal, which as far as I understand is stored in the cookie, to be updated without calling `SignInAsync()` again?

**Comment by rustd** [comment]
You can also call UpdateSecurityStamp() on UserManager which will update the cookie automatically whenever the SecurityStamp changes.
