### ISSUE TITLE
error CS0648: '' is a type not supported by the language

### ISSUE THREAD

**Issue by miroslavsiska** [aspnet/Identity#609]
I will use no DI scenario for userManager with folowing code:

           const string SuperAdminUserName = "test@test.com"; 
            const string SuperAdminPassword = "Password*";   
            const string adminRole = "ADMIN";
            string con = "Connection string";
            UserManager<ApplicationUser> TESTuserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(TenantDbContext.Create(con)), null, null, null, null, null, null, null, null, null);
            var user = await TESTuserManager.FindByNameAsync(SuperAdminUserName);
            if (user == null)
            {
                user = new ApplicationUser { UserName = SuperAdminUserName, Email = SuperAdminUserName, EmailConfirmed = true };
                var result2 = await TESTuserManager.CreateAsync(user, SuperAdminPassword);
            }

TESTuserManager give me error CS0648: '' is a type not supported by the language

**Comment by rustd** [comment]
This is probably a compilation error and not an exception thrown by Identity.
