### ISSUE TITLE
Navigation Property in IdentityUserRole

### ISSUE THREAD

**Issue by YZahringer** [aspnet/Identity#610]
Hello,

How to add a navigation property in IdentityUserRole to IdentityRole? Why this entity is not customizable like IdentityRole and IdentityUser? Why this navigation property does not exist by default?

Thanks,
Yann

**Comment by rustd** [comment]
Related issue: https://github.com/aspnet/Identity/issues/585

**Comment by HaoK** [comment]
Not going to make it in today

**Comment by blowdart** [comment]
Moving out of backlog and aiming for RC2

**Comment by divega** [comment]
This is not a ship stopper for RC2 so moving to RTM and assigning.

**Comment by HaoK** [comment]
@divega I don't think we can add this navigation property anymore since we are adding the generic arguments back, as `IdentityUser<TKey>` wouldn't be the correct type anymore, rather it would need to be `IdentityUser<TKey, TUserClaim, TUserRole, TUserLogin>` which is circular

**Comment by blowdart** [comment]
As we won't have a navigation property this isn't possible.
