### ISSUE TITLE
Add doc comments for mainline APIs

### ISSUE THREAD

**Issue by Eilon** [aspnet/Identity#612]
At least these APIs:
* AddEntityFrameworkStores method
* UserManager class cleanup
* SignInManager class cleanup
* IdentityDbContext class and methods
* IdentityUser class

**Comment by rustd** [comment]
#532

**Comment by divega** [comment]
Talked to @Eilon and he thinks if we can do some of these for RC1 it would be great. So asking @blowdart, @HaoK and @rustd if that would be possible :smile:

**Comment by blowdart** [comment]
Given your timescales it's doubtful.

**Comment by rustd** [comment]
I emailed you guys with a proposal for a smaller set of docs that we should update for rc1.

**Comment by HaoK** [comment]
379f1928a4d676d2ad14ba026f50b204ed33d518
