### ISSUE TITLE
From IList<T> returning APIs to IReadOnlyList<T> returning ones

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Identity#615]
Some interface APIs return `Task<IList<T>>` which seems weird as I don't want the list I am passing to be mutable. I would rather have `IEnumerable<T>` but I assume it has not been preferred as it may not be evaluated. If that's the case, let's at least return `IReadOnlyList<T>`.

**Comment by rustd** [comment]
This would be a nice to have at this point, but it would be a breaking change from RC1 and does not provide much value to users.
