### ISSUE TITLE
Provide UserClaimsPrincipalFactory<TUser>

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Identity#617]
Currently, `IUserClaimsPrincipalFactory<TUser>` has an implementation as `UserClaimsPrincipalFactory<TUser, TRole>`. However, this is not convinent for implementations which don't support `IRoleStore<TRole>`. Providing `UserClaimsPrincipalFactory<TUser>` would be great.

**Comment by tugberkugurlu** [comment]
Happy to PR for this if this sounds reasonable.

**Comment by HaoK** [comment]
Feel free to submit a PR for this sure :)

**Comment by rustd** [comment]
https://github.com/aspnet/Identity/issues/581

**Comment by jasonwilliams200OK** [comment]
Any progress on this? We should also have `IServiceCollection.AddIdentity<TUser>` without having to specify `TRole`.

**Comment by HaoK** [comment]
@blowdart we should discuss this in triage again

**Comment by HaoK** [comment]
This was done in 2.0 to support roles being optional

**Comment by HaoK** [comment]
Done via https://github.com/aspnet/Identity/issues/1269
