### ISSUE TITLE
Provide IdentityServiceCollectionExtensions.AddIdentity<TUser>

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Identity#618]
Currently, there is an `AddIdentity<TUser, TRole>` extension on `IServiceCollection` which registers bunch of stuff including Role related things. This is not convenient for implementations which don't support `IRoleStore<TRole>`. Providing `AddIdentity<TUser>` and only registering `TUser` related stuff would be nice.

Also, the sample application should use this extension rather than the other one.

**Comment by tugberkugurlu** [comment]
Happy to PR for this if this sounds reasonable.

**Comment by tugberkugurlu** [comment]
This also effects `IdentityBuilder`.

**Comment by tugberkugurlu** [comment]
This is what I had to do now to get around this: https://github.com/tugberkugurlu/Identity/blob/9ba9408e62d7d72446cbf4fc15cf30966ac26557/samples/IdentitySample.Mvc/Startup.cs#L39-L72

**Comment by HaoK** [comment]
Yeah this is the same issue as https://github.com/aspnet/Identity/issues/581.  We are considering it for RC2.  cc @divega

**Comment by tugberkugurlu** [comment]
@HaoK awesome, thx!
