### ISSUE TITLE
(Question) Aspnet Identity only will work with Code First?

### ISSUE THREAD

**Issue by danicomas** [aspnet/Identity#620]

**Comment by divega** [comment]
Sorry for the long time it took for me to answer. If you are referring to the EF6-based store provider that we ship with ASP.NET Identity 1.x and 2.x, I think you should be able to create a derived DbContext that is gets its model from EDMX. 

I haven't tried this myself but you would need to use a constructor that takes a connection string name that points to an EntityClient connection string in the configuration file. @ajcvickers wrote an article that has some good information on how this works: http://blog.oneunicorn.com/2012/02/26/dont-use-code-first-by-mistake/. 

Re the new ASP.NET Core Identity (until recently know as ASP.NET Identity 3.0) it comes with an EF Core-based store and EF Core (until recently known as EF 7) only supports Code First models.

HTH.
