### ISSUE TITLE
UseIdentity is a confusing name -- perhaps a better name is in order?

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#621]
UseIdentity is a confusing name, since ASP.NET Identity is mainly about managing data in a database. This extension method only registers cookie middleware that's used in conjunction with ASP.NET Identity.

Perhaps UseIdentityCookies (or something similar) would be more clear because that indicates it's encapsulating registering several cookie middleware?

**Comment by davidfowl** [comment]
Like, but oh man is this a breaking change

**Comment by brockallen** [comment]
*shrug*

**Comment by mikeandersun** [comment]
:+1:

**Comment by brockallen** [comment]
I guess my main reason for bringing this up is because there's already a lot of confusion over what ASP.NET Identity is and does. Conflating it with cookie middleware just muddies the waters. I'm just trying to suggest an approach for keeping the distinction clear (since the distinction is important, IMO).

**Comment by divega** [comment]
@HaoK @rustd @blowdart thoughts?

I like this suggestion. We would need to check what our bar for breaking changes is going to be post RC1.

**Comment by blowdart** [comment]
Damnit, I agree with @davidfowl. You see what you did @brockallen?

**Comment by HaoK** [comment]
I'm not sure I like it, as we already do slightly more than just include the cookies ( we also ensure that AddIdentity was called here, and in the future could potentially add more identity specific middleware in the future without the name being a problem).  

Another example of where we are just wrapping a middleware would be UseMvc which is basically UseRouting().

Going forward we can always have one single UseIdentity which means add all the identity middleware to the app, which happens to mostly be 3 cookie middlewares today, but this could certainly change/expand to more going forward.

**Comment by brockallen** [comment]
Ok, I can acquiesce on this one. I suppose I'm so used to adding cookie middleware myself that the fact that AddIdentity also does it wasn't obvious. Perhaps this is just an education thing.

At least I was able to frustrate @blowdart.
