### ISSUE TITLE
Why the OwinStartupAttribute?

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Identity#622]
All other plug-ins to ASP.NET are getting configured in Application_Start. Why does Katana take a different approach and use the `OwinStartupAttribute`?

It's hard to examine project behaviour and searching sources if NuGet packages take different approaches for achieving the same kind of result, not abiding by the same strategy.

**Comment by rustd** [comment]
This is not a question for ASP.NET Identity 3. Please ask Katana specific questions http://katanaproject.codeplex.com/
