### ISSUE TITLE
What is necessary in StartUp.Auth.cs to opt-out from having the user agree to reveal his profile data?

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Identity#623]
According to [this article](http://www.asp.net/web-api/overview/security/external-authentication-services), Facebook and Microsoft Account ask the user for revealing user profile data to a web application:

![](http://i1.asp.net/media/4319405/webapimicrosoft03.png?cdn_id=2015-10-16-001)

I only want the user to authenticate. I do not want him/her to reveal anything to my web application. So, what is necessary in Web API code to opt-out from having the user agree to reveal his profile data?

```c#
app.UseMicrosoftAccountAuthentication
    ( clientId: ""
    , clientSecret: ""
    , ... ???
    );
```

**Comment by HaoK** [comment]
This is behavior that comes from the 3rd party auth providers, most likely based on what scopes you ask for (i.e. profile/email)

**Comment by SetTrend** [comment]
Thank you, Hao.

I was looking for some kind of consent, i.e. when providing a particular scope the above confirmation screen would be skipped.

So apparently there is no such consent scope?

Thank you for enlightening me.

**Comment by divega** [comment]
Reopening as a discussion so that @HaoK can answer the last question if possible.

**Comment by HaoK** [comment]
I don't have any further insight into this.  At this point, this is entirely 3rd party auth behavior.  We don't control any of that flow.  Scopes are entirely defined by each auth provider

**Comment by HaoK** [comment]
But to elaborate, I would assume the consent is triggered by what scopes you ask for.  I.e. if you ask for email or any other 'restricted' user info, the consent screen gets triggered.  I doubt you can opt out of that, its probably based on how the user has configured their privacy settings.

**Comment by SetTrend** [comment]
OK, that you for all your efforts.

From what I understand this would be an issue to discuss in the OAuth2/OpenID workgroup then, since the authorization server is proprietearily deciding whether to show a confirmation screen or not. There may be a certain scope to be defined that would be accepted by all security providers to skip the confirmation screen as it only returned the user Id and authorization key, right?
