### ISSUE TITLE
Question about ITicketStore and ApplicationCookie.SessionStore injection

### ISSUE THREAD

**Issue by Schlurcher** [aspnet/Identity#624]
I'm currently playing around with cookies and session storage, as mentioned in the title. I'm trying to write an ITicketStore which uses an IDistrubutedCache to store the AuthTickets.

SqlServerCache is nice enough to provide an extension method to add it to ServiceCollection as IDistributedCache, so no problems there. 
```
services.AddSqlServerCache(options =>
{
    options.ConnectionString = Configuration["Data:DefaultConnection:ConnectionString"];
});
```

My ctor looks like this: ```SqlServerCacheTicketStore(IDistributedCache cache)```

So far so good, but this is where I ran into a problem. How do I register my ITicketStore for injection into CookeAuthOptions.SessionStore? I tried adding it to the ServiceCollection:
```
services.AddTransient<ITicketStore, SqlServerCacheTicketStore>()
```

But this doesn't work, probably because CookieAuthOptions serves as the basis for other Cookies (TwoFactor, External, etc.), and there is no way to indicate for which cookie you wan't the ITicketStore injected?

Is the only way to wire up everything manually for CookieAuthOptions.SessionStorage? Or am I completely off track here and doing something dumb anyways? :)

**Comment by Schlurcher** [comment]
Hi there, again!

After toying around with this on the weekend, I came up with a pretty simple but somewhat smelly solution to avoid wiring up the dependencies manually.
```csharp
public static void AddTicketStore<TTicketStore>(this IServiceCollection services)
    where TTicketStore : class, ITicketStore
{
    // Maybe Singleton is better?
    services.AddScoped<ITicketStore, TTicketStore>();

    // This smells a little...
    var provider = services.BuildServiceProvider();
    var store = provider.GetService<ITicketStore>();
    services.Configure<IdentityOptions>(options =>
    {
        options.Cookies.ApplicationCookie.SessionStore = store;
    });
}
```

It's used during Configure[Staging|Production]Services. I can live with cunked cookies during development, plus no additional setup necessary.

```
public void ConfigureProductionServices(IServiceCollection services)
{
    ConfigureServices(services);
    // Register sql server as IDistributedCache.
    services.AddSqlServerCache(...);
    services.AddTicketStore<DistributedTicketStore>();
}
```

I don't like that I have to use BuildServicePovider() for this. Feels wrong. And it will throw if the services are added in the wrong order.

**Comment by HaoK** [comment]
Yeah the provider model for cookies isn't really DI aware.  cc @Tratcher

**Comment by rustd** [comment]
Closing this and opening it in security https://github.com/aspnet/Security/issues/581
