### ISSUE TITLE
How can I unit test OAuth2 authentication on Web API using Microsoft.Owin.Testing?

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Identity#627]
Hi,

given the following VS solution setup:

```
MySolution
| -- WebApiProject
| -- UnitTestProject
```

I have installed the `Microsoft.Owin.Diagnostics` and `Microsoft.Owin.Testing` NuGet packages.

Now I want to test internal and external authentication using this set-up. How can I do this?

I have been googling this but can't find any documentation on how to apply TestServer here.

Thank you for enlightening me.

**Comment by rustd** [comment]
This is not related to Identity 3. This is a question for the Katana project. Please open an issue http://katanaproject.codeplex.com/

**Comment by SetTrend** [comment]
Actually [I did do that a week ago](http://katanaproject.codeplex.com/discussions/646845). But to no avail. Apparently no-one there know the answer themselves :(

I was hoping someone here would know the answer as it seems closely related.

**Comment by Roybaby** [comment]
http://www.vannevel.net/2015/03/21/how-to-unit-test-your-owin-configured-oauth2-implementation/
