### ISSUE TITLE
Revisit User.IsSignedIn()

### ISSUE THREAD

**Issue by rustd** [aspnet/Identity#630]

**Comment by rustd** [comment]
Delete this and in the templates add User.IsAuthenticated()

This is a breaking change so please post it in the Announcements repo.

**Comment by HaoK** [comment]
Tracking via https://github.com/aspnet/Identity/issues/663

**Comment by xperiandri** [comment]
What about User.GetUserId() ?

**Comment by HaoK** [comment]
That got moved to UserManager as well.
