### ISSUE TITLE
Separated Authentication functionalities from persistent functionalities.

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Identity#631]
Separated Authentication functionalities from persistent(IMO, Data.Abestractions is a good name) functionalities is a nice to have. And of course having two Nuget packages.
For example sometime we just need to store and retrieve user data and authentication done by identity server (e.g IdentityServer3).

**Comment by HaoK** [comment]
This already is factored today, Security/HttpAbstractions handles the low level AuthZ decisions/ClaimsPrincipal.  Identity layers on top of that the concept of users, and 'sign in' via password social etc.  You can replace parts of identity or replace it entirely with your own authentication mechanism if desired

**Comment by brockallen** [comment]
I think he might mean separate the AspId3 manager and store APIs from the SignIn manager. Right now the whole thing has a dependency on HttpAbstractions, whereas the core identity management (user management APIs) could be separate and a separate package that assumes the ASP.NET pipeline and cookie MW.
