### ISSUE TITLE
UserManager.GetUsersInRoleAsync XML comment wrong

### ISSUE THREAD

**Issue by angelsix** [aspnet/Identity#632]
Just a heads up. The XML comment for GetUsersInRoleAsync is wrong. It's copy/pasted from the claim, needs updating to the correct comment.

Also the comment for GetUsersForClaimAsync is missing.

**Comment by HaoK** [comment]
Mr Dorrans, your awesome wordsmith skills are needed again! @blowdart

**Comment by blowdart** [comment]
You are perfectly capable of cutting and pasting the correct comments yourself :p (because inheritdoc doesn't work)

**Comment by HaoK** [comment]
Merged @blowdart s poetic changes :)  2084a95f0ac68dfc6739a47745c9f2a500975e50
