### ISSUE TITLE
The scope of DBContext of Identity

### ISSUE THREAD

**Issue by singlewind** [aspnet/Identity#633]
We are using identity beta-8 for a project. When use AddClaimAsync in RoleManager, it gives error  "[Some Class]" cannot be tracked because another instance of this type with the same key is already being tracked. 

The dbcontext was injected in Startup.cs

```csharp
services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<HemaIdentityContext>(options =>
                {
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]);
                }
            );            

            services.AddSingleton(_ => Configuration);
            
            services.AddIdentity<HemaUser, HemaRole>()
                .AddEntityFrameworkStores<HemaIdentityContext, Guid>()
                .AddDefaultTokenProviders();
```

Nothing is special here. I wonder any Jedi master here can show me some force to light the road for me.

I know by default the IdentityDbContext was injected as scope and some source code use attach method to attach entity to be tracked without check whether the entity already inside context. This is where the error comes from.

I don't know why EF decide not handle duplicate check inside attach method.

**Comment by singlewind** [comment]
I found a closed ticket #536 which changed to scope from transient, which is good. However, it may brings issue when we use attach method in our code without check whether entity is already in the context

**Comment by rustd** [comment]
Can you please send us the snippet of code for this "When use AddClaimAsync in RoleManager"?

**Comment by singlewind** [comment]
It is very easy to replicate. Any time, the second call to userManager, roleManage related to a same entity will fail. For example, the ResetAccessFailedCountAsync is OK, but SetLockoutEndDateAsync will fail, because user is already in tracker.

```csharp
var result = await userManager.ResetAccessFailedCountAsync(user);
                if (result.Succeeded)
                {
                    await userManager.SetLockoutEndDateAsync(user, null);
                } 
```

**Comment by rustd** [comment]
@HaoK maybe we have a bug. Can you please look into it?

**Comment by singlewind** [comment]
I didn't observe the issue again after upgrade to RC1. I believe this may be an issue of EF instead of Identity. I will keep an eye on it.
