### ISSUE TITLE
DB connection issue  with AspNet.ApplicationCookie 

### ISSUE THREAD

**Issue by mayur4monto** [aspnet/Identity#634]
I have used ASP.net identity in my mvc5 application. but gives the following error randomly

 A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)

at the same time it is working in the other browser window 

to resolve this error if I delete the .AspNet.ApplicationCookie cookie of my browser then it start working. not sure what is missing here.

this issue errors randomly mostly after the idle state of the browser window

this is the strange issue

Please help me.

**Comment by rustd** [comment]
This is unrelated to ASP.NET Identity. Please discuss it http://forums.asp.net/25.aspx/1?Security
