### ISSUE TITLE
Double-check in SignInManager

### ISSUE THREAD

**Issue by rhegner** [aspnet/Identity#636]
While looking through the code of SignInManager.cs I noticed that in `PasswordSignInAsync` you first call `PreSignInCheck` and then check `IsLockedOut`. But inside of `PreSignInCheck` you already check `IsLockedOut`. So you end up checking twice if the user is locked out. Is this intentionally so?

**Comment by rustd** [comment]
Yes this is by design. We want to track the error case where the user is signed in or not which is defined in PreSignInCheck.
