### ISSUE TITLE
Sample AccountController does not populate ViewBag.LoginProviders on Login

### ISSUE THREAD

**Issue by egorpavlikhin** [aspnet/Identity#638]
ViewBag.LoginProviders is populated on GET Login action, but not on POST, which results in a RuntimeBinderException when trying to login.

https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.Mvc/Controllers/AccountController.cs#L42

**Comment by rustd** [comment]
Update the sample to match the templates

**Comment by HaoK** [comment]
267d0ac20671ec80ae0d45c1988f1347a2dff0b9

**Comment by HaoK** [comment]
Fixed this specific login provider bug.  Updating the samples entirely will be done later
