### ISSUE TITLE
How to Unit test AccountController and mock the signInManager.PasswordSignInAsync

### ISSUE THREAD

**Issue by Anderman** [aspnet/Identity#640]
I tried to test the account controller with Xunit and Moq. But I have a problem to mock the PasswordSignInAsync

I have no idea how to set the result. I looked to this issue https://github.com/aspnet/Identity/issues/344 and the musicstore

I used this for mocking UserManager and SignInManager
```
 public static Mock<SignInManager<TUser>> MockSignInManager<TUser>() where TUser : class
        {
            var context = new Mock<HttpContext>();
            var manager = MockUserManager<TUser>();
            return new Mock<SignInManager<TUser>>(manager.Object,
                new HttpContextAccessor { HttpContext = context.Object },
                new Mock<IUserClaimsPrincipalFactory<TUser>>().Object,
                null, null)
            { CallBase = true };
        }

        public static Mock<UserManager<TUser>> MockUserManager<TUser>() where TUser : class
        {
            IList<IUserValidator<TUser>> UserValidators = new List<IUserValidator<TUser>>();
            IList<IPasswordValidator<TUser>> PasswordValidators = new List<IPasswordValidator<TUser>>();

            var store = new Mock<IUserStore<TUser>>();
            UserValidators.Add(new UserValidator<TUser>());
            PasswordValidators.Add(new PasswordValidator<TUser>());
            var mgr = new Mock<UserManager<TUser>>(store.Object, null, null, UserValidators, PasswordValidators, null, null, null, null, null);
            return mgr;
        }
```

    // Arrange
            var MockUserManager = Microsoft.AspNet.Identity.Test.MockHelpers.MockUserManager<ApplicationUser>();
            var MockSignInManager = Microsoft.AspNet.Identity.Test.MockHelpers.MockSignInManager<ApplicationUser>();

            var controller = new AccountController(MockUserManager.Object, MockSignInManager.Object);

            MockSignInManager.Setup(m => m.PasswordSignInAsync(It.IsAny<string>(), It.IsAny<string>(), true, false))
                         .Returns(Task.FromResult<SignInResult>(new SignInResult() { Succeeded = true }));

           var y = await controller.Login(new LoginViewModel() { Email = "email", Password = "1", RememberMe = true }, "retrunurl");

But I can't set Succeeded because it is protected.

Is this the right approach to test the accountController?

**Comment by HaoK** [comment]
Call SignInResult.Success to create a success

**Comment by umutesen** [comment]
How can one mock user manager/ signin manager in .net core?

**Comment by maxalmonte14** [comment]
> How can one mock user manager/ signin manager in .net core?

@umutesen I had the same question so I started searching, this is how I do, I hope it works for you

`UserManager`

```c#
using System;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Moq;

namespace YourNamespace
{
    public class FakeUserManager : UserManager<IdentityUser>
    {
        public FakeUserManager()
            : base(new Mock<IUserStore<ApplicationUser>>().Object,
                  new Mock<IOptions<IdentityOptions>>().Object,
                  new Mock<IPasswordHasher<ApplicationUser>>().Object,
                  new IUserValidator<ApplicationUser>[0],
                  new IPasswordValidator<ApplicationUser>[0],
                  new Mock<ILookupNormalizer>().Object,
                  new Mock<IdentityErrorDescriber>().Object,
                  new Mock<IServiceProvider>().Object,
                  new Mock<ILogger<UserManager<ApplicationUser>>>().Object)
        { }
    }
}
```

`SignInManager`

```c#
using System;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Moq;

namespace YourNamespace
{
    public class FakeSignInManager : SignInManager<IdentityUser>
    {
        public FakeSignInManager()
            : base(new FakeUserManager(),
            new Mock<IHttpContextAccessor>().Object,
            new Mock<IUserClaimsPrincipalFactory<ApplicationUser>>().Object,
            new Mock<IOptions<IdentityOptions>>().Object,
            new Mock<ILogger<SignInManager<ApplicationUser>>>().Object,
            new Mock<IAuthenticationSchemeProvider>().Object)
        { }
    }
}
```

After defining the classes you have to mock them anything you want to use them, that way you can modify any specific behavior the way you want.

```c#
private Mock<FakeUserManager> _userManagerMock;
private Mock<FakeSigInManager> _signInManagerMock;

public YourContrustor()
{
    _userManagerMock = new Mock<FakeUserManager>();
    _signInManagerMock = new Mock<FakeSigInManager>();
}
```

_____

I have to say, this is not my work (at least not 100%), this is a compilation of tips and tricks I found in different sites like Stackoverflow, Medium, the Microsoft documentation, blogs, etc. Anyways I hope it works for you and everybody else 😄

**Comment by umutesen** [comment]
@maxalmonte14 Thanks for the code snippet! 👍 

here is how I ended up doing:

Controller:
```
    [Route("api/[controller]")]
    public class AccountController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public AccountController(UserManager<User> userManager,
            SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
    }
```

Test:

```
    [TestClass]
    public class AccountControllerTests
    {
        private AccountController _controller;
        private Mock<UserManager<User>> _mockUserManager;
        private Mock<SignInManager<User>> _mockSignInManager;

        [TestInitialize]
        public void TestInitialise()
        {
            var userStoreMock = new Mock<IUserStore<User>>();

            _mockUserManager = new Mock<UserManager<User>>(userStoreMock.Object,
                null, null, null, null, null, null, null, null);

            var contextAccessor = new Mock<IHttpContextAccessor>();
            var userPrincipalFactory = new Mock<IUserClaimsPrincipalFactory<User>>();

            _mockSignInManager = new Mock<SignInManager<User>>(_mockUserManager.Object,
                contextAccessor.Object, userPrincipalFactory.Object, null, null, null);
 
            _controller = new AccountController(_mockUserManager.Object, _mockSignInManager.Object);
        }
  }
```

Then you can assert like this:
`            _mockUserManager.Verify(s => s.FindByNameAsync("username"), Times.Once);
`

**Comment by omrumbakitemiz** [comment]
On this code 
` _mockUserManager = new Mock<UserManager<ApplicationUser>>(userStoreMock.Object,
                null, null, null, null, null, null, null, null);`
I'm getting
 `'Moq.Mock<Microsoft.AspNetCore.Identity.UserManager<ClubSystem.Lib.Model.ApplicationUser>>' to 'Moq.Mock<ClubSystem.Test.FakeUserManager>'`
My code is equal to above. Am i missing something?

**Comment by omrumbakitemiz** [comment]
Thank you for all codes, i have this [code](https://gist.github.com/omrumbakitemiz/7febcf7b7f5f8fed36d8b06788600348) when i run unit test i'm getting this error, can you help me?

> Castle.DynamicProxy.InvalidProxyConstructorArgumentsException : Can not instantiate proxy of class: ClubSystem.Test.FakeUserManager.
Could not find a constructor that would match given arguments:
