### ISSUE TITLE
Any hint on how to extends the UserManager Class in Identity3 

### ISSUE THREAD

**Issue by ahmad-moussawi** [aspnet/Identity#642]
What am trying to do is to migrate from the old membership provider, but I have no idea how to extend the UserManager class especially on: 
 - Use my custom `SqlPasswordHasher`
 - Put the `CustomUserManager` in the DI container, and use it on the controller

**Comment by madmunsterdaddy** [comment]
I'm also having troubles getting a custom PasswordHasher. This seemed much easier in Identity 2.

**Comment by ahmad-moussawi** [comment]
I've ended up to extend the UserManagerClass and passing the custom PasswordHasher in the constructor, 
Now the constructor takes much params then before
Here's my class code (Its working now, but may there is a better way to achieve this)

```c#
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using tx.Providers;
using tx.Models;
using Microsoft.Data.Entity.Infrastructure;

namespace tx.Providers.Identity{
  public class ApplicationUserManager<T> : UserManager<ApplicationUser>
  {
    public ApplicationUserManager() : base(
      new UserStore<ApplicationUser>(new ApplicationDbContext()),
      null,
      new SqlPasswordHasher(),
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ){ }
    
    
  }
}
```

**Comment by madmunsterdaddy** [comment]
Yeah, I also tried that route but found it ugly. I wish we could get some official guidance here on the right way to do this.

**Comment by rustd** [comment]
@HaoK do you have any recommendations?

**Comment by HaoK** [comment]
Adding it as scoped should work fine.  Try putting it before the `AddIdentity` call and see if that makes a difference.

**Comment by madmunsterdaddy** [comment]
Thanks. it works fine after addidentity, I just didn't know if that was the right way to do it. i.e. If you guys wrote documentation on "How do implement a custom password hasher" is that how you'd say to do it? ;)

**Comment by HaoK** [comment]
Yes, use DI is the standard way to replace services.

**Comment by nhdmalik** [comment]
@HaoK I am facing issue when i add my custom password hasher using DI as follow, it never invoked. What I missed in asp.net core project?

`services.AddScoped<IPasswordHasher<ApplicationUser>, SQLPasswordHasher>();`

and here is my SQLPasswordHasher class:

` public class SQLPasswordHasher : PasswordHasher<ApplicationUser>
    {
        public override string HashPassword(ApplicationUser user, string password)
        {
            return base.HashPassword(user,password);
        }

        public override PasswordVerificationResult VerifyHashedPassword(ApplicationUser user, string hashedPassword, string providedPassword)
        {
            string[] passwordProperties = hashedPassword.Split('|');
            if (passwordProperties.Length != 3)
            {
                return base.VerifyHashedPassword(user, hashedPassword, providedPassword);
            }
            else
            {
                string passwordHash = passwordProperties[0];
                int passwordformat = 1;
                string salt = passwordProperties[2];
                if (String.Equals(EncryptPassword(providedPassword, passwordformat, salt), passwordHash, StringComparison.CurrentCultureIgnoreCase))
                {
                    return PasswordVerificationResult.SuccessRehashNeeded;
                }
                else
                {
                    return PasswordVerificationResult.Failed;
                }
            }
        }

        //This is copied from the existing SQL providers and is provided only for back-compat.
        private string EncryptPassword(string pass, int passwordFormat, string salt)
        {
            if (passwordFormat == 0) // MembershipPasswordFormat.Clear
                return pass;

            byte[] bIn = Encoding.Unicode.GetBytes(pass);
            byte[] bSalt = Convert.FromBase64String(salt);
            byte[] bRet = null;

            if (passwordFormat == 1)
            { // MembershipPasswordFormat.Hashed 
                HashAlgorithm hm = HashAlgorithm.Create("SHA1");
                if (hm is KeyedHashAlgorithm)
                {
                    KeyedHashAlgorithm kha = (KeyedHashAlgorithm)hm;
                    if (kha.Key.Length == bSalt.Length)
                    {
                        kha.Key = bSalt;
                    }
                    else if (kha.Key.Length < bSalt.Length)
                    {
                        byte[] bKey = new byte[kha.Key.Length];
                        Buffer.BlockCopy(bSalt, 0, bKey, 0, bKey.Length);
                        kha.Key = bKey;
                    }
                    else
                    {
                        byte[] bKey = new byte[kha.Key.Length];
                        for (int iter = 0; iter < bKey.Length;)
                        {
                            int len = Math.Min(bSalt.Length, bKey.Length - iter);
                            Buffer.BlockCopy(bSalt, 0, bKey, iter, len);
                            iter += len;
                        }
                        kha.Key = bKey;
                    }
                    bRet = kha.ComputeHash(bIn);
                }
                else
                {
                    byte[] bAll = new byte[bSalt.Length + bIn.Length];
                    Buffer.BlockCopy(bSalt, 0, bAll, 0, bSalt.Length);
                    Buffer.BlockCopy(bIn, 0, bAll, bSalt.Length, bIn.Length);
                    bRet = hm.ComputeHash(bAll);
                }
            }

            return Convert.ToBase64String(bRet);
        }

    }`

**Comment by HaoK** [comment]
Can you include all of your startup?
