### ISSUE TITLE
UserManager.UpdateNormalizedEmailAsync not to call IUserStore.SetNormalizedEmailAsync when user doesn't have an e-mail

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Identity#645]
Not sure about the disadvantages but it seems to me that [`UserManager.UpdateNormalizedEmailAsync`](https://github.com/aspnet/Identity/blob/0249c6181c077db4ecbff7cf70f0768f3408168a/src/Microsoft.AspNet.Identity/UserManager.cs#L1247) should not call [`IUserStore.SetNormalizedEmailAsync`](https://github.com/aspnet/Identity/blob/0249c6181c077db4ecbff7cf70f0768f3408168a/src/Microsoft.AspNet.Identity/UserManager.cs#L1253) when user doesn't have an e-mail.

**Comment by rustd** [comment]
@HaoK what do you think?

**Comment by HaoK** [comment]
Well what if they are nulling out the email, we also need to null it out, I think we need to do this always.
