### ISSUE TITLE
Installing packages in Class Library project

### ISSUE THREAD

**Issue by hamuk** [aspnet/Identity#647]
Hi

I'm trying to create a Class Library project to contain my identity models so I can share them throughout my solution. However whenever I install the Microsoft.AspNet.Identity.EntityFramework package it installs all the dependencies then fails for some reason and rolls back.

How can I go about sharing my identity models across my solution?

Cheers
![image](https://cloud.githubusercontent.com/assets/1218756/11343536/61cd0a76-9204-11e5-9b79-0cbc69b09281.JPG)

**Comment by rustd** [comment]
https://github.com/aspnet/Identity/issues/592 You need to use Identity in DNX Console projects.
