### ISSUE TITLE
Pass in DbContextOptions to *.IdentityDbContext for all version of IdentityDbContext <>

### ISSUE THREAD

**Issue by SychevIgor** [aspnet/Identity#652]
We need to configure dbcontext as it mentioned here: https://github.com/aspnet/EntityFramework/wiki/Configuring-a-DbContext

It's cool that we make it possible to pass DbContextOptions via constructor for this class:

``` C#
  public class IdentityDbContext<TUser, TRole, TKey> : DbContext
        where TUser : IdentityUser<TKey>
        where TRole : IdentityRole<TKey>
        where TKey : IEquatable<TKey>
```
https://github.com/aspnet/Identity/issues/570
https://github.com/aspnet/Identity/issues/418

But for 2 others we still can't do it without modifications of our context:
``` C#
    /// <summary>
    /// Base class for the Entity Framework database context used for identity.
    /// </summary>
    public class IdentityDbContext : IdentityDbContext<IdentityUser, IdentityRole, string> { }

    /// <summary>
    /// Base class for the Entity Framework database context used for identity.
    /// </summary>
    /// <typeparam name="TUser">The type of the user objects.</typeparam>
    public class IdentityDbContext<TUser> : IdentityDbContext<TUser, IdentityRole, string> where 
        TUser : IdentityUser { }
``` 

As a result you are forcing us to inherit our dbcontext from `IdentityDbContext : IdentityDbContext<IdentityUser, IdentityRole, string>` and making the other 2 others versions `IdentityDbContext<TUser>`, `IdentityDbContext` completely useless.

**Comment by SychevIgor** [comment]
Looks like somebody already propose this changes https://github.com/aspnet/Identity/pull/643 and I hope that team will get it to a project.

**Comment by divega** [comment]
@HaoK @rustd I just looked at this bug and I agree we should just extend the constructors of all the versions of IdentityDbContext to take the same parameters as the base. I am assigning it to @HaoK.

**Comment by HaoK** [comment]
ada5756c874bec41b19b492e102c31930a09bd5d
