### ISSUE TITLE
Make "store" option null supported in UserManager and RoleManager

### ISSUE THREAD

**Issue by tstar** [aspnet/Identity#653]
My code does not need UserStore or RoleStore, but I need it create, because my custom UserManager and RoleManager need it in constructor. I think, that "store" option can be null supported.

In extreme cases it can be implemented as follows:
```
protected internal IUserStore<TUser> Store
{
    get
    {
        if (_store == null)
        {
            throw new ArgumentNullException(nameof(Store));
        }
        return _store;
    }
}
```
 And change UserManager and RoleManager in constructor:
```
if (store == null)
{
    throw new ArgumentNullException(nameof(store));
}
```
on
```
_store = store;
```

**Comment by rustd** [comment]
How are you storing the User and Roles information? The stores are needed to persist data in a persistent store.

**Comment by tstar** [comment]
I'm all realized in the UserStore or RoleStore.

**Comment by rustd** [comment]
This is not something we plan to support. Managers need a store for persisting Identity information.
