### ISSUE TITLE
UserManager/OWIN: Odd implementation

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Identity#654]
To it looks rather odd and hard to survey that the UserManager class, created by the Web API 2.2 template, uses a factory method to create an object instead of using a constructor for that purpose (which is the intrinsic objective of an constructor).

Using the factory method is creating an unnecessary (as I see it) dependency: OWIN must provide a dedicated function to create a UserManager object, providing a specialized `options` parameter. It's impossible to create a full-blown `UserManager` object in a generic way (i. e., without constructor arguments).

The UserManager's `Create` implementation seems clumsy and I believe it needs improvement (despite the fact that its code should be put within the constructor function):

 * The `Create` function creates its own store, thus preventing dependency injection.

 * `UserValidator` and `PasswordValidator` should not be created anew. That's an unnecessary distension. In the `UserManager's` constructor, their individual properties should be set individually:

 * The `options` parameter should not be served by some specialized `IdentityFactoryOptions` class object. The `DataProtectionProvider` should be available as some ASP.NET Identitity context property, so it can be accessed everywhere and anytime for any purpose.

 * The `UserValidator` class should not be required 

The current implementation is rather irritating. As there is no thorough documentation available, the current implementatin creates unnecessary lint.

My suggestion for a cleaned-up version would look like this:

```C#
using System;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security.DataProtection;
using MyWebApi.Identity.POCO;

namespace AuthenticationServer.Identity.Managers
{
  public class UserManager : UserManager<User>
  {
    protected new UserValidator<User> UserValidator => (UserValidator<User>)base.UserValidator;
    protected new PasswordValidator PasswordValidator => (PasswordValidator)base.PasswordValidator;

    public UserManager(IUserStore<User> store, IDataProtectionProvider dataProtectionProvider = null) : base(store)
    {
      UserValidator.AllowOnlyAlphanumericUserNames = false;
      UserValidator.RequireUniqueEmail = true;

      PasswordValidator.RequiredLength = 2;
      PasswordValidator.RequireNonLetterOrDigit = false;
      PasswordValidator.RequireDigit = false;
      PasswordValidator.RequireLowercase = false;
      PasswordValidator.RequireUppercase = false;

      if (dataProtectionProvider != null) UserTokenProvider = new DataProtectorTokenProvider<User>(dataProtectionProvider.Create("ASP.NET Identity"));
    }
  }
}
```
<br/>
... and in Startup.cs it could be initialized just like that:
```C#
app.CreatePerOwinContext<IdentityContext>(() => new IdentityContext());
app.CreatePerOwinContext<UserManager>((IdentityFactoryOptions<UserManager> options, IOwinContext owin) => new UserManager(new UserStore<User>(owin.Get<IdentityContext>()), options.DataProtectionProvider));
```

This way one doesn't need to go back and forth in files to see where objects and parameters actually hail from.

My two cents.

**Comment by davidfowl** [comment]
This repository doesn't have the Katana/OWIN implementation so not sure if this feedback is relevant to the new API surface.

**Comment by SetTrend** [comment]
Please forgive me if I mistakenly have posted to the wrong group.

I believed because my feedback mainly targets the `UserManager` class my issue belongs to this group.

The Katana group @ Codeplex seems to have deceased, by the way. Reponses there are fairly sparse.

**Comment by rustd** [comment]
This is related to Identity 2.x. Please open an issue at https://aspnetidentity.codeplex.com/
