### ISSUE TITLE
Make dependency in IHttpContextAccessor optional

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Identity#655]
React to https://github.com/aspnet/Hosting/commit/7c8b37bcc726895d12724ba2d7f657c8400c6c4d

**Comment by divega** [comment]
What is the recommended action? Add it to DI ourselves or stop depending on it?

**Comment by brockallen** [comment]
+1

**Comment by davidfowl** [comment]
Use it if it exists and all cancellation token overloads with default values. The functionality lost isn't that critical

**Comment by divega** [comment]
OK, thanks.

**Comment by divega** [comment]
@davidfowl the functionality lost may not be critical for `UserManager` and `RoleManager` but `HttpContext` is critical for most things in `SignInManager` (as #674 states we will stop trying to access `contextAccessor.HttpContext` in the constructor but we sill need it in 14 other places in the class). So, 
- Should we `TryAdd()` the service on `AddIdentity()` or 
- Should be split `AddIdentity()` into a method that adds the services for `UserManager()` and `RoleManager()` and another method that adds the services necessary for `SignInManager()`
- Any other option?

**Comment by HaoK** [comment]
For now we just use an empty cancellation token if the accessor is not found

167bb54c8d7aaafa12983164f8033cc25d0af39e

**Comment by RehanSaeed** [comment]
I'm still unclear on the recommended approach. One use case for `IHttpContextAccessor` is the command pattern for controller actions e.g. 

```
public class FooCommand : ICommand<string, string>
{
    private IHttpContextAccessor httpContextAccessor;

    public FooCommand(IHttpContextAccessor httpContextAccessor)
    {
        this.httpContextAccessor = httpContextAccessor;
    }

    public IActionResult Execute(string param1, string param2)
    {
        // Use this.httpContextAccessor.HttpContext
    }
}

public class FooController : Controller
{
    public FooCommand fooCommand;

    public FooController(FooCommand fooCommand) { this.fooCommand = fooCommand; }

    public IActionResult Foo(string param1, string param2)
    {
        return this.fooCommand.Execute(param1, param2);
    }
}
```

The alternative approach is to pass the HttpContext around all over the place which can get a bit ugly if you have a few parameters, in addition to a HttpContext to pass e.g.

```
public class FooCommand : ICommand
{
    public IActionResult Execute(HttpContext httpContext, string param1, string param2)
    {
        // Use httpContext
    }
}

public class FooController : Controller
{
    public FooCommand fooCommand;

    public FooController(FooCommand fooCommand) { this.fooCommand = fooCommand; }

    public IActionResult Foo(string param1, string param2)
    {
        return this.fooCommand.Execute(this.HttpContext, param1, param2);
    }
}
```
