### ISSUE TITLE
IdentityDbContext.Database.CurrentTransaction is null when context is instantiated with existing connection

### ISSUE THREAD

**Issue by quasilatent** [aspnet/Identity#657]
IdentityDbContext throws
*BeginExecuteReader requires the command to have a transaction when the connection assigned to the command is in a pending local transaction.  The Transaction property of the command has not been initialized.*
it was instantiated with existing connection with transaction when in my case ValidateUserName() is called.

lib version 2.2.1

Should be that way and I supposed to call UseTransaction on another context Database prop which seems to work?

**Comment by divega** [comment]
Yes. If the transaction is also initiated externally, you need to call `UseTransaction(transaction)` to tell the EF about it. Feel free to reopen if that doesn't work.
