### ISSUE TITLE
Is it possible to remove password complexity checks?

### ISSUE THREAD

**Issue by alexjusti** [aspnet/Identity#658]
I have written my own password complexity check (it differs from that of the Identity UserManager), and I'd like to implement my check while also replacing the default check.  Is there a way to do that without rewriting the entire CreateAsync method in the UserManager?

**Comment by rustd** [comment]
@HaoK how can we do this? Can we do it by replacing this service in DI?

**Comment by HaoK** [comment]
Replace the IPasswordValidator or just turn it off via

```
            services.AddIdentity<TUser, TRole>(options =>
            {
                options.Password.RequireDigit = false;
                options.Password.RequireLowercase = false;
                options.Password.RequireNonLetterOrDigit = false;
                options.Password.RequireUppercase = false;
                options.User.AllowedUserNameCharacters = null;
             }
```
