### ISSUE TITLE
GetUserId extension method doesn't honor IdentityOptions.ClaimsIdentity.UserIdClaimType

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#663]
Same for GetUserName. They're both hard coded to use the legacy SOAP/WS-* `ClaimTypes` enum.

**Comment by rustd** [comment]
Add this to the announcements repo.

**Comment by brockallen** [comment]
I'm guessing you're not looking for a fix, so might I suggest adding these as extension methods to the VS template project and not into the core identity framework? In many projects the display name should not be the same as the username the user enters to login.

**Comment by leastprivilege** [comment]
really? I always say "good morning MICROSOFT/PRANAV" when I meet him him the hallway.

**Comment by MaximRouiller** [comment]
I'll have to greet him that way at the next Summit. ;-)

**Comment by HaoK** [comment]
We are actually going to nuke this extension since it was only important in 2.0 because all the user manager APIs took user id, now that they take the user itself, its no longer needed

**Comment by brockallen** [comment]
yay. the less people are forced to use certain claims types, the better. thx.

**Comment by HaoK** [comment]
Gone 1c26e8f5fa1b36febaca1f9a63b2a2f65fb11727

**Comment by HaoK** [comment]
Looks like we need to provide alternate sugar for the templates in some from before removing these

**Comment by HaoK** [comment]
Going to remove all the identity claims principal extensions and add instance methods on SignInManager:

GetUserId/UserName/IsSignedIn...

Templates will need to be updated

**Comment by HaoK** [comment]
2dade94404d3198b19e6af9083b410287e11314f
