### ISSUE TITLE
'AADSTS65005: The application needs access to a service that your organization test has not subscribed to.

### ISSUE THREAD

**Issue by steve-warwick** [aspnet/Identity#665]
First off, forgive me if this not the correct group for this issue. I've already posted this to the Azure AD forum and I have a support ticket pending in the Azure portal for someone to help look into this issue. In the meantime I thought it may be worth posting this here since it could be a bug in the Azure identity system.

I took the ToDoListItemService Azure AD sample posted to GitHub and ported to RC1 ASP.NET 5. I'm trying to figure out how to create a multi-tenant WebApp that also surfaces a public multi-tenant WebApi. Each tenant will have an on premise headless agent that will comunicate with the WebApi in secure fashion. I took the OpenIdConnect with WebApi ToDoListSerice sample and attempted to make it multi-tenant. It works fine if I used a user from the directory where the app is hosted, but when I use a user from a directory not hosting the app I get the following error:

Microsoft.AspNet.Hosting.Internal.HostingEngine: Information: Request starting HTTP/1.1 POST https://localhost:44350/signin-oidc application/x-www-form-urlencoded 749
Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware: Error: Message contains error: 'access_denied', error_description: 'AADSTS65005: The application needs access to a service that your organization test has not subscribed to. Please contact your Administrator to review the configuration of your service subscriptions.
Trace ID: 26b2a633-9ae2-4bde-a332-358c94c9b6df
Correlation ID: befaa393-561a-42dc-9248-4c98ea84c41a

If I remove the ToDoListService WebApi from the ToDoListWebApp application I am presented with the consent screen as expected, so it appears this has something to do with the WebApi and some additional consents that are required. I made sure the WebApi was marked as multi-tenant as well. Any idea what the problem may be? 

I have a sample app which I attempted to attached to this post. However, GitHub keeps telling me it doesn't support files of this type. It's a zip file, so it should be supported. I can post it somewhere else if this helps. Thanks.

**Comment by steve-warwick** [comment]
It turns out this issue was due to not having client Id of the WebApp configured in the WebApi's "knowClientApplications" array property in the manifest file. This needs information needs to be documented in the other multi-tenant Azure AD samples

**Comment by thangchung** [comment]
@steve-warwick You are my lifesaver 👍

**Comment by rishikeshjadhav** [comment]
@steve-warwick  This worked like charm :)
