### ISSUE TITLE
Make SQL Server tests configurable

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Identity#666]
Two scenarios:

1. our CI agents that use LocalDB and overwhelm its capability => test failures. LocalDB locks due to slow file I/O on azure VMs and the number of create/delete db operations in universe testing.
2. x-plat. LocalDB does not exist on Windows.

Possible solution: use what EF does:
See [SqlConnectionStringBuilderExtensions.cs](https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.MicrosoftSqlServer.FunctionalTests/Utilities/SqlConnectionStringBuilderExtensions.cs) and [SqlServerConfiguredConditionAttribute.cs](https://github.com/aspnet/EntityFramework/blob/b802ac3c5d69d7fb128452ff121c68714e045c17/test/EntityFramework.MicrosoftSqlServer.FunctionalTests/Utilities/SqlServerConfiguredConditionAttribute.cs#L20)

cc @divega @dougbu

**Comment by divega** [comment]
@HaoK after talking to @natemcmaster, we should try the solution that increases the timeout first. If that is not enough, then we can move from LocalDB to SQLExpress (we are not 100% confident that doing so helped us much on EF).

**Comment by HaoK** [comment]
Increased timeout to 30s to match EF tests for now: 7ae091d2a4f3624229fd6c8eddde0865abddf77b
