### ISSUE TITLE
Identity Authentication cookie too long?

### ISSUE THREAD

**Issue by wenbinke** [aspnet/Identity#668]
The authentication cookie is too long. When I use one domain for both front-end and back-end.
In front-end, some third-party service creates cookies(maybe also long) under the sub domain(.exmple.com). Now the authentication function doesn't work anymore and it always redirects to login page. Only when I remove some cookies and it starts to work again.

I think it is better to reduce the size of the authentication cookie and give some room for other cookies.

ASP.NET 5 RC1
"Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
"Microsoft.AspNet.Identity": "3.0.0-rc1-final"

**Comment by rustd** [comment]
What browser are you using and what is the size of the other cookies? How many claims are in your Identity? What is the size of the Identity Authentication cookie for your case?

**Comment by rustd** [comment]
Please reopen this issue once you have more information.
