### ISSUE TITLE
HttpContext.Authentication.SignInAsync not working

### ISSUE THREAD

**Issue by yuezhongxin** [aspnet/Identity#676]
This is my code:

```cs
app.UseCookieAuthentication((cookieOptions) =>
{
    cookieOptions.AuthenticationScheme = "Cookies";
    cookieOptions.AutomaticAuthenticate = true;
    cookieOptions.AutomaticChallenge = true;
    cookieOptions.LoginPath = new PathString("/Account/Login");
});
```

```cs
public class HomeController : Controller
{
    [Authorize]
    public IActionResult Index()
    {
        return View();
    }
}

public class AccountController : Controller
{
    [AllowAnonymous]
    public async Task<IActionResult> Login(string returnUrl = null)
    {
        var userId = "xishuai";
        var identity = new ClaimsIdentity();
        identity.AddClaim(new Claim(ClaimTypes.Name, userId));
        await HttpContext.Authentication.SignInAsync("Cookies", new ClaimsPrincipal(identity));
        return Redirect(returnUrl);
    }
}
```

The problem is that the loop executes `/Account/Login` code.

"Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final"
"Microsoft.AspNet.Identity": "3.0.0-rc1-final"

**Comment by brockallen** [comment]
When you create your `ClaimsIdentity` you need to pass the `authenticationType` ctor param, otherwise your user's `IsAuthenticated` will still be `false`.

**Comment by yuezhongxin** [comment]
@brockallen About `authenticationType ` ctor param, I should write what values? In `CookieAuthenticationOptions` type, I did not find `AuthenticationType` property: 

![qq20151212-0 2x](https://cloud.githubusercontent.com/assets/6800671/11759664/4199849e-a0bb-11e5-9a9c-9ebed20d478b.png)

**Comment by brockallen** [comment]
It's means to indicate how the user logged in. So "password" for a password based login, "2fa" for two-factor, etc.

**Comment by yuezhongxin** [comment]
@brockallen Sorry, I still can not understand what you mean, can you help me write an example code?

**Comment by brockallen** [comment]
`var identity = new ClaimsIdentity();`

**Comment by rustd** [comment]
@yuezhongxin please see the comment above and update your code.

**Comment by yuezhongxin** [comment]
@brockallen @rustd This is the modified code:

```cs
app.UseCookieAuthentication((cookieOptions) =>
{
    cookieOptions.AuthenticationScheme = "Cookies";
    cookieOptions.AutomaticAuthenticate = true;
    cookieOptions.AutomaticChallenge = true;
    cookieOptions.LoginPath = new PathString("/Account/Login");
});
```

```cs
public class HomeController : Controller
{
    [Authorize]
    public IActionResult Index()
    {
        return View();
    }
}

public class AccountController : Controller
{
    [AllowAnonymous]
    public async Task<IActionResult> Login(string returnUrl = null)
    {
        var userId = "xishuai";
        var identity = new ClaimsIdentity("password");
        identity.AddClaim(new Claim(ClaimTypes.Name, userId));
        await HttpContext.Authentication.SignInAsync("Cookies", new ClaimsPrincipal(identity));
        return Redirect(returnUrl);
    }
}
```

But sometimes does not work: 

![untitled](https://cloud.githubusercontent.com/assets/6800671/11799076/ca6833b8-a30b-11e5-9bd0-5ad621a9261d.gif)

**Comment by 717009629** [comment]
大神我就是这个问题，你让我给你发邮件了 @yuezhongxin

**Comment by yuezhongxin** [comment]
@717009629 这个测试代码写的有些问题，所以才会出现上面的问题。

**Comment by lmxin123** [comment]
@717009629 我也遇到这个问题，请问你是怎么解决的，麻烦发我邮箱一下 409001887@qq.com

**Comment by lmxin123** [comment]
@yuezhongxin 请问上面的代码哪里写的有问题。还有下面是我的代码，帮忙看下哪里有问题，谢谢。
`  app.UseCookieAuthentication(options =>
            {
                options.AuthenticationScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.LoginPath = new PathString("/user/login");
                options.AutomaticAuthenticate = true;
                options.AutomaticChallenge = true;
                options.CookieHttpOnly = true;
            });

 public async Task<IActionResult> Test()
        {
            List<Claim> claims = new List<Claim>();
            claims.Add(new Claim("Name", "TestName", ClaimValueTypes.String));
            claims.Add(new Claim(ClaimTypes.Name, "TestName", ClaimValueTypes.String));
            ClaimsIdentity identity = new ClaimsIdentity(claims, IdentityCookieOptions.ApplicationCookieAuthenticationType, "Name", ClaimTypes.Role);
            ClaimsPrincipal principal = new ClaimsPrincipal(identity);
            HttpContext.Authentication.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

return view();
} 
`

**Comment by 717009629** [comment]
@lmxin123 
ClaimsPrincipal principal = new ClaimsPrincipal(identity,CookieAuthenticationDefaults.AuthenticationScheme);

**Comment by lmxin123** [comment]
@717009629 ClaimsPrincipal 并没有两个参数的构造函数。但是我使用系统自带的signInManager.PasswordSignInAsync(model.UserName, model.Password, model.RememberMe, false);是成功的。自定义的就一直不成功

**Comment by 717009629** [comment]
@lmxin123  你看看我写的吧
var cp = new ClaimsPrincipal(new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, u.Name) }, CookieAuthenticationDefaults.AuthenticationScheme));
            await HttpContext.Authentication.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, cp);

**Comment by lmxin123** [comment]
@717009629 我复制你的代码，也清空了cookie，调试是可以通过，没报任何异常，但是cookie里面并没有保存值，非常奇怪。请问下在 Setup里面你是怎么配置的，这个问题耽误了太多时间了，非常急着。

**Comment by 717009629** [comment]
app.UseCookieAuthentication(option =>
            {
                option.AutomaticAuthenticate = true;
                option.AutomaticChallenge = true;
                option.CookieHttpOnly = true;
                option.LoginPath = "/admin/login";

                option.AuthenticationScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            });

**Comment by MaximRouiller** [comment]
I have absolutely no idea what's going on in this thread. :confused:

**Comment by yuezhongxin** [comment]
@MaximRouiller You can look at this reply: https://github.com/aspnet/Security/issues/624#issuecomment-170913079
