### ISSUE TITLE
UserManager - UpdateAsync InvalidOperationException

### ISSUE THREAD

**Issue by ericgreenmix** [aspnet/Identity#677]
When calling UpdateAsync on the UserManager the following error occurs:

```InvalidOperationException: The instance of entity type MyUser cannot be tracked because another instance of this type with the same key is already being tracked. For new entities consider using an IIdentityGenerator to generate unique key values.```

UserManager/Store are being registered as scoped and UpdateAsync is the only method being called in that scoped request, so the DbContext should not be tracking any entities.

**Comment by rustd** [comment]
Can you please post the code that reproes this?

**Comment by rustd** [comment]
Please reopen this bug once you have the repro.
