### ISSUE TITLE
Interop with 4.5 (doc/sample story)

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#682]
Need to clean up a few things still:
- Add initial EF6 migration
- Add code to do property updating of normalized columns as part of SaveChanges

**Comment by HaoK** [comment]
EF migration looks correct here:

http://stackoverflow.com/questions/36345121/how-to-migrate-database-schema-from-identity-2-2-0-to-3-0-0-rc1-final

**Comment by HaoK** [comment]
Desired flow:
- Create 4.5.1 MVC App (Run + Create user + login) => Initial V2 schema
- Drop in compat classes which rebase the Identity POCO
- Run migrations using EF6 to update schema to V3
- Run Core Identity app and verify that login works against database
- Final step: Update both apps to use the same dataprotection so cookies are shared cross app

**Comment by divega** [comment]
@haok Remember that before yo drop the new classes and rebase you have to make sure you have enabled migrations.

**Comment by HaoK** [comment]
Interop sample can't live in same sln as core currently due to package restore issues and ef migrations.  Will need to revisit what we want to do (if anything)  Could just have a blog post/doc walkthrough instead of a checked in sample since its more of a flow anyways

**Comment by HaoK** [comment]
Moving to 1.0.1 since there's nothing to be done in 1.0.0

**Comment by divega** [comment]
> Could just have a blog post/doc walkthrough instead of a checked in sample since its more of a flow anyways

Another option would be to put it into its own repo.

**Comment by HaoK** [comment]
The main problem is that the best I can do is check in a snapshot at a single point (probably the end result) of the migration.

**Comment by HaoK** [comment]
Also its weird for it to live in its own repo when the Compat package lives here

**Comment by HaoK** [comment]
I think a second sln in this repo would be better than moving it out

**Comment by HaoK** [comment]
Related https://github.com/aspnet/EntityFramework/issues/2167

**Comment by danroth27** [comment]
@divega @HaoK Microsoft Customer Support Services reported that customers are having issues setting up cookie sharing and could use a fully functional sample. How soon can we get the sample updated so that we can link to it from the docs?

**Comment by HaoK** [comment]
Are they asking about full identity database Interop or only the much simpler app cookie sharing scenario?

**Comment by divega** [comment]
@danroth27 we can make this a high priority as per our conversation, but can you please answer about the scope (cooking sharing vs. full with a shared database)?

**Comment by HaoK** [comment]
@blowdart is working on the updated example/sample doc in his private repo

**Comment by divega** [comment]
@HaoK @blowdart moving this to 1.2 because it doesn't seem to be something that would block use from shipping 1.1 at this point.

**Comment by Eilon** [comment]
@blowdart / @HaoK / @divega - this bug is ~1.5 years old, should we just close it?

**Comment by HaoK** [comment]
yeah its already covered by https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/cookie-sharing?tabs=aspnetcore2x and there are issues tracking improving that to target interop
