### ISSUE TITLE
Unable to add "Microsoft.AspNet.Identity.Core" in a coreclr project

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Identity#685]
I'm not sure if this is a tooling issue or something else, but I'm unable to add `Microsoft.AspNet.Identity.Core` to my project.  I'm running the latest Visual Studio.

It does give me a red squiggly line with the hover message:

```
The dependency Microsoft.AspNet.Identity.Core 2.2.1 in project [Project] does not support framework DNXCore,Version=v5.0
```

**Comment by MaximRouiller** [comment]
It looks like the package hasn't been updated since April 2015.

Another package named [`Microsoft.AspNet.Identity`](https://www.nuget.org/packages/Microsoft.AspNet.Identity/) seem to have taken off where .Core left off. As in, no < 3.X releases, all betas and following the ASP.NET 5 releases.

Can you try that package?

PS: Not currently in front of VS2015 or any working implementation thereof.

**Comment by MaximRouiller** [comment]
Oh and `Microsoft.AspNet.Identity.Core` has never been DNX compatible, as in ever, but is still available through the NuGet gallery so that might lead to confusion.

**Comment by atrauzzi** [comment]
That does restore successfully, but now `Microsoft.AspNet.Identity.IUser` doesn't exist.

**Comment by MaximRouiller** [comment]
You are converting old code to the new identity model, right?

**Comment by MaximRouiller** [comment]
And look at that... [no documentation](http://docs.asp.net/en/latest/migration/identity.html#stub-icon-migrating-from-asp-net-identity-2-x-to-3-x) :stuck_out_tongue: 

//cc: @rustd

**Comment by atrauzzi** [comment]
Ah, no, I'm writing new code in a new project.  But I'm not necessarily using Entity Framework.

**Comment by MaximRouiller** [comment]
Care to share a bit of code for your use case? Maybe we can help.

**Comment by atrauzzi** [comment]
This is gonna seem silly, but it's really just a bare class that I'm starting out with.  I'm going through making an ASP.NET 5 project from scratch to study it.

```
namespace Project.Domain {

	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Threading.Tasks;
	using Microsoft.AspNet.Identity;


	public class User : IUser {

		public string Id {
			get	{
				throw new NotImplementedException();
			}
		}

		public string UserName {

			get {
				throw new NotImplementedException();
			}

			set {
				throw new NotImplementedException();
			}

		}

	}

}
```

Nothing special at all in dependencies:

```
  "dependencies": {
        "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
	"Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
	"Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
	"Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final",
	"Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
	"Glimpse": "2.0.0-beta1",
	"Microsoft.AspNet.Identity": "3.0.0-rc1-final",
	"EntityFramework7.Npgsql": "3.1.0-beta8-2"
  },
```

**Comment by atrauzzi** [comment]
I should add, the problem here is that it can't find the `IUser` interface.  Nothing implementation specific.  It's just not available, despite having the package installed.

**Comment by MaximRouiller** [comment]
From what I can see in the samples, they are using `IdentityUser` and not `IUser`.

https://github.com/aspnet/Identity/blob/3.0.0-rc1/src/Microsoft.AspNet.Identity.EntityFramework/IdentityUser.cs

**Comment by atrauzzi** [comment]
Oh... Did they just eliminate the interface all together?  Is the generic parameter what it uses to infer the key type?

**Comment by atrauzzi** [comment]
Maybe it's that all the keys are handled through the repository/store?

**Comment by MaximRouiller** [comment]
Looks like it. 

`IdentityUser<TKey>` is defined in that file at line 42. :)

And don't forget your towel.

**Comment by atrauzzi** [comment]
Hah!  Brave new world! :)

**Comment by Moses-Bassey** [comment]
This can be really frustrating, what solutions do the have to help resolve this issue. Working on asp.net core and now i need to user thier useridentity but the package is not installing. is there any help around?

**Comment by MaximRouiller** [comment]
@Moses-Bassey Please open an issue and describe your problem. What you have right now may be very different from what happened back in December 2015.

**Comment by yellareddy-allcloud** [comment]
I started to develop an Web Core Application and i am trying to Install microsoft.Aspnet.Diagnostics package for exception handling, but i am unable to install this pickage.
