### ISSUE TITLE
How to persist the login information after closing Broswer?

### ISSUE THREAD

**Issue by kinshines** [aspnet/Identity#688]
I want to persist the login information as long as possible once the user login my website,so the user don't need to login again when they reopened their Broswer,just like the github.com,when I once login the github,it can persist my information for many days,So I don't need to login again every day.Are there any methods can implment this feature with Identity?

**Comment by MaximRouiller** [comment]
Hi @kinshines, I think you'll get fast answer if you head out to www.stackoverflow.com for questions of this kind. 

This repository to report possibles defects or missing feature. You might get an answer here, but it might take days or weeks (especially with the holidays).

**Comment by kinshines** [comment]
thank you @MaximRouiller ,I think it is exactly the missing feature for persisting login information in ASP.NET Identity,and it is not simply a question which can be answered in www.stackoverflow.com.

**Comment by mlynam** [comment]
What @MaximRouiller is saying is that you are describing an extremely general behavior that the majority of frameworks implement, including aspnet. Have you heard of cookies?

**Comment by blowdart** [comment]
It's not missing at all. The templates which include ASP.NET Identity include it.

If you are not using the templates then you should look at the [cookie middleware documentation](https://docs.asp.net/en/latest/security/authentication/cookie.html) where you can see an example that creates a persistent cookie 

```c#
  await HttpContext.Authentication.SignInAsync(
      "MyCookieMiddlewareInstance",
      principal,
      new AuthenticationProperties
      {
          IsPersistent = true
      });
  ```
