### ISSUE TITLE
Claims are not loading even when I override FindByNameAsync

### ISSUE THREAD

**Issue by jvelezc** [aspnet/Identity#689]
Problem: I want to know a user his roles and his claims. 
I try to use 
   var currentUserName = HttpContext.User.GetUserName();
            var user = _userManager.FindByNameAsync(currentUserName).Result;
but because of lazy loading it does not load the related entities. 

Then I went ahead and tried to load them explicitly but only the roles are populated. 

It does not load claims associated with the roles.
``` 
 public override Task<ApplicationUser> FindByNameAsync(string userName)
        {
  
            return this.Users.Include(roles=>roles.Roles).Include(y=>y.Claims).FirstOrDefaultAsync(y => y.UserName == userName);
           // return base.FindByNameAsync(userName);
        }
```

```
My Work Around



   var currentUserName = HttpContext.User.GetUserName();
            var user = _userManager.FindByNameAsync(currentUserName).Result;

            if (user != null)
            {
                var userRoles = _userManager.GetRolesAsync(user).Result;
                var role = _applicationRoleManager.FindByNameAsync(userRoles.FirstOrDefault()).Result;
                var myClaims = _applicationRoleManager.GetClaimsAsync(role).Result;
                var claims = _userManager.GetClaimsAsync(user).Result;
                var x = _userManager.GetLoginsAsync(user).Result;

            }
    var myClaims = _applicationRoleManager.GetClaimsAsync(role).Result;
```

then compose the claim and return the actual entity with the correct claims.

**Comment by Eneuman** [comment]
If I'm not misstaken, getting a claim should be as easy as this:

var email = User.FindFirst(“email”);

where "email" is the claim you want to get.

**Comment by jvelezc** [comment]
yes I agree that you can use that. Is there any reason why it did not load with my query ?this.Users.Include(roles=>roles.Roles).Include(y=>y.Claims).

**Comment by Eneuman** [comment]
In EF7 you have to user ThenInclude I think.. Try:
 ?this.Users.Include(roles=>roles.Roles).ThenInclude(y=>y.Claims).

**Comment by Eneuman** [comment]
Start SQL Profiler and see what SQL is created.
I'm gonna give it a try in my end as well

**Comment by HaoK** [comment]
@divega is this the proper way to include with EF 7?

**Comment by divega** [comment]
The name of the variables in the lambda look a bit strange but I think the Includes are fine. I would have written something like this:

``` C#
return this.Users.Include(user=>user.Roles).Include(user=>user.Claims)
    .FirstOrDefaultAsync(y => y.UserName == userName);
```

Note however that this will only load the IndentityUserRole and not the actual Role instances. It won't load the RoleClaim instances either.

There are no navigation property on `IndentityUserRole` so there is no way to navigate to the actual `IdentityRole` entity just using `Include()` or `ThenInclude()`. You will have to issue multiple queries, at which point I think we should just recommend getting the related information explicitly using Identity APIs (similar to @jvelezc's workaround but using `await` instead of `.Result`). That pattern should work independently of the store implementation.

**Comment by divega** [comment]
Also for context on why ASP.NET Identity 3.0 won't load this additional information by default: In Identity 2.0 the EF provider used to contain additional code to load the whole graph of objects associated with a user in case it was needed by user code. This caused a big performance overhead so in ASP.NET Identity 3.0 we changed that to only load the related objects that are needed to resolve the Identity API calls. If you need a specific piece of data, it is recommended that you invoke Identity APIs explicitly to retrieve them.
