### ISSUE TITLE
JWT tokens with ASP.NETv5

### ISSUE THREAD

**Issue by capesean** [aspnet/Identity#692]
I've written a website with v4 (OWIN) that uses JWTs by issuing & validating them with a custom authorization server provider (basically following http://bitoftech.net/2015/02/16/implement-oauth-json-web-tokens-authentication-in-asp-net-web-api-and-identity-2/). 

I'm now trying to migrate to v5 and I'm not making much headway. I can get everything working on a project using cookies, but the steps to convert that project to issuing and validating JWTs is beyond me. The few examples out there are generally outdated as V5 has evolved in the last 6-12 months.

Do I have to use IdentityServer3 or some other third party code, or can I 'roll my own' as I did previously? Any help would be greatly appreciated. If I can get this working I intend putting up a lengthy blog post as I'm sure others would benefit from it.

**Comment by rustd** [comment]
Please see the following issues where this is discussed https://github.com/aspnet/Security/issues/83 and 
https://github.com/aspnet/Security/issues/359

**Comment by leastprivilege** [comment]
http://leastprivilege.com/2015/07/22/the-state-of-security-in-asp-net-5-and-mvc-6-oauth-2-0-openid-connect-and-identityserver/
