### ISSUE TITLE
Email Address Validation Problems

### ISSUE THREAD

**Issue by DaisyDave** [aspnet/Identity#693]
My email address conatains 2 '-' characters. It is correct according to the RFC but the default ASP.NET5 project with simple authentication tells me my email address can only contain letters an numbers.

**Comment by HaoK** [comment]
Can you include your AddIdentity configuration if any?  This is actually triggered by the username validation, which is just looking for the identityOptions.User.AllowedUserNameCharacters which contains '-' by default so it shouldn't be blocking this.  

We'll update this error since its a bit outdated

**Comment by DaisyDave** [comment]
I just created an ASP.NET v5 project using the ASP.NETv5 Web Application template with Individual User Accounts authentication. I made no code changes, just compiled and ran the project. 

The only occurance of AddIdentity is in Startup.cs and looks like this:
`// Add Identity services to the services container.`
`services.AddIdentity<ApplicationUser, IdentityRole>()`                `.AddEntityFrameworkStores<ApplicationDbContext>()`
`.AddDefaultTokenProviders();`

**Comment by DaisyDave** [comment]
Hi I'm new to GitHub and am not sure why/how I closed this item. I'm reopening it. If it should be cleased will someong please correct me nicely :-)

**Comment by HaoK** [comment]
I just tried this on current bits and don't see this behavior, what version are you running?

**Comment by HaoK** [comment]
Feel free to reopen this if you are able to reproduce this error on RC2 bits once they are available.
