### ISSUE TITLE
Microsoft.AspNet.Identity.Test as a nuget package

### ISSUE THREAD

**Issue by SharePointRadi** [aspnet/Identity#696]
Do you have plans to release the Microsoft.AspNet.Identity.Test project as a nuget package? Currently, if we are building a custom user store and want to reuse the UserManagerTestBase class (from the Shared folder), we have to clone, build, reference, etc.

It would be useful if it is reusable.

**Comment by HaoK** [comment]
Seems reasonable to consider in the future...backlog @divega @rustd ?

**Comment by divega** [comment]
Yes. We did this with the EF tests for provider writers and has been working well.

**Comment by SharePointRadi** [comment]
Further to this discussion, UserManager.cs has internal methods that are referenced from UserManagerTestBase.cs.

This means that we (provider writers?) could not really reuse UserManagerTestBase because it refers those internal methods. I had a similiar need and had to use reflection to refer to those internal methods.

https://github.com/OneBitSoftware/Microsoft.AspNet.Identity.EntityFramework6/blob/master/test/Microsoft.AspNet.Identity.EntityFramework6.Test/TestingUserManager.cs

**Comment by HaoK** [comment]
5e4e9ccdf164b622872c397c27b75d2bc8a329da
