### ISSUE TITLE
Null values when calling CreatAdminUser function.

### ISSUE THREAD

**Issue by huytnd** [aspnet/Identity#700]
I follow the sample, and stuck at creating Identity Database step. When debugging, I found that 2 fields of IdentityDbContextOptions were null.
![null](https://cloud.githubusercontent.com/assets/2102905/12085809/9351540e-b2f6-11e5-8ee4-ce8c00a5afae.jpg).
If I don't comment these lines, the process will pass over, and won't call CreateAdminUser function.
```
public static async Task InitializeIdentityDatabaseAsync(IServiceProvider serviceProvider)
        {
            using (var db = serviceProvider.GetRequiredService<ApplicationDbContext>())
            {
                //if(await db.Database.EnsureCreatedAsync())
                //{
                    await CreateAdminUser(serviceProvider);
                //}
            } 
        }
```
I use these line of code to call CreateAdminUser method, but it didn't jump in.
```
using (var db = serviceProvider.GetRequiredService<ApplicationDbContext>())
            {
                if (db == null)
                    return;

                if(await db.Database.EnsureCreatedAsync())
                {
                    await CreateAdminUser(serviceProvider);
                }
            }
```
Link to code sample: https://github.com/aspnet/Identity/tree/dev/samples/IdentitySample.Mvc

**Comment by HaoK** [comment]
I've updated the samples to match the latest templates, we no longer have an EnsureCreatedCall, EF migrations should be used to create the initial database now...
