### ISSUE TITLE
[Question] - Rename Identity

### ISSUE THREAD

**Issue by XcoderTeam** [aspnet/Identity#702]
Hi

Using rc1-final, when I add the Entity and modify the table name.
What is the proper way to config change the table name but I want the PK is Int rather than string.

```C#
            base.OnModelCreating(builder);
            builder.Entity<ApplicationUser<int>>(i => {
                i.ToTable("Users");

                i.HasKey(x => x.Id);
            });
            builder.Entity<IdentityRole<int>>(i => {
                i.ToTable("Role");

                i.HasKey(x => x.Id);
            });
            builder.Entity<IdentityUserRole<int>>(i => {
                i.ToTable("UserRole");

                i.HasKey(x => new { x.RoleId, x.UserId });
            });
            builder.Entity<IdentityUserLogin<int>>(i => {
                i.ToTable("UserLogin");

                i.HasKey(x => new { x.ProviderKey, x.LoginProvider });
            });
            builder.Entity<IdentityRoleClaim<int>>(i => {
                i.ToTable("RoleClaims");

                i.HasKey(x => x.Id);
            });
            builder.Entity<IdentityUserClaim<int>>(i => {
                i.ToTable("UserClaims");

                i.HasKey(x => x.Id);
            });
```

performing 
<code>
dnx ef database update
</code> 
It generate this to the database, is this bug on Identity 3.0?
![image](https://cloud.githubusercontent.com/assets/1622986/12110190/8a291d8e-b3c4-11e5-9a1c-bcacdc5e4f41.png)

this below attachment generate from the codegen

[20160105074833_v0.0.1.txt](https://github.com/aspnet/Identity/files/78128/20160105074833_v0.0.1.txt)

**Comment by rustd** [comment]
Call `AddIdentity<ApplicationUser,IdentityRole,int>()` in Startup.cs
Please reopen if this does not help.
