### ISSUE TITLE
Allow Custom Roles to be visible from User Entity instead of Base IdentityRoles

### ISSUE THREAD

**Issue by chrisjmccrum** [aspnet/Identity#706]
In my project I extended the attributes of both IdentityUser and IdentityRole to an entity called ApplicationUser and ApplicationRole.  As expected, when the database was created the additional custom columns were created for each entity, extending what I needed to define Users and Roles.  Unfortunately when I query ApplicationUser I don't receive ApplicationRole in return - instead it gives me a private property of IdentityUser called Roles.  

I'd like to make a request that the property Roles can be overrode so people with custom IdentityRoles can see there custom attributes.  Currently I have to make an unnecessary additional trip to the same table with the RoleID provided and then query my custom attributes.

![image](https://cloud.githubusercontent.com/assets/1857216/12177532/a8ae48b6-b53a-11e5-969e-3d8c6d6de338.png)

**Comment by HaoK** [comment]
This is basically the same issue as https://github.com/aspnet/Identity/issues/765, we will track with that one
