### ISSUE TITLE
Expand tests to include multiple operations

### ISSUE THREAD

**Issue by tedd** [aspnet/Identity#708]
ASP.Net 5 RC1
Microsoft.AspNet.Identity.EntityFramework 3.0.0-rc1-final
Not sure where it loads "Microsoft.AspNet.Identity" from. DNX has some magic adding of /references, maybe there? Anyway not important.

Creating a migration script for adding multiple users. Very simple script that reads json-file and attempts to execute command multiple times.

* Adding multiple users (multiple calls to CreateAsync) gives me “Collection was modified; enumeration operation may not execute” on second user.
* Attempting to add password (multiple calls to AddPasswordAsync) for more multiple users gives me “Cannot access a disposed object” on second user.

Unit tests for this project should include multiple calls to methods within same dbcontext instance so that these bugs are identified. From what I could see the tests are missing. (maybe I missed it?)

**Comment by HaoK** [comment]
Can you provide the code you are using to insert multiple users

**Comment by tedd** [comment]
I have deleted the code as I was rewriting it to work (ended up with manual inserts directly into the table). But I have one piece of code that still doesn't work. This is running on the vanilla ASP.Net Web project with Areas added.

I am using MSSQL as db storage: data source=10.0.0.60;initial catalog=TheDb;persist security info=True;user id=TheUser;password=ThePassword;MultipleActiveResultSets=True;App=EntityFramework

    [Area("Import")]
    [Route("Import/[controller]")]
    public class OneTimeImportController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public OneTimeImportController(RoleManager<IdentityRole> roleManager) {
            _roleManager = roleManager;
        }

        [Route("Run")]
        [HttpGet]
        public IActionResult Run()
        {
            var roles = new Dictionary<Enums.UserType, string>();
            roles.Add(UserType.User, "User");
            roles.Add(UserType.ProjectAdmin, "ProjectAdmin");
            roles.Add(UserType.Admin, "Admin");
            foreach (var role in roles.Values)
            {
                if (!await _roleManager.RoleExistsAsync(role))
                    _roleManager.CreateAsync(new IdentityRole(role));
            }
        }
    }

Hope this helps.

**Comment by tedd** [comment]
Changing it to this makes it work:
    if (!roleManager.RoleExistsAsync(role).Result)
        roleManager.CreateAsync(new IdentityRole(role)).Wait();

So it may be related to code not blocking on "async void" and continuing to do other stuff / dispose of the object?

**Comment by HaoK** [comment]
Can you try removing the dictionary/values enumeration and directly calling the APIs to see if it still repos?  Also can you provide the full stack trace for the exception?

**Comment by HaoK** [comment]
Actually looks like you are missing await in your call to execute.  Can you add it and see if that fixes the issue?

```
Execute(_roleManager);
```

**Comment by HaoK** [comment]
Please reopen this if you can still repro this after adding the await
