### ISSUE TITLE
RequireNonLetterOrDigit does not allow to use letters and digits 

### ISSUE THREAD

**Issue by JGrzybowski** [aspnet/Identity#709]
I used ASP.NET 5 MVC6 Project Template with User Authentication, changed default password requirements to:

```csharp
o.Password.RequireDigit = false;
o.Password.RequireLowercase = true;
o.Password.RequireUppercase = true;
o.Password.RequireNonLetterOrDigit = true; 
o.Password.RequiredLength = 6;
```

When I try to register with passwords having Upper, lower and digit the user manager fails to create an account because `Failed : PasswordRequiresNonLetterAndDigit` When I change `RequireNonLetterOrDigit ` to false problem disappears. 

1.0.0-rc1-final

**Comment by MaximRouiller** [comment]
Do you have a sample password that fails?

**Comment by JGrzybowski** [comment]
user0Pass

**Comment by MaximRouiller** [comment]
Seems to be a bug.

Here's the corresponding line: https://github.com/aspnet/Identity/blob/3.0.0-rc1/src/Microsoft.AspNet.Identity/PasswordValidator.cs#L55

And relevant code:

    if (options.RequireNonLetterOrDigit && password.All(IsLetterOrDigit))
    {
        errors.Add(Describer.PasswordRequiresNonLetterAndDigit());
    }

Basically, if you only have digits and no special characters, it will fail.

**Comment by MaximRouiller** [comment]
That seems to be the bug. If a password have a digit, with `RequireNonLetterOrDigit`, it should be valid... yet if the password is all letters or digits... it fails.

**Comment by MaximRouiller** [comment]
Maybe the name should have been `RequireNonLetter` since this is exactly what this is doing. 

@rustd? What do you think?

**Comment by rustd** [comment]
@HaoK?

**Comment by HaoK** [comment]
It's always been this way. it means there must be one non letter and non digit.

**Comment by divega** [comment]
Ah, I think it is starting to make sense to me... So, if we could use parenthesis in names it would be called `RequireNon(LetterOrDigit)` :smile: But honestly, when I read it the first time I interpreted the same way as @JGrzybowski and @MaximRouiller apparently did, i.e.  `Require(NonLetter)OrDigit`.

Maybe we can come up with a name that is no ambiguous. Was `RequireNonAlphanumeric` ever considered?

**Comment by HaoK** [comment]
I forget the exact naming history. I think it was called that at some point. Also RequireNonLetterAndDigit I think too.

**Comment by divega** [comment]
See the SO questions: 

http://stackoverflow.com/questions/25865952/requirenonletterordigit-not-correctly-validated

(I think there is a bug in the question, e.g. the flag should be set to true instead of false)

http://stackoverflow.com/questions/24796454/how-to-change-password-validation-in-asp-net-mvc-identity-2/24819318#24819318

And this forum thread:

http://forums.asp.net/t/1998093.aspx?Error+message+unclear+Passwords+must+have+at+least+one+non+letter+or+digit+character+

It seems customers have been hitting the ambiguity in the property name, the API documentation for it and even the validation error for a while.

**Comment by JGrzybowski** [comment]
Also, there should be a way to require nonletter character. I think it was possible in previous version of framework.

**Comment by HaoK** [comment]
How about we go with RequireNonAlphanumeric and change the error text to be: "Passwords must have at least one non alphanumeric character."

**Comment by MaximRouiller** [comment]
@HaoK sounds very good! :smile:

**Comment by HaoK** [comment]
84804fec20e8f301194474cc5d31fba359e8a090

**Comment by MaximRouiller** [comment]
:+1:
