### ISSUE TITLE
RC1 Update identity not working

### ISSUE THREAD

**Issue by nrkarthick** [aspnet/Identity#710]
In beta7, i used EF 6.1.3 with oracle code first and in my startup class under Configure method I have `app.UseIdentity() ` and its worked well (code as follows)

     Claim[] claims = SampleUser.Create_Claims(); // get claims
     var identity = new ClaimsIdentity(claims,CookieAuthenticationDefaults.AuthenticationScheme);
     ClaimsPrincipal principal = new ClaimsPrincipal(identity);
     await HttpContext.Authentication.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,  principal, new AuthenticationProperties() { IsPersistent = true });

But in RC1 it gives error to include `services.AddIdentity()` in the method ConfigureServices with application user and role.

I dont know how to use this application user and role in this new method..

Please guide me

**Comment by Fosol** [comment]
You're using EF 6.1.3 and the new Identity 3 uses EF 7.  Presently you cannot use two different versions of EF by default.  You would most likely have to figure out a way to make them play nice.

**Comment by nrkarthick** [comment]
@Fosol , Thank u.. But here i have two questions 
1. Will you help me to figure out this issue ?
2. When will EF 7 support Oracle ?

**Comment by MaximRouiller** [comment]
@nrkarthick I think you are better going to https://github.com/aspnet/EntityFramework to ask that question. :smile:

**Comment by Fosol** [comment]
Regrettably I don't have the time to go through all the details.  I am currently working on a project that uses Oracle.  As such I've had to do a lot of workarounds to handle the EF issues.

1) EF 6.1.3
2) Oracle.ManagedDataAccess 12.1.22
3) Oracle.ManagedDataAccess.EntityFramework 12.1.22
3) Custom implementation of Identity 3 using my own implementation of EF 6.1.3 and Oracle
4) Don't reference EF 7 anywhere
5) Apply this attribute below to your custom DbContext classes
```
[DbConfigurationType(typeof(OracleDbConfiguration))]
```
6) You'll need the implementation for the above attribute.
```
    /// <summary>
    /// <see cref="OracleDbConfiguration"/> class, provides a way to force Entity Framework to use the appropriate data access providers and factories from Oracle.
    /// This is required in ASP.NET 5 since configuration
    /// </summary>
    public class OracleDbConfiguration : DbConfiguration
    {
        #region Variables
        public const string OracleClient = "Oracle.ManagedDataAccess.Client";
        #endregion

        #region Constructors
        /// <summary>
        /// Creates a new instance of an OracleDbConfiguration class.
        /// </summary>
        public OracleDbConfiguration()
        {
            SetProviderServices(OracleClient, EFOracleProviderServices.Instance);
            SetProviderFactory(OracleClient, OracleClientFactory.Instance);
        }
        #endregion
    }
```
7) Regrettably you'll need to do a lot more than that, but that was the first steps that allowed me to connect correctly to the DB.

**Comment by nrkarthick** [comment]
@Fosol , U r absolutely right.. I too worked it out already.. Only thing I cant figure out is that applicationUser and role in identity 3.0.. but the following url throw some light and i will test and come back here... 
sharing link
http://stackoverflow.com/questions/29289731/example-of-using-asp-net-5-mvc-6-with-identity-and-ef-6

**Comment by divega** [comment]
Closing this issue as it seems that all the questions have already been answered. In summary, we don't offer an EF6-based store for the new ASP.NET Core Identity out of the box but the components have been designed so that you can register your own. Thanks @Fosol and @nrkarthick for including the details. 

Please create new issues if you find bugs or have feature suggestions.
