### ISSUE TITLE
Missing migrations

### ISSUE THREAD

**Issue by dburriss** [aspnet/Identity#717]
https://github.com/aspnet/Identity/tree/dev/samples/Interop45/Migrations
Seems to be missing:
- 201511031830242_InitialCreate
- 201511232040531_Identity3Migration
- 201511232057540_IdentityV3Schema
- 201511232103169_Identity3Migration1

They seem to be in the Interop45 csproj file but the actual .cs files are not in source control.

**Comment by HaoK** [comment]
Yeah this sample is currently not working any longer, will address as part of https://github.com/aspnet/Identity/issues/717
