### ISSUE TITLE
RoleManager and IRoleStore don't have a TKey for custom key types

### ISSUE THREAD

**Issue by flensrocker** [aspnet/Identity#718]
That means you cannot use FindByIdAsync and GetRoleIdAsync, because the id is expected to be a string.

Additionally there's a typo in the comment of the class (TUser => TRole):
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/RoleManager.cs#L20

**Comment by rustd** [comment]
This is by design. In this version the id is always a string. The store can persist it in whatever type you want.
@HaoK can you please update the comment.

**Comment by flensrocker** [comment]
Ok, waiting for the next version. :)
I successfully use IdentityUser and IdentityRole with Int64 keys. Just found these two functions which lacks support for custom key types. Most of the time I need FindByNameAsync.

Thanks!

**Comment by rustd** [comment]
Closing as By Design.
