### ISSUE TITLE
How to custom PreSignInCheck in SignInManager.

### ISSUE THREAD

**Issue by PMExtra** [aspnet/Identity#720]
Our project want to custom a check when login, and that will return a custom SignInResult.
I found only a method named CanSignInAsync, but that will return a bool, and final it return the SingInResult.NetAllow.

So, why the PreSignInCheck method is private? It's for this reason that I must override many SignIn method like PasswordSignInAsync, TwoFactorSignInAsync, ExternalLoginSignInAsync.

So, I wish PreSignInCheck can be public in next version.

**Comment by rustd** [comment]
Please use CanSignIn() https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L122

**Comment by PMExtra** [comment]
What? I know CanSignIn()
but the method could only return a bool value.
and finally I will get the SignInResult.NotAllow.
I want to custom the SignInResult with my check.

**Comment by PMExtra** [comment]
@rustd Could you review the issue？

**Comment by PMExtra** [comment]
ok, i got it.
override the SignInAsync() will solve my problem. It seems that all xxxSignIn method will call SignInAsync() inner.

**Comment by PMExtra** [comment]
I am still beset by this problem...
