### ISSUE TITLE
Consider overload of SignIn that specifies whether CanSignIn is checked before signing in

### ISSUE THREAD

**Issue by PMExtra** [aspnet/Identity#721]
When I set "RequireConfirmedEmail = true" in SignInOptions, the SignInManager.SignInAsync will skip PreSignInCheck (ex. Check the Email confirmed).
The visual studio template Account/Register action will take the SignInAsync method.
So, When I register a new account, I will sign-in successful. Then, if I log out, I could't sign-in again.

So, I think that SignInAsync method should take the PreSignInCheck?

**Comment by HaoK** [comment]
CanSignIn is the method that looks at the SignInOptions like RequireConfirmedEmail.  The two normal flows (PasswordSignIn/ExternalSignIn) ensure that CanSignIn is true before calling SignIn.  But if you are directly calling SignInAsync, you will need to check that the user can sign in first if desired.  

We could tweak this a bit, by having an overload of SignInAsync that takes a `bool checkCanSignIn` to clear this up a bit.

Thoughts @divega @blowdart @rustd?

**Comment by blowdart** [comment]
I don't think the parameter clarifies anything :(

**Comment by rustd** [comment]
Well atleast it puts it in the API so users can see. Without it they need to find the other API to call :)

**Comment by HaoK** [comment]
Well the implementation change with the new overload would push the check into SignIn instead of Password/External, so we could have SignIn default to check the flag, and only if you explicitly disabled it would you get the existing behavior (so it'd be a slight breaking change)

**Comment by PMExtra** [comment]
ok, I got it.
But, there is still a problem about the project template in Visual Studio (2015 Update1) : 
if I set RequireConfirmedEmail = true in SignInOptions,
When I register a new account, I will login success. Then, if I logout, I couldn't login again.

**Comment by HaoK** [comment]
That is by design, you can't login if the email isn't confirmed.  You should make sure there's a flow to confirm the email before logging them in.
