### ISSUE TITLE
No Option To Map To Stored Procedures

### ISSUE THREAD

**Issue by Marren85** [aspnet/Identity#722]
There is no option to map Idenetiy to stored procedures. I cannot run my code without it and don't know how to do a workaround.

In MVC 5 I simply added:

modelBuilder.Entity<IdentityUser>().MapToStoredProcedures();

overriding onmodelcreating in my Identity model but I can't seem to do that now.

Anyone help?

**Comment by rustd** [comment]
@rowanmiller what is the bug number tracking this in EF? @divega mentioned it is in the backlog

**Comment by divega** [comment]
Found it. 

The Identity stores we offer out of the box are for EF Core, and EF Core will not support stored procedure mapping in the initial release (we use the following issue to track the feature in our backlog: https://github.com/aspnet/EntityFramework/issues/245). 

In the meanwhile it should be possible to produce your own Identity store implementations (i.e. UserStore and RoleStore) that use stored procedures for persistence based on some other means.
