### ISSUE TITLE
ASP.NET 5 Identity with one table and 4 columns

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Identity#723]
_From @kjanshair on January 26, 2016 15:37_

I creating an ASP.NET MVC 6 application which uses Identity with Entity Framework on SQL Server. By default, it creates 5 tables in the database

AspNetRoles
AspNetClaims
AspNetLogins
AspNetRoles
AspNetUsers

But I want only 1 table in the database instead of these 5 with 4 columns integer Identity Column, UserName, Email and Password (Hashed). How do I implement or create a custom user store?

_Copied from original issue: aspnet/Security#678_

**Comment by SharePointRadi** [comment]
You can look at a user store implementation here : https://github.com/OneBitSoftware/Microsoft.AspNet.Identity.EntityFramework6/blob/master/src/Microsoft.AspNet.Identity.EntityFramework6/UserStore.cs
That should give you enough info on how ant what to do. If you look at IdentityDbContext you will see how the model gets created, you can tweak it to your liking.

**Comment by rustd** [comment]
Please look at the above comment.

**Comment by kjanshair** [comment]
@SharePointRadi the code you provided is pretty long. Can you please provide a shorter and more elaborated version of the problem? I'm searching throughout the Internet but couldn't get through yet. Thanks.
