### ISSUE TITLE
How to custom a SignInResult

### ISSUE THREAD

**Issue by PMExtra** [aspnet/Identity#728]
I am already submit a issue about this question at https://github.com/aspnet/Identity/issues/720 .
But this reply appear to have misunderstood what I mean.
I want to custom some check and return custom result.
Then, I can not find a suitable method to override.

ex:
My company has many employees. Some of them are in-service, and some have left.
I want to check their in-service before sign-in. And gives friendly tip when check failed.
I can't delete their accounts because there are other associated data files need to stay. (Some foreign key contains the account)

**Comment by PMExtra** [comment]
I just got, my thoughts may be wrong.
I want to declare a class " AppSignInResult : SignInResult " ,
but I can't override a method with different return type.

So, how to solve my needs like the example?

**Comment by PMExtra** [comment]
...finally, I copy the source from SignInManager and custom a parallel AppSignInManager class without inherit... I solve it...

**Comment by divega** [comment]
@HaoK please take a look to see if you can help.

**Comment by HaoK** [comment]
Looks like you have resolved all your outstanding issues already?  closing
