### ISSUE TITLE
Cascading delete should work

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Identity#730]
**This is the code to delete user**
```
var user =await _userManager.FindByIdAsync(id);
                if (user != null)
                {
                    await _userManager.DeleteAsync(user);
                }     
```

**This is the error I get**
```
<h1>A database operation failed while processing the request.</h1>
        <p>
                <span>DbUpdateException: An error occurred while updating the entries. See the inner exception for details.</span>
                <br />
                <span>SqliteException: SQLite Error 19: &#x27;FOREIGN KEY constraint failed&#x27;</span>
                <br />
        </p>
```

I can create user without any problem at all, thus Delete suppose to be just working right?

**Comment by andrew-vandenbrink** [comment]
Could be caused by user still attached to role, any api to delete cascade?

**Comment by HaoK** [comment]
Cascading deletes should be enabled by default after this commit: https://github.com/aspnet/Identity/commit/c847f9c50df478ef826f6d4781ddcd760325da78

Can you verify that you haven't changed the model in your db context's OnModelCreating at all?

**Comment by andrew-vandenbrink** [comment]
No, not ef fan here so i dont touch OnModelCreating,just accidentally assign to role right after create user

**Comment by HaoK** [comment]
What build are you using?

**Comment by andrew-vandenbrink** [comment]
Rc1, I'll wait for Rc2 to be released to test.

**Comment by HaoK** [comment]
Ok please reopen this if you still see this issue should be working now
