### ISSUE TITLE
External logins - process callback error redirect

### ISSUE THREAD

**Issue by praneethw** [aspnet/Identity#731]
I am using facebook as an external login. Currently based on my configurations, upon clicking **"Okay"** and approving access to the FB app, I am redirected back to my ASP.NET site callback action and I am able to get the external login info using **GetExternalLoginInfoAsync() **.

The problem I am facing is that, during the approval process, if I click the ** "Cancel"** I am redirected to my ASP.NET site with the redirect not being processed. The resulting URL is,

**http://localhost:57636/signin-facebook?error=access_denied&error_code=200&error_description=Permissions+error&error_reason=user_denied&state=CfD....**

Looking at my browser network log, I see that there is a status code 500 with Internal Server error. Does this mean I have not configured my startup configs properly? If not how would it be possible for me to get the callback action invoked with the remoteError parameter populated as in the sample application provided?

Your help is much appreciated.

**Comment by HaoK** [comment]
This behavior is by design, if you click cancel fb auth fails as you'd expect and that is clear from the errors in the query string "access_denied", error_reason= "user_denied"

**Comment by HaoK** [comment]
Note if you want to handle the cancel in some way, you can hook the OnRemoteError event and look for the error_reason of user_denied to do something special...

Configure the FacebookOptions.Events
```
                Events = redirect ? new OAuthEvents()
                {
                    OnRemoteFailure = ctx =>
                    {
                        // do something when ctx.Failure.Message contains "user_denied"
                        ctx.HandleResponse();
                        return Task.FromResult(0);
                    }
                } : new OAuthEvents()
```
