### ISSUE TITLE
Token Options

### ISSUE THREAD

**Issue by stevejgordon** [aspnet/Identity#733]
I was wondering if it is correct within the TokenOptions class that all of the properties are set to the DefaultProvider string rather than using the Email and Phone ones where applicable?

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/TokenOptions.cs#L26

**Comment by blowdart** [comment]
This is probably a naming problem. In reality they're 2fa tokens used during 2fa logins. There is a PR coming which will rename these properties and make it easier to understand what their actual function is.
