### ISSUE TITLE
How to control Google/Facebook/Twitter cookie expiration?

### ISSUE THREAD

**Issue by pepevc** [aspnet/Identity#740]
It looks Google maintains the user for 10 minutes logged in. It is not clear in the documentation how to control this. I tried multiple combinations of values for ExpireTimeSpan, SlidingExpiration, AutomaticAuthenticate, AutomaticChallenge in the AddIdentity method but nothing seems to work. I get logged of in about 10 minutes.

**Comment by blowdart** [comment]
When you say google maintains the user what do mean? Are you talking about the external signing cookie identity sets? Or Google's own login pages?

**Comment by blowdart** [comment]
Closing due to no response
