### ISSUE TITLE
Per-request options

### ISSUE THREAD

**Issue by joshmouch** [aspnet/Identity#741]
As far as I can tell, there's no way to configure any of the Identity Framework options per request.  In other words, using a Transient or Scope scoped in the DI container instead of Instance scope.

I'd like to do the following to support a multi-tenant environment:
````
services.AddScoped<CookieAuthenticationOptions>((serviceProvider) =>
			{
				var applicationContext = serviceProvider.GetService<IApplicationContext>();
				return new CookieAuthenticationOptions()
				{
					CookiePath = applicationContext.ClientBaseUrl,
				};
			});
````

However that method is only called once during startup, and not once per scope as I would have hoped.

Looking into the code, it appears this isn't really supported because the options are only pulled from the DI container sometimes, and other times they're passed around internally as arguments, and sometimes they're added internally to the DI container as an IServiceCollection.AddInstance (therefore ignoring my IServiceCollection.AddScope).

Is this correct, or am I missing something?

**Comment by joshmouch** [comment]
Perhaps one way to tackle this would be to make the properties/methods on CookieAuthenticationOptions virtual so that I could override the properties and generate their value per-request.

Have you considered making your CookieAuthenticationOptions class extensible?

**Comment by blowdart** [comment]
Identity is not designed for multi-tenant scenarios in any way, shape or form.

**Comment by MaximRouiller** [comment]
One way would be to to provision a site for each of your tenant. Each with their own identity/urls/settings/etc.

That would also allow you to control the migration of each clients onto new APIs and such.

That being said, it's not a discussion for aspnet/Identity. :smile:

**Comment by joshmouch** [comment]
I think if I take the word "multi-tenant" out of the title, this is still a valid question.  Perhaps you have multiple directories in your site that require different credentials.  How would that be done?

**Comment by blowdart** [comment]
We wouldn't target identity at a site that needs separate authentications per directory either.
