### ISSUE TITLE
Change username's default allowed characters to confirm better to email spec

### ISSUE THREAD

**Issue by janpieterz** [aspnet/Identity#742]
Since the default configuration in the samples, and presumably in quite a lot of systems will be that the username is the email address, it threw me off a little bit when discovering that the + sign is not an allowed character in a username.

I was thinking that it would be helpful to offer the email's allowed list (see [this ](http://stackoverflow.com/a/2049510/1202118)answer of someone diving into the allowed characters).

If this is not feasible (I can imagine that a username should be something remotely readable, although one could argue that an email should be as well), would it be possible to offer both versions of these strings as a const string in the user options class, so that this behavior is not repeatedly implemented by every application? In either case, the current implementation suggests it allows email addresses (the @ and .) but it doesn't actually fully implement this.

The string I use in my application (as far as I know I'm only missing the 'quoted' character requirement):
```
abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!#$%&'*+-/=?^_`{|}~.@
```

**Comment by HaoK** [comment]
@blowdart the delta appears to be the following characters, how many of these do you want to enable by default, some of these look pretty wonky to be valid user name characters by default...

!#$%&'*+/=?^`{|}~

**Comment by blowdart** [comment]
Oh that is bad isn't it. Lots of invalid characters for emails. This is strange. Either we update the samples so it's not emails, or we pare it down a bit.

**Comment by MaximRouiller** [comment]
> I can imagine that a username should be something remotely readable, although one could argue that an email should be as well

@janpieterz Well... [the original RFC compliant regex](http://ex-parrot.com/~pdw/Mail-RFC822-Address.html) doesn't argue. That is if you want to validate as per the RFC.

There is many characters that are available in an email (`()[]+-<>` among others).

[Good read](http://girders.org/blog/2013/01/31/dont-rfc-validate-email-addresses/) if you want to go further. 

One thing for sure... refusing a valid email is plainly frustrating to most users.

**Comment by MaximRouiller** [comment]
I do use the `+` sign in my Gmail address. Allows me to tag emails I use to register to some services.

**Comment by blowdart** [comment]
We won't be using regular expressions for validation. We made a conscious decision to remove that approach.

**Comment by GuardRex** [comment]
For reference, `AllowedUserNameCharacters` is here ...

https://github.com/aspnet/Identity/blob/c8a276e716064ac40df5a56512e0217b14b48060/src/Microsoft.AspNetCore.Identity/UserOptions.cs#L17

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@

Is there any reason why that can't be overridden no matter what the team settles on here?

**Comment by janpieterz** [comment]
@GuardRex  It can (quite easily even) be overridden. Below does the trick. The issue (more an issue with the template and a suggestion for improvement for Identity) isn't the override, but more the fact that the default templates use an email as a username (and I think this is a very common usage pattern) and this fails when certain characters are used, for example the `+` (I found this out as well when testing with a + sign). The options then are to either **_always_** allow all email chars 
**_or_** have two statics strings (one with email, one with 'normal') **_or_** change the templates.
```
 services.AddIdentity<ApplicationUser, IdentityRole>(options =>
    {
        //Below UserOptions is my own class
        options.User.AllowedUserNameCharacters = UserOptions.EmailAllowedCharacters;
    })
```

**Comment by HaoK** [comment]
How about we just add + since that is fairly common, users can always add whatever additional characters they really want?

**Comment by MaximRouiller** [comment]
@HaoK that would fix 90+% of all scenarios I think.

**Comment by janpieterz** [comment]
Works for me!

**Comment by HaoK** [comment]
+ it is, thanks!
