### ISSUE TITLE
redundant method call in UpdateSecurityStampAsync method of UserManger class

### ISSUE THREAD

**Issue by amitkraghuvanshi** [aspnet/Identity#743]
redundant method call in  method below
     public virtual async Task<IdentityResult> UpdateSecurityStampAsync(TUser user)
        {
            ThrowIfDisposed();
            **GetSecurityStore();  // This code in not doing anything and have no use of this method call**
           
          if (user == null)
            {
                throw new ArgumentNullException("user");
            }         

            await UpdateSecurityStampInternal(user);
            return await UpdateUserAsync(user);
        }

**Comment by blowdart** [comment]
This is deliberate. It's a way of checking if the store implementation supports the API. As it's an internal call we're not so worried about naming.
