### ISSUE TITLE
Remove setters from IdentityCookieOptions

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Identity#744]
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/IdentityCookieOptions.cs#L53-L56
https://github.com/aspnet/Security/issues/588#issuecomment-183419422

The various CookieAuthenticationOptions properties on IdentityCookieOptions should not be settable because they contain significant default configuration.

While you're at it: What's up with the *CookieAuthenticationScheme properties? Modifying them does not modify the associated CookieAuthenticationOptions. Maybe these properties should just be wrappers around the related CookieAuthenticationOptions.AuthenticationScheme properties.

**Comment by jods4** [comment]
@Tratcher Modifying `*CookieAuthenticationScheme` is not the only way you get the problem (at least I didn't). You can also modify `*Cookie.AuthenticationScheme` or set a `new CookieAuthenticationOptions` and the schemes are not in sync anymore.

**Comment by HaoK** [comment]
Yeah these schemes no longer are needed, they used to be statics for extension methods that were removed recently.  I can nuke the duplicate copies, the only source of truth for the schemes should be the cookie options instances

**Comment by HaoK** [comment]
I think the setting of cookie instances is okay on the IdentityCookiesOptions, but I agree the auth scheme properties are redundant and should be removed
