### ISSUE TITLE
Automatic lockout doesn't work (Microsoft.AspNet.Identity.EntityFramework)

### ISSUE THREAD

**Issue by cbmek** [aspnet/Identity#747]
When You enable automatic lockout by:
` var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: true);`
it starts to count failures correclty (in AccessFailedCount) and after configured amount of failures it sets only LockoutEnd column to proper date. - this seams to work ok.
But when LockoutEnd is set and one try to log in and fail again, nothing happens because LockoutEnd is never used - only LockoutEnabled is checked:

From userStore.cs:
```csharp
    public virtual Task<bool> GetLockoutEnabledAsync(TUser user, CancellationToken cancellationToken = default(CancellationToken))
    {
        cancellationToken.ThrowIfCancellationRequested();
        ThrowIfDisposed();
        if (user == null)
        {
            throw new ArgumentNullException(nameof(user));
        }
        return Task.FromResult(user.LockoutEnabled);
    }
```

So the actual lockout never happen, it just cont failures, set dates and restart counting.
I'm not sure how it's supposed to work, but I see two options:
1) Check in GetLockoutEnabledAsync fo LockoutEnd value also.
2) SetLockoutEndDateAsync shold also set LockoutEnabled = true.

**Comment by HaoK** [comment]
Are you saying userManager.IsLockedOutAsync returns false in these situations?

**Comment by cbmek** [comment]
I'm saying `var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: true);`
returns `result.Succeeded` instead of `result.IsLockedOut`.

But yes, it's using `IsLockedOutAsync`, which is calling `store.GetLockoutEnabledAsync`.

**Comment by HaoK** [comment]
So for a user to be locked out, two things need to be true.

Lockout must be enabled for the user, meaning user.IsLockoutEnabled must be true AND user's locked end date must be in the future...

```
            if (!await store.GetLockoutEnabledAsync(user, CancellationToken))
            {
                return false;
            }
            var lockoutTime = await store.GetLockoutEndDateAsync(user, CancellationToken);
            return lockoutTime >= DateTimeOffset.UtcNow;
```

You can think of it as a flag saying the user can be locked out ever, and only if that is true, does the lockout end date matter...
