### ISSUE TITLE
Proposal: make UserStore.ThrowIfDispose protected

### ISSUE THREAD

**Issue by divega** [aspnet/Identity#750]
_From @sumtec on February 19, 2016 5:51_

Hi,

Is it possible to make ThrowIfDispose in the UserStore<> protected? I am trying to make it work for a legacy database and I have to write my own UserStore to enable login. When trying to implementing the UserStore class, I found no way to call the ThrowIfDispose.

I need to query different table to get a wrapped IdentityUser object. So, I can't call the FindByName in the base class directly. Or, any other advice other than implementing my own UserStore class?

Thanks,
Frank

_Copied from original issue: aspnet/EntityFramework#4607_

**Comment by HaoK** [comment]
472c6f87348c7f8f7a29a22f1fb7fe9cb3b5411e
