### ISSUE TITLE
File database relative path connection string issue

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Identity#751]
Not sure if this can be solved but an issue anyway
This is the configuration
![image](https://cloud.githubusercontent.com/assets/12871379/13173635/087de5fe-d6ff-11e5-869e-06d3ed47be96.png)

When developing with local machine its expect the databases to reside in the same level of source code
![image](https://cloud.githubusercontent.com/assets/12871379/13173667/38257ede-d6ff-11e5-88c8-68966cb6fc20.png)

When you deploy it, it expect the databases to be resided at
![image](https://cloud.githubusercontent.com/assets/12871379/13173696/5f60aaa0-d6ff-11e5-9bc2-73f895d255dd.png)

where it "ideally" it should expect the databases to reside at **approot/src/{project_name}/**

Of course I know there is workaround to put additional production appsettings.json and use different path.

**Comment by divega** [comment]
@Eilon any insights on this feedback and what the "ideal" location for a database file would be at development time and on deployment? 

FWIW, our SQLite provider simply uses `AppContext.BaseDirectory` (or equivalent) to resolve file name locations in the connection string.

**Comment by Eilon** [comment]
I have no strong opinion on this, as long as it's not in `wwwroot` :smile:

**Comment by MaximRouiller** [comment]
`App_Data`? :stuck_out_tongue_winking_eye:

**Comment by blowdart** [comment]
This really isn't an identity issue, it's more a configuration one. @Eilon where should this bug end up?

**Comment by divega** [comment]
It a question/suggestion about what should the base path be at development and deployment so I don't think @blowdart means "configuration" in the [aspnet/Configuration](http://github.com/aspnet/configuration) sense. 
Maybe [aspnet/hosting](http://github.com/aspnet/Hosting)?

**Comment by divega** [comment]
This issue was moved to aspnet/Hosting#639
