### ISSUE TITLE
Implement Azure Table Storage support

### ISSUE THREAD

**Issue by gblmarquez** [aspnet/Identity#76]
Hi,

I think add support for Table Storage is a good feature, as it's fast and reliable.

How I could contribute with this feature?

Thanks,

Gabriel Marquez

**Comment by MaximRouiller** [comment]
Just bumping this up to see if there's any progress on this front.

**Comment by Eilon** [comment]
@MaximRouiller we are not planning on building this provider at this time, so no updates. If anyone wants to work on it I think we'd be happy to collaborate on the design.

**Comment by MaximRouiller** [comment]
Let's say that maybe I would perhaps be interested in doing it. ;-)

Who would I need to bother? Would it be integrated into the main framework or would it need to be a separate package? 

Finally, if you need my email for further discussions let me know. :)

**Comment by rustd** [comment]
Email is fine for packaging details. You can post any questions in this repo to @HaoK @divega and we will be happy to help.

**Comment by Eilon** [comment]
Looks like @MaximRouiller is going to take crack at this. Thank you!

**Comment by MaximRouiller** [comment]
I'll give it my best!

**Comment by SharePointRadi** [comment]
Hey @MaximRouiller do you need a hand? I've built my own MongoDB provider and have most likely run into similiar issues/challenges. I'm also condidering a Document DB provider.

**Comment by MaximRouiller** [comment]
I've looked at it and asked several people around and they all told me the same thing.

It's not a good idea as it won't be able to scale after a while. Perfect for small solutions but once you start to hit anything bigger, you will encounter performance issues and full table scan. 

So at that point you'll need to migrate which won't be as easy. If you are on the cloud, there's already something out that is called Azure AD B2C which basically makes the whole username/password completely useless.

If you want to make a crack at it, go! :smile:

**Comment by SharePointRadi** [comment]
Table Storage doesn't make that much sense, but DocumentDB does :)

**Comment by MaximRouiller** [comment]
Oh absolutely. :smile: I've just decided to not waste time on Table Storage.

**Comment by alexsandro-xpt** [comment]
+1

**Comment by dlmelendez** [comment]
Table Storage Provider working on Identity 3.0 RC1 - https://www.nuget.org/packages/ElCamino.AspNet.Identity.AzureTable/2.0.0-beta2
Unfortunately, I have not had the time to move the project to GitHub yet, it is in the works..- https://identityazuretable.codeplex.com/

**Comment by dlmelendez** [comment]
Table Storage for Identity Core [https://github.com/dlmelendez/identityazuretable](url) .
