### ISSUE TITLE
Assembly version incorrect versus nuget package version

### ISSUE THREAD

**Issue by mwpowellhtx** [aspnet/Identity#761]
Hello,

Microsoft.AspNet.Identity.Core NuGet package version is 2.2.1.

Microsoft.AspNet.Identity.Core.dll version is 2.0.0.0. I think it too should be 2.2.1.X. Whatever X is, the [build number](http://www.symbolsource.org/MyGet/Metadata/aspnetwebstacknightly/Project/Microsoft.AspNet.Identity.Core) appended to the nightly build number, perhaps.

That is all.

Thank you...

**Comment by jdluzen** [comment]
It appears that they're switching to a new assembly: https://www.nuget.org/packages/Microsoft.AspNet.Identity/

**Comment by mwpowellhtx** [comment]
Fair enough. What is the Github for it?

**Comment by jdluzen** [comment]
This current repo should be it. Current version is 3.0.0-rc1, though I can't point to a version number in the code to verify.

**Comment by mwpowellhtx** [comment]
What do you mean "in the code"? There isn't an ``AssemblyInfo.cs``, common, etc?

**Comment by blowdart** [comment]
You are confusing the "Core" of identity 2.0 with Core of ASP.NET. So you are attempting to add the previous version for .NET 4.5.

**Comment by mwpowellhtx** [comment]
No, I don't think so. _Microsoft.AspNet.Identity.Core_ package version is _2.2.something_; whereas, this is the assembly properties itself. Note, Version should also read _2.2.something_, for consistency.

![microsoft aspnet identity core-assembly-properties](https://cloud.githubusercontent.com/assets/1824187/13657642/d3714262-e63e-11e5-9b47-5906f66db390.png)

**Comment by mwpowellhtx** [comment]
Kindly reopen until you've fact checked please. Or if there is a better repository I should be directing my questions, kindly reference me there. Thank you.

**Comment by MaximRouiller** [comment]
@mwpowellhtx This is technically the repository for [Identity 3.X](https://www.nuget.org/packages/Microsoft.AspNet.Identity/).

You are talking about Identity 2.X which is the version built for the previous version of ASP.NET.

As for the 2.X versioning scheme, it might be a bit late to retroactively fix that.

My opinion? I don't care what the build number is. I care about the GitHub tag that was used to generate this assembly. Of course, the assembly number is important (major,minor especially) but the Nuget package version is more critical. In 3.X, if you go in the "tags", you can basically navigate to the code that was used to generate that assembly.

**Comment by mwpowellhtx** [comment]
My assertion is, I don't care which you consider the source, the two ought to be consistent, especially when it comes to questions that come up, assembly queries, etc.

As for retroactive, forward progress; respond as you will. Obviously, if the retro is considered abandoned in favor of the new one, by all means treat it as such.

Thanks for the feedback.
