### ISSUE TITLE
ThrowIfDisposed should be protected

### ISSUE THREAD

**Issue by mwpowellhtx** [aspnet/Identity#762]
Hello,

In [UserManager](http://mandrillapp.com/track/click/30209653/www.symbolsource.org?p=eyJzIjoidXBxYy1WMjg0ZU9xQ2lrd1JYMk9rVlU3VWVVIiwidiI6MSwicCI6IntcInVcIjozMDIwOTY1MyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvd3d3LnN5bWJvbHNvdXJjZS5vcmdcXFwvTXlHZXRcXFwvTWV0YWRhdGFcXFwvYXNwbmV0d2Vic3RhY2tuaWdodGx5XFxcL1Byb2plY3RcXFwvTWljcm9zb2Z0LkFzcE5ldC5JZGVudGl0eS5Db3JlXFxcLzIuMy4wLXJ0bS0xNTA4MDZcXFwvUmVsZWFzZVxcXC9EZWZhdWx0XFxcL01pY3Jvc29mdC5Bc3BOZXQuSWRlbnRpdHkuQ29yZVxcXC9NaWNyb3NvZnQuQXNwTmV0LklkZW50aXR5LkNvcmVcXFwvVXNlck1hbmFnZXIuY3M_SW1hZ2VOYW1lPU1pY3Jvc29mdC5Bc3BOZXQuSWRlbnRpdHkuQ29yZVwiLFwiaWRcIjpcIjFkMDUzMWNlMmE1ZjRhZmNiOTRjNzE3N2IxOGVlYjgyXCIsXCJ1cmxfaWRzXCI6W1wiYTI1ZThhMGRiOTFkY2E3NWYwMGQyNGIwMzA0ZTkyMjZjYWJkZjg1MFwiXX0ifQ), ThrowIfDisposed should be protected. Today it is private.

```C#
protected void ThrowIfDisposed()
{
    if (_disposed)
    {
        throw new ObjectDisposedException(GetType().Name);
    }
}
```

Tangent to that is to expose an IsDisposed property.

Thank you.

**Comment by blowdart** [comment]
Linked to #750

**Comment by mwpowellhtx** [comment]
Thanks...

**Comment by HaoK** [comment]
41fa99e9f329180c2e956b3a092af3f13e1fc357
