### ISSUE TITLE
Cookie names not set properly.

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Identity#763]
I overlooked the fact that setting the AuthenticationScheme values does not actually achieve what we want. By default, schemes are set to `.AspNetCore.{AuthenticationScheme}` and this leads to names like `.AspNetCore..AspNetCore.Identity.Application` since cookies middleware adds the `.AspNetCore.` prefix by default. We can remove the `.AspNetCore.` from the prefix of the authentication scheme.

Still investigating the why there are also cookies like `.AspNetCore.Microsoft.AspNetCore.Identity.ExternalLogin`.

**Edit**: Ignore the ExternalLogin cookie issue. That is a really old legacy name for the cookie and the test is only checking it for non-existence.

fyi @natemcmaster

**Comment by natemcmaster** [comment]
>  By default, cookie names are set to .AspNetCore.{AuthenticationScheme}

Where is this in code?

**Comment by JunTaoLuo** [comment]
@natemcmaster I mean the default schemes https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/IdentityCookieOptions.cs#L16-L20
