### ISSUE TITLE
authentication timeout after successful login - ignoring appCookie.ExpireTimeSpan property

### ISSUE THREAD

**Issue by philwindsor** [aspnet/Identity#766]
Apologies if this is the incorrect process for logging issues but I've asked this question on SO: http://stackoverflow.com/questions/35695975/asp-net-mvc-core-and-identity-3 and had no answers

Everything appears setup ok but after a certain amount of time I'm logged out. 

I have the cookie timeout set to 8 hours and SlidingExpiration is set to true but it logs me out way before 8 hours, its something like 20-30mins after it kicks me out

appCookie.SlidingExpiration = true;
appCookie.ExpireTimeSpan = TimeSpan.FromHours(8);

Does it have something to do with session at all?

**Comment by HaoK** [comment]
Make sure you are configuring the cookie via identityOptions and not any other way, can you include the startup code that you are using to set the cookie options?

**Comment by HaoK** [comment]
Please reopen if this is still a problem and can attach the relevant startup...

**Comment by ole1986** [comment]
I do not know if this is still an issue but I noticed when I used 
`ApplicationCookie.ExpireTimeSpan = TimeSpan.FromMinutes(5)`
And cookie has never been created (or shown in browser) and I also get not "logged in"

As I have UTC + 2 (Berlin) timezone, I tried `DateTime.Now.Subtract(DateTime.UtcNow).Add( TimeSpan.FromMinutes(5.0) );` which makes the TimeSpan to **02h05m**. But in Chrome browser using "EditCookie" it shows **5 minutes difference only** and login worked

**Comment by korzh** [comment]
One note: it seems that ExpireTimeSpan and other options work well only if you set RememberMe parameter to true during SignIn... call.
