### ISSUE TITLE
Reset Password Fails Token Validation

### ISSUE THREAD

**Issue by Fosol** [aspnet/Identity#773]
Not sure what I'm doing wrong, but I can't get the token to validate when attempting to reset a password.
This fails every time when it calls VerifyUserTokenAsync.
```
var token = await this.UserManager.GeneratePasswordResetTokenAsync(user);
return await this.UserManager.ResetPasswordAsync(user, token, password);
```

**Comment by blowdart** [comment]
Can you check if the user in question has a null security stamp?

**Comment by divega** [comment]
Triage: we are closing this issue because we haven't heard back in a long time. Feel free to re-activate if you are still experiencing problems in this area.
