### ISSUE TITLE
jwt authentication

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Identity#778]
Hi,
  I'm trying to implement a sample project template, like the starndard asp.net template, using frameworks as aurelia and angular 2, and I have to handle authentication. To do this the client libraries I found uses JWT, and I'm looking how to implement it.
  Since should be a simple template I would like to implement a solution as simple as possible: I heard about identity server and found samples like this https://github.com/paulvanbladel/aurelia-identityserver-aspnetcore, but require multiple site and it's an overkill solution.
  To implement a simpler solution I lookied at System.IdentityModel.Tokens.Jwt to create tokens in a simple way: seems to work, but now I have the problem of handling the logout: from what I understand , in a simple way, I have to revoke the token and is not possible to handle client side, and I have to keep a server cache of the tokens that have been revoked and refuse requests done with there tokens.
  If I'm corrent, is this supported by Identity or is possbile to take advantage of Identity to handle this?

**Comment by MaximRouiller** [comment]
What are you authenticating against?

Equivalent to Forms Auth? Your own SSO solution? ADFS as SSO? Facebook? Google? Twitter?

It might not look like much but each have their own solution.

**Comment by lucamorelli** [comment]
The equivalent of Forms Auth. the idea is to create a project template functionally equivalent to the actual asp.net template, but based on spa frameworks.

**Comment by blowdart** [comment]
There's no built in functionality for what you require
