### ISSUE TITLE
Question: How to get ClaimsPrincipal from (string) id?

### ISSUE THREAD

**Issue by jasonwilliams200OK** [aspnet/Identity#779]
When user gets logged in, I store the result of `HttpContext.User.GetUserId()` in a static dictionary.
When user gets logged out, I remove the user from the dictionary.

This dictionary storage is meant for external applications, which when make an HTTP call to my MVC application with a special header set; a middleware in place checks if that header is set, treat its value as encrypted user id, decipher the value and check if it is present in the dictionary, then responds with JSON with certain message. The caller service (external app) let the user operates on its end based on this JSON response, otherwise redirects the user to my MVC app for authentication with return URL. After the successful authentication on MVC side, we append the encrypted uid to redirect URL, which external app set to the cookie on their side of the kerb (aka SSO).

I was hoping to avoid having this shared dictionary and instead getting the actual `ClaimsPrincipal` by user id (the way aspnet frameworks constructs CP when the cookie is present in `HttpContext.Request`), so I could simply call `IsSignedIn()` (e.g. `HttpContext.GetUserById("..").IsSignedIn()`). Is there a way to do so and hence making the solution more resilient?

Any recommendations/comments about the overall solution, pertaining to security and trust are welcome as well.

**Comment by blowdart** [comment]
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/IUserClaimsPrincipalFactory.cs

    Task<ClaimsPrincipal> CreateAsync(TUser user);

That should get you a principal from a user object.

**Comment by jasonwilliams200OK** [comment]
Thanks @blowdart and sorry for the late response (was busy with lifey stuff).

So in a middleware I am having:

```c#
var customStorageService = context.RequestServices.GetService<CustomMemroyStorage>();
IdentityUser identityUser = customStorageService.GetUser( context.User.GetUserId() );
```

Now to get ClaimPrincipal of this user, I did:

```c#
var um = context.ApplicationServices.GetService<UserManager<IdentityUser>>();
var rm = context.ApplicationServices.GetService<RoleManager<IdentityRole>>();
var io =new OptionsManager<IdentityOptions>(new List<IConfigureOptions<IdentityOptions>>());

Task<ClaimsPrincipal> principal= new UserClaimsPrincipalFactory<
                                             IdentityUser,
                                             IdentityRole
                                   >( um, rm, io )
                                .CreateAsync( identityUser );
```

My only gripe is the part where we are mandated to specify some arbitrary `IOption<IdentityOptions>` object in factory ctor..

In addition to this existing ctro, can we have `UserClaimsPrincipalFactory<TUser>(UserManager<TUser>)` (re: #617) and `UserClaimsPrincipalFactory<TUser>(UserManager<TUser>, RoleManager<TRole>)` which can use a default options object?

**Comment by HaoK** [comment]
You shouldn't need to create your own UserClaimsPrincipalFactory, you should be able to resolve it from ApplicationServices just like the managers...
