### ISSUE TITLE
Microsoft.AspNet.Identity.EntityFramework  could not be found

### ISSUE THREAD

**Issue by kuashe** [aspnet/Identity#783]
I tried to install Microsoft.AspNet.Identity.EntityFramework RC1 with Nuget targeting .NET 4.5.1 using visual studio 2015

I have this issue everytime , tried on two different computer 

**How to reproduce** :

In Visual Studio 2015 Community ,

File -> New -> Project -> Console Application (.NET 4.5.1 )
Run  "Install-Package Microsoft.AspNet.Identity.EntityFramework -Pre" in package manager console
Build solution 
Error appear in the error list .

![image](https://cloud.githubusercontent.com/assets/6097946/14113167/0aa0682e-f5d2-11e5-9313-895db5ed8200.png)

**Comment by MaximRouiller** [comment]
Weird...

[It does show](https://www.nuget.org/packages/Microsoft.AspNet.Identity.EntityFramework/3.0.0-rc1-final) that it is supported.

**Comment by kuashe** [comment]
Indeed, but the package is not instaled anywhere . Obliviously it works on .NET Core and DNX .

**Comment by blowdart** [comment]
What feeds do you have setup in nuget? This looks like you're mixing feeds and dependencies. Take a look at https://github.com/aspnet/Home/wiki/NuGet-feeds and choose the single, correct, feed for your situation

**Comment by kuashe** [comment]
@blowdart  I have nuget + myget . 
But i reproduced this issue on a fresh VS2015 on another computer.

![image](https://cloud.githubusercontent.com/assets/6097946/14158476/82c903d4-f6d0-11e5-8f5c-60b0d5b3a984.png)

**Comment by blowdart** [comment]
I'd ask in the entity framework repo. https://github.com/aspnet/EntityFramework

**Comment by kuashe** [comment]
Thanks , i'm going to try that.

**Comment by divega** [comment]
@blowdart do you think this could be an EF issue? All packages mentioned seem to be on the Identity side.

**Comment by kuashe** [comment]
@blowdart  Any update on this ? It's been two weeks now ...

**Comment by divega** [comment]
@kuashe I have tried the repro steps and confirmed that installation of the RC1 version of Microsoft.AspNet.Identity.EntityFramework package fails. I got the following warning/error messages in the output from the install-package command:

```
...
Added package 'Microsoft.AspNet.Identity.EntityFramework.3.0.0-rc1-final' to folder 'c:\users\divega\documents\visual studio 2015\Projects\ConsoleApplication49\packages'
Install failed. Rolling back...
Package 'Microsoft.AspNet.Identity.EntityFramework.3.0.0-rc1-final : EntityFramework.Relational [7.0.0-rc1-final, ), Microsoft.AspNet.Identity [3.0.0-rc1-final, )' does not exist in project 'ConsoleApplication49'
...
Install-Package : Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global 
Assembly Cache.
At line:1 char:1
+ Install-Package Microsoft.AspNet.Identity.EntityFramework -pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPac 
   kageCommand
```

Could you please confirm that you are seeing the same?

@yishaigalatzer and I tried a few more combinations, e.g. downgrading NuGet client to 3.3 and targeting .NET 4.5.2, but as expected that didn't help. We talked about one possible reason for the failure: that there is package in the change of dependencies (Microsoft.AspNet.Identity.EntityFramework -> EntityFramework.Relational -> System.Diagnostics.DiagnosticSource) that depends on a design-time façade, System.Runtime (which appears in the error) and that is not really supported and could be a package authoring error, but it is surprising that installing EntityFramework.Relational directly works without failure.

At this point I will file a bug in NuGet with the symptoms (we believe the error message can use some improvement) and will follow up to try to see if there is a workaround.

**Comment by divega** [comment]
Related issue: https://github.com/NuGet/Home/issues/2193.

**Comment by kuashe** [comment]
@divega Yes , I confirm i have the same error message.

**Comment by divega** [comment]
@kuashe thanks. The good news I found so far that installing the RC2 equivalent (Microsoft.AspNetCore.Identity.EntityFrameworkCore) using NuGet does not fail.

**Comment by kuashe** [comment]
@divega Good news , but i guess it would not work with my projects , I would need to update all my packages to match RC2 naming refactor  .... I'll wait for RC2 i guess , let's hope everything works this time :octopus:

**Comment by kuashe** [comment]
@blowdart  RC2 is out and i managed to install this properly . Closing this .
