### ISSUE TITLE
SqlException: Subquery returned more than 1 value

### ISSUE THREAD

**Issue by sdanko** [aspnet/Identity#785]
When I try to log in or register a user I get the following error:
 
```
Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.
The statement has been terminated.
```

The error appears when calling _await UserManager.CreateAsync(user, model.Password)_ and _await SignInManager.PasswordSignInAsync(model.UserName, model.Password, model.RememberMe, shouldLockout: false)_

**Comment by blowdart** [comment]
@divega Can you help?

**Comment by divega** [comment]
Sure thing...

In general this kind of error can occur if the data in the database does not comply with an assumption made on the query, e.g. consider something like this:

``` SQL
SELECT Id,  
    Price = SELECT Price FROM ProductPrice pp WHERE pp.Id = p.Id
FROM Product p
``` 
This query will only work if there is exactly on ProductPrice row for each Product row. If there is more than one it will fail with the mentioned error.

We should debug and look at our queries to see if there is any generated SQL query that is making assumptions of cardinality that are not actually enforced by the database.

**Comment by blowdart** [comment]
Where is the exception coming from? As in do you get a line number? What database are you using? Do you have multiple users with the same username?

**Comment by HaoK** [comment]
Can you include a stack trace so we can figure out where it is.

**Comment by sdanko** [comment]
[stack.txt](https://github.com/aspnet/Identity/files/197085/stack.txt)

`
Source File: AccountController.cs    Line: 79 `

The tables that are used for Identity are not yet created, but with all databases that I worked with prior to this one, they initialized perfectly normal when running the application for the first time.

**Comment by divega** [comment]
Ok,  thanks for the stack trace. 

It is clear the exception  has nothing to do with the Identity operations in question but is coming from EF migrations. 

It is also clearly not EF Core but an older version, so it is likely not ASP.NET Core Identity either. Just to confirm, what versions of ASP.NET Identity and EF are you using? 

In case it helps,  could you try executing an `update-database -verbose` command directly on the package manager console in VS to see if you can get any more details about what is wrong?

**Comment by sdanko** [comment]
[output.txt](https://github.com/aspnet/Identity/files/199301/output.txt)
Im using EF 6.0 and Identity 2.0. I attached the output of update operation.

**Comment by divega** [comment]
Thanks @sdanko for the additional details. Unfortunately the output doesn't seem to include the actual last SQL statement that Update-Database is trying to execute when the failure occurs. 

Would it be possible for you to capture that statement either using SQL Server Profiler or the Intellitrace window while debugging that part of your application?

**Comment by divega** [comment]
Another thought on this: could you try adding an explicit migration (using Add-Migration_name_ in the package manager console) for the pending changes to see what happens? 

It may not help with either solving or explaining the failure but in general automatic migrations are more brittle than explicit migrations.

**Comment by sdanko** [comment]
I created an explicit migration but I get the same error in package manger console.Also I used SQL Server Profiler and Intellitrace to capture events, but I didnt get any useful information.The last statement that I get in Profiler is :+1: 
```
CREATE TABLE [dbo].[AspNetRoles] (
    [Id] [nvarchar](128) NOT NULL,
    [Name] [nvarchar](256) NOT NULL,
    CONSTRAINT [PK_dbo.AspNetRoles] PRIMARY KEY ([Id])
)
```
But it doesent show any errors.

**Comment by divega** [comment]
Closing this issue as it is not actionable for ASP.NET Core Identity 1.0. I have copied all the relevant information in https://entityframework.codeplex.com/workitem/2926, and we will follow up on it as an EF issue.

**Comment by divega** [comment]
@sdanko sorry for taking so long to respond. If you still have a repro, I have posted another suggestion to try to diagnose the issue at https://entityframework.codeplex.com/workitem/2926.
