### ISSUE TITLE
SignInManager PasswordSignInAsync problem

### ISSUE THREAD

**Issue by Skisas** [aspnet/Identity#789]
Hello,
I came with a problem when using PasswordSignInAsync method, it always returns false when my signin data is wrong and no result ( code stops there ) if info is same as in database. I have created authentication just like in asp.net documentation.Here is my startup.cs:

ConfigureServices:

             services.AddEntityFramework()
            .AddSqlServer()
            .AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration["Data:DbContextConnection"]));

            services.AddIdentity<User, UserRole>(config => 
                {
                    config.User.RequireUniqueEmail = true;
                    config.Password.RequiredLength = 8;
                    config.Cookies.ApplicationCookie.LoginPath = "/App/Login";
                    config.SignIn.RequireConfirmedEmail = false;
                    config.SignIn.RequireConfirmedPhoneNumber = false;
                })
            .AddEntityFrameworkStores<ApplicationDbContext,string>()
            .AddDefaultTokenProviders();

Configure:

            app.UseIdentity();

And my controller that handles login form:

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(
                    model.Email,
                    model.Password,
                    model.RememberMe,
                    lockoutOnFailure: false);

                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(EmployeeController.Contact), "Employee");
                }
                if (result.IsLockedOut)
                {
                    return View("Lockout");
                }
                if(result.IsNotAllowed)
                {
                    return View("Not Allowed");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(model);
                }
            }
            return View(model);
        }

And these methods returns values as expected:

       var user = await _userManager.FindByEmailAsync(model.Email);
       var password = await _userManager.CheckPasswordAsync(user, model.Password);
       await _signInManager.CanSignInAsync(user);

P.S. Registration is working without any problems

**Comment by HaoK** [comment]
What exactly do you mean by "it always returns false when my signin data is wrong and no result "  When you step through it in the debugger it returns false but your controller hangs?

**Comment by Skisas** [comment]
I found that problem was with custom user roles, after I changed it to default identity roles, everything is alright

**Comment by HaoK** [comment]
Awesome.

**Comment by jparmar7** [comment]
> I found that problem was with custom user roles, after I changed it to default identity roles, everything is alright

I am having the same problem as you did.  How did you resolve it?
