### ISSUE TITLE
No authentication handler is configured to handle the scheme: Microsoft.AspNet.Identity.Application 

### ISSUE THREAD

**Issue by raberana** [aspnet/Identity#790]
The error _**No authentication handler is configured to handle the scheme: Microsoft.AspNet.Identity.Application**_ shows up when I try to sign-in the user:

    public async Task<bool> SignIn(string email, string password)
    {
        var user = await this._userManager.FindByEmailAsync(email);
        if (user == null)
            return false;

        if (await this._userManager.CheckPasswordAsync(user, password))
        {
            await this._signInManager.SignInAsync(user, false); //error
            return true;
        }
        return false;
    }

My Startup.cs is shown below:

        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json")
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

            if (env.IsDevelopment())
            {
                builder.AddUserSecrets();
            }

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; set; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddTransient<RoleManager<IdentityRole>>();
            services.AddTransient<UserManager<ApplicationUser>>();
            services.AddTransient<SignInManager<ApplicationUser>>();

            // Add framework services.
            services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<DbContext>(options =>
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<DbContext>()
                .AddDefaultTokenProviders();

            services.AddMvc(config =>
            {
            #if !DEBUG
                config.Filters.Add(new RequireHttpsAttribute());
            #endif
            }).AddJsonOptions(opts =>
            {
                opts.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            }); ;

            services.AddSingleton<IAccountService, AccountService>();
            services.AddSingleton<IAgencyService, AgencyService>();
            services.AddSingleton<IFeatureService, FeatureService>();
            ....
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");

                try
                {
                    using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>()
                        .CreateScope())
                    {
                        serviceScope.ServiceProvider.GetService<DbContext>()
                             .Database.Migrate();
                    }
                }
                catch { }
            }

            app.UseIISPlatformHandler(options => options.AuthenticationDescriptions.Clear());

            app.UseStaticFiles();

            app.UseIdentity();

            app.UseMvc(routes =>
            {
                ... routes

            });

            SeedGenerator.Initialize(app.ApplicationServices);
        }

        public static void Main(string[] args) => WebApplication.Run<Startup>(args);
   
The stack trace is:
```
  at Microsoft.AspNet.Http.Authentication.Internal.DefaultAuthenticationManager.<SignInAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.SignInManager`1.<SignInAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

**Comment by HaoK** [comment]
Can you try removing your explicit transient registrations of the identity mangers, that might be the root source of your issues...AddIdentity does this for you, these should generally be Scoped to the request... was there a reason you wanted these to be transient?

```
 services.AddTransient<RoleManager<IdentityRole>>();
        services.AddTransient<UserManager<ApplicationUser>>();
        services.AddTransient<SignInManager<ApplicationUser>>();
```

**Comment by raberana** [comment]
None actually. I was just unaware of that. Thanks for that info.
So I tried to remove that but it still gives the same error.

**Comment by HaoK** [comment]
Put UseMVC before UseIdentity

**Comment by raberana** [comment]
Still not working :(

**Comment by eherrera** [comment]
Set ApplicationCookie.AutomaticAuthenticate to true:
`services.AddIdentity<MyIdentityUser, MyIdentityRole>(config =>`
               `                  {`
                        `config.Cookies.ApplicationCookie.AutomaticAuthenticate = true;`
                `}).AddEntityFrameworkStores<MyContext>()`
               ` .AddDefaultTokenProviders();`

**Comment by eherrera** [comment]
//Identity must be placed before UseMVC()
app.UseIdentity();
app.UseMvc();
 [https://stackoverflow.com/questions/38968422/no-authentication-handler-is-configured-to-handle-the-scheme](no-authentication-handler-is-configured-to-handle-the-scheme)
