### ISSUE TITLE
Identity cookie with claims to long

### ISSUE THREAD

**Issue by markusvt** [aspnet/Identity#791]
I am using Claims based Authorization in my application, with like 8 different claims. 
Over the last days I saw, that the cookie ```.AspNet.Microsoft.AspNet.Identity.Application=chunks:4```
is getting bigger and bigger. And now I get an exception ```Bad Request - Request Too Long``` every time i log in.
How can I manage it to shrink that cookie?

*Edit* I managed to find a bug in my application, so that the amount of claims a user had increased over time, so I ended up having 660 claims in my application, which produced that enormous header. 

But nevertheless: my question: is there an alternative to saving the claims as cookie?

**Comment by blowdart** [comment]
You could do a reference cookie, then use the claims transformation piece to rebuild your actual claims. Basically put the bare minimum you need to identity a user into the cookie and then use the hook as demonstrated in http://benfoster.io/blog/customising-claims-transformation-in-aspnet-core-identity
