### ISSUE TITLE
Why does HashPassword take in TUser as parameter?

### ISSUE THREAD

**Issue by henningst** [aspnet/Identity#793]
The HashPassword method in https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/PasswordHasher.cs takes in both TUser and plain text password as params, but the user param is never used. This seems to be something new that is added in the AspNetCore implementation. Why?

**Comment by HaoK** [comment]
This is so custom implementations can access things off of the user if they so desire as part of the hashing operation, for example if they wanted the salt to live on the user entity.  By default we don't use this behavior but it was requested to enable more advanced scenarios.

**Comment by akamud** [comment]
Shouldn't `IPasswordHasher<TUser>` have an overload without `TUser` then?

**Comment by HaoK** [comment]
Just ignore it if your hasher implementation doesn't care about the user instance.
