### ISSUE TITLE
Does Identity store the Users DB Primary Key in a cookie?

### ISSUE THREAD

**Issue by simonpbond** [aspnet/Identity#795]
I'm wondering if Identity stores the User's DB Primary Key as a claim and this get's passed in to the cookie?

I'm guessing this is how GetUserId() works as it seems to be getting the value from the principal.

I've read passing the primary key of a user in a cookie is bad security practice, so wondering if anyone can shed some light.

Thanks

**Comment by HaoK** [comment]
Yes, its stored as the ClaimsTypes.NameIdenfitier by default
