### ISSUE TITLE
Need to re-log for changing user claims to take effect

### ISSUE THREAD

**Issue by newsash** [aspnet/Identity#797]
After I add/remove claims to user using UserManager, they don't change on Controller.User until user re-log.

**Comment by brockallen** [comment]
Claims are cached in the cookie. You need to re-issue the cookie.

**Comment by newsash** [comment]
Issue resolved by `UserManager.UpdateSecurityStampAsync()` after changing claims and by `options.SecurityStampValidationInterval = Timespan.FromMinutes(1)` in Identity configuration.
