### ISSUE TITLE
Remove npm scripts from sample publish

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Identity#804]
We no longer use npm \ gulp in the sample. The `scripts` section should be removed since publishing would cause the app to fail.

**Comment by divega** [comment]
@pranavkm can this be closed then?

**Comment by pranavkm** [comment]
https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.Mvc/project.json#L63 needs to be deleted.

**Comment by divega** [comment]
@pranavkm RTM sounds good?

**Comment by pranavkm** [comment]
Yup.

**Comment by HaoK** [comment]
4c63935174395c74753093c876c9ce492889b061
