### ISSUE TITLE
Need Ability To Override Primary Key For UserClaim

### ISSUE THREAD

**Issue by mikeking27** [aspnet/Identity#805]
All other key datatypes for identity models can be overridden except UserClaim - it is hard coded as an 'int' - this can lead to a situation where the application database will end up with inconsistent primary key types.

**Comment by divega** [comment]
@HaoK will this be covered by the generics work?

**Comment by HaoK** [comment]
None of the child entities primary key types can currently be overridden only the primary key type for user and role.

**Comment by divega** [comment]
We are currently not planning to add the ability to customize the type of any child entity. If we hear enough feedback with justification of why it is important we can revisit.
