### ISSUE TITLE
2 databases

### ISSUE THREAD

**Issue by shima20** [aspnet/Identity#810]
@HaoK -  I have a separate database server that already has usernames and passwords stored and I would like to authenticate using that (there is already a webapi to call). But utilize the default identity server for the claims, roles. So technically there's 2 databases.  Is there any easy way to handle this scenario?  

I posed my question on openiddict as that's what I'm using for JWT and Kevin mentioned the below.

"Since OpenIddict simply relies on Identity's UserManager to validate the user credentials, I'd simply create my own UserManager, override the UserManager.VerifyPasswordAsync method and replace the default user manager by the custom one in the DI container.

Overriding the default user manager is a pretty common scenario in Identity and I'm pretty sure there's some documentation about that. You should ping the ASP.NET team and ask them to point you to the right direction."

**Comment by HaoK** [comment]
So if you just want to change how the password methods behave, you can just override UserManager and implement all of the Password methods to go against the other database, while leaving all the other methods alone which will use the default EF database. 

At a minimum you will probably need to override:
```
VerifyPasswordAsync
CheckPasswordAsync
HasPasswordAsync
```

**Comment by shima20** [comment]
@HaoK What would my Startup.cs have in it?  Currently, I had the below:

services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<FMGPortalContext>()
                .AddDefaultTokenProviders()
                .AddOpenIddictCore<Application>(config => config.UseEntityFramework());

**Comment by HaoK** [comment]
You can probably just add your custom user manager before the call to AddIdentity:

```
services.AddScoped<UserManager<ApplicationUser>>, YourCustomUserManager>()
```

**Comment by divega** [comment]
@haok don't we have a sugar extension method for that?

**Comment by HaoK** [comment]
Yeah there's also the `AddUserManager<TUserManager>()` that hangs off of IdentityBuilder which is what AddIdentity returns.

**Comment by shima20** [comment]
Do I also need to override SigninManager for the password as well?

**Comment by PinpointTownes** [comment]
@shima20 that shouldn't be needed for at least 2 reasons:
  - the default `SignInManager` ends up calling `UserManager` for all the password-related operations.
  - OpenIddict barely uses `SignInManager` because it has too many side effects and is basically tied to cookies (which is annoying, but that's another topic :smile:)

**Comment by HaoK** [comment]
Yeah SignInManager = UserManager + Cookie sugar APIs

**Comment by PinpointTownes** [comment]
@shima20 did you have a chance to confirm it worked for you?

**Comment by shima20** [comment]
@HaoK @PinpointTownes - I was able to override CheckPasswordAsync and got it working, however, after upgrading to the latest, it doesn't hit the overridden method anymore.  Do you know what could be wrong now or if there were any recent changes?

**Comment by HaoK** [comment]
You are calling CHeckPassword directly and its not being called?

**Comment by shima20** [comment]
I'm overriding UserManager and then implementing my own logic in CheckPasswordAsync

**Comment by HaoK** [comment]
Are you able to debug and confirm that you are getting the right instance?

**Comment by shima20** [comment]
The same way you had mentioned how to do it above.  The implementation for this didn't change any.  It just never gets called.

**Comment by PinpointTownes** [comment]
@shima20 make sure your manager inherits from `OpenIddictUserManager<TUser>` and is registered using `services.AddOpenIddict<...>().AddUserManager<CustomManager>()`.

**Comment by HaoK** [comment]
Closing, feel free to reopen if you are still having issues
