### ISSUE TITLE
Feature RequestUser attribute

### ISSUE THREAD

**Issue by Ciantic** [aspnet/Identity#813]
I've implemented a RequestUser attribute that can be used like this:

```C#
[Authorize]
[Route("[controller]")]
public class AccountController
{
	[HttpPost("[action]")]
	public dynamic LoggedIn([RequestUser] User loggedInUser)
	{
		return new 
		{
			Id = loggedInUser.Id,
			Email = loggedInUser.Email
		};
	}
}
```

Advantages for this attribute are multitude: You don't need to inherit from _Controller or ControllerBase_ anymore. You can use your POCO controller actions as is in websockets or other ways, because they are not dependent on HttpContext etc. Your actions becomes instantly more testable, since the user comes as argument.

I believe this attribute is so useful, that Identity or Mvc should provide it in the library.

Here is the implementation: https://gist.github.com/Ciantic/d1cd2f0680e50acd512b479872bb5e3b 

Also [available in my sample project](https://github.com/Ciantic/AspNetApiMonolithSample/blob/master/src/Api/Mvc/RequestUserAttribute.cs)

Thanks for considering.

**Comment by blowdart** [comment]
This would be an request for the MVC repo, rather than us. Really it's an app concern rather than the framework, as "User" is under your control. We believe that this would be better served as your own project and nuget package though.
