### ISSUE TITLE
Query: How we can create object of UserManager without using in built dependency injection ?

### ISSUE THREAD

**Issue by dotnetjalps** [aspnet/Identity#814]
Right with ASP.NET Core 1.0 there is only one way initialize the user manager class is to use the dependency injection. 

But in our application, We have created a custom user store for the multi-tenant application.  We need to use that UserStore class in UserManager class. So is there any way to create a new object with NEW keyword. I have tried lots of ways but not succeed as there are lots many arguments in the constructor and every time I am getting some error.

Please provide some guideline for this.

**Comment by MaximRouiller** [comment]
You don't want to "new" dependencies.

You put them as a dependency in your constructor:
```csharp
public class MyUserStore
{
    public MyUserStore(MyDependency dependency)
    {
        ...
    }
}
```

Then you add it to the `ConfigureServices` by overriding IUserStore

That's it really. Did I forget something?

**Comment by dotnetjalps** [comment]
I have already created code for user store. I need to use that user store in UserManger class.

```
public class ApplicationUserStore : UserStore<ApplicationUser>
    {
        public ApplicationUserStore(Rg2Context context)
          : base(context)
        {
        }

        public int TenantId{ get; set; }

        public override Task<ApplicationUser> FindByNameAsync(string userName, CancellationToken cancellationToken = new CancellationToken())
        {
            return this.GetUserAggregateAsync(u => u.UserName.ToUpper() == userName.ToUpper()
                  && TenantId== this.TenantId);
        }

        public override Task<ApplicationUser> FindByEmailAsync(string email, CancellationToken cancellationToken = new CancellationToken())
        {
            return this.GetUserAggregateAsync(u => u.Email.ToUpper() == email.ToUpper()
                   && u.TenantId == this.TenantId);
        }

        Task<ApplicationUser> GetUserAggregateAsync(Expression<Func<ApplicationUser, bool>> filter)
        {
            return Users.Include(u => u.Roles)
                .Include(u => u.Claims)
                .Include(u => u.Logins)
                .FirstOrDefaultAsync(filter);
        }
    }
```

**Comment by divega** [comment]
@dotnetjalps have you tried replacing the default store with your version by adding it to the service collection? E.g.

``` C#
services.AddScoped<IUserStore<ApplicationUser>, ApplicationUserStore>();
```

**Comment by dotnetjalps** [comment]
Sorry the late reply. its working fine thank you.

**Comment by gehbeez** [comment]
how did it work for you
