### ISSUE TITLE
Attempting to change user ID property from string to int hits troubles with EF migrations

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Identity#816]
If you go through the process of changing the `ApplicationUser` ID type to `int`, (e.g., https://github.com/aspnet/Identity/issues/780), then you will hit issues with EF migrations:

 * On SQLite, you'll get the exception "System.NotSupportedException: SQLite does not support this migration operation. For more information, see http://go.microsoft.com/fwlink/?LinkId=723262"

    The linked page explains that `AlterColumn` isn't supported on SQLite, but that instruction does appear in the generated migration script.

 * On SQL Server, you'll get errors including:

    The object 'PK_AspNetUsers' is dependent on column 'Id'.
    The object 'FK_AspNetUserRoles_AspNetUsers_UserId' is dependent on column 'Id'.
    The object 'FK_AspNetUserLogins_AspNetUsers_UserId' is dependent on column 'Id'.
    The object 'FK_AspNetUserClaims_AspNetUsers_UserId' is dependent on column 'Id'.
    ALTER TABLE ALTER COLUMN Id failed because one or more objects access this column.

I've no doubt it's possible to overcome these with more manual work, but [the most relevant docs we have on this subject](http://www.asp.net/identity/overview/extensibility/change-primary-key-for-users-in-aspnet-identity) aren't very enlightening - they just say *"If possible, just delete the existing database. ... If deletion is not possible, run code first migrations to change the tables."* but don't mention the migration issues.

**Comment by zigzag95** [comment]
They forget a string in here
public class UserStore : UserStore<IdentityUser<string>>

**Comment by danroth27** [comment]
@rowanmiller @divega

**Comment by rowanmiller** [comment]
Looks like there are two issues here:
* The Identity docs need to be updated to cover the fact that schema modifications are limited when targeting SQLite (due to limitations in the database engine itself).
* The second one - on SQL Server - looks like an issue in migrations itself (opened https://github.com/aspnet/EntityFramework/issues/5345 to track this)

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/issues/1210
