### ISSUE TITLE
On Windows, first use of Identity DB after app creation fails

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Identity#817]
Repro:

 * On Windows in VS, do a File->New ASP.NET Core Web Application project, and choose "Web Application" (not "Empty")
 * Launch it (Ctrl+F5)
 * Click on "Register" and then try to register a new user.
 * Get error: **A database operation failed while processing the request.**

![screen shot 2016-05-09 at 18 35 16](https://cloud.githubusercontent.com/assets/1101362/15121934/adb1d040-1614-11e6-9341-4332a2938eba.png)

If you click the button and try again, it does work OK. This occurs on Windows whether you're using SQL Server (LocalDB) or SQLite.

This error *does not* occur on OS X when using SQLite - the user registration completes successfully. Even if this is by design on Windows, it should at least be consistent with OS X.

**Comment by danroth27** [comment]
@barrytang @sayedihashimi @rowanmiller This isn't an identity issue. You need to run a migration to get the database created. Hence the big blue button.

Admittedly the current experience isn't great. In the past we created the database on first run, which had it's own issues. Ideas on how to improve this?

**Comment by danroth27** [comment]
Have we considered just creating the database on project creation?

**Comment by rowanmiller** [comment]
Yes, I think that is viable since it can be kicked of asynchronously. Obviously it would only help on the initial dev machine, but I think it's a good start.

**Comment by sayedihashimi** [comment]
What about command line users?

**Comment by rowanmiller** [comment]
Not sure about the infrastructure capabilities for creating the project from the command line, but we could still rely on the current "click the big blue button" experience. Or we could invoke `dotnet ef database update` as part of project creation (if possible).

**Comment by divega** [comment]
> This error does not occur on OS X when using SQLite - the user registration completes successfully. Even if this is by design on Windows, it should at least be consistent with OS X.

It this because the yo templates still include the workaround? If no, why?
