### ISSUE TITLE
2FA functionality gaps

### ISSUE THREAD

**Issue by rustd** [aspnet/Identity#818]
Copying from https://github.com/aspnet/Templates/issues/552
While the default templates 2FA setup is reasonably comprehensive, there are a couple of bits of functionality that you'd typically expect to see but aren't present here:
- **Recovery codes**
  
  Since the default template doesn't include any kind of "recovery codes" feature, it's quite a risk for a user to enable 2FA. If they lose access to their phone service, they lose their account too. (Actually, under the default setup, they could technically use "Email" as a second factor, but many sites are going to want to disable "Email" as a 2FA option).
- **Forget this browser**
  
  If you use "remember this browser" with 2FA, that's great, but there's no way to turn it off later. Many sites have something like "forget this browser" or "forget all other devices".

Neither of these are strictly essential for the template, but on most realistic sites you'd want them.

**Comment by blowdart** [comment]
Backlogging till post RTM

**Comment by HaoK** [comment]
Clearing backlog for visibility

**Comment by HaoK** [comment]
Rolled into https://github.com/aspnet/Identity/issues/1342
