### ISSUE TITLE
Add custom properties to usersroles 

### ISSUE THREAD

**Issue by zigzag95** [aspnet/Identity#819]
We would like add DateFrom and DateTo properties to usersroles gateway table and manage access using policies.
This was possible in 2.0 using userRole generic on context but not in 3.x

**Comment by blowdart** [comment]
@HaoK  is the user2roles table something we expect to be customizable?

**Comment by HaoK** [comment]
Should be addressed by https://github.com/aspnet/Identity/issues/585 which brings htings back to the 2.0 state of things more or less...
