### ISSUE TITLE
Package restore failed : AspNetCore.Identity  | AspNetCore.Identity.EntityFrameworkCore

### ISSUE THREAD

**Issue by kuashe** [aspnet/Identity#822]
After creating a new class library using .NET Core , adding a reference to 

- Microsoft.AspNetCore.Identity

Or 
- Microsoft.AspNetCore.Identity.EntityFrameworkCore

Result in the following errors 

![image](https://cloud.githubusercontent.com/assets/6097946/15338936/5456c5e0-1c82-11e6-8c68-b63c0d652b24.png)

How to make those packages work with .NET Core class library ?

**Comment by smitpatel** [comment]
You would need imports since those packages do not target netstandard tfm.
Can you try this
```
"netstandard1.3": { 
       "imports": [ 
         "portable-net452+win81" 
       ]
}
```

**Comment by kuashe** [comment]
@smitpatel  Set my netstand to 1.3 did not knew i needed those extra line in the imports . Thanks for this.

**Comment by smitpatel** [comment]
Such errors arise when the packages you are trying to use does not target the framework you are targeting in your app. But that does not mean that you cannot use those packages. If the target framework of the package is compatible with what you are targeting then you can put that framework in imports. Which tells dotnet that it can use packages which may not be targeting netstandard but any other tfm from the list of imports.
