### ISSUE TITLE
Site Cookie won't get created or modified resulting in strange behaviour

### ISSUE THREAD

**Issue by gray29** [aspnet/Identity#823]
1. For an external deployed site when I log in as user X, log out and log in as user Y, I get data belong to  user X showing and when I log out I get an error. (not resolved)

2. If I force delete my site cookie and refresh the app login page the cookie doesn't get created and I cannot log into the site at all. (Resolved)

When I access the same web site  on VPN I don't get the issue. I  only get this from external Url.

I wrote stackoverflow post here:
http://stackoverflow.com/questions/37297925/stange-cookie-behaviour-between-two-external-domain-sites-with-two-identical-asp

**Comment by blowdart** [comment]
What cached data are you seeing? What error are you seeing when you logout?

For point 2 the login page doesn't create any cookies until you actually login. A refresh doesn't do this.. What do you mean by you are unable to login? Are you seeing errors?

**Comment by gray29** [comment]
Its difficult as it is on production server that I'm not given access to from external url so I can't see errors. On dev server which is supposed to be duplicate of production I don't get the issue. 

Having a site work while I'm on a VPN but not when I'm on it is what I don't understand.

**Comment by blowdart** [comment]
We haven't seen such an issue either, we can't think of what would cause it. Logging out deletes the cookie entirely, logging in creates a complete new cookie. Is there a proxy in the way anywhere?

On production could you configure debug logs to a file to try to catch any exceptions?

Again when you say you can't login what do you mean? What happens? Is the login page there? Does the form submit? What happens if the form submits? Are there errors? 

There's nothing in our code that cares about IP addresses, so why it works on a VPN is a huge puzzle, unless you've customised login code, or have some sort of IP filtering or blocking in place.

**Comment by gray29** [comment]
What I don't understand is if I delete all cookies (tested on all desktop browser and mobile phone browser) and want to log in again, it doesn't allow me. The form posts to the server. the Result back is login failed. Running a database trace and nothing. The page refuses to create a new cookie. (On the VPN and working dev server over the internet  it does create cookie)

The signing in is the first step after the post

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
        {

          ViewData["ReturnUrl"] = returnUrl;
           if (ModelState.IsValid){
                 SignInResult result = await _signInManager.PasswordSignInAsync(model.Username, model.Password, false, lockoutOnFailure: false);

SignInResult  has no field to explain why it failed. Just Success Yes or No. No exception is thrown either.

If I restart the IIS worker process I can log in with the  again by immediately clicking the Login button without even refreshing the Login page.

I don't have any IP filtering or settings. I can't explain why it works on VPN but not over internet.
I have customized Identity to make use of Guids instead of the default string

      public class ApplicationUser : IdentityUser<Guid>

Apart from that my code is taken from  the default template.


Everything  works  on the VPN on production server, has the issues over internet. It behaves consistent when at office / or using 3G from my android phone with its mobile browser or my home ISP across all browsers. The VPN/ direct internet behavior is consistent across multiple devices and networks.
So it isn't a client browser proxy.

VPN over internet  works but internet direct  has the issue over the  same https url. A dev server with the same IIS version, Windows version and .net version and exact same site deployed does not have the issue over the internet

**Comment by gray29** [comment]
I also compare using fiddler between being on the VPN and not after deleting the cookie when logging in as the same user

On the VPN:
- ASP.Identity Cookie "MySiteCookie" is POSTed with the login.
- First Page after login GET contains the ASP.NET Identity Cookie "MySiteCookie"
-Response body of my first page after login is 7,705 bytes Chunked transfer encoding is used. GZIP

Not on the VPN:
- ASP.Identity Cookie is not POSTed with the login although it exists in the site lists of cookies.
 A unknown cookie name is posted instead with a name of Nue9LI0c0tY
- First Page after login GET contains the ASP.NET Identity Cookie "MySiteCookie"
-Response body of my first page after login is 7,705 bytes, Response Body is 34494 bytes. Not chunked. not HTTP compressed

**Comment by blowdart** [comment]
Can you try enabling debug logging within the app? @HaoK any more ideas? This is pretty bizarre.

**Comment by gray29** [comment]
Regarding the production server treating cookies differently direct on the internet I cannot explain. One difference I picked up in fiddler is that when on the VPN or to the dev server the content gets encoded/zipped but not to production via the internet. Not sure why IIS behaves this way or if it is related to the problem

Regarding the strange behavior when not on the VPN
It is basically is two issues. The one issue of when deleting the cookie a new cookie doesn't get created. I found the the reason for this was the Identity cookie being in  conflict with `Microsoft. AspNet Session`

I  found an answer googling [here](http://stackoverflow.com/questions/29906611/asp-net-identity-stops-handing-out-external-cookie-after-removing-external-accou?lq=1). Setting a dummy session value before login  worked somewhat but I decided to remove using sessions and `Microsoft. AspNet Session` from my application to eliminate any other conflicts. So I'm not experiencing this when.




The 2nd issue of logging with user X, logging out, log in with user Y and getting user X details still always occurs on VPN. I suspect the cookie isn't updated or something gets cached.
 
The errors I get sometime User.IsAuthenticated= false and User.GetUserId() .is null
and

    await _signInManager.SignOutAsync(); 
can throw error.

To not get errors I commented out the Authorize attribute and put the code in a conditional if

    if (User.Identity.IsAuthenticated) { await _signInManager.SignOutAsync(); }

The issue I get seems to be getting the wrong User.GetUserId. The errors I don't often get it is only sometimes when User.GetUserId() becomes null and as a result  my code failing because it is unexpected

The only [similar issue ](http://stackoverflow.com/questions/33463706/asp-net-5-mvc6-user-getuserid-returns-incorrect-id )I could find googling solution is to she cookie validateInterval to 0 however that property doesn't exist anymore from what I could find in Identity 3 RC1

**Comment by HaoK** [comment]
Why is the identity cookie in conflict with the session cookie?  As a first step, can you revert any changes you have to the cookie properties in general, the defaults should be fine in general, and would be a good thing to remove as possible causes of any weirdness you are seeing.

**Comment by gray29** [comment]
I can only conclude the issue is to do with caching. This might explain why over VPN I don't get the issue. There must be a server caching https server traffic.

I log in as user X. Access some page. Then log out. 
Log in as user Y. then all the pages that user X accessed previously shows user X details instead of user Y.

 If I access a page that user X hasn't accessed  it will show user Y's page. Errors a get is because the cached page contains user X's details but the server know I am logged in a user Y.
For example when I log out. Because the page thinks I am user X but the server thinks I am user Y I get a subsequent error

**Comment by gray29** [comment]
closed as proxy/cache related
