### ISSUE TITLE
Integration with ClaimsPrincipal

### ISSUE THREAD

**Issue by kdelorey** [aspnet/Identity#826]
I've notice a change in behavior from RC1 (Identity 3.0.0-rc1-final) to RC2 (Identity Core 1.0.0-rc2-final) in regards to the integration with the `ClaimsPrincipal` typically accessed through the the `ControllerBase`. Simply the claims don't appear. So invoking `User.HasClaim( string, string )` on a valid claim will always yield `false`.

Reading the [rc1 to rc2 migration instructions](https://docs.asp.net/en/latest/migration/rc1-to-rc2.html) explains the removal of the helper extensions in favor of using the managers directly for information, but nothing about validating claims for the context user, so I would assume the behavior would remain the same.

My ultimate problem is that I depend on the `IServiceCollection.AddAuthorization` policy builder to create policies using the `AuthorizationPolicyBuilder.RequireClaim( string, params string[] )` method. With some experimentation I've noticed that `RequireRole( param string[] )` also fails.

Did I possibly miss something?

**Comment by HaoK** [comment]
Can you include more details about what you are doing and expecting, the removal of the helpers shouldn't have changed anything on your actual ClaimsPrincipal, but that said, its possible some other changes affect what the data actually is as well...

**Comment by kdelorey** [comment]
@HaoK I was writing a large overview of what I was trying to do and what the result was and I stumbled upon my problem. Sometimes you just have to talk these things out. I apologize for the inconvenience. It is a slight difference in behavior from RC1 to RC2, but I believe it is a mistake from my ported code and RC2 has the appropriate behavior.

Basically I was creating a default account in a role:
```C#
await mUserManager.CreateAsync( account, "Admin1" );
await mUserManager.AddToRoleAsync( account, UserRole.AdministratorName );
```

..but when I was finished creating the role, I forgot to update:
```C#
await mUserManager.UpdateAsync( account );
```

Thanks for your support regardless.
