### ISSUE TITLE
UserManager - add next functionality

### ISSUE THREAD

**Issue by miroslavsiska** [aspnet/Identity#831]
Hi.
I need for "SuperUser" ability to change password of any user in identity system. 
I need add this to  existing UserManager:
   public virtual async Task<IdentityResult> ChangePasswordAsync(TenantUser user, string newPassword)
(No Token parameter as parameter...)

I'm finished with CustomUserManager like this:

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.Entity;
using Program.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using Microsoft.Extensions.OptionsModel;
using Microsoft.AspNet.Http;
using Microsoft.Extensions.Logging;
using System.Text;
using Microsoft.Extensions.DependencyInjection;

namespace Program.Models
{

    public class TenantUserManager<TenantUser> : UserManager<TenantUser>, IDisposable where TenantUser : class
    {
        // protected const string ResetPasswordTokenPurpose = "ResetPassword";
        //  protected const string ConfirmEmailTokenPurpose = "EmailConfirmation";

        private TimeSpan _defaultLockout = TimeSpan.Zero;
        private bool _disposed;
        private readonly HttpContext _context;
        private CancellationToken CancellationToken => _context?.RequestAborted ?? CancellationToken.None;

        /// <summary>
        /// Constructs a new instance of <see cref="UserManager{TenantUser}"/>.
        /// </summary> 
        /// <param name="store">The persistence store the manager will operate over.</param> 
        /// <param name="optionsAccessor">The accessor used to access the <see cref="IdentityOptions"/>.</param> 
        /// <param name="userValidators">A collection of <see cref="IUserValidator{TenantUser}"/> to validate users against.</param> 
        /// <param name="passwordValidators">A collection of <see cref="IPasswordValidator{TenantUser}"/> to validate passwords against.</param> 
        /// <param name="keyNormalizer">The <see cref="ILookupNormalizer"/> to use when generating index keys for users.</param> 
        /// <param name="errors">The <see cref="IdentityErrorDescriber"/> used to provider error messages.</param> 
        /// <param name="services">The <see cref="IServiceProvider"/> used to resolve services.</param> 
        public TenantUserManager(IUserStore<TenantUser> store, IOptions<IdentityOptions> optionsAccessor,
        IPasswordHasher<TenantUser> passwordHasher, IEnumerable<IUserValidator<TenantUser>> userValidators,
        IEnumerable<IPasswordValidator<TenantUser>> passwordValidators, ILookupNormalizer keyNormalizer,
        IdentityErrorDescriber errors, IServiceProvider services, ILogger<UserManager<TenantUser>> logger, IHttpContextAccessor contextAccessor)
        : base(store, optionsAccessor, passwordHasher, userValidators, passwordValidators, keyNormalizer, errors, services, logger, contextAccessor)
        {
          
            if (store == null)
            {
                throw new ArgumentNullException(nameof(store));
            }
            Store = store;
            Options = optionsAccessor?.Value ?? new IdentityOptions();
            PasswordHasher = passwordHasher;
            KeyNormalizer = keyNormalizer;
            ErrorDescriber = errors;
            Logger = logger;

            if (userValidators != null)
            {
                foreach (var v in userValidators)
                {
                    UserValidators.Add(v);
                }
            }
            if (passwordValidators != null)
            {
                foreach (var v in passwordValidators)
                {
                    PasswordValidators.Add(v);
                }
            }

            // IUserTwoFactorTokenProvider is not accessible
            /*
            if (services != null)
            {

                _context = services.GetService<IHttpContextAccessor>()?.HttpContext;
                foreach (var providerName in Options.Tokens.ProviderMap.Keys)
                {
                    var provider = services.GetRequiredService(Options.Tokens.ProviderMap[providerName].ProviderType) as IUserTwoFactorTokenProvider<TenantUser>; //HERE SOLVE
                    if (provider != null)
                    {
                        RegisterTokenProvider(providerName, provider);
                    }
                }

            }
            */

        }
        /// <summary>
        /// Gets or sets the persistence store the manager operates over.
        /// </summary>
        /// <value>The persistence store the manager operates over.</value>
     //   protected internal IUserStore<TenantUser> Store { get; set; }

        /// <summary>
        /// Gets the <see cref="ILogger"/> used to log messages from the manager.
        /// </summary>
        /// <value>
        /// The <see cref="ILogger"/> used to log messages from the manager.
        /// </value>
     //   protected internal virtual ILogger Logger { get; set; }

        internal IPasswordHasher<TenantUser> PasswordHasher { get; set; }

        internal IList<IUserValidator<TenantUser>> UserValidators { get; } = new List<IUserValidator<TenantUser>>();

        internal IList<IPasswordValidator<TenantUser>> PasswordValidators { get; } = new List<IPasswordValidator<TenantUser>>();

        internal ILookupNormalizer KeyNormalizer { get; set; }

        internal IdentityErrorDescriber ErrorDescriber { get; set; }

        internal IdentityOptions Options { get; set; }

        public virtual async Task<IdentityResult> ChangePasswordAsync(TenantUser user, string newPassword)
        {
            ThrowIfDisposed();
            var passwordStore = GetPasswordStore();
            if (user == null)
            {
                throw new ArgumentNullException(nameof(user));
            }
            var result = await UpdatePasswordHash(passwordStore, user, newPassword);
            if (!result.Succeeded)
            {
                return result;
            }

            try
            {
                return await UpdateUserAsync(user);
            }
            catch
            {
                Logger.LogWarning(2, "Change password failed for user {userId}.", await GetUserIdAsync(user));
                return IdentityResult.Failed(ErrorDescriber.PasswordMismatch());    
            }
        }

        private static string NewSecurityStamp()
        {
            return Guid.NewGuid().ToString();
        }

        private IUserSecurityStampStore<TenantUser> GetSecurityStore()
        {
            var cast = Store as IUserSecurityStampStore<TenantUser>;
            if (cast == null)
            {
                throw new NotSupportedException("No security user store is available.");
            }
            return cast;
        }

        internal async Task UpdateSecurityStampInternal(TenantUser user)
        {
            if (SupportsUserSecurityStamp)
            {
                await GetSecurityStore().SetSecurityStampAsync(user, NewSecurityStamp(), CancellationToken);
            }
        }

        internal async Task<IdentityResult> UpdatePasswordHash(IUserPasswordStore<TenantUser> passwordStore,
           TenantUser user, string newPassword, bool validatePassword = true)
        {
            if (validatePassword)
            {
                var validate = await ValidatePasswordInternal(user, newPassword);
                if (!validate.Succeeded)
                {
                    return validate;
                }
            }
            var hash = newPassword != null ? PasswordHasher.HashPassword(user, newPassword) : null;
            await passwordStore.SetPasswordHashAsync(user, hash, CancellationToken);
            await UpdateSecurityStampInternal(user);
            return IdentityResult.Success;
        }

        private async Task<IdentityResult> ValidateUserInternal(TenantUser user)
        {
            var errors = new List<IdentityError>();
            foreach (var v in UserValidators)
            {
                var result = await v.ValidateAsync(this, user);
                if (!result.Succeeded)
                {
                    errors.AddRange(result.Errors);
                }
            }
            if (errors.Count > 0)
            {
                Logger.LogWarning(13, "User {userId} validation failed: {errors}.", await GetUserIdAsync(user), string.Join(";", errors.Select(e => e.Code)));
                return IdentityResult.Failed(errors.ToArray());
            }
            return IdentityResult.Success;
        }

        private async Task<IdentityResult> ValidatePasswordInternal(TenantUser user, string password)
        {
            var errors = new List<IdentityError>();
            foreach (var v in PasswordValidators)
            {
                var result = await v.ValidateAsync(this, user, password);
                if (!result.Succeeded)
                {
                    errors.AddRange(result.Errors);
                }
            }
            if (errors.Count > 0)
            {
                Logger.LogWarning(14, "User {userId} password validation failed: {errors}.", await GetUserIdAsync(user), string.Join(";", errors.Select(e => e.Code)));
                return IdentityResult.Failed(errors.ToArray());
            }
            return IdentityResult.Success;
        }

        private async Task<IdentityResult> UpdateUserAsync(TenantUser user)
        {
            var result = await ValidateUserInternal(user);
            if (!result.Succeeded)
            {
                return result;
            }
            await UpdateNormalizedUserNameAsync(user);
            await UpdateNormalizedEmailAsync(user);
            return await Store.UpdateAsync(user, CancellationToken);
        }
        private IUserPasswordStore<TenantUser> GetPasswordStore()
        {
            var cast = Store as IUserPasswordStore<TenantUser>;
            if (cast == null)
            {
                throw new NotSupportedException("User store is not available."); //Resources are not awailable
            }
            return cast;
        }

        /// <summary> 
        /// Releases the unmanaged resources used by the role manager and optionally releases the managed resources. 
        /// <param name="disposing">true to release both managed and unmanaged resources; false to release only unmanaged resources.</param> 
        protected override void Dispose(bool disposing)
        {
            if (disposing && !_disposed)
            {
                Store.Dispose();
                _disposed = true;
            }
        }

        protected void ThrowIfDisposed()
        {
            if (_disposed)
            {
                throw new ObjectDisposedException(GetType().Name);
            }
        }

    }

}

Exist some better way or is this solution correct?

**Comment by blowdart** [comment]
Given a user, you retrieve from the store, you could generate the password hash, using the password hasher, set the password field in the user class, and then update it via the user store.
