### ISSUE TITLE
Sort out how to publish the Microsoft.AspNet.Identity.AspNetCoreCompat package

### ISSUE THREAD

**Issue by divega** [aspnet/Identity#833]
This package contains code that should useful customers share a database and identities between an application based on ASP.NET Identity 2.x and an application based on ASP.NET Core Identity 1.0. 

We want to publish it as a supplement to a step-by-step guide on how to do that, but it isn't clear we should make it part of any supported product. 

This issue is to sort out how we go about publishing this package, e.g. should it go to NuGet, how we name it and versioning, should we put it in its own repo, etc.

**Comment by HaoK** [comment]
ed1d8cfbd001676c7b187881934d207577cf8a24

Shipping as 0.1 version with AspNetCoreCompat name

**Comment by PaulDeac** [comment]
> We want to publish it as a supplement to a step-by-step guide on how to do that, but it isn't clear we should make it part of any supported product.

Hi, is there any guide online on how to use this package ? I'm migrating an MVC 5 (with EF 6) web application to .net core. I've decided not to migrate to entity framework core yet, so i've created a class library project which holds the EF 6 db context and migrations, and referenced that in the main .net core web application. All shine and rozy, but i'm facing problems now migrating the identity. Been thinking this package would help me out.

If i'm not mistaken it's not possible to keep using the old membership (Microsoft.AspNet.Identity.Core v2.2.1) in a .Net Core project, and the idea is to migrate to Microsoft.AspNetCore.Identity, but i want to keep using Entity Framework 6. 

Thanks.

**Comment by HaoK** [comment]
If you want to use EF6 with identity core, you will just need to implement the identity core interfaces using EF6, you might be able to reuse most of the store code in the Identity.EntityFrameworkCore package.  The compat package is intended to let you use the old 2.2 schema, with the new EF Core provider.

**Comment by PaulDeac** [comment]
Thanks. @HaoK 

I'll try that.

**Comment by simeyla** [comment]
@HaoK is there a guide for this anywhere though? I can probably 'wing it' but this is the kind of thing where a small nuance is going to kill me - and my website if I make a wrong assumption.
