### ISSUE TITLE
Asynchronize call does not use the same account

### ISSUE THREAD

**Issue by chinadragon0515** [aspnet/Identity#835]
We have a customer who build a Web Api application, it will use Windows authentication, and in this application, it will have some aynchronized call to the database via entity framework.  We find the windows credential used to access Web Api application is not passed to DB call, and DB call uses a different app pool account.

For the configuration,
1. IIS has enabled windows authentication.
2. in project, web.config, there is configuration "< identity impersonate="true"/>"
3. For DB connection "Integrated Security=SSPI" and "Integrated Security=true" are tried.

Customers did lots of search, find this link can resolve the issue, https://blogs.msdn.microsoft.com/tom/2008/04/22/making-an-asynchronous-call-using-the-impersonation-identity/

Then question is whether this issue is fixed or not? Is the solution in this link still valid? Any new solutions recommended? thanks

If this is not right project for this issue, can you help me to know the right project?

**Comment by blowdart** [comment]
The link you have is for the previous versions of .NET Core.

Are you using .NET Core?

**Comment by chinadragon0515** [comment]
No, we are not use .NET core.
This is from our package.config file,
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net45" />

**Comment by blowdart** [comment]
This github repo is for ASP.NET Core I'm afraid. I'd suggest asking on StackOverflow, and one of the team will pick it up.

**Comment by chinadragon0515** [comment]
stackoverflow question is http://stackoverflow.com/questions/37604029/webapi-project-entity-framework-asynchronize-call-does-not-use-the-same-account
