### ISSUE TITLE
Consider protecting tokens in IUserAuthenticationTokenStore

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#836]
Since this seems geared for storing user's access tokens back to whatever external IdP, and given that you have no idea what scope those access tokens might provide access to, storing the values in plain text in the store seems a bit open. Sure, perhaps most of these tokens will be for something like a user info endpoint, but even that is indirectly PII you might be leaking if the DB is compromised. 

Seems like a perfect use of a decorator (only if the DI system allowed named instances/decorators).

Anyway, just interested in a conversation and awareness about this.

**Comment by HaoK** [comment]
Related https://github.com/aspnet/Identity/issues/516

**Comment by blowdart** [comment]
We should look at a token protection service for this sort of thing, which could in turn apply to other pieces like username or email, but we wouldn't provide an implementation by default, because who would know where to keep keys.

I'm thinking Protect/Unprotect as the verbage.

**Comment by brockallen** [comment]
So I'll remind you guys about this issue, now that I notice in ASP.NET Identity 2 that the authenticator TOTP key and recovery codes are being kept in this table as plaintext. Not ideal.

**Comment by HaoK** [comment]
Yeah this is on our list, and be part of the GPDR work which needs encryption as well

**Comment by HaoK** [comment]
Tracking as part of https://github.com/aspnet/Identity/issues/836
