### ISSUE TITLE
GenerateEmailConfirmationTokenAsync does not use current email value to verify

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#837]
GenerateEmailConfirmationTokenAsync does not use the current email in any way for verification. If the email is changed in between the time the token is generated to the time it's confirmed then the confirmation would really be incorrect/invalid and for the wrong email.

I'd have to spend some more time thinking about this to suggest an attack, but regardless it seems very easy to shore this up by loading the current email and include that in the purpose much like GenerateChangeEmailTokenAsync does.

It's also interesting that there's no equivalent GeneratePhoneNumberConfirmationTokenAsync.

**Comment by blowdart** [comment]
@HaoK can you try this? The security stamp might change when emails or usernames change, in which case all previous tokens should be invalidated.

**Comment by HaoK** [comment]
So I verified that if the email is changed via SetEmail after the token is generated, it is invalidated as you expect, the token is using the security stamp for its secret, so anything that affects the stamp (changing password, user name, email etc, would invalidate the token), hence I don't think we need the old email in the payload as its already taken into account by the stamp

**Comment by HaoK** [comment]
See 119eb3fa684dca448ee9156dd7981b1445a15aa0
