### ISSUE TITLE
NotifyAsync left over from AspId2?

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#839]
Is this supposed to still be in there in v3?

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/DataProtectionTokenProvider.cs#L172

**Comment by HaoK** [comment]
Yeah looks like dead code, thanks!

**Comment by HaoK** [comment]
@divega @blowdart easy fix to slam in?

**Comment by blowdart** [comment]
Sure go for it.
