### ISSUE TITLE
Applying Polices (Authorize), problem with NormalizedName

### ISSUE THREAD

**Issue by casertano** [aspnet/Identity#847]
In our application with ASP.NET Core RC1, we have a problem applying Polices (Authorize) with Claims. The NormalizedName have to be exactly the same as Name (in AspNetRoles table).
That is:
Name = **Test A** and NormalizedName = **TEST_A** => _Is not recognized in the Police_;
Name = **Test A** and NormalizedName = **TEST A** => _It is recognized in Police_;

**Comment by blowdart** [comment]
Can you describe what you're trying to do? Please include your policy code & authz configuration, and the roles you're trying to validate.

**Comment by casertano** [comment]
@blowdart here's a simple example that used to validate the problem.

Follows the model applied in Startup.cs:

`services.AddAuthorization(options =>
            {
options.AddPolicy("PROJECT_INSERT", policy => policy.RequireClaim("PROJECT", "INSERT"));
options.AddPolicy("PROJECT_VIEW", policy => policy.RequireClaim("PROJECT", "VIEW"));
options.AddPolicy("PROJECT_UPDATE", policy => policy.RequireClaim("PROJECT", "UPDATE"));
options.AddPolicy("PROJECT_DELETE", policy => policy.RequireClaim("PROJECT", "DELETE"));
            });`

The application to the Controller, for example:

 `[Authorize("PROJECT_VIEW")]
  public IActionResult Index()
  {
        return View(model);
  }`

Relationships in the database:

AspNetRole (Is not recognized in the Police):

**Id:** 0be5574b-e86f-4a41-b944-34495bcd05b6
**ComcurrencyStamp:** A0EA7225-C235-43FE-83DA-7399720252A1
**Name:** Project Manager
**NormalizedName:** _PROJECT_MANAGER_

AspNetRoleClaims:

**Id:** 4333
**ClaimType:** PROJECT
**ClaimValue:** VIEW
**RoleId:** 0be5574b-e86f-4a41-b944-34495bcd05b6


Related to **Role** with the **User**, it does not authorize the **Controller** above, but if you change the **NormalizedName** for **PROJECT MANAGER** (no underscore), works.

Tks,

**Comment by blowdart** [comment]
So this almost looks like the claims for a role aren't populating?

@HaoK

**Comment by HaoK** [comment]
Why are normalized name and name different with regards to _?  By default the normalization we expect is only a ToUpperInvariant(), the _ does indeed mean a different role unless you are customizing the normalization service identity uses.

**Comment by HaoK** [comment]
You shouldn't be setting the normalized names at all, identity uses those to persist the results from the ILookupNormalizer service:

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/ILookupNormalizer.cs

**Comment by angelobelchior8** [comment]
@Haok If the field "Name Normalized" should be the "Name" field in uppercase format, for which reason we can set a value for it?

**Comment by HaoK** [comment]
EntityFramework works against POCOs, there are lots of fields that if you set to unexpected values, things will break.  PasswordHash is a good example of another field that you shouldn't set manually for example.  You are free to set the normalized name to something, but you need to set the service instanced used to respect that value as well.
