### ISSUE TITLE
Add IdentityBuilder API for registering IUserClaimsPrincipalFactory

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#849]
IUserClaimsPrincipalFactory is a pretty crucial extensibility point in AspNet Identity (e.g. mapping custom properties on the user to claims in the cookie), but there's no visible API on IdentityBuilder for it.

**Comment by HaoK** [comment]
27f021ab933a153eb977318e844a74f8497e3b47

**Comment by brockallen** [comment]
thx
