### ISSUE TITLE
SignInManager:ExternalLoginSignInAsync needs flag to bypass 2fa

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#850]
Currently if a user's account in ASP.NET Identity is configured to require 2fa it's required for both password and external authentication. Often the external provider already does the 2fa. There should be a param on the ExternalLoginSignInAsync to bypass the 2fa step, but still keep the other checks (primarily the call to PreSignInCheck).

**Comment by HaoK** [comment]
fa976e7765db498b7587d4028da76f533d1590ff
