### ISSUE TITLE
is it not possible to replace the old claimsprincipal extensions?

### ISSUE THREAD

**Issue by joeaudette** [aspnet/Identity#857]
This breaking change announcement for rc2 removed some useful ClaimsPrincipal extensions
https://github.com/aspnet/Announcements/issues/140

which resulted in the need to inject both UserManager and SignInManager into _LoginPartial.cshtml in the latest project templates.

That seems kind of ugly to me. Is it not possible to make new extension methods that do respect the configuration options somehow instead of just removing them?

**Comment by brentdavid2008** [comment]
+1 on this, i use User.GetUserId() in a lot of partial views, seems silly to have to give the view the entire UserManager

**Comment by HaoK** [comment]
The claim types are configurable via IdentityOptions so there was no clean way to make static extension methods support this, so we moved them to the identity specific managers.
