### ISSUE TITLE
Return JSON message when policy requirement fails

### ISSUE THREAD

**Issue by levitatejay** [aspnet/Identity#858]
It seems both the cookie and token middleware are overwriting the response I'm setting in my requirement handler. Here is the code that sets the response in my requirement handler:

```
//if we don't have permission then:
var mvcContext = context.Resource as Microsoft.AspNetCore.Mvc.Filters.AuthorizationFilterContext;

                if (mvcContext != null)
                {
                    var response = new { Message = "You don't have permission to access this" }
                    mvcContext.Result = new JsonErrorResult(403, response);
                }
```

When the response comes through there is no JSON in the body.

I've seen that using requirements and handlers is the suggested way to do authorization but how can I return a custom message to the client along with the 403 status code?

**Comment by HaoK** [comment]
The security repo issue can track this, not an issue for identity.
