### ISSUE TITLE
AspNetUserLogins.ProviderDisplayName always null

### ISSUE THREAD

**Issue by madmunsterdaddy** [aspnet/Identity#862]
This field never gets populated when logging in with any provider. Is it supposed to?

**Comment by HaoK** [comment]
Did you set it in your app when adding the login, i.e.

`await manager.AddLoginAsync(user, new UserLoginInfo(provider, providerKey, displayName)`

**Comment by madmunsterdaddy** [comment]
Was just using default template ;) That should probably be added.

Even so, in LinkLoginCallback, ExternalLoginInfo.ProviderDisplayName is null so if you want this you have to use something like:

await _userManager.AddLoginAsync(user, new UserLoginInfo(info.LoginProvider, info.ProviderKey, **info.LoginProvider**));

**Comment by HaoK** [comment]
For the default templates this is fine because we are using the default names for the providers.  This field is mostly there for the app to use if desired.
