### ISSUE TITLE
[template] ResetPassword is using FindByNameAsync, not FindByEmailAsync

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#865]
The template is using the wrong API to find the account for password resets. It should be based on email, not the username. This makes it easier for people who use the template and don't use email for the username.

**Comment by HaoK** [comment]
Well email doesn't have to be unique which is why we went with username originally.

**Comment by brockallen** [comment]
And how do people get their username emailed to them if they forget the username?

Is there a flag to make email unique? IIRC I saw one...

**Comment by HaoK** [comment]
Yeah there's a flag on User options to require it to be unique. You could send them all their usernames for the email I guess.

**Comment by HaoK** [comment]
@blowdart anything to be done here?  Our templates currently use email as the user name, so the apis are as such.  UserName is our login key in identity.  Email is not necessarily unique from Identity's perspective so we don't use it in any of the login apis.

**Comment by blowdart** [comment]
I think Brock's right here. I often forget what my damned username is, and so end up asking for it by email. So a username recovery page would be a good enhancement come v.next

**Comment by HaoK** [comment]
You should close this and create a new issue in templates, I don't think there's any identity APIs missing preventing this today.

**Comment by brockallen** [comment]
Done.

**Comment by Ponant** [comment]
@blowdart 

> I often forget what my damned username

Younger generations in public facing websites remember username or phone.
