### ISSUE TITLE
cannot access a disposed object UserManager in asp.net mvc core

### ISSUE THREAD

**Issue by onedevteam** [aspnet/Identity#867]
I have following code in my service that should create UserManager instance

    public class SubscriptionService : ISubscriptionService
    {

        private UserManager<ApplicationUser> userManager;
        public UserManager<ApplicationUser> UserManager
        {
            get
            {
                return userManager;  

            }
            private set { userManager = value; }
        }

        public SubscriptionService(
            UserManager<ApplicationUser> userManager,   
            StripeCustomerService customerService, 
            StripeSubscriptionService subscriptionService)
        {
            this.userManager = userManager;
            this.customerService = customerService;
            this.subscriptionService = subscriptionService;
        }

        public SubscriptionService(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }

When userManager is called first time inside class, it works but second call returns an error "`cannot access a disposed object UserManager`"

I'm consuming SubscriptionService class in my controller with: 

    public ISubscriptionService SubscriptionService
    {
        get
        {
            return subscriptionService ?? new SubscriptionService(_userManager);
        }
        private set
        {
            subscriptionService = value;
        }
    }

and service is called with 

`SubscriptionService.Create(HttpContext.User.Identity.Name, model.Plan, model.StripeToken); //this is function that calls userManager and throws an exception`

Can someone point me where i'm wrong with this and how to fix it?

I'm using ASP.NET Core 1.0

**Comment by HaoK** [comment]
How are you registering your SubscriptionService, is its lifetime scoped?  The usermanager will be disposed after each request, so that is most likely what's causing the error.

**Comment by onedevteam** [comment]
SubscriptionService is registered in Startup.ConfigureServices with 

            services.AddTransient<ISubscriptionService, SubscriptionService>();

**Comment by dallancarr** [comment]
Interesting your instatiating the service  potentially inside the controller. Why do that?

**Comment by onedevteam** [comment]
@dallancarr If i don't reference service, when i try to call it i get compile error `An object reference is required for the non-static field, method, or property 'SubscriptionService.Create(string, Plan, string)'	`

**Comment by onedevteam** [comment]
Update: i have replaced  in my Startup.ConfigureServices()

`        services.AddTransient<ISubscriptionService, SubscriptionService>();
`

with 

`        services.AddSingleton<ISubscriptionService, SubscriptionService>();
`

and app worked as it should be.

**Comment by dallancarr** [comment]
Yes that would work but not ideal. How are you  constructing the controller?

**Comment by onedevteam** [comment]
Controller constructor: 

```
        private IPlanService planService;
        private ISubscriptionService subscriptionService;
        private UserManager<ApplicationUser> _userManager;

        public SubscriptionController(IPlanService planService, 
                                        ISubscriptionService subscriptionService, 
                                        UserManager<ApplicationUser> userManager)
        {
            this._userManager = userManager;
            this.planService = planService;
            this.subscriptionService = subscriptionService;
        }
```

**Comment by dallancarr** [comment]
The newing code should be removed and let DI deal with the lifetime. There some scoped dependencies inside the manager which your hand a little.

**Comment by dallancarr** [comment]
Also no need to inject the manager in the controller if you constructing it as part of the service. But that is down to your implementation.
