### ISSUE TITLE
XML comment for IdentityUser.Id property is messed up

### ISSUE THREAD

**Issue by xperiandri** [aspnet/Identity#869]
[See](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityUser.cs#L71)

**Comment by MaximRouiller** [comment]
*Misaligned*.

**Comment by blowdart** [comment]
@HaoK - missed :) Can you adjust?

**Comment by xperiandri** [comment]
Also incorrect comment at https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityUserClaim.cs#L21

**Comment by xperiandri** [comment]
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/UserStore.cs#L54
`a user and a role`

**Comment by HaoK** [comment]
7b3b3627957404fe9083268929dd5589f7a26d1b

**Comment by xperiandri** [comment]
I'm just looking at the comments to make [OpenIddict](https://github.com/openiddict/openiddict-core/) comments having the same style.

**Comment by xperiandri** [comment]
The style of description is inconsistent for
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityDbContext.cs#L51-L53
and
https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/UserStore.cs#L105-L112

Which one will be agreed for entity type description?
1. The type of `entity` object**s**.
2. The type representing **a** `entity`.

And for primary key
1. The type of the primary key for `entity`**es**`1` and `entity`**es**`2`>.
2. The type of the primary key for **a** `entity`.
