### ISSUE TITLE
by default, string as primary key type for the user entity !!!

### ISSUE THREAD

**Issue by ikourfaln** [aspnet/Identity#874]
Hi,
We see that, by default, you use string as primary key type for the user entity !! 
And we all know that int is more efficient than string. But we believe that there is a reason why you choose string. So please can you explain why ?! are we missing something.

We want start a new project from scratch, and our team said that int as key type is more efficient because in our model, User entity is in relation with almost all other entities.

**Comment by ikourfaln** [comment]
so ?? anyone

**Comment by kroniak** [comment]
@ikourfaln Use int as you wish. As for me It can be little smaller for storage for many users. It's all. But remember about high value of int.

**Comment by ikourfaln** [comment]
@kroniak thanx for the reply, but what do you mean by "high value of int" ?
I'm just wondering why ASP.NET Identity team chose string as default primary key type !! And if there is no problem with string type I will keep it without overriding the implementation of the framework.
I'm just looking for a decision.

**Comment by kroniak** [comment]
@ikourfaln http://www.c-sharpcorner.com/UploadFile/rohatash/maximum-limit-value-for-integer-data-type-in-sql-server-2012/

**Comment by ikourfaln** [comment]
@kroniak !! I don't understand what is the relation between the maximum range of numeric data and our subject, I already know this article talking about. Do you mean that the default string as primary key (generated by GUID system) is better because there is no maximum value ?

**Comment by kroniak** [comment]
@ikourfaln No, I dont mean that.

**Comment by ikourfaln** [comment]
@kroniak  So !!

**Comment by liamwang** [comment]
I prefer to use sequential GUIDs as primary keys. Sequential GUIDs are more efficient than string, even more efficient than auto increment int. It is friendly to ORM frameworks, which avoid relying on the server to generate key values. It also has advantages in distribution system.

**Comment by ikourfaln** [comment]
@liamwang thank you for infos

**Comment by jvelezc** [comment]
Please read this article I wrote : https://medium.com/@goodealsnow/asp-net-core-identity-3-0-6018fc151b4#.pvc8b09bd it explains how to easily change things around for you db team. Why did they choose string guid? Because it was an easy way to ensure uniqueness.
