### ISSUE TITLE
XML doc issues in Identity classes

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Identity#875]
* `LockoutOptions.AllowedForNewUsers` property gives no intellisense documentation (whereas the other two properties on that class do)
* `CookieAuthenticationOptions.CookieName` intellisense docs claims the default value is `.AspNetCore.Cookies`, but the actual default value seems to be `.AspNetCore.Identity.Application`

**Comment by HaoK** [comment]
This is because the default from identity is different than the cookies default but the intellesense comes from cookies
> CookieAuthenticationOptions.CookieName intellisense docs claims the default value is .AspNetCore.Cookies, but the actual default value seems to be .AspNetCore.Identity.Application

**Comment by SteveSandersonMS** [comment]
OK, makes sense. Maybe we shouldn't mention the default value in the XML docs if we have a high probability of giving false information.

**Comment by HaoK** [comment]
ec4c08d11a00ec9b4dd8c22ef13a4950cb70901e
