### ISSUE TITLE
AutoSaveChanges in IUserStore

### ISSUE THREAD

**Issue by YZahringer** [aspnet/Identity#877]
To import users, I set the property UserStore.AutoSaveChanges to False, I create all users with UserManager.CreateAsync and then I call UserStore.Context.SaveChangesAsync.

This works, but I have to cast IUserStore to UserStore to access to the property AutoSaveChanges. The property AutoSaveChanges should not be in the IUserStore interface? There is another way to make an import of multiple users in a "single transaction"?

**Comment by HaoK** [comment]
AutoSaveChanges is a behavior specific to the EntityFramework implementation UserStore, which is why you have to cast it.

**Comment by YZahringer** [comment]
Yes I understand, but there no other/official way to import multiple users in bulk?

Retrieve UserStore directoy by DI is currently not possible, it would be a solution to avoid the cast.

**Comment by HaoK** [comment]
The property only lives on UserStore, so yes you have to a reference to that type to use the property.

**Comment by NtFreX** [comment]
Can we add this property to the startup configuration? Because when I can't find a (not crazy) solution to prevent the auto save from happening when I use the UserManager.
