### ISSUE TITLE
System.Security.Principal.Current.Claims doesnt return Identity Claims

### ISSUE THREAD

**Issue by uselesshasid** [aspnet/Identity#880]
After login using Asp.net Identity, HttpContext.User.Claims doesnt have the same claims as System.Security.Claims.ClaimsPrincipal.Current.Claims

When using Asp.net Identity v2 they are the same

Here is a simple asp.net core website created in VS 2015
https://github.com/uselesshasid/AspNetIdentity_Issue_880

- Clone the project
- On the website project folder run dotnot ef database update
- Run the website
- Create an account 
- Login
- Go to /home/claims

The page will display claims from both places

**Comment by HaoK** [comment]
This is correct, SignIn has no effect on ClaimsPrincipal.Current in Core.  @blowdart

**Comment by HaoK** [comment]
Dupe of https://github.com/aspnet/Security/issues/322
