### ISSUE TITLE
The AspNetCoreCompat package needs to be updated

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Identity#881]
https://github.com/aspnet/Identity/tree/dev/src/Microsoft.AspNet.Identity.AspNetCoreCompat
The `CreateSharedDataFormat` method uses "Microsoft.AspNet.Authentication.Cookies.CookieAuthenticationMiddleware" which of course is the old name. Should check other parts of the source too and update the sample

**Comment by BrennanConroy** [comment]
@HaoK @Tratcher

**Comment by HaoK** [comment]
Ah good catch, thanks!

**Comment by HaoK** [comment]
9e0204279818869b43c7cb4695b726c2960be662
