### ISSUE TITLE
WebApi Questions and Example ?

### ISSUE THREAD

**Issue by NVentimiglia** [aspnet/Identity#884]
I was going to start implementing authentication and authorization on a Core based web server and was wondering if I should use Identity framework. In the past I had been forced to roll my own... something I would rather not do.

- What is the roadmap for a WebApi json-serving example ?
- What will the api authentication mechanism look like ? Will It be header based or cookie based ?
- How easy / difficult would it be to extend and override this ?
- How will identity conflicts / migrations be handled ?
- Will password reset be exposed (was not in previous samples of identity) ?
- Will Managment be exposed ?
- Are OAUTH and third party providers such as still Facebook supported ? I ask because it is branched off into its own service. https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers. Are these competing products ?

**Comment by PinpointTownes** [comment]
> Are OAUTH and third party providers such as still Facebook supported ? I ask because it is branched off into its own service. https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers. Are these competing products ?

Yes they are. You can find the Google/Facebook/Twitter/Microsoft providers in the aspnet/Security repository: https://github.com/aspnet/Security/tree/dev/src.

The project you mentioned aims at supporting other well-known social providers (e.g LinkedIn, GitHub, Reddit or Wordpress). All these providers are developed by the community and use the same OAuth2 generic middleware as the "official providers".

**Comment by NVentimiglia** [comment]
What about the JSON based (API) Account / Manager controller ?

**Comment by PinpointTownes** [comment]
That's a question for @HaoK :smile:

**Comment by HaoK** [comment]
@blowdart thoughts?

**Comment by blowdart** [comment]
It's not something we've considered. Identity is pretty much interactive browser via form submission. WebAPI et al would want bearer tokens, and that's not on the roadmap, given the various community offerings around OAuth servers.

**Comment by NVentimiglia** [comment]
> given the various community offerings around OAuth servers.

So I take it that Identity is really only meant for starter projects with no support for WebApi / JWT out of the box. That smells like an oversight, but ok. Can you point me to a quality community driven Identity replacement then ? Preferably one that supports OAuth as well as traditional email authentication (such as Identity).

**Comment by PinpointTownes** [comment]
Microsoft's recommended approach is to use their (commercial) Azure AD/B2C offer.

If you prefer open source solutions, you can take a look at IdentityServer 4, ASOS (`OAuthAuthorizationServerMiddleware`'s equivalent in the vNext world) or OpenIddict (which is basically "Identity for Web API"): https://github.com/aspnet/Identity/issues/503

**Comment by brockallen** [comment]
> That smells like an oversight, but ok.

They actually said it was deliberate: https://github.com/aspnet/Identity/issues/883#issuecomment-228569093

**Comment by NVentimiglia** [comment]
>> That smells like an oversight, but ok.
> They actually said it was deliberate: #883 (comment)

I am not following, this discussion is about Entity Framework and the DAL, not a WebApi interface.

**Comment by brockallen** [comment]
> I am not following, this discussion is about Entity Framework and the DAL, not a WebApi interface.

You said it sounded like an oversight that "Identity" (which means ASP.NET Identity) did not accommodate non-web scenarios. I linked that that it was not an oversight.

**Comment by NVentimiglia** [comment]
> You said it sounded like an oversight that "Identity" (which means ASP.NET Identity) did not accommodate non-web scenarios. I linked that that it was not an oversight.

What do you mean by non-web ? Web Api is web, it is just serving json instead of html.

**Comment by brockallen** [comment]
Right, but that's not what Microsoft is supporting. They are tied to the cookie/browser use case. There are OAuth2 flows that don't involve a browser.

**Comment by NVentimiglia** [comment]
> Right, but that's not what Microsoft is supporting. They are tied to the cookie/browser use case. There are OAuth2 flows that don't involve a browser.

Gotcha, that makes sense.
