### ISSUE TITLE
Exception when trying to get the user if the Users table has PK of int, and the user logged in with external provider

### ISSUE THREAD

**Issue by gdoron** [aspnet/Identity#885]
#780 
@HaoK, I had to revert all my tables back to varchar because of a bug with int users.

Steps to reproduce:

Change the PK of user to int,
Login with external provider where the key isn't int compatible (FB, LinkedIn, etc.)
In the View use this:

	UserManager.GetUserAsync(User);
Exception is thrown saying the key isn't int compatible.

Unfortunately we encountered it just before we had to demo something to our investors... so we change everything ASAP and didn't keep the exception and stack trace.

**Comment by HaoK** [comment]
This is likely to be a dupe of https://github.com/aspnet/Identity/issues/860 where you need to turn off AutomaticAuthenticate for the external cookie, due to a bug in RC2 that's fixed in 1.0.0

**Comment by gdoron** [comment]
@HaoK I'll give it a try in couple of days, after RTM and will let you know.

**Comment by gdoron** [comment]
@HaoK So I moved to 1.0.0 and my PK is a string, and I'm not sure how I can go back to int because the table already has real data in it.
Any suggestions?

**Comment by HaoK** [comment]
Can you try to migrate the data using EF Migrations?

**Comment by gdoron** [comment]
@HaoK I hope I'll have the time for it in the weekend.
We are overwhelmed with tasks.

Will let you know soon.

**Comment by gdoron** [comment]
@HaoK 

Sorry for the extremely late response.
Our codebase has changed a lot since we moved  from int to string, it required a lot of time to get to that point in time and fiddle with that, and time is a thing crucially missing in an early stages startup.

As far as I can see, it's working now using RTM bits.
But I guess for us it's too late, as we have too much data which rely on varchar.

Well that's life.

Thanks.
