### ISSUE TITLE
Invalidate old Authentication cookie

### ISSUE THREAD

**Issue by dpmragu** [aspnet/Identity#886]
The cookie called AspNet.ApplicationCookie is generated by OWIN after successful login. I cloned the request with cookies after login using Fiddler or other tool, then I signed out from application. I was able to access the application using cloned request without entering user name and password. It seems old session cookie can be used to authenticate a user with unlimited time . 

Is there any way to fix this issue?

**Comment by HaoK** [comment]
The lifetime of the cookie is determined by `identityOptions.Cookies.ApplicationCookie.ExpireTimeSpan`
