### ISSUE TITLE
CookieSecureOption missing after Asp.Net Core 1.0 RTM upgrade

### ISSUE THREAD

**Issue by logankd** [aspnet/Identity#888]
I'm getting compiler errors on 
services.AddIdentity<ApplicationUser, IdentityRole>(config =>
			{
				config.Password.RequiredLength = 8;
				config.Password.RequireDigit = false;
				config.Password.RequireNonAlphanumeric = true;
				config.Cookies.ApplicationCookie.CookieSecure = CookieSecureOption.Always;

after updating to the RTM bits.
 "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
The type changed to a CookieSecurePolicy, but I'm not finding how to set it.
I didn't see an announcement about it.

Can I just remove that line since the comment says it is http by default?

**Comment by BrennanConroy** [comment]
You looking for https://github.com/aspnet/HttpAbstractions/blob/release/src/Microsoft.AspNetCore.Http.Abstractions/CookieSecurePolicy.cs#L24 ?

**Comment by logankd** [comment]
Thanks, @BrennanConroy. Shouldn't this be in the https://github.com/aspnet/Announcements/?

**Comment by BrennanConroy** [comment]
@Tratcher

**Comment by Tratcher** [comment]
https://github.com/aspnet/Announcements/issues/197.

Use CookieSecurePolicy.Always here, the default is only SameAsRequest.
