### ISSUE TITLE
What's the reasoning behind UserManager<TUser>.GetUserIdAsync(TUser user) ?

### ISSUE THREAD

**Issue by gdoron** [aspnet/Identity#889]
If I have the TUser instance, I can simply use user.Id, can't I?

Why does this method exist?

BTW, What is the most efficient way of getting the current logged in user 's Id in ASP.NET Core?

Thanks,
Doron

**Comment by HaoK** [comment]
User.Id exists in the identity EF implementation. It's not necessarily required as custom identity  implementations do not have to expose an id property. The tradeoff is between having the manager abstract this operation or directly going against an implementation property that the store backs against.

**Comment by gdoron** [comment]
@HaoK 

A. So might be a good idea changing the template which does use EF and still uses this method to get the id (didn't check if it was changed in 1.0.0 but I guess it wasn't).

B. Any tip about _What is the most efficient way of getting the current logged in user's Id in ASP.NET Core?_ because currently I'm using this awkward code to get the user with a navigation property:

	var user = await UserManager.GetUserAsync(HttpContext.User);
	user = await Context.Users.Where(x => x.Id == user.Id).Include(x => x.Follows).SingleAsync();
	
There **must** be a better way of doing this!

**Comment by brockallen** [comment]
> Any tip about What is the most efficient way of getting the current logged in user's Id in ASP.NET Core

Put the user's id as a claim in the cookie when you sign them in.
