### ISSUE TITLE
a serious bug in UserCore

### ISSUE THREAD

**Issue by richerp** [aspnet/Identity#890]
public abstract class UserStore〈TUser, TRole, TContext, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken〉
.............................
    where TRole：IdentityRole〈TKey, TUserRole, IdentityRoleClaim〈TKey〉〉
 ............................

error:     where TRole ： IdentityRole 〈TKey, TUserRole, IdentityRoleClaim〈TKey〉
correct:  where TRole ： IdentityRole 〈TKey, TUserRole, TRoleClaim〉 ?

**Comment by richerp** [comment]
public abstract class UserStore<TUser, TRole, TContext
.....
where TRole : IdentityRole<TKey, TUserRole, IdentityRoleClaim<TKey>>

is it where TRole : IdentityRole<TKey, TUserRole, TRoleClaim>????

**Comment by HaoK** [comment]
Can you clarify what you are asking?

**Comment by richerp** [comment]
error: where TRole ： IdentityRole 〈TKey, TUserRole, IdentityRoleClaim〈TKey〉
correct: where TRole ： IdentityRole 〈TKey, TUserRole, TRoleClaim〉 ?

**Comment by HaoK** [comment]
Ah yes, dupe of https://github.com/aspnet/Identity/issues/855
