### ISSUE TITLE
Usermanager updates affecting related entities

### ISSUE THREAD

**Issue by markusvt** [aspnet/Identity#894]
After updating my working RC1 project to Core 1.0 i came across following problem:

I have the following database structure:

```
User (0..1) --> (0..1) Contact (1)  <---> (*) ContactGroup (*) <--> (1) Group
```

So I got a m:n relation between `Contact` and `Group` plus my `User` Entity has a Single Relation to `Contact`  

So i have the following code in one of my controllers, that is supposed to update some group-assignments and also update the security timestamp of the user afterwards. In the code, the variable `b` is a role that contains some users

```
if(b.hasGroupChanges)
{
   IEnumerable<Contact> contacts = StaticServices.getRepository<ContactRepository>().getContacts(b.getAssignedUsers().Where(u => u.ContactId.HasValue).Select(u => u.ContactId.Value)).ToList();

   foreach (var group in b.groupsToAdd)
   {
      group.addContacts(contacts);
   }

   foreach (var group in b.groupsToRemove)
   {
      group.removeContacts(contacts);
   }
}
StaticServices.getMapper<Group>().applyChanges();

//Before: foreach(var user in b.getAssignedUsers())
foreach (var user in StaticServices.getRepository<BenutzerRepository>().getWithContactsOfIds(b.getAssignedUsers().Select(u => u.Id)).ToList())
{
   if (user != null)
   {
      await StaticServices.getUsermanager().UpdateSecurityStampAsync(user);
   }
}
```

So  my problem is the following: the first part to update the groups works without problem. Afterwards i wanted to get all assigned users of my role `b` and update the security timestamp. In RC1 that worked. If i do it now, my `ContactGroup` connections get `NULL` values in GroupId and ContactId (so the relation isnt deleted but the IDs get removed). 

The `b.getAssignedUsers` Method does the following:
`return await StaticServices.getUsermanager().GetUsersInRoleAsync(this.Name)`

So after some trying i found out, that i have to load the users + all contact and group relations so that those IDs are not removed.
So did I miss something? I thought if i just want to update that security timestamp I just need the users but somehow the relations are also necessary.

**Comment by HaoK** [comment]
What does StaticServices.getUserManager() look like?

**Comment by markusvt** [comment]
here is the original code:

```
public static UserManager<Benutzer> getUsermanager()
        {
            return (UserManager<Benutzer>) RequestServices.GetService(typeof(UserManager<Benutzer>));
        }
```

RequestServices is the following:
```
 private static IServiceProvider RequestServices
        {
            get
            {
                return HttpContext?.RequestServices;
            }
        }
```
where HttpContext is the current http context of the request
