### ISSUE TITLE
User authentication timeout - ApplicationCookie.ExpireTimeSpan ignored

### ISSUE THREAD

**Issue by tmm360** [aspnet/Identity#900]
As for #766, I've the same problem. Users are logged out after ~30 minutes (didn't check exact time).
I'm running RTM and this is the portion of my configuration where i set asp's services.

            services.AddMemoryCache();
            services.AddIdentity<User, Role>(opts =>
            {
                //cookie
                opts.Cookies.ApplicationCookie.ExpireTimeSpan = TimeSpan.FromDays(30);
                opts.Cookies.ApplicationCookie.LoginPath = new PathString("/App");
                opts.Cookies.ApplicationCookie.LogoutPath = new PathString("/App/Logout");
                opts.Cookies.ApplicationCookie.SlidingExpiration = true;
                //email
                opts.User.RequireUniqueEmail = true;
                //password
                opts.Password.RequireDigit = false;
                opts.Password.RequiredLength = 6;
                opts.Password.RequireLowercase = false;
                opts.Password.RequireNonAlphanumeric = false;
                opts.Password.RequireUppercase = false;
            }).AddDefaultTokenProviders();
            services.AddLocalization(opts => opts.ResourcesPath = "Resources");
            services.AddMvc()
                .AddDataAnnotationsLocalization()
                .AddViewLocalization();
            services.AddSession(opts => opts.IdleTimeout = TimeSpan.FromMinutes(60));

**Comment by HaoK** [comment]
Do you have a security stamp set for your user's?

**Comment by tmm360** [comment]
Yes I have, and it doesn't change

**Comment by HaoK** [comment]
What does the cookie look like in F12, can you include what headers it has here?

**Comment by tmm360** [comment]
A cookie header sample:
`Cookie: .AspNetCore.Antiforgery.w5W7x28NAIs=CfDJ8P9CdzvZvT1AlVB9wjmoTzmTapz9JT3mQRnUDv-DQ4uedGqcDY87YsqoUnVzGbmsScltsXVEbpDDCYo1pNrPqY1fBT9zem1Tdy-YL2aNOMkY63nrA3Y2X8HFRvFTyNiiqmnQAzFE5aUwSyEZbmJCQgg; .AspNetCore.Session=CfDJ8P9CdzvZvT1AlVB9wjmoTzkng%2FAXY2y5QD%2B6GzlTmLYCbe9q6ln73S%2BnuTOXl8O27wL%2BrY4dQe9rSb5b%2FM59EScgKJlArPjUsroYTvRVHy1mJx5y3FEgvMVJYyE7uPp8P77NykT2lPK8KSbpo1Gp15OUL%2F1mAFHMAKzh8qQtuFyx; ARRAffinity=5ab45bb448faaa6c281c76d2c75f7d67c31d8a3024d62d44737acd94c45aa6f0; .AspNetCore.Identity.Application=CfDJ8P9CdzvZvT1AlVB9wjmoTznE-a-g6Co11Dl48i4H03nayi_-mTcH6DKST7LEXXysxDKw1d6knWHO71int2-SbjcAk_5_cMFKWy113udPwKUdYYedsrAMmVGC1HMQhaPc3t_CpSpZtLe5lLYTNrehDSjIIEWvh0VPLIkl5HxgptWbLMxnnVrDE3RnwlWWZVW3jF4A1SUxn2lu9WN5sgQITAv-m-Ij-VNIdv4FUOE2PVB1NI1Xe_80cFQFIIdEpn7T9EubRx1akitoW_3EGcOCWPSUphXMNGWfgGGfXFrXYSAaNv8AOmOIcwVbAOdNlXGb2EHQyGsbOT9nmiCNSQi3reUjFgHx489tojFtGpzTzUctbBzqXwWftQ8EIqy4rjbehOxg4xVk5r6vFEbjFX0VRFlEsF4QfFluOc_Mv2XXhUZBJvcbv1_cwZTgfgtEV2lbImAjBLjf0hf200EazLR5DrJPK4pZ8pMnh6XON93rHmdCeunuAJuLmoaqt1Vkxo-y9-CvhTczXleAP1T_j9cRl0cZhzArHOLQr9ssqexXGm9OHBsmrlbp8GTCxdhwlFncPcQozp8TcEbm36Jc_XMBIV8`

**Comment by HaoK** [comment]
Do you see any extra info like Expires as well?

**Comment by tmm360** [comment]
No, only a 302 message with a redirect to the login page.
I've experimented that ExpireTimeSpan works if I set a small timespan of some minutes, and it stop to works with longer.

**Comment by tmm360** [comment]
This test fails:

        [Fact]
        public async Task CanCreateMeLoginAndCookieStopsWorkingAfterExpiration_LongTime()
        {
            var clock = new TestClock();
            var server = CreateServer(services => services.Configure<IdentityOptions>(options =>
            {
                options.Cookies.ApplicationCookie.SystemClock = clock;
                options.Cookies.ApplicationCookie.ExpireTimeSpan = TimeSpan.FromDays(10);
                options.Cookies.ApplicationCookie.SlidingExpiration = false;
            }));

            var transaction1 = await SendAsync(server, "http://example.com/createMe");
            Assert.Equal(HttpStatusCode.OK, transaction1.Response.StatusCode);
            Assert.Null(transaction1.SetCookie);

            var transaction2 = await SendAsync(server, "http://example.com/pwdLogin/false");
            Assert.Equal(HttpStatusCode.OK, transaction2.Response.StatusCode);
            Assert.NotNull(transaction2.SetCookie);
            Assert.DoesNotContain("; expires=", transaction2.SetCookie);

            var transaction3 = await SendAsync(server, "http://example.com/me", transaction2.CookieNameValue);
            Assert.Equal("hao", FindClaimValue(transaction3, ClaimTypes.Name));
            Assert.Null(transaction3.SetCookie);

            clock.Add(TimeSpan.FromDays(7));

            var transaction4 = await SendAsync(server, "http://example.com/me", transaction2.CookieNameValue);
            Assert.Equal("hao", FindClaimValue(transaction4, ClaimTypes.Name));
            Assert.Null(transaction4.SetCookie);

            clock.Add(TimeSpan.FromDays(7));

            var transaction5 = await SendAsync(server, "http://example.com/me", transaction2.CookieNameValue);
            Assert.Null(FindClaimValue(transaction5, ClaimTypes.Name));
            Assert.Null(transaction5.SetCookie);
        }

I've token the original from prev tests and replaced `FromMinutes` with `FromDays`.

**Comment by HaoK** [comment]
Your test is failing because of something unrelated, the security stamp interval controls regenerating the cookie, if you set that to also 10 days, it won't regenerate the identity...
```
                options.SecurityStampValidationInterval = TimeSpan.FromDays(10);
```

**Comment by HaoK** [comment]
By default the cookie is refreshed after 30 minutes on the next request to ensure the claims are up to date assuming the security stamp hasn't changed, if that has changed, it will sign out and clear the cookie instead.

**Comment by tmm360** [comment]
I will investigate more... Have you tried to reproduce the issue?

**Comment by HaoK** [comment]
We have tests that exercise cookie expiration that are passing, if the timespan that is causing cookie signout issues is exactly 30 minutes, that is the security stamp validator that usually is causing the logout.

Try setting that to something longer to see if that is what you are running into.

**Comment by tmm360** [comment]
My project uses a timespan of 30 days.
Now I'm trying to attach Identity's project to mine, for try a direct debug.

**Comment by tmm360** [comment]
You are right! My code was blocking reading of security stamp from for a wrong security configuration. Now I've fixed and it works. Thank you!
