### ISSUE TITLE
AzureAD & Roles with EntityFramework

### ISSUE THREAD

**Issue by wangkanai** [aspnet/Identity#901]
How do you assign roles to azure active directory users?
How do I assign Users identity to the Entity their created in Entity Framework Core?
How do I have authorization in the Query entity collection that their have permission or are in the roles?

```
public class Category : Entity, ITimeLogger
{
    public int Order { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public DateTime Created { get; set; }
    public DateTime Updated { get; set; }
    public User User { get; set; }
    public Visibility Visibility { get; set; }   
    public List<Section> Sections { get; set; }  
}
```

So for the many questions :) much documentation regarding these questions i couldn't find anywhere or googling.

Thank you very much

**Comment by blowdart** [comment]
This is confusing. How are you using Azure AD? As an external login provider in the same way we do social like Facebook and Google, or using it via the Work & School template? If it's the latter then that's a function of AD, and doesn't concern or use identity at all.
