### ISSUE TITLE
Azure Active Directory B2C

### ISSUE THREAD

**Issue by wangkanai** [aspnet/Identity#902]
Has ASP.NET Core support [Azure Active Directory B2C](https://azure.microsoft.com/en-us/services/active-directory-b2c/) as a feature yet?

**Comment by GuardRex** [comment]
Well, it's not so much .NET Core supporting B2C as it is just having a sample for B2C. It does work today, we just don't have a dedicated sample for the app case from MS yet. You can make the conversion from samples and docs, such as ...

https://azure.microsoft.com/en-us/documentation/articles/active-directory-b2c-devquickstarts-web-dotnet/
https://github.com/AzureADQuickStarts/B2C-WebApp-OpenIdConnect-DotNet

I imagine that @dstrockis is on the case tho. He is a most excellent :cat2: and provides great samples and docs.

I have a very, very old one (beta7) that gives the general outline of what must be done, but I wouldn't look too closely at it at this late stage: https://github.com/GuardRex/AZUREB2C. There are definitely more recent examples floating around out there, like https://github.com/dzimchuk/azure-ad-b2c-asp-net-core and https://github.com/estiller/AzureB2CWithAspNetCoreSample.

**Comment by HaoK** [comment]
Closing, not related to identity
