### ISSUE TITLE
AccessDenied Google OAuth

### ISSUE THREAD

**Issue by NVentimiglia** [aspnet/Identity#903]
I am sometimes getting a funky result from google when I sign in. I say sometimes because a few times the service works fine. When it goes bad, google calls back to the Account/AccessDenied action. This action is undefined, so, I see a blank page. 

This 'AccessDenied' literal shows up nowhere in my project. If I define an action method, it is surely hit and includes a 'returnUrl' argument. the returnUrl argument is '/Account/ExternalLoginCallback'

Here is my startup.cs partial 

```
app.UseGoogleAuthentication(new GoogleOptions
            {
                //Keys here
                Events = new OAuthEvents()
                {
                    OnRemoteFailure = ctx =>
                    {
                        //I have a breakpoint here that is never hit.
                        ctx.HandleResponse();
                        return Task.FromResult(0);
                    },
                }
            });
```

The rest of my code is unchanged.

**Comment by HaoK** [comment]
The AccessDenied is the default url used if no AccessDeniedPath is configured in the options:

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationMiddleware.cs#L57

**Comment by NVentimiglia** [comment]
What could be causing this ? ExternalLoginCallback and ExternalLogin are annotated with AllowAnonymous. Again, this is a 99% out of the box default template. This should not be happening.

**Comment by NVentimiglia** [comment]
```
 [HttpGet]
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> AccessDenied(string returnUrl = null)
        {
            return Redirect(returnUrl); // ExternalLoginCallback
        }
```

Here is my current work around, please dont let me do this.

**Comment by NVentimiglia** [comment]
Also, should I be implementing AccessDenied ? It feels like that should be a included with identity.

**Comment by NVentimiglia** [comment]
@HaoK 

Removing the [Authorize] annotation on the AccountController solved this. Obviously, this is not a good solution. This smells like a **bug** in the Authorize annotation.
