### ISSUE TITLE
Update AspNet Core compat package

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#906]
Seems to be some issues installing the package today, see https://github.com/aspnet/EntityFramework/issues/2167#issuecomment-232205222

I tried installing it from the nuget feed and see: Unable to resolve dependency 'Microsoft.AspNet.DataProtection.Extensions'. Source(s) used: 'ASPNET1', 'nuget.org', 'Microsoft Visual Studio Offline Packages'.			0

**Comment by ToddThomson** [comment]
@HaoK Sorry, I didn't mention that I got had this issue as well yesterday. The package does exist and can be installed individually.

**Comment by HaoK** [comment]
Fixed via f9cdef745f92b05c1c141d80b6af6b14b165ee62
