### ISSUE TITLE
Check if current user is in specific Role without querying for TUser first

### ISSUE THREAD

**Issue by gdoron** [aspnet/Identity#908]
Hi,

Usually people categorize actions for different roles, and it is easily done with 

	[Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)

But often the required role depends on the request parameters:

	[Authorize]
	public ActionResult Edit(string id)
	{
		// doesn't compile
	    if (User.FindFirst(ClaimTypes.NameIdentifier).Value != id &&
	        !UserManager.IsInRoleAsync(User.FindFirst(ClaimTypes.NameIdentifier).Value, "Admin"))
	    {
	        throw new SecurityException();
	    }
	    //...
	}
	
Problem is, `UserManager.IsInRoleAsync` expects a TUser, not a TKey (the id).
So we need to query the user from the DB first, which is completely redundant.

Am I doing something wrong?

**Comment by brockallen** [comment]
If the request is authenticated and the role is in the cookie, then why query the DB? Instead use:

```
User.IsInRole("foo")
```

or

```
if (User.HasRole("role", "admin"))
```

**Comment by gdoron** [comment]
@brockallen thanks mate!
> Am I doing something wrong?

**Yes.** :smile: 

BTW, how do I refresh the cookie after I update a user's claims?

**Comment by brockallen** [comment]
> BTW, how do I refresh the cookie after I update a user's claims?

Call RefreshSignInAsync on the SIgnInManager.
