### ISSUE TITLE
Is Identity thread safe?

### ISSUE THREAD

**Issue by gdoron** [aspnet/Identity#909]
I use Identity with `DbContext` as the store.
I'm aware of [`DbContext` not being thread safe](EntityFramework/issues/5962), but what about Identity?
Are SignInManager and UserManager thread safe? Does it depend on the backend store?

Can stuff like the following run in parallel?

	UserManager.ReplaceClaimAsync
	UserManager.AddClaimsAsync
	
Thanks

**Comment by brockallen** [comment]
Well, the user manager uses the context, so I don't think so.

**Comment by gdoron** [comment]
@brockallen I thought this will be the answer, just wanted to be sure.
I'll close it as your answer is an `officialAnswer - 1`  :)

Thanks
