### ISSUE TITLE
Extend the cookie with custom claims

### ISSUE THREAD

**Issue by seriouz** [aspnet/Identity#910]
Is it possible to extend the identity cookie with custom claims like firstname and lastname?
I did not find anything regarding in the docs.

**Comment by brockallen** [comment]
Extend the UserClaimsPrincipalFactory (https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserClaimsPrincipalFactory.cs) and register it in DI. I show how to do this in this video: https://vimeo.com/172009501 from NDC.
