### ISSUE TITLE
Empty Birthday and Gender Google Authentification .Net Core RC2

### ISSUE THREAD

**Issue by maslovay** [aspnet/Identity#916]
I have already got users mail, name with GoogleAuthentication .Net Core RC2

Now I'm trying to get birthday and gender fields.

Here is my start Starptup.cs code:

app.UseGoogleAuthentication(new GoogleOptions()
{
   ClientId = "***",
   ClientSecret = "***",
   Scope = { "https://www.googleapis.com/auth/plus.me", "https://www.googleapis.com/auth/userinfo.profile", "https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/plus.login" },
   SaveTokens = true
});
last two parameters are not required, i have added them to make sure that scope is correct

I have google api response, that contains birthday and gender fiddler screenshot I try to receive birthday and gender in AccountController like this:

var gender = info.Principal.FindFirstValue(ClaimTypes.Gender);
var birthday = info.Principal.FindFirstValue(ClaimTypes.DateOfBirth);
But it returns empty fields(

How I can correctly map that claimtypes and google fields? or maybe you have other solutions of this problem

![json](https://cloud.githubusercontent.com/assets/11196396/17021899/a0a33196-4f53-11e6-9038-9e260b5bc138.JPG)

**Comment by HaoK** [comment]
var gender = info.Principal.FindFirstValue("gender");
var birthday = info.Principal.FindFirstValue("birthday");

probably should work

**Comment by maslovay** [comment]
Haok, your code doesn't work. It returns empty fields (aslo in Facebook authorization). With my code works with facebook (it receives gender and birthday), but doesn't work with google.

Can you offer other sollution?

**Comment by HaoK** [comment]
Debug and look at info.Principal to see what claims it has, its possible those claims are simply ignored by default and never transferred over to the cookie

**Comment by maslovay** [comment]
Haok, sorry how can I check it? 
As I can see the problem is that GoogleAuthentication RC2 can't match ClaimTypes.Birthday and ClaimTypes.Gender with the Json fields from Google API

**Comment by HaoK** [comment]
Set a breakpoint on those lines, and include what claims it actually has

**Comment by maslovay** [comment]
![claims](https://cloud.githubusercontent.com/assets/11196396/17066505/06874bf8-5050-11e6-9651-fe9a8a09d135.jpg)


Haok, thanks one more time! 
There are no gender and birthday in claims
So how can I solve that problem?

**Comment by HaoK** [comment]
Doesn't look like the google handler will copy over any extra claims you ask for by default, I think you just need to plug in your own CreatingTicket event to store the extra claims you requested.

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Google/GoogleHandler.cs#L75

**Comment by maslovay** [comment]
Haok, thanks I'll try!

Why the GoogleAuthentication doesn't work properly? Onyone will have same problem. Walkaround is not best sollution

**Comment by maslovay** [comment]
I try to update your code to get Birthday and Gender 

var gender = payload["gender"].Value<string>();
 if (!string.IsNullOrEmpty(gender))
  {
identity.AddClaim(new Claim(ClaimTypes.Gender, gender, ClaimValueTypes.String, Options.ClaimsIssuer));
 }

  var birthday = payload["birthday"].Value<string>();
if (!string.IsNullOrEmpty(birthday))
 {
                identity.AddClaim(new Claim(ClaimTypes.DateOfBirth, birthday, ClaimValueTypes.String, Options.ClaimsIssuer));
}

But I have no result(

May be I can't call properly it?  
I have to do it from my AccountController?

**Comment by HaoK** [comment]
See http://stackoverflow.com/questions/18942196/how-to-access-facebook-private-information-by-using-asp-net-identity-owin the second (26 upvoted) answer.

This is for Identity 2, but it should be similar for core, where you hook the `OnCreatingTicket` event instead to include the birthday/gender, and add the claims during SignIn like the SO answer

**Comment by maslovay** [comment]
Haok, let me check my steps to do:
1. In my  **startup.cs** i place only basic GoogleOptions (ClientId, ClientSecret)  - done 
2.  I add GoogleHandler.cs to override the Google claims (and add Birthday and Gender) (only CreateTicketAsync procedure) - done
3. In my AccountController I try to get Birthday and Gender Claims with GetExternalLoginInfoAsync as usual - done
That staff doesn't work

what is incorrect?

**Comment by PinpointTownes** [comment]
@maslovay there's no need to create your own `GoogleHandler.cs`, you can leverage the events model for that: http://stackoverflow.com/a/35634697/542757

**Comment by maslovay** [comment]
Yes! It works!!!!))

Thank you  lot, PinpointTownes!

**Comment by maslovay** [comment]
But I think it's .Net Google Authentification   bug, because it can't receive fields by default(

**Comment by HaoK** [comment]
This was the design, only a specific set of claims are copied into the ticket by default.

**Comment by maslovay** [comment]
HaoK but facebook Authentification do this staff without any additional code. I think lot of people will face such a problem

**Comment by HaoK** [comment]
I believe that is because those claims are requested by default in the facebook auth handler.
