### ISSUE TITLE
How to support sequential GUIDs as primary keys.

### ISSUE THREAD

**Issue by liamwang** [aspnet/Identity#917]

**Comment by arespr** [comment]
You could use one of these implementations to generate guids:

`/// <summary>
    /// Code based on http://developmenttips.blogspot.com/2008/03/generate-sequential-guids-for-sql.html
    /// </summary>
    public class SqlServerSequentialGuidGenerator
    {
        //        With UIDs As(
        //Select ID = 3, UID = cast('01000000-0000-0000-0000-000000000000' as uniqueidentifier)
        //Union Select ID = 2, UID = cast('00010000-0000-0000-0000-000000000000' as uniqueidentifier)
        //Union Select ID = 1, UID = cast('00000100-0000-0000-0000-000000000000' as uniqueidentifier)
        //Union Select ID = 0, UID = cast('00000001-0000-0000-0000-000000000000' as uniqueidentifier)
        //Union Select ID = 5, UID = cast('00000000-0100-0000-0000-000000000000' as uniqueidentifier)
        //Union Select ID = 4, UID = cast('00000000-0001-0000-0000-000000000000' as uniqueidentifier)
        //Union Select ID = 7, UID = cast('00000000-0000-0100-0000-000000000000' as uniqueidentifier)
        //Union Select ID = 6, UID = cast('00000000-0000-0001-0000-000000000000' as uniqueidentifier)
        //Union Select ID = 8, UID = cast('00000000-0000-0000-0100-000000000000' as uniqueidentifier)
        //Union Select ID = 9, UID = cast('00000000-0000-0000-0001-000000000000' as uniqueidentifier)
        //Union Select ID = 10, UID = cast('00000000-0000-0000-0000-010000000000' as uniqueidentifier)
        //Union Select ID = 11, UID = cast('00000000-0000-0000-0000-000100000000' as uniqueidentifier)
        //Union Select ID = 12, UID = cast('00000000-0000-0000-0000-000001000000' as uniqueidentifier)
        //Union Select ID = 13, UID = cast('00000000-0000-0000-0000-000000010000' as uniqueidentifier)
        //Union Select ID = 14, UID = cast('00000000-0000-0000-0000-000000000100' as uniqueidentifier)
        //Union Select ID = 15, UID = cast('00000000-0000-0000-0000-000000000001' as uniqueidentifier)
        //)
        //Select* From UIDs Order By UID
        private static readonly int[] SqlOrderMap = { 3, 2, 1, 0, 5, 4, 7, 6, 9, 8, 15, 14, 13, 12, 11, 10 };


        private readonly byte[] _currentGuidArray;
        private Guid _currentGuid;

        public Guid CurrentGuid
        {
            get { return _currentGuid; }
        }

        public SqlServerSequentialGuidGenerator()
            :this(Guid.NewGuid())
        {
        }

        public SqlServerSequentialGuidGenerator(Guid initialGuid)
        {
            _currentGuid = initialGuid;
            _currentGuidArray = initialGuid.ToByteArray();
        }

        public  Guid Generate()
        {
            byte[] guidArray = _currentGuidArray;
            var orderMap = SqlOrderMap;
            for (int mapIndex = 0; mapIndex < 16; mapIndex++)
            {
                int bytesIndex = orderMap[mapIndex];
                guidArray[bytesIndex]++;
                if (guidArray[bytesIndex] != 0)
                {
                    break; // No need to increment more significant bytes
                }
            }
            _currentGuid =  new Guid(guidArray);
            return _currentGuid;
        }
    }`
Or
`/// <summary>
    /// Code based on http://www.informit.com/articles/article.aspx?p=25862&seqNum=7
    /// </summary>
    public class SequentialGuidGenerator
    {
        private int _counter;

        private long GetTicks()
        {
            int i = Interlocked.Increment(ref _counter);
            // use UTC now to prevent conflicts w/ daylight savings
            return DateTime.UtcNow.Ticks + i;
        }

        private readonly byte[] _currentGuidArray;
        private Guid _currentGuid;
        public Guid CurrentGuid
        {
            get { return _currentGuid; }
        }

        public SequentialGuidGenerator()
            :this(Guid.NewGuid())
        {
        }

        public SequentialGuidGenerator(Guid initialGuid)
        {
            _currentGuid = initialGuid;
            _currentGuidArray = initialGuid.ToByteArray();
        }

        public Guid Generate()
        {
            byte[] guidArray = _currentGuidArray;
            long ticks = GetTicks();

            //uid[0] TO uid[6]
            // the first 7 bytes are random - if two combs
            // are generated at the same point in time
            // they are not guaranteed to be sequential.
            // But for every DateTime.Tick there are
            // 72,057,594,037,927,935 unique possibilities so
            // there shouldn't be any collisions       

            // set the first 'nibble of the 7th byte to '1100' so 
            // later we can validate it was generated by us
            guidArray[7] = (byte) (0xc0 | (0xf & guidArray[7]));

            // the last 8 bytes are sequential,
            // these will reduce index fragmentation
            // to a degree as long as there are not a large
            // number of Sequential-Guids generated per millisecond  
            guidArray[8] = (byte)((ticks >> 8) & 0xFF);
            guidArray[9] = (byte)(ticks & 0xFF);
            guidArray[10] = (byte)((ticks >> 8 * 7) & 0xFF);
            guidArray[11] = (byte)((ticks >> 8 * 6) & 0xFF);
            guidArray[12] = (byte)((ticks >> 8 * 5) & 0xFF);
            guidArray[13] = (byte)((ticks >> 8 * 4) & 0xFF);
            guidArray[14] = (byte)((ticks >> 8 * 3) & 0xFF);
            guidArray[15] = (byte)((ticks >> 8 * 2) & 0xFF);
            _currentGuid = new Guid(guidArray);
            return _currentGuid;
        }
    }`

**Comment by Oger-Me** [comment]
nice.

**Comment by liamwang** [comment]
@arespr Thanks for your reply. 
I should google it first. These days I also found several implementations :
* [https://github.com/jhtodd/SequentialGuid](https://github.com/jhtodd/SequentialGuid)
* [https://github.com/richardtallent/RT.Comb](https://github.com/richardtallent/RT.Comb)
* [https://github.com/mrtaikandi/SequentialGuid](https://github.com/mrtaikandi/SequentialGuid)

And this question is nothing about asp.net core identity. I think it should be closed. @HaoK
