### ISSUE TITLE
Sharing auth cookies between MVC5 and MVC 6

### ISSUE THREAD

**Issue by gaborkalmar** [aspnet/Identity#925]
I'm having issues sharing authentication cookies between an mvc5 and an mvc6 application. Both are using .netframework 4.6 , first one is asp.net and the other is .netcore. I've tried this https://docs.asp.net/en/latest/security/data-protection/compatibility/cookie-sharing.html with no luck.

**Comment by HaoK** [comment]
See https://github.com/aspnet/EntityFramework/issues/2167#issuecomment-232205222 as someone was able to get this to work recently

**Comment by gaborkalmar** [comment]
Thanks , i'll check it out  , will report back if I got it working
