### ISSUE TITLE
abstarct UserStore`8 implementation fails to instantiate UserStore 

### ISSUE THREAD

**Issue by maxim-shaw** [aspnet/Identity#927]
I work on custom implementation of identity on PostgreSQL. 
UserStore'4 implementation worked well, but when I added a custom TRole implemetation and implemented UserStore'8 https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/UserStore.cs ln:160
    
    public abstract class UserStore<TUser, TRole, TContext, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken>
    { ... }

Instantiation of Identity service 
    
    services.AddIdentity<ApplicationUser, ApplicationRole>()
        .AddEntityFrameworkStores<DatabaseContext, string>()
        .AddDefaultTokenProviders();
fails with the following exception:

Additional information: GenericArguments[0], 'every1trade.repo.Identity.ApplicationUser', on 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore'4[TUser,TRole,TContext,TKey]' violates the constraint of type 'TUser'.

UserStore'4 class takes a TUser that is inherited from `IdentityUser<TKey>` however for UserStore'8 implementation TUser is inherited from `IdentityUser<TKey, TUserClaim, TUserRole, TUserLogin>` the inheritance that I use. Database context is inherited from `IdentityDbContext<8>`.

`public class DatabaseContext :  IdentityDbContext<ApplicationUser, ApplicationRole, string, ApplicationUserClaim, ApplicationUserRole, ApplicationUserLogin, IdentityRoleClaim<string>, IdentityUserToken<string>>
    { ... }`

Thus UserStore'8 implementation should be instantiated instead of UserStore'4. TUser implementation of UserStore'4 obviously violates signature of `IdentityUser<TKey>`.

**Comment by ttaber** [comment]
See #855 , PR #893 & #918

**Comment by HaoK** [comment]
You also cannot use .AddEntityFrameworkStores<ApplicationDbContext, string>() when you customize everything, you should be able to use AddUserStore/RoleStore instead

**Comment by maxim-shaw** [comment]
@HaoK, thank you for the direction. Replacement of .AddEntityFrameworkStores() with
    
    services.AddIdentity<ApplicationUser, ApplicationRole>()
        .AddUserStore<ApplicationUserStore>()
        .AddRoleStore<ApplicationRoleStore>()
        .AddUserManager<ApplicationUserManager>()
        .AddDefaultTokenProviders();

gave me seeking results.
