### ISSUE TITLE
[Question] Dispose Behavior of UserStore on EF Core Provider

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Identity#929]
AFA I can see, `UserStore` on EF Core provider implements `IDisposable` but it does nothing: https://github.com/aspnet/Identity/blob/47e8e49de8f8fc995114242997d2fc3000648343/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/UserStore.cs#L653-L670 However, it marks the instance as disposed and makes it not usable after dispose. 

Is there any specific reason to this behavior?

**Comment by HaoK** [comment]
Legacy code mostly, in the past I believe this Dispose would have disposed the DbContext potentially, but that code was removed, so its mostly just there to block method calls after the store has been disposed now...
