### ISSUE TITLE
Minor Comment Tweak

### ISSUE THREAD

**Issue by dazinator** [aspnet/Identity#937]
Just wondering if this line should say "Users" rather than "Roles":

https://github.com/aspnet/Identity/blob/4ef80fabf66624b464e77ac9dd6e8c4461759e0c/src/Microsoft.AspNetCore.Identity/IQueryableUserStore.cs#L9

**Comment by HaoK** [comment]
c1b8f3abf39a4856e5f48a20a59ecc14580947a0
