### ISSUE TITLE
Support Auth Apps, preferred over Text Based Auth

### ISSUE THREAD

**Issue by blowdart** [aspnet/Identity#941]
https://nakedsecurity.sophos.com/2016/08/18/nists-new-password-rules-what-you-need-to-know/'

As NIST has now said "Stop using SMS" we should fully support TOTP/authenticator apps, and change the templates to use this, rather than SMS.

**Comment by blowdart** [comment]
And recovery codes.

**Comment by HaoK** [comment]
Not going to make it in this week after discussion with @divega

**Comment by HaoK** [comment]
Since there's no template updates for 1.1, there's no real benefit for rushing this in, will put this in for 1.2 soon as the branches are open

**Comment by HaoK** [comment]
as discussed with @blowdart in security triage

**Comment by HaoK** [comment]
Should address https://github.com/aspnet/Identity/issues/818 as part of this work

**Comment by HaoK** [comment]
Initial feature is in 5aed9742a4f1a35558f5ca644e981398df7017c1 @blowdart give it a try, the sample is updated with the current flow just with authenticator as an additional option (you need to generate a key via manage for it to show up as an option.
