### ISSUE TITLE
Unique role names

### ISSUE THREAD

**Issue by cjcfreitas** [aspnet/Identity#944]
Role names must be unique.
This is enforced by `RoleValidator`.
Shouldn't this be also enforced in the EntityFramework model?
File IdentityDbContext.cs line 170 would be:
`b.HasIndex(r => r.NormalizedName).HasName("RoleNameIndex").IsUnique();`

**Comment by HaoK** [comment]
5d759abcde8e652fa83ad1a7099fffffb53ca648
