### ISSUE TITLE
Things [Authorize] attribute needs to work properly

### ISSUE THREAD

**Issue by piotrek-k** [aspnet/Identity#945]
I want to write my own authorization system which will include custom registration and signin process. I want it to work with ASP.net Identity `[Authorize]` attribute. What should I do to make it work properly? How `[Authorize]` know which controllers can be accessible for users and which not? What properies need to be configured in order to achieve that?

**Comment by blowdart** [comment]
This isn't a question for Identity. Identity is the kind of system you want to write. Authorization is handled not by identity, but by MVC and by the Authorization middleware you find in the security repo. The authorization attribute in MVC looks at the current user. It's up to you to put that user on the context. Samples of that sort of thing can be found in the various authorization middlewares in the Security repo.
