### ISSUE TITLE
Microsoft.AspNetCore.Identity

### ISSUE THREAD

**Issue by GArrigotti** [aspnet/Identity#948]
In the package` "Microsoft.AspNetCore.Identity": "1.0.0-rc2-final"` I don't see `IUser`.  When implementing our `IUserStore<Member>`, do we need to have our POCO inherit `IUser` or not?  I can't find any documentation, otherwise.

**Comment by HaoK** [comment]
There is no IUser in AspNetCore Identity, you no longer have to implement IUser, but your IUserStore needs to implement the equivalent methods that used to live on this interface, GetUserId(TUser), GetUserName(TUser)

**Comment by GArrigotti** [comment]
@HaoK Thank you for that clarification, I thought that might be.  But I figured I'd seek the clarification since I couldn't find the implementation or documentation.  I appreciate your response.
