### ISSUE TITLE
Is it possible getting all the roles of a user in a view?

### ISSUE THREAD

**Issue by gdoron** [aspnet/Identity#949]
e.g.

	@User.GetAllRoles().Any(x => x.StartsWith("Vendor_")
?
I can store the role as a claim and get all the claims that start with {xxx} but that seems less feasible for my needs.

**Comment by blowdart** [comment]
Dupe of #947

**Comment by HaoK** [comment]
UserManager.GetRolesAsync(user) will return you all of the roles for the user.

**Comment by gdoron** [comment]
@HaoK 

I managed to find this way which doesn't require DB queries:

	@User.Claims.Where(x=> x.Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/role")
	
Is there any disadvantages using it?

**Comment by HaoK** [comment]
That should work fine
