### ISSUE TITLE
Token Store Support

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#950]
Token Types by string
Create/Revoke/Expiration

Token Schema:
Id
Value
Type

Identity
1 TOTP key per user
N recovery codes

Per App
N Single Auth code
N Access token
N Refresh token

**Comment by HaoK** [comment]
@blowdart @divega 

Feels like the proper key is ID + type, as opposed to requiring unique ID always, but I'm not entirely convinced...thoughts?

Which leads us to an API that looks something like:
```
   public interface ITokenStore {
        // Create or updates the token (would we need to split these apart into two apis?)
        Task StoreAsync(string id, string type, string value, CancellationToken cancellationToken);
        Task<bool> RemoveAsync(string id, string type, CancellationToken cancellationToken)
        Task<string> GetValueAsync(string id, string type, CancellationToken cancellationToken) 
   }

   // Constraints would be non null id, type and values (but empty would be considered valid)
   // GetValue would return null for tokens that don't exist
```

**Comment by divega** [comment]
It depends. What is this `id`? Is it a key borrowed from some other entity or is it just added to this entity to become the key? If the latter then it should be sufficient by definition.

**Comment by HaoK** [comment]
If we go that route with the id being the key, maybe we should use a POCO
```
public class IdentityToken {
   public string Id { get; set; }
   public string Type { get; set; }
   public string Value { get; set; } 
}

Task StoreAsync(IdentityToken token)
Task<bool> RemoveAsync(string id)
Task<IdentityToken> GetAsync(string id)
```

**Comment by HaoK** [comment]
For usage, I'm imagining we don't need any extra complexity like a manager, we'd just implement the store in Identity.EF, and it would get registered as part of AddEntityFrameworkStores, and consuming it would be up to the developer for 1.1, since we don't have any features that currently use this store (until the templates are updated)

**Comment by divega** [comment]
Could you still answer what the ID represents?

**Comment by HaoK** [comment]
> Could you still answer what the ID represents?
> 
That's sort of the question I am asking. Do we want to make the id the unique key or part of the key. We are deciding what the contract is for consumers. 

It basically boils down to whether we want to make it easy to partition based on token type or not. If we say is must be unique across all token types. We don't even need token type anymore. We can just say that's something that should be in the payload as well since we won't have any APIs that use the type.

**Comment by blowdart** [comment]
ID would be a unique key probably. Nothing you query on. Then there's the property bag too.

We would need token type though, unless you make the token type part of the property bag, because, for example, we'd want to say "Give me all the TOTP reset tokens for user X"

**Comment by HaoK** [comment]
Having the type alone won't help with that since we won't be able to query using user id since that's part of the bag.  

> For example, we'd want to say "Give me all the TOTP reset tokens for user X"

**Comment by blowdart** [comment]
Well true, but you'd get the unique token IDs from the property bag by looking up the user property, then backtrack up.

**Comment by HaoK** [comment]
The main difference between the token server and user ids is here, where the token id is enough for them, while user tokens have the additional filters of type + owner that we will need to query by.

**Comment by HaoK** [comment]
For identity could use these the token store just as a bag with another table in charge of managing token types/payloads.

So maybe: `ITokenStore` for the generic get/set/delete of ID/value token pairs.
`IUserTokenStore` which layers on UserId, TokenType, TokenId which we can use to build our recovery code/whatever we want

**Comment by HaoK** [comment]
We've decided to roll the authenticator info into the existing UserAuthenticationTokenTable
