### ISSUE TITLE
Claims tables id type

### ISSUE THREAD

**Issue by kroniak** [aspnet/Identity#954]
I see that claims to role and claims to user tables have int PK id.

``` c#
modelBuilder.Entity("Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();
                });

modelBuilder.Entity("Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();
                });
```

In other tables uses string GUID PK.

In this case there are no ability to make cross database migrations.

**Comment by blowdart** [comment]
I don't understand what the issue or the question is here? Could you expand?

**Comment by kroniak** [comment]
@blowdart I think this is issue and this tables must have string id. Then we can be move between databases (like PG and SQL) without recreate ef core migrations code.

**Comment by blowdart** [comment]
I don't see why they need to have a string ID. It's a key just used for linking, and changing it would mean a database migration for everyone. 

What database doesn't have integers? I don't see why having an int demands an ef migration.

**Comment by kroniak** [comment]
@blowdart As you see

```c#
 migrationBuilder.CreateTable(
                name: "AspNetUserClaims",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("Npgsql:ValueGeneratedOnAdd", true),
                    ClaimType = table.Column<string>(nullable: true),
                    ClaimValue = table.Column<string>(nullable: true),
                    UserId = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AspNetUserClaims_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });
```

EF Core added ```Npgsql:ValueGeneratedOnAdd``` and ```SqlServer:ValueGeneratedOnAdd``` tags to migration and it cannot moving between databases. On production it tryes pick up dll like EntytityFramaworkCore.SqlServer.

May be it is EF Core issue.

**Comment by blowdart** [comment]
Hey @divega is this an EF issue?

**Comment by kroniak** [comment]
@blowdart @divega There are any information?

**Comment by divega** [comment]
@kroniak can you try adding both annotations in the same migration manually? We don't support scaffolding annotations automatically that will run across multiple databases but if both annotations are present each provider should be able to make sense of the annotations I knows about. AFAIR there is also a provider name property on the builder you can use to execute conditional logic, but I don't think you should need that in this case.

**Comment by kroniak** [comment]
@divers yes, of course I can add this options manually.  I don't understand the logic. in user table, role tables there are string pk, here are int pk. Why?

**Comment by divega** [comment]
`TKey` only controls the type of `UserId` and `RoleId`. Claim entities are the only ones in the model that happens to have its own surrogate key property. I don't know how intentional the choice of `int` for the type was (@HaoK may remember) but whether EF Core migrations would require provider specific annotations for store generated keys was likely not a consideration when the decision was made.

BTW, I think the type is unlikely to change in a point release.

**Comment by HaoK** [comment]
It was somewhat intentional, we picked int mostly because it was easy to autogenerate and also compact. int keys cause migration pain?

**Comment by divega** [comment]
> int keys cause migration pain?

Some. Only if you are trying to have migrations that work across different databases, which is an advanced scenario.
