### ISSUE TITLE
Should IUserStore be disposable?

### ISSUE THREAD

**Issue by rexcfnghk** [aspnet/Identity#957]
From the source I can see that `IUserStore` implements `IDisposable` but I do not think it makes much sense. I believe disposing resources is only a concern by the implementation class and not the interface. For example when I try to implement my own `CustomUserStore` which does not own any disposable resources, I am forced to add an empty `Dispose` method to make sure it compiles.

Am I using `IUserStore` correctly or am I missing something?

**Comment by MorayM** [comment]
For the record I found this issue after Googling to check that I could use disposable entities in an implementation of `IUserStore` so feel I should add my two pence!
You _are_ probably using `IUserStore` correctly, however as my current implementation of it uses various database connection objects which implement `IDisposable` I'm very grateful that it does so I can be sure they're cleared up properly when Identity is finished with them.

**Comment by blowdart** [comment]
Yes. Because, as you can see, other folks might want to dispose things. It's fine to no-op it if you don't need to do anything.
