### ISSUE TITLE
Make it possible to extend/hook Security stamp validation to enable keeping current cookie claims when renewing cookie

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#958]
Vital claims that might only be captured at login time are lost when the security stamp is renewed. The implementation itself even has a comment to review this behavior:

```
var user = await _signInManager.ValidateSecurityStampAsync(context.Principal);
if (user != null)
{
    // REVIEW: note we lost login authenticaiton method
    context.ReplacePrincipal(await _signInManager.CreateUserPrincipalAsync(user));
    context.ShouldRenew = true;
}
```

I'd suggest simply using the current ticket's claims, but replacing the security stamp. If it's deemed that this is not to be changed/fixed, then perhaps add a flag to allow both behaviors?

This came up as part of using ASP.NET Identity within IdentityServer4: https://github.com/IdentityServer/IdentityServer4/issues/277

**Comment by HaoK** [comment]
Yeah the current behavior assumes the UserPrincipalFactory is the source of truth for creating a current up to date principal (we don't want to just refresh the old cookie at all).  Can you just plug in your own derived factory to add the additional claims or are they stored anywhere other than the cookie?

**Comment by brockallen** [comment]
They're dynamic.

Also this behavior of reloading only from the DB behavior will break OIDC federated sign-out behavior given the need to maintain the `sid` claim coming from an external provider:  https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L123

**Comment by HaoK** [comment]
Not at all, this feature is about clearing out security related claims or any other things that might have changed in the user.  I.e. some permission has been revoked, so the cookie must be regenerated as its no longer valid.  The stamp claim is only used to trigger the forced refresh.

**Comment by HaoK** [comment]
We have no way to tell what's sensitive or not, hence the entire cookie needs to be regenerated (which is what the IUserClaimsPrincipal's job is)

**Comment by brockallen** [comment]
The security stamp is only changed on these operations:
* create user
* set username
* remove login
* set/change email
* set/change phone
* set 2fa
* update password

it's not set when claims or roles change, so I'm not sure I agree with this:

> this feature is about clearing out security related claims or any other things that might have changed in the user

so it really seems the security stamp feature is about when the user's credentials change, not when their data changes.

**Comment by HaoK** [comment]
Well the idea is when you want to sign out the user everywhere, you call the public method UpdateSecurityStamp on the UserManager....  So in any admin app which is doing the role changes, it almost certainly would call that method (i.e. almost every operation on a manage page should result in this being called).  

The idea is any time any 'security' (intentionally vague as its app specific) related feature changes, this should be called.  I agree that its intended to be called if just user data changes, as something explicitly had to have triggered the stamp to change.

**Comment by brockallen** [comment]
Regardless of my use case, this still breaks federated sign-out with the OIDC middleware. Perhaps you and @Tratcher could discuss?

**Comment by brockallen** [comment]
Also, something to consider: Make it easier to extend the existing `SecurityStampValidator`. It looks like I can't derive from the existing, and instead have to replicate all of the same logic. Perhaps either some virtuals to break apart the check vs. the replacing the user. Or just move the logic of checking for enough elapsed time into an extension method.

**Comment by brockallen** [comment]
Wait, I just looked again at the implementation in `SecurityStampValidator`. If the validation is successful (meaning the security stamp has not changed), then the user is replaced. So a new cookie is issued even if nothing security related on the account has changed. 

I now get the signout part, but why reissue/replace the claims? That's the "feature" I don't understand.

**Comment by HaoK** [comment]
Its been this way since we added this feature I think (2.0), unfortunately I don't exactly remember the reasoning anymore (regenerate vs reuse).  @blowdart any recollection, basically the behavior we have is, we check every 30 minutes or so, when we check (we either reject the cookie (stamp doesn't match), or we regenerate an fresh principal for the user.  

If I were to guess, this is safest, since if an app forgets to call UpdateSecurityStamp, they will still automatically get protected every 30 minutes or so if anything security critical was changed but the stamp wasn't explicitly invalidated.  Flipping the stamp results in the user having to relog in, while a fresh identity shouldn't be lossy in theory...

**Comment by brockallen** [comment]
Turns out it's impossible to build a custom `IUserClaimsPrincipalFactory` that copies over the claims from the current logged in user, because it's called from within the authenticate phase of the cookie MW. IOW, the cookie mw calls security stamp validator, which calls user manager, which calls my IUserClaimsPrincipalFactory, which tries to call authenticate on the authentication manager, which tries to call into cookie MW. Deadlocks.

**Comment by HaoK** [comment]
You probably have to do it from within a custom security stamp validator, since that has access to both the old principal, and what's going to be the new principal.

**Comment by HaoK** [comment]
To be more precise, not necessarily a custom identity validator, but hook into the same cookie events the security stamp validator is

**Comment by brockallen** [comment]
Right. See my comments about about that.

**Comment by HaoK** [comment]
Sure, we can certainly revisit the validator to make it more reusable as that hasn't gotten any love since it was first written back in the katana days

**Comment by blowdart** [comment]
Don't blame me for 2.0 :) I can't even remember adding this feature.

**Comment by HaoK** [comment]
Sure you do, you and levi did the security review and pushed for sign out
everywhere, which is this feature :)

**Comment by blowdart** [comment]
It was well over a year ago. I can't remember what I did last week. It does seem out to spit out a new cookie.

**Comment by HaoK** [comment]
Well lets say hypothetically we didn't spit out a new cookie every time we
hit the database (every 30 min or so), then even if you removed a user from
the admin role, that would never get reflected in their cookie unless they
signed out...

**Comment by brockallen** [comment]
But if you care about this, then when your admin UI removes them from the admin role you'd also trigger the security stamp being changed. Thus the user would be forced to login again.

**Comment by HaoK** [comment]
Yeah so we would be putting the onus onto the app developer to get it right, this does not seem like something obvious for people to automatically get right...

**Comment by HaoK** [comment]
Its been hard enough for us to get this right :)

**Comment by brockallen** [comment]
Begs the question why this wasn't done automatically in the AddRole APIs.

**Comment by brockallen** [comment]
Yea, I hear security is hard.

**Comment by brockallen** [comment]
Here's an idea: Augment the existing security stamp validator to roll over a list of claims that you can configure on the options.

**Comment by HaoK** [comment]
More likely I will just add an extensibility point where you can hook and do your own thing easier than replacing the whole shindig, you really just want yet another claims transformation point where this one is old principal to new principal, with access to all your stuff

**Comment by brockallen** [comment]
Yea, I guess that'd work. Only issue is DI -- how does the current security stamp validator get it? Another interface in DI just for this?

**Comment by HaoK** [comment]
it'd hang off of IdentityOptions somewhere, always a safe dumping ground :)

**Comment by HaoK** [comment]
this is identity specific anyways, not a general cookie middleware validator

**Comment by brockallen** [comment]
Yea, ok. I guess that'd work.

**Comment by HaoK** [comment]
@brockallen chatted with @Tratcher and we think that the same transformation step that was needed to get the sid into the identity cookie, could be updated to use this new feature to carry over the sid into the new cookie.

**Comment by brockallen** [comment]
What if we need some additional logic to carry over claims beyond the OIDC logic for the sid claim?

**Comment by HaoK** [comment]
Yeah basically since they would have to have been doing something custom to get the sid in there in the first place, they just need to do more to keep it carried over when the validator refresh's the cookie

**Comment by brockallen** [comment]
Ok, so the OIDC MW config will somehow hook into it automatically, but if someone custom must do it they then need to know to include sid in their custom implementation.

**Comment by Tratcher** [comment]
No, he meant that for you to have copied external claims over to the app cookie you already had to hook one identity event. Now there will be another identity event you'll hook up at the same time.

**Comment by HaoK** [comment]
aba7cf96b9ac7c910ee7db5e34fa7cf78516116a
