### ISSUE TITLE
FindByIdAsync should use User key type instead of string?

### ISSUE THREAD

**Issue by JeanCollas** [aspnet/Identity#961]
In IUserStore.cs and UserManager.cs:
Is there a reason why FindById uses a string type?

**Comment by bernatgy** [comment]
As I can see, they have left behind the customization of key types...

**Comment by JeanCollas** [comment]
Indeed, changing the key type doesn't compile (issues with incompatible types).
I had to fork the code to use a custom key type...

**Comment by HaoK** [comment]
Customization of the key types is now only a store concern.  The core identity apis all use string, your store implementation is required to implement string GetUserId(TUser user), so you can still persist the key in whatever type you want, but your store is responsible for doing the stringifcation.
