### ISSUE TITLE
AddRoleManager should support a generic RoleManager?

### ISSUE THREAD

**Issue by snys98** [aspnet/Identity#971]
Case I have some code like this:

```
services.AddIdentity<SiteUser, SiteRole>()
                .AddRoleManager<RoleManager<SiteRole>>()
                .AddEntityFrameworkStores<SiteDbContext>()
                .AddDefaultTokenProviders();
```

notice that the line of `.AddRoleManager<RoleManager<SiteRole>>()` is going to throw an exception of

```Type RoleManager`1 must derive from RoleManager<SiteRole>```

and sure that generic type of `RoleManager<SiteRole>` actually means the type of ``RoleManager`1[SiteRole]``.

I've find out that I was able there is a workaround of making a real type to derive from `RoleManager<SiteRole>`, but maybe it's better to implement it _generically_?

**Comment by HaoK** [comment]
AddIdentity already calls adds a RoleManager service. That method is for adding a derived role manager. 

>

**Comment by snys98** [comment]
Well, but if I didn't add a RoleManager explicitly, an exception of service not found will be thrown.
