### ISSUE TITLE
EF Core stores: Switch to Find[Async]() instead of First[OrDefault][Async]() or Single[OrDefault][Async]() as appropriate

### ISSUE THREAD

**Issue by divega** [aspnet/Identity#975]
`Find()` (added to EF Core in 1.1) can return objects already in memory without performing a database roundtrip. We are also unnecessarily using `SingleOrDefault()` in some cases in comparisons by key which would never return more than one row.

**Comment by divega** [comment]
Yes unless there is not enough time. I assigned it.

**Comment by HaoK** [comment]
@divega does this work only on key's (the userID/roleID), or would it work for things that are unique index'ed, like the NormalizedName queries?

**Comment by divega** [comment]
@HaoK only on primary keys, at least for now.
