### ISSUE TITLE
Consider an approach to allow additional claims to be supplied at login time

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#976]
Perhaps some overload of `SignInAsync` on the `SigninManager` that allows additional claims to be set into the cookie.

I know our prior discussion of the security token stamp validator overwriting the claims somewhat defeats this, but given the fix for that this woul[d sill be a welcome addition.

Backstory: In short, a customer needs to capture additional context at signin time that's not in his identity DB. https://github.com/IdentityServer/IdentityServer4/issues/330

**Comment by HaoK** [comment]
@blowdart thoughts?  Its a cheap overload, the behavior would be that we jam some additional claims on to the `ClaimsPrincipal.Identities.First()` from the ClaimsPrincipalFactory

**Comment by blowdart** [comment]
Seems like a reasonable suggestion.

**Comment by HaoK** [comment]
This is basically the same ask as https://github.com/aspnet/Identity/issues/628, using that issue to track this
