### ISSUE TITLE
No authentication handler is configured to authenticate for the scheme: MyCookieMiddlewareInstance

### ISSUE THREAD

**Issue by MiniverCheevy** [aspnet/Identity#978]
The code in this article

https://docs.asp.net/en/latest/security/authentication/cookie.html

produces interment exceptions.   There is a fix detailed here

http://stackoverflow.com/questions/38968422/no-authentication-handler-is-configured-to-handle-the-scheme

corrects the issue, but it seems like a lot of hoops to jump through.

calling HttpContext.Authentication.SignInAsync will often throw an exception because the HttpContext.Authentication.HttpAuthenticationFeature.Handler is null.  

These are the relevant dependencies from my project.json:

```
"Microsoft.AspNetCore.Diagnostics": "1.0.0",
"Microsoft.AspNetCore.Mvc": "1.0.1",
"Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
"Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
"Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
"Microsoft.Extensions.Configuration.Json": "1.0.0",
"Microsoft.Extensions.Logging.Console": "1.0.0",
"Microsoft.AspNetCore.StaticFiles": "1.0.0",
"Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
```

**Comment by brunopiovan** [comment]
The only difference between your versions and mine when I wrote that fix is Mvc and Kestrel were both 1.0.0.

After investigating a bit more, I changed the code slightly:

```
if (httpContext.Features.Get<IHttpAuthenticationFeature>()?.Handler == null)
{
    var handler = (AuthenticationHandler<CookieAuthenticationOptions>)Activator.CreateInstance(cookieAuthenticationHandlerType);
    await handler.InitializeAsync(Startup.cookieAuthenticationOptions, httpContext, logger, UrlEncoder.Default);

    var feature = httpContext.Features.Get<IHttpAuthenticationFeature>() ?? new HttpAuthenticationFeature();
    if (feature.Handler == null) //yes, sometimes it gets set when this line is reached
    {
        feature.Handler = handler;
        httpContext.Features.Set(feature);
    }
}
```

the comment explains it.

**Comment by Tratcher** [comment]
Can anyone share a sample app (via a github repo) that reproduces this? Especially the MVC controller code.

My only theory is a threading issue because IHttpAuthenticationFeature.Handler is cleaned up towards the end of the response.

**Comment by MiniverCheevy** [comment]
Interestingly enough my sample app doesn't throw the exception.  It has the same basic workflow, javascript post to async controller method, which calls an async command, which makes an async call to authenticate the user, an async call to create the identity, then an async call to sign in. 

I'm simulating the async entity framework calls, am I correct in assuming that using CopyToAsync from a file stream to a memory stream works essentially the same way as a FirstOrDefaultAsync?

**Comment by HaoK** [comment]
Nothing we can do unless we get a repro for this, if this still is happening, feel free to file a new issue with the repro, but in the https://github.com/aspnet/Security repo
