### ISSUE TITLE
Is it possible signing out a user other than the current user?

### ISSUE THREAD

**Issue by gdoron** [aspnet/Identity#979]
Currently when we give a user a new claim-role we need to ask them to signout and and signin again which many times leads to confusion.

Is it possible to force a user to login on Identity core?

For example, something like:

	_signInManager.SignOutAsync("a4342bc-4327ac-123-" /*UserId*/)
	_signInManager.SignOutAsync(applicationUser)

My Googling found nothing 😢

**Comment by brockallen** [comment]
You can update that user's security stamp in the DB. This will trigger signout of any app that honors the security stamp.

**Comment by gdoron** [comment]
@brockallen  thank for the reply Brock.
But I fail to understand how changing a column in the DB is going to force a user to sign-in again?
Identity doesn't go to the DB on every HTTP request.

Can you please explain a bit more?

Thanks mate,
Doron

**Comment by gdoron** [comment]
@brockallen I read the source code of Identity a bit, did you mean using something like:

	if ((await _signInManager.ValidateSecurityStampAsync(User)) == null)
		//...
On every request?

Is there something built-in?  that does it automatically every x minutes?

BTW, @HaoK  this is probably a typo:


    /// <summary>
    /// Get the security stamp for the specified <paramref name="user" />.
    /// </summary>
    
    -----------> /// <param name="user">The user whose security stamp should be **set**.</param> 
    
    /// <returns>The <see cref="T:System.Threading.Tasks.Task" /> that represents the asynchronous operation, containing the security stamp for the specified <paramref name="user" />.</returns>
    public virtual async Task<string> GetSecurityStampAsync(TUser user)

Seems like a copy-paste error, nothing here should be set if I'm not mistaken.

**Comment by brockallen** [comment]
It is done automatically: https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/IdentityCookieOptions.cs#L36

**Comment by gdoron** [comment]
@brockallen
Thanks Brock, you surely helped me a lot!

BTW, can I have different intervals based on the role?
For admin for example I would want it to run every 5 minutes while for normal user I wouldn't mind it be much higher.

**Comment by brockallen** [comment]
You'd need to build your own at that point.
