### ISSUE TITLE
Can't inherit BaseEntity and IdentityUser for ApplicationUser

### ISSUE THREAD

**Issue by viennv1709** [aspnet/Identity#980]
With the current implementation of ASP.NET Core Identity. I can't create an ApplicationUser class that inherit from the IdentityUser class and the custom BaseEntity class.

**Comment by HaoK** [comment]
You don't have to inherit from IdentityUser unless you are using our EF User Store.  If its not possible to make BaseEntity derive from IdentityUser, you can always write your own UserStore implementation (reusing most of the code from ours)
