### ISSUE TITLE
How to Add custom field to aspnetUserClaim table

### ISSUE THREAD

**Issue by BehnamAbdy** [aspnet/Identity#982]
I need to add a custom field to aspnetuseclaim table.I know some how I must inherit the IdentityUseClaim<> and do the customization but doing it and make the identity context to use this class is not that easy. Can any one help me with sample!!

**Comment by HaoK** [comment]
See https://github.com/aspnet/Identity/blob/dev/test/Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test/UserStoreWithGenericsTest.cs#L87
