### ISSUE TITLE
Can't extend user store

### ISSUE THREAD

**Issue by TonyBarnett** [aspnet/Identity#984]
Should this not be `IUserStore` and `IRoleStore`? https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityEntityFrameworkBuilderExtensions.cs#L50 

As it stands it means I cannot use a custom user store unless it inherits from UserStore (which it cannot).

**Comment by HaoK** [comment]
This is correct, if you cannot derive from our UserStore/RoleStore, then you need to just implement the interfaces yourself, and you probably don't need to use the Identity.EntityFrameworkCore package at all in that case.
