### ISSUE TITLE
Should AddIdentity throw if called more than once?

### ISSUE THREAD

**Issue by HaoK** [aspnet/Identity#985]
See for some bad unexpected things that can happen: https://github.com/aspnet/Identity/issues/972

Basically we don't really support it, so should we try to block it?  Throw if a AddIdentity is called a second time(we can just look for our Marker interface basically)

Thoughts? @divega @blowdart

**Comment by divega** [comment]
Would it be easy to make it idempotent? e.g. do we have places in which we could replace Add with TryAdd methods?

**Comment by HaoK** [comment]
AddIdentity is fine, its the Configure of the options, they SHARE options (since its singleton), which is 100% not what people would expect, that you get the union of all of the AddIdentity options configurations, with last one winning...

**Comment by HaoK** [comment]
Meaning, the services we add are fine in AddIdentity, those are already all TryAdds and safe

**Comment by blowdart** [comment]
Throw

**Comment by divega** [comment]
Agreed.

**Comment by HaoK** [comment]
This is probably technically a breaking change, still ok for 1.1?

**Comment by divega** [comment]
Fair enough, it is a breaking change if customers can reasonably have things working with this setup today. We need to understand:

- How common this is.
- Are there legitimate reasons to have things setup this way or are we convinced it is not a valid scenario? If it is a valid scenario we may consider a pattern to allow independent options to be configured (e.g. we solved this problem in EF Core with generic options).

Then we can decide what to do for 1.1.

**Comment by HaoK** [comment]
I doubt its very common, but given that we've already seen one example of someone doing this, its certainly possible today if they have multiple user entity types, and are using identity to access them.  That said, if they are careful and either avoided or worked around any issues that arose from all instances of UserManager's sharing the same identity options, it would work...

**Comment by HaoK** [comment]
That said, even if we were to block AddIdentity from being called more than once, anyone who was relying on this before would still be able to work around the block by manually adding the services that AddIdentity does.
