### ISSUE TITLE
Question - user gets auto logged off.

### ISSUE THREAD

**Issue by RLaptev** [aspnet/Identity#987]
I'm using all the latest libraries of AspNetCore, including Identity 3.0 but without the Entity Framework. Authentication works perfectly, the client receives an authentication cookie (expiring in default 14 days). Consecutive requests to the site return true for both User.Identity.IsAuthenticated and SignInManager.IsSignedIn. After about 5 minutes of inactivity, request to the same page would return false for the above two methods, and I can see that 3 cookies are being deleted by the first server response - Identity.Application (my authentication cookie), Identity.External and Identity.TwoFactorUserId. What would cause Identity to “auto logoff” current user, even though the authentication cookie is set to expire in 2 weeks?

Thank you.

**Comment by HaoK** [comment]
The security stamp validator could cause this behavior, make sure that your users have a security stamp set

**Comment by RLaptev** [comment]
Thank you, thank you!
You steered me in the right direction. My user object did have the SecurityStamp set, but I was missing SecurityStamp claim under `Task<ClaimsPrincipal> CreateAsync`. Adding the line below fixed the problem. Thanks again!

`identity.AddClaim(new Claim("AspNet.Identity.SecurityStamp", user.SecurityStamp));`
