### ISSUE TITLE
Q: Authorization expiration

### ISSUE THREAD

**Issue by shutdown256** [aspnet/Identity#992]
In my SPA I have problem with user login expiration I've set signin persistent = true, ApplicationCookie.SlidingExpiration = true and AddDataProtection().PersistKeysToFileSystem(), but during testing I get signed-out quite often at (seemingly) random intervals. This is obviously bad for SPA where I need to do a lot of fetch/ajax reqs. - is there a way to know when will user auth expire or at least detect expiration during validation (signManager.IsSignedIn()) so I can send message to client instead of plain UNAUTHORIZED ACCESS?

**Comment by blowdart** [comment]
What are you trying to do setting both persistent and slidingexpiration? Those are mutually exclusive options.

**Comment by shutdown256** [comment]
My bad, which one of them should I use? Even so is there a good way/how to deal with expired sign-in in SPA?

**Comment by blowdart** [comment]
Well it depends what you're trying to do, Using cookies with SPA is generally not a great idea, because of CSRF. If you limit yourself to sliding, then with each request the cookie expiry will extend (kind of, it's every few requests)

**Comment by shutdown256** [comment]
I think I figured it out. Several mistakes on my part.
