### ISSUE TITLE
Q: IdentityDbContext in WebSite and MyProjectDbContext in separate assembly sharing a table

### ISSUE THREAD

**Issue by cedric-cazin** [aspnet/Identity#993]
Hello

I have a Web Site with of course an `ApplicationDbContext : IdentityDbContext<ApplicationUser>`
where my ApplicationUser is : 
```C#
    public class ApplicationUser : IdentityUser
    {
        public MyProject.Models.UserInfo UserInfo { get; set; }
    }
```
UserInfo come from MyProject.Models (where I have a MyProjectDbContext) because it used by other project (Web Services, Windows Services...) and is also joined to other table, mainly in history tables...
I wish to keep the ApplicationDbContext (IdentityDbContext) in the web site, and have a separate assembly for my Models.
The pb is that the migration failed because the table UserInfo is in both assembly

Is there a way to do that ?
or 
do I have to move the ApplicationDbContext (IdentityDbContext) in my model assembly ?

**Comment by blowdart** [comment]
@divega

**Comment by ajcvickers** [comment]
Sorry for being slow responding--we had some internal team changes. This can be done, but requires that you choose one context that will manage the UserInfo table through Migrations and manually remove anything generated for it by the other context. More info and a better experience for this is tracked by https://github.com/aspnet/EntityFrameworkCore/issues/2725
