### ISSUE TITLE
ASP.NET Core policy based authorization with windows logged in user

### ISSUE THREAD

**Issue by raymak23** [aspnet/Identity#997]
Hello,

I am creating policy base authorization and would like to allow multiple users in one policy to access webpage.

I created policy like shown below in start up file. Question, How can I use multiple usernames in one policy? I looked at the method for` .RequireUserName`, it is only accepting `string username`.

Policy name`AdminServiceAccount` is mostly I am interested in to add multiple users. If I use `param` `.RequireUserName("DOMAIN\\USER1,DOMAIN\\USER2")` will it work? I don't think so, but wanted to check if there is an alternative way. 

```
services.AddAuthorization(
                    option =>
                    {
                        option.AddPolicy("Admin", policy => policy.RequireRole("Domain\\GroupName"));
                        option.AddPolicy("SuperAdminUser", policy => policy.RequireUserName("DOMAIN\\SuperAdminUser"));
                        option.AddPolicy("AdminServiceAccount", policy => policy.RequireUserName("DOMAIN\\USER1"));
                    }
            );
```

**Comment by blowdart** [comment]
This is not an identity question, it should be in the Security repo. You should look at [my workshop](https://github.com/blowdart/AspNetAuthorizationWorkshop), you need to do this in a custom code based policy. If that's not clear log an issue in the [security repo](https://github.com/aspnet/Security/issues).
