### ISSUE TITLE
Incorrect userId when UserManager invokes UserStore.FindByIdAsync

### ISSUE THREAD

**Issue by jgauffin** [aspnet/Identity#998]
I'm trying to write a custom UserStore/RoleStore and am struggling. This might as well be my error, but am having a hard time to figure out what in that case.

**Background**

There are several questions at StackOverflow about getting the user id when using ASP.NET Identity. Most of them resolve around parsing the `NameIdentifier` claim.

However, most of them seem to miss an import point. When using OAuth the `NameIdentifier` seem to point at the identity that the OAuth provider returned.

This can be observed by setting a break point in the AccountController just after the authentication finished.

**My problem**

If you look at the UserStore you can see that `GetUserIdAsync` will return the `Id` of the `IdentityUser` object which is your internal id from the database. All good so far.

However, if you look at the [UserManager<T>][1] it got the following code:

    /// <summary>
    /// Returns the User ID claim value if present otherwise returns null.
    /// </summary>
    /// <param name="principal">The <see cref="T:System.Security.Claims.ClaimsPrincipal" /> instance.</param>
    /// <returns>The User ID claim value, or null if the claim is not present.</returns>
    /// <remarks>The User ID claim is identified by <see cref="F:System.Security.Claims.ClaimTypes.NameIdentifier" />.</remarks>
    public virtual string GetUserId(ClaimsPrincipal principal)
    {
      if (principal == null)
    	throw new ArgumentNullException("principal");
      return principal.FindFirstValue(this.Options.ClaimsIdentity.UserIdClaimType);
    }

.. which looks just fine on the first peak. But if you look at the constant value for `UserIdClaimType` it's the same as `ClaimTypes.NameIdentifier`. Thus it will fetch the oauth user id.

Code that wont work due to the above problem:

    //this returns the oauth id, can't be used to work with the application account
    var id = await _userManager.GetUserIdAsync(currentClaimPrincipal);
    
    //this returns null as it internally uses the above line
    await user = _userManager.GetUserAsync(currentClaimPrincipal);

The code above will invoke `UserStorage.FindByIdAsync` with the oath user id as user id. the user store will therefore try to find the application account by using the incorrect key. It will of course return `null`.

A hack would be to use the oAuth userId as the PK in the local user table, but that can break if two oauth providers return the same id (not unlikely). And it won't work if multiple oauth accounts are associated to the same application user account.

This is confusing. `userId` should mean one thing and only one thing in all the identity classes like SigninManager, UserManager and UserStore. You should also state more explicitly which claims are required to be able to map oauth accounts to the application account.

  [1]: https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UserManager.cs

**Comment by jgauffin** [comment]
From my point of view there are two solutions:

1. Let `ClaimsIdentity.UserIdClaimType` be a unique claim and not reference `NameIdentifier`. Make sure that it's set to the id of the application/identity user.
2. Change `UserManager.GetUserId(ClaimPrincipal)` and `UserManager.GetUserAsync(ClaimPrincipal)` so they use `UserStore.FindByLoginAsync`

**Comment by HaoK** [comment]
You shouldn't be calling GetUserId with the claims principal from an OAuth provider. The only ClaimsPrincipal that should be used with that is one generated via the ClaimsPrincipalUserFactory that identity uses. Associating OAuth with the local user is usually done via the AddLogin method which links the OAuth id to the local user id.

**Comment by jgauffin** [comment]
My point was that a custom PrincipalFactory and a custom UserManager wouldn't have been required if you had included the userId as a claim per default. I mean, you have the `ClaimsIdentity.UserIdClaimType` and you have a method in the `UserStore` to get the userId. Why not combine them to make it more straight forward to create custom stores?

`ClaimTypes.NameIdentifier` already exist, so why have to different constants for the same claim?

**Comment by jgauffin** [comment]
I saw that the default ClaimsFactory do assign the identity user id to the NameIdentifier.  My own claimsfactory is also invoked. But when `_signInManager.ExternalLoginSignInAsync` have completed the generated principal is nowhere to be found.

Where is it assigned to the current context? I've tried to follow the pipeline and I can see that the SigninManager creates it, but when `_myContext.HttpContext.Authentication.SignInAsync` have been invoked from it it doesn't seem like its been assigned to anything.

How can I verify that it's actually been used?

**Comment by HaoK** [comment]
The flow is a bit involved, have you stepped through a working normal template flow (MVC/Individual Auth) that does external logins?

Which looks something like: https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Controllers/AccountController.cs#L152

There's basically two claims principals (the identity/application identity, and another external identity which has nothing to do with the former, except for using some of the claims to lookup things in the database)

**Comment by jgauffin** [comment]
Yes, I'm using the default AccountController.

In `ExternalLoginCallback` the `_signInManager.GetExternalLoginInfoAsync` returns the oauth claimsidentity which seems correct.

the claimsfactory is invoked when the `ExternalLoginSignInAsync` method is executing. But once it completes I cannot find the created ClaimsPrincipal anywhere.

I had originally not changed anything but the `UserStore` and `RoleStore`. Due to debugging I've added my own UserManager and SigninManager just to be able to debug method calls.

How can I investigate further where, and if, the created application user principal is assigned?

**Comment by HaoK** [comment]
It doesn't get assigned until the next request, you should see the application cookie being set on the response where you did a signIn, and the next request should result in HttpContext.User having the claims principal

**Comment by jgauffin** [comment]
I need to do some post processing in the AccountController for the authenticated identity user. Is there no way to retrieve it? I need to be able to get the application user id.

(I'm my specific case I need to store a token for the authenticated user in the database to be able to use single sign-on for multiple domains).

**Comment by HaoK** [comment]
You can call FindByLogin using the external login to get the user instance out

**Comment by jgauffin** [comment]
true. thanks.
